import { ACCOUNT_CODES, DEFAULT_CHART_OF_ACCOUNTS } from "@loan/accounting";
import { Prisma } from "@prisma/client";
import type { PrismaClient } from "@prisma/client";
import { describe, expect, it } from "vitest";

import { LoanRepository } from "./loan.repository";

/**
 * GOLDEN TESTS — payment allocation as `LoanRepository.recordPayment`
 * actually persists and posts it.
 *
 * Written against the CURRENT implementation and committed passing BEFORE
 * it is touched, per §81. `posting.allocation.golden.test.ts` pins the
 * arithmetic; this file pins what reaches the database and the ledger — the
 * two schedule progress columns, the moment an instalment flips to paid,
 * the journal credits, and whether the loan closes.
 *
 * READ THIS BEFORE CHANGING A NUMBER IN THIS FILE. Every figure here is a
 * peso figure a borrower would recognise. The §26 work adds fee and penalty
 * tiers ahead of interest and makes the order configurable; a loan on the
 * existing order must come through it with these numbers unchanged, and
 * that claim is only worth something because these were committed first.
 *
 * ── What the current implementation does, exactly ───────────────────────
 *
 * `recordPaymentUnsafe`, in one transaction:
 *
 *   1. Resolves the loan by id or number; throws `LoanNotPayableError`
 *      unless the status is DISBURSED / ACTIVE / DEFAULTED / WRITTEN_OFF.
 *   2. Inserts the `LoanPayment` row.
 *   3. Reads every `LoanSchedule` with `paidInFullAt: null`, ordered by
 *      `installmentNo` ascending.
 *   4. Calls `allocatePayment(Number(input.amount), …)` — see the float
 *      note below — mapping each open row to
 *      `{ interestDue, principalDue, interestPaid, principalPaid }`, all
 *      through `Number()`.
 *   5. For each returned slice, writes back
 *        interestPaid  = round2(Number(row.interestPaid)  + slice.interest)
 *        principalPaid = round2(Number(row.principalPaid) + slice.principal)
 *        paidInFullAt  = settled ? input.paidOn : null
 *      where
 *        settled = interestPaid  + 0.005 >= Number(row.interestDue)
 *              AND principalPaid + 0.005 >= Number(row.principalDue)
 *      Rows that received no slice are not visited at all.
 *   6. Posts one journal entry — `badDebtRecoveryEntry` when the loan is
 *      WRITTEN_OFF, otherwise `loanPaymentEntry` with the interest,
 *      principal and overpayment portions.
 *   7. Closes the loan (status CLOSED, `closedAt` now) when the schedule is
 *      non-empty, nothing is left open, and it was not already CLOSED.
 *
 * ── The settlement threshold, stated precisely ──────────────────────────
 *
 * `paid + 0.005 >= due` is `paid >= due - 0.005`. Both sides are read from
 * `Decimal(14, 2)` columns and `round2` keeps the left side at two
 * decimals, so across the whole domain of representable values the epsilon
 * is INERT: `due - 0.01` fails, `due` passes, and there is no representable
 * value in between. It is a float-tolerance guard that the column types
 * have already made unreachable. The tests below pin the observable
 * consequence — a centavo short does not settle, the exact figure does —
 * rather than the epsilon itself, so the guard can be kept, dropped, or
 * expressed in Decimal without any of them moving.
 *
 * Both conditions are ANDed and evaluated per instalment independently:
 * interest fully collected AND principal fully collected.
 *
 * ── The float note (§11) ────────────────────────────────────────────────
 *
 * Step 4 converts the payment amount and all four per-row Decimals to JS
 * floats before allocating, and `round2` discards the representation error
 * long before half a centavo. Nothing is wrong today — that is exactly what
 * this file is here to hold true while the conversion is removed.
 *
 * The fixture therefore stores `Prisma.Decimal`, as Postgres `NUMERIC(14,2)`
 * does, and the assertions compare through `money()` — a 2-decimal string —
 * so they read the same whether the implementation hands back a float or a
 * Decimal. A golden test that only passed for one of the two would prove
 * nothing about the change from one to the other.
 *
 * ── The schedule ────────────────────────────────────────────────────────
 *
 * ₱50,000.00 over 6 monthly instalments at 18% p.a., declining balance —
 * generated by the same `computeAmortizationFor` that writes production
 * `LoanSchedule` rows.
 *
 *   #   principalDue   interestDue   totalDue
 *   1      8,026.26        750.00     8,776.26
 *   2      8,146.65        629.61     8,776.26
 *   3      8,268.85        507.41     8,776.26
 *   4      8,392.89        383.37     8,776.26
 *   5      8,518.78        257.48     8,776.26
 *   6      8,646.57        129.70     8,776.27   ← absorbs the rounding drift
 *   ───────────────────────────────────────────
 *      50,000.00      2,657.57    52,657.57
 */

// ─── Fixture schedule ─────────────────────────────────────────────────────

const ROWS: Array<{ principalDue: string; interestDue: string }> = [
  { principalDue: "8026.26", interestDue: "750.00" },
  { principalDue: "8146.65", interestDue: "629.61" },
  { principalDue: "8268.85", interestDue: "507.41" },
  { principalDue: "8392.89", interestDue: "383.37" },
  { principalDue: "8518.78", interestDue: "257.48" },
  { principalDue: "8646.57", interestDue: "129.70" },
];

const TOTAL_DUE = "52657.57";
const TOTAL_INTEREST = "2657.57";
const TOTAL_PRINCIPAL = "50000.00";

/** A real uuid, so `idOrNumberWhere` routes it to `{ id }`. */
const LOAN_ID = "3f1c9e02-6b47-4d5a-9c18-7a2e5b0d4c93";
const LOAN_NUMBER = "LN-2026-000042";
const OFFICER = "user-golden-1";

/**
 * Normalises a money value to a 2-decimal string, whatever it arrives as —
 * JS number today, `Prisma.Decimal` after the §11 fix. This is what keeps
 * the assertions below valid across that change.
 */
function money(v: unknown): string {
  if (v === null || v === undefined) return "null";
  return new Prisma.Decimal(v as Prisma.Decimal.Value).toFixed(2);
}

// ─── Decimal-faithful Prisma double ───────────────────────────────────────

interface Row {
  id: string;
  loanId: string;
  installmentNo: number;
  dueDate: Date;
  principalDue: Prisma.Decimal;
  interestDue: Prisma.Decimal;
  totalDue: Prisma.Decimal;
  principalPaid: Prisma.Decimal;
  interestPaid: Prisma.Decimal;
  paidInFullAt: Date | null;
}

interface Line {
  accountId: string;
  debit: number;
  credit: number;
}

interface Entry {
  id: string;
  number: string;
  source: string;
  sourceRefId: string | null;
  lines: Line[];
}

class Db {
  loans: Array<{
    id: string;
    number: string;
    status: string;
    closedAt: Date | null;
  }> = [];
  schedules: Row[] = [];
  payments: Array<{ id: string; amount: unknown }> = [];
  entries: Entry[] = [];
  accounts = DEFAULT_CHART_OF_ACCOUNTS.map((a) => ({
    id: `acct-${a.code}`,
    code: a.code,
    active: true,
  }));
  periods: Array<{ id: string; year: number; month: number; status: string }> =
    [];
  private seq = 0;

  nextId(p: string): string {
    this.seq += 1;
    return `${p}-${this.seq}`;
  }

  inst(no: number): Row {
    const r = this.schedules.find((s) => s.installmentNo === no);
    if (!r) throw new Error(`no instalment ${no}`);
    return r;
  }

  /** Total credited to an account code across every entry posted so far. */
  credited(code: string): string {
    const id = this.accounts.find((a) => a.code === code)?.id;
    return money(
      this.entries
        .flatMap((e) => e.lines)
        .filter((l) => l.accountId === id)
        .reduce((s, l) => s + l.credit, 0),
    );
  }

  /** Total debited to an account code across every entry posted so far. */
  debited(code: string): string {
    const id = this.accounts.find((a) => a.code === code)?.id;
    return money(
      this.entries
        .flatMap((e) => e.lines)
        .filter((l) => l.accountId === id)
        .reduce((s, l) => s + l.debit, 0),
    );
  }

  /** Credits to an account code on the entry posted for one payment. */
  creditedFor(paymentId: string, code: string): string {
    const id = this.accounts.find((a) => a.code === code)?.id;
    const e = this.entries.find((x) => x.sourceRefId === paymentId);
    if (!e) return "0.00";
    return money(
      e.lines
        .filter((l) => l.accountId === id)
        .reduce((s, l) => s + l.credit, 0),
    );
  }
}

function makeClient(db: Db): PrismaClient {
  const client = {
    $transaction: async (fn: (tx: unknown) => Promise<unknown>) => fn(client),

    loanApplication: {
      findFirst: async ({
        where,
      }: {
        where: { id?: string; number?: string };
      }) =>
        db.loans.find((l) =>
          where.id !== undefined
            ? l.id === where.id
            : l.number === where.number,
        ) ?? null,
      update: async ({
        where,
        data,
      }: {
        where: { id: string };
        data: Record<string, unknown>;
      }) => {
        const l = db.loans.find((x) => x.id === where.id)!;
        Object.assign(l, data);
        return l;
      },
    },

    loanPayment: {
      findUnique: async () => null,
      create: async ({ data }: { data: { amount: unknown } }) => {
        const row = { id: db.nextId("pay"), ...data };
        db.payments.push(row);
        return row;
      },
    },

    loanSchedule: {
      /*
       * Returns `Prisma.Decimal`, exactly as Postgres NUMERIC(14,2) does.
       * The existing payments test hands back plain numbers, which means it
       * never exercises the `Number(decimal)` conversion that §11 is about.
       */
      findMany: async ({ where }: { where: { loanId: string } }) =>
        db.schedules
          .filter((s) => s.loanId === where.loanId && s.paidInFullAt === null)
          .sort((a, b) => a.installmentNo - b.installmentNo),
      update: async ({
        where,
        data,
      }: {
        where: { id: string };
        data: Record<string, unknown>;
      }) => {
        const r = db.schedules.find((s) => s.id === where.id)!;
        // Store back whatever the repository wrote, unconverted — the
        // assertions normalise, so a float and a Decimal both survive here.
        Object.assign(r, data);
        return r;
      },
      count: async ({
        where,
      }: {
        where: { loanId: string; paidInFullAt?: null };
      }) =>
        db.schedules.filter(
          (s) =>
            s.loanId === where.loanId &&
            (!("paidInFullAt" in where) || s.paidInFullAt === null),
        ).length,
    },

    account: {
      findMany: async ({ where }: { where: { code: { in: string[] } } }) =>
        db.accounts.filter((a) => where.code.in.includes(a.code)),
    },

    accountingPeriod: {
      upsert: async ({
        where,
      }: {
        where: { year_month: { year: number; month: number } };
      }) => {
        const { year, month } = where.year_month;
        let p = db.periods.find((x) => x.year === year && x.month === month);
        if (!p) {
          p = { id: db.nextId("period"), year, month, status: "OPEN" };
          db.periods.push(p);
        }
        return p;
      },
    },

    journalEntry: {
      findFirst: async ({
        where,
      }: {
        where: { sourceRefId?: string; source?: string };
      }) => {
        if (where.sourceRefId) {
          return (
            db.entries.find(
              (e) =>
                e.sourceRefId === where.sourceRefId &&
                e.source === where.source,
            ) ?? null
          );
        }
        return (
          [...db.entries].sort((a, b) => b.number.localeCompare(a.number))[0] ??
          null
        );
      },
      create: async ({
        data,
      }: {
        data: Record<string, unknown> & { lines: { create: Line[] } };
      }) => {
        const e: Entry = {
          id: db.nextId("je"),
          number: data.number as string,
          source: data.source as string,
          sourceRefId: (data.sourceRefId as string) ?? null,
          lines: data.lines.create,
        };
        db.entries.push(e);
        return e;
      },
    },
  };
  return client as unknown as PrismaClient;
}

/** Seeds one ACTIVE loan carrying the six-row schedule above. */
function seed(status = "ACTIVE"): { db: Db; repo: LoanRepository } {
  const db = new Db();
  db.loans.push({ id: LOAN_ID, number: LOAN_NUMBER, status, closedAt: null });
  ROWS.forEach((r, i) => {
    db.schedules.push({
      id: `sched-${i + 1}`,
      loanId: LOAN_ID,
      installmentNo: i + 1,
      dueDate: new Date(Date.UTC(2026, 3 + i, 1)),
      principalDue: new Prisma.Decimal(r.principalDue),
      interestDue: new Prisma.Decimal(r.interestDue),
      totalDue: new Prisma.Decimal(r.principalDue).plus(r.interestDue),
      principalPaid: new Prisma.Decimal(0),
      interestPaid: new Prisma.Decimal(0),
      paidInFullAt: null,
    });
  });
  return { db, repo: new LoanRepository(makeClient(db)) };
}

/** Pays `amount` — passed as a Decimal, as the API layer does. */
function pay(repo: LoanRepository, amount: string, day = 1) {
  return repo.recordPayment(LOAN_ID, {
    amount: new Prisma.Decimal(amount) as unknown as number,
    paidOn: new Date(Date.UTC(2026, 3, day)),
    recordedById: OFFICER,
  });
}

/** Every posted entry balances to the centavo, individually. */
function expectBalanced(db: Db) {
  for (const e of db.entries) {
    const d = e.lines.reduce((s, l) => s + l.debit, 0);
    const c = e.lines.reduce((s, l) => s + l.credit, 0);
    expect(money(d)).toBe(money(c));
  }
}

// ─── Exact payment of one instalment ──────────────────────────────────────

describe("recordPayment — exact payment of instalment 1 (₱8,776.26)", () => {
  it("writes 750.00 interest and 8,026.26 principal onto the row", async () => {
    const { db, repo } = seed();
    await pay(repo, "8776.26");

    expect(money(db.inst(1).interestPaid)).toBe("750.00");
    expect(money(db.inst(1).principalPaid)).toBe("8026.26");
  });

  it("flips the row to paid on the payment date", async () => {
    const { db, repo } = seed();
    await pay(repo, "8776.26", 5);
    expect(db.inst(1).paidInFullAt).toEqual(new Date(Date.UTC(2026, 3, 5)));
  });

  it("leaves instalment 2 completely untouched", async () => {
    const { db, repo } = seed();
    await pay(repo, "8776.26");
    expect(money(db.inst(2).interestPaid)).toBe("0.00");
    expect(money(db.inst(2).principalPaid)).toBe("0.00");
    expect(db.inst(2).paidInFullAt).toBeNull();
  });

  it("posts 750.00 interest income and 8,026.26 against the receivable", async () => {
    const { db, repo } = seed();
    await pay(repo, "8776.26");

    expect(db.debited(ACCOUNT_CODES.CASH)).toBe("8776.26");
    expect(db.credited(ACCOUNT_CODES.INTEREST_INCOME)).toBe("750.00");
    expect(db.credited(ACCOUNT_CODES.LOANS_RECEIVABLE)).toBe("8026.26");
    expect(db.credited(ACCOUNT_CODES.CUSTOMER_ADVANCES)).toBe("0.00");
    expectBalanced(db);
  });

  it("does not close a loan with five instalments still open", async () => {
    const { db, repo } = seed();
    await pay(repo, "8776.26");
    expect(db.loans[0]!.status).toBe("ACTIVE");
    expect(db.loans[0]!.closedAt).toBeNull();
  });
});

// ─── Partial payment ──────────────────────────────────────────────────────

describe("recordPayment — partial payment (₱5,000.00)", () => {
  it("takes the interest in full, then 4,250.00 of principal", async () => {
    const { db, repo } = seed();
    await pay(repo, "5000.00");

    expect(money(db.inst(1).interestPaid)).toBe("750.00");
    expect(money(db.inst(1).principalPaid)).toBe("4250.00");
  });

  it("leaves the row open — 3,776.26 of principal still owing", async () => {
    const { db, repo } = seed();
    await pay(repo, "5000.00");

    expect(db.inst(1).paidInFullAt).toBeNull();
    // Stated through `money()` on both sides so the subtraction reads the
    // same whether the repository wrote back a float or a Decimal.
    const owing = new Prisma.Decimal(money(db.inst(1).principalDue)).minus(
      money(db.inst(1).principalPaid),
    );
    expect(owing.toFixed(2)).toBe("3776.26");
  });

  it("posts exactly what was received, split 750.00 / 4,250.00", async () => {
    const { db, repo } = seed();
    await pay(repo, "5000.00");

    expect(db.debited(ACCOUNT_CODES.CASH)).toBe("5000.00");
    expect(db.credited(ACCOUNT_CODES.INTEREST_INCOME)).toBe("750.00");
    expect(db.credited(ACCOUNT_CODES.LOANS_RECEIVABLE)).toBe("4250.00");
    expectBalanced(db);
  });

  it("recognises the interest once across two partials, not twice", async () => {
    const { db, repo } = seed();
    await pay(repo, "5000.00", 1);
    const second = await pay(repo, "3000.00", 10);

    // The second payment finds interestOpen at 0 — it is all principal.
    expect(db.creditedFor(second.id, ACCOUNT_CODES.INTEREST_INCOME)).toBe(
      "0.00",
    );
    expect(db.creditedFor(second.id, ACCOUNT_CODES.LOANS_RECEIVABLE)).toBe(
      "3000.00",
    );
    expect(money(db.inst(1).interestPaid)).toBe("750.00");
    expect(money(db.inst(1).principalPaid)).toBe("7250.00");
    expect(db.inst(1).paidInFullAt).toBeNull();
  });
});

// ─── Overpayment spanning instalments ─────────────────────────────────────

describe("recordPayment — a payment spanning instalments (₱20,000.00)", () => {
  it("settles #1 and #2 and part-pays #3", async () => {
    const { db, repo } = seed();
    await pay(repo, "20000.00");

    expect(money(db.inst(1).interestPaid)).toBe("750.00");
    expect(money(db.inst(1).principalPaid)).toBe("8026.26");
    expect(db.inst(1).paidInFullAt).not.toBeNull();

    expect(money(db.inst(2).interestPaid)).toBe("629.61");
    expect(money(db.inst(2).principalPaid)).toBe("8146.65");
    expect(db.inst(2).paidInFullAt).not.toBeNull();

    // #3 takes its interest in full, then 1,940.07 of principal.
    expect(money(db.inst(3).interestPaid)).toBe("507.41");
    expect(money(db.inst(3).principalPaid)).toBe("1940.07");
    expect(db.inst(3).paidInFullAt).toBeNull();

    expect(db.inst(4).paidInFullAt).toBeNull();
    expect(money(db.inst(4).interestPaid)).toBe("0.00");
  });

  it("posts 1,887.02 interest and 18,112.98 principal", async () => {
    const { db, repo } = seed();
    await pay(repo, "20000.00");

    expect(db.debited(ACCOUNT_CODES.CASH)).toBe("20000.00");
    expect(db.credited(ACCOUNT_CODES.INTEREST_INCOME)).toBe("1887.02");
    expect(db.credited(ACCOUNT_CODES.LOANS_RECEIVABLE)).toBe("18112.98");
    expect(db.credited(ACCOUNT_CODES.CUSTOMER_ADVANCES)).toBe("0.00");
    expectBalanced(db);
  });
});

describe("recordPayment — overpayment clearing the whole book (₱53,000.00)", () => {
  it("settles all six instalments to their exact dues", async () => {
    const { db, repo } = seed();
    await pay(repo, "53000.00");

    for (let n = 1; n <= 6; n++) {
      expect(money(db.inst(n).interestPaid)).toBe(
        new Prisma.Decimal(ROWS[n - 1]!.interestDue).toFixed(2),
      );
      expect(money(db.inst(n).principalPaid)).toBe(
        new Prisma.Decimal(ROWS[n - 1]!.principalDue).toFixed(2),
      );
      expect(db.inst(n).paidInFullAt).not.toBeNull();
    }
  });

  it("books the 342.43 excess to Customer Advances, not to principal", async () => {
    const { db, repo } = seed();
    await pay(repo, "53000.00");

    expect(db.debited(ACCOUNT_CODES.CASH)).toBe("53000.00");
    expect(db.credited(ACCOUNT_CODES.INTEREST_INCOME)).toBe(TOTAL_INTEREST);
    expect(db.credited(ACCOUNT_CODES.LOANS_RECEIVABLE)).toBe(TOTAL_PRINCIPAL);
    // 53,000.00 - 52,657.57 = 342.43
    expect(db.credited(ACCOUNT_CODES.CUSTOMER_ADVANCES)).toBe("342.43");
    expectBalanced(db);
  });

  it("closes the loan", async () => {
    const { db, repo } = seed();
    await pay(repo, "53000.00");
    expect(db.loans[0]!.status).toBe("CLOSED");
    expect(db.loans[0]!.closedAt).not.toBeNull();
  });

  it("settles the book exactly on ₱52,657.57 with no advance", async () => {
    const { db, repo } = seed();
    await pay(repo, TOTAL_DUE);

    expect(db.credited(ACCOUNT_CODES.INTEREST_INCOME)).toBe(TOTAL_INTEREST);
    expect(db.credited(ACCOUNT_CODES.LOANS_RECEIVABLE)).toBe(TOTAL_PRINCIPAL);
    expect(db.credited(ACCOUNT_CODES.CUSTOMER_ADVANCES)).toBe("0.00");
    expect(db.loans[0]!.status).toBe("CLOSED");
    expectBalanced(db);
  });
});

// ─── Settling an instalment precisely ─────────────────────────────────────

describe("recordPayment — settling an instalment precisely", () => {
  it("lands ₱3,000.00 then ₱5,776.26 exactly on instalment 1", async () => {
    const { db, repo } = seed();

    await pay(repo, "3000.00", 1);
    expect(money(db.inst(1).interestPaid)).toBe("750.00");
    expect(money(db.inst(1).principalPaid)).toBe("2250.00");
    expect(db.inst(1).paidInFullAt).toBeNull();

    const second = await pay(repo, "5776.26", 12);

    // Exactly the remaining principal — no interest left to take.
    expect(db.creditedFor(second.id, ACCOUNT_CODES.INTEREST_INCOME)).toBe(
      "0.00",
    );
    expect(db.creditedFor(second.id, ACCOUNT_CODES.LOANS_RECEIVABLE)).toBe(
      "5776.26",
    );
    expect(money(db.inst(1).interestPaid)).toBe("750.00");
    expect(money(db.inst(1).principalPaid)).toBe("8026.26");
    expect(db.inst(1).paidInFullAt).toEqual(new Date(Date.UTC(2026, 3, 12)));
    expectBalanced(db);
  });

  it("settles the last instalment on its odd ₱8,776.27 total", async () => {
    // The sixth row carries the schedule's rounding drift, so it is a
    // centavo larger than the other five. Paying the whole book must clear
    // it rather than leave the loan a centavo from closing.
    const { db, repo } = seed();
    await pay(repo, TOTAL_DUE);

    expect(money(db.inst(6).interestPaid)).toBe("129.70");
    expect(money(db.inst(6).principalPaid)).toBe("8646.57");
    expect(db.inst(6).paidInFullAt).not.toBeNull();
  });
});

// ─── A centavo short ──────────────────────────────────────────────────────

describe("recordPayment — a centavo short (₱8,776.25)", () => {
  it("does NOT settle the instalment", async () => {
    const { db, repo } = seed();
    await pay(repo, "8776.25");

    // 8,026.25 + 0.005 >= 8,026.26 is false. The half-centavo tolerance
    // cannot bridge a whole centavo, and that is the point of the figure.
    expect(db.inst(1).paidInFullAt).toBeNull();
    expect(money(db.inst(1).interestPaid)).toBe("750.00");
    expect(money(db.inst(1).principalPaid)).toBe("8026.25");
  });

  it("still allocates every centavo it was given", async () => {
    const { db, repo } = seed();
    await pay(repo, "8776.25");

    expect(db.debited(ACCOUNT_CODES.CASH)).toBe("8776.25");
    expect(db.credited(ACCOUNT_CODES.INTEREST_INCOME)).toBe("750.00");
    expect(db.credited(ACCOUNT_CODES.LOANS_RECEIVABLE)).toBe("8026.25");
    expect(db.credited(ACCOUNT_CODES.CUSTOMER_ADVANCES)).toBe("0.00");
    expectBalanced(db);
  });

  it("settles once the last centavo arrives", async () => {
    const { db, repo } = seed();
    await pay(repo, "8776.25", 1);
    expect(db.inst(1).paidInFullAt).toBeNull();

    await pay(repo, "0.01", 2);
    expect(money(db.inst(1).principalPaid)).toBe("8026.26");
    expect(db.inst(1).paidInFullAt).toEqual(new Date(Date.UTC(2026, 3, 2)));
  });

  it("leaves the whole book a centavo from closing on ₱52,657.56", async () => {
    const { db, repo } = seed();
    await pay(repo, "52657.56");

    // Five rows settle; the sixth is short by exactly 0.01 of principal.
    for (let n = 1; n <= 5; n++) {
      expect(db.inst(n).paidInFullAt).not.toBeNull();
    }
    expect(money(db.inst(6).interestPaid)).toBe("129.70");
    expect(money(db.inst(6).principalPaid)).toBe("8646.56");
    expect(db.inst(6).paidInFullAt).toBeNull();

    // And so the loan stays open.
    expect(db.loans[0]!.status).toBe("ACTIVE");
    expect(db.credited(ACCOUNT_CODES.LOANS_RECEIVABLE)).toBe("49999.99");
    expect(db.credited(ACCOUNT_CODES.CUSTOMER_ADVANCES)).toBe("0.00");
    expectBalanced(db);
  });
});

// ─── Written-off loans take a different entry entirely ────────────────────

describe("recordPayment — recovery on a written-off loan", () => {
  it("books the whole amount to Bad Debt Recovery, never to Customer Advances", async () => {
    const { db, repo } = seed("WRITTEN_OFF");
    // Nothing is open on a written-off loan in production; the schedule
    // here is still open, which is the harsher case — the branch is on the
    // loan's STATUS, not on whether allocation found anything.
    await pay(repo, "5000.00");

    expect(db.credited(ACCOUNT_CODES.BAD_DEBT_RECOVERY)).toBe("5000.00");
    expect(db.credited(ACCOUNT_CODES.CUSTOMER_ADVANCES)).toBe("0.00");
    expect(db.credited(ACCOUNT_CODES.INTEREST_INCOME)).toBe("0.00");
    expectBalanced(db);
  });
});
