/** GENERATED — Region I: 3267 barangays across 125 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "0102801000": ["Adams (Pob.)"],
  "0102802000": [
    "Bani",
    "Buyon",
    "Cabaruan",
    "Cabulalaan",
    "Cabusligan",
    "Cadaratan",
    "Calioet-Libong",
    "Casilian",
    "Corocor",
    "Duripes",
    "Ganagan",
    "Libtong",
    "Macupit",
    "Nambaran",
    "Natba",
    "Paninaan",
    "Pasiocan",
    "Pasngal",
    "Pipias",
    "Pulangi",
    "Pungto",
    "San Agustin I (Pob.)",
    "San Agustin II (Pob.)",
    "San Andres I (Pob.)",
    "San Andres II (Pob.)",
    "San Gabriel I (Pob.)",
    "San Gabriel II (Pob.)",
    "San Pedro I (Pob.)",
    "San Pedro II (Pob.)",
    "San Roque I (Pob.)",
    "San Roque II (Pob.)",
    "San Simon I (Pob.)",
    "San Simon II (Pob.)",
    "San Vicente (Pob.)",
    "Sangil",
    "Santa Filomena I (Pob.)",
    "Santa Filomena II (Pob.)",
    "Santa Rita (Pob.)",
    "Santo Cristo I (Pob.)",
    "Santo Cristo II (Pob.)",
    "Tambidao",
    "Teppang",
    "Tubburan",
  ],
  "0102803000": [
    "Alay-Nangbabaan",
    "Alogoog",
    "Ar-arusip",
    "Aring",
    "Balbaldez",
    "Bato",
    "Camanga",
    "Canaan (Pob.)",
    "Caraitan",
    "Gabut Norte",
    "Gabut Sur",
    "Garreta (Pob.)",
    "La Virgen Milagrosa",
    "Labut",
    "Lacuben",
    "Lubigan",
    "Mabusag Norte",
    "Mabusag Sur",
    "Madupayas",
    "Morong",
    "Nagrebcan",
    "Napu",
    "Pagsanahan Norte",
    "Pagsanahan Sur",
    "Paltit",
    "Parang",
    "Pasuc",
    "Santa Cruz Norte",
    "Santa Cruz Sur",
    "Saud",
    "Turod",
  ],
  "0102804000": [
    "Abaca",
    "Bacsil",
    "Banban",
    "Baruyen",
    "Dadaor",
    "Lanao",
    "Malasin",
    "Manayon",
    "Masikil",
    "Nagbalagan",
    "Payac",
    "San Lorenzo (Pob.)",
    "Taguiporo",
    "Utol",
  ],
  "0102805000": [
    "Ablan Pob.",
    "Acosta Pob.",
    "Aglipay (Pob.)",
    "Baay",
    "Baligat",
    "Baoa East",
    "Baoa West",
    "Barani (Pob.)",
    "Ben-agan (Pob.)",
    "Bil-loca",
    "Biningan",
    "Bungon",
    "Callaguip (Pob.)",
    "Camandingan",
    "Camguidan",
    "Cangrunaan (Pob.)",
    "Capacuan",
    "Caunayan (Pob.)",
    "Colo",
    "Dariwdiw",
    "Lacub (Pob.)",
    "Mabaleng",
    "Magnuang",
    "Maipalig",
    "Nagbacalan",
    "Naguirangan",
    "Palongpong",
    "Palpalicong (Pob.)",
    "Parangopong",
    "Payao",
    "Pimentel",
    "Quiling Norte",
    "Quiling Sur",
    "Quiom",
    "Rayuray",
    "Ricarte Pob.",
    "San Julian (Pob.)",
    "San Mateo",
    "San Pedro",
    "Suabit (Pob.)",
    "Sumader",
    "Tabug",
    "Valdez Pob.",
  ],
  "0102806000": [
    "Ablan Sarat",
    "Agaga",
    "Bayog",
    "Bobon",
    "Buduan",
    "Nagsurot",
    "Paayas",
    "Pagali",
    "Poblacion",
    "Saoit",
    "Tanap",
  ],
  "0102807000": ["Angset", "Barbaqueso (Pob.)", "Virbira"],
  "0102808000": [
    "Anggapang Norte",
    "Anggapang Sur",
    "Bimmanga",
    "Cabuusan",
    "Comcomloong",
    "Gaang",
    "Lang-ayan-Baramban",
    "Lioes",
    "Maglaoi Centro",
    "Maglaoi Norte",
    "Maglaoi Sur",
    "Paguludan-Salindeg",
    "Pangil",
    "Pias Norte",
    "Pias Sur",
    "Poblacion I",
    "Poblacion II",
    "Salugan",
    "San Simeon",
    "Santa Cruz",
    "Tapao-Tigue",
    "Torre",
    "Victoria",
  ],
  "0102809000": [
    "Albano (Pob.)",
    "Bacsil",
    "Bagut",
    "Baresbes",
    "Barong",
    "Bungcag",
    "Cali",
    "Capasan",
    "Dancel (Pob.)",
    "Elizabeth",
    "Espiritu",
    "Foz",
    "Guerrero (Pob.)",
    "Lanas",
    "Lumbad",
    "Madamba (Pob.)",
    "Mandaloque",
    "Medina",
    "Parado",
    "Peralta (Pob.)",
    "Puruganan (Pob.)",
    "Root",
    "Sagpatan",
    "Saludares",
    "San Esteban",
    "San Francisco",
    "San Marcelino",
    "San Marcos",
    "Sulquiano",
    "Suyo",
    "Ver",
  ],
  "0102810000": ["Cabaritan", "Kalaw", "Quibel", "San Isidro"],
  "0102811000": [
    "Balioeg",
    "Bangsar",
    "Barbarangay",
    "Binacag",
    "Bomitog",
    "Bugasi",
    "Caestebanan",
    "Caribquib",
    "Catagtaguen",
    "Crispina",
    "Hilario (Pob.)",
    "Imelda",
    "Lorenzo (Pob.)",
    "Macayepyep",
    "Marcos (Pob.)",
    "Nagpatayan",
    "Sinamar",
    "Tabtabagan",
    "Valdez",
    "Valenciano (Pob.)",
  ],
  "0102812000": [
    "Bgy. No. 1, San Lorenzo (Pob.)",
    "Bgy. No. 10, San Jose (Pob.)",
    "Bgy. No. 11, Santa Balbina (Pob.)",
    "Bgy. No. 12, San Isidro (Pob.)",
    "Bgy. No. 13, Nstra. Sra. De Visitacion (Pob.)",
    "Bgy. No. 14, Santo Tomas (Pob.)",
    "Bgy. No. 15, San Guillermo (Pob.)",
    "Bgy. No. 16, San Jacinto (Pob.)",
    "Bgy. No. 17, San Francisco (Pob.)",
    "Bgy. No. 19, Santa Marcela (Pob.)",
    "Bgy. No. 2, Santa Joaquina (Pob.)",
    "Bgy. No. 20, San Miguel (Pob.)",
    "Bgy. No. 21, San Pedro (Pob.)",
    "Bgy. No. 22, San Andres (Pob.)",
    "Bgy. No. 23, San Matias (Pob.)",
    "Bgy. No. 24, Nstra. Sra. De Consolacion (Pob.)",
    "Bgy. No. 25, Santa Cayetana (Pob.)",
    "Bgy. No. 26, San Marcelino (Pob.)",
    "Bgy. No. 27, Nstra. Sra. De Soledad (Pob.)",
    "Bgy. No. 28, San Bernardo (Pob.)",
    "Bgy. No. 29, Santo Tomas (Pob.)",
    "Bgy. No. 3, Nstra. Sra. Del Rosario (Pob.)",
    "Bgy. No. 30-A, Suyo",
    "Bgy. No. 30-B, Santa Maria",
    "Bgy. No. 31, Talingaan",
    "Bgy. No. 32-A, La Paz East",
    "Bgy. No. 32-B, La Paz West",
    "Bgy. No. 32-C La Paz East",
    "Bgy. No. 33-A, La Paz Proper",
    "Bgy. No. 33-B, La Paz Proper",
    "Bgy. No. 34-A, Gabu Norte West",
    "Bgy. No. 34-B, Gabu Norte East",
    "Bgy. No. 35, Gabu Sur",
    "Bgy. No. 36, Araniw",
    "Bgy. No. 37, Calayab",
    "Bgy. No. 38-A, Mangato East",
    "Bgy. No. 38-B, Mangato West",
    "Bgy. No. 39, Santa Rosa",
    "Bgy. No. 4, San Guillermo (Pob.)",
    "Bgy. No. 40, Balatong",
    "Bgy. No. 41, Balacad",
    "Bgy. No. 42, Apaya",
    "Bgy. No. 43, Cavit",
    "Bgy. No. 44, Zamboanga",
    "Bgy. No. 45, Tangid",
    "Bgy. No. 46, Nalbo",
    "Bgy. No. 47, Bengcag",
    "Bgy. No. 48-B, Cabungaan South",
    "Bgy. No. 49-A, Darayday",
    "Bgy. No. 49-B, Raraburan",
    "Bgy. No. 5, San Pedro (Pob.)",
    "Bgy. No. 50, Buttong",
    "Bgy. No. 51-A, Nangalisan East",
    "Bgy. No. 51-B, Nangalisan West",
    "Bgy. No. 52-A, San Mateo",
    "Bgy. No. 52-B, Lataag",
    "Bgy. No. 53, Rioeng",
    "Bgy. No. 54-A, Lagui-Sail",
    "Bgy. No. 54-B, Camangaan",
    "Bgy. No. 55-A, Barit-Pandan",
    "Bgy. No. 55-B, Salet-Bulangon",
    "Bgy. No. 55-C, Vira",
    "Bgy. No. 56-A, Bacsil North",
    "Bgy. No. 56-B, Bacsil South",
    "Bgy. No. 57, Pila",
    "Bgy. No. 58, Casili",
    "Bgy. No. 59-A, Dibua South",
    "Bgy. No. 59-B, Dibua North",
    "Bgy. No. 6, San Agustin (Pob.)",
    "Bgy. No. 60-A, Caaoacan",
    "Bgy. No. 60-B, Madiladig",
    "Bgy. No. 61, Cataban",
    "Bgy. No. 62-A, Navotas North",
    "Bgy. No. 62-B, Navotas South",
    "Bgy. No. 7-A, Nstra. Sra. De Natividad (Pob.)",
    "Bgy. No. 7-B, Nstra. Sra. De Natividad (Pob.)",
    "Bgy. No. 8, San Vicente (Pob.)",
    "Bgy. No. 9, Santa Angela (Pob.)",
    "Bry. No. 18, San Quirino (Pob.)",
    "Bry. No. 48-A, Cabungaan North",
  ],
  "0102813000": [
    "Cacafean",
    "Daquioag",
    "Elizabeth",
    "Escoda",
    "Ferdinand",
    "Fortuna",
    "Imelda",
    "Lydia (Pob.)",
    "Mabuti",
    "Pacifico",
    "Santiago",
    "Tabucbuc",
    "Valdez",
  ],
  "0102814000": [
    "Acnam",
    "Barangobong",
    "Barikir",
    "Bugayong",
    "Cabittauran",
    "Caray",
    "Garnaden",
    "Naguillan",
    "Poblacion",
    "Santo Niño",
    "Uguis",
  ],
  "0102815000": [
    "Aggasi",
    "Baduang",
    "Balaoi",
    "Burayoc",
    "Caparispisan",
    "Caunayan",
    "Dampig",
    "Ligaya",
    "Pancian",
    "Pasaleng",
    "Poblacion 1",
    "Poblacion 2",
    "Saguigui",
    "Saud",
    "Subec",
    "Tarrag",
  ],
  "0102816000": [
    "Bacsil",
    "Cabagoan",
    "Cabangaran",
    "Callaguip",
    "Cayubog",
    "Dolores",
    "Laoa",
    "Masintoc",
    "Monte",
    "Mumulaan",
    "Nagbacalan",
    "Nalasin",
    "Nanguyudan",
    "Oaig-Upay-Abulao",
    "Pambaran",
    "Pannaratan (Pob.)",
    "Paratong",
    "Pasil",
    "Salbang (Pob.)",
    "San Agustin",
    "San Blas (Pob.)",
    "San Juan",
    "San Pedro",
    "San Roque (Pob.)",
    "Sangladan Pob.",
    "Santa Rita (Pob.)",
    "Sideg",
    "Suba",
    "Sungadan",
    "Surgui",
    "Veronica",
  ],
  "0102817000": [
    "Batuli",
    "Binsang",
    "Caruan",
    "Carusikis",
    "Carusipan",
    "Dadaeman",
    "Darupidip",
    "Davila",
    "Dilanis",
    "Dilavo",
    "Estancia",
    "Naglicuan",
    "Nagsanga",
    "Nalvo",
    "Ngabangab",
    "Pangil",
    "Poblacion 1",
    "Poblacion 2",
    "Poblacion 3",
    "Poblacion 4",
    "Pragata",
    "Puyupuyan",
    "Salpad",
    "San Juan",
    "Santa Catalina",
    "Santa Matilde",
    "Sapat",
    "Sulbec",
    "Sulongan",
    "Surong",
    "Susugaen",
    "Tabungao",
    "Tadao",
  ],
  "0102818000": [
    "Ab-abut",
    "Abucay",
    "Anao (Pob.)",
    "Arua-ay",
    "Bimmanga",
    "Boyboy",
    "Cabaroan (Pob.)",
    "Calambeg",
    "Callusa",
    "Dupitac",
    "Estancia",
    "Gayamat",
    "Lagandit",
    "Libnaoan",
    "Loing (Pob.)",
    "Maab-abaca",
    "Mangitayag",
    "Maruaya",
    "San Antonio",
    "Santa Maria",
    "Sucsuquen",
    "Tangaoan",
    "Tonoton",
  ],
  "0102819000": [
    "Aglipay",
    "Apatut-Lubong",
    "Badio",
    "Barbar",
    "Buanga",
    "Bulbulala",
    "Bungro",
    "Cabaroan",
    "Capangdanan",
    "Dalayap",
    "Darat",
    "Gulpeng",
    "Liliputen",
    "Lumbaan-Bicbica",
    "Nagtrigoan",
    "Pagdilao (Pob.)",
    "Pugaoan",
    "Puritac",
    "Puzol",
    "Sacritan",
    "Salanap",
    "Santo Tomas",
    "Tartarabang",
    "Upon",
    "Valbuena (Pob.)",
  ],
  "0102820000": [
    "San Agustin",
    "San Baltazar (Pob.)",
    "San Bartolome (Pob.)",
    "San Cayetano (Pob.)",
    "San Eugenio (Pob.)",
    "San Fernando (Pob.)",
    "San Francisco (Pob.)",
    "San Gregorio (Pob.)",
    "San Guillermo",
    "San Ildefonso (Pob.)",
    "San Jose (Pob.)",
    "San Juan Bautista (Pob.)",
    "San Lorenzo",
    "San Lucas (Pob.)",
    "San Marcos",
    "San Miguel (Pob.)",
    "San Pablo",
    "San Paulo (Pob.)",
    "San Pedro",
    "San Rufino (Pob.)",
    "San Silvestre (Pob.)",
    "Santa Asuncion",
    "Santa Cecilia",
    "Santa Monica",
  ],
  "0102821000": [
    "San Agustin (Pob.)",
    "San Andres",
    "San Antonio",
    "San Bernabe",
    "San Cristobal",
    "San Felipe",
    "San Francisco (Pob.)",
    "San Isidro",
    "San Joaquin (Pob.)",
    "San Jose",
    "San Juan",
    "San Leandro (Pob.)",
    "San Lorenzo",
    "San Manuel",
    "San Marcos",
    "San Nicolas",
    "San Pedro",
    "San Roque",
    "San Vicente (Pob.)",
    "Santa Barbara (Pob.)",
    "Santa Magdalena",
    "Santa Rosa",
    "Santo Santiago",
    "Santo Tomas",
  ],
  "0102822000": [
    "Aguitap",
    "Bagbag",
    "Bagbago",
    "Barcelona",
    "Bubuos",
    "Capurictan",
    "Catangraran",
    "Darasdas",
    "Juan (Pob.)",
    "Laureta (Pob.)",
    "Lipay",
    "Maananteng",
    "Manalpac",
    "Mariquet",
    "Nagpatpatan",
    "Nalasin",
    "Puttao",
    "San Juan",
    "San Julian",
    "Santa Ana",
    "Santiago",
    "Talugtog",
  ],
  "0102823000": [
    "Abkir",
    "Alejo Malasig",
    "Alsem",
    "Bago",
    "Bulbulala",
    "Cabangaran",
    "Cabayo",
    "Cabisocolan",
    "Canaam",
    "Columbia",
    "Dagupan",
    "Dipilat",
    "Esperanza",
    "Ester",
    "Isic Isic",
    "Lubnac",
    "Mabanbanag",
    "Malampa",
    "Manarang",
    "Margaay",
    "Namoroc",
    "Parparoroc",
    "Parut",
    "Pedro F. Alviar",
    "Salsalamagui",
    "San Jose",
    "San Nicolas (Pob.)",
    "San Pedro (Pob.)",
    "San Ramon (Pob.)",
    "San Roque (Pob.)",
    "Santa Maria (Pob.)",
    "Tamdagan",
    "Visaya",
  ],
  "0102901000": [
    "Alilem Daya (Pob.)",
    "Amilongan",
    "Anaao",
    "Apang",
    "Apaya",
    "Batbato",
    "Daddaay",
    "Dalawa",
    "Kiat",
  ],
  "0102902000": [
    "Bagbagotot",
    "Banbanaal",
    "Bisangol",
    "Cadanglaan",
    "Casilagan Norte",
    "Casilagan Sur",
    "Elefante",
    "Guardia",
    "Lintic",
    "Lopez",
    "Montero",
    "Naguimba",
    "Pila",
    "Poblacion",
  ],
  "0102903000": [
    "Aggay",
    "An-annam",
    "Balaleng",
    "Banaoang",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Bulag",
    "Buquig",
    "Cabalanggan",
    "Cabaroan",
    "Cabusligan",
    "Capangdanan",
    "Guimod",
    "Lingsat",
    "Malingeb",
    "Mira",
    "Naguiddayan",
    "Ora",
    "Paing",
    "Puspus",
    "Quimmarayan",
    "Sagneb",
    "Sagpat",
    "San Isidro",
    "San Julian",
    "San Mariano",
    "Sinabaan",
    "Taguiporo",
    "Taleb",
    "Tay-ac",
  ],
  "0102904000": [
    "Ambugat",
    "Balugang",
    "Bangbangar",
    "Bessang",
    "Cabcaburao",
    "Cadacad",
    "Callitong",
    "Dayanki",
    "Dirdirig",
    "Lesseb",
    "Lubing",
    "Lucaban",
    "Luna",
    "Macaoayan",
    "Mambug",
    "Manaboc",
    "Mapanit",
    "Nagpanaoan",
    "Paduros",
    "Patac",
    "Poblacion Norte",
    "Poblacion Sur",
    "Sabangan Pinggan",
    "Subadi Norte",
    "Subadi Sur",
    "Taliao",
  ],
  "0102905000": [
    "Alinaay",
    "Aragan",
    "Arnap",
    "Baclig (Pob.)",
    "Bato",
    "Bonifacio (Pob.)",
    "Bungro",
    "Cacadiran",
    "Caellayan",
    "Carusipan",
    "Catucdaan",
    "Cuancabal",
    "Cuantacla",
    "Daclapan",
    "Dardarat",
    "Lipit",
    "Maradodon",
    "Margaay",
    "Nagsantaan",
    "Nagsincaoan",
    "Namruangan",
    "Pila",
    "Pug-os",
    "Quezon (Pob.)",
    "Reppaac",
    "Rizal (Pob.)",
    "Sabang",
    "Sagayaden",
    "Salapasap",
    "Salomague",
    "Sisim",
    "Turod",
    "Turod-Patac",
  ],
  "0102906000": [
    "Allangigan Primero",
    "Allangigan Segundo",
    "Amguid",
    "Ayudante",
    "Bagani Camposanto",
    "Bagani Gabor",
    "Bagani Tocgo",
    "Bagani Ubbog",
    "Bagar",
    "Balingaoan",
    "Bugnay",
    "Calaoaan",
    "Calongbuyan",
    "Caterman",
    "Cubcubboot",
    "Darapidap",
    "Langlangca Primero",
    "Langlangca Segundo",
    "Oaig-Daya",
    "Palacapac",
    "Paras",
    "Parioc Primero",
    "Parioc Segundo",
    "Patpata Primero",
    "Patpata Segundo",
    "Paypayad",
    "Salvador Primero",
    "Salvador Segundo",
    "San Agustin",
    "San Andres",
    "San Antonio (Pob.)",
    "San Isidro (Pob.)",
    "San Jose (Pob.)",
    "San Juan (Pob.)",
    "San Nicolas",
    "San Pedro",
    "Santo Tomas",
    "Tablac",
    "Talogtog",
    "Tamurong Primero",
    "Tamurong Segundo",
    "Villarica",
  ],
  "0102907000": [
    "Anonang Mayor",
    "Anonang Menor",
    "Baggoc",
    "Callaguip",
    "Caparacadan",
    "Don Alejandro Quirolgico (Pob.)",
    "Don Dimas Querubin (Pob.)",
    "Don Lorenzo Querubin (Pob.)",
    "Fuerte",
    "Manangat",
    "Naguilian",
    "Nansuagao",
    "Pandan",
    "Pantay Tamurong",
    "Pantay-Quitiquit",
    "Puro",
    "Villamar",
  ],
  "0102908000": [
    "Aluling",
    "Comillas North",
    "Comillas South",
    "Concepcion (Pob.)",
    "Dinwede East",
    "Dinwede West",
    "Libang",
    "Malaya",
    "Pilipil",
    "Remedios",
    "Rosario (Pob.)",
    "San Juan",
    "San Luis",
  ],
  "0102909000": [
    "Abaya",
    "Baracbac",
    "Bidbiday",
    "Bitong",
    "Borobor",
    "Calimugtong",
    "Calongbuyan",
    "Calumbaya",
    "Daldagan",
    "Kilang",
    "Legaspi",
    "Mabayag",
    "Matanubong",
    "Mckinley",
    "Nagsingcaoan",
    "Oaig-Daya",
    "Pagangpang",
    "Patac",
    "Poblacion",
    "Rubio",
    "Sabangan-Bato",
    "Sacaang",
    "San Vicente",
    "Sapang",
  ],
  "0102910000": [
    "Alfonso",
    "Bussot",
    "Concepcion",
    "Dapdappig",
    "Matue-Butarag",
    "Poblacion Norte",
    "Poblacion Sur",
  ],
  "0102911000": [
    "Banucal",
    "Bequi-Walin",
    "Bugui",
    "Calungbuyan",
    "Carcarabasa",
    "Labut",
    "Poblacion Norte",
    "Poblacion Sur",
    "San Vicente",
    "Suysuyan",
    "Tay-ac",
  ],
  "0102912000": [
    "Alangan",
    "Bacar",
    "Barbarit",
    "Bungro",
    "Cabaroan",
    "Cadanglaan",
    "Caraisan",
    "Dacutan",
    "Labut",
    "Maas-asin",
    "Macatcatud",
    "Manzante",
    "Maratudo",
    "Miramar",
    "Namalpalan",
    "Napo",
    "Pagsanaan Norte",
    "Pagsanaan Sur",
    "Panay Norte",
    "Panay Sur",
    "Patong",
    "Puro",
    "San Basilio (Pob.)",
    "San Clemente (Pob.)",
    "San Julian (Pob.)",
    "San Lucas (Pob.)",
    "San Ramon (Pob.)",
    "San Vicente (Pob.)",
    "Santa Monica",
    "Sarsaracat",
  ],
  "0102913000": [
    "Balaweg",
    "Bandril",
    "Bantugo",
    "Cadacad",
    "Casilagan",
    "Cosocos",
    "Lapting",
    "Mapisi",
    "Mission",
    "Poblacion East",
    "Poblacion West",
    "Taleb",
  ],
  "0102914000": [
    "Abuor",
    "Ambulogan",
    "Aquib",
    "Banglayan",
    "Bantay Abot",
    "Bulanos",
    "Cadacad",
    "Cagayungan",
    "Camarao",
    "Casilagan",
    "Codoog",
    "Dasay",
    "Dinalaoan",
    "Estancia",
    "Lanipao",
    "Lungog",
    "Margaay",
    "Marozo",
    "Naguneg",
    "Orence",
    "Pantoc",
    "Paratong",
    "Parparia",
    "Quinarayan",
    "Rivadavia",
    "San Antonio",
    "San Jose (Pob.)",
    "San Pablo",
    "San Pedro",
    "Santa Lucia (Pob.)",
    "Sarmingan",
    "Sucoc",
    "Sulvec",
    "Turod",
  ],
  "0102915000": [
    "Banoen",
    "Cayus",
    "Lamag",
    "Legleg (Pob.)",
    "Malideg",
    "Namitpit",
    "Patiacan",
    "Patungcaleo",
    "Suagayan",
  ],
  "0102916000": [
    "Atabay",
    "Balidbid",
    "Baluarte",
    "Baybayading",
    "Boguibog",
    "Bulala-Leguey",
    "Calangcuasan",
    "Culiong",
    "Dinaratan",
    "Kaliwakiw",
    "Kinmarin",
    "Lucbuban",
    "Madarang",
    "Maligcong",
    "Pias",
    "Poblacion Norte",
    "Poblacion Sur",
    "San Gaspar",
    "San Tiburcio",
    "Sorioan",
    "Ubbog",
  ],
  "0102917000": [
    "Cabaroan (Pob.)",
    "Kalumsing",
    "Lancuas",
    "Matibuey",
    "Paltoc",
    "San Miliano",
    "Sibsibbu",
    "Tiagan",
  ],
  "0102918000": [
    "Ansad",
    "Apatot",
    "Bateria",
    "Cabaroan",
    "Cappa-cappa",
    "Poblacion",
    "San Nicolas",
    "San Pablo",
    "San Rafael",
    "Villa Quirino",
  ],
  "0102919000": [
    "Arnap",
    "Bahet",
    "Belen",
    "Bungro",
    "Busiing Norte",
    "Busiing Sur",
    "Dongalo",
    "Gongogong",
    "Iboy",
    "Kinamantirisan",
    "Otol-Patac",
    "Poblacion East",
    "Poblacion West",
    "Sagneb",
    "Sagsagat",
  ],
  "0102920000": [
    "Asilang",
    "Bacsil",
    "Baliw",
    "Bannuar (Pob.)",
    "Barbar",
    "Cabanglotan",
    "Cacandongan",
    "Camanggaan",
    "Camindoroan",
    "Caronoan",
    "Darao",
    "Dardarat",
    "Guimod Norte",
    "Guimod Sur",
    "Immayos Norte",
    "Immayos Sur",
    "Labnig",
    "Lapting",
    "Lira (Pob.)",
    "Malamin",
    "Muraya",
    "Nagsabaran",
    "Nagsupotan",
    "Pandayan (Pob.)",
    "Refaro",
    "Resurreccion (Pob.)",
    "Sabangan",
    "San Isidro",
    "Saoang",
    "Solotsolot",
    "Sunggiam",
    "Surngit",
  ],
  "0102921000": [
    "Bantaoay",
    "Bayubay Norte",
    "Bayubay Sur",
    "Lubong",
    "Poblacion",
    "Pudoc",
    "San Sebastian",
  ],
  "0102922000": [
    "Ampandula",
    "Banaoang",
    "Basug",
    "Bucalag",
    "Cabangaran",
    "Calungboyan",
    "Casiber",
    "Dammay",
    "Labut Norte",
    "Labut Sur",
    "Mabilbila Norte",
    "Mabilbila Sur",
    "Magsaysay District (Pob.)",
    "Manueva",
    "Marcos (Pob.)",
    "Nagpanaoan",
    "Namalangan",
    "Oribi",
    "Pasungol",
    "Quezon (Pob.)",
    "Quirino (Pob.)",
    "Rancho",
    "Rizal",
    "Sacuyya Norte",
    "Sacuyya Sur",
    "Tabucolan",
  ],
  "0102923000": [
    "Cabaroan",
    "Cabittaogan",
    "Cabuloan",
    "Pangada",
    "Paratong",
    "Poblacion",
    "Sinabaan",
    "Subec",
    "Tamorong",
  ],
  "0102924000": [
    "Amarao",
    "Babayoan",
    "Bacsayan",
    "Banay",
    "Bayugao Este",
    "Bayugao Oeste",
    "Besalan",
    "Bugbuga",
    "Calaoaan",
    "Camanggaan",
    "Candalican",
    "Capariaan",
    "Casilagan",
    "Coscosnong",
    "Daligan",
    "Dili",
    "Gabor Norte",
    "Gabor Sur",
    "Lalong",
    "Lantag",
    "Las-ud",
    "Mambog",
    "Mantanas",
    "Nagtengnga",
    "Padaoil",
    "Paratong",
    "Pattiqui",
    "Pidpid",
    "Pilar",
    "Pinipin",
    "Poblacion Este",
    "Poblacion Norte",
    "Poblacion Sur",
    "Poblacion Weste",
    "Quinfermin",
    "Quinsoriano",
    "Sagat",
    "San Antonio",
    "San Jose",
    "San Pedro",
    "Saoat",
    "Sevilla",
    "Sidaoen",
    "Suyo",
    "Tampugo",
    "Turod",
    "Villa Garcia",
    "Villa Hermosa",
    "Villa Laurencia",
  ],
  "0102925000": [
    "Alincaoeg",
    "Angkileng",
    "Arangin",
    "Ayusan (Pob.)",
    "Banbanaba",
    "Bani",
    "Bao-as",
    "Barangobong (Pob.)",
    "Buliclic",
    "Burgos (Pob.)",
    "Cabaritan",
    "Catayagan",
    "Conconig East",
    "Conconig West",
    "Damacuag",
    "Luba",
    "Lubong",
    "Nagrebcan",
    "Nagtablaan",
    "Namatican",
    "Nangalisan",
    "Palali Norte",
    "Palali Sur",
    "Paoc Norte",
    "Paoc Sur",
    "Paratong",
    "Pila East",
    "Pila West",
    "Quinabalayangan",
    "Ronda",
    "Sabuanan",
    "San Juan",
    "San Pedro",
    "Sapang",
    "Suagayan",
    "Vical",
  ],
  "0102926000": [
    "Ag-agrao",
    "Ampuagan",
    "Baballasioan",
    "Baliw Daya",
    "Baliw Laud",
    "Bia-o",
    "Butir",
    "Cabaroan",
    "Danuman East",
    "Danuman West",
    "Dunglayan",
    "Gusing",
    "Langaoan",
    "Laslasong Norte",
    "Laslasong Sur",
    "Laslasong West",
    "Lesseb",
    "Lingsat",
    "Lubong",
    "Maynganay Norte",
    "Maynganay Sur",
    "Nagsayaoan",
    "Nagtupacan",
    "Nalvo",
    "Pacang",
    "Penned",
    "Poblacion Norte",
    "Poblacion Sur",
    "Silag",
    "Sumagui",
    "Suso",
    "Tangaoan",
    "Tinaan",
  ],
  "0102927000": [
    "Al-aludig",
    "Ambucao",
    "Baybayabas",
    "Bigbiga",
    "Bulbulala",
    "Busel-busel",
    "Butol",
    "Caburao",
    "Dan-ar",
    "Gabao",
    "Guinabang",
    "Imus",
    "Lang-ayan",
    "Mambug",
    "Nalasin",
    "Olo-olo Norte",
    "Olo-olo Sur",
    "Poblacion Norte",
    "Poblacion Sur",
    "Sabangan",
    "Salincub",
    "San Jose",
    "San Roque",
    "Ubbog",
  ],
  "0102928000": [
    "Binalayangan",
    "Binongan",
    "Borobor",
    "Cabaritan",
    "Cabigbigaan",
    "Calautit",
    "Calay-ab",
    "Camestizoan",
    "Casili",
    "Flora",
    "Lagatit",
    "Laoingen",
    "Lussoc",
    "Nagbettedan",
    "Naglaoa-an",
    "Nalasin",
    "Nambaran",
    "Nanerman",
    "Napo",
    "Padu Chico",
    "Padu Grande",
    "Paguraper",
    "Panay",
    "Pangpangdan",
    "Parada",
    "Paras",
    "Poblacion",
    "Puerta Real",
    "Pussuac",
    "Quimmarayan",
    "San Pablo",
    "Santa Cruz",
    "Santo Tomas",
    "Sived",
    "Suksukit",
    "Vacunero",
  ],
  "0102929000": [
    "Abaccan",
    "Mabileg",
    "Matallucod",
    "Poblacion",
    "San Elias",
    "San Ramon",
    "Santo Rosario",
  ],
  "0102930000": [
    "Aguing",
    "Baliw",
    "Ballaigui (Pob.)",
    "Baracbac",
    "Barikir",
    "Battog",
    "Binacud",
    "Cabangtalan",
    "Cabarambanan",
    "Cabulalaan",
    "Cadanglaan",
    "Calanutian",
    "Calingayan",
    "Curtin",
    "Dadalaquiten Norte",
    "Dadalaquiten Sur",
    "Dean Leopoldo Yabes",
    "Duyayyat",
    "Jordan",
    "Katipunan",
    "Macabiag (Pob.)",
    "Magsaysay",
    "Marnay",
    "Masadag",
    "Nagbalioartian",
    "Nagcullooban",
    "Nagongburan",
    "Namnama (Pob.)",
    "Pacis",
    "Paratong",
    "Purag",
    "Quibit-quibit",
    "Quimmallogong",
    "Rang-ay (Pob.)",
    "Ricudo",
    "Sabañgan",
    "Sallacapo",
    "Santa Cruz",
    "Sapriana",
    "Tapao",
    "Teppeng",
    "Tubigay",
    "Ubbog",
    "Zapat",
  ],
  "0102931000": [
    "Balbalayang (Pob.)",
    "Banga",
    "Caoayan",
    "Danac",
    "Licungan",
    "Pangotan",
  ],
  "0102932000": [
    "Baringcucurong",
    "Cabugao",
    "Man-atong",
    "Patoc-ao",
    "Poblacion",
    "Suyo Proper",
    "Urzadan",
    "Uso",
  ],
  "0102933000": [
    "Ag-aguman",
    "Ambalayat",
    "Baracbac",
    "Bario-an",
    "Baritao",
    "Becques",
    "Bimmanga",
    "Bio",
    "Bitalag",
    "Borono",
    "Bucao East",
    "Bucao West",
    "Cabaroan",
    "Cabugbugan",
    "Cabulanglangan",
    "Dacutan",
    "Dardarat",
    "Del Pilar (Pob.)",
    "Farola",
    "Gabur",
    "Garitan",
    "Jardin",
    "Lacong",
    "Lantag",
    "Las-ud",
    "Libtong",
    "Lubnac",
    "Magsaysay (Pob.)",
    "Malacañang",
    "Pacac",
    "Pallogan",
    "Pudoc East",
    "Pudoc West",
    "Pula",
    "Quirino (Pob.)",
    "Ranget",
    "Rizal (Pob.)",
    "Salvacion",
    "San Miguel",
    "Sawat",
    "Tallaoen",
    "Tampugo",
    "Tarangotong",
  ],
  "0102934000": [
    "Ayusan Norte",
    "Ayusan Sur",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay IX",
    "Barangay V (Pob.)",
    "Barangay VI (Pob.)",
    "Barangay VII",
    "Barangay VIII",
    "Barraca",
    "Beddeng Daya",
    "Beddeng Laud",
    "Bongtolan",
    "Bulala",
    "Cabalangegan",
    "Cabaroan Daya",
    "Cabaroan Laud",
    "Camangaan",
    "Capangpangan",
    "Mindoro",
    "Nagsangalan",
    "Pantay Daya",
    "Pantay Fatima",
    "Pantay Laud",
    "Paoa",
    "Paratong",
    "Pong-ol",
    "Purok-a-bassit",
    "Purok-a-dackel",
    "Raois",
    "Rugsuanan",
    "Salindeg",
    "San Jose",
    "San Julian Norte",
    "San Julian Sur",
    "San Pedro",
    "Tamag",
  ],
  "0103301000": [
    "Ambitacay",
    "Balawarte",
    "Capas",
    "Consolacion (Pob.)",
    "Macalva Central",
    "Macalva Norte",
    "Macalva Sur",
    "Nazareno",
    "Purok",
    "San Agustin East",
    "San Agustin Norte",
    "San Agustin Sur",
    "San Antonino",
    "San Antonio",
    "San Francisco",
    "San Isidro",
    "San Joaquin Norte",
    "San Joaquin Sur",
    "San Jose Norte",
    "San Jose Sur",
    "San Juan",
    "San Julian Central",
    "San Julian East",
    "San Julian Norte",
    "San Julian West",
    "San Manuel Norte",
    "San Manuel Sur",
    "San Marcos",
    "San Miguel",
    "San Nicolas Central (Pob.)",
    "San Nicolas East",
    "San Nicolas Norte (Pob.)",
    "San Nicolas Sur (Pob.)",
    "San Nicolas West",
    "San Pedro",
    "San Roque East",
    "San Roque West",
    "San Vicente Norte",
    "San Vicente Sur",
    "Santa Ana",
    "Santa Barbara (Pob.)",
    "Santa Fe",
    "Santa Maria",
    "Santa Monica",
    "Santa Rita",
    "Santa Rita East",
    "Santa Rita Norte",
    "Santa Rita Sur",
    "Santa Rita West",
  ],
  "0103302000": [
    "Alaska",
    "Basca",
    "Dulao",
    "Gallano",
    "Macabato",
    "Manga",
    "Pangao-aoan East",
    "Pangao-aoan West",
    "Poblacion",
    "Samara",
    "San Antonio",
    "San Benito Norte",
    "San Benito Sur",
    "San Eugenio",
    "San Juan East",
    "San Juan West",
    "San Simon East",
    "San Simon West",
    "Santa Cecilia",
    "Santa Lucia",
    "Santa Rita East",
    "Santa Rita West",
    "Santo Rosario East",
    "Santo Rosario West",
  ],
  "0103303000": [
    "Agtipal",
    "Arosip",
    "Bacqui",
    "Bacsil",
    "Bagutot",
    "Ballogo",
    "Baroro",
    "Bitalag",
    "Bulala",
    "Burayoc",
    "Bussaoit",
    "Cabaroan",
    "Cabarsican",
    "Cabugao",
    "Calautit",
    "Carcarmay",
    "Casiaman",
    "Galongen",
    "Guinabang",
    "Legleg",
    "Lisqueb",
    "Mabanengbeng 1st",
    "Mabanengbeng 2nd",
    "Maragayap",
    "Nagatiran",
    "Nagsaraboan",
    "Nagsimbaanan",
    "Nangalisan",
    "Narra",
    "Ortega",
    "Oya-oy",
    "Paagan",
    "Pandan",
    "Pang-pang",
    "Poblacion",
    "Quirino",
    "Raois",
    "Salincob",
    "San Martin",
    "Santa Cruz",
    "Santa Rita",
    "Sapilang",
    "Sayoan",
    "Sipulo",
    "Tammocalao",
    "Ubbog",
    "Zaragosa",
  ],
  "0103304000": [
    "Alibangsay",
    "Baay",
    "Cambaly",
    "Cardiz",
    "Dagup",
    "Libbo",
    "Suyo (Pob.)",
    "Tagudtud",
    "Tio-angan",
    "Wallayan",
  ],
  "0103305000": [
    "Almeida",
    "Antonino",
    "Apatut",
    "Ar-arampang",
    "Baracbac Este",
    "Baracbac Oeste",
    "Bet-ang",
    "Bulbulala",
    "Bungol",
    "Butubut Este",
    "Butubut Norte",
    "Butubut Oeste",
    "Butubut Sur",
    "Cabuaan Oeste (Pob.)",
    "Calliat",
    "Calungbuyan",
    "Camiling",
    "Dr. Camilo Osias Pob.",
    "Guinaburan",
    "Masupe",
    "Nagsabaran Norte",
    "Nagsabaran Sur",
    "Nalasin",
    "Napaset",
    "Pa-o",
    "Pagbennecan",
    "Pagleddegan",
    "Pantar Norte",
    "Pantar Sur",
    "Paraoir",
    "Patpata",
    "Sablut",
    "San Pablo",
    "Sinapangan Norte",
    "Sinapangan Sur",
    "Tallipugo",
  ],
  "0103306000": [
    "Agdeppa",
    "Alzate",
    "Bangaoilan East",
    "Bangaoilan West",
    "Barraca",
    "Cadapli",
    "Caggao",
    "Central East No. 1 (Pob.)",
    "Central East No. 2 (Pob.)",
    "Central West No. 1 (Pob.)",
    "Central West No. 2 (Pob.)",
    "Central West No. 3 (Pob.)",
    "Consuegra",
    "General Prim East",
    "General Prim West",
    "General Terrero",
    "Luzong Norte",
    "Luzong Sur",
    "Maria Cristina East",
    "Maria Cristina West",
    "Mindoro",
    "Nagsabaran",
    "Paratong No. 3",
    "Paratong No. 4",
    "Paratong Norte",
    "Quintarong",
    "Reyna Regente",
    "Rissing",
    "San Blas",
    "San Cristobal",
    "Sinapangan Norte",
    "Sinapangan Sur",
    "Ubbog",
  ],
  "0103307000": [
    "Acao",
    "Baccuit Norte",
    "Baccuit Sur",
    "Bagbag",
    "Ballay",
    "Bawanta",
    "Boy-utan",
    "Bucayab",
    "Cabalayangan",
    "Cabisilan",
    "Calumbaya",
    "Carmay",
    "Casilagan",
    "Central East (Pob.)",
    "Central West (Pob.)",
    "Dili",
    "Disso-or",
    "Guerrero",
    "Lower San Agustin",
    "Nagrebcan",
    "Pagdalagan Sur",
    "Palintucang",
    "Palugsi-Limmansangan",
    "Parian Este",
    "Parian Oeste",
    "Paringao",
    "Payocpoc Norte Este",
    "Payocpoc Norte Oeste",
    "Payocpoc Sur",
    "Pilar",
    "Pottot",
    "Pudoc",
    "Pugo",
    "Quinavite",
    "Santa Monica",
    "Santiago",
    "Taberna",
    "Upper San Agustin",
    "Urayong",
  ],
  "0103308000": [
    "Agpay",
    "Bilis",
    "Caoayan",
    "Dalacdac",
    "Delles",
    "Imelda",
    "Libtong",
    "Linuan",
    "Lower Tumapoc",
    "New Poblacion",
    "Old Poblacion",
    "Upper Tumapoc",
  ],
  "0103309000": [
    "Bautista",
    "Gana",
    "Juan Cartas",
    "Las-ud",
    "Liquicia",
    "Poblacion Norte",
    "Poblacion Sur",
    "San Carlos",
    "San Cornelio",
    "San Fermin",
    "San Gregorio",
    "San Jose",
    "Santiago Norte",
    "Santiago Sur",
    "Sobredillo",
    "Urayong",
    "Wenceslao",
  ],
  "0103310000": [
    "Alcala (Pob.)",
    "Ayaoan",
    "Barangobong",
    "Barrientos",
    "Bungro",
    "Buselbusel",
    "Cabalitocan",
    "Cantoria No. 1",
    "Cantoria No. 2",
    "Cantoria No. 3",
    "Cantoria No. 4",
    "Carisquis",
    "Darigayos",
    "Magallanes (Pob.)",
    "Magsiping",
    "Mamay",
    "Nagrebcan",
    "Nalvo Norte",
    "Nalvo Sur",
    "Napaset",
    "Oaqui No. 1",
    "Oaqui No. 2",
    "Oaqui No. 3",
    "Oaqui No. 4",
    "Pila",
    "Pitpitac",
    "Rimos No. 1",
    "Rimos No. 2",
    "Rimos No. 3",
    "Rimos No. 4",
    "Rimos No. 5",
    "Rissing",
    "Salcedo (Pob.)",
    "Santo Domingo Norte",
    "Santo Domingo Sur",
    "Sucoc Norte",
    "Sucoc Sur",
    "Suyo",
    "Tallaoen",
    "Victoria (Pob.)",
  ],
  "0103311000": [
    "Aguioas",
    "Al-alinao Norte",
    "Al-alinao Sur",
    "Ambaracao Norte",
    "Ambaracao Sur",
    "Angin",
    "Balecbec",
    "Bancagan",
    "Baraoas Norte",
    "Baraoas Sur",
    "Bariquir",
    "Bato",
    "Bimmotobot",
    "Cabaritan Norte",
    "Cabaritan Sur",
    "Casilagan",
    "Dal-lipaoen",
    "Daramuangan",
    "Guesset",
    "Gusing Norte",
    "Gusing Sur",
    "Imelda",
    "Lioac Norte",
    "Lioac Sur",
    "Magungunay",
    "Mamat-ing Norte",
    "Mamat-ing Sur",
    "Nagsidorisan",
    "Natividad (Pob.)",
    "Ortiz (Pob.)",
    "Ribsuan",
    "San Antonio",
    "San Isidro",
    "Sili",
    "Suguidan Norte",
    "Suguidan Sur",
    "Tuddingan",
  ],
  "0103312000": [
    "Ambalite",
    "Ambangonan",
    "Cares",
    "Cuenca",
    "Duplas",
    "Maoasoas Norte",
    "Maoasoas Sur",
    "Palina",
    "Poblacion East",
    "Poblacion West",
    "San Luis",
    "Saytan",
    "Tavora East",
    "Tavora Proper",
  ],
  "0103313000": [
    "Alipang",
    "Ambangonan",
    "Amlang",
    "Bacani",
    "Bangar",
    "Bani",
    "Benteng-Sapilang",
    "Cadumanian",
    "Camp One",
    "Carunuan East",
    "Carunuan West",
    "Casilagan",
    "Cataguingtingan",
    "Concepcion",
    "Damortis",
    "Gumot-Nagcolaran",
    "Inabaan Norte",
    "Inabaan Sur",
    "Marcos",
    "Nagtagaan",
    "Nangcamotian",
    "Parasapas",
    "Poblacion East",
    "Poblacion West",
    "Puzon",
    "Rabon",
    "San Jose",
    "Subusub",
    "Tabtabungao",
    "Tanglag",
    "Tay-ac",
    "Udiao",
    "Vila",
  ],
  "0103314000": [
    "Abut",
    "Apaleng",
    "Bacsil",
    "Bangbangolan",
    "Bangcusay",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Baraoas",
    "Bato",
    "Biday",
    "Birunget",
    "Bungro",
    "Cabaroan",
    "Cabarsican",
    "Cadaclan",
    "Calabugao",
    "Camansi",
    "Canaoay",
    "Carlatan",
    "Catbangen",
    "Dallangayan Este",
    "Dallangayan Oeste",
    "Dalumpinas Este",
    "Dalumpinas Oeste",
    "Ilocanos Norte",
    "Ilocanos Sur",
    "Langcuas",
    "Lingsat",
    "Madayegdeg",
    "Mameltac",
    "Masicong",
    "Nagyubuyuban",
    "Namtutan",
    "Narra Este",
    "Narra Oeste",
    "Pacpaco",
    "Pagdalagan",
    "Pagdaraoan",
    "Pagudpud",
    "Pao Norte",
    "Pao Sur",
    "Parian",
    "Pias",
    "Poro",
    "Puspus",
    "Sacyud",
    "Sagayad",
    "San Agustin",
    "San Francisco",
    "San Vicente",
    "Santiago Norte",
    "Santiago Sur",
    "Saoay",
    "Sevilla",
    "Siboan-Otong",
    "Tanqui",
    "Tanquigan",
  ],
  "0103315000": [
    "Amontoc",
    "Apayao",
    "Balbalayang",
    "Bayabas",
    "Bucao",
    "Bumbuneg",
    "Daking",
    "Lacong",
    "Lipay Este",
    "Lipay Norte",
    "Lipay Proper",
    "Lipay Sur",
    "Lon-oy",
    "Poblacion",
    "Polipol",
  ],
  "0103316000": [
    "Allangigan",
    "Aludaid",
    "Bacsayan",
    "Balballosa",
    "Bambanay",
    "Bugbugcao",
    "Caarusipan",
    "Cabaroan",
    "Cabugnayan",
    "Cacapian",
    "Caculangan",
    "Calincamasan",
    "Casilagan",
    "Catdongan",
    "Dangdangla",
    "Dasay",
    "Dinanum",
    "Duplas",
    "Guinguinabang",
    "Ili Norte (Pob.)",
    "Ili Sur (Pob.)",
    "Legleg",
    "Lubing",
    "Nadsaag",
    "Nagsabaran",
    "Naguirangan",
    "Naguituban",
    "Nagyubuyuban",
    "Oaquing",
    "Pacpacac",
    "Pagdildilan",
    "Panicsican",
    "Quidem",
    "San Felipe",
    "Santa Rosa",
    "Santo Rosario",
    "Saracat",
    "Sinapangan",
    "Taboc",
    "Talogtog",
    "Urbiztondo",
  ],
  "0103317000": [
    "Ambitacay",
    "Bail",
    "Balaoc",
    "Balsaan",
    "Baybay",
    "Cabaruan",
    "Casantaan",
    "Casilagan",
    "Cupang",
    "Damortis",
    "Fernando",
    "Linong",
    "Lomboy",
    "Malabago",
    "Namboongan",
    "Namonitan",
    "Narvacan",
    "Patac",
    "Poblacion",
    "Pongpong",
    "Raois",
    "Tococ",
    "Tubod",
    "Ubagan",
  ],
  "0103318000": [
    "Corrooy",
    "Lettac Norte",
    "Lettac Sur",
    "Mangaan",
    "Paagan",
    "Poblacion",
    "Puguil",
    "Ramot",
    "Sapdaan",
    "Sasaba",
    "Tubaday",
  ],
  "0103319000": [
    "Bigbiga",
    "Bulalaan",
    "Castro",
    "Duplas",
    "Ilocano",
    "Ipet",
    "Maliclico",
    "Namaltugan",
    "Old Central",
    "Poblacion",
    "Porporiket",
    "San Francisco Norte",
    "San Francisco Sur",
    "San Jose",
    "Sengngat",
    "Turod",
    "Up-uplas",
  ],
  "0103320000": [
    "Amallapay",
    "Anduyan",
    "Caoigue",
    "Francia Sur",
    "Francia West",
    "Garcia",
    "Gonzales",
    "Halog East",
    "Halog West",
    "Leones East",
    "Leones West",
    "Linapew",
    "Lloren",
    "Magsaysay",
    "Pideg",
    "Poblacion",
    "Rizal",
    "Santa Teresa",
  ],
  "0105501000": [
    "Allabon",
    "Aloleng",
    "Bangan-Oda",
    "Baruan",
    "Boboy",
    "Cayungnan",
    "Dangley",
    "Gayusan",
    "Macaboboni",
    "Magsaysay",
    "Namatucan",
    "Patar",
    "Poblacion East",
    "Poblacion West",
    "San Juan",
    "Tupa",
    "Viga",
  ],
  "0105502000": [
    "Bayaoas",
    "Baybay",
    "Bocacliw",
    "Bocboc East",
    "Bocboc West",
    "Buer",
    "Calsib",
    "Laoag",
    "Manlocboc",
    "Ninoy",
    "Panacol",
    "Poblacion",
    "Pogomboa",
    "Pogonsili",
    "San Jose",
    "Tampac",
  ],
  "0105503000": [
    "Alos",
    "Amandiego",
    "Amangbangan",
    "Balangobong",
    "Balayang",
    "Baleyadaan",
    "Bisocol",
    "Bolaney",
    "Bued",
    "Cabatuan",
    "Cayucay",
    "Dulacac",
    "Inerangan",
    "Landoc",
    "Linmansangan",
    "Lucap",
    "Maawi",
    "Macatiw",
    "Magsaysay",
    "Mona",
    "Palamis",
    "Pandan",
    "Pangapisan",
    "Poblacion",
    "Pocalpocal",
    "Pogo",
    "Polo",
    "Quibuar",
    "Sabangan",
    "San Antonio",
    "San Jose",
    "San Roque",
    "San Vicente",
    "Santa Maria",
    "Tanaytay",
    "Tangcarang",
    "Tawintawin",
    "Telbang",
    "Victoria",
  ],
  "0105504000": [
    "Anulid",
    "Atainan",
    "Bersamin",
    "Canarvacanan",
    "Caranglaan",
    "Curareng",
    "Gualsic",
    "Kasikis",
    "Laoac",
    "Macayo",
    "Pindangan Centro",
    "Pindangan East",
    "Pindangan West",
    "Poblacion East",
    "Poblacion West",
    "San Juan",
    "San Nicolas",
    "San Pedro Apartado",
    "San Pedro IlI",
    "San Vicente",
    "Vacante",
  ],
  "0105505000": [
    "Awag",
    "Awile",
    "Batiarao",
    "Cabungan",
    "Carot",
    "Dolaoan",
    "Imbo",
    "Macaleeng",
    "Macandocandong",
    "Mal-ong",
    "Namagbagan",
    "Poblacion",
    "Roxas",
    "Sablig",
    "San Jose",
    "Siapar",
    "Tondol",
    "Toritori",
  ],
  "0105506000": [
    "Ariston Este",
    "Ariston Weste",
    "Bantog",
    "Baro",
    "Bobonan",
    "Cabalitian",
    "Calepaan",
    "Carosucan Norte",
    "Carosucan Sur",
    "Coldit",
    "Domanpot",
    "Dupac",
    "Macalong",
    "Palaris",
    "Poblacion East",
    "Poblacion West",
    "San Vicente Este",
    "San Vicente Weste",
    "Sanchez",
    "Sobol",
    "Toboy",
  ],
  "0105507000": [
    "Angayan Norte",
    "Angayan Sur",
    "Capulaan",
    "Esmeralda",
    "Kita-kita",
    "Mabini",
    "Mauban",
    "Poblacion",
    "Pugaro",
    "Rajal",
    "San Andres",
    "San Aurelio 1st",
    "San Aurelio 2nd",
    "San Aurelio 3rd",
    "San Joaquin",
    "San Julian",
    "San Leon",
    "San Marcelino",
    "San Miguel",
    "San Raymundo",
  ],
  "0105508000": [
    "Ambabaay",
    "Aporao",
    "Arwas",
    "Ballag",
    "Banog Norte",
    "Banog Sur",
    "Calabeng",
    "Centro Toma",
    "Colayo",
    "Dacap Norte",
    "Dacap Sur",
    "Garrita",
    "Luac",
    "Macabit",
    "Masidem",
    "Poblacion",
    "Quinaoayanan",
    "Ranao",
    "Ranom Iloco",
    "San Jose",
    "San Miguel",
    "San Simon",
    "San Vicente",
    "Tiep",
    "Tipor",
    "Tugui Grande",
    "Tugui Norte",
  ],
  "0105509000": [
    "Anambongan",
    "Bayoyong",
    "Cabeldatan",
    "Dumpay",
    "Malimpec East",
    "Mapolopolo",
    "Nalneran",
    "Navatat",
    "Obong",
    "Osmena Sr.",
    "Palma",
    "Patacbo",
    "Poblacion",
  ],
  "0105510000": [
    "Artacho",
    "Baluyot",
    "Cabuaan",
    "Cacandongan",
    "Diaz",
    "Ketegan",
    "Nandacan",
    "Nibaliw Norte",
    "Nibaliw Sur",
    "Palisoc",
    "Poblacion East",
    "Poblacion West",
    "Pogo",
    "Poponto",
    "Primicias",
    "Sinabaan",
    "Vacante",
    "Villanueva",
  ],
  "0105511000": [
    "Alinggan",
    "Amamperez",
    "Amancosiling Norte",
    "Amancosiling Sur",
    "Ambayat I",
    "Ambayat II",
    "Apalen",
    "Asin",
    "Ataynan",
    "Bacnono",
    "Balaybuaya",
    "Banaban",
    "Bani",
    "Batangcawa",
    "Beleng",
    "Bical Norte",
    "Bical Sur",
    "Bongato East",
    "Bongato West",
    "Buayaen",
    "Buenlag 1st",
    "Buenlag 2nd",
    "Cadre Site",
    "Carungay",
    "Caturay",
    "Darawey",
    "Duera",
    "Dusoc",
    "Hermoza",
    "Idong",
    "Inanlorenzana",
    "Inirangan",
    "Iton",
    "Langiran",
    "Ligue",
    "M. H. del Pilar",
    "Macayocayo",
    "Magsaysay",
    "Maigpa",
    "Malimpec",
    "Malioer",
    "Managos",
    "Manambong Norte",
    "Manambong Parte",
    "Manambong Sur",
    "Mangayao",
    "Nalsian Norte",
    "Nalsian Sur",
    "Pangdel",
    "Pantol",
    "Paragos",
    "Poblacion Sur",
    "Pugo",
    "Reynado",
    "San Gabriel 1st",
    "San Gabriel 2nd",
    "San Vicente",
    "Sangcagulis",
    "Sanlibo",
    "Sapang",
    "Tamaro",
    "Tambac",
    "Tampog",
    "Tanolong",
    "Tatarao",
    "Telbang",
    "Tococ East",
    "Tococ West",
    "Warding",
    "Wawa",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)",
    "Zone V (Pob.)",
    "Zone VI (Pob.)",
    "Zone VII (Pob.)",
  ],
  "0105512000": [
    "Balangobong",
    "Bued",
    "Bugayong",
    "Camangaan",
    "Canarvacanan",
    "Capas",
    "Cili",
    "Dumayat",
    "Linmansangan",
    "Mangcasuy",
    "Moreno",
    "Pasileng Norte",
    "Pasileng Sur",
    "Poblacion",
    "San Felipe Central",
    "San Felipe Sur",
    "San Pablo",
    "Santa Catalina",
    "Santa Maria Norte",
    "Santiago",
    "Santo Niño",
    "Sumabnit",
    "Tabuyoc",
    "Vacante",
  ],
  "0105513000": [
    "Amancoro",
    "Balagan",
    "Balogo",
    "Basing",
    "Baybay Lopez",
    "Baybay Polong",
    "Biec",
    "Buenlag",
    "Calit",
    "Caloocan Dupo",
    "Caloocan Norte",
    "Caloocan Sur",
    "Camaley",
    "Canaoalan",
    "Dulag",
    "Gayaman",
    "Linoc",
    "Lomboy",
    "Malindong",
    "Manat",
    "Nagpalangan",
    "Naguilayan",
    "Pallas",
    "Papagueyan",
    "Parayao",
    "Poblacion",
    "Pototan",
    "Sabangan",
    "Salapingao",
    "San Isidro Norte",
    "San Isidro Sur",
    "Santa Rosa",
    "Tombor",
  ],
  "0105514000": [
    "Arnedo",
    "Balingasay",
    "Binabalian",
    "Cabuyao",
    "Catuday",
    "Catungi",
    "Concordia (Pob.)",
    "Culang",
    "Dewey",
    "Estanza",
    "Germinal (Pob.)",
    "Goyoden",
    "Ilogmalino",
    "Lambes",
    "Liwa-liwa",
    "Lucero",
    "Luciente 1.0",
    "Luciente 2.0",
    "Luna",
    "Patar",
    "Pilar",
    "Salud",
    "Samang Norte",
    "Samang Sur",
    "Sampaloc",
    "San Roque",
    "Tara",
    "Tupa",
    "Victory",
    "Zaragoza",
  ],
  "0105515000": [
    "Angarian",
    "Asinan",
    "Bacabac",
    "Banaga",
    "Bolaoen",
    "Buenlag",
    "Cabayaoasan",
    "Cayanga",
    "Gueset",
    "Hacienda",
    "Laguit Centro",
    "Laguit Padilla",
    "Magtaking",
    "Pangascasan",
    "Pantal",
    "Poblacion",
    "Polong",
    "Portic",
    "Salasa",
    "Salomague Norte",
    "Salomague Sur",
    "Samat",
    "San Francisco",
    "Umanday",
  ],
  "0105516000": [
    "Anapao",
    "Cacayasen",
    "Concordia",
    "Don Matias",
    "Ilio-ilio",
    "Papallasen",
    "Poblacion",
    "Pogoruac",
    "San Miguel",
    "San Pascual",
    "San Vicente",
    "Sapa Grande",
    "Sapa Pequeña",
    "Tambacan",
  ],
  "0105517000": [
    "Ambonao",
    "Ambuetel",
    "Banaoang",
    "Bued",
    "Buenlag",
    "Cabilocaan",
    "Dinalaoan",
    "Doyong",
    "Gabon",
    "Lasip",
    "Longos",
    "Lumbang",
    "Macabito",
    "Malabago",
    "Mancup",
    "Nagsaing",
    "Nalsian",
    "Poblacion East",
    "Poblacion West",
    "Quesban",
    "San Miguel",
    "San Vicente",
    "Songkoy",
    "Talibaew",
  ],
  "0105518000": [
    "Bacayao Norte",
    "Bacayao Sur",
    "Barangay I",
    "Barangay II",
    "Barangay IV",
    "Bolosan",
    "Bonuan Binloc",
    "Bonuan Boquig",
    "Bonuan Gueset",
    "Calmay",
    "Carael",
    "Caranglaan",
    "Herrero",
    "Lasip Chico",
    "Lasip Grande",
    "Lomboy",
    "Lucao",
    "Malued",
    "Mamalingling",
    "Mangin",
    "Mayombo",
    "Pantal",
    "Poblacion Oeste",
    "Pogo Chico",
    "Pogo Grande",
    "Pugaro Suit",
    "Salapingao",
    "Salisay",
    "Tambac",
    "Tapuac",
    "Tebeng",
  ],
  "0105519000": [
    "Alilao",
    "Amalbalan",
    "Bobonot",
    "Eguia",
    "Gais-Guipe",
    "Hermosa",
    "Macalang",
    "Magsaysay",
    "Malacapas",
    "Malimpin",
    "Osmeña",
    "Petal",
    "Poblacion",
    "San Vicente",
    "Tambac",
    "Tambobong",
    "Uli",
    "Viga",
  ],
  "0105520000": [
    "Babuyan",
    "Bamban",
    "Batang",
    "Bayambang",
    "Cato",
    "Doliman",
    "Fatima",
    "Maya",
    "Nangalisan",
    "Nayom",
    "Pita",
    "Poblacion",
    "Potol",
  ],
  "0105521000": [
    "Bolo",
    "Bongalon",
    "Dulig",
    "Laois",
    "Magsaysay",
    "Poblacion",
    "San Gonzalo",
    "San Jose",
    "Tobuan",
    "Uyong",
  ],
  "0105522000": [
    "Aliwekwek",
    "Baay",
    "Balangobong",
    "Balococ",
    "Bantayan",
    "Basing",
    "Capandanan",
    "Domalandan Center",
    "Domalandan East",
    "Domalandan West",
    "Dorongan",
    "Dulag",
    "Estanza",
    "Lasip",
    "Libsong East",
    "Libsong West",
    "Malawa",
    "Malimpuec",
    "Maniboc",
    "Matalava",
    "Naguelguel",
    "Namolan",
    "Pangapisan North",
    "Pangapisan Sur",
    "Poblacion",
    "Quibaol",
    "Rosario",
    "Sabangan",
    "Talogtog",
    "Tonton",
    "Tumbar",
    "Wawa",
  ],
  "0105523000": [
    "Bacnit",
    "Barlo",
    "Caabiangaan",
    "Cabanaetan",
    "Cabinuangan",
    "Calzada",
    "Caranglaan",
    "De Guzman",
    "Luna",
    "Magalong",
    "Nibaliw",
    "Patar",
    "Poblacion",
    "San Pedro",
    "Tagudin",
    "Villacorta",
  ],
  "0105524000": [
    "Abonagan",
    "Agdao",
    "Alacan",
    "Aliaga",
    "Amacalan",
    "Anolid",
    "Apaya",
    "Asin Este",
    "Asin Weste",
    "Bacundao Este",
    "Bacundao Weste",
    "Bakitiw",
    "Balite",
    "Banawang",
    "Barang",
    "Bawer",
    "Binalay",
    "Bobon",
    "Bolaoit",
    "Bongar",
    "Butao",
    "Cabatling",
    "Cabueldatan",
    "Calbueg",
    "Canan Norte",
    "Canan Sur",
    "Cawayan Bogtong",
    "Don Pedro",
    "Gatang",
    "Goliman",
    "Gomez",
    "Guilig",
    "Ican",
    "Ingalagala",
    "Lareg-lareg",
    "Lasip",
    "Lepa",
    "Loqueb Este",
    "Loqueb Norte",
    "Loqueb Sur",
    "Lunec",
    "Mabulitec",
    "Malimpec",
    "Manggan-Dampay",
    "Nalsian Norte",
    "Nalsian Sur",
    "Nancapian",
    "Nansangaan",
    "Olea",
    "Pacuan",
    "Palapar Norte",
    "Palapar Sur",
    "Palong",
    "Pamaranum",
    "Pasima",
    "Payar",
    "Poblacion",
    "Polong Norte",
    "Polong Sur",
    "Potiocan",
    "San Julian",
    "Tabo-Sili",
    "Talospatang",
    "Taloy",
    "Taloyan",
    "Tambac",
    "Tobor",
    "Tolonguat",
    "Tomling",
    "Umando",
    "Viado",
    "Waig",
    "Warey",
  ],
  "0105525000": [
    "Babasit",
    "Baguinay",
    "Baritao",
    "Bisal",
    "Bucao",
    "Cabanbanan",
    "Calaocan",
    "Inamotan",
    "Lelemaan",
    "Licsi",
    "Lipit Norte",
    "Lipit Sur",
    "Matolong",
    "Mermer",
    "Nalsian",
    "Oraan East",
    "Oraan West",
    "Pantal",
    "Pao",
    "Parian",
    "Poblacion",
    "Pugaro",
    "San Ramon",
    "Santa Ines",
    "Sapang",
    "Tebuel",
  ],
  "0105526000": [
    "Alitaya",
    "Amansabina",
    "Anolid",
    "Banaoang",
    "Bantayan",
    "Bari",
    "Bateng",
    "Buenlag",
    "David",
    "Embarcadero",
    "Gueguesangen",
    "Guesang",
    "Guiguilonen",
    "Guilig",
    "Inlambo",
    "Lanas",
    "Landas",
    "Maasin",
    "Macayug",
    "Malabago",
    "Navaluan",
    "Nibaliw",
    "Osiem",
    "Palua",
    "Poblacion",
    "Pogo",
    "Salaan",
    "Salay",
    "Talogtog",
    "Tebag",
  ],
  "0105527000": [
    "Andangin",
    "Arellano Street (Pob.)",
    "Bantay",
    "Bantocaling",
    "Baracbac",
    "Bogtong Bolo",
    "Bogtong Bunao",
    "Bogtong Centro",
    "Bogtong Niog",
    "Bogtong Silag",
    "Buaya",
    "Buenlag",
    "Bueno",
    "Bunagan",
    "Bunlalacao",
    "Burgos Street (Pob.)",
    "Cabaluyan 1st",
    "Cabaluyan 2nd",
    "Cabarabuan",
    "Cabaruan",
    "Cabayaoasan",
    "Cabayugan",
    "Cacaoiten",
    "Calumboyan Norte",
    "Calumboyan Sur",
    "Calvo (Pob.)",
    "Casilagan",
    "Catarataraan",
    "Caturay Norte",
    "Caturay Sur",
    "Caviernesan",
    "Dorongan Ketaket",
    "Dorongan Linmansangan",
    "Dorongan Punta",
    "Dorongan Sawat",
    "Dorongan Valerio",
    "General Luna (Pob.)",
    "Historia",
    "Lawak Langka",
    "Linmansangan",
    "Lopez (Pob.)",
    "Mabini (Pob.)",
    "Macarang",
    "Malabobo",
    "Malibong",
    "Malunec",
    "Maravilla (Pob.)",
    "Maravilla-Arellano Ext. (Pob.)",
    "Muelang",
    "Naguilayan East",
    "Naguilayan West",
    "Nancasalan",
    "Niog-Cabison-Bulaney",
    "Olegario-Caoile (Pob.)",
    "Olo Cacamposan",
    "Olo Cafabrosan",
    "Olo Cagarlitan",
    "Osmeña (Pob.)",
    "Pacalat",
    "Pampano",
    "Parian",
    "Paul",
    "Peania Pedania",
    "Pogon-Aniat",
    "Pogon-Lomboy (Pob.)",
    "Ponglo-Baleg",
    "Ponglo-Muelag",
    "Quetegan",
    "Quezon (Pob.)",
    "Salavante",
    "Sapang",
    "Sonson Ongkit",
    "Suaco",
    "Tagac",
    "Takipan",
    "Talogtog",
    "Tococ Barikir",
    "Torre 1st",
    "Torre 2nd",
    "Torres Bugallon (Pob.)",
    "Umangan",
    "Zamora (Pob.)",
  ],
  "0105528000": [
    "Amanoaoac",
    "Apaya",
    "Aserda",
    "Baloling",
    "Coral",
    "Golden",
    "Jimenez",
    "Lambayan",
    "Luyan",
    "Nilombot",
    "Pias",
    "Poblacion",
    "Primicias",
    "Santa Maria",
    "Torres",
  ],
  "0105529000": [
    "Barangobong",
    "Batchelor East",
    "Batchelor West",
    "Burgos",
    "Cacandungan",
    "Calapugan",
    "Canarem",
    "Luna",
    "Poblacion East",
    "Poblacion West",
    "Rizal",
    "Salud",
    "San Eugenio",
    "San Macario Norte",
    "San Macario Sur",
    "San Maximo",
    "San Miguel",
    "Silag",
  ],
  "0105530000": [
    "Alipangpang",
    "Amagbagan",
    "Balacag",
    "Banding",
    "Bantugan",
    "Batakil",
    "Bobonan",
    "Buneg",
    "Cablong",
    "Casanfernandoan",
    "Castaño",
    "Dilan",
    "Don Benito",
    "Haway",
    "Imbalbalatong",
    "Inoman",
    "Laoac",
    "Maambal",
    "Malasin",
    "Malokiat",
    "Manaol",
    "Nama",
    "Nantangalan",
    "Palacpalac",
    "Palguyod",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Rosario",
    "Sugcong",
    "Talogtog",
    "Tulnac",
    "Villegas",
  ],
  "0105531000": [
    "Acop",
    "Bakitbakit",
    "Balingcanaway",
    "Cabalaoangan Norte",
    "Cabalaoangan Sur",
    "Calanutan",
    "Camangaan",
    "Capitan Tomas",
    "Carmay East",
    "Carmay West",
    "Carmen East",
    "Carmen West",
    "Casanicolasan",
    "Coliling",
    "Don Antonio Village",
    "Guiling",
    "Palakipak",
    "Pangaoan",
    "Rabago",
    "Rizal",
    "Salvacion",
    "San Angel",
    "San Antonio",
    "San Bartolome",
    "San Isidro",
    "San Luis",
    "San Pedro East",
    "San Pedro West",
    "San Vicente",
    "Station District",
    "Tomana East",
    "Tomana West",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)",
    "Zone V (Pob.)",
  ],
  "0105532000": [
    "Abanon",
    "Agdao",
    "Anando",
    "Ano",
    "Antipangol",
    "Aponit",
    "Bacnar",
    "Balaya",
    "Balayong",
    "Baldog",
    "Balite Sur",
    "Balococ",
    "Bani",
    "Bega",
    "Bocboc",
    "Bogaoan",
    "Bolingit",
    "Bolosan",
    "Bonifacio (Pob.)",
    "Buenglat",
    "Bugallon-Posadas Street (Pob.)",
    "Burgos Padlan (Pob.)",
    "Cacaritan",
    "Caingal",
    "Calobaoan",
    "Calomboyan",
    "Caoayan-Kiling",
    "Capataan",
    "Cobol",
    "Coliling",
    "Cruz",
    "Doyong",
    "Gamata",
    "Guelew",
    "Ilang",
    "Inerangan",
    "Isla",
    "Libas",
    "Lilimasan",
    "Longos",
    "Lucban (Pob.)",
    "M. Soriano",
    "Mabalbalino",
    "Mabini (Pob.)",
    "Magtaking",
    "Malacañang",
    "Maliwara",
    "Mamarlao",
    "Manzon",
    "Matagdem",
    "Mestizo Norte",
    "Naguilayan",
    "Nilentap",
    "Padilla-Gomez",
    "Pagal",
    "Paitan-Panoypoy",
    "Palaming",
    "Palaris (Pob.)",
    "Palospos",
    "Pangalangan",
    "Pangoloan",
    "Pangpang",
    "Parayao",
    "Payapa",
    "Payar",
    "Perez Boulevard (Pob.)",
    "PNR Station Site",
    "Polo",
    "Quezon Boulevard (Pob.)",
    "Quintong",
    "Rizal (Pob.)",
    "Roxas Boulevard (Pob.)",
    "Salinap",
    "San Juan",
    "San Pedro-Taloy",
    "Sapinit",
    "Supo",
    "Talang",
    "Tamayo",
    "Tandang Sora",
    "Tandoc",
    "Tarece",
    "Tarectec",
    "Tayambani",
    "Tebag",
    "Turac",
  ],
  "0105533000": [
    "Alacan",
    "Ambalangan-Dalin",
    "Angio",
    "Anonang",
    "Aramal",
    "Bigbiga",
    "Binday",
    "Bolaoen",
    "Bolasi",
    "Cabaruan",
    "Cayanga",
    "Colisao",
    "Gomot",
    "Inmalog",
    "Inmalog Norte",
    "Lekep-Butao",
    "Lipit-Tomeeng",
    "Longos",
    "Longos Proper",
    "Longos-Amangonan-Parac-Parac Fabrica",
    "Mabilao",
    "Nibaliw Central",
    "Nibaliw East",
    "Nibaliw Magliba",
    "Nibaliw Narvarte",
    "Nibaliw Vidal",
    "Palapad",
    "Poblacion",
    "Rabon",
    "Sagud-Bahley",
    "Sobol",
    "Tempra-Guilig",
    "Tiblong",
    "Tocok",
  ],
  "0105534000": [
    "Awai",
    "Bagong Pag-asa",
    "Bolo",
    "Capaoay (Pob.)",
    "Casibong",
    "Guibel",
    "Imelda",
    "Labney",
    "Lobong",
    "Macayug",
    "Magsaysay",
    "San Guillermo",
    "San Jose",
    "San Juan",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Santa Maria",
    "Santo Tomas",
  ],
  "0105535000": [
    "Cabacaraan",
    "Cabaritan",
    "Flores",
    "Guiset Norte (Pob.)",
    "Guiset Sur (Pob.)",
    "Lapalo",
    "Nagsaag",
    "Narra",
    "San Antonio-Arzadon",
    "San Bonifacio",
    "San Juan",
    "San Roque",
    "San Vicente",
    "Santo Domingo",
  ],
  "0105536000": [
    "Bensican",
    "Cabitnongan",
    "Caboloan",
    "Cacabugaoan",
    "Calanutian",
    "Calaocan",
    "Camanggaan",
    "Camindoroan",
    "Casaratan",
    "Dalumpinas",
    "Fianza",
    "Lungao",
    "Malico",
    "Malilion",
    "Nagkaysa",
    "Nining",
    "Poblacion East",
    "Poblacion West",
    "Salingcob",
    "Salpad",
    "San Felipe East",
    "San Felipe West",
    "San Isidro",
    "San Jose",
    "San Rafael Centro",
    "San Rafael East",
    "San Rafael West",
    "San Roque",
    "Santa Maria East",
    "Santa Maria West",
    "Santo Tomas",
    "Siblot",
    "Sobol",
  ],
  "0105537000": [
    "Alac",
    "Baligayan",
    "Bantog",
    "Bolintaguen",
    "Cabalaoangan",
    "Cabangaran",
    "Calomboyan",
    "Carayacan",
    "Casantamarian",
    "Gonzalo",
    "Labuan",
    "Lagasit",
    "Lumayao",
    "Mabini",
    "Mantacdang",
    "Nangapugan",
    "Poblacion Zone I",
    "Poblacion Zone II",
    "Poblacion Zone III",
    "San Pedro",
    "Ungib",
  ],
  "0105538000": [
    "Alibago",
    "Balingueo",
    "Banaoang",
    "Banzal",
    "Botao",
    "Cablong",
    "Carusocan",
    "Dalongue",
    "Erfe",
    "Gueguesangen",
    "Leet",
    "Malanay",
    "Maningding",
    "Maronong",
    "Maticmatic",
    "Minien East",
    "Minien West",
    "Nilombot",
    "Patayac",
    "Payas",
    "Poblacion Norte",
    "Poblacion Sur",
    "Primicias",
    "Sapang",
    "Sonquil",
    "Tebag East",
    "Tebag West",
    "Tuliao",
    "Ventinilla",
  ],
  "0105539000": [
    "Bal-loy",
    "Bantog",
    "Caboluan",
    "Cal-litang",
    "Capandanan",
    "Cauplasan",
    "Dalayap",
    "Libsong",
    "Namagbagan",
    "Paitan",
    "Pataquid",
    "Pilar",
    "Poblacion East",
    "Poblacion West",
    "Pugot",
    "Samon",
    "San Alejandro",
    "San Mariano",
    "San Pablo",
    "San Patricio",
    "San Vicente",
    "Santa Cruz",
    "Santa Rosa",
  ],
  "0105540000": [
    "La Luna",
    "Poblacion East",
    "Poblacion West",
    "Salvacion",
    "San Agustin",
    "San Antonio",
    "San Jose",
    "San Marcos",
    "Santo Domingo",
    "Santo Niño",
  ],
  "0105541000": [
    "Agat",
    "Alibeng",
    "Amagbagan",
    "Artacho",
    "Asan Norte",
    "Asan Sur",
    "Bantay Insik",
    "Bila",
    "Binmeckeg",
    "Bulaoen East",
    "Bulaoen West",
    "Cabaritan",
    "Calunetan",
    "Camangaan",
    "Cauringan",
    "Dungon",
    "Esperanza",
    "Inmalog",
    "Killo",
    "Labayug",
    "Paldit",
    "Pindangan",
    "Pinmilapil",
    "Poblacion Central",
    "Poblacion Norte",
    "Poblacion Sur",
    "Sagunto",
    "Tara-tara",
  ],
  "0105542000": [
    "Baquioen",
    "Baybay Norte",
    "Baybay Sur",
    "Bolaoen",
    "Cabalitian",
    "Calumbuyan",
    "Camagsingalan",
    "Caoayan",
    "Capantolan",
    "Macaycayawan",
    "Paitan East",
    "Paitan West",
    "Pangascasan",
    "Poblacion",
    "Santo Domingo",
    "Seselangen",
    "Sioasio East",
    "Sioasio West",
    "Victoria",
  ],
  "0105543000": [
    "Agno",
    "Amistad",
    "Barangay A (Pob.)",
    "Barangay B (Pob.)",
    "Barangay C (Pob.)",
    "Barangay D (Pob.)",
    "Barangobong",
    "C. Lichauco",
    "Carriedo",
    "Evangelista",
    "Guzon",
    "Lawak",
    "Legaspi",
    "Libertad",
    "Magallanes",
    "Panganiban",
    "Saleng",
    "Santo Domingo",
    "Toketec",
    "Trenchera",
    "Zamora",
  ],
  "0105544000": [
    "Abot Molina",
    "Alo-o",
    "Amaronan",
    "Annam",
    "Bantug",
    "Baracbac",
    "Barat",
    "Buenavista",
    "Cabalitian",
    "Cabangaran",
    "Cabaruan",
    "Cabatuan",
    "Cadiz",
    "Calitlitan",
    "Capas",
    "Carayungan Sur",
    "Carosalesan",
    "Casilan",
    "Caurdanetaan",
    "Concepcion",
    "Decreto",
    "Del Rosario",
    "Diaz",
    "Diket",
    "Don Justo Abalos",
    "Don Montano",
    "Esperanza",
    "Evangelista",
    "Flores",
    "Fulgosino",
    "Gonzales",
    "La Paz",
    "Labuan",
    "Lauren",
    "Lubong",
    "Luna Este",
    "Luna Weste",
    "Mantacdang",
    "Maseil-seil",
    "Nampalcan",
    "Nancalabasaan",
    "Pangangaan",
    "Papallasen",
    "Pemienta",
    "Poblacion East",
    "Poblacion West",
    "Prado",
    "Resurreccion",
    "Ricos",
    "San Andres",
    "San Juan",
    "San Leon",
    "San Pablo",
    "San Vicente",
    "Santa Maria",
    "Santa Rosa",
    "Sinabaan",
    "Tanggal Sawang",
  ],
  "0105545000": [
    "Angatel",
    "Balangay",
    "Batangcaoa",
    "Baug",
    "Bayaoas",
    "Bituag",
    "Camambugan",
    "Dalangiring",
    "Duplac",
    "Galarin",
    "Gueteb",
    "Malaca",
    "Malayo",
    "Malibong",
    "Pasibi East",
    "Pasibi West",
    "Pisuac",
    "Poblacion",
    "Real",
    "Salavante",
    "Sawat",
  ],
  "0105546000": [
    "Anonas",
    "Bactad East",
    "Bayaoas",
    "Bolaoen",
    "Cabaruan",
    "Cabuloan",
    "Camanang",
    "Camantiles",
    "Casantaan",
    "Catablan",
    "Cayambanan",
    "Consolacion",
    "Dilan Paurido",
    "Dr. Pedro T. Orata",
    "Labit Proper",
    "Labit West",
    "Mabanogbog",
    "Macalong",
    "Nancalobasaan",
    "Nancamaliran East",
    "Nancamaliran West",
    "Nancayasan",
    "Oltama",
    "Palina East",
    "Palina West",
    "Pinmaludpod",
    "Poblacion",
    "San Jose",
    "San Vicente",
    "Santa Lucia",
    "Santo Domingo",
    "Sugcong",
    "Tipuso",
    "Tulong",
  ],
  "0105547000": [
    "Amamperez",
    "Bacag",
    "Barangobong",
    "Barraca",
    "Capulaan",
    "Caramutan",
    "La Paz",
    "Labit",
    "Lipay",
    "Lomboy",
    "Piaz",
    "Puelay",
    "San Blas",
    "San Nicolas",
    "Tombod",
    "Unzad",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)",
    "Zone V (Pob.)",
  ],
  "0105548000": [
    "Anis",
    "Balligi",
    "Banuar",
    "Botique",
    "Caaringayan",
    "Cabilaoan West",
    "Cabulalaan",
    "Calaoagan",
    "Calmay",
    "Casampagaan",
    "Casanestebanan",
    "Casantiagoan",
    "Domingo Alarcio",
    "Inmanduyan",
    "Lebueg",
    "Maraboc",
    "Nanbagatan",
    "Panaga",
    "Poblacion",
    "Talogtog",
    "Turko",
    "Yatyat",
  ],
};
