/** GENERATED — Region II: 2311 barangays across 93 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "0200901000": [
    "Chanarian",
    "Ihubok I",
    "Ihubok II",
    "Kayhuvokan",
    "San Antonio",
    "San Joaquin",
  ],
  "0200902000": [
    "Raele",
    "San Rafael",
    "Santa Lucia",
    "Santa Maria",
    "Santa Rosa",
  ],
  "0200903000": ["Radiwan", "Salagao", "San Vicente", "Tuhel (Pob.)"],
  "0200904000": ["Hañib", "Kaumbakan", "Panatayan", "Uvoy (Pob.)"],
  "0200905000": [
    "Chavayan",
    "Malakdang (Pob.)",
    "Nakanmuan",
    "Savidug",
    "Sinakan (Pob.)",
    "Sumnanga",
  ],
  "0200906000": ["Imnajbu", "Itbud", "Kayuganan (Pob.)", "Kayvaluganan (Pob.)"],
  "0201501000": [
    "Alinunu",
    "Bagu",
    "Banguian",
    "Calog Norte",
    "Calog Sur",
    "Canayun",
    "Centro (Pob.)",
    "Dana-Ili",
    "Guiddam",
    "Libertad",
    "Lucban",
    "Pinili",
    "San Agustin",
    "San Julian",
    "Santa Filomena",
    "Santa Rosa",
    "Santo Tomas",
    "Siguiran",
    "Simayung",
    "Sirit",
  ],
  "0201502000": [
    "Abbeg",
    "Afusing Bato",
    "Afusing Daga",
    "Agani",
    "Baculod",
    "Baybayog",
    "Cabuluan",
    "Calantac",
    "Carallangan",
    "Centro Norte (Pob.)",
    "Centro Sur (Pob.)",
    "Dalaoig",
    "Damurog",
    "Jurisdiction",
    "Malalatan",
    "Maraburab",
    "Masin",
    "Pagbangkeruan",
    "Pared",
    "Piggatan",
    "Pinopoc",
    "Pussian",
    "San Esteban",
    "Tamban",
    "Tupang",
  ],
  "0201503000": [
    "Bessang",
    "Binobongan",
    "Bulo",
    "Burot",
    "Capagaran",
    "Capalutan",
    "Capanickian Norte",
    "Capanickian Sur",
    "Cataratan",
    "Centro East (Pob.)",
    "Centro West (Pob.)",
    "Daan-Ili",
    "Dagupan",
    "Dalayap",
    "Gagaddangan",
    "Iringan",
    "Labben",
    "Maluyo",
    "Mapurao",
    "Matucay",
    "Nagattatan",
    "Pacac",
    "San Juan",
    "Silagan",
    "Tamboli",
    "Tubel",
    "Utan",
  ],
  "0201504000": [
    "Abolo",
    "Agguirit",
    "Alituntung",
    "Annabuculan",
    "Annafatan",
    "Anquiray",
    "Babayuan",
    "Baccuit",
    "Bacring",
    "Baculud",
    "Balauini",
    "Bauan",
    "Bayabat",
    "Calamagui",
    "Calintaan",
    "Caratacat",
    "Casingsingan Norte",
    "Casingsingan Sur",
    "Catarauan",
    "Centro",
    "Concepcion",
    "Cordova",
    "Dadda",
    "Dafunganay",
    "Dugayung",
    "Estefania",
    "Gabut",
    "Gangauan",
    "Goran",
    "Jurisdiccion",
    "La Suerte",
    "Logung",
    "Magogod",
    "Manalo",
    "Marobbob",
    "Masical",
    "Monte Alegre",
    "Nabbialan",
    "Nagsabaran",
    "Nangalasauan",
    "Nanuccauan",
    "Pacac-Grande",
    "Pacac-Pequeño",
    "Palacu",
    "Palayag",
    "Tana",
    "Unag",
  ],
  "0201505000": [
    "Backiling",
    "Bangag",
    "Binalan",
    "Bisagu",
    "Bukig",
    "Bulala Norte",
    "Bulala Sur",
    "Caagaman",
    "Centro 1 (Pob.)",
    "Centro 10 (Pob.)",
    "Centro 11 (Pob.)",
    "Centro 12 (Pob.)",
    "Centro 13 (Pob.)",
    "Centro 14 (Pob.)",
    "Centro 15 (Pob.)",
    "Centro 2 (Pob.)",
    "Centro 3 (Pob.)",
    "Centro 4 (Pob.)",
    "Centro 5 (Pob.)",
    "Centro 6 (Pob.)",
    "Centro 7 (Pob.)",
    "Centro 8 (Pob.)",
    "Centro 9 (Pob.)",
    "Dodan",
    "Fuga Island",
    "Gaddang",
    "Linao",
    "Mabanguc",
    "Macanaya",
    "Maura",
    "Minanga",
    "Navagan",
    "Paddaya",
    "Paruddun Norte",
    "Paruddun Sur",
    "Plaza",
    "Punta",
    "San Antonio",
    "Sanja",
    "Tallungan",
    "Toran",
    "Zinarag",
  ],
  "0201506000": [
    "Adaoag",
    "Agaman",
    "Agaman Norte",
    "Agaman Sur",
    "Alba",
    "Annayatan",
    "Asassi",
    "Asinga-Via",
    "Awallan",
    "Bacagan",
    "Bagunot",
    "Barsat East",
    "Barsat West",
    "Bitag Grande",
    "Bitag Pequeño",
    "Bunugan",
    "C. Verzosa",
    "Canagatan",
    "Carupian",
    "Catugay",
    "Dabbac Grande",
    "Dalin",
    "Dalla",
    "Hacienda Intal",
    "Ibulo",
    "Imurong",
    "J. Pallagao",
    "Lasilat",
    "Mabini",
    "Masical",
    "Mocag",
    "Nangalinan",
    "Poblacion",
    "Remus",
    "San Antonio",
    "San Francisco",
    "San Isidro",
    "San Jose",
    "San Miguel",
    "San Vicente",
    "Santa Margarita",
    "Santor",
    "Taguing",
    "Taguntungan",
    "Tallang",
    "Taytay",
    "Temblique",
    "Tungel",
  ],
  "0201507000": [
    "Ammubuan",
    "Baran",
    "Cabaritan East",
    "Cabaritan West",
    "Cabayu",
    "Cabuluan East",
    "Cabuluan West",
    "Centro East (Pob.)",
    "Centro West (Pob.)",
    "Fugu",
    "Mabuttal East",
    "Mabuttal West",
    "Nararagan",
    "Palloc",
    "Payagan East",
    "Payagan West",
    "San Juan",
    "Santa Cruz",
    "Zitanga",
  ],
  "0201508000": [
    "Alucao Weste",
    "Ballang",
    "Balza",
    "Cabaritan",
    "Calamegatan",
    "Centro (Pob.)",
    "Centro West",
    "Dalaya",
    "Fula",
    "Leron",
    "M. Antiporda",
    "Maddalero",
    "Mala Este",
    "Mala Weste",
    "Minanga Este",
    "Minanga Weste",
    "Paddaya Este",
    "Paddaya Weste",
    "Pattao",
    "Quinawegan",
    "Remebella",
    "San Isidro",
    "San Juan",
    "San Vicente",
    "Santa Isabel",
    "Santa Maria",
    "Tabbac",
    "Villa Cielo",
    "Villa Gracia",
    "Villa Leonora",
  ],
  "0201509000": [
    "Babuyan Claro",
    "Balatubat",
    "Cabudadan",
    "Centro II",
    "Dadao",
    "Dalupiri",
    "Dibay",
    "Dilam",
    "Magsidel",
    "Minabel",
    "Naguilian",
    "Poblacion",
  ],
  "0201510000": [
    "Abagao",
    "Afunan Cabayu",
    "Agusi",
    "Alilinu",
    "Baggao",
    "Bantay",
    "Bulala",
    "Casili Norte",
    "Casili Sur",
    "Catotoran Norte",
    "Catotoran Sur",
    "Centro Norte (Pob.)",
    "Centro Sur (Pob.)",
    "Cullit",
    "Dacal-Lafugu",
    "Dammang Norte",
    "Dammang Sur",
    "Dugo",
    "Fusina",
    "Gang-ngo",
    "Jurisdiccion",
    "Luec",
    "Minanga",
    "Paragat",
    "Sapping",
    "Tagum",
    "Tuluttuging",
    "Ziminila",
  ],
  "0201511000": [
    "Alimoan",
    "Bacsay Cataraoan Norte",
    "Bacsay Cataraoan Sur",
    "Bacsay Mapulapula",
    "Bilibigao",
    "Buenavista",
    "Cadcadir East",
    "Cadcadir West",
    "Camalaggoan/D Leaño",
    "Capannikian",
    "Centro I (Pob.)",
    "Centro II (Pob.)",
    "Centro III",
    "Centro IV",
    "Centro V",
    "Centro VI",
    "Centro VII",
    "Centro VIII",
    "Culao",
    "Dibalio",
    "Kilkiling",
    "Lablabig",
    "Luzon",
    "Mabnang",
    "Magdalena",
    "Malilitao",
    "Nagsabaran",
    "Pata East",
    "Pata West",
    "Pinas",
    "San Antonio",
    "San Isidro",
    "San Vicente",
    "Santa Maria",
    "Santiago",
    "Santo Niño",
    "Santo Tomas",
    "Tabbugan",
    "Taggat Norte",
    "Taggat Sur",
    "Union",
  ],
  "0201512000": [
    "Alibago",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III",
    "Barangay III-A",
    "Barangay IV (Pob.)",
    "Batu",
    "Divisoria",
    "Inga",
    "Lanna",
    "Lemu Norte",
    "Lemu Sur",
    "Liwan Norte",
    "Liwan Sur",
    "Maddarulug Norte",
    "Maddarulug Sur",
    "Magalalag East",
    "Magalalag West",
    "Maracuru",
    "Roma Norte",
    "Roma Sur",
    "San Antonio",
  ],
  "0201513000": [
    "Abra",
    "Aguiguican",
    "Bangatan Ngagan",
    "Baracaoit",
    "Baraoidan",
    "Barbarit",
    "Basao",
    "Bolos Point",
    "Cabayu",
    "Calaoagan Bassit",
    "Calaoagan Dackel",
    "Capiddigan",
    "Capissayan Norte",
    "Capissayan Sur",
    "Casicallan Norte",
    "Casicallan Sur",
    "Centro Norte (Pob.)",
    "Centro Sur (Pob.)",
    "Cullit",
    "Cumao",
    "Cunig",
    "Dummun",
    "Fugu",
    "Ganzano",
    "Guising",
    "L. Adviento",
    "Langgan",
    "Lapogan",
    "Mabuno",
    "Nabaccayan",
    "Naddungan",
    "Nagatutuan",
    "Nassiping",
    "Newagac",
    "Palagao Norte",
    "Palagao Sur",
    "Piña Este",
    "Piña Weste",
    "San Carlos",
    "San Vicente",
    "Santa Maria",
    "Sidem",
    "Sta. Ana",
    "T. Elizaga",
    "Tagumay",
    "Takiki",
    "Taligan",
    "Tanglagan",
    "Tubungan Este",
    "Tubungan Weste",
  ],
  "0201514000": [
    "Amunitan",
    "Batangan",
    "Baua",
    "Cabanbanan Norte",
    "Cabanbanan Sur",
    "Cabiraoan",
    "Calayan",
    "Callao",
    "Caroan",
    "Casitan",
    "Flourishing (Pob.)",
    "Ipil",
    "Isca",
    "Magrafil",
    "Minanga",
    "Paradise (Pob.)",
    "Pateng",
    "Progressive (Pob.)",
    "Rebecca",
    "San Jose",
    "Santa Clara",
    "Santa Cruz",
    "Santa Maria",
    "Smart (Pob.)",
    "Tapel",
  ],
  "0201515000": [
    "Ajat (Pob.)",
    "Atulu",
    "Baculud",
    "Bayo",
    "Campo",
    "Dumpao",
    "Gammad",
    "Garab",
    "Malabbac",
    "Manaoag",
    "Minanga Norte",
    "Minanga Sur",
    "Nattanzan (Pob.)",
    "Redondo",
    "Salamague",
    "San Esteban",
    "San Isidro",
    "San Lorenzo",
    "San Vicente",
    "Santa Barbara",
    "Santa Rosa",
    "Santa Teresa",
    "Santiago",
  ],
  "0201516000": [
    "Abagao",
    "Alaguia",
    "Bagumbayan",
    "Bangag",
    "Bical",
    "Bicud",
    "Binag",
    "Cabayabasan",
    "Cagoran",
    "Cambong",
    "Catayauan",
    "Catugan",
    "Centro (Pob.)",
    "Cullit",
    "Dagupan",
    "Dalaya",
    "Fabrica",
    "Fusina",
    "Jurisdiction",
    "Lalafugan",
    "Logac",
    "Magallungon (Sta. Teresa)",
    "Magapit",
    "Malanao",
    "Maxingal",
    "Naguilian",
    "Paranum",
    "Rosario",
    "San Antonio",
    "San Jose",
    "San Juan",
    "San Lorenzo",
    "San Mariano",
    "Sta. Maria",
    "Tucalana",
  ],
  "0201517000": [
    "Aggunetan",
    "Alannay",
    "Battalan",
    "Cabatacan East",
    "Cabatacan West",
    "Calapangan Norte",
    "Calapangan Sur",
    "Callao Norte",
    "Callao Sur",
    "Cataliganan",
    "Centro I (Pob.)",
    "Centro II (Pob.)",
    "Centro III (Pob.)",
    "Finugo Norte",
    "Gabun",
    "Ignacio Jurado",
    "Magsaysay",
    "Malinta",
    "Minanga Norte",
    "Minanga Sur",
    "Nabannagan East",
    "Nabannagan West",
    "New Orlins",
    "Nicolas Agatep",
    "Peru",
    "San Pedro",
    "Sicalao",
    "Tagao",
    "Tucalan Passing",
    "Viga",
  ],
  "0201518000": [
    "Abanqueruan",
    "Allasitan",
    "Bagu",
    "Balingit",
    "Bidduang",
    "Cabaggan",
    "Capalalian",
    "Casitan",
    "Centro (Pob.)",
    "Curva",
    "Gattu",
    "Masi",
    "Nagattatan",
    "Nagtupacan",
    "San Juan",
    "Santa Cruz",
    "Tabba",
    "Tupanna",
  ],
  "0201519000": [
    "Aggugaddan",
    "Alimannao",
    "Baliuag",
    "Bical",
    "Bugatay",
    "Buyun",
    "Cabasan",
    "Cabbo",
    "Callao",
    "Camasi",
    "Centro (Pob.)",
    "Dodan",
    "Lapi",
    "Malibabag",
    "Manga",
    "Minanga",
    "Nabbabalayan",
    "Nanguilattan",
    "Nannarian",
    "Parabba",
    "Patagueleg",
    "Quibal",
    "San Roque",
    "Sisim",
  ],
  "0201520000": [
    "Apayao",
    "Aquib",
    "Baung",
    "Calaoagan",
    "Catarauan",
    "Dugayung",
    "Gumarueng",
    "Macapil",
    "Maguilling",
    "Minanga",
    "Poblacion I",
    "Poblacion II",
    "Santa Barbara",
    "Santo Domingo",
    "Sicatna",
    "Villa Rey",
    "Villa Reyno",
    "Warat",
  ],
  "0201521000": [
    "Anagguan",
    "Anungu",
    "Anurturu",
    "Baluncanag",
    "Battut",
    "Batu",
    "Bural",
    "Cambabangan",
    "Capacuan",
    "Dunggan",
    "Duyun",
    "Gaddangao",
    "Gaggabutan East",
    "Gaggabutan West",
    "Illuru Norte",
    "Illuru Sur",
    "Lattut",
    "Linno",
    "Liwan",
    "Mabbang",
    "Masi",
    "Mauanan",
    "Minanga",
    "Nanauatan",
    "Nanungaran",
    "Pasingan",
    "Poblacion",
    "San Juan",
    "Sinicking",
  ],
  "0201522000": [
    "Bangan",
    "Callungan",
    "Centro I (Pob.)",
    "Centro II (Pob.)",
    "Dacal",
    "Dagueray",
    "Dammang",
    "Kittag",
    "Langagan",
    "Magacan",
    "Marzan",
    "Masisit",
    "Nagrangtayan",
    "Namuac",
    "San Andres",
    "Santiago",
    "Santor",
    "Tokitok",
  ],
  "0201523000": [
    "Batu-Parada",
    "Casagan",
    "Casambalangan",
    "Centro (Pob.)",
    "Diora-Zinungan",
    "Dungeg",
    "Kapanikian",
    "Marede",
    "Palawig",
    "Patunungan",
    "Rapuli",
    "San Vicente",
    "Santa Clara",
    "Santa Cruz",
    "Tangatan",
    "Visitacion (Pob.)",
  ],
  "0201524000": [
    "Cadongdongan",
    "Capacuan",
    "Centro I (Pob.)",
    "Centro II (Pob.)",
    "Macatel",
    "Portabaga",
    "Salungsong",
    "San Juan",
    "San Miguel",
    "Sicul",
  ],
  "0201525000": [
    "Alucao",
    "Aridowen",
    "Buyun",
    "Caniugan",
    "Centro East (Pob.)",
    "Centro West",
    "Dungeg",
    "Luga",
    "Masi",
    "Mission",
    "Simbaluca",
    "Simpatuyo",
    "Villa",
  ],
  "0201526000": [
    "Abariongan Ruar",
    "Abariongan Uneg",
    "Balagan",
    "Balanni",
    "Cabayo",
    "Calapangan",
    "Calassitan",
    "Campo",
    "Centro Norte (Pob.)",
    "Centro Sur (Pob.)",
    "Dungao",
    "Lattac",
    "Lipatan",
    "Lubo",
    "Mabitbitnong",
    "Mapitac",
    "Masical",
    "Matalao",
    "Nag-uma",
    "Namuccayan",
    "Niug Norte",
    "Niug Sur",
    "Palusao",
    "San Manuel",
    "San Roque",
    "Santa Felicitas",
    "Santa Maria",
    "Sidiran",
    "Tabang",
    "Tamucco",
    "Virginia",
  ],
  "0201527000": [
    "Andarayan North",
    "Andarayan South",
    "Bangag",
    "Bantay",
    "Basi East",
    "Basi West",
    "Bauan East",
    "Bauan West",
    "Cadaanan",
    "Calamagui",
    "Calillauan",
    "Carilucud",
    "Cattaran",
    "Centro Northeast (Pob.)",
    "Centro Northwest (Pob.)",
    "Centro Southeast (Pob.)",
    "Centro Southwest (Pob.)",
    "Dassun",
    "Furagui",
    "Gadu",
    "Gen. Eulogio Balao",
    "Iraga",
    "Lanna",
    "Lannig",
    "Lingu",
    "Maddarulug",
    "Maguirig",
    "Malalam-Malacabibi",
    "Nabbotuan",
    "Nangalisan",
    "Natappian East",
    "Natappian West",
    "Padul",
    "Palao",
    "Parug-parug",
    "Pataya",
    "Sampaguita",
    "Ubong",
  ],
  "0201528000": [
    "Accusilian",
    "Alabiao",
    "Alabug",
    "Angang",
    "Bagumbayan",
    "Barancuag",
    "Battung",
    "Bicok",
    "Bugnay",
    "Bulagao",
    "Cagumitan",
    "Cato",
    "Culung",
    "Dagupan",
    "Fugu",
    "Lakambini",
    "Lallayug",
    "Malalinta",
    "Malummin",
    "Mambacag",
    "Mungo",
    "Naruangan",
    "Palca",
    "Pata",
    "Poblacion I",
    "Poblacion II",
    "San Juan",
    "San Luis",
    "San Vicente",
    "Santo Tomas",
    "Taribubu",
    "Villa Laida",
  ],
  "0201529000": [
    "Annafunan East",
    "Annafunan West",
    "Atulayan Norte",
    "Atulayan Sur",
    "Bagay",
    "Buntun",
    "Caggay",
    "Capatan",
    "Carig",
    "Caritan Centro",
    "Caritan Norte",
    "Caritan Sur",
    "Cataggaman Nuevo",
    "Cataggaman Pardo",
    "Cataggaman Viejo",
    "Centro 1 (Pob.)",
    "Centro 10 (Pob.)",
    "Centro 11 (Pob.)",
    "Centro 12 (Pob.)",
    "Centro 2 (Pob.)",
    "Centro 3 (Pob.)",
    "Centro 4 (Pob.)",
    "Centro 5 (Pob.)",
    "Centro 6 (Pob.)",
    "Centro 7 (Pob.)",
    "Centro 8 (Pob.)",
    "Centro 9 (Pob.)",
    "Dadda",
    "Gosi Norte",
    "Gosi Sur",
    "Larion Alto",
    "Larion Bajo",
    "Leonarda",
    "Libag Norte",
    "Libag Sur",
    "Linao East",
    "Linao Norte",
    "Linao West",
    "Namabbalan Norte",
    "Namabbalan Sur",
    "Pallua Norte",
    "Pallua Sur",
    "Pengue",
    "Reyes",
    "San Gabriel",
    "Tagga",
    "Tanza",
    "Ugac Norte",
    "Ugac Sur",
  ],
  "0203101000": [
    "Amistad",
    "Antonino (Pob.)",
    "Apanay",
    "Aurora",
    "Bagnos",
    "Bagong Sikat",
    "Bantug-Petines",
    "Bonifacio",
    "Burgos",
    "Calaocan (Pob.)",
    "Callao",
    "Dagupan",
    "Inanama",
    "Linglingay",
    "M.H. del Pilar",
    "Mabini",
    "Magsaysay (Pob.)",
    "Mataas na Kahoy",
    "Paddad",
    "Rizal",
    "Rizaluna",
    "Salvacion",
    "San Antonio (Pob.)",
    "San Fernando",
    "San Francisco",
    "San Juan",
    "San Pablo",
    "San Pedro",
    "Santa Cruz",
    "Santa Maria",
    "Santo Domingo",
    "Santo Tomas",
    "Victoria",
    "Zamora",
  ],
  "0203102000": [
    "Allangigan",
    "Aniog",
    "Baniket",
    "Bannawag",
    "Bantug",
    "Barangcuag",
    "Baui",
    "Bonifacio",
    "Buenavista",
    "Bunnay",
    "Calabayan-Minanga",
    "Calaccab",
    "Calaocan",
    "Campanario",
    "Canangan",
    "Centro I (Pob.)",
    "Centro II (Pob.)",
    "Centro III (Pob.)",
    "Consular",
    "Cumu",
    "Dalakip",
    "Dalenat",
    "Dipaluda",
    "Duroc",
    "Esperanza",
    "Fugaru",
    "Ingud Norte",
    "Ingud Sur",
    "Kalusutan",
    "La Suerte",
    "Liwliwa",
    "Lomboy",
    "Loria",
    "Lourdes",
    "Mabuhay",
    "Macalauat",
    "Macaniao",
    "Malannao",
    "Malasin",
    "Mangandingay",
    "Minanga Proper",
    "Pappat",
    "Pissay",
    "Ramona",
    "Rancho Bassit",
    "Rang-ayan",
    "Salay",
    "San Ambrocio",
    "San Guillermo",
    "San Isidro",
    "San Marcelo",
    "San Roque",
    "San Vicente",
    "Santo Niño",
    "Saranay",
    "Sinabbaran",
    "Victory",
    "Viga",
    "Villa Domingo",
  ],
  "0203103000": [
    "Apiat",
    "Bagnos",
    "Bagong Tanza",
    "Ballesteros",
    "Bannagao",
    "Bannawag",
    "Bolinao",
    "Caipilan",
    "Camarunggayan",
    "Dalig-Kalinga",
    "Diamantina",
    "Divisoria",
    "Esperanza East",
    "Esperanza West",
    "Kalabaza",
    "Macatal",
    "Malasin",
    "Nampicuan",
    "Panecien",
    "Rizaluna",
    "San Andres",
    "San Jose (Pob.)",
    "San Juan (Pob.)",
    "San Pedro-San Pablo (Pob.)",
    "San Rafael",
    "San Ramon",
    "Santa Rita",
    "Santa Rosa",
    "Saranay",
    "Sili",
    "Victoria",
    "Villa Fugu",
    "Villa Nuesa",
  ],
  "0203104000": [
    "Andabuen",
    "Ara",
    "Balliao",
    "Binogtungan",
    "Capuseran",
    "Dagupan",
    "Danipa",
    "District I (Pob.)",
    "District II (Pob.)",
    "Gomez",
    "Guilingan",
    "La Salette",
    "Lucban",
    "Makindol",
    "Maluno Norte",
    "Maluno Sur",
    "Nacalma",
    "New Magsaysay",
    "Placer",
    "Punit",
    "San Carlos",
    "San Francisco",
    "Santa Cruz",
    "Santiago",
    "Sevillana",
    "Sinipit",
    "Villaluz",
    "Yeban Norte",
    "Yeban Sur",
  ],
  "0203105000": [
    "Bacnor East",
    "Bacnor West",
    "Caliguian (Pob.)",
    "Catabban",
    "Cullalabo Del Norte",
    "Cullalabo Del Sur",
    "Cullalabo San Antonio",
    "Dalig",
    "Malasin",
    "Masigun",
    "Raniag",
    "San Bonifacio",
    "San Miguel",
    "San Roque",
  ],
  "0203106000": [
    "Aggub",
    "Anao",
    "Angancasilian",
    "Balasig",
    "Cansan",
    "Casibarag Norte",
    "Casibarag Sur",
    "Catabayungan",
    "Centro (Pob.)",
    "Cubag",
    "Garita",
    "Luquilu",
    "Mabangug",
    "Magassi",
    "Masipi East",
    "Masipi West",
    "Ngarag",
    "Pilig Abajo",
    "Pilig Alto",
    "San Antonio",
    "San Bernardo",
    "San Juan",
    "Saui",
    "Tallag",
    "Ugad",
    "Union",
  ],
  "0203107000": [
    "Calaocan",
    "Canan",
    "Centro (Pob.)",
    "Culing Centro",
    "Culing East",
    "Culing West",
    "Del Corpuz",
    "Del Pilar",
    "Diamantina",
    "La Paz",
    "Luzon",
    "Macalaoat",
    "Magdalena",
    "Magsaysay",
    "Namnama",
    "Nueva Era",
    "Paraiso",
    "Rang-ay",
    "Sampaloc",
    "San Andres",
    "Saranay",
    "Tandul",
  ],
  "0203108000": [
    "Alicaocao",
    "Alinam",
    "Amobocan",
    "Andarayan",
    "Baculod",
    "Baringin Norte",
    "Baringin Sur",
    "Buena Suerte",
    "Bugallon",
    "Buyon",
    "Cabaruan",
    "Cabugao",
    "Carabatan Bacareno",
    "Carabatan Chica",
    "Carabatan Grande",
    "Carabatan Punta",
    "Casalatan",
    "Cassap Fuera",
    "Catalina",
    "Culalabat",
    "Dabburab",
    "De Vera",
    "Dianao",
    "Disimuray",
    "District I (Pob.)",
    "District II (Pob.)",
    "District III (Pob.)",
    "Duminit",
    "Faustino",
    "Gagabutan",
    "Gappal",
    "Guayabal",
    "Labinab",
    "Linglingay",
    "Mabantad",
    "Maligaya",
    "Manaoag",
    "Marabulig I",
    "Marabulig II",
    "Minante I",
    "Minante II",
    "Naganacan",
    "Nagcampegan",
    "Nagrumbuan",
    "Nungnungan I",
    "Nungnungan II",
    "Pinoma",
    "Rizal",
    "Rogus",
    "San Antonio",
    "San Fermin",
    "San Francisco",
    "San Isidro",
    "San Luis",
    "San Pablo",
    "Santa Luciana",
    "Santa Maria",
    "Sillawit",
    "Sinippil",
    "Tagaran",
    "Turayong",
    "Union",
    "Villa Concepcion",
    "Villa Luna",
    "Villaflor",
  ],
  "0203109000": [
    "Aguinaldo",
    "Anonang",
    "Calimaturod",
    "Camarao",
    "Capirpiriwan",
    "Caquilingan",
    "Dallao",
    "Gayong",
    "Laurel",
    "Magsaysay",
    "Malapat",
    "Osmena",
    "Quezon",
    "Quirino",
    "Rizaluna",
    "Roxas Pob.",
    "Sagat",
    "San Juan",
    "Taliktik",
    "Tanggal",
    "Tarinsing",
    "Turod Norte",
    "Turod Sur",
    "Villamarzo",
    "Villamiemban",
    "Wigan",
  ],
  "0203110000": [
    "Ayod",
    "Bucal Norte",
    "Bucal Sur",
    "Dibulo",
    "Digumased (Pob.)",
    "Dimaluade",
  ],
  "0203111000": [
    "Bicobian",
    "Dibulos",
    "Dicambangan",
    "Dicaroyan",
    "Dicatian",
    "Dilakit",
    "Dimapnat",
    "Dimapula (Pob.)",
    "Dimasalansan",
    "Dipudo",
    "Ditarum",
    "Sapinit",
  ],
  "0203112000": [
    "Angoluan",
    "Annafunan",
    "Arabiat",
    "Aromin",
    "Babaran",
    "Bacradal",
    "Benguet",
    "Buneg",
    "Busilelao",
    "Cabugao (Pob.)",
    "Caniguing",
    "Carulay",
    "Castillo",
    "Dammang East",
    "Dammang West",
    "Diasan",
    "Dicaraoyan",
    "Dugayong",
    "Fugu",
    "Garit Norte",
    "Garit Sur",
    "Gucab",
    "Gumbauan",
    "Ipil",
    "Libertad",
    "Mabbayad",
    "Mabuhay",
    "Madadamian",
    "Magleticia",
    "Malibago",
    "Maligaya",
    "Malitao",
    "Narra",
    "Nilumisu",
    "Pag-asa",
    "Pangal Norte",
    "Pangal Sur",
    "Rumang-ay",
    "Salay",
    "Salvacion",
    "San Antonio Minit",
    "San Antonio Ugad",
    "San Carlos",
    "San Fabian",
    "San Felipe",
    "San Juan",
    "San Manuel",
    "San Miguel",
    "San Salvador",
    "Santa Ana",
    "Santa Cruz",
    "Santa Maria",
    "Santa Monica",
    "Santo Domingo",
    "Silauan Norte (Pob.)",
    "Silauan Sur (Pob.)",
    "Sinabbaran",
    "Soyung",
    "Taggappan",
    "Tuguegarao",
    "Villa Campo",
    "Villa Fermin",
    "Villa Rey",
    "Villa Victoria",
  ],
  "0203113000": [
    "Barcolan",
    "Buenavista",
    "Dammao",
    "District I (Pob.)",
    "District II (Pob.)",
    "District III (Pob.)",
    "Furao",
    "Guibang",
    "Lenzon",
    "Linglingay",
    "Mabini",
    "Pintor",
    "Rizal",
    "Songsong",
    "Union",
    "Upi",
  ],
  "0203114000": [
    "Aggasian",
    "Alibagu",
    "Allinguigan 1st",
    "Allinguigan 2nd",
    "Allinguigan 3rd",
    "Arusip",
    "Baculod (Pob.)",
    "Bagong Silang",
    "Bagumbayan (Pob.)",
    "Baligatan",
    "Ballacong",
    "Bangag",
    "Batong-Labang",
    "Bigao",
    "Cabannungan 1st",
    "Cabannungan 2nd",
    "Cabeseria 10",
    "Cabeseria 14 and 16",
    "Cabeseria 17 and 21",
    "Cabeseria 19",
    "Cabeseria 2",
    "Cabeseria 22",
    "Cabeseria 23",
    "Cabeseria 25",
    "Cabeseria 27",
    "Cabeseria 3",
    "Cabeseria 4",
    "Cabeseria 5",
    "Cabeseria 6 & 24",
    "Cabeseria 7",
    "Cabeseria 9 and 11",
    "Cadu",
    "Calamagui 1st",
    "Calamagui 2nd",
    "Camunatan",
    "Capellan",
    "Capo",
    "Carikkikan Norte",
    "Carikkikan Sur",
    "Centro - San Antonio",
    "Centro Poblacion",
    "Fugu",
    "Fuyo",
    "Gayong-Gayong Norte",
    "Gayong-Gayong Sur",
    "Guinatan",
    "Imelda Bliss Village",
    "Lullutan",
    "Malalam",
    "Malasin",
    "Manaring",
    "Mangcuram",
    "Marana I",
    "Marana II",
    "Marana III",
    "Minabang",
    "Morado",
    "Naguilian Norte",
    "Naguilian Sur",
    "Namnama",
    "Nanaguan",
    "Osmeña",
    "Paliueg",
    "Pasa",
    "Pilar",
    "Quimalabasa",
    "Rang-ayan",
    "Rugao",
    "Salindingan",
    "San Andres",
    "San Felipe",
    "San Ignacio",
    "San Isidro",
    "San Juan",
    "San Lorenzo",
    "San Pablo",
    "San Rodrigo",
    "San Vicente (Pob.)",
    "Santa Barbara (Pob.)",
    "Santa Catalina",
    "Santa Isabel Norte",
    "Santa Isabel Sur",
    "Santa Maria",
    "Santa Victoria",
    "Santo Tomas",
    "Siffu",
    "Sindon Bayabo",
    "Sindon Maride",
    "Sipay",
    "Tangcul",
    "Villa Imelda",
  ],
  "0203115000": [
    "Abulan",
    "Addalam",
    "Arubub",
    "Bannawag",
    "Bantay",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangcuag",
    "Dalibubon",
    "Daligan",
    "Diarao",
    "Dibuluan",
    "Dicamay I",
    "Dicamay II",
    "Dipangit",
    "Disimpit",
    "Divinan",
    "Dumawing",
    "Fugu",
    "Lacab",
    "Linamanan",
    "Linomot",
    "Malannit",
    "Minuri",
    "Namnama",
    "Napaliong",
    "Palagao",
    "Papan Este",
    "Papan Weste",
    "Payac",
    "Pongpongan",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Roque",
    "San Sebastian",
    "San Vicente",
    "Santa Isabel",
    "Santo Domingo",
    "Tupax",
    "Usol",
    "Villa Bello",
  ],
  "0203116000": [
    "Bustamante",
    "Centro 1 (Pob.)",
    "Centro 2 (Pob.)",
    "Centro 3 (Pob.)",
    "Concepcion",
    "Dadap",
    "Harana",
    "Lalog 1",
    "Lalog 2",
    "Luyao",
    "Macañao",
    "Macugay",
    "Mambabanga",
    "Pulay",
    "Puroc",
    "San Isidro",
    "San Miguel",
    "Santo Domingo",
    "Union Kalinga",
  ],
  "0203117000": [
    "Aplaya",
    "Canadam",
    "Diana",
    "Eleonor (Pob.)",
    "Fely (Pob.)",
    "Lita (Pob.)",
    "Malasin",
    "Minanga",
    "Reina Mercedes",
    "Santa Marina",
  ],
  "0203118000": [
    "Aga",
    "Andarayan",
    "Aneg",
    "Bayabo",
    "Calinaoan Sur",
    "Caloocan",
    "Capitol",
    "Carmencita",
    "Concepcion",
    "Maui",
    "Quibal",
    "Ragan Almacen",
    "Ragan Norte",
    "Ragan Sur (Pob.)",
    "Rizal",
    "San Andres",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Macario",
    "San Nicolas",
    "San Patricio",
    "San Roque",
    "Santo Rosario",
    "Santor",
    "Villa Luz",
    "Villa Pereda",
    "Visitacion",
  ],
  "0203119000": [
    "Binmonton",
    "Casili",
    "Centro I (Pob.)",
    "Centro II (Pob.)",
    "Holy Friday",
    "Maligaya",
    "Manano",
    "Olango",
    "Rang-ayan",
    "San Jose Norte I",
    "San Jose Norte II",
    "San Jose Sur",
    "San Pedro",
    "San Ramon",
    "Siempre Viva Norte",
    "Siempre Viva Sur",
    "Trinidad",
    "Victoria",
  ],
  "0203120000": [
    "Aguinaldo",
    "Bagong Sikat",
    "Burgos",
    "Cabaruan",
    "Flores",
    "La Union",
    "Magsaysay (Pob.)",
    "Manaring",
    "Mansibang",
    "Minallo",
    "Minanga",
    "Palattao",
    "Quezon (Pob.)",
    "Quinalabasa",
    "Quirino (Pob.)",
    "Rangayan",
    "Rizal",
    "Roxas (Pob.)",
    "San Manuel",
    "Santa Victoria",
    "Santo Tomas",
    "Sunlife",
    "Surcoc",
    "Tomines",
    "Villa Paz",
  ],
  "0203121000": [
    "Alomanay",
    "Bisag",
    "Culasi",
    "Dialaoyao",
    "Dicabisagan East (Pob.)",
    "Dicabisagan West (Pob.)",
    "Dicadyuan",
    "Diddadungan",
    "Didiyan",
    "Dimalicu-licu",
    "Dimasari",
    "Dimatican",
    "Maligaya",
    "Marikit",
    "San Isidro",
    "Santa Jacinta",
    "Villa Robles",
  ],
  "0203122000": [
    "Abut",
    "Alunan (Pob.)",
    "Arellano (Pob.)",
    "Aurora",
    "Barucboc Norte",
    "Calangigan",
    "Dunmon",
    "Estrada",
    "Lepanto",
    "Mangga",
    "Minagbag",
    "Samonte (Pob.)",
    "San Juan",
    "Santos (Pob.)",
    "Turod",
  ],
  "0203123000": [
    "Binarzang",
    "Cabaruan",
    "Camaal",
    "Dolores",
    "Luna",
    "Manaoag",
    "Rizal",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Mateo",
    "San Vicente",
    "Santa Catalina",
    "Santa Lucia (Pob.)",
    "Santiago",
    "Santo Domingo",
    "Sinait",
    "Suerte",
    "Villa Bulusan",
    "Villa Miguel",
    "Vintar",
  ],
  "0203124000": [
    "Ambatali",
    "Bantug",
    "Bugallon Norte",
    "Bugallon Proper (Pob.)",
    "Burgos",
    "General Aguinaldo",
    "Nagbacalan",
    "Oscariz",
    "Pabil",
    "Pagrang-ayan",
    "Planas",
    "Purok ni Bulan",
    "Raniag",
    "San Antonio",
    "San Miguel",
    "San Sebastian",
    "Villa Beltran",
    "Villa Carmen",
    "Villa Marcos",
  ],
  "0203125000": [
    "Banquero",
    "Binarsang",
    "Cutog Grande",
    "Cutog Pequeño",
    "Dangan",
    "District I (Pob.)",
    "District II (Pob.)",
    "Labinab Grande (Pob.)",
    "Labinab Pequeño (Pob.)",
    "Mallalatang Grande",
    "Mallalatang Tunggui",
    "Napaccu Grande",
    "Napaccu Pequeño",
    "Salucong",
    "Santiago",
    "Santor",
    "Sinippil",
    "Tallungan (Pob.)",
    "Turod",
    "Villador",
  ],
  "0203126000": [
    "Anao",
    "Bantug (Pob.)",
    "Doña Concha",
    "Imbiao",
    "Lanting",
    "Lucban",
    "Luna (Pob.)",
    "Marcos",
    "Masigun",
    "Matusalem",
    "Muñoz East",
    "Muñoz West",
    "Quiling",
    "Rang-ayan",
    "Rizal (Pob.)",
    "San Antonio",
    "San Jose",
    "San Luis",
    "San Pedro",
    "San Placido",
    "San Rafael",
    "Simimbaan",
    "Sinamar",
    "Sotero Nuesa",
    "Villa Concepcion",
    "Vira (Pob.)",
  ],
  "0203127000": [
    "Bautista",
    "Calaocan",
    "Dabubu Grande",
    "Dabubu Pequeño",
    "Dappig",
    "Laoag",
    "Mapalad",
    "Masaya Centro (Pob.)",
    "Masaya Norte",
    "Masaya Sur",
    "Nemmatan",
    "Palacian",
    "Panang",
    "Quimalabasa Norte",
    "Quimalabasa Sur",
    "Rang-ay",
    "Salay",
    "San Antonio",
    "Santo Niño",
    "Santos",
    "Sinaoangan Norte",
    "Sinaoangan Sur",
    "Virgoneza",
  ],
  "0203128000": [
    "Anonang",
    "Aringay",
    "Burgos",
    "Calaoagan",
    "Centro 1 (Pob.)",
    "Centro 2 (Pob.)",
    "Colorado",
    "Dietban",
    "Dingading",
    "Dipacamo",
    "Estrella",
    "Guam",
    "Nakar",
    "Palawan",
    "Progreso",
    "Rizal",
    "San Francisco Norte",
    "San Francisco Sur",
    "San Mariano Norte",
    "San Mariano Sur",
    "San Rafael",
    "Sinalugan",
    "Villa Remedios",
    "Villa Rose",
    "Villa Sanchez",
    "Villa Teresita",
  ],
  "0203129000": [
    "Camarag",
    "Cebu",
    "Gomez",
    "Gud",
    "Nagbukel",
    "Patanad",
    "Quezon",
    "Ramos East",
    "Ramos West",
    "Rizal East (Pob.)",
    "Rizal West (Pob.)",
    "Victoria",
    "Villaflor",
  ],
  "0203130000": [
    "Agliam",
    "Babanuang",
    "Cabaritan",
    "Caraniogan",
    "District 1 (Pob.)",
    "District 2 (Pob.)",
    "District 3 (Pob.)",
    "District 4 (Pob.)",
    "Eden",
    "Malalinta",
    "Mararigue",
    "Nueva Era",
    "Pisang",
    "San Francisco",
    "Sandiat Centro",
    "Sandiat East",
    "Sandiat West",
    "Santa Cruz",
    "Villanueva",
  ],
  "0203131000": [
    "Alibadabad",
    "Balagan",
    "Binatug",
    "Bitabian",
    "Buyasan",
    "Cadsalan",
    "Casala",
    "Cataguing",
    "Daragutan East",
    "Daragutan West",
    "Del Pilar",
    "Dibuluan",
    "Dicamay",
    "Dipusu",
    "Disulap",
    "Disusuan",
    "Gangalan",
    "Ibujan",
    "Libertad",
    "Macayucayu",
    "Mallabo",
    "Marannao",
    "Minanga",
    "Old San Mariano",
    "Palutan",
    "Panninan",
    "San Jose",
    "San Pablo",
    "San Pedro",
    "Santa Filomina",
    "Tappa",
    "Ueg",
    "Zamora",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
  ],
  "0203132000": [
    "Bacareña",
    "Bagong Sikat",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Bella Luz",
    "Dagupan",
    "Daramuangan Norte",
    "Daramuangan Sur",
    "Estrella",
    "Gaddanan",
    "Malasin",
    "Mapuroc",
    "Marasat Grande",
    "Marasat Pequeño",
    "Old Centro I",
    "Old Centro II",
    "Salinungan East",
    "Salinungan West",
    "San Andres",
    "San Antonio",
    "San Ignacio",
    "San Manuel",
    "San Marcos",
    "San Roque",
    "Sinamar Norte",
    "Sinamar Sur",
    "Victoria",
    "Villa Cruz",
    "Villa Gamiao",
    "Villa Magat",
    "Villafuerte",
  ],
  "0203133000": [
    "Annanuman",
    "Auitan",
    "Ballacayu",
    "Binguang",
    "Bungad",
    "Caddangan/Limbauan",
    "Calamagui",
    "Caralucud",
    "Dalena",
    "Guminga",
    "Minanga Norte",
    "Minanga Sur",
    "Poblacion",
    "San Jose",
    "Simanu Norte",
    "Simanu Sur",
    "Tupa",
  ],
  "0203134000": [
    "Bangad",
    "Buenavista",
    "Calamagui East",
    "Calamagui North",
    "Calamagui West",
    "Divisoria",
    "Lingaling",
    "Mozzozzin North",
    "Mozzozzin Sur",
    "Naganacan",
    "Poblacion 1",
    "Poblacion 2",
    "Poblacion 3",
    "Quinagabian",
    "San Antonio",
    "San Isidro East",
    "San Isidro West",
    "San Rafael East",
    "San Rafael West",
    "Villabuena",
  ],
  "0203135000": [
    "Abra",
    "Ambalatungan",
    "Balintocatoc",
    "Baluarte",
    "Bannawag Norte",
    "Batal",
    "Buenavista",
    "Cabulay",
    "Calao East (Pob.)",
    "Calao West (Pob.)",
    "Calaocan",
    "Centro East (Pob.)",
    "Centro West (Pob.)",
    "Divisoria",
    "Dubinan East",
    "Dubinan West",
    "Luna",
    "Mabini",
    "Malvar",
    "Nabbuan",
    "Naggasican",
    "Patul",
    "Plaridel",
    "Rizal",
    "Rosario",
    "Sagana",
    "Salvador",
    "San Andres",
    "San Isidro",
    "San Jose",
    "Santa Rosa",
    "Sinili",
    "Sinsayon",
    "Victory Norte",
    "Victory Sur",
    "Villa Gonzaga",
    "Villasis",
  ],
  "0203136000": [
    "Ammugauan",
    "Antagan",
    "Bagabag",
    "Bagutari",
    "Balelleng",
    "Barumbong",
    "Biga Occidental",
    "Biga Oriental",
    "Bolinao-Culalabo",
    "Bubug",
    "Calanigan Norte",
    "Calanigan Sur",
    "Calinaoan Centro",
    "Calinaoan Malasin",
    "Calinaoan Norte",
    "Cañogan Abajo Norte",
    "Cañogan Abajo Sur",
    "Cañogan Alto",
    "Centro",
    "Colunguan",
    "Malapagay",
    "San Rafael Abajo",
    "San Rafael Alto",
    "San Roque",
    "San Vicente",
    "Uauang-Galicia",
    "Uauang-Tuliao",
  ],
  "0203137000": [
    "Annafunan",
    "Antagan I",
    "Antagan II",
    "Arcon",
    "Balug",
    "Banig",
    "Bantug",
    "Barangay District 1 (Pob.)",
    "Barangay District 2 (Pob.)",
    "Barangay District 3 (Pob.)",
    "Barangay District 4 (Pob.)",
    "Bayabo East",
    "Caligayan",
    "Camasi",
    "Carpentero",
    "Compania",
    "Cumabao",
    "Fermeldy",
    "Fugu Abajo",
    "Fugu Norte",
    "Fugu Sur",
    "Lalauanan",
    "Lanna",
    "Lapogan",
    "Lingaling",
    "Liwanag",
    "Malamag East",
    "Malamag West",
    "Maligaya",
    "Minanga",
    "Moldero",
    "Namnama",
    "Paragu",
    "Pilitan",
    "San Mateo",
    "San Pedro",
    "San Vicente",
    "Santa",
    "Santa Catalina",
    "Santa Visitacion",
    "Santo Niño",
    "Sinippil",
    "Sisim Abajo",
    "Sisim Alto",
    "Tunggui",
    "Ugad",
  ],
  "0205001000": [
    "Ammueg",
    "Camandag",
    "Dulli",
    "Labang",
    "Napo",
    "Poblacion",
    "Salingsingan",
    "Tiblac",
  ],
  "0205002000": [
    "Anayo",
    "Baan",
    "Balite",
    "Banganan",
    "Beti",
    "Bone North",
    "Bone South",
    "Calitlitan",
    "Canabuan",
    "Canarem",
    "Comon",
    "Cutar",
    "Darapidap",
    "Kirang",
    "Latar-Nocnoc-San Francisco",
    "Nagcuartelan",
    "Ocao-Capiniaan",
    "Poblacion",
    "Santa Clara",
    "Tabueng",
    "Tucanon",
    "Yaway",
  ],
  "0205003000": [
    "Bakir",
    "Baretbet",
    "Careb",
    "Lantap",
    "Murong",
    "Nangalisan",
    "Paniki",
    "Pogonsino",
    "Quirino (Pob.)",
    "San Geronimo (Pob.)",
    "San Pedro (Pob.)",
    "Santa Cruz",
    "Santa Lucia",
    "Tuao North",
    "Tuao South",
    "Villa Coloma (Pob.)",
    "Villaros",
  ],
  "0205004000": [
    "Abian",
    "Abinganan",
    "Aliaga",
    "Almaguer North",
    "Almaguer South",
    "Banggot (Pob.)",
    "Barat",
    "Buag (Pob.)",
    "Calaocan (Pob.)",
    "Dullao",
    "Homestead",
    "Indiana",
    "Mabuslo",
    "Macate",
    "Magsaysay Hills",
    "Manamtam",
    "Mauan",
    "Pallas",
    "Salinas",
    "San Antonio North",
    "San Antonio South",
    "San Fernando",
    "San Leonardo",
    "Santo Domingo",
    "Santo Domingo West",
  ],
  "0205005000": [
    "Bansing",
    "Bonfal East",
    "Bonfal Proper",
    "Bonfal West",
    "Buenavista",
    "Busilac",
    "Cabuaan",
    "Casat",
    "District III Pob.",
    "District IV (Pob.)",
    "Don Domingo Maddela Pob. ",
    "Don Mariano Marcos",
    "Don Tomas Maddela Pob.",
    "Ipil-Cuneg",
    "La Torre North",
    "La Torre South",
    "Luyang",
    "Magapuy",
    "Magsaysay",
    "Masoc",
    "Paitan",
    "Salvacion",
    "San Nicolas North",
    "Santa Rosa",
    "Vista Alegre",
  ],
  "0205006000": [
    "Ampakling",
    "Arwas",
    "Balete",
    "Bugnay",
    "Butao",
    "Decabacan",
    "Duruarog",
    "Escoting",
    "Langca",
    "Lurad",
    "Nagsabaran",
    "Namamparan",
    "Pinya",
    "Poblacion",
    "Rosario",
    "San Luis",
    "San Pablo",
    "Villa Aurora",
    "Villa Florentino",
  ],
  "0205007000": [
    "Belance",
    "Binnuangan",
    "Bitnong",
    "Bulala",
    "Inaban",
    "Ineangan",
    "Lamo",
    "Mabasa",
    "Macabenga",
    "Malasin (Pob.)",
    "Munguia",
    "New Gumiad",
    "Oyao",
    "Parai",
    "Yabbi",
  ],
  "0205008000": [
    "Abaca",
    "Bagumbayan",
    "Balsain",
    "Banila",
    "Biruk",
    "Canabay",
    "Carolotan",
    "Domang",
    "Dopaj",
    "Gabut",
    "Ganao",
    "Kimbutan",
    "Kinabuan",
    "Lukidnon",
    "Mangayang",
    "Palabotan",
    "Sanguit",
    "Santa Maria",
    "Talbek",
  ],
  "0205009000": [
    "Alimit",
    "Alloy",
    "Antutot",
    "Bilet",
    "Binogawan",
    "Biyoy",
    "Bua",
    "Camamasi",
    "Capisaan",
    "Catarawan",
    "Cordon",
    "Didipio",
    "Dine",
    "Kakiduguen",
    "Kongkong",
    "Lupa",
    "Macalong",
    "Malabing",
    "Muta",
    "Nantawacan",
    "Pacquet",
    "Pao",
    "Papaya",
    "Poblacion",
    "Pudi",
    "Seguem",
    "Tadji",
    "Tokod",
    "Wangal",
    "Watwat",
  ],
  "0205010000": [
    "Acacia",
    "Alang-Salacsac",
    "Amilong Labeng",
    "Ansipsip",
    "Baan",
    "Babadi",
    "Balangabang",
    "Balete",
    "Banao",
    "Besong",
    "Binalian",
    "Buyasyas",
    "Cabalatan-Alang",
    "Cabanglasan",
    "Cabayo",
    "Castillo Village",
    "Kayapa Proper East",
    "Kayapa Proper West",
    "Latbang",
    "Lawigan",
    "Mapayao",
    "Nansiakan",
    "Pampang (Pob.)",
    "Pangawan",
    "Pinayag",
    "Pingkian",
    "San Fabian",
    "Talecabcab",
    "Tidang Village",
    "Tubongan",
  ],
  "0205011000": [
    "Aurora",
    "Baresbes",
    "Bonifacio",
    "Buliwao",
    "Calaocan",
    "Caliat (Pob.)",
    "Dagupan",
    "Darubba",
    "Maasin",
    "Maddiangat",
    "Nalubbunan",
    "Runruno",
  ],
  "0205012000": [
    "Atbu",
    "Bacneng",
    "Balete",
    "Baliling",
    "Bantinan",
    "Baracbac",
    "Buyasyas",
    "Canabuan",
    "Imugan",
    "Malico",
    "Poblacion",
    "Santa Rosa",
    "Sinapaoan",
    "Tactac",
    "Unib",
    "Villa Flores",
  ],
  "0205013000": [
    "Aggub",
    "Bagahabag",
    "Bangaan",
    "Bangar",
    "Bascaran",
    "Communal",
    "Concepcion",
    "Curifang",
    "Dadap",
    "Lactawan",
    "Osmeña",
    "Pilar D. Galima",
    "Poblacion North",
    "Poblacion South",
    "Quezon",
    "Quirino",
    "Roxas",
    "San Juan",
    "San Luis",
    "Tucal",
    "Uddiawan",
    "Wacal",
  ],
  "0205014000": [
    "Bintawan Norte",
    "Bintawan Sur",
    "Cabuluan",
    "Ibung",
    "Nagbitin",
    "Ocapon",
    "Pieza",
    "Poblacion",
    "Sawmill",
  ],
  "0205015000": [
    "Abuyo",
    "Cauayan",
    "Galintuja",
    "Lipuga",
    "Lublub (Pob.)",
    "Pelaway",
  ],
  "0205701000": [
    "Alicia",
    "Cabugao",
    "Dagupan",
    "Diodol",
    "Dumabel",
    "Dungo",
    "Guinalbin",
    "Ligaya",
    "Nagabgaban",
    "Palacian",
    "Pinaripad Norte",
    "Pinaripad Sur",
    "Progreso (Pob.)",
    "Ramos",
    "Rang-ayan",
    "San Antonio",
    "San Benigno",
    "San Francisco",
    "San Leonardo",
    "San Manuel",
    "San Ramon",
    "Victoria",
    "Villa Pagaduan",
    "Villa Santiago",
    "Villa Ventura",
  ],
  "0205702000": [
    "Banuar",
    "Burgos",
    "Calaocan",
    "Del Pilar",
    "Dibibi",
    "Dingasan",
    "Eden",
    "Gomez",
    "Gundaway (Pob.)",
    "Mangandingay (Pob.)",
    "San Marcos",
    "Santo Domingo",
    "Tucod",
    "Villa Peña",
    "Villamor",
    "Villarose",
    "Zamora",
  ],
  "0205703000": [
    "Aklan Village",
    "Andres Bonifacio (Pob.)",
    "Aurora East (Pob.)",
    "Aurora West (Pob.)",
    "Baguio Village",
    "Balagbag",
    "Bannawag",
    "Cajel",
    "Campamento",
    "Diego Silang",
    "Don Faustino Pagaduan",
    "Don Mariano Perez, Sr.",
    "Doña Imelda",
    "Dumanisi",
    "Gabriela Silang",
    "Gregorio Pimentel",
    "Gulac",
    "Guribang",
    "Ifugao Village",
    "Isidro Paredes",
    "Liwayway",
    "Luttuad",
    "Magsaysay",
    "Makate",
    "Maria Clara",
    "Rafael Palma",
    "Ricarte Norte",
    "Ricarte Sur",
    "Rizal (Pob.)",
    "San Antonio",
    "San Isidro",
    "San Pascual",
    "Villa Pascua",
  ],
  "0205704000": [
    "Abbag",
    "Balligui",
    "Buenavista",
    "Cabaruan",
    "Cabua-an",
    "Cofcaville",
    "Diduyon",
    "Dipintin",
    "Divisoria Norte",
    "Divisoria Sur",
    "Dumabato Norte",
    "Dumabato Sur",
    "Jose Ancheta",
    "Lusod",
    "Manglad",
    "Pedlisan",
    "Poblacion Norte",
    "Poblacion Sur",
    "San Bernabe",
    "San Dionisio I",
    "San Martin",
    "San Pedro",
    "San Salvador",
    "Santa Maria",
    "Santo Niño",
    "Santo Tomas",
    "Villa Agullana",
    "Villa Gracia",
    "Villa Hermosa Norte",
    "Villa Hermosa Sur",
    "Villa Jose V Ylanan",
    "Ysmael",
  ],
  "0205705000": [
    "Cardenas",
    "Dibul",
    "Gamis",
    "La Paz",
    "Magsaysay (Pob.)",
    "Rizal (Pob.)",
    "Salvacion",
    "Santo Tomas",
    "Tres Reyes",
  ],
  "0205706000": [
    "Anak",
    "Asaklat",
    "Dipantan",
    "Dissimungal",
    "Guino",
    "La Conwap",
    "Landingan",
    "Mataddi",
    "Matmad",
    "Old Gumiad",
    "Ponggo",
    "San Dionisio II",
    "San Pugo",
    "San Ramos",
    "Sangbay",
    "Wasid",
  ],
};
