/** GENERATED — Region III: 3102 barangays across 130 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "0300801000": [
    "Bangkal",
    "Calaylayan (Pob.)",
    "Capitangan",
    "Gabon",
    "Laon (Pob.)",
    "Mabatang",
    "Omboy",
    "Salian",
    "Wawa (Pob.)",
  ],
  "0300802000": [
    "Atilano L. Ricardo",
    "Bagumbayan (Pob.)",
    "Banawang",
    "Binuangan",
    "Binukawan",
    "Ibaba",
    "Ibis",
    "Pag-asa",
    "Parang",
    "Paysawan",
    "Quinawan",
    "San Antonio",
    "Saysain",
    "Tabing-Ilog (Pob.)",
  ],
  "0300803000": [
    "Bagong Silang",
    "Bagumbayan",
    "Cabog-Cabog",
    "Camacho",
    "Cataning",
    "Central",
    "Cupang North",
    "Cupang Proper",
    "Cupang West",
    "Dangcol",
    "Doña Francisca",
    "Ibayo",
    "Lote",
    "Malabia",
    "Munting Batangas",
    "Poblacion",
    "Pto. Rivas Ibaba",
    "Pto. Rivas Itaas",
    "San Jose",
    "Sibacan",
    "Talisay",
    "Tanato",
    "Tenejero",
    "Tortugas",
    "Tuyo",
  ],
  "0300804000": [
    "Aquino",
    "Bangal",
    "Bayan-bayanan",
    "Bonifacio (Pob.)",
    "Burgos (Pob.)",
    "Colo",
    "Daang Bago",
    "Dalao",
    "Del Pilar (Pob.)",
    "Gen. Luna (Pob.)",
    "Gomez (Pob.)",
    "Happy Valley",
    "Jose C. Payumo, Jr.",
    "Kataasan",
    "Layac",
    "Luacan",
    "Mabini Ext. (Pob.)",
    "Mabini Proper (Pob.)",
    "Magsaysay",
    "Maligaya",
    "Naparing",
    "New San Jose",
    "Old San Jose",
    "Padre Dandan (Pob.)",
    "Pag-asa",
    "Pagalanggang",
    "Payangan",
    "Pentor",
    "Pinulot",
    "Pita",
    "Rizal (Pob.)",
    "Roosevelt",
    "Roxas (Pob.)",
    "Saguing",
    "San Benito",
    "San Isidro (Pob.)",
    "San Pablo",
    "San Ramon",
    "San Simon",
    "Santa Isabel",
    "Santo Niño",
    "Sapang Balas",
    "Torres Bugauen (Pob.)",
    "Tubo-tubo",
    "Tucop",
    "Zamora (Pob.)",
  ],
  "0300805000": [
    "A. Rivera (Pob.)",
    "Almacen",
    "Bacong",
    "Balsic",
    "Bamban",
    "Burgos-Soliman (Pob.)",
    "Cataning (Pob.)",
    "Culis",
    "Daungan (Pob.)",
    "Judge Roman Cruz Sr.",
    "Mabiga",
    "Mabuco",
    "Maite",
    "Mambog - Mandama",
    "Palihan",
    "Pandatung",
    "Pulo",
    "Saba",
    "Sacrifice Valley",
    "San Pedro (Pob.)",
    "Santo Cristo (Pob.)",
    "Sumalo",
    "Tipo",
  ],
  "0300806000": [
    "Alangan",
    "Duale",
    "Kitang 2 & Luz",
    "Kitang I",
    "Lamao",
    "Landing",
    "Poblacion",
    "Reformista",
    "San Francisco de Asis",
    "St. Francis II",
    "Townsite",
    "Wawa",
  ],
  "0300807000": [
    "Alas-asin",
    "Alion",
    "Balon-Anito",
    "Baseco Country",
    "Batangas II",
    "Biaan",
    "Cabcaben",
    "Camaya",
    "Ipag",
    "Lucanin",
    "Malaya",
    "Maligaya",
    "Mt. View",
    "Poblacion",
    "San Carlos",
    "San Isidro",
    "Sisiman",
    "Townsite",
  ],
  "0300808000": ["Binaritan", "Mabayo", "Nagbalayong", "Poblacion", "Sabang"],
  "0300809000": [
    "Apollo",
    "Bagong Paraiso (Pob.)",
    "Balut (Pob.)",
    "Bayan (Pob.)",
    "Calero (Pob.)",
    "Centro I (Pob.)",
    "Centro II (Pob.)",
    "Dona",
    "Kabalutan",
    "Kaparangan",
    "Maria Fe",
    "Masantol",
    "Mulawin",
    "Pag-asa",
    "Paking-Carbonero (Pob.)",
    "Palihan (Pob.)",
    "Pantalan Bago (Pob.)",
    "Pantalan Luma (Pob.)",
    "Parang Parang (Pob.)",
    "Puksuan",
    "Sibul",
    "Silahis",
    "Tagumpay",
    "Tala",
    "Talimundoc",
    "Tapulao",
    "Tenejero (Pob.)",
    "Tugatog",
    "Wawa (Pob.)",
  ],
  "0300810000": [
    "Arellano (Pob.)",
    "Bagumbayan (Pob.)",
    "Balagtas (Pob.)",
    "Balut (Pob.)",
    "Bantan",
    "Bilolo",
    "Calungusan",
    "Camachile",
    "Daang Bago (Pob.)",
    "Daang Bilolo (Pob.)",
    "Daang Pare",
    "General Lim",
    "Kapunitan",
    "Lati (Pob.)",
    "Lusungan (Pob.)",
    "Puting Buhangin",
    "Sabatan",
    "San Vicente (Pob.)",
    "Santa Elena",
    "Santo Domingo",
    "Villa Angeles (Pob.)",
    "Wakas (Pob.)",
    "Wawa (Pob.)",
  ],
  "0300811000": [
    "Ala-uli",
    "Bagumbayan",
    "Balut I",
    "Balut II",
    "Bantan Munti",
    "Burgos",
    "Del Rosario (Pob.)",
    "Diwa",
    "Landing",
    "Liyang",
    "Nagwaling",
    "Panilao",
    "Pantingan",
    "Poblacion",
    "Rizal (Pob.)",
    "Santa Rosa",
    "Wakas North",
    "Wakas South",
    "Wawa",
  ],
  "0300812000": [
    "East Calaguiman (Pob.)",
    "East Daang Bago (Pob.)",
    "Gugo",
    "Ibaba (Pob.)",
    "Imelda",
    "Lalawigan",
    "Palili",
    "San Juan (Pob.)",
    "San Roque (Pob.)",
    "Santa Lucia",
    "Sapa",
    "Tabing Ilog",
    "West Calaguiman (Pob.)",
    "West Daang Bago (Pob.)",
  ],
  "0301401000": [
    "Banaban",
    "Baybay",
    "Binagbag",
    "Donacion",
    "Encanto",
    "Laog",
    "Marungko",
    "Niugan",
    "Paltok",
    "Pulong Yantok",
    "San Roque (Pob.)",
    "Santa Cruz (Pob.)",
    "Santa Lucia",
    "Santo Cristo (Pob.)",
    "Sulucan",
    "Taboc",
  ],
  "0301402000": [
    "Borol 1st",
    "Borol 2nd",
    "Dalig",
    "Longos",
    "Panginay",
    "Pulong Gubat",
    "San Juan",
    "Santol",
    "Wawa (Pob.)",
  ],
  "0301403000": [
    "Bagong Nayon",
    "Barangca",
    "Calantipay",
    "Catulinan",
    "Concepcion",
    "Hinukay",
    "Makinabang",
    "Matangtubig",
    "Pagala",
    "Paitan",
    "Piel",
    "Pinagbarilan",
    "Poblacion",
    "Sabang",
    "San Jose",
    "San Roque",
    "Santa Barbara",
    "Santo Cristo",
    "Santo Niño",
    "Subic",
    "Sulivan",
    "Tangos",
    "Tarcan",
    "Tiaong",
    "Tibag",
    "Tilapayong",
    "Virgen delas Flores",
  ],
  "0301404000": [
    "Antipona",
    "Bagumbayan",
    "Bambang",
    "Batia",
    "Biñang 1st",
    "Biñang 2nd",
    "Bolacan",
    "Bundukan",
    "Bunlo",
    "Caingin",
    "Duhat",
    "Igulot",
    "Lolomboy",
    "Poblacion",
    "Sulucan",
    "Taal",
    "Tambobong",
    "Turo",
    "Wakas",
  ],
  "0301405000": [
    "Bagumbayan",
    "Balubad",
    "Bambang",
    "Matungao",
    "Maysantol",
    "Perez",
    "Pitpitan",
    "San Francisco",
    "San Jose (Pob.)",
    "San Nicolas",
    "Santa Ana",
    "Santa Ines",
    "Taliptip",
    "Tibig",
  ],
  "0301406000": [
    "Bonga Mayor",
    "Bonga Menor",
    "Buisan",
    "Camachilihan",
    "Cambaog",
    "Catacte",
    "Liciada",
    "Malamig",
    "Malawak",
    "Poblacion",
    "San Pedro",
    "Talampas",
    "Tanawan",
    "Tibagan",
  ],
  "0301407000": [
    "Balite",
    "Balungao",
    "Buguion",
    "Bulusan",
    "Calizon",
    "Calumpang",
    "Caniogan",
    "Corazon",
    "Frances",
    "Gatbuca",
    "Gugo",
    "Iba Este",
    "Iba O'Este",
    "Longos",
    "Meysulao",
    "Meyto",
    "Palimbang",
    "Panducot",
    "Pio Cruzcosa",
    "Poblacion",
    "Pungo",
    "San Jose",
    "San Marcos",
    "San Miguel",
    "Santa Lucia",
    "Santo Niño",
    "Sapang Bayan",
    "Sergio Bayan",
    "Sucol",
  ],
  "0301408000": [
    "Cutcut",
    "Daungan",
    "Ilang-Ilang",
    "Malis",
    "Panginay",
    "Poblacion",
    "Pritil",
    "Pulong Gubat",
    "Santa Cruz",
    "Santa Rita",
    "Tabang",
    "Tabe",
    "Tiaong",
    "Tuktukan",
  ],
  "0301409000": [
    "Abulalas",
    "Carillo",
    "Iba",
    "Iba-Ibayo",
    "Mercado",
    "Palapat",
    "Pugad",
    "Sagrada Familia",
    "San Agustin",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Miguel",
    "San Nicolas",
    "San Pablo",
    "San Pascual",
    "San Pedro",
    "San Roque",
    "San Sebastian",
    "Santa Cruz",
    "Santa Elena",
    "Santa Monica",
    "Santo Niño (Pob.)",
    "Santo Rosario",
    "Tampok",
    "Tibaguin",
  ],
  "0301410000": [
    "Anilao",
    "Atlag",
    "Babatnin",
    "Bagna",
    "Bagong Bayan",
    "Balayong",
    "Balite",
    "Bangkal",
    "Barihan",
    "Bulihan",
    "Bungahan",
    "Caingin",
    "Calero",
    "Caliligawan",
    "Canalate",
    "Caniogan",
    "Catmon",
    "Cofradia",
    "Dakila",
    "Guinhawa",
    "Liang",
    "Ligas",
    "Longos",
    "Look 1st",
    "Look 2nd",
    "Lugam",
    "Mabolo",
    "Mambog",
    "Masile",
    "Matimbo",
    "Mojon",
    "Namayan",
    "Niugan",
    "Pamarawan",
    "Panasahan",
    "Pinagbakahan",
    "San Agustin",
    "San Gabriel",
    "San Juan",
    "San Pablo",
    "San Vicente (Pob.)",
    "Santiago",
    "Santisima Trinidad",
    "Santo Cristo",
    "Santo Niño (Pob.)",
    "Santo Rosario (Pob.)",
    "Santor",
    "Sumapang Bata",
    "Sumapang Matanda",
    "Taal",
    "Tikay",
  ],
  "0301411000": [
    "Abangan Norte",
    "Abangan Sur",
    "Ibayo",
    "Lambakin",
    "Lias",
    "Loma de Gato",
    "Nagbalon",
    "Patubig",
    "Poblacion I",
    "Poblacion II",
    "Prenza I",
    "Prenza II",
    "Santa Rosa I",
    "Santa Rosa II",
    "Saog",
    "Tabing Ilog",
  ],
  "0301412000": [
    "Bagbaguin",
    "Bahay Pare",
    "Bancal",
    "Banga",
    "Bayugo",
    "Caingin",
    "Calvario",
    "Camalig",
    "Hulo",
    "Iba",
    "Langka",
    "Lawa",
    "Libtong",
    "Liputan",
    "Longos",
    "Malhacan",
    "Pajo",
    "Pandayan",
    "Pantoc",
    "Perez",
    "Poblacion",
    "Saint Francis (Gasak)",
    "Saluysoy",
    "Tugatog",
    "Ubihan",
    "Zamora",
  ],
  "0301413000": [
    "Bangkal",
    "Baraka",
    "Bigte",
    "Bitungol",
    "Friendship Village Resources",
    "Matictic",
    "Minuyan",
    "Partida",
    "Pinagtulayan",
    "Poblacion",
    "San Lorenzo",
    "San Mateo",
    "Tigbe",
  ],
  "0301414000": [
    "Binuangan",
    "Catanghalan",
    "Hulo",
    "Lawa",
    "Paco",
    "Pag-asa (Pob.)",
    "Paliwas",
    "Panghulo",
    "Salambao",
    "San Pascual",
    "Tawiran",
  ],
  "0301415000": [
    "Bagbaguin",
    "Bagong Barrio",
    "Baka-bakahan",
    "Bunsuran I",
    "Bunsuran II",
    "Bunsuran III",
    "Cacarong Bata",
    "Cacarong Matanda",
    "Cupang",
    "Malibong Bata",
    "Malibong Matanda",
    "Manatal",
    "Mapulang Lupa",
    "Masagana",
    "Masuso",
    "Pinagkuartelan",
    "Poblacion",
    "Real de Cacarong",
    "San Roque",
    "Santo Niño",
    "Siling Bata",
    "Siling Matanda",
  ],
  "0301416000": [
    "Binakod",
    "Kapitangan",
    "Malumot",
    "Masukol",
    "Pinalagdan",
    "Poblacion",
    "San Isidro I",
    "San Isidro II",
    "San Jose",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Santo Niño",
    "Santo Rosario",
  ],
  "0301417000": [
    "Agnaya",
    "Bagong Silang",
    "Banga I",
    "Banga II",
    "Bintog",
    "Bulihan",
    "Culianin",
    "Dampol",
    "Lagundi",
    "Lalangan",
    "Lumang Bayan",
    "Parulan",
    "Poblacion",
    "Rueda",
    "San Jose",
    "Santa Ines",
    "Santo Niño",
    "Sipat",
    "Tabang",
  ],
  "0301418000": [
    "Balatong A",
    "Balatong B",
    "Cutcot",
    "Dampol I",
    "Dampol II-A",
    "Dampol II-B",
    "Dulong Malabon",
    "Inaon",
    "Longos",
    "Lumbac",
    "Paltao",
    "Penabatan",
    "Poblacion",
    "Santa Peregrina",
    "Santo Cristo",
    "Taal",
    "Tabon",
    "Tibag",
    "Tinejero",
  ],
  "0301419000": [
    "Akle",
    "Alagao",
    "Anyatam",
    "Bagong Barrio",
    "Basuit",
    "Bubulong Malaki",
    "Bubulong Munti",
    "Buhol na Mangga",
    "Bulusukan",
    "Calasag",
    "Calawitan",
    "Casalat",
    "Gabihan",
    "Garlang",
    "Lapnit",
    "Maasim",
    "Makapilapil",
    "Malipampang",
    "Mataas na Parang",
    "Matimbubong",
    "Nabaong Garlang",
    "Palapala",
    "Pasong Bangkal",
    "Pinaod",
    "Poblacion",
    "Pulong Tamo",
    "San Juan",
    "Santa Catalina Bata",
    "Santa Catalina Matanda",
    "Sapang Dayap",
    "Sapang Putik",
    "Sapang Putol",
    "Sumandig",
    "Telepatio",
    "Umpucan",
    "Upig",
  ],
  "0301420000": [
    "Assumption",
    "Bagong Buhay I",
    "Bagong Buhay II",
    "Bagong Buhay III",
    "Citrus",
    "Ciudad Real",
    "Dulong Bayan",
    "Fatima I",
    "Fatima II",
    "Fatima III",
    "Fatima IV",
    "Fatima V",
    "Francisco Homes-Guijo",
    "Francisco Homes-Mulawin",
    "Francisco Homes-Narra",
    "Francisco Homes-Yakal",
    "Gaya-gaya",
    "Graceville",
    "Gumaoc Central",
    "Gumaoc East",
    "Gumaoc West",
    "Kaybanban",
    "Kaypian",
    "Lawang Pari",
    "Maharlika",
    "Minuyan I",
    "Minuyan II",
    "Minuyan III",
    "Minuyan IV",
    "Minuyan Proper",
    "Minuyan V",
    "Muzon",
    "Paradise III",
    "Poblacion",
    "Poblacion I",
    "San Isidro",
    "San Manuel",
    "San Martin de Porres",
    "San Martin I",
    "San Martin II",
    "San Martin III",
    "San Martin IV",
    "San Pedro",
    "San Rafael I",
    "San Rafael II",
    "San Rafael III",
    "San Rafael IV",
    "San Rafael V",
    "San Roque",
    "Santa Cruz I",
    "Santa Cruz II",
    "Santa Cruz III",
    "Santa Cruz IV",
    "Santa Cruz V",
    "Santo Cristo",
    "Santo Niño I",
    "Santo Niño II",
    "Sapang Palay",
    "Tungkong Mangga",
  ],
  "0301421000": [
    "Bagong Pag-asa",
    "Bagong Silang",
    "Balaong",
    "Balite",
    "Bantog",
    "Bardias",
    "Baritan",
    "Batasan Bata",
    "Batasan Matanda",
    "Biak-na-Bato",
    "Biclat",
    "Buga",
    "Buliran",
    "Bulualto",
    "Calumpang",
    "Cambio",
    "Camias",
    "Ilog-Bulo",
    "King Kabayo",
    "Labne",
    "Lambakin",
    "Magmarale",
    "Malibay",
    "Maligaya",
    "Mandile",
    "Masalipit",
    "Pacalag",
    "Paliwasan",
    "Partida",
    "Pinambaran",
    "Poblacion",
    "Pulong Bayabas",
    "Pulong Duhat",
    "Sacdalan",
    "Salacot",
    "Salangan",
    "San Agustin",
    "San Jose",
    "San Juan",
    "San Vicente",
    "Santa Ines",
    "Santa Lucia",
    "Santa Rita Bata",
    "Santa Rita Matanda",
    "Sapang",
    "Sibul",
    "Tartaro",
    "Tibagan",
    "Tigpalas",
  ],
  "0301422000": [
    "Banca-banca",
    "BMA-Balagtas",
    "Caingin",
    "Capihan",
    "Coral na Bato",
    "Cruz na Daan",
    "Dagat-dagatan",
    "Diliman I",
    "Diliman II",
    "Libis",
    "Lico",
    "Maasim",
    "Mabalas-balas",
    "Maguinao",
    "Maronquillo",
    "Paco",
    "Pansumaloc",
    "Pantubig",
    "Pasong Bangkal",
    "Pasong Callos",
    "Pasong Intsik",
    "Pinacpinacan",
    "Poblacion",
    "Pulo",
    "Pulong Bayabas",
    "Salapungan",
    "Sampaloc",
    "San Agustin",
    "San Roque",
    "Sapang Pahalang",
    "Talacsan",
    "Tambubong",
    "Tukod",
    "Ulingao",
  ],
  "0301423000": [
    "Bagbaguin",
    "Balasing",
    "Buenavista",
    "Bulac",
    "Camangyanan",
    "Catmon",
    "Cay Pombo",
    "Caysio",
    "Guyong",
    "Lalakhan",
    "Mag-asawang Sapa",
    "Mahabang Parang",
    "Manggahan",
    "Parada",
    "Poblacion",
    "Pulong Buhangin",
    "San Gabriel",
    "San Jose Patag",
    "San Vicente",
    "Silangan",
    "Sta. Clara",
    "Sta. Cruz",
    "Tabing Bakod",
    "Tumana",
  ],
  "0301424000": [
    "Bayabas",
    "Camachile",
    "Camachin",
    "Kabayunan",
    "Kalawakan",
    "Pulong Sampalok",
    "Sapang Bulak",
    "Talbak",
  ],
  "0304901000": [
    "Betes",
    "Bibiclat",
    "Bucot",
    "La Purisima",
    "Macabucod",
    "Magsaysay",
    "Pantoc",
    "Poblacion Centro",
    "Poblacion East I",
    "Poblacion East II",
    "Poblacion West III",
    "Poblacion West IV",
    "San Carlos",
    "San Emiliano",
    "San Eustacio",
    "San Felipe Bata",
    "San Felipe Matanda",
    "San Juan",
    "San Pablo Bata",
    "San Pablo Matanda",
    "Santa Monica",
    "Santiago",
    "Santo Rosario",
    "Santo Tomas",
    "Sunson",
    "Umangan",
  ],
  "0304902000": [
    "Antipolo",
    "Ariendo",
    "Bantug",
    "Calaanan",
    "Commercial (Pob.)",
    "Cruz",
    "Curva",
    "Digmala",
    "Kaingin (Pob.)",
    "Labi",
    "Larcon",
    "Lusok",
    "Macabaclay",
    "Magtanggol (Pob.)",
    "Mantile (Pob.)",
    "Olivete",
    "Palo Maria (Pob.)",
    "Pesa",
    "Rizal (Pob.)",
    "Sampalucan (Pob.)",
    "San Roque (Pob.)",
    "Santor",
    "Sinipit (Pob.)",
    "Sisilang na Ligaya (Pob.)",
    "Social (Pob.)",
    "Tugatug",
    "Tulay na Bato (Pob.)",
    "Vega",
  ],
  "0304903000": [
    "Aduas Centro",
    "Aduas Norte",
    "Aduas Sur",
    "Bagong Buhay",
    "Bagong Sikat",
    "Bakero",
    "Bakod Bayan",
    "Balite",
    "Bangad",
    "Bantug Bulalo",
    "Bantug Norte",
    "Barlis",
    "Barrera District (Pob.)",
    "Bernardo District (Pob.)",
    "Bitas",
    "Bonifacio District (Pob.)",
    "Buliran",
    "Caalibangbangan",
    "Cabu",
    "Calawagan",
    "Campo Tinio",
    "Caridad",
    "Caudillo",
    "Cinco-Cinco",
    "City Supermarket (Pob.)",
    "Communal",
    "Cruz Roja",
    "Daang Sarile",
    "Dalampang",
    "Dicarma (Pob.)",
    "Dimasalang (Pob.)",
    "Dionisio S. Garcia",
    "Fatima (Pob.)",
    "General Luna (Pob.)",
    "Hermogenes C. Concepcion, Sr.",
    "Ibabao Bana",
    "Imelda District",
    "Isla (Pob.)",
    "Kalikid Norte",
    "Kalikid Sur",
    "Kapitan Pepe (Pob.)",
    "Lagare",
    "Lourdes",
    "M. S. Garcia",
    "Mabini Extension",
    "Mabini Homesite",
    "Macatbong",
    "Magsaysay District",
    "Magsaysay South",
    "Maria Theresa",
    "Matadero (Pob.)",
    "Mayapyap Norte",
    "Mayapyap Sur",
    "Melojavilla (Pob.)",
    "Nabao (Pob.)",
    "Obrero",
    "Padre Burgos (Pob.)",
    "Padre Crisostomo",
    "Pagas",
    "Palagay",
    "Pamaldan",
    "Pangatian",
    "Patalac",
    "Polilio",
    "Pula",
    "Quezon District (Pob.)",
    "Rizdelis (Pob.)",
    "Samon",
    "San Isidro",
    "San Josef Norte",
    "San Josef Sur",
    "San Juan Pob.",
    "San Roque Norte",
    "San Roque Sur",
    "Sanbermicristi (Pob.)",
    "Sangitan",
    "Sangitan East",
    "Santa Arcadia",
    "Santo Niño",
    "Sapang",
    "Sumacab Este",
    "Sumacab Norte",
    "Sumacab South",
    "Talipapa",
    "Valdefuente",
    "Valle Cruz",
    "Vijandre District (Pob.)",
    "Villa Ofelia-Caridad",
    "Zulueta District (Pob.)",
  ],
  "0304904000": [
    "Bagong Buhay",
    "Bagong Sikat",
    "Bagong Silang",
    "Concepcion",
    "Entablado",
    "Maligaya",
    "Natividad North (Pob.)",
    "Natividad South (Pob.)",
    "Palasinan",
    "Polilio",
    "San Antonio",
    "San Carlos",
    "San Fernando Norte",
    "San Fernando Sur",
    "San Gregorio",
    "San Juan North (Pob.)",
    "San Juan South (Pob.)",
    "San Roque",
    "San Vicente",
    "Santa Ines",
    "Santa Isabel",
    "Santa Rita",
    "Sinipit",
  ],
  "0304905000": [
    "Bantug",
    "Bunga",
    "Burgos",
    "Capintalan",
    "D. L. Maglanoc Pob.",
    "F. C. Otic Pob.",
    "G. S. Rosario Pob.",
    "General Luna",
    "Joson",
    "Minuli",
    "Piut",
    "Puncan",
    "Putlan",
    "R.A.Padilla",
    "Salazar",
    "San Agustin",
    "T. L. Padilla Pob.",
  ],
  "0304906000": [
    "Baloy",
    "Bambanaba",
    "Bantug",
    "Bentigan",
    "Bibiclat",
    "Bonifacio",
    "Bued",
    "Bulala",
    "Burgos",
    "Cabatuan",
    "Cabileo",
    "Cacapasan",
    "Calancuasan Norte",
    "Calancuasan Sur",
    "Colosboa",
    "Columbitin",
    "Curva",
    "District I",
    "District II",
    "District IV",
    "District V",
    "District VI",
    "District VII",
    "District VIII",
    "Landig",
    "Latap",
    "Loob",
    "Luna",
    "Malbeg-Patalan",
    "Malineng",
    "Matindeg",
    "Maycaban",
    "Nacuralan",
    "Nagmisahan",
    "Paitan Norte",
    "Paitan Sur",
    "Piglisan",
    "Pugo",
    "Rizal",
    "Sabit",
    "Salagusog",
    "San Antonio",
    "San Jose",
    "San Juan",
    "Santa Clara",
    "Santa Cruz",
    "Sinimbaan",
    "Tagtagumbao",
    "Tutuloy",
    "Ungab",
    "Villaflores",
  ],
  "0304907000": [
    "Bagong Sikat",
    "Bagting",
    "Bantug",
    "Bitulok",
    "Bugnan",
    "Calabasa",
    "Camachile",
    "Cuyapa",
    "Ligaya",
    "Macasandal",
    "Malinao",
    "Pantoc",
    "Pinamalisan",
    "Sawmill",
    "South Poblacion",
    "Tagumpay",
  ],
  "0304908000": [
    "Balante",
    "Bayanihan",
    "Bulak",
    "Bungo",
    "Kapalangan",
    "Mabunga",
    "Maburak",
    "Mahipon",
    "Makabaclay",
    "Malimba",
    "Mangino",
    "Marelo",
    "Pambuan",
    "Parcutela",
    "Puting Tubig",
    "San Lorenzo (Pob.)",
    "San Nicolas",
    "San Roque",
    "San Vicente (Pob.)",
    "Santa Cruz",
    "Santo Cristo Norte",
    "Santo Cristo Sur",
    "Santo Niño",
  ],
  "0304909000": [
    "Balangkare Norte",
    "Balangkare Sur",
    "Balaring",
    "Belen",
    "Bravo",
    "Burol",
    "Kabulihan",
    "Mag-asawang Sampaloc",
    "Manarog",
    "Mataas na Kahoy",
    "Panacsac",
    "Picaleon",
    "Pinahan",
    "Platero",
    "Poblacion",
    "Pula",
    "Pulong Singkamas",
    "Sapang Bato",
    "Talabutab Norte",
    "Talabutab Sur",
  ],
  "0304910000": [
    "Bago",
    "Concepcion",
    "Nazareth",
    "Padolina",
    "Palale",
    "Pias",
    "Poblacion Central",
    "Poblacion East",
    "Poblacion West",
    "Pulong Matong",
    "Rio Chico",
    "Sampaguita",
    "San Pedro (Pob.)",
  ],
  "0304911000": [
    "Agcano",
    "Ayos Lomboy",
    "Bacayao",
    "Bagong Barrio",
    "Balbalino",
    "Balingog East",
    "Balingog West",
    "Banitan",
    "Bantug",
    "Bulakid",
    "Bunol",
    "Caballero",
    "Cabaruan",
    "Caingin Tabing Ilog",
    "Calem",
    "Camiling",
    "Cardinal",
    "Casongsong",
    "Catimon",
    "Cavite",
    "Cawayan Bugtong",
    "Consuelo",
    "Culong",
    "Escano",
    "Faigal",
    "Galvan",
    "Guiset",
    "Lamorito",
    "Lennec",
    "Macamias",
    "Macapabellag",
    "Macatcatuit",
    "Manacsac",
    "Manggang Marikit",
    "Maturanoc",
    "Maybubon",
    "Naglabrahan",
    "Nagpandayan",
    "Narvacan I",
    "Narvacan II",
    "Pacac",
    "Partida I",
    "Partida II",
    "Pasong Inchic",
    "Saint John District (Pob.)",
    "San Agustin",
    "San Andres",
    "San Bernardino",
    "San Marcelino",
    "San Miguel",
    "San Rafael",
    "San Roque",
    "Santa Ana",
    "Santa Cruz",
    "Santa Lucia",
    "Santa Veronica District (Pob.)",
    "Santo Cristo District (Pob.)",
    "Saranay District (Pob.)",
    "Sinulatan",
    "Subol",
    "Tampac I",
    "Tampac II & III",
    "Triala",
    "Yuson",
  ],
  "0304912000": [
    "Calabasa",
    "Dampulan (Pob.)",
    "Don Mariano Marcos (Pob.)",
    "Hilera",
    "Imbunia",
    "Imelda Pob.",
    "Lambakin",
    "Langla",
    "Magsalisi",
    "Malabon-Kaingin",
    "Marawa",
    "Niyugan",
    "Ocampo-Rivera District (Pob.)",
    "Pakol",
    "Pamacpacan",
    "Pinanggaan",
    "Putlod",
    "San Jose",
    "San Josef",
    "San Pablo",
    "San Roque",
    "San Vicente",
    "Santa Rita",
    "Santo Tomas North",
    "Santo Tomas South",
    "Sapang",
    "Ulanin-Pitak",
  ],
  "0304913000": [
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Betania",
    "Canantong",
    "Nauzon",
    "Pangarulong",
    "Pinagbayanan",
    "Sagana",
    "San Felipe",
    "San Fernando",
    "San Isidro",
    "San Josef",
    "San Juan",
    "San Vicente",
    "Siclong",
  ],
  "0304914000": [
    "Aquino",
    "Linao",
    "Poblacion Norte",
    "Poblacion Sur",
    "San Casimiro",
    "San Cristobal",
    "San Jose",
    "San Juan",
    "Santa Maria",
    "Tabing Ilog",
    "Villarosa",
  ],
  "0304915000": [
    "A. Bonifacio",
    "Bagumbayan (Pob.)",
    "Bosque",
    "Caridad Norte",
    "Caridad Sur",
    "Casile",
    "Florida Blanca",
    "General Luna",
    "General Ricarte",
    "Gomez",
    "Inanama",
    "Ligaya",
    "Mabini",
    "Murcon",
    "Plaridel",
    "San Felipe",
    "San Francisco",
    "San Nicolas",
    "San Vicente",
    "Santa Barbara",
    "Victoria",
    "Villa Viniegas",
  ],
  "0304916000": [
    "Agupalo Este",
    "Agupalo Weste",
    "Alalay Chica",
    "Alalay Grande",
    "Bagong Flores",
    "Balbalungao",
    "Burgos",
    "Cordero",
    "J. U. Tienzo",
    "Mapangpang",
    "Namulandayan",
    "Parista",
    "Poblacion East",
    "Poblacion North",
    "Poblacion South",
    "Poblacion West",
    "Salvacion I",
    "Salvacion II",
    "San Antonio Este",
    "San Antonio Weste",
    "San Isidro",
    "San Pedro",
    "San Roque",
    "Santo Domingo",
  ],
  "0304917000": [
    "Bagong Sikat",
    "Balante",
    "Bantug",
    "Bical",
    "Cabisuculan",
    "Calabalabaan",
    "Calisitan",
    "Catalanacan",
    "Curva",
    "Franza",
    "Gabaldon",
    "Labney",
    "Licaong",
    "Linglingay",
    "Magtanggol",
    "Maligaya",
    "Mangandingay",
    "Mapangpang",
    "Maragol",
    "Matingkis",
    "Naglabrahan",
    "Palusapis",
    "Pandalla",
    "Poblacion East",
    "Poblacion North",
    "Poblacion South",
    "Poblacion West",
    "Rang-ayan",
    "Rizal",
    "San Andres",
    "San Antonio",
    "San Felipe",
    "Sapang Cawayan",
    "Villa Cuizon",
    "Villa Isla",
    "Villa Nati",
    "Villa Santos",
  ],
  "0304918000": [
    "Alemania",
    "Ambasador Alzate Village",
    "Cabaducan East (Pob.)",
    "Cabaducan West (Pob.)",
    "Cabawangan",
    "East Central Poblacion",
    "Edy",
    "Estacion (Pob.)",
    "Maeling",
    "Mayantoc",
    "Medico",
    "Monic",
    "North Poblacion",
    "Northwest Poblacion",
    "Recuerdo",
    "South Central Poblacion",
    "Southeast Poblacion",
    "Southwest Poblacion",
    "Tony",
    "West Central Poblacion",
    "West Poblacion",
  ],
  "0304919000": [
    "Atate",
    "Aulo",
    "Bagong Buhay",
    "Bo. Militar",
    "Caballero",
    "Caimito",
    "Doña Josefa",
    "Ganaderia",
    "Imelda Valley",
    "Langka",
    "Malate (Pob.)",
    "Maligaya",
    "Manacnac",
    "Mapait",
    "Marcos Village",
    "Popolon Pagas",
    "Santolan",
    "Sapang Buho",
    "Singalat",
  ],
  "0304920000": [
    "Cadaclan",
    "Cambitala",
    "Conversion",
    "Fatima",
    "Ganduz",
    "Liberty",
    "Malbang",
    "Marikit",
    "Napon-Napon",
    "Poblacion East",
    "Poblacion West",
    "Sampaloc",
    "San Juan",
    "Villarica",
  ],
  "0304921000": [
    "Callos",
    "Las Piñas",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "San Josef",
    "San Mariano",
    "Santo Tomas",
    "Sinasajan",
  ],
  "0304922000": [
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Bertese",
    "Doña Lucia",
    "Dulong Bayan",
    "Ilog Baliwag",
    "Pulong Bahay",
    "San Alejandro",
    "San Andres I",
    "San Andres II",
    "San Manuel",
    "San Miguel",
    "Santa Clara",
    "Santa Rita",
    "Santo Cristo",
    "Santo Tomas Feria",
  ],
  "0304923000": [
    "Agbannawag",
    "Aglipay",
    "Bicos",
    "Cabucbucan",
    "Calaocan District",
    "Canaan East",
    "Canaan West",
    "Casilagan",
    "Del Pilar",
    "Estrella",
    "General Luna",
    "Macapsing",
    "Maligaya",
    "Paco Roman",
    "Pag-asa",
    "Poblacion Central",
    "Poblacion East",
    "Poblacion Norte",
    "Poblacion Sur",
    "Poblacion West",
    "Portal",
    "San Esteban",
    "San Gregorio",
    "Santa Monica",
    "Villa Labrador",
    "Villa Paraiso",
  ],
  "0304924000": [
    "Buliran",
    "Cama Juan",
    "Julo",
    "Lawang Kupang",
    "Luyos",
    "Maugat",
    "Panabingan",
    "Papaya",
    "Poblacion",
    "San Francisco",
    "San Jose",
    "San Mariano",
    "Santa Barbara",
    "Santa Cruz",
    "Santo Cristo",
    "Tikiw",
  ],
  "0304925000": [
    "Alua",
    "Calaba",
    "Malapit",
    "Mangga",
    "Poblacion",
    "Pulo",
    "San Roque",
    "Santo Cristo",
    "Tabon",
  ],
  "0304926000": [
    "A. Pascual",
    "Abar 2nd",
    "Abar Ist",
    "Bagong Sikat",
    "Caanawan",
    "Calaocan",
    "Camanacsacan",
    "Canuto Ramos Pob.",
    "Crisanto Sanchez Pob.",
    "Culaylay",
    "Dizol",
    "Ferdinand E. Marcos Pob.",
    "Kaliwanagan",
    "Kita-Kita",
    "Malasin",
    "Manicla",
    "Palestina",
    "Parang Mangga",
    "Pinili",
    "Porais",
    "Rafael Rueda, Sr. Pob.",
    "Raymundo Eugenio Pob.",
    "San Agustin",
    "San Juan",
    "San Mauricio",
    "Santo Niño 1st",
    "Santo Niño 2nd",
    "Santo Niño 3rd",
    "Santo Tomas",
    "Sibut",
    "Sinipit Bubon",
    "Tabulac",
    "Tayabo",
    "Tondod",
    "Tulat",
    "Villa Floresca",
    "Villa Joson",
    "Villa Marina",
  ],
  "0304927000": [
    "Bonifacio District (Pob.)",
    "Burgos District (Pob.)",
    "Castellano",
    "Diversion",
    "Magpapalayoc",
    "Mallorca",
    "Mambangnan",
    "Nieves",
    "Rizal District (Pob.)",
    "San Anton",
    "San Bartolome (Pob.)",
    "San Roque",
    "Tabuating",
    "Tagumpay",
    "Tambo Adorable",
  ],
  "0304928000": [
    "Aguinaldo",
    "Berang",
    "Burgos",
    "Cojuangco (Pob.)",
    "Del Pilar",
    "Gomez",
    "Inspector",
    "Isla",
    "La Fuente",
    "Liwayway",
    "Lourdes",
    "Luna",
    "Mabini",
    "Malacañang",
    "Maliolio",
    "Mapalad",
    "Rajal Centro",
    "Rajal Norte",
    "Rajal Sur",
    "Rizal (Pob.)",
    "San Gregorio",
    "San Isidro",
    "San Josep",
    "San Mariano",
    "San Pedro",
    "Santa Teresita",
    "Santo Rosario",
    "Sapsap",
    "Soledad",
    "Tagpos",
    "Tramo",
    "Valenzuela (Pob.)",
    "Zamora (Pob.)",
  ],
  "0304929000": [
    "Baloc",
    "Buasao",
    "Burgos",
    "Cabugao",
    "Casulucan",
    "Comitang",
    "Concepcion",
    "Dolores",
    "General Luna",
    "Hulo",
    "Mabini",
    "Malasin",
    "Malaya",
    "Malayantoc",
    "Mambarao",
    "Poblacion",
    "Pulong Buli",
    "Sagaba",
    "San Agustin",
    "San Fabian",
    "San Francisco",
    "San Pascual",
    "Santa Rita",
    "Santo Rosario",
  ],
  "0304930000": [
    "Andal Alino (Pob.)",
    "Bagong Sikat",
    "Bagong Silang",
    "Bakal I",
    "Bakal II",
    "Bakal III",
    "Baluga",
    "Bantug",
    "Bantug Hacienda",
    "Bantug Hamog",
    "Bugtong na Buli",
    "Bulac",
    "Burnay",
    "Caaniplahan",
    "Cabubulaonan",
    "Calipahan",
    "Campos",
    "Caputican",
    "Casulucan Este",
    "Collado",
    "Dimasalang Norte",
    "Dimasalang Sur",
    "Dinarayat",
    "Esguerra District (Pob.)",
    "Gulod",
    "Homestead I",
    "Homestead II",
    "Kinalanguyan",
    "La Torre",
    "Lomboy",
    "Mabuhay",
    "Maestrang Kikay (Pob.)",
    "Mamandil",
    "Marcos District (Pob.)",
    "Matingkis",
    "Minabuyoc",
    "Pag-asa (Pob.)",
    "Paludpod",
    "Pantoc Bulac",
    "Pinagpanaan",
    "Poblacion Sur",
    "Pula",
    "Pulong San Miguel (Pob.)",
    "Purok Matias (Pob.)",
    "Sampaloc",
    "San Miguel na Munti",
    "San Pascual",
    "San Ricardo",
    "Sibul",
    "Sicsican Matanda",
    "Tabacao",
    "Tagaytay",
    "Valle",
  ],
  "0304931000": [
    "Alula",
    "Baybayabas",
    "Buted",
    "Cabiangan",
    "Calisitan",
    "Cinense",
    "Culiat",
    "Maasin",
    "Magsaysay (Pob.)",
    "Mayamot I",
    "Mayamot II",
    "Nangabulan",
    "Osmeña (Pob.)",
    "Pangit",
    "Patola",
    "Quezon (Pob.)",
    "Quirino (Pob.)",
    "Roxas (Pob.)",
    "Saguing",
    "Sampaloc",
    "Santa Catalina",
    "Santo Domingo",
    "Saringaya",
    "Saverona",
    "Tandoc",
    "Tibag",
    "Villa Boado",
    "Villa Rosario",
  ],
  "0304932000": [
    "Batitang",
    "Carmen",
    "Concepcion",
    "Del Pilar",
    "General Luna",
    "H. Romero",
    "Macarse",
    "Manaul",
    "Mayamot",
    "Pantoc",
    "San Isidro",
    "San Rafael",
    "San Vicente (Pob.)",
    "Santa Cruz",
    "Santa Lucia Old",
    "Santa Lucia Young",
    "Santo Rosario Old",
    "Santo Rosario Young",
    "Valeriana",
  ],
  "0305402000": [
    "Balucuc",
    "Calantipe",
    "Cansinala",
    "Capalangan",
    "Colgante",
    "Paligui",
    "Sampaloc",
    "San Juan (Pob.)",
    "San Vicente",
    "Sucad",
    "Sulipan",
    "Tabuyuc",
  ],
  "0305403000": [
    "Arenas",
    "Baliti",
    "Batasan",
    "Buensuceso",
    "Candating",
    "Cupang",
    "Gatiawin",
    "Guemasan",
    "Kaledian",
    "La Paz",
    "Lacmit",
    "Lacquios",
    "Mangga-Cacutud",
    "Mapalad",
    "Matamo",
    "Panlinlang",
    "Paralaya",
    "Plazang Luma",
    "Poblacion",
    "San Agustin Norte",
    "San Agustin Sur",
    "San Antonio",
    "San Jose Mesulo",
    "San Juan Bano",
    "San Mateo",
    "San Nicolas",
    "San Roque Bitas",
    "Santo Niño Tabuan",
    "Suclayin",
    "Telapayong",
  ],
  "0305404000": [
    "Balas",
    "Cabalantian",
    "Cabambangan (Pob.)",
    "Cabetican",
    "Calibutbut",
    "Concepcion",
    "Dolores",
    "Duat",
    "Macabacle",
    "Magliman",
    "Maliwalu",
    "Mesalipit",
    "Parulog",
    "Potrero",
    "San Antonio",
    "San Isidro",
    "San Vicente",
    "Santa Barbara",
    "Santa Ines",
    "Talba",
    "Tinajero",
  ],
  "0305405000": [
    "Bahay Pare",
    "Bambang",
    "Barangca",
    "Barit",
    "Buas (Pob.)",
    "Cuayang Bugtong",
    "Dalayap",
    "Dulong Ilog",
    "Gulap",
    "Lanang",
    "Lourdes",
    "Magumbali",
    "Mandasig",
    "Mandili",
    "Mangga",
    "Mapaniqui",
    "Paligui",
    "Pangclara",
    "Pansinao",
    "Paralaya (Pob.)",
    "Pasig",
    "Pescadores (Pob.)",
    "Pulong Gubat",
    "Pulong Palazan",
    "Salapungan",
    "San Agustin (Pob.)",
    "Santo Rosario",
    "Tagulod",
    "Talang",
    "Tenejero",
    "Vizal San Pablo",
    "Vizal Santo Cristo",
    "Vizal Santo Niño",
  ],
  "0305406000": [
    "Anon",
    "Apalit",
    "Basa Air Base",
    "Benedicto",
    "Bodega",
    "Cabangcalan",
    "Calantas",
    "Carmencita",
    "Consuelo",
    "Dampe",
    "Del Carmen",
    "Fortuna",
    "Gutad",
    "Mabical",
    "Maligaya",
    "Mawacat",
    "Nabuclod",
    "Pabanlag",
    "Paguiruan",
    "Palmayo",
    "Pandaguirig",
    "Poblacion",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Nicolas",
    "San Pedro",
    "San Ramon",
    "San Roque",
    "Solib",
    "Sta. Monica",
    "Sto. Rosario",
    "Valdez",
  ],
  "0305407000": [
    "Ascomo",
    "Bancal",
    "Jose Abad Santos",
    "Lambac",
    "Magsaysay",
    "Maquiapo",
    "Natividad",
    "Plaza Burgos (Pob.)",
    "Pulungmasle",
    "Rizal",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Juan Bautista",
    "San Juan Nepomuceno",
    "San Matias",
    "San Miguel",
    "San Nicolas 1st",
    "San Nicolas 2nd",
    "San Pablo",
    "San Pedro",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santa Filomena (Pob.)",
    "Santa Ines",
    "Santa Ursula",
    "Santo Cristo",
    "Santo Niño (Pob.)",
  ],
  "0305408000": [
    "Balantacan",
    "Bancal Pugad",
    "Bancal Sinubli",
    "Baruya",
    "Calangain",
    "Concepcion",
    "De La Paz",
    "Del Carmen",
    "Don Ignacio Dimson",
    "Lourdes",
    "Prado Siongco",
    "Remedios",
    "San Agustin",
    "San Antonio",
    "San Francisco",
    "San Isidro",
    "San Jose Apunan",
    "San Jose Gumi",
    "San Juan (Pob.)",
    "San Matias",
    "San Miguel",
    "San Nicolas 1st (Pob.)",
    "San Nicolas 2nd",
    "San Pablo 1st",
    "San Pablo 2nd",
    "San Pedro Palcarangan",
    "San Pedro Saug",
    "San Roque Arbol",
    "San Roque Dau",
    "San Vicente",
    "Santa Barbara",
    "Santa Catalina",
    "Santa Cruz",
    "Santa Lucia (Pob.)",
    "Santa Maria",
    "Santa Monica",
    "Santa Rita",
    "Santa Teresa 1st",
    "Santa Teresa 2nd",
    "Santiago",
    "Santo Cristo",
    "Santo Domingo",
    "Santo Niño",
    "Santo Tomas (Pob.)",
  ],
  "0305409000": [
    "Atlu-Bola",
    "Bical",
    "Bundagul",
    "Cacutud",
    "Calumpang",
    "Camachiles",
    "Dapdap",
    "Dau",
    "Dolores",
    "Duquit",
    "Lakandula",
    "Mabiga",
    "Macapagal Village",
    "Mamatitang",
    "Mangalit",
    "Marcos Village",
    "Mawaque",
    "Paralayunan",
    "Poblacion",
    "San Francisco",
    "San Joaquin",
    "Santa Ines",
    "Santa Maria",
    "Santo Rosario",
    "Sapang Balen",
    "Sapang Biabas",
    "Tabun",
  ],
  "0305410000": [
    "Batasan",
    "Caduang Tete",
    "Candelaria",
    "Castuli",
    "Consuelo",
    "Dalayap",
    "Mataguiti",
    "San Esteban",
    "San Francisco",
    "San Gabriel (Pob.)",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Saplad David",
    "Sta. Cruz (Pob.)",
    "Sta. Lutgarda",
    "Sta. Maria",
    "Sta. Rita (Pob.)",
    "Sto. Niño",
    "Sto. Rosario (Pob.)",
    "Tacasan",
    "Telacsan",
  ],
  "0305411000": [
    "Ayala",
    "Bucanan",
    "Camias",
    "Dolores",
    "Escaler",
    "La Paz",
    "Navaling",
    "San Agustin",
    "San Antonio",
    "San Franciso",
    "San Ildefonso",
    "San Isidro",
    "San Jose",
    "San Miguel",
    "San Nicolas 1st (Pob.)",
    "San Nicolas 2nd",
    "San Pablo (Pob.)",
    "San Pedro I",
    "San Pedro II",
    "San Roque",
    "San Vicente",
    "Santa Cruz (Pob.)",
    "Santa Lucia",
    "Santa Maria",
    "Santo Niño",
    "Santo Rosario",
    "Turu",
  ],
  "0305412000": [
    "Alauli",
    "Bagang",
    "Balibago",
    "Bebe Anac",
    "Bebe Matua",
    "Bulacus",
    "Cambasi",
    "Malauli",
    "Nigui",
    "Palimpe",
    "Puti",
    "Sagrada",
    "San Agustin",
    "San Isidro Anac",
    "San Isidro Matua (Pob.)",
    "San Nicolas (Pob.)",
    "San Pedro",
    "Sapang Kawayan",
    "Sta. Cruz",
    "Sta. Lucia Anac (Pob.)",
    "Sta. Lucia Matua",
    "Sta. Lucia Paguiba",
    "Sta. Lucia Wakas",
    "Sta. Monica",
    "Sto. Niño",
    "Sua",
  ],
  "0305413000": [
    "Acli",
    "Anao",
    "Balas",
    "Buenavista",
    "Camuning",
    "Cawayan",
    "Concepcion",
    "Culubasa",
    "Divisoria",
    "Dolores",
    "Eden",
    "Gandus",
    "Lagundi",
    "Laput",
    "Laug",
    "Masamat",
    "Masangsang",
    "Nueva Victoria",
    "Pandacaqui",
    "Pangatlan",
    "Panipuan",
    "Parian (Pob.)",
    "Sabanilla",
    "San Antonio",
    "San Carlos",
    "San Jose Malino",
    "San Jose Matulid",
    "San Juan",
    "San Lorenzo",
    "San Miguel",
    "San Nicolas",
    "San Pablo",
    "San Patricio",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Santa Maria",
    "Santo Domingo",
    "Santo Rosario",
    "Sapang Maisac",
    "Suclaban",
    "Tangle",
  ],
  "0305414000": [
    "Bulac",
    "Dawe",
    "Lourdes",
    "Maniango",
    "San Francisco 1st",
    "San Francisco 2nd",
    "San Isidro",
    "San Nicolas (Pob.)",
    "San Pedro",
    "Saplad",
    "Sta. Catalina",
    "Sta. Maria",
    "Sta. Rita",
    "Sto. Domingo",
    "Sto. Rosario (Pob.)",
  ],
  "0305415000": [
    "Babo Pangulo",
    "Babo Sacan",
    "Balubad",
    "Calzadang Bayu",
    "Camias",
    "Cangatba",
    "Diaz",
    "Dolores",
    "Inararo",
    "Jalung",
    "Mancatian",
    "Manibaug Libutad",
    "Manibaug Paralaya",
    "Manibaug Pasig",
    "Manuali",
    "Mitla Proper",
    "Palat",
    "Pias",
    "Pio",
    "Planas",
    "Poblacion",
    "Pulung Santol",
    "Salu",
    "San Jose Mitla",
    "Sapang Uwak",
    "Sepung Bulaon",
    "Sinura",
    "Sta. Cruz",
    "Villa Maria",
  ],
  "0305416000": [
    "Alasas",
    "Baliti",
    "Bulaon",
    "Calulut",
    "Del Carmen",
    "Del Pilar",
    "Del Rosario",
    "Dela Paz Norte",
    "Dela Paz Sur",
    "Dolores",
    "Juliana",
    "Lara",
    "Lourdes",
    "Magliman",
    "Maimpis",
    "Malino",
    "Malpitic",
    "Pandaras",
    "Panipuan",
    "Pulung Bulu",
    "Quebiauan",
    "Saguin",
    "San Agustin",
    "San Felipe",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Nicolas",
    "San Pedro",
    "Santa Lucia",
    "Santa Teresita",
    "Santo Niño",
    "Santo Rosario (Pob.)",
    "Sindalan",
    "Telabastagan",
  ],
  "0305417000": [
    "San Agustin",
    "San Carlos",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Nicolas",
    "San Roque",
    "San Sebastian",
    "Santa Catalina",
    "Santa Cruz Pambilog",
    "Santa Cruz Poblacion",
    "Santa Lucia",
    "Santa Monica",
    "Santa Rita",
    "Santo Niño",
    "Santo Rosario",
    "Santo Tomas",
  ],
  "0305418000": [
    "Concepcion",
    "De La Paz",
    "San Agustin",
    "San Isidro",
    "San Jose",
    "San Juan (Pob.)",
    "San Miguel",
    "San Nicolas",
    "San Pablo Libutad",
    "San Pablo Proper",
    "San Pedro",
    "Santa Cruz",
    "Santa Monica",
    "Santo Niño",
  ],
  "0305419000": [
    "San Agustin",
    "San Bartolome",
    "San Isidro",
    "San Joaquin (Pob.)",
    "San Jose",
    "San Juan",
    "San Nicolas",
    "San Pablo",
    "San Pedro",
    "San Roque",
    "Santa Lucia",
    "Santa Maria",
    "Santiago",
    "Santo Rosario",
  ],
  "0305420000": [
    "Becuran",
    "Dila-dila",
    "San Agustin",
    "San Basilio",
    "San Isidro",
    "San Jose (Pob.)",
    "San Juan",
    "San Matias",
    "San Vicente",
    "Santa Monica",
  ],
  "0305421000": [
    "Moras De La Paz",
    "Poblacion",
    "San Bartolome",
    "San Matias",
    "San Vicente",
    "Santo Rosario",
    "Sapa",
  ],
  "0305422000": [
    "Batang 1st",
    "Batang 2nd",
    "Mabuanbuan",
    "Malusac",
    "San Antonio",
    "San Nicolas 1st",
    "San Nicolas 2nd",
    "San Pedro",
    "Santa Monica",
    "Santo Tomas",
    "Sebitanan",
    "Sta. Lucia (Pob.)",
  ],
  "0306901000": [
    "Baguindoc",
    "Bantog",
    "Campos",
    "Carmen",
    "Casili",
    "Don Ramon",
    "Hernando",
    "Poblacion",
    "Rizal",
    "San Francisco East",
    "San Francisco West",
    "San Jose North",
    "San Jose South",
    "San Juan",
    "San Roque",
    "Santo Domingo",
    "Sinense",
    "Suaverdez",
  ],
  "0306902000": [
    "Anupul",
    "Banaba",
    "Bangcu",
    "Culubasa",
    "Dela Cruz",
    "La Paz",
    "Lourdes",
    "Malonzo",
    "San Nicolas (Pob.)",
    "San Pedro",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santo Niño",
    "Virgen de los Remedios",
  ],
  "0306903000": [
    "Anoling 1st",
    "Anoling 2nd",
    "Anoling 3rd",
    "Bacabac",
    "Bacsay",
    "Bancay 1st",
    "Bilad",
    "Birbira",
    "Bobon 1st",
    "Bobon 2nd",
    "Bobon Caarosipan",
    "Cabanabaan",
    "Cacamilingan Norte",
    "Cacamilingan Sur",
    "Caniag",
    "Carael",
    "Cayaoan",
    "Cayasan",
    "Florida",
    "Lasong",
    "Libueg",
    "Malacampa",
    "Manaquem",
    "Manupeg",
    "Marawi",
    "Matubog",
    "Nagrambacan",
    "Nagserialan",
    "Palimbo Caarosipan",
    "Palimbo Proper",
    "Pao 1st",
    "Pao 2nd",
    "Pao 3rd",
    "Papaac",
    "Pindangan 1st",
    "Pindangan 2nd",
    "Poblacion A",
    "Poblacion B",
    "Poblacion C",
    "Poblacion D",
    "Poblacion E",
    "Poblacion F",
    "Poblacion G",
    "Poblacion H",
    "Poblacion I",
    "Poblacion J",
    "San Isidro",
    "Sawat",
    "Sinilian 1st",
    "Sinilian 2nd",
    "Sinilian 3rd",
    "Sinilian Cacalibosoan",
    "Sinulatan 1st",
    "Sinulatan 2nd",
    "Sta. Maria",
    "Surgui 1st",
    "Surgui 2nd",
    "Surgui 3rd",
    "Tambugan",
    "Telbang",
    "Tuec",
  ],
  "0306904000": [
    "Aranguren",
    "Bueno",
    "Cristo Rey",
    "Cubcub (Pob.)",
    "Cutcut 1st",
    "Cutcut 2nd",
    "Dolores",
    "Estrada",
    "Lawy",
    "Manga",
    "Manlapig",
    "Maruglu",
    "O'Donnell",
    "Santa Juliana",
    "Santa Lucia",
    "Santa Rita",
    "Santo Domingo 1st",
    "Santo Domingo 2nd",
    "Santo Rosario",
    "Talaga",
  ],
  "0306905000": [
    "Alfonso",
    "Balutu",
    "Cafe",
    "Calius Gueco",
    "Caluluan",
    "Castillo",
    "Corazon de Jesus",
    "Culatingan",
    "Dungan",
    "Dutung-A-Matas",
    "Green Village",
    "Lilibangan",
    "Mabilog",
    "Magao",
    "Malupa",
    "Minane",
    "Panalicsian",
    "Pando",
    "Parang",
    "Parulung",
    "Pitabunan",
    "San Agustin",
    "San Antonio",
    "San Bartolome",
    "San Francisco",
    "San Isidro",
    "San Jose (Pob.)",
    "San Juan",
    "San Martin",
    "San Nicolas (Pob.)",
    "San Nicolas Balas",
    "San Vicente",
    "Santa Cruz",
    "Santa Maria",
    "Santa Monica",
    "Santa Rita",
    "Santa Rosa",
    "Santiago",
    "Santo Cristo",
    "Santo Niño",
    "Santo Rosario",
    "Talimunduc Marimla",
    "Talimunduc San Miguel",
    "Telabanca",
    "Tinang",
  ],
  "0306906000": [
    "Abagon",
    "Amacalan",
    "Apsayan",
    "Ayson",
    "Bawa",
    "Buenlag",
    "Bularit",
    "Calayaan",
    "Carbonel",
    "Cardona",
    "Caturay",
    "Danzo",
    "Dicolor",
    "Don Basilio",
    "Luna",
    "Mabini",
    "Magaspac",
    "Malayep",
    "Matapitap",
    "Matayumcab",
    "New Salem",
    "Oloybuaya",
    "Padapada",
    "Parsolingan",
    "Pinasling",
    "Plastado",
    "Poblacion 1",
    "Poblacion 2",
    "Poblacion 3",
    "Quezon",
    "Rizal",
    "Salapungan",
    "San Agustin",
    "San Antonio",
    "San Bartolome",
    "San Jose",
    "Santa Lucia",
    "Santiago",
    "Sembrano",
    "Singat",
    "Sulipa",
    "Tagumbao",
    "Tangcaran",
    "Villa Paz",
  ],
  "0306907000": [
    "Balanoy",
    "Bantog-Caricutan",
    "Caramutan",
    "Caut",
    "Comillas",
    "Dumarais",
    "Guevarra",
    "Kapanikian",
    "La Purisima",
    "Lara",
    "Laungcupang",
    "Lomboy",
    "Macalong",
    "Matayumtayum",
    "Mayang",
    "Motrico",
    "Paludpud",
    "Rizal",
    "San Isidro (Pob.)",
    "San Roque (Pob.)",
    "Sierra",
  ],
  "0306908000": [
    "Ambalingit",
    "Baybayaoas",
    "Bigbiga",
    "Binbinaca",
    "Calabtangan",
    "Caocaoayan",
    "Carabaoan",
    "Cubcub",
    "Gayonggayong",
    "Gossood",
    "Labney",
    "Mamonit",
    "Maniniog",
    "Mapandan",
    "Nambalan",
    "Pedro L. Quines",
    "Pitombayog",
    "Poblacion Norte",
    "Poblacion Sur",
    "Rotrottooc",
    "San Bartolome",
    "San Jose",
    "Taldiapan",
    "Tangcarang",
  ],
  "0306909000": [
    "Ablang-Sapang",
    "Aringin",
    "Atencio",
    "Banaoang East",
    "Banaoang West",
    "Baquero Norte",
    "Baquero Sur",
    "Burgos",
    "Calamay",
    "Calapan",
    "Camangaan East",
    "Camangaan West",
    "Camposanto 1 - Norte",
    "Camposanto 1 - Sur",
    "Camposanto 2",
    "Capaoayan",
    "Lapsing",
    "Mabini",
    "Maluac",
    "Poblacion 1",
    "Poblacion 2",
    "Poblacion 3",
    "Poblacion 4",
    "Rizal",
    "San Juan",
    "San Julian",
    "San Leon",
    "San Pedro",
    "San Roque",
    "Santa Lucia East",
    "Santa Lucia West",
    "Santa Maria",
    "Santa Monica",
    "Tolega Norte",
    "Tolega Sur",
    "Tubectubang",
    "Villa",
  ],
  "0306910000": [
    "Abogado",
    "Acocolao",
    "Aduas",
    "Apulid",
    "Balaoang",
    "Barang",
    "Brillante",
    "Burgos",
    "Cabayaoasan",
    "Canan",
    "Carino",
    "Cayanga",
    "Colibangbang",
    "Coral",
    "Dapdap",
    "Estacion",
    "Mabilang",
    "Manaois",
    "Matalapitap",
    "Nagmisaan",
    "Nancamarinan",
    "Nipaco",
    "Patalan",
    "Poblacion Norte",
    "Poblacion Sur",
    "Rang-ayan",
    "Salumague",
    "Samput",
    "San Carlos",
    "San Isidro",
    "San Juan de Milla",
    "Santa Ines",
    "Sinigpit",
    "Tablang",
    "Ventenilla",
  ],
  "0306911000": [
    "Balite",
    "Buenavista",
    "Cadanglaan",
    "Estipona",
    "Linao",
    "Maasin",
    "Matindeg",
    "Maungib",
    "Naya",
    "Nilasin 1st",
    "Nilasin 2nd",
    "Poblacion 1",
    "Poblacion 2",
    "Poblacion 3",
    "Poroc",
    "Singat",
  ],
  "0306912000": [
    "Coral-Iloco",
    "Guiteb",
    "Pance",
    "Poblacion Center",
    "Poblacion North",
    "Poblacion South",
    "San Juan",
    "San Raymundo",
    "Toledo",
  ],
  "0306913000": [
    "Balloc",
    "Bamban",
    "Casipo",
    "Catagudingan",
    "Daldalayap",
    "Doclong 1",
    "Doclong 2",
    "Maasin",
    "Nagsabaran",
    "Pit-ao",
    "Poblacion Norte",
    "Poblacion Sur",
  ],
  "0306914000": [
    "Colubot",
    "Lanat",
    "Legaspi",
    "Mangandingay",
    "Matarannoc",
    "Pacpaco",
    "Poblacion",
    "Salcedo",
    "San Agustin",
    "San Felipe",
    "San Jacinto",
    "San Miguel",
    "San Narciso",
    "San Vicente",
    "Santa Maria",
  ],
  "0306915000": [
    "Baldios",
    "Botbotones",
    "Caanamongan",
    "Cabaruan",
    "Cabugbugan",
    "Caduldulaoan",
    "Calipayan",
    "Macaguing",
    "Nambalan",
    "Padapada",
    "Pilpila",
    "Pinpinas",
    "Poblacion East",
    "Poblacion West",
    "Pugo-Cecilio",
    "San Francisco",
    "San Sotero",
    "San Vicente",
    "Santa Ines Centro",
    "Santa Ines East",
    "Santa Ines West",
    "Taguiporo",
    "Timmaguab",
    "Vargas",
  ],
  "0306916000": [
    "Aguso",
    "Alvindia Segundo",
    "Amucao",
    "Armenia",
    "Asturias",
    "Atioc",
    "Balanti",
    "Balete",
    "Balibago I",
    "Balibago II",
    "Balingcanaway",
    "Banaba",
    "Bantog",
    "Baras-baras",
    "Batang-batang",
    "Binauganan",
    "Bora",
    "Buenavista",
    "Buhilit",
    "Burot",
    "Calingcuan",
    "Capehan",
    "Carangian",
    "Care",
    "Central",
    "Culipat",
    "Cut-cut I",
    "Cut-cut II",
    "Dalayap",
    "Dela Paz",
    "Dolores",
    "Laoang",
    "Ligtasan",
    "Lourdes",
    "Mabini",
    "Maligaya",
    "Maliwalo",
    "Mapalacsiao",
    "Mapalad",
    "Matadero",
    "Matatalaib",
    "Paraiso",
    "Poblacion",
    "Salapungan",
    "San Carlos",
    "San Francisco",
    "San Isidro",
    "San Jose",
    "San Jose de Urquico",
    "San Juan de Mata",
    "San Luis",
    "San Manuel",
    "San Miguel",
    "San Nicolas",
    "San Pablo",
    "San Pascual",
    "San Rafael",
    "San Roque",
    "San Sebastian",
    "San Vicente",
    "Santa Cruz",
    "Santa Maria",
    "Santo Cristo",
    "Santo Domingo",
    "Santo Niño",
    "Sapang Maragul",
    "Sapang Tagalog",
    "Sepung Calzada",
    "Sinait",
    "Suizo",
    "Tariji",
    "Tibag",
    "Tibagan",
    "Trinidad",
    "Ungot",
    "Villa Bacolor",
  ],
  "0306917000": [
    "Baculong",
    "Balayang",
    "Balbaloto",
    "Bangar",
    "Bantog",
    "Batangbatang",
    "Bulo",
    "Cabuluan",
    "Calibungan",
    "Canarem",
    "Cruz",
    "Lalapac",
    "Maluid",
    "Mangolago",
    "Masalasa",
    "Palacpalac",
    "San Agustin",
    "San Andres",
    "San Fernando (Pob.)",
    "San Francisco",
    "San Gavino (Pob.)",
    "San Jacinto",
    "San Nicolas (Pob.)",
    "San Vicente",
    "Santa Barbara",
    "Santa Lucia (Pob.)",
  ],
  "0306918000": [
    "Burgos",
    "David",
    "Iba",
    "Labney",
    "Lawacamulag",
    "Lubigan",
    "Maamot",
    "Mababanaba",
    "Moriones",
    "Pao",
    "San Juan de Valdez",
    "Sula",
    "Villa Aglipay",
  ],
  "0307101000": [
    "Bancal",
    "Bangan",
    "Batonlapoc",
    "Belbel",
    "Beneg",
    "Binoclutan",
    "Burgos",
    "Cabatuan",
    "Capayawan",
    "Carael",
    "Danacbunga",
    "Maguisguis",
    "Malomboy",
    "Mambog",
    "Moraza",
    "Nacolcol",
    "Owaog-Nebloc",
    "Paco (Pob.)",
    "Palis",
    "Panan",
    "Parel",
    "Paudpod",
    "Poonbato",
    "Porac",
    "San Isidro",
    "San Juan",
    "San Miguel",
    "Santiago",
    "Tampo (Pob.)",
    "Taugtog",
    "Villar",
  ],
  "0307102000": [
    "Anonang",
    "Apo-apo",
    "Arew",
    "Banuanbayo (Pob.)",
    "Cadmang-Reserva",
    "Camiling (Camiing)",
    "Casabaan",
    "Del Carmen (Pob.)",
    "Dolores (Pob.)",
    "Felmida-Diaz",
    "Laoag",
    "Lomboy",
    "Longos",
    "Mabanglit",
    "New San Juan",
    "San Antonio",
    "San Isidro",
    "San Juan (Pob.)",
    "San Rafael",
    "Santa Rita",
    "Santo Niño",
    "Tondo",
  ],
  "0307103000": [
    "Babancal",
    "Binabalian",
    "Catol",
    "Dampay",
    "Lauis",
    "Libertador",
    "Malabon",
    "Malimanga",
    "Pamibian",
    "Panayonan",
    "Pinagrealan",
    "Poblacion",
    "Sinabacan",
    "Taposo",
    "Uacon",
    "Yamot",
  ],
  "0307104000": [
    "Balaybay",
    "Buenavista",
    "Del Pilar",
    "Looc",
    "Magsaysay",
    "Nagbayan",
    "Nagbunga",
    "San Agustin",
    "San Jose (Pob.)",
    "San Juan (Pob.)",
    "San Nicolas",
    "San Pablo (Pob.)",
    "San Roque",
    "Santa Maria",
  ],
  "0307105000": [
    "Amungan",
    "Bangantalinga",
    "Dirita-Baloguen",
    "Lipay-Dingin-Panibuatan",
    "Palanginan",
    "San Agustin",
    "Santa Barbara",
    "Santo Rosario",
    "Zone 1 Pob.",
    "Zone 2 Pob.",
    "Zone 3 Pob.",
    "Zone 4 Pob.",
    "Zone 5 Pob.",
    "Zone 6 Pob.",
  ],
  "0307106000": [
    "Baloganon",
    "Bamban",
    "Bani",
    "Collat",
    "Inhobol",
    "North Poblacion",
    "San Lorenzo",
    "San Salvador",
    "Santa Rita",
    "Santo Rosario",
    "South Poblacion",
    "Taltal",
    "Tapuac",
  ],
  "0307108000": [
    "Alwa",
    "Bato",
    "Bulawen",
    "Cauyan",
    "East Poblacion",
    "Garreta",
    "Libaba",
    "Liozon",
    "Lipay",
    "Locloc",
    "Macarang",
    "Magalawa",
    "Pangolingan",
    "Salaza",
    "San Juan",
    "Sto. Niño",
    "Sto. Tomas",
    "Tition",
    "West Poblacion",
  ],
  "0307109000": [
    "Angeles",
    "Antipolo (Pob.)",
    "Burgos (Pob.)",
    "East Dirita",
    "Luna (Pob.)",
    "Pundaquit",
    "Rizal",
    "San Esteban",
    "San Gregorio (Pob.)",
    "San Juan (Pob.)",
    "San Miguel",
    "San Nicolas (Pob.)",
    "Santiago",
    "West Dirita",
  ],
  "0307110000": [
    "Amagna (Pob.)",
    "Apostol (Pob.)",
    "Balincaguing",
    "Farañal (Pob.)",
    "Feria (Pob.)",
    "Maloma",
    "Manglicmot (Pob.)",
    "Rosete (Pob.)",
    "San Rafael",
    "Sindol",
    "Sto. Niño",
  ],
  "0307111000": [
    "Aglao",
    "Buhawen",
    "Burgos (Pob.)",
    "Central (Pob.)",
    "Consuelo Norte",
    "Consuelo Sur (Pob.)",
    "La Paz (Pob.)",
    "Laoag",
    "Linasin",
    "Linusungan",
    "Lucero (Pob.)",
    "Nagbunga",
    "Rabanes",
    "Rizal (Pob.)",
    "San Guillermo (Pob.)",
    "San Isidro (Pob.)",
    "San Rafael",
    "Santa Fe",
  ],
  "0307112000": [
    "Alusiis",
    "Beddeng",
    "Candelaria (Pob.)",
    "Dallipawen",
    "Grullo",
    "La Paz",
    "Libertad (Pob.)",
    "Namatacan",
    "Natividad (Pob.)",
    "Omaya",
    "Paite",
    "Patrocinio (Pob.)",
    "San Jose (Pob.)",
    "San Juan (Pob.)",
    "San Pascual (Pob.)",
    "San Rafael (Pob.)",
    "Simminublan",
  ],
  "0307113000": [
    "Babuyan",
    "Bangcol",
    "Bayto",
    "Biay",
    "Bolitoc",
    "Bulawon",
    "Canaynayan",
    "Gama",
    "Guinabon",
    "Guisguis",
    "Lipay",
    "Lomboy",
    "Lucapon North",
    "Lucapon South",
    "Malabago",
    "Naulo",
    "Pagatpat",
    "Pamonoran",
    "Poblacion North",
    "Poblacion South",
    "Sabang",
    "San Fernando",
    "Tabalong",
    "Tubotubo North",
    "Tubotubo South",
  ],
  "0307114000": [
    "Aningway Sacatihan",
    "Asinan Poblacion",
    "Asinan Proper",
    "Baraca-Camachile (Pob.)",
    "Batiawan",
    "Calapacuan",
    "Calapandayan (Pob.)",
    "Cawag",
    "Ilwas (Pob.)",
    "Mangan-Vaca",
    "Matain",
    "Naugsol",
    "Pamatawan",
    "San Isidro",
    "Santo Tomas",
    "Wawandue (Pob.)",
  ],
  "0307701000": [
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Buhangin",
    "Calabuanan",
    "Obligacion",
    "Pingit",
    "Reserva",
    "Sabang",
    "Suclayin",
    "Zabali",
  ],
  "0307702000": [
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Bianuan",
    "Calabgan",
    "Calangcuasan",
    "Calantas",
    "Cozo",
    "Culat",
    "Dibacong",
    "Dibet",
    "Ditinagyan",
    "Esperanza",
    "Esteves",
    "Lual",
    "Marikit",
    "San Ildefonso",
    "Tabas",
    "Tinib",
  ],
  "0307703000": [
    "Diagyan",
    "Dicabasan",
    "Dilaguidi",
    "Dimaseset",
    "Diniog",
    "Esperanza",
    "Lawang",
    "Maligaya (Pob.)",
    "Manggitahan",
    "Masagana (Pob.)",
    "Ura",
  ],
  "0307704000": [
    "Abuleg",
    "Dibaraybay",
    "Ditawini",
    "Mapalad",
    "Nipoo",
    "Paleg",
    "Simbahan",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
  ],
  "0307705000": [
    "Aplaya",
    "Butas Na Bato",
    "Cabog",
    "Caragsacan",
    "Davildavilan",
    "Dikapanikian",
    "Ibona",
    "Paltic",
    "Poblacion",
    "Tanawan",
    "Umiray",
  ],
  "0307706000": [
    "Bayabas",
    "Borlongan",
    "Buenavista",
    "Calaocan",
    "Diamanen",
    "Dianed",
    "Diarabasin",
    "Dibutunan",
    "Dimabuno",
    "Dinadiawan",
    "Ditale",
    "Gupa",
    "Ipil",
    "Laboy",
    "Lipit",
    "Lobbot",
    "Maligaya",
    "Mijares",
    "Mucdol",
    "North Poblacion",
    "Puangi",
    "Salay",
    "Sapangkawayan",
    "South Poblacion",
    "Toytoyan",
  ],
  "0307707000": [
    "Alcala",
    "Bagtu",
    "Bangco",
    "Bannawag",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Baubo",
    "Bayanihan",
    "Bazal",
    "Cabituculan East",
    "Cabituculan West",
    "Cadayacan",
    "Debucao",
    "Decoliat",
    "Detailen",
    "Diaat",
    "Dialatman",
    "Diaman",
    "Dianawan",
    "Dikildit",
    "Dimanpudso",
    "Diome",
    "Estonilo",
    "Florida",
    "Galintuja",
    "Malasin",
    "Ponglo",
    "Quirino",
    "Ramada",
    "San Joaquin",
    "San Jose",
    "San Juan",
    "San Leonardo",
    "Santa Lucia",
    "Santo Tomas",
    "Suguit",
    "Villa Aurora",
    "Wenceslao",
  ],
  "0307708000": [
    "Bacong",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Dibalo",
    "Dibayabay",
    "Dibut",
    "Dikapinisan",
    "Dimanayat",
    "Diteki",
    "Ditumabo",
    "L. Pimentel",
    "Nonong Senior",
    "Real",
    "San Isidro",
    "San Jose",
    "Zarah",
  ],
  "0330100000": [
    "Agapito del Rosario",
    "Amsic",
    "Anunas",
    "Balibago",
    "Capaya",
    "Claro M. Recto",
    "Cuayan",
    "Cutcut",
    "Cutud",
    "Lourdes North West",
    "Lourdes Sur",
    "Lourdes Sur East",
    "Malabañas",
    "Margot",
    "Mining",
    "Ninoy Aquino",
    "Pampang",
    "Pandan",
    "Pulung Cacutud",
    "Pulung Maragul",
    "Pulungbulu",
    "Salapungan",
    "San Jose",
    "San Nicolas",
    "Sapalibutad",
    "Sapangbato",
    "Sta. Teresita",
    "Sta. Trinidad",
    "Sto. Cristo",
    "Sto. Domingo",
    "Sto. Rosario (Pob.)",
    "Tabun",
    "Virgen Delos Remedios",
  ],
  "0331400000": [
    "Asinan",
    "Banicain",
    "Barretto",
    "East Bajac-bajac",
    "East Tapinac",
    "Gordon Heights",
    "Kalaklan",
    "Mabayuan",
    "New Cabalan",
    "New Ilalim",
    "New Kababae",
    "New Kalalake",
    "Old Cabalan",
    "Pag-asa",
    "Santa Rita",
    "West Bajac-bajac",
    "West Tapinac",
  ],
};
