/** GENERATED — Region IV-A: 4019 barangays across 142 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "0401001000": [
    "Adia",
    "Bagong Sikat",
    "Balangon",
    "Bangin",
    "Banyaga",
    "Barigon",
    "Bilibinwang",
    "Coral Na Munti",
    "Guitna",
    "Mabini",
    "Pamiga",
    "Panhulan",
    "Pansipit",
    "Poblacion",
    "Pook",
    "San Jacinto",
    "San Teodoro",
    "Santa Cruz",
    "Santo Tomas",
    "Subic Ibaba",
    "Subic Ilaya",
  ],
  "0401002000": [
    "Balagbag",
    "Concepcion",
    "Concordia",
    "Dalipit East",
    "Dalipit West",
    "Dominador East",
    "Dominador West",
    "Munlawin Norte",
    "Munlawin Sur",
    "Muzon Primero",
    "Muzon Segundo",
    "Pinagkurusan",
    "Ping-As",
    "Poblacion East",
    "Poblacion West",
    "San Jose",
    "San Juan",
    "Santa Cruz",
    "Tadlac",
  ],
  "0401003000": [
    "Baclaran",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 12 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Calan",
    "Caloocan",
    "Calzada",
    "Canda",
    "Carenahan",
    "Caybunga",
    "Cayponce",
    "Dalig",
    "Dao",
    "Dilao",
    "Duhatan",
    "Durungao",
    "Gimalas",
    "Gumamela",
    "Lagnas",
    "Lanatan",
    "Langgangan",
    "Lucban Pook",
    "Lucban Putol",
    "Magabe",
    "Malalay",
    "Munting Tubig",
    "Navotas",
    "Palikpikan",
    "Patugo",
    "Pooc",
    "Sambat",
    "Sampaga",
    "San Juan",
    "San Piro",
    "Santol",
    "Sukol",
    "Tactac",
    "Taludtud",
    "Tanggoy",
  ],
  "0401004000": [
    "Alangilan",
    "Calawit",
    "Looc",
    "Magapi",
    "Makina",
    "Malabanan",
    "Paligawan",
    "Palsara",
    "Poblacion",
    "Sala",
    "Sampalocan",
    "San Sebastian",
    "Solis",
  ],
  "0401005000": [
    "Alangilan",
    "Balagtas",
    "Balete",
    "Banaba Center",
    "Banaba Ibaba",
    "Banaba Kanluran",
    "Banaba Silangan",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 12 (Pob.)",
    "Barangay 13 (Pob.)",
    "Barangay 14 (Pob.)",
    "Barangay 15 (Pob.)",
    "Barangay 16 (Pob.)",
    "Barangay 17 (Pob.)",
    "Barangay 18 (Pob.)",
    "Barangay 19 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 20 (Pob.)",
    "Barangay 21 (Pob.)",
    "Barangay 22 (Pob.)",
    "Barangay 23 (Pob.)",
    "Barangay 24 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Bilogo",
    "Bolbok",
    "Bukal",
    "Calicanto",
    "Catandala",
    "Concepcion",
    "Conde Itaas",
    "Conde Labak",
    "Cuta",
    "Dalig",
    "Dela Paz",
    "Dela Paz Pulot Aplaya",
    "Dela Paz Pulot Itaas",
    "Domoclay",
    "Dumantay",
    "Gulod Itaas",
    "Gulod Labak",
    "Haligue Kanluran",
    "Haligue Silangan",
    "Ilihan",
    "Kumba",
    "Kumintang Ibaba",
    "Kumintang Ilaya",
    "Libjo",
    "Liponpon, Isla Verde",
    "Maapas",
    "Mabacong",
    "Mahabang Dahilig",
    "Mahabang Parang",
    "Mahacot Kanluran",
    "Mahacot Silangan",
    "Malalim",
    "Malibayo",
    "Malitam",
    "Maruclap",
    "Pagkilatan",
    "Paharang Kanluran",
    "Paharang Silangan",
    "Pallocan Kanluran",
    "Pallocan Silangan",
    "Pinamucan",
    "Pinamucan Ibaba",
    "Pinamucan Silangan",
    "Sampaga",
    "San Agapito, Isla Verde",
    "San Agustin Kanluran, Isla Verde",
    "San Agustin Silangan, Isla Verde",
    "San Andres, Isla Verde",
    "San Antonio, Isla Verde",
    "San Isidro",
    "San Jose Sico",
    "San Miguel",
    "San Pedro",
    "Santa Clara",
    "Santa Rita Aplaya",
    "Santa Rita Karsada",
    "Santo Domingo",
    "Santo Niño",
    "Simlong",
    "Sirang Lupa",
    "Sorosoro Ibaba",
    "Sorosoro Ilaya",
    "Sorosoro Karsada",
    "Tabangao Ambulong",
    "Tabangao Aplaya",
    "Tabangao Dao",
    "Talahib Pandayan",
    "Talahib Payapa",
    "Talumpok Kanluran",
    "Talumpok Silangan",
    "Tinga Itaas",
    "Tinga Labak",
    "Tulo",
    "Wawa",
  ],
  "0401006000": [
    "Alagao",
    "Aplaya",
    "As-Is",
    "Bagong Silang",
    "Baguilawa",
    "Balayong",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Bolo",
    "Colvo",
    "Cupang",
    "Durungao",
    "Gulibay",
    "Inicbulan",
    "Locloc",
    "Magalang-Galang",
    "Malindig",
    "Manalupong",
    "Manghinao Proper",
    "Manghinao Uno",
    "New Danglayan",
    "Orense",
    "Pitugo",
    "Rizal",
    "Sampaguita",
    "San Agustin",
    "San Andres Proper",
    "San Andres Uno",
    "San Diego",
    "San Miguel",
    "San Pablo",
    "San Pedro",
    "San Roque",
    "San Teodoro",
    "San Vicente",
    "Santa Maria",
    "Santo Domingo",
    "Sinala",
  ],
  "0401007000": [
    "Baclas",
    "Bagong Tubig",
    "Balimbing",
    "Bambang",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Bisaya",
    "Cahil",
    "Calantas",
    "Caluangan",
    "Camastilisan",
    "Coral Ni Bacal",
    "Coral Ni Lopez",
    "Dacanlao",
    "Dila",
    "Loma",
    "Lumbang Calzada",
    "Lumbang Na Bata",
    "Lumbang Na Matanda",
    "Madalunot",
    "Makina",
    "Matipok",
    "Munting Coral",
    "Niyugan",
    "Pantay",
    "Puting Bato East",
    "Puting Bato West",
    "Puting Kahoy",
    "Quisumbing",
    "Salong",
    "San Rafael",
    "Sinisian",
    "Taklang Anak",
    "Talisay",
    "Tamayo",
    "Timbain",
  ],
  "0401008000": [
    "Bagong Silang",
    "Baha",
    "Balibago",
    "Balitoc",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Biga",
    "Bucal",
    "Carlosa",
    "Carretunan",
    "Encarnacion",
    "Gulod",
    "Hukay",
    "Lucsuhin",
    "Luya",
    "Paraiso",
    "Quilitisan",
    "Real",
    "Sambungan",
    "Santa Ana",
    "Talibayog",
    "Talisay",
    "Tanagan",
  ],
  "0401009000": [
    "Balagbag",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Bungahan",
    "Calumayin",
    "Dalipit East",
    "Dalipit West",
    "Dita",
    "Don Juan",
    "Emmanuel",
    "Ibabao",
    "Labac",
    "Pinagkaisahan",
    "San Felipe",
    "San Isidro",
  ],
  "0401010000": [
    "Bago",
    "Balanga",
    "Bungahan",
    "Calamias",
    "Catandala",
    "Coliat",
    "Dayapan",
    "Lapu-lapu",
    "Lucsuhin",
    "Mabalor",
    "Malainin",
    "Matala",
    "Munting-Tubig",
    "Palindan",
    "Pangao",
    "Panghayaan",
    "Poblacion",
    "Quilo",
    "Sabang",
    "Salaban I",
    "Salaban II",
    "San Agustin",
    "Sandalan",
    "Santo Niño",
    "Talaibon",
    "Tulay Na Patpat",
  ],
  "0401011000": [
    "As-Is",
    "Balakilong",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Berinayan",
    "Bugaan East",
    "Bugaan West",
    "Buso-buso",
    "Dayap Itaas",
    "Gulod",
    "J. Leviste",
    "Molinete",
    "Niyugan",
    "Paliparan",
    "San Gabriel",
    "San Gregorio",
    "Santa Maria",
    "Ticub",
  ],
  "0401012000": [
    "Anak-Dagat",
    "Arumahan",
    "Ayao-iyao",
    "Bagong Pook",
    "Bagong Sikat",
    "Balanga",
    "Bukal",
    "Cahilan I",
    "Cahilan II",
    "Dayapan",
    "District I (Pob.)",
    "District II (Pob.)",
    "District III (Pob.)",
    "District IV (Pob.)",
    "Dita",
    "Gulod",
    "Lucky",
    "Maguihan",
    "Mahabang Dahilig",
    "Mahayahay",
    "Maigsing Dahilig",
    "Maligaya",
    "Malinis",
    "Masalisi",
    "Mataas Na Bayan",
    "Matingain I",
    "Matingain II",
    "Mayasang",
    "Niugan",
    "Nonong Casto",
    "Palanas",
    "Payapa Ibaba",
    "Payapa Ilaya",
    "Rizal",
    "Sambal Ibaba",
    "Sambal Ilaya",
    "San Isidro Ibaba",
    "San Isidro Itaas",
    "Sangalang",
    "Sinisian East",
    "Sinisian West",
    "Talaga",
    "Tubigan",
    "Tubuan",
    "Wawa Ibaba",
    "Wawa Ilaya",
  ],
  "0401013000": [
    "Bagong Pook",
    "Balibago",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Binubusan",
    "Bungahan",
    "Cumba",
    "Humayingan",
    "Kapito",
    "Lumaniag",
    "Luyahan",
    "Malaruhatan",
    "Matabungkay",
    "Prenza",
    "Puting-Kahoy",
    "San Diego",
  ],
  "0401014000": [
    "Adya",
    "Anilao",
    "Anilao-Labac",
    "Antipolo Del Norte",
    "Antipolo Del Sur",
    "Bagong Pook",
    "Balintawak",
    "Banaybanay",
    "Barangay 12 (Pob.)",
    "Bolbok",
    "Bugtong na Pulo",
    "Bulacnin",
    "Bulaklakan",
    "Calamias",
    "Cumba",
    "Dagatan",
    "Duhatan",
    "Halang",
    "Inosloban",
    "Kayumanggi",
    "Latag",
    "Lodlod",
    "Lumbang",
    "Mabini",
    "Malagonlong",
    "Malitlit",
    "Marauoy",
    "Mataas Na Lupa",
    "Munting Pulo",
    "Pagolingin Bata",
    "Pagolingin East",
    "Pagolingin West",
    "Pangao",
    "Pinagkawitan",
    "Pinagtongulan",
    "Plaridel",
    "Poblacion Barangay 1",
    "Poblacion Barangay 10",
    "Poblacion Barangay 11",
    "Poblacion Barangay 2",
    "Poblacion Barangay 3",
    "Poblacion Barangay 4",
    "Poblacion Barangay 5",
    "Poblacion Barangay 6",
    "Poblacion Barangay 7",
    "Poblacion Barangay 8",
    "Poblacion Barangay 9",
    "Poblacion Barangay 9-A",
    "Pusil",
    "Quezon",
    "Rizal",
    "Sabang",
    "Sampaguita",
    "San Benito",
    "San Carlos",
    "San Celestino",
    "San Francisco",
    "San Guillermo",
    "San Jose",
    "San Lucas",
    "San Salvador",
    "San Sebastian",
    "Santo Niño",
    "Santo Toribio",
    "Sapac",
    "Sico",
    "Talisay",
    "Tambo",
    "Tangob",
    "Tanguay",
    "Tibig",
    "Tipacan",
  ],
  "0401015000": [
    "Apar",
    "Balatbat",
    "Balibago",
    "Banalo",
    "Biga",
    "Bignay",
    "Calo",
    "Calumpit",
    "Fabrica",
    "Jaybanga",
    "Lagadlarin",
    "Mabilog Na Bundok",
    "Malabrigo",
    "Malalim Na Sanog",
    "Malapad Na Parang",
    "Masaguitsit",
    "Nagtalongtong",
    "Nagtoctoc",
    "Olo-olo",
    "Pinaghawanan",
    "Poblacion",
    "San Miguel",
    "San Nicolas",
    "Sawang",
    "Soloc",
    "Tayuman",
  ],
  "0401016000": [
    "Anilao East",
    "Anilao Proper",
    "Bagalangit",
    "Bulacan",
    "Calamias",
    "Estrella",
    "Gasang",
    "Laurel",
    "Ligaya",
    "Mainaga",
    "Mainit",
    "Majuben",
    "Malimatoc I",
    "Malimatoc II",
    "Nag-Iba",
    "Pilahan",
    "Poblacion",
    "Pulang Lupa",
    "Pulong Anahao",
    "Pulong Balibaguhan",
    "Pulong Niogan",
    "Saguing",
    "Sampaguita",
    "San Francisco",
    "San Jose",
    "San Juan",
    "San Teodoro",
    "Santa Ana",
    "Santa Mesa",
    "Santo Niño",
    "Santo Tomas",
    "Solo",
    "Talaga East",
    "Talaga Proper",
  ],
  "0401017000": [
    "Bagong Pook",
    "Bilucao",
    "Bulihan",
    "Luta Del Norte",
    "Luta Del Sur",
    "Poblacion",
    "San Andres",
    "San Fernando",
    "San Gregorio",
    "San Isidro East",
    "San Juan",
    "San Pedro I",
    "San Pedro II",
    "San Pioquinto",
    "Santiago",
  ],
  "0401018000": [
    "Barangay II-A (Pob.)",
    "Bayorbor",
    "Bubuyan",
    "Calingatan",
    "District I (Pob.)",
    "District II (Pob.)",
    "District III (Pob.)",
    "District IV (Pob.)",
    "Kinalaglagan",
    "Loob",
    "Lumang Lipa",
    "Manggahan",
    "Nangkaan",
    "San Sebastian",
    "Santol",
    "Upa",
  ],
  "0401019000": [
    "Aga",
    "Balaytigui",
    "Banilad",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 12 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Bilaran",
    "Bucana",
    "Bulihan",
    "Bunducan",
    "Butucan",
    "Calayo",
    "Catandaan",
    "Cogunan",
    "Dayap",
    "Kaylaway",
    "Kayrilaw",
    "Latag",
    "Looc",
    "Lumbangan",
    "Malapad Na Bato",
    "Mataas Na Pulo",
    "Maugat",
    "Munting Indan",
    "Natipuan",
    "Pantalan",
    "Papaya",
    "Putat",
    "Reparo",
    "Talangan",
    "Tumalim",
    "Utod",
    "Wawa",
  ],
  "0401020000": [
    "Banaba",
    "Banaybanay",
    "Bawi",
    "Bukal",
    "Castillo",
    "Cawongan",
    "Manggas",
    "Maugat East",
    "Maugat West",
    "Pansol",
    "Payapa",
    "Poblacion",
    "Quilo-quilo North",
    "Quilo-quilo South",
    "San Felipe",
    "San Miguel",
    "Tamak",
    "Tangob",
  ],
  "0401021000": [
    "Alupay",
    "Antipolo",
    "Bagong Pook",
    "Balibago",
    "Barangay A (Pob.)",
    "Barangay B (Pob.)",
    "Barangay C (Pob.)",
    "Barangay D (Pob.)",
    "Barangay E (Pob.)",
    "Bayawang",
    "Baybayin",
    "Bulihan",
    "Cahigam",
    "Calantas",
    "Colongan",
    "Itlugan",
    "Leviste",
    "Lumbangan",
    "Maalas-As",
    "Mabato",
    "Mabunga",
    "Macalamcam A",
    "Macalamcam B",
    "Malaya",
    "Maligaya",
    "Marilag",
    "Masaya",
    "Matamis",
    "Mavalor",
    "Mayuro",
    "Namuco",
    "Namunga",
    "Nasi",
    "Natu",
    "Palakpak",
    "Pinagsibaan",
    "Putingkahoy",
    "Quilib",
    "Salao",
    "San Carlos",
    "San Ignacio",
    "San Isidro",
    "San Jose",
    "San Roque",
    "Santa Cruz",
    "Timbugan",
    "Tiquiwan",
    "Tulos",
  ],
  "0401022000": [
    "Aguila",
    "Anus",
    "Aya",
    "Bagong Pook",
    "Balagtasin",
    "Balagtasin I",
    "Banaybanay I",
    "Banaybanay II",
    "Bigain I",
    "Bigain II",
    "Bigain South",
    "Calansayan",
    "Dagatan",
    "Don Luis",
    "Galamay-Amo",
    "Lalayat",
    "Lapolapo I",
    "Lapolapo II",
    "Lepute",
    "Lumil",
    "Mojon-Tampoy",
    "Natunuan",
    "Palanca",
    "Pinagtung-Ulan",
    "Poblacion Barangay I",
    "Poblacion Barangay II",
    "Poblacion Barangay III",
    "Poblacion Barangay IV",
    "Sabang",
    "Salaban",
    "Santo Cristo",
    "Taysan",
    "Tugtug",
  ],
  "0401023000": [
    "Abung",
    "Balagbag",
    "Barualte",
    "Bataan",
    "Buhay Na Sapa",
    "Bulsa",
    "Calicanto",
    "Calitcalit",
    "Calubcub I",
    "Calubcub II",
    "Catmon",
    "Coloconto",
    "Escribano",
    "Hugom",
    "Imelda",
    "Janaojanao",
    "Laiya-Aplaya",
    "Laiya-Ibabao",
    "Libato",
    "Lipahan",
    "Mabalanoy",
    "Maraykit",
    "Muzon",
    "Nagsaulay",
    "Palahanan I",
    "Palahanan II",
    "Palingowak",
    "Pinagbayanan",
    "Poblacion",
    "Poctol",
    "Pulangbato",
    "Putingbuhangin",
    "Quipot",
    "Sampiro",
    "Sapangan",
    "Sico I",
    "Sico II",
    "Subukin",
    "Talahiban I",
    "Talahiban II",
    "Ticalan",
    "Tipaz",
  ],
  "0401024000": [
    "Abiacao",
    "Bagong Tubig",
    "Balagtasin",
    "Balite",
    "Banoyo",
    "Boboy",
    "Bonliw",
    "Calumpang East",
    "Calumpang West",
    "Dulangan",
    "Durungao",
    "Locloc",
    "Luya",
    "Mahabang Parang",
    "Manggahan",
    "Muzon",
    "Poblacion",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Martin",
    "Santa Monica",
    "Taliba",
    "Talon",
    "Tejero",
    "Tungal",
  ],
  "0401025000": [
    "Abelo",
    "Alas-as",
    "Balete",
    "Baluk-baluk",
    "Bancoro",
    "Bangin",
    "Calangay",
    "Hipit",
    "Maabud North",
    "Maabud South",
    "Munlawin",
    "Pansipit",
    "Poblacion",
    "Pulang-Bato",
    "Santo Niño",
    "Sinturisan",
    "Tagudtod",
    "Talang",
  ],
  "0401026000": [
    "Alalum",
    "Antipolo",
    "Balimbing",
    "Banaba",
    "Bayanan",
    "Danglayan",
    "Del Pilar",
    "Gelerang Kawayan",
    "Ilat North",
    "Ilat South",
    "Kaingin",
    "Laurel",
    "Malaking Pook",
    "Mataas Na Lupa",
    "Natunuan North",
    "Natunuan South",
    "Padre Castillo",
    "Palsahingin",
    "Pila",
    "Poblacion",
    "Pook Ni Banal",
    "Pook Ni Kapitan",
    "Resplandor",
    "Sambat",
    "San Antonio",
    "San Mariano",
    "San Mateo",
    "Santa Elena",
    "Santo Niño",
  ],
  "0401027000": [
    "Antipolo",
    "Bihis",
    "Burol",
    "Calayaan",
    "Calumala",
    "Cuta East",
    "Cutang Cawayan",
    "Irukan",
    "Pacifico",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Saimsim",
    "Sampa",
    "Sinipian",
    "Tambo Ibaba",
    "Tambo Ilaya",
  ],
  "0401028000": [
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "San Agustin",
    "San Antonio",
    "San Bartolome",
    "San Felix",
    "San Fernando",
    "San Francisco",
    "San Isidro Norte",
    "San Isidro Sur",
    "San Joaquin",
    "San Jose",
    "San Juan",
    "San Luis",
    "San Miguel",
    "San Pablo",
    "San Pedro",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santa Ana",
    "Santa Anastacia",
    "Santa Clara",
    "Santa Cruz",
    "Santa Elena",
    "Santa Maria",
    "Santa Teresita",
    "Santiago",
  ],
  "0401029000": [
    "Apacay",
    "Balisong",
    "Bihis",
    "Bolbok",
    "Buli",
    "Butong",
    "Carasuche",
    "Cawit",
    "Caysasay",
    "Cubamba",
    "Cultihan",
    "Gahol",
    "Halang",
    "Iba",
    "Ilog",
    "Imamawo",
    "Ipil",
    "Laguile",
    "Latag",
    "Luntal",
    "Mahabang Lodlod",
    "Niogan",
    "Pansol",
    "Poblacion 1",
    "Poblacion 10",
    "Poblacion 11",
    "Poblacion 12",
    "Poblacion 13",
    "Poblacion 14",
    "Poblacion 2",
    "Poblacion 3",
    "Poblacion 4",
    "Poblacion 5",
    "Poblacion 6",
    "Poblacion 7",
    "Poblacion 8",
    "Poblacion 9",
    "Pook",
    "Seiran",
    "Tatlong Maria",
    "Tierra Alta",
    "Tulo",
  ],
  "0401030000": [
    "Aya",
    "Balas",
    "Banga",
    "Buco",
    "Caloocan",
    "Leynes",
    "Miranda",
    "Poblacion Barangay 1",
    "Poblacion Barangay 2",
    "Poblacion Barangay 3",
    "Poblacion Barangay 4",
    "Poblacion Barangay 5",
    "Poblacion Barangay 6",
    "Poblacion Barangay 7",
    "Poblacion Barangay 8",
    "Quiling",
    "Sampaloc",
    "San Guillermo",
    "Santa Maria",
    "Tranca",
    "Tumaway",
  ],
  "0401031000": [
    "Altura Bata",
    "Altura Matanda",
    "Altura-South",
    "Ambulong",
    "Bagbag",
    "Bagumbayan",
    "Balele",
    "Banadero",
    "Banjo East",
    "Banjo Laurel",
    "Bilog-bilog",
    "Boot",
    "Cale",
    "Darasa",
    "Gonzales",
    "Hidalgo",
    "Janopol",
    "Janopol Oriental",
    "Laurel",
    "Luyos",
    "Mabini",
    "Malaking Pulo",
    "Maria Paz",
    "Maugat",
    "Montaña",
    "Natatas",
    "Pagaspas",
    "Pantay Bata",
    "Pantay Matanda",
    "Poblacion Barangay 1",
    "Poblacion Barangay 2",
    "Poblacion Barangay 3",
    "Poblacion Barangay 4",
    "Poblacion Barangay 5",
    "Poblacion Barangay 6",
    "Poblacion Barangay 7",
    "Sala",
    "Sambat",
    "San Jose",
    "Santol",
    "Santor",
    "Sulpoc",
    "Suplang",
    "Talaga",
    "Tinurik",
    "Trapiche",
    "Ulango",
    "Wawa",
  ],
  "0401032000": [
    "Bacao",
    "Bilogo",
    "Bukal",
    "Dagatan",
    "Guinhawa",
    "Laurel",
    "Mabayabas",
    "Mahanadiong",
    "Mapulo",
    "Mataas Na Lupa",
    "Pag-Asa",
    "Panghayaan",
    "Piña",
    "Pinagbayanan",
    "Poblacion East",
    "Poblacion West",
    "San Isidro",
    "San Marcelino",
    "Santo Niño",
    "Tilambo",
  ],
  "0401033000": [
    "Barangay 13",
    "Barangay 14",
    "Barangay 15",
    "Corona",
    "Gamao",
    "Makawayan",
    "Marikaban",
    "Papaya",
    "Pisa",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Pedro",
    "Santo Tomas",
    "Talahib",
  ],
  "0401034000": [
    "Acle",
    "Bayudbud",
    "Bolboc",
    "Burgos (Pob.)",
    "Dalima",
    "Dao",
    "Guinhawa",
    "Lumbangan",
    "Luna (Pob.)",
    "Luntal",
    "Magahis",
    "Malibu",
    "Mataywanac",
    "Palincaro",
    "Putol",
    "Rillo (Pob.)",
    "Rizal (Pob.)",
    "Sabang",
    "San Jose",
    "Talon",
    "Toong",
    "Tuyon-tuyon",
  ],
  "0402101000": [
    "Amuyong",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Bilog",
    "Buck Estate",
    "Esperanza Ibaba",
    "Esperanza Ilaya",
    "Kaysuyo",
    "Kaytitinga I",
    "Kaytitinga II",
    "Kaytitinga III",
    "Luksuhin",
    "Luksuhin Ilaya",
    "Mangas I",
    "Mangas II",
    "Marahan I",
    "Marahan II",
    "Matagbak I",
    "Matagbak II",
    "Pajo",
    "Palumlum",
    "Santa Teresa",
    "Sikat",
    "Sinaliw Malaki",
    "Sinaliw na Munti",
    "Sulsugin",
    "Taywanak Ibaba",
    "Taywanak Ilaya",
    "Upli",
  ],
  "0402102000": [
    "Banaybanay",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay IX (Pob.)",
    "Barangay V (Pob.)",
    "Barangay VI (Pob.)",
    "Barangay VII (Pob.)",
    "Barangay VIII (Pob.)",
    "Barangay X (Pob.)",
    "Barangay XI (Pob.)",
    "Barangay XII (Pob.)",
    "Bucal",
    "Buho",
    "Dagatan",
    "Halang",
    "Loma",
    "Maitim I",
    "Maymangga",
    "Minantok Kanluran",
    "Minantok Silangan",
    "Pangil",
    "Salaban",
    "Talon",
    "Tamacan",
  ],
  "0402103000": [
    "Alima",
    "Aniban I",
    "Aniban II",
    "Aniban III",
    "Aniban IV",
    "Aniban V",
    "Banalo",
    "Bayanan",
    "Campo Santo",
    "Daang Bukid",
    "Digman",
    "Dulong Bayan",
    "Habay I",
    "Habay II",
    "Kaingin (Pob.)",
    "Ligas I",
    "Ligas II",
    "Ligas III",
    "Mabolo I",
    "Mabolo II",
    "Mabolo III",
    "Maliksi I",
    "Maliksi II",
    "Maliksi III",
    "Mambog I",
    "Mambog II",
    "Mambog III",
    "Mambog IV",
    "Mambog V",
    "Molino I",
    "Molino II",
    "Molino III",
    "Molino IV",
    "Molino V",
    "Molino VI",
    "Molino VII",
    "Niog I",
    "Niog II",
    "Niog III",
    "P.F. Espiritu I",
    "P.F. Espiritu II",
    "P.F. Espiritu III",
    "P.F. Espiritu IV",
    "P.F. Espiritu V",
    "P.F. Espiritu VI",
    "P.F. Espiritu VII",
    "P.F. Espiritu VIII",
    "Queens Row Central",
    "Queens Row East",
    "Queens Row West",
    "Real I",
    "Real II",
    "Salinas I",
    "Salinas II",
    "Salinas III",
    "Salinas IV",
    "San Nicolas I",
    "San Nicolas II",
    "San Nicolas III",
    "Sineguelasan",
    "Tabing Dagat",
    "Talaba I",
    "Talaba II",
    "Talaba III",
    "Talaba IV",
    "Talaba V",
    "Talaba VI",
    "Talaba VII",
    "Zapote I",
    "Zapote II",
    "Zapote III",
    "Zapote IV",
    "Zapote V",
  ],
  "0402104000": [
    "Bancal",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Cabilang Baybay",
    "Lantic",
    "Mabuhay",
    "Maduya",
    "Milagrosa",
  ],
  "0402105000": [
    "Barangay 1",
    "Barangay 10",
    "Barangay 10-A",
    "Barangay 10-B",
    "Barangay 11",
    "Barangay 12",
    "Barangay 13",
    "Barangay 14",
    "Barangay 15",
    "Barangay 16",
    "Barangay 17",
    "Barangay 18",
    "Barangay 19",
    "Barangay 2",
    "Barangay 20",
    "Barangay 21",
    "Barangay 22",
    "Barangay 22-A",
    "Barangay 23",
    "Barangay 24",
    "Barangay 25",
    "Barangay 26",
    "Barangay 27",
    "Barangay 28",
    "Barangay 29",
    "Barangay 29-A",
    "Barangay 3",
    "Barangay 30",
    "Barangay 31",
    "Barangay 32",
    "Barangay 33",
    "Barangay 34",
    "Barangay 35",
    "Barangay 36",
    "Barangay 36-A",
    "Barangay 37",
    "Barangay 37-A",
    "Barangay 38",
    "Barangay 38-A",
    "Barangay 39",
    "Barangay 4",
    "Barangay 40",
    "Barangay 41",
    "Barangay 42",
    "Barangay 42-A",
    "Barangay 42-B",
    "Barangay 42-C",
    "Barangay 43",
    "Barangay 44",
    "Barangay 45",
    "Barangay 45-A",
    "Barangay 46",
    "Barangay 47",
    "Barangay 47-A",
    "Barangay 47-B",
    "Barangay 48",
    "Barangay 48-A",
    "Barangay 49",
    "Barangay 49-A",
    "Barangay 5",
    "Barangay 50",
    "Barangay 51",
    "Barangay 52",
    "Barangay 53",
    "Barangay 53-A",
    "Barangay 53-B",
    "Barangay 54",
    "Barangay 54-A",
    "Barangay 55",
    "Barangay 56",
    "Barangay 57",
    "Barangay 58",
    "Barangay 58-A",
    "Barangay 59",
    "Barangay 6",
    "Barangay 60",
    "Barangay 61",
    "Barangay 61-A",
    "Barangay 62",
    "Barangay 62-A",
    "Barangay 62-B",
    "Barangay 7",
    "Barangay 8",
    "Barangay 9",
  ],
  "0402106000": [
    "Burol",
    "Burol I",
    "Burol II",
    "Burol III",
    "Datu Esmael",
    "Emmanuel Bergado I",
    "Emmanuel Bergado II",
    "Fatima I",
    "Fatima II",
    "Fatima III",
    "H-2",
    "Langkaan I",
    "Langkaan II",
    "Luzviminda I",
    "Luzviminda II",
    "Paliparan I",
    "Paliparan II",
    "Paliparan III",
    "Sabang",
    "Saint Peter I",
    "Saint Peter II",
    "Salawag",
    "Salitran I",
    "Salitran II",
    "Salitran III",
    "Salitran IV",
    "Sampaloc I",
    "Sampaloc II",
    "Sampaloc III",
    "Sampaloc IV",
    "Sampaloc V",
    "San Agustin I",
    "San Agustin II",
    "San Agustin III",
    "San Andres I",
    "San Andres II",
    "San Antonio De Padua I",
    "San Antonio De Padua II",
    "San Dionisio",
    "San Esteban",
    "San Francisco I",
    "San Francisco II",
    "San Isidro Labrador I",
    "San Isidro Labrador II",
    "San Jose",
    "San Juan",
    "San Lorenzo Ruiz I",
    "San Lorenzo Ruiz II",
    "San Luis I",
    "San Luis II",
    "San Manuel I",
    "San Manuel II",
    "San Mateo",
    "San Miguel",
    "San Miguel II",
    "San Nicolas I",
    "San Nicolas II",
    "San Roque",
    "San Simon",
    "Santa Cristina I",
    "Santa Cristina II",
    "Santa Cruz I",
    "Santa Cruz II",
    "Santa Fe",
    "Santa Lucia",
    "Santa Maria",
    "Santo Cristo",
    "Santo Niño I",
    "Santo Niño II",
    "Victoria Reyes",
    "Zone I (Pob.)",
    "Zone I-B",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)",
  ],
  "0402107000": [
    "A. Dalusag",
    "Batas Dao",
    "Castaños Cerca",
    "Castaños Lejos",
    "Kabulusan",
    "Kaymisas",
    "Kaypaaba",
    "Lumipa",
    "Narvaez",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Tabora",
  ],
  "0402108000": [
    "Alingaro",
    "Arnaldo Pob.",
    "Bacao I",
    "Bacao II",
    "Bagumbayan Pob.",
    "Biclatan",
    "Buenavista I",
    "Buenavista II",
    "Buenavista III",
    "Corregidor Pob.",
    "Dulong Bayan Pob.",
    "Gov. Ferrer Pob.",
    "Javalera",
    "Manggahan",
    "Navarro",
    "Ninety Sixth Pob.",
    "Panungyanan",
    "Pasong Camachile I",
    "Pasong Camachile II",
    "Pasong Kawayan I",
    "Pasong Kawayan II",
    "Pinagtipunan",
    "Prinza Pob.",
    "Sampalucan Pob.",
    "San Francisco",
    "San Gabriel Pob.",
    "San Juan I",
    "San Juan II",
    "Santa Clara",
    "Santiago",
    "Tapia",
    "Tejero",
    "Vibora Pob.",
  ],
  "0402109000": [
    "Alapan I-A",
    "Alapan I-B",
    "Alapan I-C",
    "Alapan II-A",
    "Alapan II-B",
    "Anabu I-A",
    "Anabu I-B",
    "Anabu I-C",
    "Anabu I-D",
    "Anabu I-E",
    "Anabu I-F",
    "Anabu I-G",
    "Anabu II-A",
    "Anabu II-B",
    "Anabu II-C",
    "Anabu II-D",
    "Anabu II-E",
    "Anabu II-F",
    "Bagong Silang",
    "Bayan Luma I",
    "Bayan Luma II",
    "Bayan Luma III",
    "Bayan Luma IV",
    "Bayan Luma IX",
    "Bayan Luma V",
    "Bayan Luma VI",
    "Bayan Luma VII",
    "Bayan Luma VIII",
    "Bucandala I",
    "Bucandala II",
    "Bucandala III",
    "Bucandala IV",
    "Bucandala V",
    "Buhay na Tubig",
    "Carsadang Bago I",
    "Carsadang Bago II",
    "Magdalo",
    "Maharlika",
    "Malagasang I-A",
    "Malagasang I-B",
    "Malagasang I-C",
    "Malagasang I-D",
    "Malagasang I-E",
    "Malagasang I-F",
    "Malagasang I-G",
    "Malagasang II-A",
    "Malagasang II-B",
    "Malagasang II-C",
    "Malagasang II-D",
    "Malagasang II-E",
    "Malagasang II-F",
    "Malagasang II-G",
    "Mariano Espeleta I",
    "Mariano Espeleta II",
    "Mariano Espeleta III",
    "Medicion I-A",
    "Medicion I-B",
    "Medicion I-C",
    "Medicion I-D",
    "Medicion II-A",
    "Medicion II-B",
    "Medicion II-C",
    "Medicion II-D",
    "Medicion II-E",
    "Medicion II-F",
    "Pag-Asa I",
    "Pag-Asa II",
    "Pag-Asa III",
    "Palico I",
    "Palico II",
    "Palico III",
    "Palico IV",
    "Pasong Buaya I",
    "Pasong Buaya II",
    "Pinagbuklod",
    "Poblacion I-A (Pob.)",
    "Poblacion I-B",
    "Poblacion I-C",
    "Poblacion II-A (Pob.)",
    "Poblacion II-B",
    "Poblacion III-A (Pob.)",
    "Poblacion III-B",
    "Poblacion IV-A (Pob.)",
    "Poblacion IV-B",
    "Poblacion IV-C",
    "Poblacion IV-D",
    "Tanzang Luma I",
    "Tanzang Luma II",
    "Tanzang Luma III",
    "Tanzang Luma IV",
    "Tanzang Luma V",
    "Tanzang Luma VI",
    "Toclong I-A",
    "Toclong I-B",
    "Toclong I-C",
    "Toclong II-A",
    "Toclong II-B",
  ],
  "0402110000": [
    "Agus-us",
    "Alulod",
    "Banaba Cerca",
    "Banaba Lejos",
    "Bancod",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Buna Cerca",
    "Buna Lejos I",
    "Buna Lejos II",
    "Calumpang Cerca",
    "Calumpang Lejos I",
    "Carasuchi",
    "Daine I",
    "Daine II",
    "Guyam Malaki",
    "Guyam Munti",
    "Harasan",
    "Kayquit I",
    "Kayquit II",
    "Kayquit III",
    "Kaytambog",
    "Kaytapos",
    "Limbon",
    "Lumampong Balagbag",
    "Lumampong Halayhay",
    "Mahabangkahoy Cerca",
    "Mahabangkahoy Lejos",
    "Mataas na Lupa",
    "Pulo",
    "Tambo Balagbag",
    "Tambo Ilaya",
    "Tambo Kulit",
    "Tambo Malaki",
  ],
  "0402111000": [
    "Balsahan-Bisita",
    "Batong Dalig",
    "Binakayan-Aplaya",
    "Binakayan-Kanluran",
    "Congbalay-Legaspi",
    "Gahak",
    "Kaingen",
    "Magdalo",
    "Manggahan-Lawin",
    "Marulas",
    "Panamitan",
    "Poblacion",
    "Pulvorista",
    "Samala-Marquez",
    "San Sebastian",
    "Santa Isabel",
    "Tabon I",
    "Tabon II",
    "Tabon III",
    "Toclong",
    "Tramo-Bantayan",
    "Wakas I",
    "Wakas II",
  ],
  "0402112000": [
    "Baliwag",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Bendita I",
    "Bendita II",
    "Caluangan",
    "Kabulusan",
    "Medina",
    "Pacheco",
    "Ramirez",
    "San Agustin",
    "Tua",
    "Urdaneta",
  ],
  "0402113000": [
    "Bucal I",
    "Bucal II",
    "Bucal III A",
    "Bucal III B",
    "Bucal IV A",
    "Bucal IV B",
    "Caingin Pob.",
    "Garita I A",
    "Garita I B",
    "Layong Mabilog",
    "Mabato",
    "Pantihan I",
    "Pantihan II",
    "Pantihan III",
    "Pantihan IV",
    "Patungan",
    "Pinagsanhan I A",
    "Pinagsanhan I B",
    "Poblacion I A",
    "Poblacion I B",
    "Poblacion II A",
    "Poblacion II B",
    "San Miguel I A",
    "San Miguel I B",
    "Talipusngo",
    "Tulay Kanluran",
    "Tulay Silangan",
  ],
  "0402114000": [
    "Anuling Cerca I",
    "Anuling Cerca II",
    "Anuling Lejos I",
    "Anuling Lejos II",
    "Asis I",
    "Asis II",
    "Asis III",
    "Banayad",
    "Bukal",
    "Galicia I",
    "Galicia II",
    "Galicia III",
    "Miguel Mojica",
    "Palocpoc I",
    "Palocpoc II",
    "Panungyan I",
    "Panungyan II",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Poblacion V",
    "Poblacion VI",
    "Poblacion VII",
  ],
  "0402115000": [
    "Bagong Karsada",
    "Balsahan",
    "Bancaan",
    "Bucana Malaki",
    "Bucana Sasahan",
    "Calubcob",
    "Capt. C. Nazareno (Pob.)",
    "Gomez-Zamora (Pob.)",
    "Halang",
    "Humbac",
    "Ibayo Estacion",
    "Ibayo Silangan",
    "Kanluran",
    "Labac",
    "Latoria",
    "Mabolo",
    "Makina",
    "Malainen Bago",
    "Malainen Luma",
    "Molino",
    "Munting Mapino",
    "Muzon",
    "Palangue 1",
    "Palangue 2 & 3",
    "Sabang",
    "San Roque",
    "Santulan",
    "Sapa",
    "Timalan Balsahan",
    "Timalan Concepcion",
  ],
  "0402116000": [
    "Magdiwang",
    "Poblacion",
    "Salcedo I",
    "Salcedo II",
    "San Antonio I",
    "San Antonio II",
    "San Jose I",
    "San Jose II",
    "San Juan I",
    "San Juan II",
    "San Rafael I",
    "San Rafael II",
    "San Rafael III",
    "San Rafael IV",
    "Santa Rosa I",
    "Santa Rosa II",
  ],
  "0402117000": [
    "Bagbag I",
    "Bagbag II",
    "Kanluran",
    "Ligtong I",
    "Ligtong II",
    "Ligtong III",
    "Ligtong IV",
    "Muzon I",
    "Muzon II",
    "Poblacion",
    "Sapa I",
    "Sapa II",
    "Sapa III",
    "Sapa IV",
    "Silangan I",
    "Silangan II",
    "Tejeros Convention",
    "Wawa I",
    "Wawa II",
    "Wawa III",
  ],
  "0402118000": [
    "Acacia",
    "Adlas",
    "Anahaw I",
    "Anahaw II",
    "Balite I",
    "Balite II",
    "Balubad",
    "Banaba",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Batas",
    "Biga I",
    "Biga II",
    "Biluso",
    "Bucal",
    "Buho",
    "Bulihan",
    "Cabangaan",
    "Carmen",
    "Hoyo",
    "Hukay",
    "Iba",
    "Inchican",
    "Ipil I",
    "Ipil II",
    "Kalubkob",
    "Kaong",
    "Lalaan I",
    "Lalaan II",
    "Litlit",
    "Lucsuhin",
    "Lumil",
    "Maguyam",
    "Malabag",
    "Malaking Tatyao",
    "Mataas Na Burol",
    "Munting Ilog",
    "Narra I",
    "Narra II",
    "Narra III",
    "Paligawan",
    "Pasong Langka",
    "Pooc I",
    "Pooc II",
    "Pulong Bunga",
    "Pulong Saging",
    "Puting Kahoy",
    "Sabutan",
    "San Miguel I",
    "San Miguel II",
    "San Vicente I",
    "San Vicente II",
    "Santol",
    "Tartaria",
    "Tibig",
    "Toledo",
    "Tubuan I",
    "Tubuan II",
    "Tubuan III",
    "Ulat",
    "Yakal",
  ],
  "0402119000": [
    "Asisan",
    "Bagong Tubig",
    "Calabuso",
    "Dapdap East",
    "Dapdap West",
    "Francisco",
    "Guinhawa North",
    "Guinhawa South",
    "Iruhin East",
    "Iruhin South",
    "Iruhin West",
    "Kaybagal East",
    "Kaybagal North",
    "Kaybagal South (Pob.)",
    "Mag-Asawang Ilat",
    "Maharlika East",
    "Maharlika West",
    "Maitim 2nd Central",
    "Maitim 2nd East",
    "Maitim 2nd West",
    "Mendez Crossing East",
    "Mendez Crossing West",
    "Neogan",
    "Patutong Malaki North",
    "Patutong Malaki South",
    "Sambong",
    "San Jose",
    "Silang Junction North",
    "Silang Junction South",
    "Sungay North",
    "Sungay South",
    "Tolentino East",
    "Tolentino West",
    "Zambal",
  ],
  "0402120000": [
    "Amaya I",
    "Amaya II",
    "Amaya III",
    "Amaya IV",
    "Amaya V",
    "Amaya VI",
    "Amaya VII",
    "Bagtas",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Biga",
    "Biwas",
    "Bucal",
    "Bunga",
    "Calibuyo",
    "Capipisa",
    "Daang Amaya I",
    "Daang Amaya II",
    "Daang Amaya III",
    "Halayhay",
    "Julugan I",
    "Julugan II",
    "Julugan III",
    "Julugan IV",
    "Julugan V",
    "Julugan VI",
    "Julugan VII",
    "Julugan VIII",
    "Lambingan",
    "Mulawin",
    "Paradahan I",
    "Paradahan II",
    "Punta I",
    "Punta II",
    "Sahud Ulan",
    "Sanja Mayor",
    "Santol",
    "Tanauan",
    "Tres Cruses",
  ],
  "0402121000": [
    "Bucana",
    "Poblacion I",
    "Poblacion I A",
    "Poblacion II",
    "Poblacion III",
    "San Jose",
    "San Juan I",
    "San Juan II",
    "Sapang I",
    "Sapang II",
  ],
  "0402122000": [
    "Aguado",
    "Cabezas",
    "Cabuco",
    "Conchu",
    "De Ocampo",
    "Gregorio",
    "Inocencio",
    "Lallana",
    "Lapidario",
    "Luciano",
    "Osorio",
    "Perez",
    "San Agustin (Pob.)",
  ],
  "0402123000": [
    "Aldiano Olaes",
    "Barangay 1 Poblacion",
    "Barangay 2 Poblacion",
    "Barangay 3 Poblacion",
    "Barangay 4 Poblacion",
    "Barangay 5 Poblacion",
    "Benjamin Tirona",
    "Bernardo Pulido",
    "Epifanio Malia",
    "Fiorello Calimag",
    "Francisco De Castro",
    "Francisco Reyes",
    "Gavino Maderan",
    "Gregoria De Jesus",
    "Inocencio Salud",
    "Jacinto Lumbreras",
    "Kapitan Kua",
    "Koronel Jose P. Elises",
    "Macario Dacon",
    "Marcelino Memije",
    "Nicolasa Virata",
    "Pantaleon Granados",
    "Ramon Cruz",
    "San Gabriel",
    "San Jose",
    "Severino De Las Alas",
    "Tiniente Tiago",
  ],
  "0403401000": [
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Del Carmen",
    "Palma",
    "San Agustin",
    "San Andres",
    "San Benito",
    "San Gregorio",
    "San Ildefonso",
    "San Juan",
    "San Miguel",
    "San Roque",
    "Santa Rosa",
  ],
  "0403402000": [
    "Bitin",
    "Calo",
    "Dila",
    "Maitim",
    "Masaya",
    "Paciano Rizal",
    "Puypuy",
    "San Agustin (Pob.)",
    "San Antonio",
    "San Isidro",
    "San Nicolas (Pob.)",
    "Santa Cruz",
    "Santo Domingo",
    "Tagumpay",
    "Tranca",
  ],
  "0403403000": [
    "Biñan",
    "Bungahan",
    "Canlalay",
    "Casile",
    "De La Paz",
    "Ganado",
    "Langkiwa",
    "Loma",
    "Malaban",
    "Malamig",
    "Mampalasan",
    "Platero",
    "Poblacion",
    "San Antonio",
    "San Francisco",
    "San Jose",
    "San Vicente",
    "Santo Domingo",
    "Santo Niño",
    "Santo Tomas",
    "Soro-soro",
    "Timbao",
    "Tubigan",
    "Zapote",
  ],
  "0403404000": [
    "Baclaran",
    "Banaybanay",
    "Banlic",
    "Barangay Dos (Pob.)",
    "Barangay Tres (Pob.)",
    "Barangay Uno (Pob.)",
    "Bigaa",
    "Butong",
    "Casile",
    "Diezmo",
    "Gulod",
    "Mamatid",
    "Marinig",
    "Niugan",
    "Pittland",
    "Pulo",
    "Sala",
    "San Isidro",
  ],
  "0403405000": [
    "Bagong Kalsada",
    "Banadero",
    "Banlic",
    "Barandal",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Batino",
    "Bubuyan",
    "Bucal",
    "Bunggo",
    "Burol",
    "Camaligan",
    "Canlubang",
    "Halang",
    "Hornalan",
    "Kay-Anlog",
    "La Mesa",
    "Laguerta",
    "Lawa",
    "Lecheria",
    "Lingga",
    "Looc",
    "Mabato",
    "Majada Labas",
    "Makiling",
    "Mapagong",
    "Masili",
    "Maunong",
    "Mayapa",
    "Milagrosa",
    "Paciano Rizal",
    "Palingon",
    "Palo-Alto",
    "Pansol",
    "Parian",
    "Prinza",
    "Punta",
    "Puting Lupa",
    "Real",
    "Saimsim",
    "Sampiruhan",
    "San Cristobal",
    "San Jose",
    "San Juan",
    "Sirang Lupa",
    "Sucol",
    "Turbina",
    "Ulango",
    "Uwisan",
  ],
  "0403406000": [
    "Balayhangin",
    "Bangyas",
    "Dayap",
    "Hanggan",
    "Imok",
    "Kanluran (Pob.)",
    "Lamot 1",
    "Lamot 2",
    "Limao",
    "Mabacan",
    "Masiit",
    "Paliparan",
    "Perez",
    "Prinza",
    "San Isidro",
    "Santo Tomas",
    "Silangan (Pob.)",
  ],
  "0403407000": [
    "Anglas",
    "Bangco",
    "Bukal",
    "Bulajo",
    "Cansuso",
    "Duhat",
    "Inao-Awan",
    "Kanluran Talaongan",
    "Labayo",
    "Layasin",
    "Layug",
    "Mahipon",
    "Paowin",
    "Poblacion",
    "Silangan Talaongan",
    "Sisilmin",
    "Sumucab",
    "Tibatib",
    "Udia",
  ],
  "0403408000": [
    "Asana (Pob.)",
    "Bacong-Sigsigan",
    "Bagong Pag-Asa (Pob.)",
    "Balitoc",
    "Banaba (Pob.)",
    "Batuhan",
    "Bulihan",
    "Caballero (Pob.)",
    "Calumpang (Pob.)",
    "Cuebang Bato",
    "Damayan (Pob.)",
    "Kapatalan",
    "Kataypuanan",
    "Liyang",
    "Maate",
    "Magdalo (Pob.)",
    "Mayatba",
    "Minayutan",
    "Salangbato",
    "Tunhac",
  ],
  "0403409000": ["Longos", "San Antonio", "San Juan (Pob.)"],
  "0403410000": [
    "Bagong Anyo (Pob.)",
    "Bayate",
    "Bongkol",
    "Bubukal",
    "Cabuyew",
    "Calumpang",
    "Culoy",
    "Dagatan",
    "Daniw",
    "Dita",
    "Ibabang Palina",
    "Ibabang San Roque",
    "Ibabang Sungi",
    "Ibabang Taykin",
    "Ilayang Palina",
    "Ilayang San Roque",
    "Ilayang Sungi",
    "Ilayang Taykin",
    "Kanlurang Bukal",
    "Laguan",
    "Luquin",
    "Malabo-Kalantukan",
    "Masikap (Pob.)",
    "Maslun (Pob.)",
    "Mojon",
    "Novaliches",
    "Oples",
    "Pag-Asa (Pob.)",
    "Palayan",
    "Rizal (Pob.)",
    "San Isidro",
    "Silangang Bukal",
    "Tuy-Baanan",
  ],
  "0403411000": [
    "Anos",
    "Bagong Silang",
    "Bambang",
    "Batong Malake",
    "Baybayin (Pob.)",
    "Bayog",
    "Lalakay",
    "Maahas",
    "Malinta",
    "Mayondon",
    "Putho Tuntungin",
    "San Antonio",
    "Tadlak",
    "Timugan (Pob.)",
  ],
  "0403412000": [
    "Barangay Zone I (Pob.)",
    "Barangay Zone II (Pob.)",
    "Barangay Zone III (Pob.)",
    "Barangay Zone IV (Pob.)",
    "Barangay Zone V (Pob.)",
    "Barangay Zone VI (Pob.)",
    "Barangay Zone VII (Pob.)",
    "Barangay Zone VIII (Pob.)",
    "De La Paz",
    "San Antonio",
    "San Buenaventura",
    "San Diego",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Luis",
    "San Pablo",
    "San Pedro",
    "San Rafael",
    "San Roque",
    "San Salvador",
    "Santo Domingo",
    "Santo Tomas",
  ],
  "0403413000": [
    "Bagong Silang",
    "Balimbingan (Pob.)",
    "Balubad",
    "Caliraya",
    "Concepcion",
    "Lewin",
    "Maracta (Pob.)",
    "Maytalang I",
    "Maytalang II",
    "Primera Parang (Pob.)",
    "Primera Pulo (Pob.)",
    "Salac (Pob.)",
    "Santo Niño (Pob.)",
    "Segunda Parang (Pob.)",
    "Segunda Pulo (Pob.)",
    "Wawa",
  ],
  "0403414000": [
    "Amuyong",
    "Bayanihan (Pob.)",
    "Lambac (Pob.)",
    "Libis ng Nayon (Pob.)",
    "Lucong",
    "Maligaya (Pob.)",
    "Masikap (Pob.)",
    "Matalatala",
    "Nanguma",
    "Numero",
    "Paagahan",
    "Pag-Asa (Pob.)",
    "San Antonio",
    "San Miguel",
    "Sinagtala (Pob.)",
  ],
  "0403415000": [
    "Alipit",
    "Baanan",
    "Balanac",
    "Bucal",
    "Buenavista",
    "Bungkol",
    "Buo",
    "Burlungan",
    "Cigaras",
    "Halayhayin",
    "Ibabang Atingay",
    "Ibabang Butnong",
    "Ilayang Atingay",
    "Ilayang Butnong",
    "Ilog",
    "Malaking Ambling",
    "Malinao",
    "Maravilla",
    "Munting Ambling",
    "Poblacion",
    "Sabang",
    "Salasad",
    "Tanawan",
    "Tipunan",
  ],
  "0403416000": [
    "Amonoy",
    "Bakia",
    "Balanac",
    "Balayong",
    "Banilad",
    "Banti",
    "Bitaoy",
    "Botocan",
    "Bukal",
    "Burgos",
    "Burol",
    "Coralao",
    "Gagalot",
    "Ibabang Banga",
    "Ibabang Bayucain",
    "Ilayang Banga",
    "Ilayang Bayucain",
    "Isabang",
    "Malinao",
    "May-It",
    "Munting Kawayan",
    "Olla",
    "Oobi",
    "Origuel (Pob.)",
    "Panalaban",
    "Pangil",
    "Panglan",
    "Piit",
    "Pook",
    "Rizal",
    "San Francisco (Pob.)",
    "San Isidro",
    "San Miguel (Pob.)",
    "San Roque",
    "Santa Catalina (Pob.)",
    "Suba",
    "Talortor",
    "Tanawan",
    "Taytay",
    "Villa Nogales",
  ],
  "0403417000": [
    "Abo",
    "Alibungbungan",
    "Alumbrado",
    "Balayong",
    "Balimbing",
    "Balinacon",
    "Bambang",
    "Banago",
    "Banca-banca",
    "Bangcuro",
    "Banilad",
    "Bayaquitos",
    "Buboy",
    "Buenavista",
    "Buhanginan",
    "Bukal",
    "Bunga",
    "Cabuyew",
    "Calumpang",
    "Kanluran Kabubuhayan",
    "Kanluran Lazaan",
    "Labangan",
    "Lagulo",
    "Lawaguin",
    "Maiit",
    "Malaya",
    "Malinao",
    "Manaol",
    "Maravilla",
    "Nagcalbang",
    "Oples",
    "Palayan",
    "Palina",
    "Poblacion I (Pob.)",
    "Poblacion II (Pob.)",
    "Poblacion III (Pob.)",
    "Sabang",
    "San Francisco",
    "Santa Lucia",
    "Sibulan",
    "Silangan Ilaya",
    "Silangan Kabubuhayan",
    "Silangan Lazaan",
    "Silangan Napapatid",
    "Sinipian",
    "Sulsuguin",
    "Talahib",
    "Talangan",
    "Taytay",
    "Tipacan",
    "Wakat",
    "Yukos",
  ],
  "0403418000": [
    "Bagumbayan (Pob.)",
    "Bangkusay (Pob.)",
    "Ermita (Pob.)",
    "Ibaba del Norte (Pob.)",
    "Ibaba del Sur (Pob.)",
    "Ilaya del Norte (Pob.)",
    "Ilaya del Sur (Pob.)",
    "Maytoong (Pob.)",
    "Quinale (Pob.)",
  ],
  "0403419000": [
    "Anibong",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Biñan",
    "Buboy",
    "Cabanbanan",
    "Calusiche",
    "Dingin",
    "Lambac",
    "Layugan",
    "Magdapio",
    "Maulawin",
    "Pinagsanjan",
    "Sabang",
    "Sampaloc",
    "San Isidro",
  ],
  "0403420000": [
    "Banilan",
    "Baño (Pob.)",
    "Burgos (Pob.)",
    "Casa Real",
    "Casinsin",
    "Dorado",
    "Gonzales (Pob.)",
    "Kabulusan",
    "Matikiw",
    "Rizal (Pob.)",
    "Saray",
    "Taft (Pob.)",
    "Tavera (Pob.)",
  ],
  "0403421000": [
    "Balian",
    "Dambo",
    "Galalan",
    "Isla (Pob.)",
    "Mabato-Azufre",
    "Natividad (Pob.)",
    "San Jose (Pob.)",
    "Sulib",
  ],
  "0403422000": [
    "Aplaya",
    "Bagong Pook",
    "Bukal",
    "Bulilan Norte (Pob.)",
    "Bulilan Sur (Pob.)",
    "Concepcion",
    "Labuin",
    "Linga",
    "Masico",
    "Mojon",
    "Pansol",
    "Pinagbayanan",
    "San Antonio",
    "San Miguel",
    "Santa Clara Norte (Pob.)",
    "Santa Clara Sur (Pob.)",
    "Tubuan",
  ],
  "0403423000": [
    "Antipolo",
    "East Poblacion",
    "Entablado",
    "Laguan",
    "Paule 1",
    "Paule 2",
    "Pook",
    "Tala",
    "Talaga",
    "Tuy",
    "West Poblacion",
  ],
  "0403424000": [
    "Atisan",
    "Bagong Bayan II-A (Pob.)",
    "Bagong Pook VI-C (Pob.)",
    "Barangay I-A (Pob.)",
    "Barangay I-B (Pob.)",
    "Barangay II-A (Pob.)",
    "Barangay II-B (Pob.)",
    "Barangay II-C (Pob.)",
    "Barangay II-D (Pob.)",
    "Barangay II-E (Pob.)",
    "Barangay II-F (Pob.)",
    "Barangay III-A (Pob.)",
    "Barangay III-B (Pob.)",
    "Barangay III-C (Pob.)",
    "Barangay III-D (Pob.)",
    "Barangay III-E (Pob.)",
    "Barangay III-F (Pob.)",
    "Barangay IV-A (Pob.)",
    "Barangay IV-B (Pob.)",
    "Barangay IV-C (Pob.)",
    "Barangay V-A (Pob.)",
    "Barangay V-B (Pob.)",
    "Barangay V-C (Pob.)",
    "Barangay V-D (Pob.)",
    "Barangay VI-A (Pob.)",
    "Barangay VI-B (Pob.)",
    "Barangay VI-D (Pob.)",
    "Barangay VI-E (Pob.)",
    "Barangay VII-A (Pob.)",
    "Barangay VII-B (Pob.)",
    "Barangay VII-C (Pob.)",
    "Barangay VII-D (Pob.)",
    "Barangay VII-E (Pob.)",
    "Bautista",
    "Concepcion",
    "Del Remedio",
    "Dolores",
    "San Antonio 1",
    "San Antonio 2",
    "San Bartolome",
    "San Buenaventura",
    "San Crispin",
    "San Cristobal",
    "San Diego",
    "San Francisco",
    "San Gabriel",
    "San Gregorio",
    "San Ignacio",
    "San Isidro",
    "San Joaquin",
    "San Jose",
    "San Juan",
    "San Lorenzo",
    "San Lucas 1",
    "San Lucas 2",
    "San Marcos",
    "San Mateo",
    "San Miguel",
    "San Nicolas",
    "San Pedro",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santa Ana",
    "Santa Catalina",
    "Santa Cruz",
    "Santa Elena",
    "Santa Felomina",
    "Santa Isabel",
    "Santa Maria",
    "Santa Maria Magdalena",
    "Santa Monica",
    "Santa Veronica",
    "Santiago I",
    "Santiago II",
    "Santisimo Rosario",
    "Santo Angel",
    "Santo Cristo",
    "Santo Niño",
    "Soledad",
  ],
  "0403425000": [
    "Bagong Silang",
    "Calendola",
    "Chrysanthemum",
    "Cuyab",
    "Estrella",
    "Fatima",
    "G.S.I.S.",
    "Landayan",
    "Langgam",
    "Laram",
    "Magsaysay",
    "Maharlika",
    "Narra",
    "Nueva",
    "Pacita 1",
    "Pacita 2",
    "Poblacion",
    "Riverside",
    "Rosario",
    "Sampaguita Village",
    "San Antonio",
    "San Lorenzo Ruiz",
    "San Roque",
    "San Vicente",
    "Santo Niño",
    "United Bayanihan",
    "United Better Living",
  ],
  "0403426000": [
    "Alipit",
    "Bagumbayan",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Bubukal",
    "Calios",
    "Duhat",
    "Gatid",
    "Jasaan",
    "Labuin",
    "Malinao",
    "Oogong",
    "Pagsawitan",
    "Palasan",
    "Patimbao",
    "San Jose",
    "San Juan",
    "San Pablo Norte",
    "San Pablo Sur",
    "Santisima Cruz",
    "Santo Angel Central",
    "Santo Angel Norte",
    "Santo Angel Sur",
  ],
  "0403427000": [
    "Adia",
    "Bagong Pook",
    "Bagumbayan",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Bubukal",
    "Cabooan",
    "Calangay",
    "Cambuja",
    "Coralan",
    "Cueva",
    "Inayapan",
    "Jose Laurel, Sr.",
    "Jose Rizal",
    "Kayhakat",
    "Macasipac",
    "Masinao",
    "Mataling-Ting",
    "Pao-o",
    "Parang Ng Buho",
    "Santiago",
    "Talangka",
    "Tungkod",
  ],
  "0403428000": [
    "Aplaya",
    "Balibago",
    "Caingin",
    "Dila",
    "Dita",
    "Don Jose",
    "Ibaba",
    "Kanluran (Pob.)",
    "Labas",
    "Macabling",
    "Malitlit",
    "Malusak (Pob.)",
    "Market Area (Pob.)",
    "Pook",
    "Pulong Santa Cruz",
    "Santo Domingo",
    "Sinalhan",
    "Tagapo",
  ],
  "0403429000": [
    "Acevida",
    "Bagong Pag-Asa (Pob.)",
    "Bagumbarangay (Pob.)",
    "Buhay",
    "G. Redor (Pob.)",
    "Gen. Luna",
    "Halayhayin",
    "J. Rizal (Pob.)",
    "Kapatalan",
    "Laguio",
    "Liyang",
    "Llavac",
    "Macatad",
    "Magsaysay",
    "Mayatba",
    "Mendiola",
    "P. Burgos",
    "Pandeno",
    "Salubungan",
    "Wawa",
  ],
  "0403430000": [
    "Banca-banca",
    "Daniw",
    "Masapang",
    "Nanhaya (Pob.)",
    "Pagalangan",
    "San Benito",
    "San Felix",
    "San Francisco",
    "San Roque (Pob.)",
  ],
  "0405601000": [
    "Binagbag",
    "Dayap",
    "Ibabang Kinagunan",
    "Ilayang Kinagunan",
    "Kanlurang Calutan",
    "Kanlurang Maligaya",
    "Poblacion I",
    "Poblacion II",
    "Salvacion",
    "Silangang Calutan",
    "Silangang Maligaya",
    "Sildora",
  ],
  "0405602000": [
    "Angeles",
    "Bacong",
    "Balungay",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Buenavista",
    "Caglate",
    "Camagong",
    "Gordon",
    "Pambilan Norte",
    "Pambilan Sur",
    "Villa Esperanza",
    "Villa Jesus Este",
    "Villa Jesus Weste",
    "Villa Norte",
    "Villa Victoria",
  ],
  "0405603000": [
    "Angeles",
    "Balubad",
    "Balugohin",
    "Barangay Zone 1 (Pob.)",
    "Barangay Zone 2 (Pob.)",
    "Barangay Zone 3 (Pob.)",
    "Barangay Zone 4 (Pob.)",
    "Buhangin",
    "Caridad Ibaba",
    "Caridad Ilaya",
    "Habingan",
    "Inaclagan",
    "Inalig",
    "Kilait",
    "Kulawit",
    "Lakip",
    "Lubi",
    "Lumutan",
    "Magsaysay",
    "Malinao Ibaba",
    "Malinao Ilaya",
    "Malusak",
    "Manggalayan Bundok",
    "Manggalayan Labak",
    "Matanag",
    "Montes Balaon",
    "Montes Kallagan",
    "Ponon",
    "Rizal",
    "San Andres Bundok",
    "San Andres Labak",
    "San Isidro",
    "San Jose Balatok",
    "San Rafael",
    "Santa Catalina",
    "Sapaan",
    "Sokol",
    "Tagbakin",
    "Talaba",
    "Tinandog",
    "Villa Ibaba",
    "Villa Ilaya",
  ],
  "0405605000": [
    "Bagong Silang",
    "Batabat Norte",
    "Batabat Sur",
    "Buenavista",
    "Bukal",
    "Bulo",
    "Cabong",
    "Cadlit",
    "Catulin",
    "Cawa",
    "De La Paz",
    "Del Rosario",
    "Hagonghong",
    "Ibabang Wasay",
    "Ilayang Wasay",
    "Lilukin",
    "Mabini",
    "Mabutag",
    "Magallanes",
    "Maligaya",
    "Manlana",
    "Masaya",
    "Poblacion",
    "Rizal",
    "Sabang Pinamasagan",
    "Sabang Piris",
    "San Diego",
    "San Isidro Ibaba",
    "San Isidro Ilaya",
    "San Pablo",
    "San Pedro",
    "San Vicente",
    "Siain",
    "Villa Aurora",
    "Villa Batabat",
    "Villa Magsaysay",
    "Villa Veronica",
  ],
  "0405606000": [
    "Aluyon",
    "Amot",
    "Anibawan",
    "Bonifacio",
    "Cabugao",
    "Cabungalunan",
    "Calutcot",
    "Caniwan",
    "Carlagan",
    "Mabini",
    "Palasan",
    "Poblacion",
    "San Rafael",
  ],
  "0405607000": [
    "Agoho",
    "Anahawan",
    "Anas",
    "Apad Lutao",
    "Apad Quezon",
    "Apad Taisan",
    "Atulayan",
    "Baclaran",
    "Bagong Silang",
    "Balibago",
    "Bangkuruhan",
    "Bantolinao",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Bigaan",
    "Binutas",
    "Biyan",
    "Bukal",
    "Buli",
    "Dapdap",
    "Dominlog",
    "Doña Aurora",
    "Guinosayan",
    "Ipil",
    "Kalibo",
    "Kapaluhan",
    "Katangtang",
    "Kigtan",
    "Kinalin Ibaba",
    "Kinalin Ilaya",
    "Kinamaligan",
    "Kumaludkud",
    "Kunalum",
    "Kuyaoyao",
    "Lagay",
    "Lainglaingan",
    "Lungib",
    "Mabini",
    "Madlangdungan",
    "Maglipad",
    "Maligaya",
    "Mambaling",
    "Manhulugin",
    "Marilag",
    "Mulay",
    "Pandanan",
    "Pansol",
    "Patihan",
    "Pinagbayanan",
    "Pinagkamaligan",
    "Pinagsakahan",
    "Pinagtalleran",
    "Rizal Ibaba",
    "Rizal Ilaya",
    "Sabang I",
    "Sabang II",
    "Salvacion",
    "San Quintin",
    "San Roque Ibaba",
    "San Roque Ilaya",
    "Santa Cecilia",
    "Santa Maria",
    "Santa Milagrosa",
    "Santa Rosa",
    "Santo Angel",
    "Santo Domingo",
    "Sinag",
    "Sumilang",
    "Sumulong",
    "Tabansak",
    "Talingting",
    "Tamis",
    "Tikiwan",
    "Tiniguiban",
    "Villa Magsino",
    "Villa San Isidro",
    "Viñas",
    "Yaganak",
  ],
  "0405608000": [
    "Buenavista East",
    "Buenavista West",
    "Bukal Norte",
    "Bukal Sur",
    "Kinatihan I",
    "Kinatihan II",
    "Malabanban Norte",
    "Malabanban Sur",
    "Mangilag Norte",
    "Mangilag Sur",
    "Masalukot I",
    "Masalukot II",
    "Masalukot III",
    "Masalukot IV",
    "Masalukot V",
    "Masin Norte",
    "Masin Sur",
    "Mayabobo",
    "Pahinga Norte",
    "Pahinga Sur",
    "Poblacion",
    "San Andres",
    "San Isidro",
    "Santa Catalina Norte",
    "Santa Catalina Sur",
  ],
  "0405610000": [
    "Ajos",
    "Anusan",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Bolo",
    "Bulagsong",
    "Camandiison",
    "Canculajao",
    "Catumbo",
    "Cawayanin Ibaba",
    "Cawayanin Ilaya",
    "Cutcutan",
    "Dahican",
    "Doongan Ibaba",
    "Doongan Ilaya",
    "Gatasan",
    "Macpac",
    "Madulao",
    "Matandang Sabang Kanluran",
    "Matandang Sabang Silangan",
    "Milagrosa",
    "Navitas",
    "Pacabit",
    "San Antonio Magkupa",
    "San Antonio Pala",
    "San Isidro",
    "San Jose",
    "San Pablo",
    "San Roque",
    "San Vicente Kanluran",
    "San Vicente Silangan",
    "Santa Maria",
    "Tagabas Ibaba",
    "Tagabas Ilaya",
    "Tagbacan Ibaba",
    "Tagbacan Ilaya",
    "Tagbacan Silangan",
    "Tuhian",
  ],
  "0405615000": [
    "Antonino",
    "Bagong Anyo (Pob.)",
    "Bayanihan (Pob.)",
    "Bulakin I",
    "Bulakin II",
    "Bungoy",
    "Cabatang",
    "Dagatan",
    "Kinabuhayan",
    "Maligaya (Pob.)",
    "Manggahan",
    "Pinagdanlayan",
    "Putol",
    "San Mateo",
    "Santa Lucia",
    "Silanganan (Pob.)",
  ],
  "0405616000": [
    "Bacong Ibaba",
    "Bacong Ilaya",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Lavides",
    "Magsaysay",
    "Malaya",
    "Nieva",
    "Recto",
    "San Ignacio Ibaba",
    "San Ignacio Ilaya",
    "San Isidro Ibaba",
    "San Isidro Ilaya",
    "San Jose",
    "San Nicolas",
    "San Vicente",
    "Santa Maria Ibaba",
    "Santa Maria Ilaya",
    "Sumilang",
    "Villarica",
  ],
  "0405617000": [
    "Anoling",
    "Banglos",
    "Batangan",
    "Canaway",
    "Catablingan",
    "Lumutan",
    "Magsikap",
    "Mahabang Lalim",
    "Maigang",
    "Maligaya",
    "Minahan Norte",
    "Minahan Sur",
    "Pagsangahan",
    "Pamplona",
    "Pisa",
    "Poblacion",
    "Sablang",
    "San Marcelino",
    "Umiray",
  ],
  "0405618000": [
    "A. Mabini",
    "Aloneros",
    "Arbismen",
    "Bagong Silang",
    "Balinarin",
    "Bukal Maligaya",
    "Cabibihan",
    "Cabong Norte",
    "Cabong Sur",
    "Calimpak",
    "Capuluan Central",
    "Capuluan Tulon",
    "Dancalan Caimawan",
    "Dancalan Central",
    "Danlagan Batis",
    "Danlagan Cabayao",
    "Danlagan Central",
    "Danlagan Reserva",
    "Del Rosario",
    "Dungawan Central",
    "Dungawan Paalyunan",
    "Dungawan Pantay",
    "Ermita",
    "Gapas",
    "Himbubulo Este",
    "Himbubulo Weste",
    "Hinabaan",
    "Ligpit Bantayan",
    "Lubigan",
    "Magallanes",
    "Magsaysay",
    "Manggagawa",
    "Manggalang",
    "Manlayo",
    "Poblacion",
    "Salakan",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Lorenzo",
    "San Luis I",
    "San Luis II",
    "San Miguel",
    "San Pedro I",
    "San Pedro II",
    "San Roque",
    "Santa Cruz",
    "Santa Maria",
    "Santa Teresita",
    "Sintones",
    "Sisi",
    "Tikay",
    "Triumpo",
    "Villa Hiwasayan",
  ],
  "0405619000": [
    "Adia Bitaog",
    "Anonangin",
    "Bagong Buhay (Pob.)",
    "Bamban",
    "Bantad",
    "Batong Dalig",
    "Biga",
    "Binambang",
    "Buensuceso",
    "Bungahan",
    "Butaguin",
    "Calumangin",
    "Camohaguin",
    "Casasahan Ibaba",
    "Casasahan Ilaya",
    "Cawayan",
    "Gayagayaan",
    "Gitnang Barrio",
    "Hagakhakin",
    "Hardinan",
    "Inaclagan",
    "Inagbuhan Ilaya",
    "Labnig",
    "Laguna",
    "Lagyo",
    "Mabini (Pob.)",
    "Mabunga",
    "Malabtog",
    "Manlayaan",
    "Marcelo H. Del Pilar",
    "Mataas Na Bundok",
    "Maunlad (Pob.)",
    "Pagsabangan",
    "Panikihan",
    "Peñafrancia (Pob.)",
    "Pipisik (Pob.)",
    "Progreso",
    "Rizal (Pob.)",
    "Rosario",
    "San Agustin",
    "San Diego",
    "San Diego Poblacion",
    "San Isidro Kanluran",
    "San Isidro Silangan",
    "San Juan De Jesus",
    "San Vicente",
    "Sastre",
    "Tabing Dagat (Pob.)",
    "Tumayan",
    "Villa Arcaya",
    "Villa Bota",
    "Villa Fuerte",
    "Villa M. Principe",
    "Villa Mendoza",
    "Villa Nava",
    "Villa Padua",
    "Villa Perez",
    "Villa Tañada",
    "Villa Victoria",
  ],
  "0405620000": [
    "Abiawin",
    "Agos-agos",
    "Alitas",
    "Amolongin",
    "Anibong",
    "Antikin",
    "Bacong",
    "Balobo",
    "Bantilan",
    "Banugao",
    "Batican",
    "Binonoan",
    "Binulasan",
    "Boboin",
    "Catambungan",
    "Cawaynin",
    "Comon",
    "Dinahican",
    "Gumian",
    "Ilog",
    "Ingas",
    "Langgas",
    "Libjo",
    "Lual",
    "Magsaysay",
    "Maypulot",
    "Miswa",
    "Pilaway",
    "Pinaglapatan",
    "Poblacion 1",
    "Poblacion 38",
    "Poblacion 39",
    "Pulo",
    "Silangan",
    "Tongohin",
    "Tudturan",
  ],
  "0405621000": ["Apad", "Bukal", "Casuguran", "Gango", "Talisoy (Pob.)"],
  "0405622000": [
    "Bacungan",
    "Bagacay",
    "Banabahin Ibaba",
    "Banabahin Ilaya",
    "Bayabas",
    "Bebito",
    "Bigajo",
    "Binahian A",
    "Binahian B",
    "Binahian C",
    "Bocboc",
    "Buenavista",
    "Burgos (Pob.)",
    "Buyacanin",
    "Cagacag",
    "Calantipayan",
    "Canda Ibaba",
    "Canda Ilaya",
    "Cawayan",
    "Cawayanin",
    "Cogorin Ibaba",
    "Cogorin Ilaya",
    "Concepcion",
    "Danlagan",
    "De La Paz",
    "Del Pilar",
    "Del Rosario",
    "Esperanza Ibaba",
    "Esperanza Ilaya",
    "Gomez (Pob.)",
    "Guihay",
    "Guinuangan",
    "Guites",
    "Hondagua",
    "Ilayang Ilog A",
    "Ilayang Ilog B",
    "Inalusan",
    "Jongo",
    "Lalaguna",
    "Lourdes",
    "Mabanban",
    "Mabini",
    "Magallanes",
    "Magsaysay (Pob.)",
    "Maguilayan",
    "Mahayod-Hayod",
    "Mal-ay",
    "Mandoog",
    "Manguisian",
    "Matinik",
    "Monteclaro",
    "Pamampangin",
    "Pansol",
    "Peñafrancia",
    "Pisipis",
    "Rizal",
    "Rizal",
    "Roma",
    "Rosario",
    "Samat",
    "San Andres",
    "San Antonio",
    "San Francisco A",
    "San Francisco B",
    "San Isidro",
    "San Jose",
    "San Miguel",
    "San Pedro",
    "San Rafael",
    "San Roque",
    "Santa Catalina",
    "Santa Elena",
    "Santa Jacobe",
    "Santa Lucia",
    "Santa Maria",
    "Santa Rosa",
    "Santa Teresa",
    "Santo Niño Ibaba",
    "Santo Niño Ilaya",
    "Silang",
    "Sugod",
    "Sumalang",
    "Talolong (Pob.)",
    "Tan-ag Ibaba",
    "Tan-ag Ilaya",
    "Tocalin",
    "Vegaflor",
    "Vergaña",
    "Veronica",
    "Villa Aurora",
    "Villa Espina",
    "Villa Geda",
    "Villa Hermosa",
    "Villamonte",
    "Villanacaob",
  ],
  "0405623000": [
    "Abang",
    "Aliliw",
    "Atulinao",
    "Ayuti",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Igang",
    "Kabatete",
    "Kakawit",
    "Kalangay",
    "Kalyaat",
    "Kilib",
    "Kulapi",
    "Mahabang Parang",
    "Malupak",
    "Manasa",
    "May-It",
    "Nagsinamo",
    "Nalunao",
    "Palola",
    "Piis",
    "Samil",
    "Tiawe",
    "Tinamnan",
  ],
  "0405625000": [
    "Amontay",
    "Anos",
    "Buyao",
    "Calantas",
    "Candangal",
    "Castillo (Pob.)",
    "Damayan (Pob.)",
    "Lahing",
    "Luctob",
    "Mabini Ibaba",
    "Mabini Ilaya",
    "Malabahay",
    "Mambog",
    "Masipag (Pob.)",
    "Olongtao Ibaba",
    "Olongtao Ilaya",
    "Padre Herrera",
    "Pag-Asa (Pob.)",
    "Pajarillo",
    "Pinagbayanan",
    "Rizal (Pob.)",
    "Rodriquez (Pob.)",
    "San Isidro",
    "San Jose",
    "San Nicolas",
    "San Vicente",
    "Taguin",
    "Tubigan Ibaba",
    "Tubigan Ilaya",
    "Vista Hermosa",
  ],
  "0405627000": [
    "Abo-abo",
    "Alitap",
    "Baao",
    "Bagong Bayan (Pob.)",
    "Balaybalay",
    "Bato",
    "Cagbalete I",
    "Cagbalete II",
    "Cagsiay I",
    "Cagsiay II",
    "Cagsiay III",
    "Concepcion",
    "Daungan (Pob.)",
    "Liwayway",
    "Lual (Pob.)",
    "Lual Rural",
    "Lucutan",
    "Luya-luya",
    "Mabato (Pob.)",
    "Macasin",
    "Polo",
    "Remedios I",
    "Remedios II",
    "Rizaliana (Pob.)",
    "Rosario",
    "Sadsaran (Pob.)",
    "San Gabriel",
    "San Isidro",
    "San Jose",
    "San Lorenzo",
    "San Miguel",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santa Lucia",
    "Santo Angel",
    "Santo Niño",
    "Santol",
    "Soledad",
    "Tapucan",
  ],
  "0405628000": [
    "Ajos",
    "Amuguis",
    "Anonang",
    "Bagong Silang",
    "Bagupaye",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Bolo",
    "Buenavista",
    "Burgos",
    "Butanyog",
    "Canuyep",
    "F. Nanadiego",
    "Ibabang Cambuga",
    "Ibabang Yuni",
    "Ilayang Cambuga",
    "Ilayang Yuni",
    "Latangan",
    "Magsaysay",
    "Matataja",
    "Pakiing",
    "Patabog",
    "Sagongon",
    "San Isidro",
    "San Pedro",
    "Santa Rosa",
  ],
  "0405629000": [
    "Basiao (Pob.)",
    "Burgos (Pob.)",
    "Cabuyao Norte",
    "Cabuyao Sur",
    "Campo (Pob.)",
    "Danlagan",
    "Duhat",
    "Hinguiwin",
    "Kinagunan Ibaba",
    "Kinagunan Ilaya",
    "Lipata",
    "Marao",
    "Marquez",
    "Punta (Pob.)",
    "Rizal",
    "San Isidro",
    "San Vicente",
    "Sipa",
    "Tulay Buhangin",
    "Villapaz",
    "Walay",
    "Yawe",
  ],
  "0405630000": [
    "Alupaye",
    "Añato",
    "Antipolo",
    "Bantigue",
    "Barangay 1 Castillo (Pob.)",
    "Barangay 2 Daungan (Pob.)",
    "Barangay 3 Del Carmen (Pob.)",
    "Barangay 4 Parang (Pob.)",
    "Barangay 5 Santa Catalina (Pob.)",
    "Barangay 6 Tambak (Pob.)",
    "Bigo",
    "Binahaan",
    "Bukal",
    "Ibabang Bagumbungan",
    "Ibabang Palsabangon",
    "Ibabang Polo",
    "Ikirin",
    "Ilayang Bagumbungan",
    "Ilayang Palsabangon",
    "Ilayang Polo",
    "Kanluran Malicboy",
    "Mapagong",
    "Mayhay",
    "Pinagbayanan",
    "Silangan Malicboy",
    "Talipan",
    "Tukalan",
  ],
  "0405631000": [
    "Balungay",
    "Bato",
    "Bonbon",
    "Calasumanga",
    "Kinalagti",
    "Libo",
    "Lipata",
    "Matangkap",
    "Milawid",
    "Pagitan",
    "Pandan",
    "Rizal",
    "San Juan (Pob.)",
  ],
  "0405632000": [
    "Amaga",
    "Busdak",
    "Kilogan",
    "Luod",
    "Patnanungan Norte",
    "Patnanungan Sur (Pob.)",
  ],
  "0405633000": [
    "Bagong Pag-Asa Pob.",
    "Bagong Silang Pob.",
    "Maabot",
    "Mainit Norte",
    "Mainit Sur",
    "Mapagmahal Pob.",
    "Pagkakaisa Pob.",
    "Pambuhan",
    "Pinagtubigan Este",
    "Pinagtubigan Weste",
    "Rizal",
    "Sangirin",
    "Villamanzano Norte",
    "Villamanzano Sur",
  ],
  "0405634000": [
    "Amontay",
    "Biga",
    "Bilucao",
    "Cabulihan",
    "Castillo (Pob.)",
    "Cawayanin",
    "Cometa",
    "Dalampasigan (Pob.)",
    "Dulong Bayan (Pob.)",
    "Gangahin",
    "Ibabang Burgos",
    "Ibabang Pacatin",
    "Ibabang Piña",
    "Ibabang Soliyao",
    "Ilayang Burgos",
    "Ilayang Pacatin",
    "Ilayang Piña",
    "Ilayang Soliyao",
    "Maaliw (Pob.)",
    "Manggahan (Pob.)",
    "Masaya (Pob.)",
    "Mayubok (Pob.)",
    "Nag-Cruz",
    "Osmeña",
    "Pag-Asa (Pob.)",
    "Pamilihan (Pob.)",
    "Payte",
    "Pinagbayanan",
    "Poctol",
    "Quezon",
    "Quinagasan",
    "Rizalino",
    "Saguinsinan",
    "Sampaloc",
    "San Roque",
    "Sisirin",
    "Sumag Este",
    "Sumag Norte",
    "Sumag Weste",
  ],
  "0405635000": [
    "Central (Pob.)",
    "Concepcion",
    "Duhat",
    "Ilaya",
    "Ilosong",
    "M. L. Tumagay Pob.",
    "Paang Bundok (Pob.)",
    "Pampaaralan (Pob.)",
    "Tanauan",
  ],
  "0405636000": [
    "Anawan",
    "Atulayan",
    "Balesin",
    "Bañadero",
    "Binibitinan",
    "Bislian",
    "Bucao",
    "Canicanian",
    "Kalubakis",
    "Languyin",
    "Libjo",
    "Pamatdan",
    "Pilion",
    "Pinaglubayan",
    "Poblacion",
    "Sabang",
    "Salipsip",
    "Sibulan",
    "Taluong",
    "Tamulaya-Anitong",
  ],
  "0405637000": [
    "Apad",
    "Argosino",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Barangay VI (Pob.)",
    "Cagbalogo",
    "Caridad",
    "Cometa",
    "Del Pilar",
    "Guinhawa",
    "Gumubat",
    "Magsino",
    "Mascariña",
    "Montaña",
    "Sabang",
    "Silangan",
    "Tagkawa",
    "Villa Belen",
    "Villa Francia",
    "Villa Gomez",
    "Villa Mercedes",
  ],
  "0405638000": [
    "Bagong Silang",
    "Capalong",
    "Cawayan",
    "Kiloloran",
    "Llavac",
    "Lubayat",
    "Malapad",
    "Maragondon",
    "Masikap",
    "Maunlad",
    "Pandan",
    "Poblacion 61",
    "Poblacion I",
    "Tagumpay",
    "Tanauan",
    "Tignoan",
    "Ungos",
  ],
  "0405639000": [
    "Alupay",
    "Apasan",
    "Banot",
    "Bataan",
    "Bayongon",
    "Bilucao",
    "Caldong",
    "Ibabang Owain",
    "Ilayang Owain",
    "Mamala",
    "San Bueno",
    "San Isidro (Pob.)",
    "San Roque (Pob.)",
    "Taquico",
  ],
  "0405640000": [
    "Alibihaban",
    "Camflora",
    "Mangero",
    "Pansoy",
    "Poblacion",
    "Tala",
    "Talisay",
  ],
  "0405641000": [
    "Arawan",
    "Bagong Niing",
    "Balat Atis",
    "Briones",
    "Bulihan",
    "Buliran",
    "Callejon",
    "Corazon",
    "Loob",
    "Magsaysay",
    "Manuel del Valle, Sr.",
    "Matipunso",
    "Niing",
    "Poblacion",
    "Pulo",
    "Pury",
    "Sampaga",
    "Sampaguita",
    "San Jose",
    "Sinturisan",
  ],
  "0405642000": [
    "Butanguiad",
    "Casay",
    "Cawayan I",
    "Cawayan II",
    "Don Juan Vercelos",
    "Huyon-Uyon",
    "Ibabang Tayuman",
    "Ilayang Tayuman",
    "Inabuan",
    "Mabuñga",
    "Nasalaan",
    "Pagsangahan",
    "Poblacion",
    "Pugon",
    "Santo Niño",
    "Silongin",
  ],
  "0405644000": [
    "Abuyon",
    "Andres Bonifacio",
    "Bani",
    "Bayanihan (Pob.)",
    "Binay",
    "Buenavista",
    "Busokbusokan",
    "Calwit",
    "Guinhalinan",
    "Lacdayan",
    "Maguiting",
    "Maligaya (Pob.)",
    "Manlampong",
    "Pagdadamayan (Pob.)",
    "Pagkakaisa (Pob.)",
    "Punta",
    "Rizal",
    "San Isidro",
    "San Juan",
    "San Vicente",
    "Vigo Central",
    "Villa Aurin",
    "Villa Reyes",
    "White Cliff",
  ],
  "0405645000": [
    "Antipolo",
    "Balubal",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Bignay 1",
    "Bignay 2",
    "Bucal",
    "Canda",
    "Castañas",
    "Concepcion Banahaw",
    "Concepcion No. 1",
    "Concepcion Palasan",
    "Concepcion Pinagbakuran",
    "Gibanga",
    "Guisguis-San Roque",
    "Guisguis-Talon",
    "Janagdong 1",
    "Janagdong 2",
    "Limbon",
    "Lutucan 1",
    "Lutucan Bata",
    "Lutucan Malabag",
    "Mamala I",
    "Mamala II",
    "Manggalang 1",
    "Manggalang Tulo-tulo",
    "Manggalang-Bantilan",
    "Manggalang-Kiling",
    "Montecillo",
    "Morong",
    "Pili",
    "Sampaloc 1",
    "Sampaloc 2",
    "Sampaloc Bogon",
    "Sampaloc Santo Cristo",
    "Talaan Aplaya",
    "Talaanpantoc",
    "Tumbaga 1",
    "Tumbaga 2",
  ],
  "0405646000": [
    "Aldavoc",
    "Aliji",
    "Bagong Silang",
    "Bamban",
    "Bosigon",
    "Bukal",
    "Cabibihan",
    "Cabugwang",
    "Cagascas",
    "Candalapdap",
    "Casispalan",
    "Colong-colong",
    "Del Rosario",
    "Katimo",
    "Kinatakutan",
    "Landing",
    "Laurel",
    "Magsaysay",
    "Maguibuay",
    "Mahinta",
    "Malbog",
    "Manato Central",
    "Manato Station",
    "Mangayao",
    "Mansilay",
    "Mapulot",
    "Munting Parang",
    "Payapa",
    "Poblacion",
    "Rizal",
    "Sabang",
    "San Diego",
    "San Francisco",
    "San Isidro",
    "San Roque",
    "San Vicente",
    "Santa Cecilia",
    "Santa Monica",
    "Santo Niño I",
    "Santo Niño II",
    "Santo Tomas",
    "Seguiwan",
    "Tabason",
    "Tunton",
    "Victoria",
  ],
  "0405647000": [
    "Alitao",
    "Alsam Ibaba",
    "Alsam Ilaya",
    "Alupay",
    "Angeles Zone I (Pob.)",
    "Angeles Zone II",
    "Angeles Zone III",
    "Angeles Zone IV",
    "Angustias Zone I (Pob.)",
    "Angustias Zone II",
    "Angustias Zone III",
    "Angustias Zone IV",
    "Anos",
    "Ayaas",
    "Baguio",
    "Banilad",
    "Bukal Ibaba",
    "Bukal Ilaya",
    "Calantas",
    "Calumpang",
    "Camaysa",
    "Dapdap",
    "Domoit Kanluran",
    "Domoit Silangan",
    "Gibanga",
    "Ibas",
    "Ilasan Ibaba",
    "Ilasan Ilaya",
    "Ipilan",
    "Isabang",
    "Katigan Kanluran",
    "Katigan Silangan",
    "Lakawan",
    "Lalo",
    "Lawigue",
    "Lita (Pob.)",
    "Malaoa",
    "Masin",
    "Mate",
    "Mateuna",
    "Mayowe",
    "Nangka Ibaba",
    "Nangka Ilaya",
    "Opias",
    "Palale Ibaba",
    "Palale Ilaya",
    "Palale Kanluran",
    "Palale Silangan",
    "Pandakaki",
    "Pook",
    "Potol",
    "San Diego Zone I (Pob.)",
    "San Diego Zone II",
    "San Diego Zone III",
    "San Diego Zone IV",
    "San Isidro Zone I (Pob.)",
    "San Isidro Zone II",
    "San Isidro Zone III",
    "San Isidro Zone IV",
    "San Roque Zone I (Pob.)",
    "San Roque Zone II",
    "Talolong",
    "Tamlong",
    "Tongko",
    "Valencia",
    "Wakas",
  ],
  "0405648000": [
    "Anastacia",
    "Aquino",
    "Ayusan I",
    "Ayusan II",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Behia",
    "Bukal",
    "Bula",
    "Bulakin",
    "Cabatang",
    "Cabay",
    "Del Rosario",
    "Lagalag",
    "Lalig",
    "Lumingon",
    "Lusacan",
    "Paiisa",
    "Palagaran",
    "Quipot",
    "San Agustin",
    "San Francisco",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Pedro",
    "Tagbakin",
    "Talisay",
    "Tamisian",
  ],
  "0405649000": [
    "Almacen",
    "Balagtas",
    "Balanacan",
    "Bonifacio",
    "Bulo Ibaba",
    "Bulo Ilaya",
    "Burgos",
    "Cabulihan Ibaba",
    "Cabulihan Ilaya",
    "Caigdal",
    "F. De Jesus (Pob.)",
    "General Luna",
    "Kalilayan Ibaba",
    "Kalilayan Ilaya",
    "Mabini",
    "Mairok Ibaba",
    "Mairok Ilaya",
    "Malvar",
    "Maputat",
    "Muliguin",
    "Pagaguasan",
    "Panaon Ibaba",
    "Panaon Ilaya",
    "Plaridel",
    "Poctol",
    "Punta",
    "R. Lapu-lapu (Pob.)",
    "R. Magsaysay (Pob.)",
    "Raja Soliman (Pob.)",
    "Rizal Ibaba",
    "Rizal Ilaya",
    "San Roque",
    "Socorro",
    "Tagumpay",
    "Tubas",
    "Tubigan",
  ],
  "0405801000": [
    "Bagumbayan",
    "Kalayaan",
    "Mahabang Parang",
    "Poblacion Ibaba",
    "Poblacion Itaas",
    "San Isidro",
    "San Pedro",
    "San Roque",
    "San Vicente",
    "Santo Niño",
  ],
  "0405802000": [
    "Bagong Nayon",
    "Beverly Hills",
    "Calawis",
    "Cupang",
    "Dalig",
    "Dela Paz (Pob.)",
    "Inarawan",
    "Mambugan",
    "Mayamot",
    "Muntingdilaw",
    "San Isidro (Pob.)",
    "San Jose (Pob.)",
    "San Juan",
    "San Luis",
    "San Roque (Pob.)",
    "Santa Cruz",
  ],
  "0405803000": [
    "Concepcion",
    "Evangelista",
    "Mabini",
    "Pinugay",
    "Rizal (Pob.)",
    "San Jose",
    "San Juan",
    "San Miguel",
    "San Salvador",
    "Santiago",
  ],
  "0405804000": [
    "Bangad",
    "Batingan",
    "Bilibiran",
    "Binitagan",
    "Bombong",
    "Buhangin",
    "Calumpang",
    "Ginoong Sanay",
    "Gulod",
    "Habagatan",
    "Ithan",
    "Janosa",
    "Kalawaan",
    "Kalinawan",
    "Kasile",
    "Kaytome",
    "Kinaboogan",
    "Kinagatan",
    "Layunan (Pob.)",
    "Libid (Pob.)",
    "Libis (Pob.)",
    "Limbon-limbon",
    "Lunsad",
    "Macamot",
    "Mahabang Parang",
    "Malakaban",
    "Mambog",
    "Pag-Asa",
    "Palangoy",
    "Pantok",
    "Pila Pila",
    "Pinagdilawan",
    "Pipindan",
    "Rayap",
    "San Carlos",
    "Sapang",
    "Tabon",
    "Tagpos",
    "Tatala",
    "Tayuman",
  ],
  "0405805000": [
    "San Andres (Pob.)",
    "San Isidro",
    "San Juan",
    "San Roque",
    "Santa Rosa",
    "Santo Domingo",
    "Santo Niño",
  ],
  "0405806000": [
    "Balibago",
    "Boor",
    "Calahan",
    "Dalig",
    "Del Remedio (Pob.)",
    "Iglesia (Pob.)",
    "Lambac",
    "Looc",
    "Malanggam-Calubacan",
    "Nagsulo",
    "Navotas",
    "Patunhay",
    "Real (Pob.)",
    "Sampad",
    "San Roque (Pob.)",
    "Subay",
    "Ticulio",
    "Tuna",
  ],
  "0405807000": [
    "Bagumbong",
    "Bayugo",
    "Lubo",
    "Paalaman",
    "Pagkalinawan",
    "Palaypalay",
    "Punta",
    "Second District (Pob.)",
    "Sipsipin",
    "Special District (Pob.)",
    "Third District (Pob.)",
  ],
  "0405808000": [
    "Balite (Pob.)",
    "Burgos",
    "Geronimo",
    "Macabud",
    "Manggahan",
    "Mascap",
    "Puray",
    "Rosario",
    "San Isidro",
    "San Jose",
    "San Rafael",
  ],
  "0405809000": [
    "Bombongan",
    "Can-Cal-Lan",
    "Lagundi",
    "Maybancal",
    "San Guillermo",
    "San Jose (Pob.)",
    "San Juan (Pob.)",
    "San Pedro (Pob.)",
  ],
  "0405810000": [
    "Bagumbayan (Pob.)",
    "Halayhayin",
    "Hulo (Pob.)",
    "Imatong (Pob.)",
    "Malaya",
    "Niogan",
    "Quisao",
    "Takungan (Pob.)",
    "Wawa (Pob.)",
  ],
  "0405811000": [
    "Ampid I",
    "Ampid II",
    "Banaba",
    "Dulong Bayan 1",
    "Dulong Bayan 2",
    "Guinayang",
    "Guitnang Bayan I (Pob.)",
    "Guitnang Bayan II (Pob.)",
    "Gulod Malaya",
    "Malanday",
    "Maly",
    "Pintong Bocawe",
    "Santa Ana",
    "Santo Niño",
    "Silangan",
  ],
  "0405812000": [
    "Cayabu",
    "Cuyambay",
    "Daraitan",
    "Katipunan-Bayan (Pob.)",
    "Kaybuto (Pob.)",
    "Laiban",
    "Madilay-dilay",
    "Mag-Ampon (Pob.)",
    "Mamuyao",
    "Pinagkamaligan (Pob.)",
    "Plaza Aldea (Pob.)",
    "Sampaloc",
    "San Andres",
    "San Isidro (Pob.)",
    "Santa Inez",
    "Santo Niño",
    "Tabing Ilog (Pob.)",
    "Tandang Kutyo (Pob.)",
    "Tinucan",
    "Wawa (Pob.)",
  ],
  "0405813000": [
    "Dolores (Pob.)",
    "Muzon",
    "San Isidro",
    "San Juan",
    "Santa Ana",
  ],
  "0405814000": [
    "Bagumbayan",
    "Calumpang Santo Cristo",
    "Dalig",
    "Dulumbayan",
    "May-Iba",
    "Poblacion",
    "Prinza",
    "San Gabriel",
    "San Roque",
  ],
  "0431200000": [
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Barra",
    "Bocohan",
    "Cotta",
    "Dalahican",
    "Domoit",
    "Gulang-gulang",
    "Ibabang Dupay",
    "Ibabang Iyam",
    "Ibabang Talim",
    "Ilayang Dupay",
    "Ilayang Iyam",
    "Ilayang Talim",
    "Isabang",
    "Market View",
    "Mayao Castillo",
    "Mayao Crossing",
    "Mayao Kanluran",
    "Mayao Parada",
    "Mayao Silangan",
    "Ransohan",
    "Salinas",
    "Talao-talao",
  ],
};
