/** GENERATED — Region V: 3471 barangays across 114 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "0500501000": [
    "Baclayon",
    "Banao",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 12 (Pob.)",
    "Barangay 13 (Pob.)",
    "Barangay 14 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Bariw",
    "Basud",
    "Bayandong",
    "Bonga",
    "Buang",
    "Busdac",
    "Cabasan",
    "Cagbulacao",
    "Cagraray",
    "Cajogutan",
    "Cawayan",
    "Damacan",
    "Gubat Ilawod",
    "Gubat Iraya",
    "Hindi",
    "Igang",
    "Langaton",
    "Manaet",
    "Mapulang Daga",
    "Mataas",
    "Misibis",
    "Nahapunan",
    "Namanday",
    "Namantao",
    "Napao",
    "Panarayon",
    "Pigcobohan",
    "Pili Ilawod",
    "Pili Iraya",
    "Pongco",
    "San Pablo",
    "San Pedro",
    "Sogod",
    "Sula",
    "Tambilagao",
    "Tambongon",
    "Tanagan",
    "Uson",
    "Vinisitahan-Basud",
    "Vinisitahan-Napao",
  ],
  "0500502000": [
    "Anoling",
    "Baligang",
    "Bantonan",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Bariw",
    "Binanderahan",
    "Binitayan",
    "Bongabong",
    "Cabagñan",
    "Cabraran Pequeño",
    "Caguiba",
    "Calabidongan",
    "Comun",
    "Cotmon",
    "Del Rosario",
    "Gapo",
    "Gotob",
    "Ilawod",
    "Iluluan",
    "Libod",
    "Ligban",
    "Mabunga",
    "Magogon",
    "Manawan",
    "Maninila",
    "Mina",
    "Miti",
    "Palanog",
    "Panoypoy",
    "Pariaan",
    "Quinartilan",
    "Quirangay",
    "Quitinday",
    "Salugan",
    "Solong",
    "Sua",
    "Sumlang",
    "Tagaytay",
    "Tagoytoy",
    "Taladong",
    "Taloto",
    "Taplacon",
    "Tinago",
    "Tumpa",
  ],
  "0500503000": [
    "Alcala",
    "Alobo",
    "Anislag",
    "Bagumbayan",
    "Balinad",
    "Bañadero",
    "Bañag",
    "Bascaran",
    "Bigao",
    "Binitayan",
    "Bongalon",
    "Budiao",
    "Burgos",
    "Busay",
    "Canarom",
    "Cullat",
    "Dela Paz",
    "Dinoronan",
    "Gabawan",
    "Gapo",
    "Ibaugan",
    "Ilawod Area Pob.",
    "Inarado",
    "Kidaco",
    "Kilicao",
    "Kimantong",
    "Kinawitan",
    "Kiwalo",
    "Lacag",
    "Mabini",
    "Malabog",
    "Malobago",
    "Maopi",
    "Market Area Pob. ",
    "Maroroy",
    "Matnog",
    "Mayon",
    "Mi-isi",
    "Nabasan",
    "Namantao",
    "Pandan",
    "Peñafrancia",
    "Sagpon",
    "Salvacion",
    "San Rafael",
    "San Ramon",
    "San Roque",
    "San Vicente Grande",
    "San Vicente Pequeño",
    "Sipi",
    "Tabon-tabon",
    "Tagas",
    "Talahib",
    "Villahermosa",
  ],
  "0500504000": [
    "Agpay",
    "Balite",
    "Banao",
    "Batbat",
    "Binogsacan Lower",
    "Binogsacan Upper",
    "Bololo",
    "Bubulusan",
    "Calzada",
    "Catomag",
    "Doña Mercedes",
    "Doña Tomasa",
    "Ilawod",
    "Inamnan Grande",
    "Inamnan Pequeño",
    "Inascan",
    "Iraya",
    "Lomacao",
    "Maguiron",
    "Maipon",
    "Malabnig",
    "Malipo",
    "Malobago",
    "Maninila",
    "Mapaco",
    "Marcial O. Rañola",
    "Masarawag",
    "Mauraro",
    "Minto",
    "Morera",
    "Muladbucad Grande",
    "Muladbucad Pequeño",
    "Ongo",
    "Palanas",
    "Poblacion",
    "Pood",
    "Quibongbongan",
    "Quitago",
    "San Francisco",
    "San Jose",
    "San Rafael",
    "Sinungtan",
    "Tandarora",
    "Travesia",
  ],
  "0500505000": [
    "Aurora Pob.",
    "Bagacay",
    "Bautista",
    "Cabraran",
    "Calzada Pob.",
    "Del Rosario",
    "Estrella",
    "Florista",
    "Mabini Pob.",
    "Magsaysay Pob",
    "Mamlad",
    "Maogog",
    "Mercado Pob.",
    "Plaza Pob.",
    "Quitinday Pob.",
    "Rizal Pob.",
    "Salvacion",
    "San Isidro",
    "San Roque",
    "San Vicente",
    "Sinagaran",
    "Villa Paz",
    "White Deer Pob.",
  ],
  "0500506000": [
    "Bgy. 1 - Em's Barrio (Pob.)",
    "Bgy. 10 - Cabugao",
    "Bgy. 11 - Maoyod Pob.",
    "Bgy. 12 - Tula-tula (Pob.)",
    "Bgy. 13 - Ilawod West Pob.",
    "Bgy. 14 - Ilawod Pob.",
    "Bgy. 15 - Ilawod East Pob.",
    "Bgy. 16 - Kawit-East Washington Drive (Pob.)",
    "Bgy. 17 - Rizal Street., Ilawod (Pob.)",
    "Bgy. 18 - Cabagñan West (Pob.)",
    "Bgy. 19 - Cabagñan",
    "Bgy. 2 - Em's Barrio South (Pob.)",
    "Bgy. 20 - Cabagñan East (Pob.)",
    "Bgy. 21 - Binanuahan West (Pob.)",
    "Bgy. 22 - Binanuahan East (Pob.)",
    "Bgy. 23 - Imperial Court Subd. (Pob.)",
    "Bgy. 24 - Rizal Street",
    "Bgy. 25 - Lapu-lapu (Pob.)",
    "Bgy. 26 - Dinagaan (Pob.)",
    "Bgy. 27 - Victory Village South (Pob.)",
    "Bgy. 28 - Victory Village North (Pob.)",
    "Bgy. 29 - Sabang (Pob.)",
    "Bgy. 3 - Em's Barrio East (Pob.)",
    "Bgy. 30 - Pigcale (Pob.)",
    "Bgy. 31 - Centro-Baybay (Pob.)",
    "Bgy. 32 - San Roque",
    "Bgy. 33 - PNR-Peñaranda St.-Iraya (Pob.)",
    "Bgy. 34 - Oro Site-Magallanes St. (Pob.)",
    "Bgy. 35 - Tinago (Pob.)",
    "Bgy. 36 - Kapantawan (Pob.)",
    "Bgy. 37 - Bitano (Pob.)",
    "Bgy. 38 - Gogon",
    "Bgy. 39 - Bonot (Pob.)",
    "Bgy. 4 - Sagpon Pob.",
    "Bgy. 40 - Cruzada",
    "Bgy. 41 - Bogtong",
    "Bgy. 42 - Rawis",
    "Bgy. 43 - Tamaoyan",
    "Bgy. 44 - Pawa",
    "Bgy. 45 - Dita",
    "Bgy. 46 - San Joaquin",
    "Bgy. 47 - Arimbay",
    "Bgy. 48 - Bagong Abre",
    "Bgy. 49 - Bigaa",
    "Bgy. 5 - Sagmin Pob.",
    "Bgy. 50 - Padang",
    "Bgy. 51 - Buyuan",
    "Bgy. 52 - Matanag",
    "Bgy. 53 - Bonga",
    "Bgy. 54 - Mabinit",
    "Bgy. 55 - Estanza",
    "Bgy. 56 - Taysan",
    "Bgy. 57 - Dap-dap",
    "Bgy. 58 - Buragwis",
    "Bgy. 59 - Puro",
    "Bgy. 6 - Bañadero Pob.",
    "Bgy. 60 - Lamba",
    "Bgy. 61 - Maslog",
    "Bgy. 62 - Homapon",
    "Bgy. 63 - Mariawa",
    "Bgy. 64 - Bagacay",
    "Bgy. 65 - Imalnod",
    "Bgy. 66 - Banquerohan",
    "Bgy. 67 - Bariis",
    "Bgy. 68 - San Francisco",
    "Bgy. 69 - Buenavista",
    "Bgy. 7 - Baño (Pob.)",
    "Bgy. 70 - Cagbacong",
    "Bgy. 8 - Bagumbayan (Pob.)",
    "Bgy. 9 - Pinaric (Pob.)",
  ],
  "0500507000": [
    "Alongong",
    "Apud",
    "Bacolod",
    "Bariw",
    "Bonbon",
    "Buga",
    "Bulusan",
    "Burabod",
    "Caguscos",
    "East Carisac",
    "Harigue",
    "Libtong",
    "Linao",
    "Mabayawas",
    "Macabugos",
    "Magallang",
    "Malabiga",
    "Marayag",
    "Matara",
    "Molosbolos",
    "Natasan",
    "Niño Jesus",
    "Nogpo",
    "Pantao",
    "Rawis",
    "Sagrada Familia",
    "Salvacion",
    "Sampongan",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Pascual",
    "San Ramon",
    "San Vicente",
    "Santa Cruz",
    "Talin-talin",
    "Tambo",
    "Villa Petrona",
    "West Carisac",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)",
    "Zone V (Pob.)",
    "Zone VI (Pob.)",
    "Zone VII (Pob.)",
  ],
  "0500508000": [
    "Abella",
    "Allang",
    "Amtic",
    "Bacong",
    "Bagumbayan",
    "Balanac",
    "Baligang",
    "Barayong",
    "Basag",
    "Batang",
    "Bay",
    "Binanowan",
    "Binatagan (Pob.)",
    "Bobonsuran",
    "Bonga",
    "Busac",
    "Busay",
    "Cabarian",
    "Calzada (Pob.)",
    "Catburawan",
    "Cavasi",
    "Culliat",
    "Dunao",
    "Francia",
    "Guilid",
    "Herrera",
    "Layon",
    "Macalidong",
    "Mahaba",
    "Malama",
    "Maonon",
    "Nabonton",
    "Nasisi",
    "Oma-oma",
    "Palapas",
    "Pandan",
    "Paulba",
    "Paulog",
    "Pinamaniquian",
    "Pinit",
    "Ranao-ranao",
    "San Vicente",
    "Santa Cruz (Pob.)",
    "Tagpo",
    "Tambo",
    "Tandarura",
    "Tastas",
    "Tinago",
    "Tinampo",
    "Tiongson",
    "Tomolin",
    "Tuburan",
    "Tula-tula Grande",
    "Tula-tula Pequeño",
    "Tupas",
  ],
  "0500509000": [
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Binitayan",
    "Calbayog",
    "Canaway",
    "Salvacion",
    "San Antonio Santicon (Pob.)",
    "San Antonio Sulong",
    "San Francisco",
    "San Isidro Ilawod",
    "San Isidro Iraya",
    "San Jose",
    "San Roque",
    "Santa Cruz",
    "Santa Teresa",
  ],
  "0500510000": [
    "Awang",
    "Bagatangki",
    "Bagumbayan",
    "Balading",
    "Balza",
    "Bariw",
    "Baybay",
    "Bulang",
    "Burabod",
    "Cabunturan",
    "Comun",
    "Diaro",
    "Estancia",
    "Jonop",
    "Labnig",
    "Libod",
    "Malolos",
    "Matalipni",
    "Ogob",
    "Pawa",
    "Payahan",
    "Poblacion",
    "Quinarabasahan",
    "Santa Elena",
    "Soa",
    "Sugcad",
    "Tagoytoy",
    "Tanawan",
    "Tuliw",
  ],
  "0500511000": [
    "Balabagon",
    "Balasbas",
    "Bamban",
    "Buyo",
    "Cabacongan",
    "Cabit",
    "Cawayan",
    "Cawit",
    "Holugan",
    "It-Ba (Pob.)",
    "Malobago",
    "Manumbalay",
    "Nagotgot",
    "Pawa",
    "Tinapian",
  ],
  "0500512000": [
    "Badbad",
    "Badian",
    "Bagsa",
    "Bagumbayan",
    "Balogo",
    "Banao",
    "Bangiawon",
    "Bogtong",
    "Bongoran",
    "Busac",
    "Cadawag",
    "Cagmanaba",
    "Calaguimit",
    "Calpi",
    "Calzada",
    "Camagong",
    "Casinagan",
    "Centro Poblacion",
    "Coliat",
    "Del Rosario",
    "Gumabao",
    "Ilaor Norte",
    "Ilaor Sur",
    "Iraya Norte",
    "Iraya Sur",
    "Manga",
    "Maporong",
    "Maramba",
    "Matambo",
    "Mayag",
    "Mayao",
    "Moroponros",
    "Nagas",
    "Obaliw-Rinas",
    "Pistola",
    "Ramay",
    "Rizal",
    "Saban",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Miguel",
    "San Pascual",
    "San Ramon",
    "San Vicente",
    "Tablon",
    "Talisay",
    "Talongog",
    "Tapel",
    "Tobgon",
    "Tobog",
  ],
  "0500513000": [
    "Agol",
    "Alabangpuro",
    "Banawan",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Basicao Coastal",
    "Basicao Interior",
    "Binodegahan",
    "Buenavista",
    "Buyo",
    "Caratagan",
    "Cuyaoyao",
    "Flores",
    "La Medalla",
    "Lawinon",
    "Macasitas",
    "Malapay",
    "Malidong",
    "Mamlad",
    "Marigondon",
    "Matanglad",
    "Nablangbulod",
    "Oringon",
    "Palapas",
    "Panganiran",
    "Rawis",
    "Salvacion",
    "Santo Cristo",
    "Sukip",
    "Tibabo",
  ],
  "0500514000": [
    "Agos",
    "Alnay",
    "Alomon",
    "Amoguis",
    "Anopol",
    "Apad",
    "Balaba",
    "Balangibang",
    "Balinad",
    "Basud",
    "Binagbangan",
    "Buyo",
    "Centro Occidental (Pob.)",
    "Centro Oriental (Pob.)",
    "Cepres",
    "Cotmon",
    "Cotnogan",
    "Danao",
    "Gabon",
    "Gamot",
    "Itaran",
    "Kinale",
    "Kinuartilan",
    "La Medalla",
    "La Purisima",
    "Lanigay",
    "Lidong",
    "Lourdes",
    "Magpanambo",
    "Magurang",
    "Matacon",
    "Maynaga",
    "Maysua",
    "Mendez",
    "Napo",
    "Pinagdapugan",
    "Ponso",
    "Salvacion",
    "San Roque",
    "Santa Cruz",
    "Santa Teresita",
    "Santicon",
    "Sugcad",
    "Ubaliw",
  ],
  "0500515000": [
    "Bagaobawan",
    "Batan",
    "Bilbao",
    "Binosawan",
    "Bogtong",
    "Buenavista",
    "Buhatan",
    "Calanaga",
    "Caracaran",
    "Carogcog",
    "Dap-dap",
    "Gaba",
    "Galicia",
    "Guadalupe",
    "Hamorawon",
    "Lagundi",
    "Liguan",
    "Linao",
    "Malobago",
    "Mananao",
    "Mancao",
    "Manila",
    "Masaga",
    "Morocborocan",
    "Nagcalsot",
    "Pagcolbon",
    "Poblacion",
    "Sagrada",
    "San Ramon",
    "Santa Barbara",
    "Tinocawan",
    "Tinopan",
    "Viga",
    "Villahermosa",
  ],
  "0500516000": [
    "Alimsog",
    "Bagong San Roque",
    "Buhatan",
    "Calayucay",
    "Del Rosario Pob.",
    "Fidel Surtida",
    "Lidong",
    "Market Site Pob.",
    "Nagsiya Pob.",
    "Pandayan Pob.",
    "Salvacion",
    "San Andres",
    "San Fernando",
    "San Francisco Pob.",
    "San Isidro",
    "San Juan Pob.",
    "San Pedro Pob.",
    "San Rafael Pob.",
    "San Roque",
    "San Vicente Pob.",
    "Santa Misericordia",
    "Santo Domingo Pob.",
    "Santo Niño",
  ],
  "0500517000": [
    "Agnas",
    "Bacolod",
    "Bangkilingan",
    "Bantayan",
    "Baranghawon",
    "Basagan",
    "Basud (Pob.)",
    "Bogñabong",
    "Bombon (Pob.)",
    "Bonot",
    "Buang",
    "Buhian",
    "Cabagñan",
    "Cobo",
    "Comon",
    "Cormidal",
    "Divino Rostro (Pob.)",
    "Fatima",
    "Guinobat",
    "Hacienda",
    "Magapo",
    "Mariroc",
    "Matagbac",
    "Oras",
    "Oson",
    "Panal",
    "Pawa",
    "Pinagbobong",
    "Quinale Cabasan (Pob.)",
    "Quinastillojan",
    "Rawis",
    "Sagurong",
    "Salvacion",
    "San Antonio",
    "San Carlos",
    "San Isidro",
    "San Juan (Pob.)",
    "San Lorenzo",
    "San Ramon",
    "San Roque",
    "San Vicente",
    "Santo Cristo (Pob.)",
    "Sua-Igot",
    "Tabiguian",
    "Tagas",
    "Tayhi (Pob.)",
    "Visita",
  ],
  "0500518000": [
    "Bagumbayan",
    "Bariis",
    "Baybay",
    "Belen",
    "Biyong",
    "Bolo",
    "Cale",
    "Cararayan",
    "Coro-coro",
    "Dap-dap",
    "Gajo",
    "Joroan",
    "Libjo",
    "Libtong",
    "Matalibong",
    "Maynonong",
    "Mayong",
    "Misibis",
    "Naga",
    "Nagas",
    "Oyama",
    "Putsan",
    "San Bernardo",
    "Sogod",
    "Tigbi (Pob.)",
  ],
  "0501601000": [
    "Angas",
    "Bactas",
    "Binatagan",
    "Caayunan",
    "Guinatungan",
    "Hinampacan",
    "Langa",
    "Laniton",
    "Lidong",
    "Mampili",
    "Mandazo",
    "Mangcamagong",
    "Manmuntay",
    "Mantugawe",
    "Matnog",
    "Mocong",
    "Oliva",
    "Pagsangahan",
    "Pinagwarasan",
    "Plaridel",
    "Poblacion 1",
    "Poblacion 2",
    "San Felipe",
    "San Jose",
    "San Pascual",
    "Taba-taba",
    "Tacad",
    "Taisan",
    "Tuaca",
  ],
  "0501602000": [
    "Alayao",
    "Binawangan",
    "Calabaca",
    "Camagsaan",
    "Catabaguangan",
    "Catioan",
    "Del Pilar",
    "Itok",
    "Lucbanan",
    "Mabini",
    "Mactang",
    "Magsaysay",
    "Mataque",
    "Old Camp",
    "Poblacion",
    "San Antonio",
    "San Isidro",
    "San Roque",
    "Tanawan",
    "Ubang",
    "Villa Aurora",
    "Villa Belen",
  ],
  "0501603000": [
    "Alawihao",
    "Awitan",
    "Bagasbas",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Barangay VI (Pob.)",
    "Barangay VII (Pob.)",
    "Barangay VIII (Pob.)",
    "Bibirao",
    "Borabod",
    "Calasgasan",
    "Camambugan",
    "Cobangbang",
    "Dogongan",
    "Gahonon",
    "Gubat",
    "Lag-On",
    "Magang",
    "Mambalite",
    "Mancruz",
    "Pamorangon",
    "San Isidro",
  ],
  "0501604000": [
    "Daculang Bolo",
    "Dagotdotan",
    "Langga",
    "Laniton",
    "Maisog",
    "Mampurog",
    "Manlimonsito",
    "Matacong (Pob.)",
    "Salvacion",
    "San Antonio",
    "San Isidro",
    "San Ramon",
  ],
  "0501605000": [
    "Bagong Bayan",
    "Calero",
    "Dahican",
    "Dayhagan",
    "Larap",
    "Luklukan Norte",
    "Luklukan Sur",
    "Motherlode",
    "Nakalaya",
    "North Poblacion",
    "Osmeña",
    "Pag-Asa",
    "Parang",
    "Plaridel",
    "Salvacion",
    "San Isidro",
    "San Jose",
    "San Martin",
    "San Pedro",
    "San Rafael",
    "Santa Cruz",
    "Santa Elena",
    "Santa Milagrosa",
    "Santa Rosa Norte",
    "Santa Rosa Sur",
    "South Poblacion",
    "Tamisan",
  ],
  "0501606000": [
    "Anahaw (Pob.)",
    "Anameam",
    "Awitan",
    "Baay",
    "Bagacay",
    "Bagong Silang I",
    "Bagong Silang II",
    "Bagong Silang III",
    "Bakiad",
    "Bautista",
    "Bayabas",
    "Bayan-bayan",
    "Benit",
    "Bulhao",
    "Cabatuhan",
    "Cabusay",
    "Calabasa",
    "Canapawan",
    "Daguit",
    "Dalas",
    "Dumagmang",
    "Exciban",
    "Fundado",
    "Guinacutan",
    "Guisican",
    "Gumamela (Pob.)",
    "Iberica",
    "Kalamunding (Pob.)",
    "Lugui",
    "Mabilo I",
    "Mabilo II",
    "Macogon",
    "Mahawan-hawan",
    "Malangcao-Basud",
    "Malasugui",
    "Malatap",
    "Malaya",
    "Malibago",
    "Maot",
    "Masalong",
    "Matanlang",
    "Napaod",
    "Pag-Asa",
    "Pangpang",
    "Pinya (Pob.)",
    "San Antonio",
    "San Francisco (Pob.)",
    "Santa Cruz",
    "Submakin",
    "Talobatib",
    "Tigbinan",
    "Tulay Na Lupa",
  ],
  "0501607000": [
    "Apuao",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Barangay VI (Pob.)",
    "Barangay VII (Pob.)",
    "Caringo",
    "Catandunganon",
    "Cayucyucan",
    "Colasi",
    "Del Rosario",
    "Gaboc",
    "Hamoraon",
    "Hinipaan",
    "Lalawigan",
    "Lanot",
    "Mambungalon",
    "Manguisoc",
    "Masalongsalong",
    "Matoogtoog",
    "Pambuhan",
    "Quinapaguian",
    "San Roque",
    "Tarum",
  ],
  "0501608000": [
    "Awitan",
    "Bagumbayan",
    "Bakal",
    "Batobalani",
    "Calaburnay",
    "Capacuan",
    "Casalugan",
    "Dagang",
    "Dalnac",
    "Dancalan",
    "Gumaus",
    "Labnig",
    "Macolabo Island",
    "Malacbang",
    "Malaguit",
    "Mampungo",
    "Mangkasay",
    "Maybato",
    "Palanas",
    "Pinagbirayan Malaki",
    "Pinagbirayan Munti",
    "Poblacion Norte",
    "Poblacion Sur",
    "Tabas",
    "Talusan",
    "Tawig",
    "Tugos",
  ],
  "0501609000": [
    "Asdum",
    "Cabanbanan",
    "Calabagas",
    "Fabrica",
    "Iraya Sur",
    "Man-Ogob",
    "Poblacion District I",
    "Poblacion District II",
    "San Jose",
  ],
  "0501610000": [
    "Basiad",
    "Bulala",
    "Don Tomas",
    "Guitol",
    "Kabuluan",
    "Kagtalaba",
    "Maulawin",
    "Patag Ibaba",
    "Patag Iraya",
    "Plaridel",
    "Polungguitguit",
    "Rizal",
    "Salvacion",
    "San Lorenzo",
    "San Pedro",
    "San Vicente",
    "Santa Elena (Pob.)",
    "Tabugon",
    "Villa San Isidro",
  ],
  "0501611000": [
    "Binanuaan",
    "Caawigan",
    "Cahabaan",
    "Calintaan",
    "Del Carmen",
    "Gabon",
    "Itomang",
    "Poblacion",
    "San Francisco",
    "San Isidro",
    "San Jose",
    "San Nicolas",
    "Santa Cruz",
    "Santa Elena",
    "Santo Niño",
  ],
  "0501612000": [
    "Aguit-It",
    "Banocboc",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Cagbalogo",
    "Calangcawan Norte",
    "Calangcawan Sur",
    "Guinacutan",
    "Mangcawayan",
    "Mangcayo",
    "Manlucugan",
    "Matango",
    "Napilihan",
    "Pinagtigasan",
    "Sabang",
    "Santo Domingo",
    "Singi",
    "Sula",
  ],
  "0501701000": [
    "Agdangan Pob.",
    "Antipolo",
    "Bagumbayan",
    "Buluang",
    "Caranday",
    "Cristo Rey",
    "Del Pilar",
    "Del Rosario (Pob.)",
    "Iyagan",
    "La Medalla",
    "Lourdes",
    "Nababarera",
    "Pugay",
    "Sagrada",
    "Salvacion",
    "San Francisco (Pob.)",
    "San Isidro",
    "San Jose (Pob.)",
    "San Juan",
    "San Nicolas (Pob.)",
    "San Rafael",
    "San Ramon (Pob.)",
    "San Roque (Pob.)",
    "San Vicente",
    "Santa Cruz (Pob.)",
    "Santa Eulalia",
    "Santa Isabel",
    "Santa Teresa",
    "Santa Teresita",
    "Tapol",
  ],
  "0501702000": [
    "Cabanbanan",
    "Cabungan",
    "Camangahan",
    "Cayogcog",
    "Coguit",
    "Duran",
    "Laganac",
    "Luluasan",
    "Montenegro",
    "Pararao",
    "Pulang Daga",
    "Sagrada Nacacale",
    "San Francisco",
    "Santiago Nacacale",
    "Siramag (Pob.)",
    "Tapayas",
    "Tomatarayo",
  ],
  "0501703000": [
    "Agos",
    "Bacolod",
    "Buluang",
    "Caricot",
    "Cawacagan",
    "Cotmon",
    "Cristo Rey",
    "Del Rosario",
    "Divina Pastora (Pob.)",
    "Goyudan",
    "Lobong",
    "Lubigan",
    "Mainit",
    "Manga",
    "Masoli",
    "Neighborhood",
    "Niño Jesus",
    "Pagatpatan",
    "Palo",
    "Payak",
    "Sagrada",
    "Salvacion",
    "San Isidro (Pob.)",
    "San Juan",
    "San Miguel",
    "San Rafael (Pob.)",
    "San Roque",
    "San Vicente",
    "Santa Cruz (Pob.)",
    "Santiago (Pob.)",
    "Sooc",
    "Tagpolo",
    "Tres Reyes (Pob.)",
  ],
  "0501704000": [
    "Pagao",
    "San Antonio",
    "San Francisco",
    "San Isidro (Pob.)",
    "San Jose (Pob.)",
    "San Roque (Pob.)",
    "Santo Domingo",
    "Siembre",
  ],
  "0501705000": [
    "Amlongan",
    "Antipolo",
    "Burocbusoc",
    "Cabatuan",
    "Cagmaslog",
    "De La Fe",
    "Delos Angeles",
    "Divino Rostro",
    "Gabas",
    "Ibayugan",
    "Igbac",
    "Ipil",
    "Iraya",
    "Labawon",
    "Lourdes",
    "Macaangay",
    "Monte Calvario",
    "Namurabod",
    "Sagrada Familia",
    "Salvacion",
    "San Antonio",
    "San Buenaventura (Pob.)",
    "San Francisco",
    "San Isidro",
    "San Jose Baybayon",
    "San Jose Salay",
    "San Pascual (Pob.)",
    "San Pedro (Pob.)",
    "San Rafael",
    "San Ramon",
    "San Roque (Pob.)",
    "San Vicente",
    "Santa Clara (Pob.)",
    "Santa Cruz",
    "Santa Elena (Pob.)",
    "Santa Isabel",
    "Santa Justina",
    "Tambo",
  ],
  "0501706000": [
    "Bagoladio",
    "Bagumbayan",
    "Balaogan",
    "Caorasan",
    "Casugad",
    "Causip",
    "Fabrica",
    "Inoyonan",
    "Itangon",
    "Kinalabasahan",
    "La Purisima",
    "La Victoria",
    "Lanipga",
    "Lubgan",
    "Ombao Heights",
    "Ombao Polpog",
    "Palsong",
    "Panoypoyan",
    "Pawili",
    "Sagrada",
    "Salvacion (Pob.)",
    "San Agustin",
    "San Francisco",
    "San Isidro",
    "San Jose",
    "San Miguel",
    "San Ramon",
    "San Roque (Pob.)",
    "San Roque Heights",
    "Santa Elena",
    "Santo Domingo",
    "Santo Niño",
    "Taisan",
  ],
  "0501707000": [
    "Barcelonita",
    "Biong",
    "Camagong",
    "Castillo",
    "New Poblacion",
    "Pandan",
    "San Pedro",
    "Santa Cruz",
    "Santa Lutgarda (Pob.)",
  ],
  "0501708000": [
    "Balatasan",
    "Balombon",
    "Balongay",
    "Belen",
    "Bigaas",
    "Binaliw",
    "Binanuaanan Grande",
    "Binanuaanan Pequeño",
    "Bonot-Santa Rosa",
    "Burabod",
    "Cabanbanan",
    "Cagsao",
    "Camuning",
    "Comaguingking",
    "Del Carmen (Pob.)",
    "Dominorog",
    "Fabrica",
    "Harobay",
    "La Purisima",
    "Lugsad",
    "Manguiring",
    "Pagatpat",
    "Paolbo",
    "Pinada",
    "Punta Tarawal",
    "Quinale",
    "Sabang",
    "Salvacion-Baybay",
    "San Antonio",
    "San Antonio Poblacion",
    "San Bernardino",
    "San Francisco (Pob.)",
    "San Isidro",
    "San Lucas",
    "San Miguel (Pob.)",
    "San Pablo (Pob.)",
    "San Roque",
    "San Vicente (Pob.)",
    "Santa Cruz Poblacion",
    "Santa Cruz Ratay",
    "Santa Isabel (Pob.)",
    "Santa Salud (Pob.)",
    "Santo Domingo",
    "Santo Niño",
    "Siba-o",
    "Sibobo",
    "Sogod",
    "Tomagodtod",
  ],
  "0501709000": [
    "Dugcal",
    "Marupit",
    "San Francisco",
    "San Jose-San Pablo (Pob.)",
    "San Juan-San Ramon (Pob.)",
    "San Lucas (Pob.)",
    "San Marcos (Pob.)",
    "San Mateo (Pob.)",
    "San Roque",
    "Santo Domingo (Pob.)",
    "Santo Tomas (Pob.)",
    "Sua",
    "Tarosanan",
  ],
  "0501710000": [
    "Baras (Pob.)",
    "Del Rosario",
    "Dinaga (Pob.)",
    "Fundado",
    "Haring",
    "Iquin",
    "Linaga",
    "Mangayawan",
    "Palo",
    "Pangpang (Pob.)",
    "Poro",
    "San Agustin",
    "San Francisco",
    "San Jose East",
    "San Jose West",
    "San Juan",
    "San Nicolas",
    "San Roque",
    "San Vicente",
    "Santa Cruz (Pob.)",
    "Santa Teresita",
    "Sua",
    "Talidtid",
    "Tibgao (Pob.)",
  ],
  "0501711000": [
    "Agaas",
    "Antolon",
    "Bacgong",
    "Bahay",
    "Bikal",
    "Binanuahan (Pob.)",
    "Cabacongan",
    "Cadong",
    "Canatuan",
    "Caputatan",
    "Colongcogong",
    "Daraga",
    "Gata",
    "Gibgos",
    "Gogon",
    "Guijalo",
    "Hanopol",
    "Hanoy",
    "Haponan",
    "Ilawod",
    "Ili-Centro (Pob.)",
    "Lidong",
    "Lubas",
    "Malabog",
    "Maligaya",
    "Mampirao",
    "Mandiclum",
    "Maqueda",
    "Minalaba",
    "Oring",
    "Oroc-Osoc",
    "Pagolinan",
    "Pandanan",
    "Paniman",
    "Patag-Belen",
    "Pili-Centro",
    "Pili-Tabiguian",
    "Poloan",
    "Salvacion",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Solnopan",
    "Tabgon",
    "Tabiguian",
    "Tabog",
    "Tawog (Pob.)",
    "Terogo",
    "Toboan",
  ],
  "0501712000": [
    "Bagong Silang",
    "Bucal",
    "Cabasag",
    "Comadaycaday",
    "Comadogcadog",
    "Domagondong",
    "Kinalangan",
    "Mabini",
    "Magais I",
    "Magais II",
    "Mansalaya",
    "Nagkalit",
    "Palaspas",
    "Pamplona",
    "Pasay",
    "Pinagdapian",
    "Pinugusan",
    "Poblacion Zone III",
    "Sabang",
    "Salvacion",
    "San Juan",
    "San Pablo",
    "Santa Rita I",
    "Santa Rita II",
    "Sinagawsawan",
    "Sinuknipan I",
    "Sinuknipan II",
    "Sugsugin",
    "Tabion",
    "Tomagoktok",
    "Zone I Fatima (Pob.)",
    "Zone II San Antonio (Pob.)",
  ],
  "0501713000": [
    "Cagbunga",
    "Dahilig",
    "District I (Pob.)",
    "District II (Pob.)",
    "Loob",
    "Malbong",
    "Namuat",
    "Sampaloc",
  ],
  "0501714000": [
    "Ason",
    "Bahi",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Binagasbasan",
    "Burabod",
    "Cagamutan",
    "Cagnipa",
    "Canlong",
    "Dangla",
    "Del Pilar",
    "Denrica",
    "Harrison",
    "Mansangat",
    "Pambuhan",
    "Sagrada",
    "Salvacion",
    "San Vicente",
    "Sumaoy",
    "Tamiawon",
    "Toytoy",
  ],
  "0501715000": [
    "Abucayan",
    "Bagumbayan Grande (Pob.)",
    "Bagumbayan Pequeño (Pob.)",
    "Balaynan",
    "Belen (Pob.)",
    "Buyo",
    "Cagaycay",
    "Catagbacan",
    "Digdigon",
    "Gimaga",
    "Halawig-Gogon",
    "Hiwacloy",
    "La Purisima (Pob.)",
    "Lamon",
    "Matacla",
    "Maymatan",
    "Maysalay",
    "Napawon",
    "Panday (Pob.)",
    "Payatan",
    "Pinaglabanan",
    "Salog",
    "San Benito (Pob.)",
    "San Isidro (Pob.)",
    "San Isidro West",
    "San Jose (Pob.)",
    "San Juan Bautista (Pob.)",
    "San Juan Evangelista (Pob.)",
    "San Pedro",
    "Scout Fuentebella",
    "Tabgon",
    "Tagongtong",
    "Tamban",
    "Taytay",
  ],
  "0501716000": [
    "Antipolo",
    "Cristo Rey",
    "Del Rosario",
    "Francia",
    "La Anunciacion",
    "La Medalla",
    "La Purisima",
    "La Trinidad",
    "Niño Jesus",
    "Perpetual Help",
    "Sagrada",
    "Salvacion",
    "San Agustin",
    "San Andres",
    "San Antonio",
    "San Francisco (Pob.)",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Miguel",
    "San Nicolas",
    "San Pedro",
    "San Rafael",
    "San Ramon",
    "San Roque (Pob.)",
    "San Vicente Norte",
    "San Vicente Sur",
    "Santa Cruz Norte",
    "Santa Cruz Sur",
    "Santa Elena",
    "Santa Isabel",
    "Santa Maria",
    "Santa Teresita",
    "Santiago",
    "Santo Domingo",
    "Santo Niño",
  ],
  "0501717000": [
    "Agosais",
    "Agpo-Camagong-Tabog",
    "Amoguis",
    "Balaton",
    "Binanuahan",
    "Bocogan",
    "Burabod",
    "Cabotonan",
    "Dahat",
    "Del Carmen",
    "Gimagtocon",
    "Ginorangan",
    "Gubat",
    "Guibahoy",
    "Himanag",
    "Kinahologan",
    "Loho",
    "Manamoc",
    "Mangogon",
    "Mapid",
    "Olas",
    "Omalo",
    "Panagan",
    "Panicuan",
    "Pinamihagan",
    "San Francisco (Pob.)",
    "San Isidro",
    "San Isidro Norte (Pob.)",
    "San Isidro Sur (Pob.)",
    "San Rafael",
    "San Ramon",
    "San Roque",
    "San Sebastian",
    "San Vicente (Pob.)",
    "Santa Cruz (Pob.)",
    "Santa Maria (Pob.)",
    "Saripongpong (Pob.)",
    "Sipaco",
  ],
  "0501718000": [
    "Aslong",
    "Awayan",
    "Bagacay",
    "Bagadion",
    "Bagamelon",
    "Bagumbayan",
    "Bahao",
    "Bahay",
    "Begajo Norte",
    "Begajo Sur",
    "Beguito Nuevo",
    "Beguito Viejo",
    "Bikal",
    "Busak",
    "Caima",
    "Calabnigan",
    "Camambugan",
    "Cambalidio",
    "Candami",
    "Candato",
    "Cawayan",
    "Concepcion",
    "Cuyapi",
    "Danawan",
    "Duang Niog",
    "Handong",
    "Ibid",
    "Inalahan",
    "Labao",
    "Libod I",
    "Libod II",
    "Loba-loba",
    "Mabini",
    "Malansad Nuevo",
    "Malansad Viejo",
    "Malbogon",
    "Malinao",
    "Mambalite",
    "Mambayawas",
    "Mambulo Nuevo",
    "Mambulo Viejo",
    "Mancawayan",
    "Mandacanan",
    "Mantalisay",
    "Padlos",
    "Pag-Oring Nuevo",
    "Pag-Oring Viejo",
    "Palangon",
    "Palong",
    "Patag",
    "Planza",
    "Poblacion",
    "Potot",
    "Puro-Batia",
    "Rongos",
    "Salvacion",
    "San Isidro",
    "San Juan",
    "San Pablo",
    "San Vicente",
    "Sibujo",
    "Sigamot",
    "Station-Church Site",
    "Taban-Fundado",
    "Tampuhan",
    "Tanag",
    "Tarum",
    "Tinalmud Nuevo",
    "Tinalmud Viejo",
    "Tinangkihan",
    "Udoc",
    "Umalo",
    "Uson",
    "Villadima",
    "Villasocorro",
  ],
  "0501719000": [
    "Alleomar",
    "Bagangan Sr.",
    "Bagong Sikat",
    "Bangon",
    "Barrera Jr.",
    "Barrera Sr.",
    "Bel-Cruz",
    "Belwang",
    "Buenasuerte",
    "Bulawan Jr.",
    "Bulawan Sr.",
    "Cabutagan",
    "Casay",
    "Colacling",
    "Cristo Rey",
    "Del Carmen",
    "Haguimit",
    "Haluban",
    "Kaibigan",
    "La Purisima",
    "Lourdes",
    "Mangcawayan",
    "Napolidan",
    "Poblacion",
    "Polantuna",
    "Sagrada",
    "Salvacion",
    "San Isidro",
    "San Jose",
    "San Pedro",
    "San Rafael Norte",
    "San Rafael Sur",
    "San Ramon",
    "San Vicente",
    "Sooc",
    "Tanawan",
    "Tapi",
    "Tible",
  ],
  "0501720000": [
    "Barobaybay",
    "Bell (Pob.)",
    "Carangcang",
    "Carigsa",
    "Casuray",
    "Monserrat (Pob.)",
    "Ponong",
    "San Francisco (Pob.)",
    "San Isidro (Pob.)",
    "San Juan (Pob.)",
    "San Miguel",
    "San Pantaleon (Pob.)",
    "Santa Lucia (Pob.)",
    "Santa Rosa",
    "Santo Tomas (Pob.)",
  ],
  "0501721000": [
    "Alimbuyog",
    "Amparado (Pob.)",
    "Balagbag",
    "Borongborongan",
    "Cabugao",
    "Capucnasan",
    "Dalipay",
    "Del Rosario (Pob.)",
    "Flordeliz",
    "Lipot",
    "Mayaopayawan",
    "Maycatmon",
    "Maydaso",
    "San Antonio",
    "San Jose (Pob.)",
    "San Miguel (Pob.)",
    "San Roque (Pob.)",
    "San Vicente (Pob.)",
    "Santo Domingo (Pob.)",
    "Tarusanan",
  ],
  "0501722000": [
    "Antipolo",
    "Bagolatao",
    "Bagongbong",
    "Baliuag Nuevo",
    "Baliuag Viejo",
    "Catanusan",
    "Del Carmen-Del Rosario (Pob.)",
    "Del Socorro",
    "Hamoraon",
    "Hobo",
    "Irayang Solong",
    "Magadap",
    "Malitbog",
    "Manapao",
    "Mataoroc",
    "Sagrada",
    "Salingogon",
    "San Antonio",
    "San Felipe-Santiago (Pob.)",
    "San Francisco (Pob.)",
    "San Jose",
    "San Juan-San Lorenzo (Pob.)",
    "Taban",
    "Tariric",
    "Timbang",
  ],
  "0501723000": [
    "Angustia",
    "Antipolo Old",
    "Antipolo Young",
    "Aro-aldao",
    "Bustrac",
    "Dolorosa",
    "Duran",
    "Inapatan",
    "La Opinion",
    "La Purisima",
    "Lourdes Old",
    "Lourdes Young",
    "Malawag",
    "Paloyon Oriental",
    "Paloyon Proper",
    "Salvacion Que Gatos",
    "San Antonio (Pob.)",
    "San Antonio Ogbon",
    "San Esteban (Pob.)",
    "San Francisco (Pob.)",
    "San Isidro (Pob.)",
    "San Isidro Inapatan",
    "San Jose",
    "San Juan (Pob.)",
    "San Luis (Pob.)",
    "San Miguel (Pob.)",
    "San Nicolas (Pob.)",
    "San Roque (Pob.)",
    "San Roque Madawon",
    "San Roque Sagumay",
    "San Vicente Gorong-Gorong",
    "San Vicente Ogbon",
    "Santa Barbara",
    "Santa Cruz",
    "Santa Elena Baras",
    "Santa Lucia Baras",
    "Santiago Old",
    "Santiago Young",
    "Santo Domingo",
    "Tandaay",
    "Topas Proper",
    "Topas Sogod",
  ],
  "0501724000": [
    "Abella",
    "Bagumbayan Norte",
    "Bagumbayan Sur",
    "Balatas",
    "Calauag",
    "Cararayan",
    "Carolina",
    "Concepcion Grande",
    "Concepcion Pequeña",
    "Dayangdang",
    "Del Rosario",
    "Dinaga",
    "Igualdad Interior",
    "Lerma",
    "Liboton",
    "Mabolo",
    "Pacol",
    "Panicuason",
    "Peñafrancia",
    "Sabang",
    "San Felipe",
    "San Francisco (Pob.)",
    "San Isidro",
    "Santa Cruz",
    "Tabuco",
    "Tinago",
    "Triangulo",
  ],
  "0501725000": [
    "Ayugan",
    "Cabariwan",
    "Cagmanaba",
    "Del Rosario",
    "Gatbo",
    "Guinaban",
    "Hanawan",
    "Hibago",
    "La Purisima Nuevo",
    "May-Ogob",
    "New Moriones",
    "Old Moriones",
    "Pinit",
    "Poblacion Central",
    "Poblacion East",
    "Poblacion West",
    "Salvacion",
    "San Antonio",
    "San Francisco",
    "San Jose Oras",
    "San Roque Commonal",
    "San Vicente",
    "Santa Cruz",
    "Santo Niño",
    "Villaflorida",
  ],
  "0501726000": [
    "Batang",
    "Burabod",
    "Cagbibi",
    "Cagbunga",
    "Calawat",
    "Del Rosario",
    "Patong",
    "Poblacion",
    "Salvacion",
    "San Gabriel",
    "San Isidro",
    "San Rafael",
    "San Ramon",
    "San Vicente",
    "Tambo",
    "Tampadong",
    "Veneracion",
  ],
  "0501727000": [
    "Antipolo",
    "Bagong Silang",
    "Bahay",
    "Balogo",
    "Caranan",
    "Cuco",
    "Dalupaon",
    "Hubo",
    "Itulan",
    "Macad",
    "Odicon",
    "Quitang",
    "Salvacion",
    "San Antonio",
    "San Cirilo (Pob.)",
    "Santa Rosa Del Norte (Pob.)",
    "Santa Rosa Del Sur (Pob.)",
    "Tilnac",
    "Tinalmud",
  ],
  "0501728000": [
    "Anayan",
    "Bagong Sirang",
    "Binanwaanan",
    "Binobong",
    "Cadlan",
    "Caroyroyan",
    "Curry",
    "Del Rosario",
    "Himaao",
    "La Purisima",
    "New San Roque",
    "Old San Roque (Pob.)",
    "Palestina",
    "Pawili",
    "Sagrada",
    "Sagurong",
    "San Agustin",
    "San Antonio (Pob.)",
    "San Isidro (Pob.)",
    "San Jose",
    "San Juan (Pob.)",
    "San Vicente (Pob.)",
    "Santiago (Pob.)",
    "Santo Niño",
    "Tagbong",
    "Tinangis",
  ],
  "0501729000": [
    "Ayugao",
    "Bagong Sirang",
    "Baliguian",
    "Bantugan",
    "Bicalen",
    "Bitaogan",
    "Buenavista",
    "Bulalacao",
    "Cagnipa",
    "Lagha",
    "Lidong",
    "Liwacsa",
    "Maangas",
    "Pagsangahan",
    "Patrocinio",
    "Pili",
    "Santa Maria (Pob.)",
    "Tanawan",
  ],
  "0501730000": [
    "Agao-ao",
    "Agrupacion",
    "Amomokpok",
    "Apad",
    "Apale",
    "Banga Caves",
    "Baya",
    "Binahan Proper",
    "Binahan Upper",
    "Buenasuerte",
    "Cabadisan",
    "Cabinitan",
    "Cabugao",
    "Caditaan",
    "Cale",
    "Catabangan Proper",
    "F. Simeon",
    "Godofredo Reyes Sr.",
    "Inandawa",
    "Laguio",
    "Lanipga-Cawayan",
    "Liboro",
    "Lohong",
    "Lower Omon",
    "Lower Santa Cruz",
    "Panaytayan",
    "Panaytayan Nuevo",
    "Patalunan",
    "Poblacion Ilaod",
    "Poblacion Iraya",
    "Port Junction Norte",
    "Port Junction Sur",
    "Salvacion",
    "Samay",
    "San Rafael",
    "Tagbac",
    "Upper Omon",
    "Upper Santa Cruz",
  ],
  "0501731000": [
    "Aniog",
    "Atulayan",
    "Bongalon",
    "Buracan",
    "Catalotoan",
    "Del Carmen (Pob.)",
    "Kilantaao",
    "Kilomaon",
    "Mabca",
    "Minadongjol",
    "Nato",
    "Patitinan",
    "San Antonio (Pob.)",
    "San Isidro (Pob.)",
    "San Roque (Pob.)",
    "Santo Niño",
    "Sibaguan",
    "Tinorongan",
    "Turague",
  ],
  "0501732000": [
    "Alianza",
    "Beberon",
    "Bical",
    "Bocal",
    "Bonifacio (Pob.)",
    "Buenavista (Pob.)",
    "Calascagas",
    "Cotmo",
    "Daculang Tubig",
    "Del Pilar (Pob.)",
    "Gñaran",
    "Grijalvo",
    "Lupi",
    "Maragñi",
    "Pamukid",
    "Pinamasagan",
    "Pipian",
    "Planza",
    "Rizal (Pob.)",
    "San Joaquin",
    "Santa Cruz",
    "Tagpocol",
  ],
  "0501733000": [
    "Adiangao",
    "Bagacay",
    "Bahay",
    "Boclod",
    "Calalahan",
    "Calawit",
    "Camagong",
    "Catalotoan",
    "Danlog",
    "Del Carmen (Pob.)",
    "Dolo",
    "Kinalansan",
    "Mampirao",
    "Manzana",
    "Minoro",
    "Palale",
    "Ponglon",
    "Pugay",
    "Sabang",
    "Salogon",
    "San Antonio (Pob.)",
    "San Juan (Pob.)",
    "San Vicente (Pob.)",
    "Santa Cruz (Pob.)",
    "Soledad (Pob.)",
    "Tagas",
    "Tambangan",
    "Telegrafo",
    "Tominawog",
  ],
  "0501734000": [
    "Aldezar",
    "Alteza",
    "Anib",
    "Awayan",
    "Azucena",
    "Bagong Sirang",
    "Binahian",
    "Bolo Norte",
    "Bolo Sur",
    "Bulan",
    "Bulawan",
    "Cabuyao",
    "Caima",
    "Calagbangan",
    "Calampinay",
    "Carayrayan",
    "Cotmo",
    "Gabi",
    "Gaongan",
    "Impig",
    "Lipilip",
    "Lubigan Jr.",
    "Lubigan Sr.",
    "Malaguico",
    "Malubago",
    "Manangle",
    "Mangapo",
    "Mangga",
    "Manlubang",
    "Mantila",
    "North Centro (Pob.)",
    "North Villazar",
    "Sagrada Familia",
    "Salanda",
    "Salvacion",
    "San Isidro",
    "San Vicente",
    "Serranzana",
    "South Centro (Pob.)",
    "South Villazar",
    "Taisan",
    "Tara",
    "Tible",
    "Tula-tula",
    "Vigaan",
    "Yabo",
  ],
  "0501735000": [
    "Bagong Sirang",
    "Bahao",
    "Boboan",
    "Butawanan",
    "Cabugao",
    "Fundado",
    "Homestead",
    "La Purisima",
    "Mabuhay",
    "Malaconini",
    "Matandang Siruma",
    "Nalayahan",
    "Pamintan-Bantilan",
    "Pinitan",
    "Poblacion",
    "Salvacion",
    "San Andres",
    "San Ramon",
    "Sulpa",
    "Tandoc",
    "Tongo-Bantigue",
    "Vito",
  ],
  "0501736000": [
    "Abo",
    "Cabalinadan",
    "Caraycayon",
    "Casuna",
    "Consocep",
    "Coyaoyao",
    "Gaao",
    "Gingaroy",
    "Gubat",
    "Huyonhuyon",
    "Libod",
    "Mabalodbalod",
    "May-Anao",
    "Panagan",
    "Poblacion",
    "Salvacion",
    "San Antonio",
    "San Francisco",
    "San Miguel",
    "San Rafael",
    "Talojongon",
    "Tinawagan",
    "Vinagre",
  ],
  "0501737000": [
    "Agay-Ayan",
    "Antipolo",
    "Bagacay",
    "Banga",
    "Bani",
    "Bataan",
    "Binalay",
    "Bolaobalite",
    "Buenavista",
    "Buyo",
    "Cagliliog",
    "Caloco",
    "Camagong",
    "Canayonan",
    "Cawaynan",
    "Daligan",
    "Filarca (Pob.)",
    "La Medalla",
    "La Purisima (Pob.)",
    "Lupi",
    "Magsaysay",
    "Magtang",
    "Mananao",
    "New Caaluan",
    "Olag Grande",
    "Olag Pequeño",
    "Old Caaluan",
    "Pag-Asa",
    "Pantat",
    "Sagrada",
    "Salvacion",
    "Salvacion Poblacion",
    "San Antonio",
    "San Isidro (Pob.)",
    "San Jose",
    "San Pascual (Pob.)",
    "San Ramon",
    "San Roque",
    "San Vicente",
    "Santa Cruz (Pob.)",
    "Sogod",
    "Tambang",
    "Tierra Nevada",
    "Union",
  ],
  "0502001000": [
    "Antipolo",
    "Bacak",
    "Bagatabao",
    "Bugao",
    "Cahan",
    "Hinipaan",
    "Magsaysay",
    "Poblacion",
    "Quezon",
    "Quigaray",
    "Sagrada",
    "Salvacion",
    "San Isidro",
    "San Rafael",
    "San Vicente",
    "Santa Mesa",
    "Santa Teresa",
    "Suchan",
  ],
  "0502002000": [
    "Abihao",
    "Agban",
    "Bagong Sirang",
    "Batolinao",
    "Benticayan",
    "Buenavista",
    "Caragumihan",
    "Danao",
    "Eastern Poblacion",
    "Ginitligan",
    "Guinsaanan",
    "J. M. Alberto",
    "Macutal",
    "Moning",
    "Nagbarorong",
    "Osmeña",
    "P. Teston",
    "Paniquihan",
    "Puraran",
    "Putsan",
    "Quezon",
    "Rizal",
    "Sagrada",
    "Salvacion",
    "San Lorenzo",
    "San Miguel",
    "Santa Maria",
    "Tilod",
    "Western Poblacion",
  ],
  "0502003000": [
    "Aroyao Pequeño",
    "Bagumbayan",
    "Banawang",
    "Batalay",
    "Binanuahan",
    "Bote",
    "Buenavista",
    "Cabugao",
    "Cagraray",
    "Carorian",
    "Guinobatan",
    "Ilawod (Pob.)",
    "Libjo",
    "Libod Poblacion",
    "Marinawa",
    "Mintay",
    "Oguis",
    "Pananaogan",
    "San Andres",
    "San Pedro",
    "San Roque",
    "Santa Isabel",
    "Sibacungan",
    "Sipi",
    "Talisay",
    "Tamburan",
    "Tilis",
  ],
  "0502004000": [
    "Baybay (Pob.)",
    "Bocon",
    "Bothoan (Pob.)",
    "Buenavista",
    "Bulalacao",
    "Camburo",
    "Dariao",
    "Datag East",
    "Datag West",
    "Guiamlong",
    "Hitoma",
    "Icanbato (Pob.)",
    "Inalmasinan",
    "Iyao",
    "Mabini",
    "Maui",
    "Maysuran",
    "Milaviga",
    "Obi",
    "Panique",
    "Sabangan",
    "Sabloyon",
    "Salvacion",
    "Supang",
    "Toytoy (Pob.)",
    "Tubli",
    "Tucao",
  ],
  "0502005000": [
    "Biong",
    "Dororian",
    "Poblacion District I",
    "Poblacion District II",
    "Poblacion District III",
    "San Pedro",
    "San Vicente",
    "Sicmil",
    "Sioron",
  ],
  "0502006000": [
    "Bagawang",
    "Balagñonan",
    "Baldoc",
    "Canlubi",
    "Catamban",
    "Cobo",
    "Hiyop",
    "Libod (Pob.)",
    "Lourdes",
    "Lumabao",
    "Marambong",
    "Napo (Pob.)",
    "Oga",
    "Pandan Del Norte (Pob.)",
    "Pandan Del Sur (Pob.)",
    "Panuto",
    "Porot",
    "Salvacion",
    "San Andres",
    "San Isidro",
    "San Rafael",
    "San Roque",
    "Santa Cruz",
    "Tabugoc",
    "Tokio",
    "Wagdas",
  ],
  "0502007000": [
    "Alinawan",
    "Babaguan",
    "Bagong Bayan",
    "Burabod",
    "Cabuyoan",
    "Cagdarao",
    "Mabini",
    "Maculiw",
    "Panay",
    "Salvacion (Pob.)",
    "San Antonio",
    "San Joaquin (Pob.)",
    "San Jose (Pob.)",
    "San Juan (Pob.)",
    "San Miguel",
    "San Nicolas (Pob.)",
    "San Pedro (Pob.)",
    "San Vicente (Pob.)",
    "Santa Ana (Pob.)",
    "Santa Maria (Pob.)",
    "Santo Santiago (Pob.)",
    "Taopon",
    "Tibo",
  ],
  "0502008000": [
    "Agojo",
    "Alibuag",
    "Asgad",
    "Bagong Sirang",
    "Barihay",
    "Batong Paloway",
    "Belmonte (Pob.)",
    "Bislig",
    "Bon-ot",
    "Cabcab",
    "Cabungahan",
    "Carangag",
    "Catagbacan",
    "Codon",
    "Comagaycay",
    "Datag",
    "Divino Rostro (Pob.)",
    "Esperanza (Pob.)",
    "Hilawan",
    "Lictin",
    "Lubas",
    "Manambrag",
    "Mayngaway",
    "Palawig",
    "Puting Baybay",
    "Rizal",
    "Salvacion (Pob.)",
    "San Isidro",
    "San Jose",
    "San Roque (Pob.)",
    "San Vicente",
    "Santa Cruz (Pob.)",
    "Sapang Palay (Pob.)",
    "Tibang",
    "Timbaan",
    "Tominawog",
    "Wagdas (Pob.)",
    "Yocti",
  ],
  "0502009000": [
    "Atsan",
    "Balatohan",
    "Boton",
    "Buhi",
    "Dayawa",
    "J. M. Alberto",
    "Katipunan",
    "Kilikilihan",
    "Mabato",
    "Obo",
    "Pacogon",
    "Pagsangahan",
    "Pangilao",
    "Paraiso",
    "Poblacion District II",
    "Poblacion District III",
    "Progreso",
    "Salvacion",
    "San Juan",
    "San Marcos",
    "Santa Elena",
    "Siay",
    "Solong",
    "Tobrehon",
  ],
  "0502010000": [
    "Almojuela",
    "Ananong",
    "Asuncion (Pob.)",
    "Batohonan",
    "Begonia",
    "Botinagan",
    "Buenavista",
    "Burgos",
    "Del Pilar",
    "Mabini",
    "Magsaysay",
    "Ogbong",
    "Osmeña",
    "Pedro Vera",
    "Peñafrancia (Pob.)",
    "Quezon",
    "Quirino",
    "Rizal",
    "Roxas",
    "Sagrada",
    "San Isidro (Pob.)",
    "San Jose Oco",
    "San Jose Poblacion",
    "San Pedro (Pob.)",
    "San Roque (Pob.)",
    "San Vicente (Pob.)",
    "Santa Rosa",
    "Soboc",
    "Tambongon",
    "Tinago",
    "Villa Aurora",
  ],
  "0502011000": [
    "Antipolo Del Norte",
    "Antipolo Del Sur",
    "Balite",
    "Batag",
    "Bigaa",
    "Buenavista",
    "Buyo",
    "Cabihian",
    "Calabnigan",
    "Calampong",
    "Calatagan Proper",
    "Calatagan Tibang",
    "Capilihan",
    "Casoocan",
    "Cavinitan",
    "Concepcion (Pob.)",
    "Constantino (Pob.)",
    "Danicop",
    "Dugui San Isidro",
    "Dugui San Vicente",
    "Dugui Too",
    "F. Tacorda Village",
    "Francia (Pob.)",
    "Gogon Centro",
    "Gogon Sirangan",
    "Hawan Grande",
    "Hawan Ilaya",
    "Hicming",
    "Ibong Sapa",
    "Igang",
    "Juan M. Alberto",
    "Lanao (Pob.)",
    "Magnesia Del Norte",
    "Magnesia Del Sur",
    "Marcelo Alberto (Pob.)",
    "Marilima",
    "Pajo Baguio",
    "Pajo San Isidro",
    "Palnab Del Norte",
    "Palnab Del Sur",
    "Palta Big",
    "Palta Salvacion",
    "Palta Small",
    "Rawis (Pob.)",
    "Salvacion",
    "San Isidro Village",
    "San Jose (Pob.)",
    "San Juan (Pob.)",
    "San Pablo (Pob.)",
    "San Pedro (Pob.)",
    "San Roque (Pob.)",
    "San Vicente",
    "Santa Cruz",
    "Santa Elena (Pob.)",
    "Santo Cristo",
    "Santo Domingo",
    "Santo Niño",
    "Simamla",
    "Sogod-Simamla",
    "Sogod-Tibgao",
    "Talisoy",
    "Tubaon",
    "Valencia",
  ],
  "0504101000": [
    "Ambolong",
    "Amoroy",
    "Amotag",
    "Bagauma",
    "Balawing",
    "Balete",
    "Bangon",
    "Cabangcalan",
    "Cabas-An",
    "Calanay",
    "Capsay",
    "Concepcion",
    "Dayhagan",
    "Don Pablo Dela Rosa",
    "Gumahang",
    "Jaboyoan",
    "Lanang",
    "Luy-a",
    "Macabug",
    "Malubi",
    "Managanaga",
    "Manamoc",
    "Mariposa",
    "Mataba",
    "Matalangtalang",
    "Matongog",
    "Nabongsoran",
    "Pangle",
    "Panique",
    "Pinanaan",
    "Poblacion",
    "Puro",
    "San Agustin",
    "San Isidro",
    "Sawang",
    "Syndicate",
    "Talabaan",
    "Talib",
    "Tigbao",
    "Tinago",
    "Tinigban",
  ],
  "0504102000": [
    "Baao",
    "Banase",
    "Batuila",
    "Cagara",
    "Cagpandan",
    "Cancahorao",
    "Canjunday",
    "Docol",
    "Eastern Capsay",
    "Gabi",
    "Gangao",
    "Lagta",
    "Lahong Interior",
    "Lahong Proper",
    "Lipata",
    "Madangcalan",
    "Magdalena",
    "Manoboc",
    "Obongon Diot",
    "Poblacion",
    "Polot",
    "Potoson",
    "Sog-Ong",
    "Tinapian",
  ],
  "0504103000": [
    "Baybay",
    "Bongcanaway",
    "Calumpang",
    "Cantil",
    "Casamongan",
    "Danao",
    "Dao",
    "Guinbanwahan",
    "Ilaya",
    "Jangan",
    "Jintotolo",
    "Mabuhay",
    "Mapili",
    "Mapitogo",
    "Pajo",
    "Palane",
    "Panguiranan",
    "Panubigan",
    "Poblacion",
    "Pulanduta",
    "Quinayangan Diotay",
    "Quinayangan Tonga",
    "Salvacion",
    "Sampad",
    "San Andres",
    "San Antonio",
    "Sapatos",
    "Talisay",
    "Tonga",
    "Ubo",
    "Victory",
    "Villa Alvarez",
  ],
  "0504104000": [
    "Burgos",
    "Cambañez",
    "Canares",
    "Costa Rica",
    "Danao",
    "Gibraltar",
    "Mabuhay",
    "Matabao",
    "Nasandig",
    "Panisihan",
    "Poblacion",
    "Rizal",
    "Royroy",
    "Sawang",
  ],
  "0504105000": [
    "Abaca",
    "Aguada",
    "Badiang",
    "Bagumbayan",
    "Cadulawan",
    "Cagbatang",
    "Chimenea",
    "Concepcion",
    "Curvada",
    "Divisoria",
    "Domorog",
    "Estampar",
    "Gahit",
    "Libtong",
    "Liong",
    "Maanahao",
    "Madamba",
    "Malobago",
    "Matayum",
    "Matubinao",
    "Mintac",
    "Nadawisan",
    "Osmeña",
    "Pawican",
    "Pitogo",
    "Poblacion",
    "Quezon",
    "San Isidro",
    "San Jose",
    "San Pedro",
    "San Rafael",
    "Santa Teresita",
    "Santo Niño",
    "Tagboan",
    "Tuybo",
    "Villa Pogado",
  ],
  "0504106000": [
    "Begia",
    "Cabayugan",
    "Cabungahan",
    "Calapayan",
    "Calumpang",
    "Chico Island",
    "Dalipe",
    "Divisoria",
    "Gilotongan",
    "Guiom",
    "Iraya",
    "Itombato",
    "Lague-lague",
    "Libertad",
    "Looc",
    "Mactan",
    "Madbad",
    "Mahayahay",
    "Maihao",
    "Malbug",
    "Naro",
    "Palobandera",
    "Pananawan",
    "Peña Island",
    "Pin-As",
    "Poblacion",
    "Pulot",
    "Punta Batsan",
    "R.M. Magbalon",
    "Recodo",
    "San Jose",
    "San Vicente",
    "Taberna",
    "Talisay",
    "Tubog",
    "Tuburan",
    "Villahermosa",
  ],
  "0504107000": [
    "Albasan",
    "Boca Engaño",
    "Buyo",
    "Calpi",
    "Canomay",
    "Cawayan",
    "Imelda",
    "Mababang Baybay",
    "Mabiton",
    "Manapao",
    "Nabasagan",
    "Nonoc",
    "Osmeña",
    "Pasig",
    "Peñafrancia",
    "Poblacion District I",
    "Poblacion District II",
    "Quezon",
    "San Isidro",
    "San Ramon",
    "San Vicente",
    "Taguilid",
  ],
  "0504108000": [
    "Balantay",
    "Balocawe",
    "Banahao",
    "Buenaflor",
    "Buracan",
    "Cabanoyoan",
    "Cabrera",
    "Cadulan",
    "Calabad",
    "Canomay",
    "Divisoria",
    "Gaid",
    "Gregorio Alino",
    "Magcaraguit",
    "Mambog",
    "Poblacion",
    "Rizal",
    "San Vicente",
    "Suba",
    "T.R. Yangco",
  ],
  "0504109000": [
    "Agoho",
    "Almero",
    "Baras",
    "Domorog",
    "Guadalupe",
    "Iligan",
    "Labangtaytay",
    "Labrador",
    "Libertad",
    "Magsaysay",
    "Masbaranon",
    "Poblacion",
    "Potingbato",
    "Rizal",
    "San Roque",
    "Santiago",
    "Sorosimbajan",
    "Tawad",
    "Tunga",
    "Villa",
  ],
  "0504110000": [
    "Alas",
    "Ayat",
    "Bat-Ongan",
    "Bugtong",
    "Buri",
    "Cabitan",
    "Cagmasoso",
    "Canomoy",
    "Centro",
    "Dayao",
    "Guincaiptan",
    "Laguinbanwa",
    "Lantangan",
    "Looc",
    "Mabatobato",
    "Maolingon",
    "Nailaban",
    "Nanipsan",
    "Pinamangcaan",
    "Poblacion",
    "Polo Dacu",
    "San Juan",
    "San Pablo",
    "Santa Fe",
    "Tagpu",
    "Tumalaytay",
  ],
  "0504111000": [
    "Anas",
    "Asid",
    "B. Titong",
    "Bagumbayan",
    "Bantigue",
    "Bapor (Pob.)",
    "Batuhan",
    "Bayombon",
    "Biyong",
    "Bolo",
    "Cagay",
    "Cawayan Exterior",
    "Cawayan Interior",
    "Centro (Pob.)",
    "Espinosa",
    "F. Magallanes",
    "Ibingay",
    "Igang",
    "Kalipay (Pob.)",
    "Kinamaligan",
    "Malinta",
    "Mapiña",
    "Mayngaran",
    "Nursery",
    "Pating (Pob.)",
    "Pawa",
    "Sinalongan",
    "Tugbo",
    "Ubongan Dacu",
    "Usab",
  ],
  "0504112000": [
    "Bacolod",
    "Bangad",
    "Bara",
    "Bonbon",
    "Calasuche",
    "Calumpang",
    "Capaculan",
    "Cayabon",
    "Guinluthangan",
    "Jamorawon",
    "Magsalangi",
    "Matagbac",
    "Matanglad",
    "Matiporon",
    "Moises R. Espinosa",
    "Narangasan",
    "Pamangpangon",
    "Paraiso",
    "Poblacion East",
    "Poblacion West",
    "San Antonio",
    "San Carlos",
    "Sawmill",
    "Tagbon",
    "Tawad",
    "Tigbao",
    "Tinaclipan",
  ],
  "0504113000": [
    "Baang",
    "Bagacay",
    "Balatucan",
    "Barag",
    "Dacu",
    "Fabrica",
    "Guintorelan",
    "Holjogon",
    "Lalaguna",
    "Lomocloc",
    "Luyong Catungan",
    "Mabuhay",
    "Mandali",
    "Mapuyo",
    "Marintoc",
    "Nasunduan",
    "Pinamalatican",
    "Pinamarbuhan",
    "Poblacion Dist. I",
    "Poblacion Dist. II",
    "Polot",
    "Sambulawan",
    "Santa Maria",
    "Sawmill",
    "Tabuc",
    "Tugawe",
    "Tugbo",
    "Umabay Exterior",
    "Umabay Interior",
  ],
  "0504114000": [
    "Cantorna",
    "Famosa",
    "Guinhadap",
    "Macarthur",
    "Maglambong",
    "Morocborocan",
    "Poblacion",
    "Real",
    "Rizal",
    "Santo Niño",
    "Togoron",
  ],
  "0504115000": [
    "Antipolo",
    "Banco",
    "Biga-a",
    "Bontod",
    "Buenasuerte",
    "Intusan",
    "Jose A. Abenir Sr.",
    "Maanahao",
    "Mabini",
    "Malatawan",
    "Malibas",
    "Maravilla",
    "Matugnao",
    "Miabas",
    "Nabangig",
    "Nipa",
    "Parina",
    "Piña",
    "Poblacion",
    "Salvacion",
    "San Antonio",
    "San Carlos",
    "San Isidro",
    "Santa Cruz",
  ],
  "0504116000": [
    "Alegria",
    "Buenasuerte",
    "Bugang",
    "Bugtong",
    "Bunducan",
    "Cabangrayan",
    "Calongongan",
    "Casabangan",
    "Guindawahan",
    "Labigan",
    "Lampuyang",
    "Mabuhay",
    "Palho",
    "Poblacion",
    "Salvacion",
    "Tanque",
    "Tubigan",
    "Tubog",
  ],
  "0504117000": [
    "Aguada",
    "Ban-Ao",
    "Burabod",
    "Cabangcalan",
    "Calumpang",
    "Camayabsan",
    "Daanlungsod",
    "Dangpanan",
    "Daraga",
    "Guin-Awayan",
    "Guinhan-Ayan",
    "Katipunan",
    "Libas",
    "Locso-An",
    "Luna",
    "Mahayag",
    "Mahayahay",
    "Manlut-Od",
    "Matagantang",
    "Naboctot",
    "Nagarao",
    "Nainday",
    "Naocondiot",
    "Pasiagon",
    "Pili",
    "Poblacion",
    "Puro",
    "Quibrada",
    "San Marcos",
    "Santa Cruz",
    "Taboc",
    "Tan-Awan",
    "Taverna",
    "Tubod",
    "Villa Inocencio",
  ],
  "0504118000": [
    "Altavista",
    "Bayanihan Pob.",
    "Baybaydagat Pob.",
    "Benitinan",
    "Buenasuerte",
    "Buenavista",
    "Buenos Aires",
    "Buyo",
    "Cañelas",
    "Corbada",
    "Daplian",
    "Del Rosario",
    "Ipil",
    "Lahong",
    "Lumbia",
    "Magkaipit",
    "Magsasaka Pob.",
    "Minio",
    "Pinamoghaan",
    "Progreso",
    "Resurreccion",
    "Salvacion",
    "Silangan Pob.",
    "Sowa",
    "Talisay",
    "Valparaiso",
  ],
  "0504119000": [
    "Almiñe",
    "Bagacay",
    "Bagahanglad",
    "Bartolabac",
    "Burgos",
    "Calipat-An",
    "Danao",
    "District I (Pob.)",
    "District II (Pob.)",
    "District III (Pob.)",
    "District IV (Pob.)",
    "Dorong-an Daplian",
    "Interior",
    "Jagna-an",
    "Luna",
    "Mabini",
    "Piña",
    "Roosevelt",
    "San Isidro",
    "Santa Rosa",
    "Washington",
  ],
  "0504120000": [
    "Boca Chica",
    "Bolod (Pob.)",
    "Busing",
    "Cueva",
    "Dangcalan",
    "Halabangbaybay",
    "Iniwaran",
    "Ki-Buaya",
    "Ki-Romero",
    "Laurente",
    "Mabini",
    "Mabuhay",
    "Malaking Ilog",
    "Mapanique",
    "Nazareno",
    "Pinamasingan",
    "Quintina",
    "San Jose",
    "San Pedro",
    "San Rafael",
    "Santa Cruz",
    "Terraplin (Pob.)",
  ],
  "0504121000": [
    "Arado",
    "Armenia",
    "Aurora",
    "Badling",
    "Bonifacio",
    "Buenasuerte",
    "Buenavista",
    "Campana",
    "Candelaria",
    "Centro",
    "Crossing",
    "Dapdap",
    "Del Carmen",
    "Del Rosario",
    "Libertad",
    "Mabini",
    "Mabuhay",
    "Madao",
    "Magsaysay",
    "Marcella",
    "Miaga",
    "Mongahay",
    "Morocborocan",
    "Paguihaman",
    "Panicijan",
    "Poblacion",
    "Quezon",
    "San Isidro",
    "San Jose",
    "San Mateo",
    "San Ramon",
    "San Vicente",
    "Santo Cristo",
    "Sawang",
    "Simawa",
  ],
  "0506202000": [
    "Alegria",
    "Bagacay",
    "Bangate",
    "Bugtong",
    "Cagang",
    "Fabrica",
    "Jibong",
    "Lago",
    "Layog",
    "Luneta",
    "Macabari",
    "Mapapac",
    "Olandia",
    "Paghaluban",
    "Poblacion Central",
    "Poblacion Norte",
    "Poblacion Sur",
    "Putiao",
    "San Antonio",
    "San Isidro",
    "San Ramon",
    "San Vicente",
    "Santa Cruz",
    "Santa Lourdes",
    "Tagdon",
  ],
  "0506203000": [
    "A. Bonifacio",
    "Abad Santos",
    "Aguinaldo",
    "Antipolo",
    "Beguin",
    "Benigno S. Aquino",
    "Bical",
    "Bonga",
    "Butag",
    "Cadandanan",
    "Calomagon",
    "Calpi",
    "Cocok-Cabitan",
    "Daganas",
    "Danao",
    "Dolos",
    "E. Quirino",
    "Fabrica",
    "G. Del Pilar",
    "Gate",
    "Inararan",
    "J. Gerona",
    "J.P. Laurel",
    "Jamorawon",
    "Lajong",
    "Libertad",
    "M. Roxas",
    "Magsaysay",
    "Managanaga",
    "Marinab",
    "Montecalvario",
    "N. Roque",
    "Namo",
    "Nasuje",
    "Obrero",
    "Osmeña",
    "Otavi",
    "Padre Diaz",
    "Palale",
    "Quezon",
    "R. Gerona",
    "Recto",
    "Sagrada",
    "San Francisco",
    "San Isidro",
    "San Juan Bag-o",
    "San Juan Daan",
    "San Rafael",
    "San Ramon",
    "San Vicente",
    "Santa Remedios",
    "Santa Teresita",
    "Sigad",
    "Somagongsong",
    "Taromata",
    "Zone I Pob.",
    "Zone II Pob.",
    "Zone III Pob.",
    "Zone IV Pob.",
    "Zone V Pob.",
    "Zone VI Pob.",
    "Zone VII Pob.",
    "Zone VIII Pob.",
  ],
  "0506204000": [
    "Bagacay",
    "Central (Pob.)",
    "Cogon",
    "Dancalan",
    "Dapdap (Pob.)",
    "Lalud",
    "Looban (Pob.)",
    "Mabuhay (Pob.)",
    "Madlawon (Pob.)",
    "Poctol (Pob.)",
    "Porog",
    "Sabang (Pob.)",
    "Salvacion",
    "San Antonio",
    "San Bernardo",
    "San Francisco",
    "San Isidro",
    "San Jose",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santa Barbara",
    "Sapngan (Pob.)",
    "Tinampo",
  ],
  "0506205000": [
    "Adovis (Pob.)",
    "Boton",
    "Burgos",
    "Casay",
    "Cawit",
    "Central (Pob.)",
    "Cogon",
    "Colambis",
    "Escuala",
    "Inlagadian",
    "Lungib",
    "Mabini",
    "Ponong",
    "Rizal",
    "San Antonio",
    "San Isidro",
    "San Juan",
    "San Pascual",
    "Santa Cruz",
    "Somal-ot (Pob.)",
    "Tigbao",
    "Timbayog (Pob.)",
    "Tiris",
    "Trece Martirez",
    "Tulay",
  ],
  "0506206000": [
    "Amomonting",
    "Bagalayag",
    "Bagong Sirang",
    "Bonga",
    "Buenavista",
    "Burabod",
    "Caburacan",
    "Canjela",
    "Cogon",
    "Cumadcad",
    "Dangcalan",
    "Dinapa",
    "La Union",
    "Libtong",
    "Loreto",
    "Macalaya",
    "Maracabac",
    "Mayon",
    "Maypangi",
    "Milagrosa",
    "Miluya",
    "Monte Carmelo",
    "Oras",
    "Pandan",
    "Poblacion",
    "Quirapi",
    "Saclayan",
    "Salvacion",
    "San Isidro",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Sogoy",
    "Tomalaytay",
  ],
  "0506207000": [
    "Alin",
    "Awai",
    "Banban",
    "Bandi",
    "Banuang Gurang",
    "Baras",
    "Bayawas",
    "Bororan Barangay 1 (Pob.)",
    "Cabugao",
    "Central Barangay 2 (Pob.)",
    "Cristo",
    "Dancalan",
    "De Vera",
    "Gimagaan",
    "Girawan",
    "Gogon",
    "Gura",
    "Juan Adre",
    "Lourdes",
    "Mabini",
    "Malapoc",
    "Malinao",
    "Market Site Barangay 3 (Pob.)",
    "New Maguisa",
    "Ogod",
    "Old Maguisa",
    "Orange",
    "Pangpang",
    "Parina",
    "Pawala",
    "Pinamanaan",
    "Poso Pob.",
    "Punta Waling-Waling Pob.",
    "Rawis",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Rafael",
    "San Ramon",
    "San Vicente",
    "Santa Cruz",
    "Sevilla",
    "Sibago",
    "Suguian",
    "Tagbac",
    "Tinanogan",
    "Tongdol",
    "Tres Marias",
    "Tuba",
    "Tupas",
    "Vinisitahan",
  ],
  "0506208000": [
    "Ariman",
    "Bagacay",
    "Balud Del Norte (Pob.)",
    "Balud Del Sur (Pob.)",
    "Benguet",
    "Bentuco",
    "Beriran",
    "Buenavista",
    "Bulacao",
    "Cabigaan",
    "Cabiguhan",
    "Carriedo",
    "Casili",
    "Cogon",
    "Cota Na Daco (Pob.)",
    "Dita",
    "Jupi",
    "Lapinig",
    "Luna-Candol (Pob.)",
    "Manapao",
    "Manook (Pob.)",
    "Naagtan",
    "Nato",
    "Nazareno",
    "Ogao",
    "Paco",
    "Panganiban (Pob.)",
    "Paradijon (Pob.)",
    "Patag",
    "Payawin",
    "Pinontingan (Pob.)",
    "Rizal",
    "San Ignacio",
    "Sangat",
    "Santa Ana",
    "Tabi",
    "Tagaytay",
    "Tigkiw",
    "Tiris",
    "Togawe",
    "Union",
    "Villareal",
  ],
  "0506209000": [
    "Bacolod (Pob.)",
    "Bagsangan",
    "Batang",
    "Bolos",
    "Buenavista",
    "Bulawan",
    "Carriedo",
    "Casini",
    "Cawayan",
    "Cogon",
    "Gabao",
    "Gulang-Gulang",
    "Gumapia",
    "Liang",
    "Macawayan",
    "Mapaso",
    "Monbon",
    "Patag",
    "Salvacion",
    "San Agustin (Pob.)",
    "San Isidro",
    "San Juan (Pob.)",
    "San Julian (Pob.)",
    "San Pedro",
    "Santo Domingo",
    "Tabon-Tabon",
    "Tinampo",
    "Tongdol",
  ],
  "0506210000": [
    "Anog",
    "Aroroy",
    "Bacolod",
    "Binanuahan",
    "Biriran",
    "Buraburan",
    "Calateo",
    "Calmayon",
    "Carohayon",
    "Catanagan",
    "Catanusan",
    "Cogon",
    "Embarcadero",
    "Guruyan",
    "Lajong",
    "Maalo",
    "North Poblacion",
    "Puting Sapa",
    "Rangas",
    "Sablayan",
    "Sipaya",
    "South Poblacion",
    "Taboc",
    "Tinago",
    "Tughan",
  ],
  "0506211000": [
    "Aguada Norte",
    "Aguada Sur",
    "Anibong",
    "Bacalon",
    "Bacolod",
    "Banacud",
    "Behia",
    "Biga",
    "Binisitahan del Norte",
    "Binisitahan del Sur",
    "Biton",
    "Bulala",
    "Busay",
    "Caditaan",
    "Cagbolo",
    "Cagtalaba",
    "Cawit Extension",
    "Cawit Proper",
    "Ginangra",
    "Hubo",
    "Incarizan",
    "Lapinig",
    "Magsaysay",
    "Malbog",
    "Pantalan",
    "Pawik",
    "Pili",
    "Poblacion",
    "Salvacion",
    "Santa Elena",
    "Siuton",
    "Tagas",
    "Tulatula Norte",
    "Tulatula Sur",
  ],
  "0506212000": [
    "Balocawe",
    "Banogao",
    "Banuangdaan",
    "Bariis",
    "Bolo",
    "Bon-Ot Big",
    "Bon-Ot Small",
    "Cabagahan",
    "Calayuan",
    "Calintaan",
    "Caloocan (Pob.)",
    "Calpi",
    "Camachiles (Pob.)",
    "Camcaman (Pob.)",
    "Coron-coron",
    "Culasi",
    "Gadgaron",
    "Genablan Occidental",
    "Genablan Oriental",
    "Hidhid",
    "Laboy",
    "Lajong",
    "Mambajog",
    "Manjunlad",
    "Manurabi",
    "Naburacan",
    "Paghuliran",
    "Pangi",
    "Pawa",
    "Poropandan",
    "Santa Isabel",
    "Sinalmacan",
    "Sinang-Atan",
    "Sinibaran",
    "Sisigon",
    "Sua",
    "Sulangan",
    "Tablac (Pob.)",
    "Tabunan (Pob.)",
    "Tugas",
  ],
  "0506213000": [
    "Abas",
    "Abucay",
    "Bantayan",
    "Banuyo (Pob.)",
    "Bayasong",
    "Bayawas",
    "Binanuahan (Pob.)",
    "Cabiguan",
    "Cagdongon",
    "Calongay",
    "Calpi",
    "Catamlangan",
    "Comapo-capo",
    "Danlog",
    "Dao (Pob.)",
    "Dapdap",
    "Del Rosario",
    "Esmerada",
    "Esperanza",
    "Ginablan",
    "Guiron",
    "Inang",
    "Inapugan",
    "Leona",
    "Lipason",
    "Lourdes",
    "Lubiano",
    "Lumbang",
    "Lungib",
    "Mabanate",
    "Malbog",
    "Marifosque (Pob.)",
    "Mercedes",
    "Migabod",
    "Naspi",
    "Palanas",
    "Pangpang",
    "Pinagsalog",
    "Pineda",
    "Poctol",
    "Pudo",
    "Putiao",
    "Sacnangan",
    "Salvacion",
    "San Antonio",
    "San Antonio",
    "San Jose",
    "San Rafael",
    "Santa Fe",
  ],
  "0506214000": [
    "Brillante (Pob.)",
    "Bulawan",
    "Calao",
    "Carayat",
    "Diamante",
    "Gogon",
    "Lupi",
    "Maningcay De Oro",
    "Manlabong",
    "Perlas",
    "Quidolog",
    "Rizal",
    "San Antonio",
    "San Fernando",
    "San Isidro",
    "San Juan",
    "San Rafael",
    "San Ramon",
    "Santa Lourdes",
    "Santo Domingo",
    "Talisayan",
    "Tupaz",
    "Ulag",
  ],
  "0506215000": [
    "Barangay Poblacion I",
    "Barangay Poblacion II",
    "Barangay Poblacion III",
    "Barangay Poblacion IV",
    "La Esperanza",
    "Peñafrancia",
    "Salvacion",
    "San Antonio",
    "San Bartolome",
    "San Eugenio",
    "San Isidro",
    "San Rafael",
    "San Roque",
    "San Sebastian",
  ],
  "0506216000": [
    "Abuyog",
    "Almendras-Cogon (Pob.)",
    "Balete",
    "Balogo",
    "Balogo",
    "Barayong",
    "Basud",
    "Bato",
    "Bibincahan",
    "Bitan-o/Dalipay (Pob.)",
    "Bogña",
    "Bon-Ot",
    "Bucalbucalan",
    "Buenavista",
    "Buenavista",
    "Buhatan",
    "Bulabog",
    "Burabod (Pob.)",
    "Cabarbuhan",
    "Cabid-An",
    "Cambulaga",
    "Capuy",
    "Caricaran",
    "Del Rosario",
    "Gatbo",
    "Gimaloto",
    "Guinlajon",
    "Jamislagan",
    "Macabog",
    "Maricrum",
    "Marinas",
    "Osiao",
    "Pamurayan",
    "Pangpang",
    "Panlayaan",
    "Peñafrancia",
    "Piot (Pob.)",
    "Poblacion",
    "Polvorista (Pob.)",
    "Rawis",
    "Rizal",
    "Salog (Pob.)",
    "Salvacion",
    "Salvacion",
    "Sampaloc (Pob.)",
    "San Isidro",
    "San Isidro",
    "San Juan",
    "San Juan",
    "San Pascual",
    "San Ramon",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Santa Lucia",
    "Santo Domingo",
    "Santo Niño",
    "Sawanga",
    "Sirangan (Pob.)",
    "Sugod",
    "Sulucan (Pob.)",
    "Talisay (Pob.)",
    "Ticol",
    "Tugos",
  ],
};
