/** GENERATED — Region VI: 4051 barangays across 133 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "0600401000": [
    "Cabangila",
    "Cabugao",
    "Catmon",
    "Dalipdip",
    "Ginictan",
    "Linayasan",
    "Lumaynay",
    "Lupo",
    "Man-up",
    "Odiong",
    "Poblacion",
    "Quinasay-an",
    "Talon",
    "Tibiao",
  ],
  "0600402000": [
    "Aranas",
    "Arcangel",
    "Calizo",
    "Cortes",
    "Feliciano",
    "Fulgencio",
    "Guanko",
    "Morales",
    "Oquendo",
    "Poblacion",
  ],
  "0600403000": [
    "Agbanawan",
    "Bacan",
    "Badiangan",
    "Cerrudo",
    "Cupang",
    "Daguitan",
    "Daja Norte",
    "Daja Sur",
    "Dingle",
    "Jumarap",
    "Lapnag",
    "Libas",
    "Linabuan Sur",
    "Mambog",
    "Mangan",
    "Muguing",
    "Pagsanghan",
    "Palale",
    "Poblacion",
    "Polo",
    "Polocate",
    "San Isidro",
    "Sibalew",
    "Sigcay",
    "Taba-ao",
    "Tabayon",
    "Tinapuay",
    "Torralba",
    "Ugsod",
    "Venturanza",
  ],
  "0600404000": [
    "Ambolong",
    "Angas",
    "Bay-ang",
    "Cabugao",
    "Caiyang",
    "Camaligan",
    "Camanci",
    "Ipil",
    "Lalab",
    "Lupit",
    "Magpag-ong",
    "Magubahay",
    "Mambuquiao",
    "Man-up",
    "Mandong",
    "Napti",
    "Palay",
    "Poblacion",
    "Songcolan",
    "Tabon",
  ],
  "0600405000": [
    "Alegria",
    "Bagongbayan",
    "Balusbos",
    "Bel-is",
    "Cabugan",
    "El Progreso",
    "Habana",
    "Katipunan",
    "Mayapay",
    "Nazareth",
    "Panilongan",
    "Poblacion",
    "Santander",
    "Tag-osip",
    "Tigum",
  ],
  "0600406000": [
    "Agbago",
    "Agdugayan",
    "Antipolo",
    "Aparicio",
    "Aquino",
    "Aslum",
    "Bagacay",
    "Batuan",
    "Buenavista",
    "Bugtongbato",
    "Cabugao",
    "Capilijan",
    "Colongcolong",
    "Laguinbanua",
    "Mabusao",
    "Malindog",
    "Maloco",
    "Mina-a",
    "Monlaque",
    "Naile",
    "Naisud",
    "Naligusan",
    "Ondoy",
    "Poblacion",
    "Polo",
    "Regador",
    "Rivera",
    "Rizal",
    "San Isidro",
    "San Jose",
    "Santa Cruz",
    "Tagbaya",
    "Tul-ang",
    "Unat",
    "Yawan",
  ],
  "0600407000": [
    "Andagaw",
    "Bachaw Norte",
    "Bachaw Sur",
    "Briones",
    "Buswang New",
    "Buswang Old",
    "Caano",
    "Estancia",
    "Linabuan Norte",
    "Mabilo",
    "Mobo",
    "Nalook",
    "Poblacion",
    "Pook",
    "Tigayon",
    "Tinigaw",
  ],
  "0600408000": [
    "Agcawilan",
    "Bagto",
    "Bugasongan",
    "Carugdog",
    "Cogon",
    "Ibao",
    "Mina",
    "Poblacion",
    "Santa Cruz",
    "Santa Cruz Bigaa",
    "Silakat-Nonok",
    "Tayhawan",
  ],
  "0600409000": [
    "Agmailig",
    "Alfonso XII",
    "Batobato",
    "Bonza",
    "Calacabian",
    "Calamcan",
    "Can-Awan",
    "Casit-an",
    "Dalagsa-an",
    "Guadalupe",
    "Janlud",
    "Julita",
    "Luctoga",
    "Magugba",
    "Manika",
    "Ogsip",
    "Ortega",
    "Oyang",
    "Pampango",
    "Pinonoy",
    "Poblacion",
    "Rivera",
    "Rosal",
    "Sibalew",
  ],
  "0600410000": [
    "Alaminos",
    "Alas-as",
    "Bacyang",
    "Balactasan",
    "Cabangahan",
    "Cabilawan",
    "Catabana",
    "Dit-Ana",
    "Galicia",
    "Guinatu-an",
    "Logohon",
    "Mamba",
    "Maria Cristina",
    "Medina",
    "Mercedes",
    "Napnot",
    "Pang-Itan",
    "Paningayan",
    "Panipiason",
    "Poblacion",
    "San Jose",
    "Singay",
    "Talangban",
    "Talimagao",
    "Tigbawan",
  ],
  "0600411000": [
    "Agbalogo",
    "Aglucay",
    "Alibagon",
    "Bagong Barrio",
    "Baybay",
    "Cabatanga",
    "Cajilo",
    "Calangcang",
    "Calimbajan",
    "Castillo",
    "Cayangwan",
    "Dumga",
    "Libang",
    "Mantiguib",
    "Poblacion",
    "Tibiawan",
    "Tina",
    "Tugas",
  ],
  "0600412000": [
    "Argao",
    "Balabag",
    "Balusbus",
    "Cabulihan",
    "Caticlan",
    "Cogon",
    "Cubay Norte",
    "Cubay Sur",
    "Dumlog",
    "Manoc-Manoc",
    "Motag",
    "Naasug",
    "Nabaoy",
    "Napaan",
    "Poblacion",
    "San Viray",
    "Yapak",
  ],
  "0600413000": [
    "Banaybanay",
    "Biga-a",
    "Bulabud",
    "Cabayugan",
    "Capataga",
    "Cogon",
    "Dangcalan",
    "Kinalangay Nuevo",
    "Kinalangay Viejo",
    "Lilo-an",
    "Malandayon",
    "Manhanip",
    "Navitas",
    "Osman",
    "Poblacion",
    "Rosario",
    "San Dimas",
    "San Ramon",
    "San Roque",
    "Sipac",
    "Sugnod",
    "Tambuan",
    "Tigpalas",
  ],
  "0600414000": [
    "Alimbo-Baybay",
    "Buenafortuna",
    "Buenasuerte",
    "Buenavista",
    "Gibon",
    "Habana",
    "Laserna",
    "Libertad",
    "Magallanes",
    "Matabana",
    "Nagustan",
    "Pawa",
    "Pinatuad",
    "Poblacion",
    "Rizal",
    "Solido",
    "Tagororoc",
    "Toledo",
    "Unidos",
    "Union",
  ],
  "0600415000": [
    "Candelaria",
    "Cawayan",
    "Dumaguit",
    "Fatima",
    "Guinbaliwan",
    "Jalas",
    "Jugas",
    "Lawa-an",
    "Mabilo",
    "Mataphao",
    "Ochando",
    "Pinamuk-an",
    "Poblacion",
    "Polo",
    "Puis",
    "Tambak",
  ],
  "0600416000": [
    "Albasan",
    "Aliputos",
    "Badio",
    "Bubog",
    "Bulwang",
    "Camanci Norte",
    "Camanci Sur",
    "Dongon East",
    "Dongon West",
    "Joyao-joyao",
    "Laguinbanua East",
    "Laguinbanua West",
    "Marianos",
    "Navitas",
    "Poblacion",
    "Pusiw",
    "Tabangka",
  ],
  "0600417000": [
    "Afga",
    "Baybay",
    "Dapdap",
    "Dumatad",
    "Jawili",
    "Lanipga",
    "Napatag",
    "Panayakan",
    "Poblacion",
    "Pudiot",
    "Tagas",
    "Tamalagon",
    "Tamokoe",
    "Tondog",
    "Vivo",
  ],
  "0600601000": [
    "Bayo Grande",
    "Bayo Pequeño",
    "Butuan",
    "Casay",
    "Casay Viejo",
    "Iba",
    "Igbarabatuan",
    "Igpalge",
    "Igtumarom",
    "Lisub A",
    "Lisub B",
    "Mabuyong",
    "Magdalena",
    "Nasuli C",
    "Nato",
    "Poblacion",
    "Sagua",
    "Salvacion",
    "San Francisco",
    "San Ramon",
    "San Roque",
    "Tagaytay",
    "Talisayan",
  ],
  "0600602000": [
    "Baghari",
    "Bahuyan",
    "Beri",
    "Biga-a",
    "Binangbang",
    "Binangbang Centro",
    "Binanu-an",
    "Cadiao",
    "Calapadan",
    "Capoyuan",
    "Cubay",
    "Embrangga-an",
    "Esparar",
    "Gua",
    "Idao",
    "Igpalge",
    "Igtunarum",
    "Integasan",
    "Ipil",
    "Jinalinan",
    "Lanas",
    "Langcaon",
    "Lisub",
    "Lombuyan",
    "Mablad",
    "Magtulis",
    "Marigne",
    "Mayabay",
    "Mayos",
    "Nalusdan",
    "Narirong",
    "Palma",
    "Poblacion",
    "San Antonio",
    "San Ramon",
    "Soligao",
    "Tabongtabong",
    "Tig-Alaran",
    "Yapo",
  ],
  "0600603000": [
    "Borocboroc",
    "Buenavista",
    "Concepcion",
    "Delima",
    "Ipil",
    "Maradiona",
    "Mojon",
    "Poblacion",
    "Rombang",
    "Salvacion",
    "Sinaja",
  ],
  "0600604000": [
    "Anilawan",
    "Arangote",
    "Bagtason",
    "Camangahan",
    "Centro Ilawod (Pob.)",
    "Centro Ilaya (Pob.)",
    "Centro Pojo (Pob.)",
    "Cubay North",
    "Cubay South",
    "Guija",
    "Igbalangao",
    "Igsoro",
    "Ilaures",
    "Jinalinan",
    "Lacayon",
    "Maray",
    "Paliwan",
    "Pangalcagan",
    "Sabang East",
    "Sabang West",
    "Tagudtud North",
    "Tagudtud South",
    "Talisay",
    "Tica",
    "Tono-an",
    "Yapu",
    "Zaragoza",
  ],
  "0600605000": [
    "Alegria",
    "Bacong",
    "Banago",
    "Bonbon",
    "Dawis",
    "Dionela",
    "Harigue",
    "Hininga-an",
    "Imba",
    "Masanag",
    "Poblacion",
    "Sabang",
    "Salamento",
    "Semirara",
    "Sibato",
    "Sibay",
    "Sibolo",
    "Tinogboc",
  ],
  "0600606000": [
    "Alojipan",
    "Bagacay",
    "Balac-balac",
    "Batbatan Island",
    "Batonan Norte",
    "Batonan Sur",
    "Bita",
    "Bitadton Norte",
    "Bitadton Sur",
    "Buenavista",
    "Buhi",
    "Camancijan",
    "Caridad",
    "Carit-an",
    "Centro Norte (Pob.)",
    "Centro Poblacion",
    "Centro Sur (Pob.)",
    "Condes",
    "Esperanza",
    "Fe",
    "Flores",
    "Jalandoni",
    "Janlagasi",
    "Lamputong",
    "Lipata",
    "Magsaysay",
    "Malacañang",
    "Malalison Island",
    "Maniguin",
    "Naba",
    "Osorio",
    "Paningayan",
    "Salde",
    "San Antonio",
    "San Gregorio",
    "San Juan",
    "San Luis",
    "San Pascual",
    "San Vicente",
    "Simbola",
    "Tigbobolo",
    "Tinabusan",
    "Tomao",
    "Valderama",
  ],
  "0600607000": [
    "Abaca",
    "Aras-Asan",
    "Arobo",
    "Atabay",
    "Atiotes",
    "Bagumbayan",
    "Balloscas",
    "Balud",
    "Barasanan A",
    "Barasanan B",
    "Barasanan C",
    "Bariri",
    "Camandagan",
    "Cato-ogan",
    "Danawan",
    "Diclum",
    "Fatima",
    "Gamad",
    "Igbalogo",
    "Igbangcal-A",
    "Igbangcal-B",
    "Igbangcal-C",
    "Igcabuad",
    "Igcadac",
    "Igcado",
    "Igcalawagan",
    "Igcapuyas",
    "Igcasicad",
    "Igdalaguit",
    "Igdanlog",
    "Igdurarog",
    "Igtugas",
    "Lawigan",
    "Lindero",
    "Manaling",
    "Masayo",
    "Nagsubuan",
    "Nasuli-A",
    "Opsan",
    "Paciencia",
    "Poblacion Norte",
    "Poblacion Sur",
    "Portillo",
    "Quezon",
    "Salamague",
    "Santo Tomas",
    "Tacbuyan",
    "Tene",
    "Villaflor",
    "Ysulat",
  ],
  "0600608000": [
    "Apdo",
    "Asluman",
    "Banawon",
    "Bia-an",
    "Bongbongan I-II",
    "Bongbongan III",
    "Botbot",
    "Budbudan",
    "Buhang",
    "Calacja I",
    "Calacja II",
    "Calala",
    "Cantulan",
    "Caridad",
    "Caromangay",
    "Casalngan",
    "Dangcalan",
    "Del Pilar",
    "Fabrica",
    "Funda",
    "General Fullon",
    "Gov. Evelio B. Javier",
    "Guintas",
    "Igbical",
    "Igbucagay",
    "Inabasan",
    "Ingwan-Batangan",
    "La Paz",
    "Linaban",
    "Malandog",
    "Mapatag",
    "Masanag",
    "Nalihawan",
    "Pamandayan",
    "Pasu-Jungao",
    "Piape I",
    "Piape II",
    "Piape III",
    "Pili 1, 2, 3",
    "Poblacion 1",
    "Poblacion 2",
    "Poblacion 3",
    "Poblacion 4",
    "Poblacion 5",
    "Pu-ao",
    "Suloc",
    "Villavert-Jimenez",
  ],
  "0600609000": [
    "Bagongbayan",
    "Banban",
    "Bongbongan",
    "Cabariwan",
    "Cadajug",
    "Canituan",
    "Capnayan",
    "Casit-an",
    "Guiamon",
    "Guinbanga-an",
    "Guisijan",
    "Igtadiao",
    "Intao",
    "Jaguikican",
    "Jinalinan",
    "Lactudan",
    "Latazon",
    "Laua-an",
    "Leon",
    "Liberato",
    "Lindero",
    "Liya-liya",
    "Lugta",
    "Lupa-an",
    "Magyapo",
    "Maria",
    "Mauno",
    "Maybunga",
    "Necesito",
    "Oloc",
    "Omlot",
    "Pandanan",
    "Paningayan",
    "Pascuala",
    "Poblacion",
    "San Ramon",
    "Santiago",
    "Tibacan",
    "Tigunhao",
    "Virginia",
  ],
  "0600610000": [
    "Barusbus",
    "Bulanao",
    "Centro Este (Pob.)",
    "Centro Weste (Pob.)",
    "Codiong",
    "Cubay",
    "Igcagay",
    "Inyawan",
    "Lindero",
    "Maramig",
    "Pajo",
    "Panangkilon",
    "Paz",
    "Pucio",
    "San Roque",
    "Taboc",
    "Tinigbas",
    "Tinindugan",
    "Union",
  ],
  "0600611000": [
    "Aracay",
    "Badiangan",
    "Bagumbayan",
    "Baybay",
    "Botbot",
    "Buang",
    "Cabugao",
    "Candari",
    "Carmen",
    "Centro Norte (Pob.)",
    "Centro Sur (Pob.)",
    "Dionela",
    "Dumrog",
    "Duyong",
    "Fragante",
    "Guia",
    "Idiacacan",
    "Jinalinan",
    "Luhod-Bayang",
    "Maadios",
    "Mag-aba",
    "Napuid",
    "Nauring",
    "Patria",
    "Perfecta",
    "San Andres",
    "San Joaquin",
    "Santa Ana",
    "Santa Cruz",
    "Santa Fe",
    "Santo Rosario",
    "Talisay",
    "Tingib",
    "Zaldivar",
  ],
  "0600612000": [
    "Alvañiz",
    "Amparo",
    "Apgahan",
    "Aureliana",
    "Badiangan",
    "Bernaldo A. Julagting",
    "Carit-an",
    "Cuyapiao",
    "Gella",
    "Igbarawan",
    "Igbobon",
    "Igburi",
    "La Rioja",
    "Mabasa",
    "Macarina",
    "Magarang",
    "Magsaysay",
    "Padang",
    "Pandanan",
    "Patlabawon",
    "Poblacion",
    "Quezon",
    "Salaguiawan",
    "Samalague",
    "San Rafael",
    "Tamayoc",
    "Tigbalogo",
    "Tobias Fornier",
    "Villa Crespo",
    "Villa Cruz",
    "Villa Elio",
    "Villa Flores",
    "Villa Laua-an",
    "Villa Sal",
    "Villa Salomon",
    "Vista Alegre",
  ],
  "0600613000": [
    "Atabay",
    "Badiang",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Bariri",
    "Bugarot",
    "Cansadan",
    "Durog",
    "Funda-Dalipe",
    "Igbonglo",
    "Inabasan",
    "Madrangca",
    "Magcalon",
    "Malaiba",
    "Maybato Norte",
    "Maybato Sur",
    "Mojon",
    "Pantao",
    "San Angel",
    "San Fernando",
    "San Pedro",
    "Supa",
  ],
  "0600614000": [
    "Agricula",
    "Alegria",
    "Aningalan",
    "Atabay",
    "Bagumbayan",
    "Baladjay",
    "Banbanan",
    "Barangbang",
    "Bawang",
    "Bugo",
    "Bulan-bulan",
    "Cabiawan",
    "Cabunga-an",
    "Cadolonan",
    "Carawisan I",
    "Carawisan II",
    "Carmelo I",
    "Carmelo II",
    "General Fullon",
    "General Luna",
    "Iguirindon",
    "Insubuan",
    "La Union",
    "Lapak",
    "Lumpatan",
    "Magdalena",
    "Maragubdub",
    "Nagbangi I",
    "Nagbangi II",
    "Nasuli",
    "Orquia",
    "Osorio I",
    "Osorio II",
    "Panpanan I",
    "Panpanan II",
    "Poblacion",
    "Ramon Magsaysay",
    "Rizal",
    "San Rafael",
    "Sinundolan",
    "Sumaray",
    "Trinidad",
    "Tubudan",
    "Vilvar",
    "Walker",
  ],
  "0600615000": [
    "Abiera",
    "Aguila",
    "Alegre",
    "Aras-Asan",
    "Bacalan",
    "Callan",
    "Idio",
    "Nauhon",
    "P. Javier",
    "Poblacion",
  ],
  "0600616000": [
    "Alangan",
    "Bari",
    "Biga-a",
    "Bongbongan I",
    "Bongbongan II",
    "Bongsod",
    "Bontol",
    "Bugnay",
    "Bulalacao",
    "Cabanbanan",
    "Cabariuan",
    "Cabladan",
    "Cadoldolan",
    "Calo-oy",
    "Calog",
    "Catmon",
    "Catungan I",
    "Catungan II",
    "Catungan III",
    "Catungan IV",
    "Cubay-Napultan",
    "Cubay-Sermon",
    "District I (Pob.)",
    "District II (Pob.)",
    "District III (Pob.)",
    "District IV (Pob.)",
    "Egaña",
    "Esperanza I",
    "Esperanza II",
    "Esperanza III",
    "Igcococ",
    "Igdagmay",
    "Igdalaquit",
    "Iglanot",
    "Igpanolong",
    "Igparas",
    "Igsuming",
    "Ilabas",
    "Imparayan",
    "Inabasan",
    "Indag-an",
    "Initan",
    "Insarayan",
    "Lacaron",
    "Lagdo",
    "Lambayagan",
    "Luna",
    "Luyang",
    "Maasin",
    "Mabini",
    "Millamena",
    "Mojon",
    "Nagdayao",
    "Nazareth",
    "Odiong",
    "Olaga",
    "Pangpang",
    "Panlagangan",
    "Pantao",
    "Pasong",
    "Pis-Anan",
    "Rombang",
    "Salvacion",
    "San Juan",
    "Sido",
    "Solong",
    "Tabongtabong",
    "Tig-Ohot",
    "Tigbalua I",
    "Tigbalua II",
    "Tordesillas",
    "Tulatula",
    "Valentin Grasparil",
    "Villafont",
    "Villahermosa",
    "Villar",
  ],
  "0600617000": [
    "Alegre",
    "Amar",
    "Bandoja",
    "Castillo",
    "Esparagoza",
    "Importante",
    "La Paz",
    "Malabor",
    "Martinez",
    "Natividad",
    "Pitac",
    "Poblacion",
    "Salazar",
    "San Francisco Norte",
    "San Francisco Sur",
    "San Isidro",
    "Santa Ana",
    "Santa Justa",
    "Santo Rosario",
    "Tigbaboy",
    "Tuno",
  ],
  "0600618000": [
    "Alon",
    "Bakiang",
    "Binanogan",
    "Borocboroc",
    "Bugnay",
    "Buluangan I",
    "Buluangan II",
    "Bunsod",
    "Busog",
    "Cananghan",
    "Canipayan",
    "Cansilayan",
    "Culyat",
    "Iglinab",
    "Igmasandig",
    "Lublub",
    "Manlacbo",
    "Pandanan",
    "San Agustin",
    "Takas (Pob.)",
    "Tigmamale",
    "Ubos (Pob.)",
  ],
  "0601901000": [
    "Agcabugao",
    "Agdahon",
    "Agnaga",
    "Angub",
    "Balingasag",
    "Bito-on Ilawod",
    "Bito-on Ilaya",
    "Bun-od",
    "Carataya",
    "Lunayan",
    "Mahabang Sapa",
    "Mahunodhunod",
    "Maindang",
    "Mainit",
    "Malagab-i",
    "Nagba",
    "Poblacion Ilawod",
    "Poblacion Ilaya",
    "Poblacion Takas",
    "Puti-an",
    "San Antonio",
    "Sinabsaban",
  ],
  "0601902000": [
    "Aganan",
    "Agtambi",
    "Agtanguay",
    "Balucuan",
    "Bita",
    "Centro",
    "Daplas",
    "Duyoc",
    "Ilas Sur",
    "Lacaron",
    "Malonoy",
    "Manhoy",
    "Mapulang Bato",
    "Matagnop",
    "Nasunogan",
    "Poblacion Ilawod",
    "Poblacion Ilaya",
    "Quinabcaban",
    "Quinayuya",
    "San Agustin",
  ],
  "0601903000": [
    "Concepcion",
    "Consolacion",
    "Dolores",
    "Duran",
    "Poblacion",
    "San Agustin",
    "San Jose",
    "San Martin",
    "San Miguel",
    "San Rafael",
    "San Roque",
    "Santa Carmen",
    "Santa Cruz",
    "Santa Monica",
    "Santa Rita",
    "Santa Teresa",
    "Santo Angel",
    "Santo Niño",
    "Santo Rosario",
  ],
  "0601904000": [
    "Agbatuan",
    "Aglalana",
    "Aglanot",
    "Agsirab",
    "Alipasiawan",
    "Astorga",
    "Bayog",
    "Bungsuan",
    "Calapawan",
    "Codingle",
    "Cubi",
    "Dacuton",
    "Dangula",
    "Gibato",
    "Guinotos",
    "Jambad",
    "Janguslob",
    "Lawaan",
    "Malonoy",
    "Nagsulang",
    "Ongol Ilawod",
    "Ongol Ilaya",
    "Poblacion Ilawod",
    "Poblacion Ilaya",
    "Sagrada Familia",
    "Salcedo",
    "San Juan",
    "Sibariwan",
    "Tamulalod",
    "Taslan",
    "Tina",
    "Tinaytayan",
    "Traciano",
  ],
  "0601905000": [
    "Agmalobo",
    "Agustin Navarra",
    "Balaring",
    "Basiao",
    "Cabugao",
    "Cudian",
    "Ilaya-Ivisan",
    "Malocloc Norte",
    "Malocloc Sur",
    "Matnog",
    "Mianay",
    "Ondoy",
    "Poblacion Norte",
    "Poblacion Sur",
    "Santa Cruz",
  ],
  "0601906000": [
    "Agambulong",
    "Agbun-od",
    "Agcagay",
    "Aglibacao",
    "Agloloway",
    "Bayebaye",
    "Caridad",
    "Esperanza",
    "Fe",
    "Ganzon",
    "Guintas",
    "Igang",
    "Jaena Norte",
    "Jaena Sur",
    "Jagnaya",
    "Lapaz",
    "Linambasan",
    "Lucero",
    "Maantol",
    "Masgrau",
    "Milan",
    "Molet",
    "Pangabat",
    "Pangabuan",
    "Pasol-o",
    "Poblacion",
    "San Jose",
    "San Juan",
    "San Vicente",
    "Santo Rosario",
  ],
  "0601907000": [
    "Aglimocon",
    "Alasaging",
    "Alayunan",
    "Balighot",
    "Batabat",
    "Bongbongan",
    "Cabungahan",
    "Canapian",
    "Carataya",
    "Duluan",
    "East Villaflores",
    "Fernandez",
    "Guinbi-alan",
    "Indayagan",
    "Jebaca",
    "Maalan",
    "Manayupit",
    "New Guia",
    "Old Guia",
    "Palaguian",
    "Parallan",
    "Piña",
    "Poblacion Ilawod",
    "Poblacion Ilaya",
    "Poblacion Tabuc",
    "Quevedo",
    "Quinabonglan",
    "Quinat-uyan",
    "Salgan",
    "Tapulang",
    "Tuburan",
    "West Villaflores",
  ],
  "0601908000": [
    "Atiplo",
    "Balat-an",
    "Balit",
    "Batiano",
    "Bating",
    "Bato Bato",
    "Baye",
    "Bergante",
    "Bula",
    "Bunga",
    "Bungsi",
    "Burias",
    "Caidquid",
    "Cala-agus",
    "Libo-o",
    "Manibad",
    "Maralag",
    "Najus-an",
    "Pangpang Norte",
    "Pangpang Sur",
    "Pinay",
    "Poblacion Proper",
    "Poblacion Tabuc",
    "Sinondojan",
    "Tugas",
    "Tumalalud",
  ],
  "0601909000": [
    "Agbalo",
    "Agbanban",
    "Agojo",
    "Anhawon",
    "Bagacay",
    "Bago Chiquito",
    "Bago Grande",
    "Bahit",
    "Bantique",
    "Bato",
    "Binangig",
    "Binantuan",
    "Bonga",
    "Buntod",
    "Butacal",
    "Cabugao Este",
    "Cabugao Oeste",
    "Calapawan",
    "Calitan",
    "Candual",
    "Cogon",
    "Daga",
    "Ilamnay",
    "Jamul-awon",
    "Lanipga",
    "Lat-Asan",
    "Libon",
    "Linao",
    "Linateran",
    "Lomboy",
    "Lus-Onan",
    "Magubilan",
    "Navitas",
    "Pawa",
    "Pili",
    "Poblacion Ilawod",
    "Poblacion Ilaya",
    "Poblacion Tabuc",
    "Talasa",
    "Tanza Norte",
    "Tanza Sur",
    "Tico",
  ],
  "0601910000": [
    "Agbabadiang",
    "Agkilo",
    "Agloway",
    "Ambilay",
    "Bahit",
    "Balatucan",
    "Banga-an",
    "Cabangahan",
    "Cabugao",
    "Cadio",
    "Cala-an",
    "Capagao",
    "Cogon",
    "Conciencia",
    "Ensenagan",
    "Intampilan",
    "Pasugue",
    "Poblacion Ilawod",
    "Poblacion Ilaya",
    "Quios",
    "Salocon",
    "Tabuc Norte",
    "Tabuc Sur",
    "Timpas",
    "Tincupon",
    "Tinigban",
  ],
  "0601911000": [
    "Balogo",
    "Binaobawan",
    "Blasco",
    "Casanayan",
    "Cayus",
    "Dayhagan",
    "Dulangan",
    "Monteflor",
    "Natividad",
    "Olalo",
    "Poblacion",
    "Rosario",
    "San Antonio",
    "San Blas",
    "San Esteban",
    "San Fernando",
    "San Nicolas",
    "San Pedro",
    "San Ramon",
    "San Silvestre",
    "Santa Fe",
    "Sinamongan",
    "Tabun-acan",
    "Yating",
  ],
  "0601912000": [
    "Agbanog",
    "Agdalipe",
    "Ameligan",
    "Bailan",
    "Banate",
    "Bantigue",
    "Binuntucan",
    "Cabugao",
    "Gabuc",
    "Guba",
    "Hipona",
    "Ilawod (Pob.)",
    "Ilaya (Pob.)",
    "Intungcan",
    "Jolongajog",
    "Lantangan",
    "Linampongan",
    "Malag-it",
    "Manapao",
    "Rizal",
    "San Pedro",
    "Solo",
    "Sublangon",
    "Tabuc",
    "Tacas",
    "Yatingan",
  ],
  "0601913000": [
    "Aranguel",
    "Badiangon",
    "Bayuyan",
    "Cabugcabug",
    "Carmencita",
    "Cubay",
    "Culilang",
    "Goce",
    "Hanglid",
    "Ibaca",
    "Madulano",
    "Manoling",
    "Marita",
    "Pandan",
    "Pantalan Cabugcabug",
    "Pinamihagan",
    "Poblacion",
    "Pondol",
    "Quiajo",
    "Sangkal",
    "Santo Niño",
    "Vizcaya",
  ],
  "0601914000": [
    "Adlawan",
    "Bago",
    "Balijuagan",
    "Banica",
    "Barra",
    "Bato",
    "Baybay",
    "Bolo",
    "Cabugao",
    "Cagay",
    "Cogon",
    "Culajao",
    "Culasi",
    "Dayao",
    "Dinginan",
    "Dumolog",
    "Gabu-an",
    "Inzo Arnaldo Village",
    "Jumaguicjic",
    "Lanot",
    "Lawa-an",
    "Libas",
    "Liong",
    "Loctugan",
    "Lonoy",
    "Milibili",
    "Mongpong",
    "Olotayan",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Poblacion IX",
    "Poblacion V",
    "Poblacion VI",
    "Poblacion VII",
    "Poblacion VIII",
    "Poblacion X",
    "Poblacion XI",
    "Punta Cogon",
    "Punta Tabuc",
    "San Jose",
    "Sibaguan",
    "Talon",
    "Tanque",
    "Tanza",
    "Tiza",
  ],
  "0601915000": [
    "Agsilab",
    "Agtatacay Norte",
    "Agtatacay Sur",
    "Bilao",
    "Damayan",
    "Dapdapan",
    "Lonoy",
    "Majanlud",
    "Maninang",
    "Poblacion",
  ],
  "0601916000": [
    "Acbo",
    "Amaga",
    "Balucuan",
    "Bangonbangon",
    "Capuyhan",
    "Cogon",
    "Dayhagon",
    "Guintas",
    "Malapad Cogon",
    "Mangoso",
    "Mansacul",
    "Matangcong",
    "Matinabus",
    "Mianay",
    "Oyong",
    "Pagbunitan",
    "Parian",
    "Pinamalatican",
    "Poblacion Norte",
    "Poblacion Sur",
    "Tawog",
  ],
  "0601917000": [
    "Abangay",
    "Acuña",
    "Agcococ",
    "Aglinab",
    "Aglupacan",
    "Agpalali",
    "Apero",
    "Artuz",
    "Bag-Ong Barrio",
    "Bato-bato",
    "Buri",
    "Camburanan",
    "Candelaria",
    "Carida",
    "Cristina",
    "Da-an Banwa",
    "Da-an Norte",
    "Da-an Sur",
    "Garcia",
    "Gebio-an",
    "Hilwan",
    "Initan",
    "Katipunan",
    "Lagdungan",
    "Lahug",
    "Libertad",
    "Mabini",
    "Maliao",
    "Malitbog",
    "Minan",
    "Nayawan",
    "Poblacion",
    "Rizal Norte",
    "Rizal Sur",
    "Roosevelt",
    "Roxas",
    "Salong",
    "San Antonio",
    "San Francisco",
    "San Jose",
    "San Julian",
    "San Miguel Ilawod",
    "San Miguel Ilaya",
    "San Nicolas",
    "San Pedro",
    "San Roque",
    "San Vicente",
    "Santa Ana",
    "Santa Petronila",
    "Senonod",
    "Siya",
    "Switch",
    "Tabon",
    "Tacayan",
    "Taft",
    "Taganghin",
    "Taslan",
    "Wright",
  ],
  "0603001000": [
    "Adcadarao",
    "Agbobolo",
    "Badiangan",
    "Barrido",
    "Bato Biasong",
    "Bay-ang",
    "Bucana Bunglas",
    "Central",
    "Culasi",
    "Lanjagan",
    "Luca",
    "Malayu-an",
    "Mangorocoro",
    "Nasidman",
    "Pantalan Nabaye",
    "Pantalan Navarro",
    "Pedada",
    "Pili",
    "Pinantan Diel",
    "Pinantan Elizalde",
    "Pinay Espinosa",
    "Poblacion",
    "Progreso",
    "Puente Bunglas",
    "Punta Buri",
    "Rojas",
    "San Antonio",
    "Santo Rosario",
    "Silagon",
    "Tagubanhan",
    "Taguhangin",
    "Tanduyan",
    "Tipacla",
    "Tubogan",
  ],
  "0603002000": [
    "Abang-abang",
    "Agsing",
    "Atabay",
    "Ba-ong",
    "Bagsakan",
    "Baguingin-Lanot",
    "Bagumbayan-Ilajas",
    "Balabago",
    "Ban-ag",
    "Bancal",
    "Binalud",
    "Bugang",
    "Buhay",
    "Bulod",
    "Cabacanan Proper",
    "Cabacanan Rizal",
    "Cagay",
    "Coline",
    "Coline-Dalag",
    "Cunsad",
    "Cuyad",
    "Dalid",
    "Dao",
    "Gines",
    "Ginomoy",
    "Ingwan",
    "Laylayan",
    "Lico",
    "Luan-luan",
    "Malamboy-Bondolan",
    "Malamhay",
    "Mambawi",
    "Manasa",
    "Manduyog",
    "Pajo",
    "Pianda-an Norte",
    "Pianda-an Sur",
    "Poblacion",
    "Punong",
    "Quinaspan",
    "Sinamay",
    "Sulong",
    "Taban-Manguining",
    "Tabug",
    "Tarug",
    "Tugaslon",
    "Ubodan",
    "Ugbo",
    "Ulay-Bugang",
    "Ulay-Hinablan",
    "Umingan",
  ],
  "0603003000": [
    "Agbatuan",
    "Badiang",
    "Balabag",
    "Balunos",
    "Cag-an",
    "Camiros",
    "Dangula-an",
    "Guipis",
    "Manganese",
    "Medina",
    "Mostro",
    "Palaypay",
    "Pantalan",
    "Poblacion",
    "Sambag Culob",
    "San Carlos",
    "San Juan Crisostomo",
    "Santa Rita",
    "Santo Rosario",
    "Serallo",
    "Vista Alegre",
  ],
  "0603004000": [
    "Agusipan",
    "Astorga",
    "Bingauan",
    "Bita-oyan",
    "Botong",
    "Budiaue",
    "Cabanga-an",
    "Cabayogan",
    "Calansanan",
    "Catubig",
    "Guinawahan",
    "Ilongbukid",
    "Indorohan",
    "Iniligan",
    "Latawan",
    "Linayuan",
    "Mainguit",
    "Malublub",
    "Manaolan",
    "Mapili Grande",
    "Mapili Sanjo",
    "Odiongan",
    "Poblacion",
    "San Julian",
    "Sariri",
    "Sianon",
    "Sinuagan",
    "Talaba",
    "Tamocol",
    "Teneclan",
    "Tina",
  ],
  "0603005000": [
    "Aranjuez",
    "Bacolod",
    "Balanti-an",
    "Batuan",
    "Cabalic",
    "Camambugan",
    "Dolores",
    "Gimamanay",
    "Ipil",
    "Kinalkalan",
    "Lawis",
    "Malapoc",
    "Mamhut Norte",
    "Mamhut Sur",
    "Maya",
    "Pani-an",
    "Poblacion Norte",
    "Poblacion Sur",
    "Quiasan",
    "Salong",
    "Salvacion",
    "Tingui-an",
    "Zaragosa",
  ],
  "0603006000": [
    "Alacaygan",
    "Bariga",
    "Belen",
    "Bobon",
    "Bularan",
    "Carmelo",
    "De La Paz",
    "Dugwakan",
    "Fuentes*",
    "Juanico",
    "Libertad",
    "Magdalo",
    "Managopaya",
    "Merced",
    "Poblacion",
    "San Salvador",
    "Talokgangan",
    "Zona Sur",
  ],
  "0603007000": [
    "Acuit",
    "Agcuyawan Calsada",
    "Agcuyawan Pulo",
    "Bagongbong",
    "Baras",
    "Bungca",
    "Cabilauan",
    "Cruz",
    "Guintas",
    "Igbong",
    "Ilaud Poblacion",
    "Ilaya Poblacion",
    "Jalaud",
    "Lagubang",
    "Lanas",
    "Lico-an",
    "Linao",
    "Monpon",
    "Palaciawan",
    "Patag",
    "Salihid",
    "So-ol",
    "Sohoton",
    "Tabuc-Suba",
    "Tabucan",
    "Talisay",
    "Tinorian",
    "Tiwi",
    "Tubungan",
  ],
  "0603008000": [
    "Bugnay",
    "California",
    "De la Peña",
    "Del Pilar",
    "General Luna",
    "La Fortuna",
    "Lipata",
    "Natividad",
    "Nueva Invencion",
    "Nueva Sevilla",
    "Poblacion",
    "Puerto Princesa",
    "Rizal",
    "San Antonio",
    "San Fernando",
    "San Francisco",
    "San Geronimo",
    "San Juan",
    "San Lucas",
    "San Miguel",
    "San Roque",
    "Santiago",
    "Santo Domingo",
    "Santo Tomas",
    "Ugasan",
    "Vista Alegre",
  ],
  "0603009000": [
    "Alapasco",
    "Alinsolong",
    "Banban",
    "Batad Viejo",
    "Binon-an",
    "Bolhog",
    "Bulak Norte",
    "Bulak Sur",
    "Cabagohan",
    "Calangag",
    "Caw-i",
    "Drancalan",
    "Embarcadero",
    "Hamod",
    "Malico",
    "Nangka",
    "Pasayan",
    "Poblacion",
    "Quiazan Florete",
    "Quiazan Lopez",
    "Salong",
    "Santa Ana",
    "Tanao",
    "Tapi-an",
  ],
  "0603010000": [
    "Agba-o",
    "Alabidhan",
    "Bulabog",
    "Cairohan",
    "Guinhulacan",
    "Inamyungan",
    "Malitbog Ilawod",
    "Malitbog Ilaya",
    "Ngingi-an",
    "Poblacion",
    "Quinangyana",
    "Quinar-Upan",
    "Tapacon",
    "Tubod",
  ],
  "0603012000": [
    "Acao",
    "Amerang",
    "Amurao",
    "Anuang",
    "Ayaman",
    "Ayong",
    "Bacan",
    "Balabag",
    "Baluyan",
    "Banguit",
    "Bulay",
    "Cadoldolan",
    "Cagban",
    "Calawagan",
    "Calayo",
    "Duyanduyan",
    "Gaub",
    "Gines Interior",
    "Gines Patag",
    "Guibuangan Tigbauan",
    "Inabasan",
    "Inaca",
    "Inaladan",
    "Ingas",
    "Ito Norte",
    "Ito Sur",
    "Janipaan Central",
    "Janipaan Este",
    "Janipaan Oeste",
    "Janipaan Olo",
    "Jelicuon Lusaya",
    "Jelicuon Montinola",
    "Lag-an",
    "Leong",
    "Lutac",
    "Manguna",
    "Maraguit",
    "Morubuan",
    "Pacatin",
    "Pagotpot",
    "Pamul-Ogan",
    "Pamuringao Garrido",
    "Pamuringao Proper",
    "Pungtod",
    "Puyas",
    "Salacay",
    "Sulanga",
    "Tabucan",
    "Tacdangan",
    "Talanghauan",
    "Tigbauan Road",
    "Tinio-an",
    "Tiring",
    "Tupol Central",
    "Tupol Este",
    "Tupol Oeste",
    "Tuy-an",
    "Zone I Pob.",
    "Zone II Pob.",
    "Zone III Pob.",
    "Zone IV Pob.",
    "Zone IX Pob.",
    "Zone V Pob.",
    "Zone VI Pob.",
    "Zone VII Pob.",
    "Zone VIII Pob.",
    "Zone X Pob.",
    "Zone XI Pob.",
  ],
  "0603013000": [
    "Agcalaga",
    "Aglibacao",
    "Aglonok",
    "Alibunan",
    "Badlan Grande",
    "Badlan Pequeño",
    "Badu",
    "Baje San Julian",
    "Balaticon",
    "Banban Grande",
    "Banban Pequeño",
    "Barrio Calinog",
    "Binolosan Grande",
    "Binolosan Pequeño",
    "Cabagiao",
    "Cabugao",
    "Cahigon",
    "Camalongo",
    "Canabajan",
    "Caratagan",
    "Carvasana",
    "Dalid",
    "Datagan",
    "Gama Grande",
    "Gama Pequeño",
    "Garangan",
    "Guinbonyugan",
    "Guiso",
    "Hilwan",
    "Impalidan",
    "Ipil",
    "Jamin-ay",
    "Lampaya",
    "Libot",
    "Lonoy",
    "Malag-it",
    "Malaguinabot",
    "Malapawe",
    "Malitbog Centro",
    "Mambiranan",
    "Manaripay",
    "Marandig",
    "Masaroy",
    "Maspasan",
    "Nalbugan",
    "Owak",
    "Poblacion Centro",
    "Poblacion Delgado",
    "Poblacion Ilaya",
    "Poblacion Rizal Ilaud",
    "San Nicolas",
    "Simsiman",
    "Supanga",
    "Tabucan",
    "Tahing",
    "Tibiao",
    "Tigbayog",
    "Toyungan",
    "Ulayan",
  ],
  "0603014000": [
    "Abong",
    "Alipata",
    "Asluman",
    "Bancal",
    "Barangcalan",
    "Barosbos",
    "Binuluangan",
    "Bito-on",
    "Bolo",
    "Buaya",
    "Buenavista",
    "Cabilao Grande",
    "Cabilao Pequeño",
    "Cabuguana",
    "Cawayan",
    "Dayhagan",
    "Gabi",
    "Granada",
    "Guinticgan",
    "Isla De Cana",
    "Lantangan",
    "Manlot",
    "Nalumsan",
    "Pantalan",
    "Poblacion",
    "Punta",
    "Punta Batuanan",
    "San Fernando",
    "Tabugon",
    "Talingting",
    "Tarong",
    "Tinigban",
    "Tupaz",
  ],
  "0603015000": [
    "Aglosong",
    "Agnaga",
    "Bacjawan Norte",
    "Bacjawan Sur",
    "Bagongon",
    "Batiti",
    "Botlog",
    "Calamigan",
    "Dungon",
    "Igbon",
    "Jamul-Awon",
    "Lo-ong",
    "Macalbang",
    "Macatunao",
    "Malangabang",
    "Maliogliog",
    "Niño",
    "Nipa",
    "Plandico",
    "Poblacion",
    "Polopina",
    "Salvacion",
    "Talotu-an",
    "Tambaliza",
    "Tamis-ac",
  ],
  "0603016000": [
    "Abangay",
    "Agsalanan",
    "Agtatacay",
    "Alegria",
    "Bongloy",
    "Buenavista",
    "Caguyuman",
    "Calicuang",
    "Camambugan",
    "Dawis",
    "Ginalinan Nuevo",
    "Ginalinan Viejo",
    "Gutao",
    "Ilajas",
    "Libo-o",
    "Licu-an",
    "Lincud",
    "Matangharon",
    "Moroboro",
    "Namatay",
    "Nazuni",
    "Pandan",
    "Poblacion",
    "Potolan",
    "San Jose",
    "San Matias",
    "Siniba-an",
    "Tabugon",
    "Tambunac",
    "Tanghawan",
    "Tiguib",
    "Tinocuan",
    "Tulatula-an",
  ],
  "0603017000": [
    "Agutayan",
    "Angare",
    "Anjawan",
    "Baac",
    "Bagongbong",
    "Balangigan",
    "Balingasag",
    "Banugan",
    "Batuan",
    "Bita",
    "Buenavista",
    "Bugtongan",
    "Cabudian",
    "Calaca-an",
    "Calang",
    "Calawinan",
    "Capaycapay",
    "Capuling",
    "Catig",
    "Dila-an",
    "Fundacion",
    "Inadlawan",
    "Jagdong",
    "Jaguimit",
    "Lacadon",
    "Luag",
    "Malusgod",
    "Maribuyong",
    "Minanga",
    "Monpon",
    "Navalas",
    "Pader",
    "Pandan",
    "Poblacion A",
    "Poblacion B",
    "Poblacion C",
    "Poblacion D",
    "Ponong Grande",
    "Ponong Pequeño",
    "Purog",
    "Romblon",
    "San Isidro",
    "Santo Niño",
    "Sawe",
    "Taminla",
    "Tinocuan",
    "Tipolo",
  ],
  "0603018000": [
    "Aurora-del Pilar (Pob.)",
    "Bacay",
    "Bacong",
    "Balabag",
    "Balud",
    "Bantud",
    "Bantud Fabrica",
    "Baras",
    "Barasan",
    "Basa-Mabini Bonifacio (Pob.)",
    "Bolilao",
    "Buenaflor Embarkadero (Pob.)",
    "Burgos-Regidor (Pob.)",
    "Calao",
    "Cali",
    "Cansilayan",
    "Capaliz",
    "Cayos",
    "Compayan",
    "Dacutan",
    "Ermita",
    "Ilaya 1st",
    "Ilaya 2nd",
    "Ilaya 3rd",
    "Jardin",
    "Lacturan",
    "Lopez Jaena - Rizal (Pob.)",
    "Managuit",
    "Maquina",
    "Nanding Lopez",
    "Pagdugue",
    "Paloc Bigque",
    "Paloc Sool",
    "Patlad",
    "Pd Monfort North",
    "Pd Monfort South",
    "Pulao",
    "Rosario",
    "Sapao",
    "Sulangan",
    "Tabucan",
    "Talusan",
    "Tambobo",
    "Tamboilan",
    "Victorias",
  ],
  "0603019000": [
    "Bayas",
    "Bayuyan",
    "Botongon",
    "Bulaqueña",
    "Calapdan",
    "Cano-an",
    "Daan Banua",
    "Daculan",
    "Gogo",
    "Jolog",
    "Loguingot",
    "Lonoy",
    "Lumbia",
    "Malbog",
    "Manipulon",
    "Pa-on",
    "Poblacion Zone 1",
    "Poblacion Zone II",
    "Poblacion Zone III",
    "San Roque",
    "Santa Ana",
    "Tabu-an",
    "Tacbuyan",
    "Tanza",
    "Villa Pani-an",
  ],
  "0603020000": [
    "Anono-o",
    "Bacong",
    "Bagumbayan Pob.",
    "Balantad-Carlos Fruto (Pob.)",
    "Baras",
    "Binanua-an",
    "Bongol San Miguel",
    "Bongol San Vicente",
    "Bulad",
    "Buluangan",
    "Burgos-Gengos (Pob.)",
    "Cabasi",
    "Cabubugan",
    "Calampitao",
    "Camangahan",
    "Generosa-Cristobal Colon (Pob.)",
    "Gerona-Gimeno (Pob.)",
    "Girado-Magsaysay (Pob.)",
    "Gotera (Pob.)",
    "Igcocolo",
    "Iyasan",
    "Libo-on Gonzales (Pob.)",
    "Lubacan",
    "Nahapay",
    "Nalundan",
    "Nanga",
    "Nito-an Lupsag",
    "Particion",
    "Pescadores (Pob.)",
    "Rizal-Tuguisan (Pob.)",
    "Santa Rosa-Laguna",
    "Sipitan-Badiang",
    "Torreblanca-Blumentritt (Pob.)",
  ],
  "0603021000": [
    "Alameda",
    "Amorogtong",
    "Anilawan",
    "Bagacay",
    "Bagacayan",
    "Bagay",
    "Balibagan",
    "Barangay 1 Poblacion",
    "Barangay 2 Poblacion",
    "Barangay 3 Poblacion",
    "Barangay 4 Poblacion",
    "Barangay 5 Poblacion",
    "Barangay 6 Poblacion",
    "Barasan",
    "Binanua-an",
    "Boclod",
    "Buenavista",
    "Buga",
    "Bugnay",
    "Calampitao",
    "Cale",
    "Catiringan",
    "Corucuan",
    "Igcabugao",
    "Igpigus",
    "Igtalongon",
    "Indaluyon",
    "Jovellar",
    "Kinagdan",
    "Lab-on",
    "Lacay Dol-Dol",
    "Lumangan",
    "Lutungan",
    "Mantangon",
    "Mulangan",
    "Pasong",
    "Passi",
    "Pinaopawan",
    "Riro-an",
    "San Ambrosio",
    "Santa Barbara",
    "Signe",
    "Tabiac",
    "Talayatay",
    "Taytay",
    "Tigbanaba",
  ],
  "0603023000": [
    "Abangay",
    "Agcarope",
    "Aglobong",
    "Aguingay",
    "Anhawan",
    "Aquino Nobleza East (Pob.)",
    "Aquino Nobleza West (Pob.)",
    "Atimonan",
    "Balanac",
    "Barasalon",
    "Bongol",
    "Cabantog",
    "Calmay",
    "Canawili",
    "Canawillian",
    "Capt. A. Tirador (Pob.)",
    "Caranas",
    "Caraudan",
    "Carigangan",
    "Concepcion Pob.",
    "Crispin Salazar North (Pob.)",
    "Crispin Salazar South (Pob.)",
    "Cunsad",
    "Dabong",
    "Damires",
    "Damo-ong",
    "Danao",
    "Don T. Lutero Center (Pob.)",
    "Don T. Lutero East (Pob.)",
    "Don T. Lutero West Pob.",
    "Gines",
    "Golgota (Pob.)",
    "Guadalupe",
    "Jibolo",
    "Kuyot",
    "Locsin (Pob.)",
    "Madong",
    "Manacabac",
    "Mangil",
    "Matag-ub",
    "Monte-Magapa",
    "Pangilihan",
    "Panuran",
    "Pararinga",
    "Patong-patong",
    "Quipot",
    "R. Armada (Pob.)",
    "S. M. Villa (Pob.)",
    "San Julian (Pob.)",
    "San Pedro (Pob.)",
    "Santa Rita (Pob.)",
    "Santo Tomas",
    "Sarawag",
    "Tambal",
    "Tamu-an",
    "Tiringanan",
    "Tolarucan",
    "Tuburan",
    "Ubian",
    "Yabon",
  ],
  "0603025000": [
    "Agsirab",
    "Agtuman",
    "Alugmawa",
    "Badiangan",
    "Balagiao",
    "Banban",
    "Bansag",
    "Bayuco",
    "Binaba-an Armada",
    "Binaba-an Labayno",
    "Binaba-an Limoso",
    "Binaba-an Portigo",
    "Binaba-an Tirador",
    "Bogongbong",
    "Bonbon",
    "Bontoc",
    "Buri",
    "Burirao",
    "Buwang",
    "Cabatangan",
    "Cabugao",
    "Cabunlawan",
    "Caguisanan",
    "Caloy-Ahan",
    "Caninguan",
    "Capangyan",
    "Cayan Este",
    "Cayan Oeste",
    "Corot-on",
    "Coto",
    "Cubay",
    "Cunarum",
    "Daanbanwa",
    "Gines",
    "Hipgos",
    "Jayubo",
    "Jorog",
    "Lanot Grande",
    "Lanot Pequeño",
    "Legayada",
    "Lumanay",
    "Madarag",
    "Magbato",
    "Maite Grande",
    "Maite Pequeño",
    "Malag-it",
    "Manaulan",
    "Maribong",
    "Marong",
    "Misi",
    "Natividad",
    "Pajo",
    "Pandan",
    "Panuran",
    "Pasig",
    "Patag",
    "Poblacion Ilawod",
    "Poblacion Ilaya",
    "Poong",
    "Pughanan",
    "Pungsod",
    "Quiling",
    "Sagcup",
    "San Gregorio",
    "Sibacungan",
    "Sibaguan",
    "Simsiman",
    "Supoc",
    "Tampucao",
    "Tranghawan",
    "Tubungan",
    "Tuburan",
    "Walang",
  ],
  "0603026000": [
    "Bigke",
    "Buntatala",
    "Cagamutan Norte",
    "Cagamutan Sur",
    "Calaboa",
    "Camangay",
    "Cari Mayor",
    "Cari Minor",
    "Gua-an",
    "Guihaman",
    "Guinobatan",
    "Guintas",
    "Lapayon",
    "M.V. Hechanova",
    "Nabitasan",
    "Napnud",
    "Poblacion",
    "San Vicente",
  ],
  "0603027000": [
    "Agpipili",
    "Alcantara",
    "Almeñana",
    "Anabo",
    "Bankal",
    "Buenavista",
    "Cabantohan",
    "Capiñahan",
    "Dalipe",
    "Dapdapan",
    "Gerongan",
    "Imbaulan",
    "Layogbato",
    "Marapal",
    "Milan",
    "Nagsulang",
    "Nasapahan",
    "Omio",
    "Pacuan",
    "Poblacion NW Zone",
    "Poblacion SE Zone",
    "Pontoc",
    "San Antonio",
    "San Diego",
    "San Jose Moto",
    "Sepanton",
    "Sincua",
    "Tabunan",
    "Tugas",
    "Velasco",
    "Yawyawan",
  ],
  "0603028000": [
    "Agboy Norte",
    "Agboy Sur",
    "Agta",
    "Ambulong",
    "Anonang",
    "Apian",
    "Avanzada",
    "Awis",
    "Ayabang",
    "Ayubo",
    "Bacolod",
    "Baje",
    "Banagan",
    "Barangbang",
    "Barasan",
    "Bayag Norte",
    "Bayag Sur",
    "Binolbog",
    "Biri Norte",
    "Biri Sur",
    "Bobon",
    "Bucari",
    "Buenavista",
    "Buga",
    "Bulad",
    "Bulwang",
    "Cabolo-an",
    "Cabunga-an",
    "Cabutongan",
    "Cagay",
    "Camandag",
    "Camando",
    "Cananaman",
    "Capt. Fernando",
    "Carara-an",
    "Carolina",
    "Cawilihan",
    "Coyugan Norte",
    "Coyugan Sur",
    "Danao",
    "Dorog",
    "Dusacan",
    "Gines",
    "Gumboc",
    "Igcadios",
    "Ingay",
    "Isian Norte",
    "Isian Victoria",
    "Jamog Gines",
    "Lampaya",
    "Lanag",
    "Lang-og",
    "Ligtos",
    "Lonoc",
    "Magcapay",
    "Maliao",
    "Malublub",
    "Manampunay",
    "Marirong",
    "Mina",
    "Mocol",
    "Nagbangi",
    "Nalbang",
    "Odong-odong",
    "Oluangan",
    "Omambong",
    "Paga",
    "Pandan",
    "Panginman",
    "Paoy",
    "Pepe",
    "Poblacion",
    "Salngan",
    "Samlague",
    "Siol Norte",
    "Siol Sur",
    "Tacuyong Norte",
    "Tacuyong Sur",
    "Tagsing",
    "Talacuan",
    "Ticuan",
    "Tina-an Norte",
    "Tina-an Sur",
    "Tu-og",
    "Tunguan",
  ],
  "0603029000": [
    "Abay",
    "Abilay",
    "AGROCEL Pob.",
    "Amerang",
    "Bagacay East",
    "Bagacay West",
    "Bolo",
    "Bug-ot",
    "Bulay",
    "Buntalan",
    "Burak",
    "Cabangcalan",
    "Cabatac",
    "Caigon",
    "Cananghan",
    "Canawili",
    "Dagami",
    "Daja",
    "Dalusan",
    "DELCAR Pob.",
    "Inabasan",
    "Layog",
    "Linab",
    "Liñagan Calsada",
    "Liñagan Tacas",
    "Magsaysay",
    "Mandog",
    "MARI Pob.",
    "Miapa",
    "Nagba",
    "Nasaka",
    "Naslo-Bucao",
    "Nasuli",
    "Panalian",
    "Piandaan East",
    "Piandaan West",
    "Pispis",
    "Punong",
    "Santa Rita",
    "Sinubsuban",
    "Siwalo",
    "Subog",
    "THTP Pob.",
    "Tigbauan",
    "Trangka",
    "Tubang",
    "Tulahong",
    "Tuy-an East",
    "Tuy-an West",
    "Ubian",
  ],
  "0603030000": [
    "Agdum",
    "Aguiauan",
    "Alimodias",
    "Awang",
    "Bacauan",
    "Bacolod",
    "Bagumbayan",
    "Banbanan",
    "Banga",
    "Bangladan",
    "Banuyao",
    "Baraclayan",
    "Bariri",
    "Baybay Norte (Pob.)",
    "Baybay Sur (Pob.)",
    "Belen",
    "Bolho (Pob.)",
    "Bolocaue",
    "Buenavista Norte",
    "Buenavista Sur",
    "Bugtong Lumangan",
    "Bugtong Naulid",
    "Cabalaunan",
    "Cabangcalan",
    "Cabunotan",
    "Cadoldolan",
    "Cagbang",
    "Caitib",
    "Calagtangan",
    "Calampitao",
    "Cavite",
    "Cawayanan",
    "Cubay",
    "Cubay Ubos",
    "Dalije",
    "Damilisan",
    "Dawog",
    "Diday",
    "Dingle",
    "Durog",
    "Frantilla",
    "Fundacion",
    "Gines",
    "Guibongan",
    "Igbita",
    "Igbugo",
    "Igcabidio",
    "Igcabito-on",
    "Igcatambor",
    "Igdalaquit",
    "Igdulaca",
    "Igpajo",
    "Igpandan",
    "Igpuro",
    "Igpuro-Bariri",
    "Igsoligue",
    "Igtuba",
    "Ilog-ilog",
    "Indag-an",
    "Kirayan Norte",
    "Kirayan Sur",
    "Kirayan Tacas",
    "La Consolacion",
    "Lacadon",
    "Lanutan",
    "Lumangan",
    "Mabayan",
    "Maduyo",
    "Malagyan",
    "Mambatad",
    "Maninila",
    "Maricolcol",
    "Maringyan",
    "Mat-y (Pob.)",
    "Matalngon",
    "Naclub",
    "Nam-o Norte",
    "Nam-o Sur",
    "Narat-an",
    "Narorogan",
    "Naulid",
    "Olango",
    "Ongyod",
    "Onop",
    "Oya-oy",
    "Oyungan",
    "Palaca",
    "Paro-on",
    "Potrido",
    "Pudpud",
    "Pungtod Monteclaro",
    "Pungtod Naulid",
    "Sag-on",
    "San Fernando",
    "San Jose",
    "San Rafael",
    "Sapa",
    "Saring",
    "Sibucao",
    "Taal",
    "Tabunacan",
    "Tacas (Pob.)",
    "Tambong",
    "Tan-agan",
    "Tatoy",
    "Ticdalan",
    "Tig-amaga",
    "Tig-Apog-Apog",
    "Tigbagacay",
    "Tiglawa",
    "Tigmalapad",
    "Tigmarabo",
    "To-og",
    "Tugura-ao",
    "Tumagboc",
    "Ubos Ilawod (Pob.)",
    "Ubos Ilaya (Pob.)",
    "Valencia",
    "Wayang",
  ],
  "0603031000": [
    "Abat",
    "Agmanaphao",
    "Amiroy",
    "Badiangan",
    "Bangac",
    "Cabalabaguan",
    "Capul-an",
    "Dala",
    "Guibuangan",
    "Janipa-an East",
    "Janipa-an West",
    "Mina East (Pob.)",
    "Mina West (Pob.)",
    "Nasirum",
    "Naumuan",
    "Singay",
    "Talibong Grande",
    "Talibong Pequeño",
    "Tipolo",
    "Tolarucan",
    "Tumay",
    "Yugot",
  ],
  "0603032000": [
    "Baclayan",
    "Badiang",
    "Balabag",
    "Bilidan",
    "Bita-og Gaja",
    "Bololacao",
    "Burot",
    "Cabilauan",
    "Cabugao",
    "Cagban",
    "Calumbuyan",
    "Damires",
    "Dawis",
    "General Delgado",
    "Guinobatan",
    "Janipa-an Oeste",
    "Jelicuon Este",
    "Jelicuon Oeste",
    "Pasil",
    "Poblacion",
    "Wari-wari",
  ],
  "0603034000": [
    "Abilay Norte",
    "Abilay Sur",
    "Alegre",
    "Batuan Ilaud",
    "Batuan Ilaya",
    "Bita Norte",
    "Bita Sur",
    "Botong",
    "Buray",
    "Cabanbanan",
    "Caboloan Norte",
    "Caboloan Sur",
    "Cadinglian",
    "Cagbang",
    "Calam-isan",
    "Galang",
    "Lambuyao",
    "Mambog",
    "Pakiad",
    "Poblacion East",
    "Poblacion North",
    "Poblacion South",
    "Poblacion West",
    "Polo Maestra Bita",
    "Rizal",
    "Salngan",
    "Sambaludan",
    "San Antonio",
    "San Nicolas",
    "Santa Clara",
    "Santa Monica",
    "Santa Rita",
    "Tagbac Norte",
    "Tagbac Sur",
    "Trapiche",
    "Tuburan",
    "Turog-Turog",
  ],
  "0603035000": [
    "Agdahon",
    "Agdayao",
    "Aglalana",
    "Agtabo",
    "Agtambo",
    "Alimono",
    "Arac",
    "Ayuyan",
    "Bacuranan",
    "Bagacay",
    "Batu",
    "Bayan",
    "Bitaogan",
    "Buenavista",
    "Buyo",
    "Cabunga",
    "Cadilang",
    "Cairohan",
    "Dalicanan",
    "Gegachac",
    "Gemat-y",
    "Gemumua-agahon",
    "Gines Viejo",
    "Imbang Grande",
    "Jaguimitan",
    "Libo-o",
    "Maasin",
    "Magdungao",
    "Malag-it Grande",
    "Malag-it Pequeño",
    "Mambiranan Grande",
    "Mambiranan Pequeño",
    "Man-it",
    "Mantulang",
    "Mulapula",
    "Nueva Union",
    "Pagaypay",
    "Pangi",
    "Poblacion Ilawod",
    "Poblacion Ilaya",
    "Punong",
    "Quinagaringan Grande",
    "Quinagaringan Pequeño",
    "Sablogon",
    "Salngan",
    "Santo Tomas",
    "Sarapan",
    "Tagubong",
    "Talongonan",
    "Tubod",
    "Tuburan",
  ],
  "0603036000": [
    "Aganan",
    "Amparo",
    "Anilao",
    "Balabag",
    "Cabugao Norte",
    "Cabugao Sur",
    "Jibao-an",
    "Mali-ao",
    "Pagsanga-an",
    "Pal-agon",
    "Pandac",
    "Purok I (Pob.)",
    "Purok II (Pob.)",
    "Purok III (Pob.)",
    "Purok IV (Pob.)",
    "Tigum",
    "Ungka I",
    "Ungka II",
  ],
  "0603037000": [
    "Abangay",
    "Amamaros",
    "Bagacay",
    "Barasan",
    "Batuan",
    "Bongco",
    "Cahaguichican",
    "Callan",
    "Cansilayan",
    "Casalsagan",
    "Cato-ogan",
    "Cau-ayan",
    "Culob",
    "Danao",
    "Dapitan",
    "Dawis",
    "Dongsol",
    "Fernando Parcon Ward (Pob.)",
    "Fundacion",
    "Guibuangan",
    "Guinacas",
    "Igang",
    "Intaluan",
    "Iwa Ilaud",
    "Iwa Ilaya",
    "Jamabalud",
    "Jebioc",
    "Lay-Ahan",
    "Lopez Jaena Ward (Pob.)",
    "Lumbo",
    "Macatol",
    "Malusgod",
    "Nabitasan",
    "Naga",
    "Nanga",
    "Naslo",
    "Pajo",
    "Palanguia",
    "Pitogo",
    "Polot-an",
    "Primitivo Ledesma Ward (Pob.)",
    "Purog",
    "Rumbang",
    "San Jose Ward (Pob.)",
    "Sinuagan",
    "Tuburan",
    "Tumcon Ilaud",
    "Tumcon Ilaya",
    "Ubang",
    "Zarrague",
  ],
  "0603038000": [
    "Agdaliran",
    "Amayong",
    "Bagacay",
    "Batuan",
    "Bondulan",
    "Boroñgon",
    "Canas",
    "Capinang",
    "Cubay",
    "Cudionan",
    "Dugman",
    "Hacienda Conchita",
    "Madanlog",
    "Mandu-awak",
    "Moto",
    "Naborot",
    "Nipa",
    "Odiongan",
    "Pangi",
    "Pase",
    "Poblacion",
    "San Nicolas",
    "Santol",
    "Siempreviva",
    "Sua",
    "Talo-ato",
    "Tamangi",
    "Tiabas",
    "Tuble",
  ],
  "0603039000": [
    "Abaca",
    "Asisig",
    "Bantayan",
    "Braulan",
    "Cabugao Nuevo",
    "Cabugao Viejo",
    "Camiri",
    "Catan-Agan",
    "Compo",
    "Cubay",
    "Dacal",
    "Dumiles",
    "Garita",
    "Gines Nuevo",
    "Imbang Pequeño",
    "Imbesad-an",
    "Iprog",
    "Lip-ac",
    "Madarag",
    "Mapili",
    "Paga",
    "Palje",
    "Poblacion Ilawod",
    "Poblacion Ilaya",
    "Quinolpan",
    "Rumagayray",
    "San Antonio",
    "Tambunac",
  ],
  "0603040000": [
    "Amboyu-an",
    "Andres Bonifacio",
    "Antalon",
    "Bad-as",
    "Bagumbayan",
    "Balabago",
    "Baybay",
    "Bayunan",
    "Bolbogan",
    "Bonga",
    "Bucaya",
    "Bulho",
    "Cadluman",
    "Cadoldolan",
    "Camaba-an",
    "Camia",
    "Cata-an",
    "Crossing Dapuyan",
    "Cubay",
    "Cumarascas",
    "Dacdacanan",
    "Danawan",
    "Doldol",
    "Dongoc",
    "Escalantera",
    "Ginot-an",
    "Guibongan Bayunan",
    "Huna",
    "Igbaje",
    "Igbangcal",
    "Igbinangon",
    "Igburi",
    "Igcabutong",
    "Igcadlum",
    "Igcaphang",
    "Igcaratong",
    "Igcondao",
    "Igcores",
    "Igdagmay",
    "Igdomingding",
    "Iglilico",
    "Igpayong",
    "Jawod",
    "Langca",
    "Languanan",
    "Lawigan",
    "Lomboy",
    "Lomboyan",
    "Lopez Vito",
    "Mabini Norte",
    "Mabini Sur",
    "Manhara",
    "Maninila",
    "Masagud",
    "Matambog",
    "Mayunoc",
    "Montinola",
    "Nadsadan",
    "Nagquirisan",
    "Nagsipit",
    "New Gumawan",
    "Panatan",
    "Pitogo",
    "Purok 1 (Pob.)",
    "Purok 2 (Pob.)",
    "Purok 3 (Pob.)",
    "Purok 4 (Pob.)",
    "Purok 5 (Pob.)",
    "Qui-anan",
    "Roma",
    "San Luis",
    "San Mateo Norte",
    "San Mateo Sur",
    "Santa Rita",
    "Santiago",
    "Sinogbuhan",
    "Siwaragan",
    "Talagutac",
    "Tapikan",
    "Taslan",
    "Tiglawa",
    "Tiolas",
    "To-og",
    "Torocadan",
    "Ulay",
  ],
  "0603041000": [
    "Bgy. 1 Pob.",
    "Bgy. 10",
    "Bgy. 11 Pob.",
    "Bgy. 12 Pob.",
    "Bgy. 13 Pob.",
    "Bgy. 14 Pob.",
    "Bgy. 15 Pob.",
    "Bgy. 16 Pob.",
    "Bgy. 2 Pob.",
    "Bgy. 3 Pob.",
    "Bgy. 4 Pob.",
    "Bgy. 5 Pob.",
    "Bgy. 6 Pob.",
    "Bgy. 7 Pob.",
    "Bgy. 8 Pob.",
    "Bgy. 9 Pob.",
    "Consolacion",
    "Igtambo",
    "San Antonio",
    "San Jose",
    "Santa Cruz",
    "Santa Teresa",
    "Santo Angel",
    "Santo Niño",
  ],
  "0603042000": [
    "Aripdip",
    "Bagacay",
    "Calaigang",
    "Ilongbukid",
    "Poblacion",
    "Poscolon",
    "San Andres",
    "San Dionisio",
    "San Florentino",
  ],
  "0603043000": [
    "Agusipan",
    "Agutayan",
    "Bagumbayan",
    "Balabag",
    "Balibagan Este",
    "Balibagan Oeste",
    "Ban-ag",
    "Bantay",
    "Barangay Zone I (Pob.)",
    "Barangay Zone II (Pob.)",
    "Barangay Zone III (Pob.)",
    "Barangay Zone IV (Pob.)",
    "Barangay Zone V (Pob.)",
    "Barangay Zone VI (Pob.)",
    "Barasan Este",
    "Barasan Oeste",
    "Binangkilan",
    "Bitaog-Taytay",
    "Bolong Este",
    "Bolong Oeste",
    "Buayahon",
    "Buyo",
    "Cabugao Norte",
    "Cabugao Sur",
    "Cadagmayan Norte",
    "Cadagmayan Sur",
    "Cafe",
    "Calaboa Este",
    "Calaboa Oeste",
    "Camambugan",
    "Canipayan",
    "Conaynay",
    "Daga",
    "Dalid",
    "Duyanduyan",
    "Gen. Martin T. Delgado",
    "Guno",
    "Inangayan",
    "Jibao-an",
    "Lacadon",
    "Lanag",
    "Lupa",
    "Magancina",
    "Malawog",
    "Mambuyo",
    "Manhayang",
    "Miraga-Guibuangan",
    "Nasugban",
    "Omambog",
    "Pal-Agon",
    "Pungsod",
    "San Sebastian",
    "Sangcate",
    "Tagsing",
    "Talanghauan",
    "Talongadian",
    "Tigtig",
    "Tuburan",
    "Tugas",
    "Tungay",
  ],
  "0603044000": [
    "Aguirre",
    "Aldeguer",
    "Alibayog",
    "Anoring",
    "Apelo",
    "Apologista",
    "Aposaga",
    "Arante",
    "Ardemil",
    "Aspera",
    "Aswe-Pabriaga",
    "Bagaygay",
    "Bakabak",
    "Batitao",
    "Bato",
    "Castor",
    "Crespo",
    "Del Castillo",
    "Devera",
    "Domingo",
    "Ferraris",
    "Gildore",
    "Improgo",
    "Juaneza",
    "Labigan",
    "Lanciola",
    "Latawan",
    "Malapaya",
    "Muyco",
    "Padios",
    "Pasig",
    "Poblacion Ilawod",
    "Poblacion Ilaya",
    "Poblacion Market",
    "Posadas",
    "Preciosa",
    "Salcedo",
    "San Luis",
    "Tady",
    "Tentay",
    "Villahermosa",
    "Zerrudo",
  ],
  "0603045000": [
    "Alupidian",
    "Atabayan",
    "Bagacay",
    "Baguingin",
    "Bagumbayan",
    "Bangkal",
    "Bantud",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Barosong",
    "Barroc",
    "Bayuco",
    "Binaliuan Mayor",
    "Binaliuan Menor",
    "Bitas",
    "Buenavista",
    "Bugasongan",
    "Buyu-an",
    "Canabuan",
    "Cansilayan",
    "Cordova Norte",
    "Cordova Sur",
    "Danao",
    "Dapdap",
    "Dorong-an",
    "Guisian",
    "Isauan",
    "Isian",
    "Jamog",
    "Lanag",
    "Linobayan",
    "Lubog",
    "Nagba",
    "Namocon",
    "Napnapan Norte",
    "Napnapan Sur",
    "Olo Barroc",
    "Parara Norte",
    "Parara Sur",
    "San Rafael",
    "Sermon",
    "Sipitan",
    "Supa",
    "Tan Pael",
    "Taro",
  ],
  "0603046000": [
    "Adgao",
    "Ago",
    "Ambarihon",
    "Ayubo",
    "Bacan",
    "Badiang",
    "Bagunanay",
    "Balicua",
    "Bantayanan",
    "Batga",
    "Bato",
    "Bikil",
    "Boloc",
    "Bondoc",
    "Borong",
    "Buenavista",
    "Cadabdab",
    "Daga-ay",
    "Desposorio",
    "Igdampog Norte",
    "Igdampog Sur",
    "Igpaho",
    "Igtuble",
    "Ingay",
    "Isauan",
    "Jolason",
    "Jona",
    "La-ag",
    "Lanag Norte",
    "Lanag Sur",
    "Male",
    "Mayang",
    "Molina",
    "Morcillas",
    "Nagba",
    "Navillan",
    "Pinamacalan",
    "San Jose",
    "Sibucauan",
    "Singon",
    "Tabat",
    "Tagpu-an",
    "Talento",
    "Teniente Benito",
    "Victoria",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
  ],
  "0603047000": [
    "Balud I",
    "Balud II",
    "Balud Lilo-an",
    "Dawis Centro",
    "Dawis Norte",
    "Dawis Sur",
    "Gines",
    "Ilawod Poblacion",
    "Ilaya Poblacion",
    "Inagdangan Centro",
    "Inagdangan Norte",
    "Inagdangan Sur",
    "Jalaud Norte",
    "Jalaud Sur",
    "Libongcogon",
    "Malunang",
    "Pajo",
    "Sambag",
    "Sigangao",
    "Talauguis",
    "Talibong",
    "Tubigan",
    "Tuburan",
    "Tuburan Sulbod",
  ],
  "0604502000": [
    "Abuanan",
    "Alianza",
    "Atipuluan",
    "Bacong-Montilla",
    "Bagroy",
    "Balingasag",
    "Binubuhan",
    "Busay",
    "Calumangan",
    "Caridad",
    "Dulao",
    "Ilijan",
    "Jorge L. Araneta",
    "Lag-Asan",
    "Ma-ao Barrio",
    "Mailum",
    "Malingin",
    "Napoles",
    "Pacol",
    "Poblacion",
    "Sagasa",
    "Sampinit",
    "Tabunan",
    "Taloc",
  ],
  "0604503000": [
    "Amontay",
    "Bagroy",
    "Bi-ao",
    "Canmoros (Pob.)",
    "Enclaro",
    "Marina (Pob.)",
    "Paglaum (Pob.)",
    "Payao",
    "Progreso (Pob.)",
    "San Jose",
    "San Juan (Pob.)",
    "San Pedro (Pob.)",
    "San Teodoro (Pob.)",
    "San Vicente (Pob.)",
    "Santo Rosario (Pob.)",
    "Santol",
  ],
  "0604504000": [
    "Andres Bonifacio",
    "Banquerohan",
    "Barangay 1 Pob.",
    "Barangay 2 Pob.",
    "Barangay 3 Pob.",
    "Barangay 4 Pob.",
    "Barangay 5 Pob.",
    "Barangay 6 Pob.",
    "Burgos",
    "Cabahug",
    "Cadiz Viejo",
    "Caduha-an",
    "Celestino Villacin",
    "Daga",
    "Jerusalem",
    "Luna",
    "Mabini",
    "Magsaysay",
    "Sicaba",
    "Tiglawigan",
    "Tinampa-an",
    "V. F. Gustilo",
  ],
  "0604505000": [
    "Agpangi",
    "Ani-e",
    "Bagacay",
    "Bantayanon",
    "Buenavista",
    "Cabungahan",
    "Calampisawan",
    "Cambayobo",
    "Castellano",
    "Cruz",
    "Dolis",
    "Hilub-Ang",
    "Hinab-Ongan",
    "Ilaya",
    "Laga-an",
    "Lalong",
    "Lemery",
    "Lipat-on",
    "Lo-ok (Pob.)",
    "Ma-aslob",
    "Macasilao",
    "Mahilum",
    "Malanog",
    "Malatas",
    "Marcelo",
    "Menchaca",
    "Mina-utok",
    "Minapasuk",
    "Paghumayan",
    "Pantao",
    "Patun-an",
    "Pinocutan",
    "Refugio",
    "San Benito",
    "San Isidro",
    "Suba (Pob.)",
    "Telim",
    "Tigbao",
    "Tigbon",
    "Winaswasan",
  ],
  "0604506000": [
    "Agboy",
    "Banga",
    "Cabia-an",
    "Caningay",
    "Gatuslao",
    "Haba",
    "Payauan",
    "Poblacion East",
    "Poblacion West",
  ],
  "0604507000": [
    "Abaca",
    "Baclao",
    "Basak",
    "Bulata",
    "Caliling",
    "Camalanda-an",
    "Camindangan",
    "Elihan",
    "Guiljungan",
    "Inayawan",
    "Isio",
    "Linaon",
    "Lumbia",
    "Mambugsay",
    "Man-Uling",
    "Masaling",
    "Molobolo",
    "Poblacion",
    "Sura",
    "Talacdan",
    "Tambad",
    "Tiling",
    "Tomina",
    "Tuyom",
    "Yao-yao",
  ],
  "0604508000": [
    "Alacaygan",
    "Alicante",
    "Batea",
    "Canlusong",
    "Consing",
    "Cudangdang",
    "Damgo",
    "Gahit",
    "Latasan",
    "Madalag",
    "Manta-angan",
    "Nanca",
    "Pasil",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "San Isidro",
    "San Jose",
    "Santo Niño",
    "Tabigue",
    "Tanza",
    "Tomongtong",
    "Tuburan",
  ],
  "0604509000": [
    "Alimango",
    "Balintawak (Pob.)",
    "Binaguiohan",
    "Buenavista",
    "Cervantes",
    "Dian-ay",
    "Hacienda Fe",
    "Japitan",
    "Jonobjonob",
    "Langub",
    "Libertad",
    "Mabini",
    "Magsaysay",
    "Malasibog",
    "Old Poblacion",
    "Paitan",
    "Pinapugasan",
    "Rizal",
    "Tamlang",
    "Udtongan",
    "Washington",
  ],
  "0604510000": [
    "Aguisan",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Buenavista",
    "Cabadiangan",
    "Cabanbanan",
    "Carabalan",
    "Caradio-an",
    "Libacao",
    "Mahalang",
    "Mambagaton",
    "Nabali-an",
    "San Antonio",
    "Sara-et",
    "Su-ay",
    "Talaban",
    "To-oy",
  ],
  "0604511000": [
    "Anahaw",
    "Aranda",
    "Baga-as",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Bato",
    "Calapi",
    "Camalobalo",
    "Camba-og",
    "Cambugsa",
    "Candumarao",
    "Gargato",
    "Himaya",
    "Miranda",
    "Nanunga",
    "Narauis",
    "Palayog",
    "Paticui",
    "Pilar",
    "Quiwi",
    "Tagda",
    "Tuguis",
  ],
  "0604512000": [
    "Alim",
    "Asia",
    "Bacuyangan",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Bulwangan",
    "Culipapa",
    "Damutan",
    "Daug",
    "Po-ok",
    "San Rafael",
    "Sangke",
    "Talacagay",
  ],
  "0604513000": [
    "Andulauan",
    "Balicotoc",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Bocana",
    "Calubang",
    "Canlamay",
    "Consuelo",
    "Dancalan",
    "Delicioso",
    "Galicia",
    "Manalad",
    "Pinggot",
    "Tabu",
    "Vista Alegre",
  ],
  "0604514000": [
    "Amin",
    "Banogbanog",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Bulad",
    "Bungahin",
    "Cabcab",
    "Camangcamang",
    "Camp Clark",
    "Cansalongon",
    "Guintubhan",
    "Libas",
    "Limalima",
    "Makilignit",
    "Mansablay",
    "Maytubig",
    "Panaquiao",
    "Riverside",
    "Rumirang",
    "San Agustin",
    "Sebucawan",
    "Sikatuna",
    "Tinongan",
  ],
  "0604515000": [
    "Bantayan",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Binicuil",
    "Camansi",
    "Camingawan",
    "Camugao",
    "Carol-an",
    "Daan Banua",
    "Hilamonan",
    "Inapoy",
    "Linao",
    "Locotan",
    "Magballo",
    "Oringao",
    "Orong",
    "Pinaguinpinan",
    "Salong",
    "Tabugon",
    "Tagoc",
    "Tagukon",
    "Talubangi",
    "Tampalon",
    "Tan-Awan",
    "Tapi",
  ],
  "0604516000": [
    "Ara-al",
    "Ayungon",
    "Balabag",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Batuan",
    "Cubay",
    "Haguimit",
    "La Granja",
    "Nagasi",
    "Roberto S. Benedicto",
    "San Miguel",
    "Yubo",
  ],
  "0604517000": [
    "Biaknabato",
    "Cabacungan",
    "Cabagnaan",
    "Camandag",
    "Lalagsan",
    "Manghanoy",
    "Mansalanao",
    "Masulog",
    "Nato",
    "Puso",
    "Robles (Pob.)",
    "Sag-Ang",
    "Talaptap",
  ],
  "0604518000": [
    "Barangay I (Pob.)",
    "Barangay I-A (Pob.)",
    "Barangay I-B (Pob.)",
    "Barangay II (Pob.)",
    "Barangay II-A (Pob.)",
    "Chambery",
    "Punta Mesa",
    "Punta Salong",
    "Purisima",
    "San Pablo",
    "Santa Teresa",
    "Tortosa",
  ],
  "0604519000": [
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Crossing Magallon",
    "Guinpana-an",
    "Inolingan",
    "Macagahay",
    "Magallon Cadre",
    "Montilla",
    "Odiong",
    "Quintin Remo",
  ],
  "0604520000": [
    "Abo-abo",
    "Alegria",
    "Amayco",
    "Blumentritt",
    "Buenavista",
    "Caliban",
    "Canlandog",
    "Cansilayan",
    "Damsite",
    "Iglau-an",
    "Lopez Jaena",
    "Minoyan",
    "Pandanon",
    "Salvacion",
    "San Miguel",
    "Santa Cruz",
    "Santa Rosa",
    "Talotog",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)",
    "Zone V (Pob.)",
  ],
  "0604521000": [
    "Antipolo",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Buenavista Gibong",
    "Buenavista Rizal",
    "Burgos",
    "Cambarus",
    "Canroma",
    "Don Salvador Benedicto",
    "General Malvar",
    "Gomez",
    "M. H. Del Pilar",
    "Mabini",
    "Miranda",
    "Pandan",
    "Recreo",
    "San Isidro",
    "San Juan",
    "Zamora",
  ],
  "0604522000": [
    "Barangay Zone 1 (Pob.)",
    "Barangay Zone 1-A (Pob.)",
    "Barangay Zone 2 (Pob.)",
    "Barangay Zone 3 (Pob.)",
    "Barangay Zone 4 (Pob.)",
    "Barangay Zone 4-A (Pob.)",
    "Barangay Zone 5 (Pob.)",
    "Barangay Zone 6 (Pob.)",
    "Barangay Zone 7 (Pob.)",
    "Canjusa",
    "Crossing Pulupandan",
    "Culo",
    "Mabini",
    "Pag-ayon",
    "Palaka Norte",
    "Palaka Sur",
    "Patic",
    "Tapong",
    "Ubay",
    "Utod",
  ],
  "0604523000": [
    "Andres Bonifacio",
    "Bato",
    "Baviera",
    "Bulanon",
    "Campo Himoga-an",
    "Campo Santiago",
    "Colonia Divina",
    "Fabrica",
    "General Luna",
    "Himoga-an Baybay",
    "Lopez Jaena",
    "Makiling",
    "Malubon",
    "Molocaboc",
    "Old Sagay",
    "Paraiso",
    "Plaridel",
    "Poblacion I",
    "Poblacion II",
    "Puey",
    "Rafaela Barrera",
    "Rizal",
    "Taba-ao",
    "Tadlong",
    "Vito",
  ],
  "0604524000": [
    "Bagonbon",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Barangay VI (Pob.)",
    "Buluangan",
    "Codcod",
    "Ermita",
    "Guadalupe",
    "Nataban",
    "Palampas",
    "Prosperidad",
    "Punao",
    "Quezon",
    "Rizal",
    "San Juan",
  ],
  "0604525000": [
    "Bagonawa",
    "Baliwagan",
    "Batuan",
    "Guintorilan",
    "Nayon",
    "Poblacion",
    "Sibucao",
    "Tabao Baybay",
    "Tabao Rizal",
    "Tibsoc",
  ],
  "0604526000": [
    "Bagtic",
    "Balaring",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Barangay VI Pob.",
    "Eustaquio Lopez",
    "Guimbala-on",
    "Guinhalaran",
    "Kapitan Ramon",
    "Lantad",
    "Mambulac",
    "Patag",
    "Rizal",
  ],
  "0604527000": [
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Cabadiangan",
    "Camindangan",
    "Canturay",
    "Cartagena",
    "Cayhagan",
    "Gil Montilla",
    "Mambaroto",
    "Manlucahoc",
    "Maricalum",
    "Nabulao",
    "Nauhang",
    "San Jose",
  ],
  "0604528000": [
    "Bubog",
    "Cabatangan",
    "Concepcion",
    "Dos Hermanas",
    "Efigenio Lizares",
    "Katilingban",
    "Matab-ang",
    "San Fernando",
    "Zone 1 (Pob.)",
    "Zone 10 (Pob.)",
    "Zone 11 (Pob.)",
    "Zone 12 (Pob.)",
    "Zone 12-A (Pob.)",
    "Zone 14 (Pob.)",
    "Zone 14-A (Pob.)",
    "Zone 14-B (Pob.)",
    "Zone 15 (Pob.)",
    "Zone 16 (Pob.)",
    "Zone 2 (Pob.)",
    "Zone 3 (Pob.)",
    "Zone 4 (Pob.)",
    "Zone 4-A (Pob.)",
    "Zone 5 (Pob.)",
    "Zone 6 (Pob.)",
    "Zone 7 (Pob.)",
    "Zone 8 (Pob.)",
    "Zone 9 (Pob.)",
  ],
  "0604529000": [
    "Bandila",
    "Bug-ang",
    "General Luna",
    "Magticol",
    "Poblacion",
    "Salamanca",
    "San Isidro",
    "San Jose",
    "Tabun-ac",
  ],
  "0604530000": [
    "Alijis",
    "Ayungon",
    "Bagumbayan",
    "Batuan",
    "Bayabas",
    "Central Tabao",
    "Doldol",
    "Guintorilan",
    "Lacaron",
    "Mabini",
    "Pacol",
    "Palaka",
    "Paloma",
    "Poblacion",
    "Sagua Banua",
    "Tabao Proper",
  ],
  "0604531000": [
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay IX",
    "Barangay V (Pob.)",
    "Barangay VI (Pob.)",
    "Barangay VI-A",
    "Barangay VII (Pob.)",
    "Barangay VIII (Pob.)",
    "Barangay X",
    "Barangay XI",
    "Barangay XII",
    "Barangay XIII",
    "Barangay XIV",
    "Barangay XIX",
    "Barangay XIX-A",
    "Barangay XV",
    "Barangay XV-A",
    "Barangay XVI",
    "Barangay XVI-A",
    "Barangay XVII",
    "Barangay XVIII",
    "Barangay XVIII-A",
    "Barangay XX",
    "Barangay XXI",
  ],
  "0604532000": [
    "Bago",
    "Bagong Silang",
    "Bunga",
    "Igmaya-an",
    "Kumaliskis",
    "Pandanon",
    "Pinowayan",
  ],
  "0607901000": [
    "Agsanayan",
    "Avila",
    "Bacjao ",
    "Banban",
    "Cansilayan",
    "Dagsa-an",
    "Daragan",
    "East Valencia",
    "Getulio",
    "Mabini",
    "Magsaysay",
    "Mclain",
    "Montpiller",
    "Navalas",
    "Nazaret",
    "New Poblacion ",
    "Old Poblacion",
    "Piña",
    "Rizal",
    "Salvacion",
    "San Fernando",
    "San Isidro",
    "San Miguel",
    "San Nicolas",
    "San Pedro",
    "San Roque",
    "Santo Rosario",
    "Sawang",
    "Supang",
    "Tacay",
    "Taminla",
    "Tanag",
    "Tastasan",
    "Tinadtaran",
    "Umilig",
    "Zaldivar",
  ],
  "0607902000": [
    "Alaguisoc",
    "Balcon Maravilla",
    "Balcon Melliza",
    "Bugnay",
    "Buluangan",
    "Espinosa",
    "Hoskyn",
    "Lawi",
    "Morobuan",
    "Poblacion",
    "Rizal",
    "San Miguel",
    "Santa Teresa",
    "Sinapsapan",
  ],
  "0607903000": [
    "Cabalagnan",
    "Calaya",
    "Canhawan",
    "Concordia Sur",
    "Dolores",
    "Guiwanon",
    "Igang",
    "Igdarapdap",
    "La Paz",
    "Lanipe",
    "Lucmayan",
    "Magamay",
    "Napandong",
    "Oracon Sur",
    "Pandaraonan",
    "Panobolon",
    "Poblacion",
    "Salvacion",
    "San Antonio",
    "San Roque",
    "Santo Domingo",
    "Tando",
  ],
  "0607904000": [
    "Aguilar",
    "Cabano",
    "Cabungahan",
    "Constancia",
    "Gaban",
    "Igcawayan",
    "M. Chavez",
    "San Enrique",
    "Sapal",
    "Sebario",
    "Suclaran",
    "Tamborong",
  ],
  "0607905000": [
    "Alegria",
    "Ayangan",
    "Bubog",
    "Concordia Norte",
    "Dasal",
    "Inampologan",
    "Maabay",
    "Millan",
    "Oracon Norte",
    "Ravina",
    "Sabang",
    "San Isidro",
    "Sebaste",
    "Tanglad",
  ],
  "0630200000": [
    "Alangilan",
    "Alijis",
    "Banago",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 12 (Pob.)",
    "Barangay 13 (Pob.)",
    "Barangay 14 (Pob.)",
    "Barangay 15 (Pob.)",
    "Barangay 16 (Pob.)",
    "Barangay 17 (Pob.)",
    "Barangay 18 (Pob.)",
    "Barangay 19 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 20 (Pob.)",
    "Barangay 21 (Pob.)",
    "Barangay 22 (Pob.)",
    "Barangay 23 (Pob.)",
    "Barangay 24 (Pob.)",
    "Barangay 25 (Pob.)",
    "Barangay 26 (Pob.)",
    "Barangay 27 (Pob.)",
    "Barangay 28 (Pob.)",
    "Barangay 29 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 30 (Pob.)",
    "Barangay 31 (Pob.)",
    "Barangay 32 (Pob.)",
    "Barangay 33 (Pob.)",
    "Barangay 34 (Pob.)",
    "Barangay 35 (Pob.)",
    "Barangay 36 (Pob.)",
    "Barangay 37 (Pob.)",
    "Barangay 38 (Pob.)",
    "Barangay 39 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 40 (Pob.)",
    "Barangay 41 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Bata",
    "Cabug",
    "Estefania",
    "Felisa",
    "Granada",
    "Handumanan",
    "Mandalagan",
    "Mansilingan",
    "Montevista",
    "Pahanocoy",
    "Punta Taytay",
    "Singcang-Airport",
    "Sum-ag",
    "Taculing",
    "Tangub",
    "Villamonte",
    "Vista Alegre",
  ],
  "0631000000": [
    "Abeto Mirasol Taft South",
    "Aguinaldo",
    "Airport",
    "Alalasan Lapuz",
    "Arguelles",
    "Arsenal Aduana",
    "Bakhaw",
    "Balabago",
    "Balantang",
    "Baldoza",
    "Bantud",
    "Banuyao",
    "Baybay Tanza",
    "Benedicto",
    "Bito-on",
    "Bolilao",
    "Bonifacio",
    "Bonifacio Tanza",
    "Buhang",
    "Buhang Taft North",
    "Buntatala",
    "Burgos-Mabini-Plaza",
    "Caingin",
    "Calahunan",
    "Calaparan",
    "Calubihan",
    "Calumpang",
    "Camalig",
    "Cochero",
    "Compania",
    "Concepcion-Montes",
    "Cuartero",
    "Cubay",
    "Danao",
    "Delgado-Jalandoni-Bagumbayan",
    "Democracia",
    "Desamparados",
    "Divinagracia",
    "Don Esteban-Lapuz",
    "Dulonan",
    "Dungon",
    "Dungon A",
    "Dungon B",
    "East Baluarte",
    "East Timawa",
    "Edganzon",
    "El 98 Castilla",
    "Fajardo",
    "Flores",
    "General Hughes-Montes",
    "Gloria",
    "Gustilo",
    "Guzman-Jesena",
    "Habog-habog Salvacion",
    "Hibao-an Norte",
    "Hibao-an Sur",
    "Hinactacan",
    "Hipodromo",
    "Inday",
    "Infante",
    "Ingore",
    "Jalandoni Estate-Lapuz",
    "Jalandoni-Wilson",
    "Javellana",
    "Jereos",
    "Kahirupan",
    "Kasingkasing",
    "Katilingban",
    "Kauswagan",
    "Laguda",
    "Lanit",
    "Lapuz Norte",
    "Lapuz Sur",
    "Legaspi dela Rama",
    "Liberation",
    "Libertad-Lapuz",
    "Libertad, Santa Isabel",
    "Loboc-Lapuz",
    "Lopez Jaena",
    "Lopez Jaena Norte",
    "Lopez Jaena Sur",
    "Luna",
    "Luna",
    "M. V. Hechanova",
    "Mabolo-Delgado",
    "Macarthur",
    "Magdalo",
    "Magsaysay",
    "Magsaysay Village",
    "Malipayon-Delgado",
    "Mansaya-Lapuz",
    "Marcelo H. del Pilar",
    "Maria Clara",
    "Maria Cristina",
    "Mohon",
    "Molo Boulevard",
    "Monica Blumentritt",
    "Montinola",
    "Muelle Loney-Montes",
    "Nabitasan",
    "Navais",
    "Nonoy",
    "North Avanceña",
    "North Baluarte",
    "North Fundidor",
    "North San Jose",
    "Obrero-Lapuz",
    "Oñate de Leon",
    "Ortiz",
    "Osmeña",
    "Our Lady Of Fatima",
    "Our Lady Of Lourdes",
    "Pale Benedicto Rizal",
    "PHHC Block 17",
    "PHHC Block 22 NHA",
    "Poblacion Molo",
    "President Roxas",
    "Progreso-Lapuz",
    "Punong-Lapuz",
    "Quezon",
    "Quintin Salas",
    "Railway",
    "Rima-Rizal",
    "Rizal",
    "Rizal Estanzuela",
    "Rizal Ibarra",
    "Rizal Palapala I",
    "Rizal Palapala II",
    "Roxas Village",
    "Sambag",
    "Sampaguita",
    "San Agustin",
    "San Antonio",
    "San Felix",
    "San Isidro",
    "San Isidro",
    "San Jose",
    "San Jose",
    "San Jose",
    "San Juan",
    "San Nicolas",
    "San Pedro",
    "San Pedro",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Santa Filomena",
    "Santa Rosa",
    "Santo Domingo",
    "Santo Niño Norte",
    "Santo Niño Sur",
    "Santo Rosario-Duran",
    "Seminario",
    "Simon Ledesma",
    "Sinikway",
    "So-oc",
    "South Baluarte",
    "South Fundidor",
    "South San Jose",
    "Taal",
    "Tabuc Suba",
    "Tabuc Suba",
    "Tabucan",
    "Tacas",
    "Tagbac",
    "Tanza-Esperanza",
    "Tap-oc",
    "Taytay Zone II",
    "Ticud",
    "Timawa Tanza I",
    "Timawa Tanza II",
    "Ungka",
    "Veterans Village",
    "Villa Anita",
    "West Habog-habog",
    "West Timawa",
    "Yulo Drive",
    "Yulo-Arroyo",
    "Zamora-Melliza",
  ],
};
