/** GENERATED — Region VII: 3003 barangays across 132 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "0701201000": [
    "Bahi",
    "Basacdacu",
    "Cantiguib",
    "Dangay",
    "East Poblacion",
    "Ponong",
    "San Agustin",
    "Santa Filomena",
    "Tagbuane",
    "Toril",
    "West Poblacion",
  ],
  "0701202000": [
    "Cabatang",
    "Cagongcagong",
    "Cambaol",
    "Cayacay",
    "Del Monte",
    "Katipunan",
    "La Hacienda",
    "Mahayag",
    "Napo",
    "Pagahat",
    "Poblacion",
    "Progreso",
    "Putlongcam",
    "Sudlon",
    "Untaga",
  ],
  "0701203000": [
    "Almaria",
    "Bacong",
    "Badiang",
    "Buenasuerte",
    "Candabong",
    "Casica",
    "Katipunan",
    "Linawan",
    "Lundag",
    "Poblacion",
    "Santa Cruz",
    "Suba",
    "Talisay",
    "Tanod",
    "Tawid",
    "Virgen",
  ],
  "0701204000": [
    "Angilan",
    "Bantolinao",
    "Bicahan",
    "Bitaugan",
    "Bungahan",
    "Can-omay",
    "Canlaas",
    "Cansibuan",
    "Celing",
    "Danao",
    "Danicop",
    "Mag-aso",
    "Poblacion",
    "Quinapon-an",
    "Santo Rosario",
    "Tabuan",
    "Tagubaas",
    "Tupas",
    "Ubojan",
    "Viga",
    "Villa Aurora",
  ],
  "0701205000": [
    "Buenaventura",
    "Cambanac",
    "Dasitam",
    "Guiwanon",
    "Landican",
    "Laya",
    "Libertad",
    "Montana",
    "Pamilacan",
    "Payahan",
    "Poblacion",
    "San Isidro",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Taguihon",
    "Tanday",
  ],
  "0701206000": [
    "Baucan Norte",
    "Baucan Sur",
    "Boctol",
    "Boyog Norte",
    "Boyog Proper",
    "Boyog Sur",
    "Cabad",
    "Candasig",
    "Cantalid",
    "Cantomimbo",
    "Cogon",
    "Datag Norte",
    "Datag Sur",
    "Del Carmen Este (Pob.)",
    "Del Carmen Norte (Pob.)",
    "Del Carmen Sur (Pob.)",
    "Del Carmen Weste (Pob.)",
    "Del Rosario",
    "Dorol",
    "Haguilanan Grande",
    "Hanopol Este",
    "Hanopol Norte",
    "Hanopol Weste",
    "Magsija",
    "Maslog",
    "Sagasa",
    "Sal-ing",
    "San Isidro",
    "San Roque",
    "Santo Niño",
    "Tagustusan",
  ],
  "0701207000": [
    "Aloja",
    "Behind The Clouds",
    "Cabacnitan",
    "Cambacay",
    "Cantigdas",
    "Garcia",
    "Janlud",
    "Poblacion Norte",
    "Poblacion Sur",
    "Poblacion Vieja",
    "Quezon",
    "Quirino",
    "Rizal",
    "Rosariohan",
    "Santa Cruz",
  ],
  "0701208000": [
    "Bonifacio",
    "Bugang Norte",
    "Bugang Sur",
    "Cabacnitan",
    "Cambigsi",
    "Campagao",
    "Cansumbol",
    "Dagohoy",
    "Owac",
    "Poblacion",
    "Quezon",
    "Riverside",
    "Rizal",
    "Roxas",
    "Subayon",
    "Villa Aurora",
    "Villa Suerte",
    "Yanaya",
    "Zamora",
  ],
  "0701209000": [
    "Anonang",
    "Asinan",
    "Bago",
    "Baluarte",
    "Bantuan",
    "Bato",
    "Bonotbonot",
    "Bugaong",
    "Cambuhat",
    "Cambus-oc",
    "Cangawa",
    "Cantomugcad",
    "Cantores",
    "Cantuba",
    "Catigbian",
    "Cawag",
    "Cruz",
    "Dait",
    "Eastern Cabul-an",
    "Hunan",
    "Lapacan Norte",
    "Lapacan Sur",
    "Lubang",
    "Lusong",
    "Magkaya",
    "Merryland",
    "Nueva Granada",
    "Nueva Montana",
    "Overland",
    "Panghagban",
    "Poblacion",
    "Puting Bato",
    "Rufo Hill",
    "Sweetland",
    "Western Cabul-an",
  ],
  "0701210000": [
    "Abucayan Norte",
    "Abucayan Sur",
    "Banlasan",
    "Bentig",
    "Binogawan",
    "Bonbon",
    "Cabayugan",
    "Cabudburan",
    "Calunasan",
    "Camias",
    "Canguha",
    "Catmonan",
    "Desamparados (Pob.)",
    "Kahayag",
    "Kinabag-an",
    "Labuon",
    "Lawis",
    "Liboron",
    "Lo-oc",
    "Lomboy",
    "Lucob",
    "Madangog",
    "Magtongtong",
    "Mandaug",
    "Mantatao",
    "Sampoangon",
    "San Isidro",
    "Santa Cruz (Pob.)",
    "Sojoton",
    "Talisay",
    "Tinibgan",
    "Tultugan",
    "Ulbujan",
  ],
  "0701211000": [
    "Abihilan",
    "Anoling",
    "Boyo-an",
    "Cadapdapan",
    "Cambane",
    "Can-olin",
    "Canawa",
    "Cogtong",
    "La Union",
    "Luan",
    "Lungsoda-an",
    "Mahangin",
    "Pagahat",
    "Panadtaran",
    "Panas",
    "Poblacion",
    "San Isidro",
    "Tambongan",
    "Tawid",
    "Tubod",
    "Tugas",
  ],
  "0701212000": [
    "Alegria",
    "Bicao",
    "Buenavista",
    "Buenos Aires",
    "Calatrava",
    "El Progreso",
    "El Salvador",
    "Guadalupe",
    "Katipunan",
    "La Libertad",
    "La Paz",
    "La Salvacion",
    "La Victoria",
    "Matin-ao",
    "Montehermoso",
    "Montesuerte",
    "Montesunting",
    "Montevideo",
    "Nueva Fuerza",
    "Nueva Vida Este",
    "Nueva Vida Norte",
    "Nueva Vida Sur",
    "Poblacion Norte",
    "Poblacion Sur",
    "Tambo-an",
    "Vallehermoso",
    "Villaflor",
    "Villafuerte",
    "Villarcayo",
  ],
  "0701213000": [
    "Alegria",
    "Ambuan",
    "Baang",
    "Bagtic",
    "Bongbong",
    "Cambailan",
    "Candumayao",
    "Causwagan Norte",
    "Hagbuaya",
    "Haguilanan",
    "Kang-iras",
    "Libertad Sur",
    "Liboron",
    "Mahayag Norte",
    "Mahayag Sur",
    "Maitum",
    "Mantasida",
    "Poblacion",
    "Poblacion Weste",
    "Rizal",
    "Sinakayanan",
    "Triple Union",
  ],
  "0701214000": [
    "Bacani",
    "Bogtongbod",
    "Bonbon",
    "Bontud",
    "Buacao",
    "Buangan",
    "Cabog",
    "Caboy",
    "Caluwasan",
    "Candajec",
    "Cantoyoc",
    "Comaang",
    "Danahao",
    "Katipunan",
    "Lajog",
    "Mataub",
    "Nahawan",
    "Poblacion Centro",
    "Poblacion Norte",
    "Poblacion Sur",
    "Tangaran",
    "Tontunan",
    "Tubod",
    "Villaflor",
  ],
  "0701215000": [
    "Anislag",
    "Canangca-an",
    "Canapnapan",
    "Cancatac",
    "Pandol",
    "Poblacion",
    "Sambog",
    "Tanday",
  ],
  "0701216000": [
    "De la Paz",
    "Fatima",
    "Loreto",
    "Lourdes",
    "Malayo Norte",
    "Malayo Sur",
    "Monserrat",
    "New Lourdes",
    "Patrocinio",
    "Poblacion",
    "Rosario",
    "Salvador",
    "San Roque",
    "Upper de la Paz",
  ],
  "0701217000": [
    "Babag",
    "Cagawasan",
    "Cagawitan",
    "Caluasan",
    "Can-oling",
    "Candelaria",
    "Estaca",
    "La Esperanza",
    "Mahayag",
    "Malitbog",
    "Poblacion",
    "San Miguel",
    "San Vicente",
    "Santa Cruz",
    "Villa Aurora",
  ],
  "0701218000": [
    "Cabatuan",
    "Cantubod",
    "Carbon",
    "Concepcion",
    "Dagohoy",
    "Hibale",
    "Magtangtang",
    "Nahud",
    "Poblacion",
    "Remedios",
    "San Carlos",
    "San Miguel",
    "Santa Fe",
    "Santo Niño",
    "Tabok",
    "Taming",
    "Villa Anunciado",
  ],
  "0701219000": [
    "Biking",
    "Bingag",
    "Catarman",
    "Dao",
    "Mariveles",
    "Mayacabac",
    "Poblacion",
    "San Isidro",
    "Songculan",
    "Tabalong",
    "Tinago",
    "Totolan",
  ],
  "0701220000": [
    "Abihid",
    "Alemania",
    "Baguhan",
    "Bakilid",
    "Balbalan",
    "Banban",
    "Bauhugan",
    "Bilisan",
    "Cabagakian",
    "Cabanbanan",
    "Cadap-agan",
    "Cambacol",
    "Cambayaon",
    "Canhayupon",
    "Canlambong",
    "Casingan",
    "Catugasan",
    "Datag",
    "Guindaguitan",
    "Guingoyuran",
    "Ile",
    "Lapsaon",
    "Limokon Ilaod",
    "Limokon Ilaya",
    "Luyo",
    "Malijao",
    "Oac",
    "Pagsa",
    "Pangihawan",
    "Puangyuta",
    "Sawang",
    "Tangohay",
    "Taongon Cabatuan",
    "Taongon Can-andam",
    "Tawid Bitaog",
  ],
  "0701221000": [
    "Alejawan",
    "Angilan",
    "Anibongan",
    "Bangwalog",
    "Cansuhay",
    "Danao",
    "Duay",
    "Guinsularan",
    "Imelda",
    "Itum",
    "Langkis",
    "Lobogon",
    "Madua Norte",
    "Madua Sur",
    "Mambool",
    "Mawi",
    "Payao",
    "San Antonio (Pob.)",
    "San Isidro",
    "San Pedro",
    "Taytay",
  ],
  "0701222000": [
    "Abijilan",
    "Antipolo",
    "Basiao",
    "Cagwang",
    "Calma",
    "Cambuyo",
    "Canayaon East",
    "Canayaon West",
    "Candanas",
    "Candulao",
    "Catmon",
    "Cayam",
    "Cupa",
    "Datag",
    "Estaca",
    "Libertad",
    "Lungsodaan East",
    "Lungsodaan West",
    "Malinao",
    "Manaba",
    "Pasong",
    "Poblacion East",
    "Poblacion West",
    "Sacaon",
    "Sampong",
    "Tabuan",
    "Togbongon",
    "Ulbujan East",
    "Ulbujan West",
    "Victoria",
  ],
  "0701223000": [
    "Basdio",
    "Bato",
    "Bayong",
    "Biabas",
    "Bulawan",
    "Cabantian",
    "Canhaway",
    "Cansiwang",
    "Casbu",
    "Catungawan Norte",
    "Catungawan Sur",
    "Guinacot",
    "Guio-ang",
    "Lombog",
    "Mayuga",
    "Sawang (Pob.)",
    "Tabajan (Pob.)",
    "Tabunok",
    "Trinidad",
  ],
  "0701224000": [
    "Anonang",
    "Badiang",
    "Baguhan",
    "Bahan",
    "Banahao",
    "Baogo",
    "Bugang",
    "Cagawasan",
    "Cagayan",
    "Cambitoon",
    "Canlinte",
    "Cawayan",
    "Cogon",
    "Cuaming",
    "Dagnawan",
    "Dagohoy",
    "Dait Sur",
    "Datag",
    "Fatima",
    "Hambongan",
    "Ilaud (Pob.)",
    "Ilaya",
    "Ilihan",
    "Lapacan Norte",
    "Lapacan Sur",
    "Lawis",
    "Liloan Norte",
    "Liloan Sur",
    "Lomboy",
    "Lonoy Cainsican",
    "Lonoy Roma",
    "Lutao",
    "Luyo",
    "Mabuhay",
    "Maria Rosario",
    "Nabuad",
    "Napo",
    "Ondol",
    "Poblacion",
    "Riverside",
    "Saa",
    "San Isidro",
    "San Jose",
    "Santo Niño",
    "Santo Rosario",
    "Sua",
    "Tambook",
    "Tungod",
    "U-og",
    "Ubujan",
  ],
  "0701225000": [
    "Alejawan",
    "Balili",
    "Boctol",
    "Bunga Ilaya",
    "Bunga Mar",
    "Buyog",
    "Cabunga-an",
    "Calabacita",
    "Cambugason",
    "Can-ipol",
    "Can-uba",
    "Can-upao",
    "Canjulao",
    "Cantagay",
    "Cantuyoc",
    "Faraon",
    "Ipil",
    "Kinagbaan",
    "Laca",
    "Larapan",
    "Lonoy",
    "Looc",
    "Malbog",
    "Mayana",
    "Naatang",
    "Nausok",
    "Odiong",
    "Pagina",
    "Pangdan",
    "Poblacion",
    "Tejero",
    "Tubod Mar",
    "Tubod Monte",
  ],
  "0701226000": [
    "Alumar",
    "Banacon",
    "Buyog",
    "Cabasakan",
    "Campao Occidental",
    "Campao Oriental",
    "Cangmundo",
    "Carlos P. Garcia",
    "Corte Baud",
    "Handumon",
    "Jagoliao",
    "Jandayan Norte",
    "Jandayan Sur",
    "Mahanay",
    "Nasingin",
    "Pandanon",
    "Poblacion",
    "Saguise",
    "Salog",
    "San Jose",
    "Santo Niño",
    "Taytay",
    "Tugas",
    "Tulang",
  ],
  "0701227000": [
    "Banban",
    "Bonkokan Ilaya",
    "Bonkokan Ubos",
    "Calvario",
    "Candulang",
    "Catugasan",
    "Cayupo",
    "Cogon",
    "Jambawan",
    "La Fortuna",
    "Lomanoy",
    "Macalingan",
    "Malinao East",
    "Malinao West",
    "Nagsulay",
    "Poblacion",
    "Taug",
    "Tiguis",
  ],
  "0701228000": [
    "Agape",
    "Alegria Norte",
    "Alegria Sur",
    "Bonbon",
    "Botoc Occidental",
    "Botoc Oriental",
    "Calvario",
    "Concepcion",
    "Hinawanan",
    "Las Salinas Norte",
    "Las Salinas Sur",
    "Palo",
    "Poblacion Ibabao",
    "Poblacion Ubos",
    "Sagnap",
    "Tambangan",
    "Tangcasan Norte",
    "Tangcasan Sur",
    "Tayong Occidental",
    "Tayong Oriental",
    "Tocdog Dacu",
    "Tocdog Ilaya",
    "Villalimpia",
    "Yanangan",
  ],
  "0701229000": [
    "Agape",
    "Alegria",
    "Bagumbayan",
    "Bahian",
    "Bonbon Lower",
    "Bonbon Upper",
    "Buenavista",
    "Bugho",
    "Cabadiangan",
    "Calunasan Norte",
    "Calunasan Sur",
    "Camayaan",
    "Cambance",
    "Candabong",
    "Candasag",
    "Canlasid",
    "Gon-ob",
    "Gotozon",
    "Jimilian",
    "Oy",
    "Poblacion Ondol",
    "Poblacion Sawang",
    "Quinoguitan",
    "Taytay",
    "Tigbao",
    "Ugpong",
    "Valladolid",
    "Villaflor",
  ],
  "0701230000": [
    "Agsoso",
    "Badbad Occidental",
    "Badbad Oriental",
    "Bagacay Katipunan",
    "Bagacay Kawayan",
    "Bagacay Saong",
    "Bahi",
    "Basac",
    "Basdacu",
    "Basdio",
    "Biasong",
    "Bongco",
    "Bugho",
    "Cabacongan",
    "Cabadug",
    "Cabug",
    "Calayugan Norte",
    "Calayugan Sur",
    "Cambaquiz",
    "Campatud",
    "Candaigan",
    "Canhangdon Occidental",
    "Canhangdon Oriental",
    "Canigaan",
    "Canmaag",
    "Canmanoc",
    "Cansuagwit",
    "Cansubayon",
    "Cantam-is Bago",
    "Cantam-is Baslay",
    "Cantaongon",
    "Cantumocad",
    "Catagbacan Handig",
    "Catagbacan Norte",
    "Catagbacan Sur",
    "Cogon Norte (Pob.)",
    "Cogon Sur",
    "Cuasi",
    "Genomoan",
    "Lintuan",
    "Looc",
    "Mocpoc Norte",
    "Mocpoc Sur",
    "Moto Norte (Pob.)",
    "Moto Sur (Pob.)",
    "Nagtuang",
    "Napo (Pob.)",
    "Nueva Vida",
    "Panangquilon",
    "Pantudlan",
    "Pig-ot",
    "Pondol",
    "Quinobcoban",
    "Sondol",
    "Song-on",
    "Talisay",
    "Tan-awan",
    "Tangnan",
    "Taytay",
    "Ticugan",
    "Tiwi",
    "Tontonan",
    "Tubodacu",
    "Tubodio",
    "Tubuan",
    "Ubayon",
    "Ubojan",
  ],
  "0701231000": [
    "Abaca",
    "Abad Santos",
    "Aguipo",
    "Baybayon",
    "Bulawan",
    "Cabidian",
    "Cawayanan",
    "Concepcion",
    "Del Mar",
    "Lungsoda-an",
    "Marcelo",
    "Minol",
    "Paraiso",
    "Poblacion I",
    "Poblacion II",
    "San Isidro",
    "San Jose",
    "San Rafael",
    "San Roque",
    "Tambo",
    "Tangkigan",
    "Valaga",
  ],
  "0701232000": [
    "Agahay",
    "Aliguay",
    "Anislag",
    "Bayacabac",
    "Bood",
    "Busao",
    "Cabawan",
    "Candavid",
    "Dipatlong",
    "Guiwanon",
    "Jandig",
    "Lagtangon",
    "Lincod",
    "Pagnitoan",
    "Poblacion",
    "Punsod",
    "Punta Cruz",
    "San Isidro",
    "San Roque",
    "San Vicente",
    "Tinibgan",
    "Toril",
  ],
  "0701233000": [
    "Bil-isan",
    "Bolod",
    "Danao",
    "Doljo",
    "Libaong",
    "Looc",
    "Lourdes",
    "Poblacion",
    "Tangnan",
    "Tawala",
  ],
  "0701234000": [
    "Aurora",
    "Bagacay",
    "Bagumbayan",
    "Bayong",
    "Buenasuerte",
    "Cagawasan",
    "Cansungay",
    "Catagda-an",
    "Del Pilar",
    "Estaca",
    "Ilaud",
    "Inaghuban",
    "La Suerte",
    "Lumbay",
    "Lundag",
    "Pamacsalan",
    "Poblacion",
    "Rizal",
    "San Carlos",
    "San Isidro",
    "San Vicente",
  ],
  "0701235000": [
    "Aguining",
    "Basiao",
    "Baud",
    "Bayog",
    "Bogo",
    "Bonbonon",
    "Butan",
    "Campamanog",
    "Canmangao",
    "Gaus",
    "Kabangkalan",
    "Lapinig",
    "Lipata",
    "Poblacion",
    "Popoo",
    "Saguise",
    "San Jose",
    "San Vicente",
    "Santo Rosario",
    "Tilmobo",
    "Tugas",
    "Tugnao",
    "Villa Milagrosa",
  ],
  "0701236000": [
    "Calangahan",
    "Canmano",
    "Canmaya Centro",
    "Canmaya Diot",
    "Dagnawan",
    "Kabasacan",
    "Kagawasan",
    "Katipunan",
    "Langtad",
    "Libertad Norte",
    "Libertad Sur",
    "Mantalongon",
    "Poblacion",
    "Sagbayan Sur",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Ramon",
    "San Roque",
    "San Vicente Norte",
    "San Vicente Sur",
    "Santa Catalina",
    "Santa Cruz",
    "Ubojan",
  ],
  "0701237000": [
    "Abehilan",
    "Baryong Daan",
    "Baunos",
    "Cabanugan",
    "Caimbang",
    "Cambansag",
    "Candungao",
    "Cansague Norte",
    "Cansague Sur",
    "Causwagan Sur",
    "Masonoy",
    "Poblacion",
  ],
  "0701238000": [
    "Bayongan",
    "Bugang",
    "Cabangahan",
    "Caluasan",
    "Camanaga",
    "Cambangay Norte",
    "Capayas",
    "Corazon",
    "Garcia",
    "Hagbuyo",
    "Kagawasan",
    "Mahayag",
    "Poblacion",
    "San Isidro",
    "San Jose",
    "San Vicente",
    "Santo Niño",
    "Tomoc",
  ],
  "0701239000": [
    "Bayawahan",
    "Cabancalan",
    "Calinga-an",
    "Calinginan Norte",
    "Calinginan Sur",
    "Cambagui",
    "Ewon",
    "Guinob-an",
    "Lagtangan",
    "Licolico",
    "Lobgob",
    "Magsaysay",
    "Poblacion",
  ],
  "0701240000": [
    "Abachanan",
    "Anibongan",
    "Bugsoc",
    "Cahayag",
    "Canlangit",
    "Canta-ub",
    "Casilay",
    "Danicop",
    "Dusita",
    "La Union",
    "Lataban",
    "Magsaysay",
    "Man-od",
    "Matin-ao",
    "Poblacion",
    "Salvador",
    "San Agustin",
    "San Isidro",
    "San Jose",
    "San Juan",
    "Santa Cruz",
    "Villa Garcia",
  ],
  "0701241000": [
    "Abucay Norte",
    "Abucay Sur",
    "Badiang",
    "Bahaybahay",
    "Cambuac Norte",
    "Cambuac Sur",
    "Canagong",
    "Libjo",
    "Poblacion I",
    "Poblacion II",
  ],
  "0701242000": [
    "Bool",
    "Booy",
    "Cabawan",
    "Cogon",
    "Dampas",
    "Dao",
    "Manga",
    "Mansasa",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "San Isidro",
    "Taloto",
    "Tiptip",
    "Ubujan",
  ],
  "0701243000": [
    "Bagacay",
    "Balintawak",
    "Burgos",
    "Busalian",
    "Calituban",
    "Cataban",
    "Guindacpan",
    "Magsaysay",
    "Mahanay",
    "Nocnocan",
    "Poblacion",
    "Rizal",
    "Sag",
    "San Agustin",
    "San Carlos",
    "San Francisco",
    "San Isidro",
    "San Jose",
    "San Pedro",
    "San Roque",
    "Santo Niño",
    "Sikatuna",
    "Suba",
    "Tanghaligue",
    "Zamora",
  ],
  "0701244000": [
    "Banlasan",
    "Bongbong",
    "Catoogan",
    "Guinobatan",
    "Hinlayagan Ilaud",
    "Hinlayagan Ilaya",
    "Kauswagan",
    "Kinan-oan",
    "La Union",
    "La Victoria",
    "Mabuhay Cabigohan",
    "Mahagbu",
    "Manuel M. Roxas",
    "Poblacion",
    "San Isidro",
    "San Vicente",
    "Santo Tomas",
    "Soom",
    "Tagum Norte",
    "Tagum Sur",
  ],
  "0701245000": [
    "Bagongbanwa",
    "Banlasan",
    "Batasan",
    "Bilangbilangan",
    "Bosongon",
    "Buenos Aires",
    "Bunacan",
    "Cabulihan",
    "Cahayag",
    "Cawayanan",
    "Centro (Pob.)",
    "Genonocan",
    "Guiwanon",
    "Ilihan Norte",
    "Ilihan Sur",
    "Libertad",
    "Macaas",
    "Matabao",
    "Mocaboc Island",
    "Panadtaran",
    "Panaytayon",
    "Pandan",
    "Pangapasan",
    "Pinayagan Norte",
    "Pinayagan Sur",
    "Pooc Occidental (Pob.)",
    "Pooc Oriental (Pob.)",
    "Potohan",
    "Talenceras",
    "Tan-awan",
    "Tinangnan",
    "Ubay Island",
    "Ubojan",
    "Villanueva",
  ],
  "0701246000": [
    "Achila",
    "Bay-ang",
    "Benliw",
    "Biabas",
    "Bongbong",
    "Bood",
    "Buenavista",
    "Bulilis",
    "Cagting",
    "Calanggaman",
    "California",
    "Camali-an",
    "Camambugan",
    "Casate",
    "Cuya",
    "Fatima",
    "Gabi",
    "Governor Boyles",
    "Guintabo-an",
    "Hambabauran",
    "Humayhumay",
    "Ilihan",
    "Imelda",
    "Juagdan",
    "Katarungan",
    "Lomangog",
    "Los Angeles",
    "Pag-asa",
    "Pangpang",
    "Poblacion",
    "San Francisco",
    "San Isidro",
    "San Pascual",
    "San Vicente",
    "Sentinila",
    "Sinandigan",
    "Tapal",
    "Tapon",
    "Tintinan",
    "Tipolo",
    "Tubog",
    "Tuboran",
    "Union",
    "Villa Teresita",
  ],
  "0701247000": [
    "Adlawan",
    "Anas",
    "Anonang",
    "Anoyon",
    "Balingasao",
    "Banderahan",
    "Botong",
    "Buyog",
    "Canduao Occidental",
    "Canduao Oriental",
    "Canlusong",
    "Canmanico",
    "Cansibao",
    "Catug-a",
    "Cutcutan",
    "Danao",
    "Genoveva",
    "Ginopolan",
    "La Victoria",
    "Lantang",
    "Limocon",
    "Loctob",
    "Magsaysay",
    "Marawis",
    "Maubo",
    "Nailo",
    "Omjon",
    "Pangi-an",
    "Poblacion Occidental",
    "Poblacion Oriental",
    "Simang",
    "Taug",
    "Tausion",
    "Taytay",
    "Ticum",
  ],
  "0701248000": [
    "Bilangbilangan Dako",
    "Bilangbilangan Diot",
    "Hingotanan East",
    "Hingotanan West",
    "Liberty",
    "Malingin",
    "Mandawa",
    "Maomawan",
    "Nueva Esperanza",
    "Nueva Estrella",
    "Pinamgo",
    "Poblacion",
    "Puerto San Pedro",
    "Sagasa",
    "Tuboran",
  ],
  "0702201000": [
    "Cabadiangan",
    "Cabil-isan",
    "Candabong",
    "Lawaan",
    "Manga",
    "Palanas",
    "Poblacion",
    "Polo",
    "Salagmaya",
  ],
  "0702202000": [
    "Atabay",
    "Daan-Lungsod",
    "Guiwang",
    "Nug-as",
    "Pasol",
    "Poblacion",
    "Pugalo",
    "San Agustin",
  ],
  "0702203000": [
    "Compostela",
    "Guadalupe",
    "Legaspi",
    "Lepanto",
    "Madridejos",
    "Montpeller",
    "Poblacion",
    "Santa Filomena",
    "Valencia",
  ],
  "0702204000": [
    "Angilan",
    "Bojo",
    "Bonbon",
    "Esperanza",
    "Kandingan",
    "Kantabogon",
    "Kawasan",
    "Olango",
    "Poblacion",
    "Punay",
    "Rosario",
    "Saksak",
    "Tampa-an",
    "Toyokon",
    "Zaragosa",
  ],
  "0702205000": [
    "Alambijud",
    "Anajao",
    "Apo",
    "Balaas",
    "Balisong",
    "Binlod",
    "Bogo",
    "Bug-ot",
    "Bulasa",
    "Butong",
    "Calagasan",
    "Canbantug",
    "Canbanua",
    "Cansuje",
    "Capio-an",
    "Casay",
    "Catang",
    "Colawin",
    "Conalum",
    "Guiwanon",
    "Gutlang",
    "Jampang",
    "Jomgao",
    "Lamacan",
    "Langtad",
    "Langub",
    "Lapay",
    "Lengigon",
    "Linut-od",
    "Mabasa",
    "Mandilikit",
    "Mompeller",
    "Panadtaran",
    "Poblacion",
    "Sua",
    "Sumaguan",
    "Tabayag",
    "Talaga",
    "Talaytay",
    "Talo-ot",
    "Tiguib",
    "Tulang",
    "Tulic",
    "Ubaub",
    "Usmad",
  ],
  "0702206000": [
    "Agbanga",
    "Agtugop",
    "Bago",
    "Bairan",
    "Banban",
    "Baye",
    "Bog-o",
    "Kaluangan",
    "Lanao",
    "Langub",
    "Looc Norte",
    "Lunas",
    "Magcalape",
    "Manguiao",
    "New Bago",
    "Owak",
    "Poblacion",
    "Saksak",
    "San Isidro",
    "San Roque",
    "Santa Lucia",
    "Santa Rita",
    "Tag-amakan",
    "Tagbubonga",
    "Tubigagmanok",
    "Tubod",
    "Ubogon",
  ],
  "0702207000": [
    "Alawijao",
    "Balhaan",
    "Banhigan",
    "Basak",
    "Basiao",
    "Bato",
    "Bugas",
    "Calangcang",
    "Candiis",
    "Dagatan",
    "Dobdob",
    "Ginablan",
    "Lambug",
    "Malabago",
    "Malhiao",
    "Manduyong",
    "Matutinao",
    "Patong",
    "Poblacion",
    "Sanlagan",
    "Santicon",
    "Sohoton",
    "Sulsugan",
    "Talayong",
    "Taytay",
    "Tigbao",
    "Tiguib",
    "Tubod",
    "Zaragosa",
  ],
  "0702208000": [
    "Abucayan",
    "Aliwanay",
    "Arpili",
    "Baliwagan (Pob.)",
    "Bayong",
    "Biasong",
    "Buanoy",
    "Cabagdalan",
    "Cabasiangan",
    "Cambuhawe",
    "Cansomoroy",
    "Cantibas",
    "Cantuod",
    "Duangan",
    "Gaas",
    "Ginatilan",
    "Hingatmonan",
    "Lamesa",
    "Liki",
    "Luca",
    "Matun-og",
    "Nangka",
    "Pondol",
    "Prenza",
    "Santa Cruz-Santo Niño (Pob.)",
    "Singsing",
    "Sunog",
    "Vito",
  ],
  "0702209000": [
    "Atop-atop",
    "Baigad",
    "Bantigue (Pob.)",
    "Baod",
    "Binaobao (Pob.)",
    "Botigues",
    "Doong",
    "Guiwanon",
    "Hilotongan",
    "Kabac",
    "Kabangbang",
    "Kampingganon",
    "Kangkaibe",
    "Lipayran",
    "Luyongbaybay",
    "Mojon",
    "Obo-ob",
    "Patao",
    "Putian",
    "Sillon",
    "Suba (Pob.)",
    "Sulangan",
    "Sungko",
    "Tamiao",
    "Ticad (Pob.)",
  ],
  "0702210000": [
    "Azucena",
    "Bagakay",
    "Balao",
    "Bolocboloc",
    "Budbud",
    "Bugtong Kawayan",
    "Cabcaban",
    "Cagay",
    "Campangga",
    "Candugay",
    "Dakit",
    "Giloctog",
    "Giwanon",
    "Guibuangan",
    "Gunting",
    "Hilasgasan",
    "Japitan",
    "Kalubihan",
    "Kangdampas",
    "Luhod",
    "Lupo",
    "Luyo",
    "Maghanoy",
    "Maigang",
    "Malolos",
    "Mantalongon",
    "Mantayupan",
    "Mayana",
    "Minolos",
    "Nabunturan",
    "Nasipit",
    "Pancil",
    "Pangpang",
    "Paril",
    "Patupat",
    "Poblacion",
    "San Rafael",
    "Santa Ana",
    "Sayaw",
    "Tal-ot",
    "Tubod",
    "Vito",
  ],
  "0702211000": [
    "Anonang Norte",
    "Anonang Sur",
    "Banban",
    "Binabag",
    "Bungtod (Pob.)",
    "Carbon (Pob.)",
    "Cayang",
    "Cogon (Pob.)",
    "Dakit",
    "Don Pedro Rodriguez",
    "Gairan",
    "Guadalupe",
    "La Paz",
    "La Purisima Concepcion (Pob.)",
    "Libertad",
    "Lourdes (Pob.)",
    "Malingin",
    "Marangog",
    "Nailon",
    "Odlot",
    "Pandan",
    "Polambato",
    "Sambag (Pob.)",
    "San Vicente (Pob.)",
    "Santo Niño",
    "Santo Rosario (Pob.)",
    "Siocon",
    "Sudlonon",
    "Taytayan",
  ],
  "0702212000": [
    "Arbor",
    "Baclayan",
    "El Pardo",
    "Granada",
    "Lower Becerril",
    "Lunop",
    "Nangka",
    "Poblacion",
    "San Antonio",
    "South Granada",
    "Upper Becerril",
  ],
  "0702213000": [
    "Bagacay",
    "Bili",
    "Bingay",
    "Bongdo",
    "Bongdo Gua",
    "Bongoyan",
    "Cadaruhan",
    "Cajel",
    "Campusong",
    "Clavera",
    "Don Gregorio Antigua",
    "Laaw",
    "Lugo",
    "Managase",
    "Poblacion",
    "Sagay",
    "San Jose",
    "Tabunan",
    "Tagnucan",
  ],
  "0702214000": [
    "Bolinawan",
    "Buenavista",
    "Calidngan",
    "Can-asujan",
    "Guadalupe",
    "Liburon",
    "Napo",
    "Ocana",
    "Perrelos",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Tuyom",
    "Valencia",
    "Valladolid",
  ],
  "0702215000": [
    "Baring",
    "Cantipay",
    "Cantukong",
    "Cantumog",
    "Caurasan",
    "Cogon East",
    "Cogon West",
    "Corte",
    "Dawis Norte",
    "Dawis Sur",
    "Hagnaya",
    "Ipil",
    "Lanipga",
    "Liboron",
    "Lower Natimao-an",
    "Luyang",
    "Poblacion",
    "Puente",
    "Sac-on",
    "Triumfo",
    "Upper Natimao-an",
  ],
  "0702216000": [
    "Agsuwao",
    "Amancion",
    "Anapog",
    "Bactas",
    "Basak",
    "Binongkalan",
    "Bongyas",
    "Cabungaan",
    "Cambangkaya",
    "Can-ibuang",
    "Catmondaan",
    "Corazon (Pob.)",
    "Duyan",
    "Flores (Pob.)",
    "Ginabucan",
    "Macaas",
    "Panalipan",
    "San Jose Pob.",
    "Tabili",
    "Tinabyonan",
  ],
  "0702218000": [
    "Bagalnga",
    "Basak",
    "Buluang",
    "Cabadiangan",
    "Cambayog",
    "Canamucan",
    "Cogon",
    "Dapdap",
    "Estaca",
    "Lupa",
    "Magay",
    "Mulao",
    "Panangban",
    "Poblacion",
    "Tag-ube",
    "Tamiao",
    "Tubigan",
  ],
  "0702219000": [
    "Cabangahan",
    "Cansaga",
    "Casili",
    "Danglag",
    "Garing",
    "Jugan",
    "Lamac",
    "Lanipga",
    "Nangka",
    "Panas",
    "Panoypoy",
    "Pitogo",
    "Poblacion Occidental",
    "Poblacion Oriental",
    "Polog",
    "Pulpogan",
    "Sacsac",
    "Tayud",
    "Tilhaong",
    "Tolotolo",
    "Tugbongan",
  ],
  "0702220000": [
    "Alegria",
    "Bangbang",
    "Buagsong",
    "Catarman",
    "Cogon",
    "Dapitan",
    "Day-as",
    "Gabi",
    "Gilutongan",
    "Ibabao",
    "Pilipog",
    "Poblacion",
    "San Miguel",
  ],
  "0702221000": [
    "Aguho",
    "Bagay",
    "Bakhawan",
    "Bateria",
    "Bitoon",
    "Calape",
    "Carnaza",
    "Dalingding",
    "Lanao",
    "Logon",
    "Malbago",
    "Malingin",
    "Maya",
    "Pajo",
    "Paypay",
    "Poblacion",
    "Talisay",
    "Tapilon",
    "Tinubdan",
    "Tominjao",
  ],
  "0702222000": [
    "Ablayan",
    "Babayongan",
    "Balud",
    "Banhigan",
    "Bulak",
    "Caleriohan",
    "Caliongan",
    "Casay",
    "Catolohan",
    "Cawayan",
    "Consolacion",
    "Coro",
    "Dugyan",
    "Dumalan",
    "Jolomaynon",
    "Lanao",
    "Langkas",
    "Lumbang",
    "Malones",
    "Maloray",
    "Mananggal",
    "Manlapay",
    "Mantalongon",
    "Nalhub",
    "Obo",
    "Obong",
    "Panas",
    "Poblacion",
    "Sacsac",
    "Salug",
    "Tabon",
    "Tapun",
    "Tuba",
  ],
  "0702223000": [
    "Baliang",
    "Bayabas",
    "Binaliw",
    "Cabungahan",
    "Cagat-Lamac",
    "Cahumayan",
    "Cambanay",
    "Cambubho",
    "Cogon-Cruz",
    "Danasan",
    "Dungga",
    "Dunggoan",
    "Guinacot",
    "Guinsay",
    "Ibo",
    "Langosig",
    "Lawaan",
    "Licos",
    "Looc",
    "Magtagobtob",
    "Malapoc",
    "Manlayag",
    "Mantija",
    "Masaba",
    "Maslog",
    "Nangka",
    "Oguis",
    "Pili",
    "Poblacion",
    "Quisol",
    "Sabang",
    "Sacsac",
    "Sandayong Norte",
    "Sandayong Sur",
    "Santa Rosa",
    "Santican",
    "Sibacan",
    "Suba",
    "Taboc",
    "Taytay",
    "Togonon",
    "Tuburan Sur",
  ],
  "0702224000": [
    "Balaygtiki",
    "Bitoon",
    "Bulak",
    "Bullogan",
    "Calaboon",
    "Camboang",
    "Candabong",
    "Cogon",
    "Cotcoton",
    "Doldol",
    "Ilaya (Pob.)",
    "Kabalaasnan",
    "Kabatbatan",
    "Kambanog",
    "Kang-actol",
    "Kanghalo",
    "Kanghumaod",
    "Kanguha",
    "Kantangkas",
    "Kanyuko",
    "Kolabtingon",
    "Lamak",
    "Lawaan",
    "Liong",
    "Manlapay",
    "Masa",
    "Matalao",
    "Paculob",
    "Panlaan",
    "Pawa",
    "Poblacion Central",
    "Poblacion Looc",
    "Poblacion Sima",
    "Tangil",
    "Tapon",
    "Tubod-Bitoon",
    "Tubod-Dugoan",
  ],
  "0702225000": [
    "Anao",
    "Cagsing",
    "Calabawan",
    "Cambagte",
    "Campisong",
    "Canorong",
    "Guiwanon",
    "Looc",
    "Malatbo",
    "Mangaco",
    "Palanas",
    "Poblacion",
    "Salamanca",
    "San Roque",
  ],
  "0702227000": [
    "Cabadiangan",
    "Calero",
    "Catarman",
    "Cotcot",
    "Jubay",
    "Lataban",
    "Mulao",
    "Poblacion",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Tabla",
    "Tayud",
    "Yati",
  ],
  "0702228000": [
    "Bunakan",
    "Kangwayan",
    "Kaongkod",
    "Kodia",
    "Maalat",
    "Malbago",
    "Mancilang",
    "Pili",
    "Poblacion",
    "San Agustin",
    "Tabagak",
    "Talangnan",
    "Tarong",
    "Tugas",
  ],
  "0702229000": [
    "Armeña",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Cerdeña",
    "Labrador",
    "Lombo",
    "Looc",
    "Mahanlud",
    "Mindanao",
    "Montañeza",
    "Salmeron",
    "Santo Niño",
    "Sorsogon",
    "Tolosa",
  ],
  "0702231000": [
    "Antipolo",
    "Canhabagat",
    "Caputatan Norte",
    "Caputatan Sur",
    "Curva",
    "Daanlungsod",
    "Dalingding Sur",
    "Dayhagon",
    "Don Virgilio Gonzales",
    "Gibitngil",
    "Kawit",
    "Lamintak Norte",
    "Lamintak Sur",
    "Luy-a",
    "Maharuhay",
    "Mahawak",
    "Panugnawan",
    "Poblacion",
    "Tindog",
  ],
  "0702232000": [
    "Cadulawan",
    "Calajo-an",
    "Camp 7",
    "Camp 8",
    "Cuanos",
    "Guindaruhan",
    "Linao",
    "Manduang",
    "Pakigne",
    "Poblacion Ward I",
    "Poblacion Ward II",
    "Poblacion Ward III",
    "Poblacion Ward IV",
    "Tubod",
    "Tulay",
    "Tunghaan",
    "Tungkil",
    "Tungkop",
    "Vito",
  ],
  "0702233000": [
    "Agbalanga",
    "Bala",
    "Balabagon",
    "Basdiot",
    "Batadbatad",
    "Bugho",
    "Buguil",
    "Busay",
    "Lanao",
    "Poblacion East",
    "Poblacion West",
    "Saavedra",
    "Tomonoy",
    "Tuble",
    "Tunga",
  ],
  "0702234000": [
    "Alfaco",
    "Bairan",
    "Balirong",
    "Cabungahan",
    "Cantao-an",
    "Central Poblacion",
    "Cogon",
    "Colon",
    "East Poblacion",
    "Inayagan",
    "Inoburan",
    "Jaguimit",
    "Lanas",
    "Langtad",
    "Lutac",
    "Mainit",
    "Mayana",
    "Naalad",
    "North Poblacion",
    "Pangdan",
    "Patag",
    "South Poblacion",
    "Tagjaguimit",
    "Tangke",
    "Tinaan",
    "Tuyan",
    "Uling",
    "West Poblacion",
  ],
  "0702235000": [
    "Alo",
    "Bangcogon",
    "Bonbon",
    "Calumpang",
    "Can-ukban",
    "Cañang",
    "Canangca-an",
    "Cansalo-ay",
    "Daanlungsod",
    "Gawi",
    "Hagdan",
    "Lagunde",
    "Looc",
    "Luka",
    "Mainit",
    "Manlum",
    "Nueva Caceres",
    "Poblacion",
    "Pungtod",
    "Tan-awan",
    "Tumalog",
  ],
  "0702236000": [
    "Biasong",
    "Cawit",
    "Dapdap",
    "Esperanza",
    "Imelda",
    "Lanao",
    "Lower Poblacion",
    "Moabog",
    "Montserrat",
    "San Isidro",
    "San Juan",
    "Upper Poblacion",
    "Villahermosa",
  ],
  "0702237000": [
    "Anislag",
    "Anopog",
    "Binabag",
    "Buhingtubig",
    "Busay",
    "Butong",
    "Cabiangon",
    "Camugao",
    "Duangan",
    "Guimbawian",
    "Lamac",
    "Lut-od",
    "Mangoto",
    "Opao",
    "Pandacan",
    "Poblacion",
    "Punod",
    "Rizal",
    "Sacsac",
    "Sambagon",
    "Sibago",
    "Tajao",
    "Tangub",
    "Tanibag",
    "Tupas",
    "Tutay",
  ],
  "0702238000": [
    "Adela",
    "Altavista",
    "Cagcagan",
    "Cansabusab",
    "Daan Paz",
    "Eastern Poblacion",
    "Esperanza",
    "Libertad",
    "Mabini",
    "Mercedes",
    "Pagsa",
    "Paz",
    "Rizal",
    "San Jose",
    "Santa Rita",
    "Teguis",
    "Western Poblacion",
  ],
  "0702239000": [
    "Butong",
    "Can-abuhon",
    "Canduling",
    "Cansalonoy",
    "Cansayahon",
    "Ilaya",
    "Langin",
    "Libo-o",
    "Malalay",
    "Palanas",
    "Poblacion",
    "Santa Cruz",
    "Tupas",
    "Vive",
  ],
  "0702240000": [
    "Basak",
    "Bonbon",
    "Bulangsuran",
    "Calatagan",
    "Cambigong",
    "Camburoy",
    "Canorong",
    "Colase",
    "Dalahikan",
    "Jumangpas",
    "Monteverde",
    "Poblacion",
    "San Sebastian",
    "Suba",
    "Tangbo",
  ],
  "0702241000": [
    "Balud",
    "Balungag",
    "Basak",
    "Bugho",
    "Cabatbatan",
    "Greenhills",
    "Ilaya",
    "Lantawan",
    "Liburon",
    "Magsico",
    "Panadtaran",
    "Pitalo",
    "Poblacion North",
    "Poblacion South",
    "San Isidro",
    "Sangat",
    "Tabionan",
    "Tananas",
    "Tinubdan",
    "Tonggo",
    "Tubod",
  ],
  "0702242000": [
    "Cabunga-an",
    "Campo",
    "Consuelo",
    "Esperanza",
    "Himensulan",
    "Montealegre",
    "Northern Poblacion",
    "San Isidro",
    "Santa Cruz",
    "Santiago",
    "Sonog",
    "Southern Poblacion",
    "Unidos",
    "Union",
    "Western Poblacion",
  ],
  "0702243000": [
    "Anapog",
    "Argawanon",
    "Bagtic",
    "Bancasan",
    "Batad",
    "Busogon",
    "Calambua",
    "Canagahan",
    "Dapdap",
    "Gawaygaway",
    "Hagnaya",
    "Kayam",
    "Kinawahan",
    "Lambusan",
    "Lawis",
    "Libaong",
    "Looc",
    "Luyang",
    "Mano",
    "Poblacion",
    "Punta",
    "Sab-a",
    "San Miguel",
    "Tacup",
    "Tambongon",
    "To-ong",
    "Victoria",
  ],
  "0702244000": [
    "Balidbid",
    "Hagdan",
    "Hilantagaan",
    "Kinatarkan",
    "Langub",
    "Maricaban",
    "Okoy",
    "Poblacion",
    "Pooc",
    "Talisay",
  ],
  "0702245000": [
    "Bunlan",
    "Cabutongan",
    "Candamiang",
    "Canlumacad",
    "Liloan",
    "Lip-tong",
    "Looc",
    "Pasil",
    "Poblacion",
    "Talisay",
  ],
  "0702246000": [
    "Abugon",
    "Bae",
    "Bagacay",
    "Bahay",
    "Banlot",
    "Basak",
    "Bato",
    "Cagay",
    "Can-aga",
    "Candaguit",
    "Cantolaroy",
    "Dugoan",
    "Guimbangco-an",
    "Lamacan",
    "Libo",
    "Lindogon",
    "Magcagong",
    "Manatad",
    "Mangyan",
    "Papan",
    "Poblacion",
    "Sabang",
    "Sayao",
    "Simala",
    "Tubod",
  ],
  "0702247000": [
    "Ampongol",
    "Bagakay",
    "Bagatayam",
    "Bawo",
    "Cabalawan",
    "Cabangahan",
    "Calumboyan",
    "Dakit",
    "Damolog",
    "Ibabao",
    "Liki",
    "Lubo",
    "Mohon",
    "Nahus-an",
    "Pansoy",
    "Poblacion",
    "Tabunok",
    "Takay",
  ],
  "0702248000": [
    "Alang-alang",
    "Caduawan",
    "Camoboan",
    "Canaocanao",
    "Combado",
    "Daantabogon",
    "Ilihan",
    "Kal-anan",
    "Labangon",
    "Libjo",
    "Loong",
    "Mabuli",
    "Managase",
    "Manlagtang",
    "Maslog",
    "Muabog",
    "Pio",
    "Poblacion",
    "Salag",
    "Sambag",
    "San Isidro",
    "San Vicente",
    "Somosa",
    "Taba-ao",
    "Tapul",
  ],
  "0702249000": [
    "Bongon",
    "Dalid",
    "Kanlim-ao",
    "Kanluhangon",
    "Kantubaon",
    "Mabunao",
    "Maravilla",
    "Olivo",
    "Poblacion",
    "Tabunok",
    "Tigbawan",
    "Villahermosa",
  ],
  "0702250000": [
    "Biasong",
    "Bulacao",
    "Cadulawan",
    "Camp IV",
    "Cansojong",
    "Dumlog",
    "Jaclupan",
    "Lagtang",
    "Lawaan I",
    "Lawaan II",
    "Lawaan III",
    "Linao",
    "Maghaway",
    "Manipis",
    "Mohon",
    "Poblacion",
    "Pooc",
    "San Isidro",
    "San Roque",
    "Tabunoc",
    "Tangke",
    "Tapul",
  ],
  "0702251000": [
    "Awihao",
    "Bagakay",
    "Bato",
    "Biga",
    "Bulongan",
    "Bunga",
    "Cabitoonan",
    "Calongcalong",
    "Cambang-ug",
    "Camp 8",
    "Canlumampao",
    "Cantabaco",
    "Capitan Claudio",
    "Carmen",
    "Daanglungsod",
    "Don Andres Soriano",
    "Dumlog",
    "Gen. Climaco",
    "Ibo",
    "Ilihan",
    "Juan Climaco, Sr.",
    "Landahan",
    "Loay",
    "Luray II",
    "Matab-ang",
    "Media Once",
    "Pangamihan",
    "Poblacion",
    "Poog",
    "Putingbato",
    "Sagay",
    "Sam-ang",
    "Sangi",
    "Santo Niño",
    "Subayon",
    "Talavera",
    "Tubod",
    "Tungkay",
  ],
  "0702252000": [
    "Alegria",
    "Amatugan",
    "Antipolo",
    "Apalan",
    "Bagasawe",
    "Bakyawan",
    "Bangkito",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Barangay VI (Pob.)",
    "Barangay VII (Pob.)",
    "Barangay VIII (Pob.)",
    "Bulwang",
    "Caridad",
    "Carmelo",
    "Cogon",
    "Colonia",
    "Daan Lungsod",
    "Fortaliza",
    "Ga-ang",
    "Gimama-a",
    "Jagbuaya",
    "Kabangkalan",
    "Kabkaban",
    "Kagba-o",
    "Kalangahan",
    "Kamansi",
    "Kampoot",
    "Kan-an",
    "Kanlunsing",
    "Kansi",
    "Kaorasan",
    "Libo",
    "Lusong",
    "Macupa",
    "Mag-alwa",
    "Mag-antoy",
    "Mag-atubang",
    "Maghan-ay",
    "Mangga",
    "Marmol",
    "Molobolo",
    "Montealegre",
    "Putat",
    "San Juan",
    "Sandayong",
    "Santo Niño",
    "Siotes",
    "Sumon",
    "Tominjao",
    "Tomugpa",
  ],
  "0702253000": [
    "Buenavista",
    "Calmante",
    "Daan Secante",
    "General",
    "McArthur",
    "Northern Poblacion",
    "Puertobello",
    "Santander",
    "Secante Bag-o",
    "Southern Poblacion",
    "Villahermosa",
  ],
  "0704601000": [
    "Bio-os",
    "Jantianon",
    "Jugno",
    "Mag-abo",
    "Poblacion",
    "Silab",
    "Tambojangin",
    "Tandayag",
  ],
  "0704602000": [
    "Amdus",
    "Anibong",
    "Atabay",
    "Awa-an",
    "Ban-ban",
    "Calagcalag",
    "Candana-ay",
    "Carol-an",
    "Gomentoc",
    "Inacban",
    "Iniban",
    "Jandalamanon",
    "Kilaban",
    "Lamigan",
    "Maaslum",
    "Mabato",
    "Manogtong",
    "Nabhang",
    "Poblacion",
    "Tambo",
    "Tampocon I",
    "Tampocon II",
    "Tibyawan",
    "Tiguib",
  ],
  "0704603000": [
    "Balayagmanok",
    "Banilad",
    "Buntis",
    "Buntod",
    "Calangag",
    "Combado",
    "Doldol",
    "Isugan",
    "Liptong",
    "Lutao",
    "Magsuhot",
    "Malabago",
    "Mampas",
    "North Poblacion",
    "Sacsac",
    "San Miguel",
    "South Poblacion",
    "Sulodpan",
    "Timbanga",
    "Timbao",
    "Tubod",
    "West Poblacion",
  ],
  "0704604000": [
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Basak",
    "Biñohon",
    "Cabanlutan",
    "Calasga-an",
    "Cambagahan",
    "Cambaguio",
    "Cambanjao",
    "Cambuilao",
    "Canlargo",
    "Capiñahan",
    "Consolacion",
    "Dansulan",
    "Hangyad",
    "Katacgahan",
    "La Paz",
    "Lo-oc",
    "Lonoy",
    "Mabunao",
    "Manlipac",
    "Mansangaban",
    "Okiot",
    "Olympia",
    "Panala-an",
    "Panam-angan",
    "Rosario",
    "Sab-ahan",
    "San Isidro",
    "Tagpo",
    "Talungon",
    "Tamisu",
    "Tamogong",
    "Tangculogan",
    "Valencia",
  ],
  "0704605000": [
    "Actin",
    "Bal-os",
    "Bongalonan",
    "Cabalayongan",
    "Cabatuanan",
    "Linantayan",
    "Maglinao",
    "Nagbo-alao",
    "Olandao",
    "Poblacion",
  ],
  "0704606000": [
    "Ali-is",
    "Banaybanay",
    "Banga",
    "Boyco",
    "Bugay",
    "Cansumalig",
    "Dawis",
    "Kalamtukan",
    "Kalumboyan",
    "Malabugas",
    "Mandu-ao",
    "Maninihon",
    "Minaba",
    "Nangka",
    "Narra",
    "Pagatban",
    "Poblacion",
    "San Isidro",
    "San Jose",
    "San Miguel",
    "San Roque",
    "Suba (Pob.)",
    "Tabuan",
    "Tayawan",
    "Tinago (Pob.)",
    "Ubos (Pob.)",
    "Villareal",
    "Villasol",
  ],
  "0704607000": [
    "Atotes",
    "Batangan",
    "Bulod",
    "Cabcaban",
    "Cabugan",
    "Camudlas",
    "Canluto",
    "Danao",
    "Danawan",
    "Domolog",
    "Malaga",
    "Manseje",
    "Matobato",
    "Nagcasunog",
    "Nalundan",
    "Pangalaycayan",
    "Peñahan",
    "Poblacion",
    "Salong",
    "Tagaytay",
    "Tinaogan",
    "Tubod",
  ],
  "0704608000": [
    "Bayog",
    "Binalbagan",
    "Bucalan",
    "Budlasan",
    "Linothangan",
    "Lumapao",
    "Mabigo (Pob.)",
    "Malaiba",
    "Masulog",
    "Ninoy Aquino",
    "Panubigan",
    "Pula",
  ],
  "0704609000": [
    "Anahawan",
    "Apo Island",
    "Bagacay",
    "Baslay",
    "Batuhon Dacu",
    "Boloc-boloc",
    "Bulak",
    "Bunga",
    "Casile",
    "Libjo",
    "Lipayo",
    "Maayongtubig",
    "Mag-aso",
    "Magsaysay",
    "Malongcay Dacu",
    "Masaplod Norte",
    "Masaplod Sur",
    "Panubtuban",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Tugawe",
    "Tunga-tunga",
  ],
  "0704610000": [
    "Bagacay",
    "Bajumpandan",
    "Balugo",
    "Banilad",
    "Bantayan",
    "Batinguel",
    "Bunao",
    "Cadawinonan",
    "Calindagan",
    "Camanjac",
    "Candau-ay",
    "Cantil-e",
    "Daro",
    "Junob",
    "Looc",
    "Mangnao-Canal",
    "Motong",
    "Piapi",
    "Poblacion No. 1",
    "Poblacion No. 2 ",
    "Poblacion No. 3",
    "Poblacion No. 4",
    "Poblacion No. 5",
    "Poblacion No. 6",
    "Poblacion No. 7",
    "Poblacion No. 8",
    "Pulantubig",
    "Tabuctubig",
    "Taclobo",
    "Talay",
  ],
  "0704611000": [
    "Bakid",
    "Balogo",
    "Banwaque",
    "Basak",
    "Binobohan",
    "Buenavista",
    "Bulado",
    "Calamba",
    "Calupa-an",
    "Hibaiyo",
    "Hilaitan",
    "Hinakpan",
    "Humayhumay",
    "Imelda",
    "Kagawasan",
    "Linantuyan",
    "Luz",
    "Mabunga",
    "Magsaysay",
    "Malusay",
    "Maniak",
    "Mckinley",
    "Nagsaha",
    "Padre Zamora",
    "Plagatasanon",
    "Planas",
    "Poblacion",
    "Sandayao",
    "Tacpao",
    "Tinayunan Beach",
    "Tinayunan Hill",
    "Trinidad",
    "Villegas",
  ],
  "0704612000": [
    "Aglahug",
    "Agutayon",
    "Apanangon",
    "Bae",
    "Bala-as",
    "Bangcal",
    "Banog",
    "Buto",
    "Cabang",
    "Camandayon",
    "Cangharay",
    "Canlahao",
    "Dayoyo",
    "Eli",
    "Lacaon",
    "Mahanlud",
    "Malabago",
    "Mambaid",
    "Mongpong",
    "North Poblacion",
    "Owacan",
    "Pacuan",
    "Panglaya-an",
    "Polopantao",
    "Sampiniton",
    "South Poblacion",
    "Talamban",
    "Tamao",
  ],
  "0704613000": [
    "Aniniaw",
    "Aya",
    "Bagtic",
    "Biga-a",
    "Busilak",
    "Cangabo",
    "Cantupa",
    "Elecia",
    "Eli",
    "Guihob",
    "Kansumandig",
    "Mambulod",
    "Mandapaton",
    "Manghulyawon",
    "Manluminsag",
    "Mapalasan",
    "Maragondong",
    "Martilo",
    "Nasungan",
    "Pacuan",
    "Pangca",
    "Pisong",
    "Pitogo",
    "Poblacion North",
    "Poblacion South",
    "San Jose",
    "Solongon",
    "Tala-on",
    "Talayong",
  ],
  "0704614000": [
    "Abis",
    "Arebasore",
    "Bagtic",
    "Banban",
    "Barras",
    "Bato",
    "Bugnay",
    "Bulibulihan",
    "Bulwang",
    "Campanun-an",
    "Canggohob",
    "Cansal-ing",
    "Dagbasan",
    "Dahile",
    "Hagtu",
    "Himocdongon",
    "Inapoy",
    "Lamdas",
    "Lumbangan",
    "Luyang",
    "Manlingay",
    "Mayaposi",
    "Napasu-an",
    "New Namangka",
    "Old Namangka",
    "Pandanon",
    "Paniabonan",
    "Pantao",
    "Poblacion",
    "Samac",
    "Tadlong",
    "Tara",
  ],
  "0704615000": [
    "Alangilanan",
    "Bagtic",
    "Balaas",
    "Bantolinao",
    "Bolisong",
    "Butong",
    "Campuyo",
    "Candabong",
    "Concepcion",
    "Dungo-an",
    "Kauswagan",
    "Lamogong",
    "Libjo",
    "Maaslum",
    "Mandalupang",
    "Panciao",
    "Poblacion",
    "Sac-sac",
    "Salvacion",
    "San Isidro",
    "San Jose",
    "Santa Monica",
    "Suba",
    "Sundo-an",
    "Tanglad",
    "Tubod",
    "Tupas",
  ],
  "0704616000": [
    "Abante",
    "Balayong",
    "Banawe",
    "Calicanan",
    "Datagon",
    "Fatima",
    "Inawasan",
    "Magsusunog",
    "Malalangsi",
    "Mamburao",
    "Mangoto",
    "Poblacion",
    "San Isidro",
    "Santa Agueda",
    "Simborio",
    "Yupisan",
  ],
  "0704617000": [
    "Basak",
    "Basiao",
    "Cambaloctot",
    "Cancawas",
    "Janayjanay",
    "Jilocon",
    "Naiba",
    "Poblacion",
    "San Roque",
    "Santo Niño",
    "Señora Ascion",
    "Siapo",
    "Tampi",
    "Tapon Norte",
  ],
  "0704618000": [
    "Alangilan",
    "Amio",
    "Buenavista",
    "Caigangan",
    "Caranoche",
    "Cawitan",
    "Fatima",
    "Kabulacan",
    "Mabuhay",
    "Manalongon",
    "Mansagomayon",
    "Milagrosa",
    "Nagbalaye",
    "Nagbinlod",
    "Obat",
    "Poblacion",
    "San Francisco",
    "San Jose",
    "San Miguel",
    "San Pedro",
    "Santo Rosario",
    "Talalak",
  ],
  "0704619000": [
    "Albiga",
    "Apoloy",
    "Bonawon",
    "Bonbonon",
    "Cabangahan",
    "Canaway",
    "Casala-an",
    "Caticugan",
    "Datag",
    "Giliga-on",
    "Inalad",
    "Malabuhan",
    "Maloh",
    "Mantiquil",
    "Mantuyop",
    "Napacao",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Salag",
    "San Jose",
    "Sandulot",
    "Si-it",
    "Sumaliring",
    "Tayak",
  ],
  "0704620000": [
    "Agan-an",
    "Ajong",
    "Balugo",
    "Bolocboloc",
    "Calabnugan",
    "Cangmating",
    "Enrique Villanueva",
    "Looc",
    "Magatas",
    "Maningcao",
    "Maslog",
    "Poblacion",
    "San Antonio",
    "Tubigon",
    "Tubtubon",
  ],
  "0704621000": [
    "Azagra",
    "Bahi-an",
    "Luca",
    "Manipis",
    "Novallas",
    "Obogon",
    "Pal-ew",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Poblacion IX",
    "Poblacion V",
    "Poblacion VI",
    "Poblacion VII",
    "Poblacion VIII",
    "Polo",
    "San Isidro",
    "San Jose",
    "San Miguel",
    "Santa Cruz Nuevo",
    "Santa Cruz Viejo",
    "Santo Niño",
    "Tugas",
  ],
  "0704622000": [
    "Bacong",
    "Bago",
    "Banga",
    "Cabulotan",
    "Cambaye",
    "Dalaupon",
    "Guincalaban",
    "Ilaya-Tayasan",
    "Jilabangan",
    "Lag-it",
    "Linao",
    "Lutay",
    "Maglihe",
    "Magtuhao",
    "Matauta",
    "Matuog",
    "Numnum",
    "Palaslan",
    "Pinalubngan",
    "Pindahan",
    "Pinocawan",
    "Poblacion",
    "Santa Cruz",
    "Saying",
    "Suquib",
    "Tamao",
    "Tambulan",
    "Tanlad",
  ],
  "0704623000": [
    "Apolong",
    "Balabag East",
    "Balabag West",
    "Balayagmanok",
    "Balili",
    "Balugo",
    "Bong-ao",
    "Bongbong",
    "Caidiocan",
    "Calayugan",
    "Cambucad",
    "Dobdob",
    "Jawa",
    "Liptong",
    "Lunga",
    "Malabo",
    "Malaunay",
    "Mampas",
    "North Poblacion",
    "Palinpinon",
    "Puhagan",
    "Pulangbato",
    "Sagbang",
    "South Poblacion",
  ],
  "0704624000": [
    "Bagawines",
    "Bairan",
    "Cabulihan",
    "Don Espiridion Villegas",
    "Guba",
    "Macapso",
    "Maglahos",
    "Malangsa",
    "Molobolo",
    "Pinocawan",
    "Poblacion",
    "Puan",
    "Tabon",
    "Tagbino",
    "Ulay",
  ],
  "0704625000": [
    "Basac",
    "Calango",
    "Lotuban",
    "Malongcay Diot",
    "Maluay",
    "Mayabon",
    "Nabago",
    "Najandig",
    "Nasig-id",
    "Poblacion",
  ],
  "0706101000": [
    "Balolong",
    "Bino-ongan",
    "Bitaug",
    "Bolot",
    "Camogao",
    "Cangmangki",
    "Libo",
    "Lomangcapan",
    "Lotloton",
    "Manan-ao",
    "Olave",
    "Parian",
    "Poblacion",
    "Tulapos",
  ],
  "0706102000": [
    "Bagacay",
    "Balolang",
    "Basac",
    "Bintangan",
    "Bontod",
    "Cabulihan",
    "Calunasan",
    "Candigum",
    "Cang-allas",
    "Cang-apa",
    "Cangbagsa",
    "Cangmalalag",
    "Canlambo",
    "Canlasog",
    "Catamboan",
    "Helen",
    "Nonoc",
    "North Poblacion",
    "Ponong",
    "Sabang",
    "Sandugan",
    "South Poblacion",
    "Taculing",
  ],
  "0706103000": [
    "Campalanas",
    "Cangclaran",
    "Cangomantong",
    "Capalasanan",
    "Catamboan (Pob.)",
    "Gabayan",
    "Kimba",
    "Kinamandagan",
    "Lower Cabangcalan",
    "Nagerong",
    "Po-o",
    "Simacolong",
    "Tagmanocan",
    "Talayong",
    "Tigbawan (Pob.)",
    "Tignao",
    "Upper Cabangcalan",
    "Ytaya",
  ],
  "0706104000": [
    "Bogo",
    "Bonga",
    "Cabal-asan",
    "Calunasan",
    "Candaping A",
    "Candaping B",
    "Cantaroc A",
    "Cantaroc B",
    "Cantugbas",
    "Lico-an",
    "Lilo-an",
    "Logucan",
    "Looc",
    "Minalulan",
    "Nabutay",
    "Olang",
    "Pisong A",
    "Pisong B",
    "Poblacion Norte",
    "Poblacion Sur",
    "Saguing",
    "Sawang",
  ],
  "0706105000": [
    "Canasagan",
    "Candura",
    "Cangmunag",
    "Cansayang",
    "Catulayan",
    "Lala-o",
    "Maite",
    "Napo",
    "Paliton",
    "Poblacion",
    "Solangon",
    "Tag-ibo",
    "Tambisan",
    "Timbaon",
    "Tubod",
  ],
  "0706106000": [
    "Banban",
    "Bolos",
    "Caipilan",
    "Caitican",
    "Calalinan",
    "Canal",
    "Candanay Norte",
    "Candanay Sur",
    "Cang-adieng",
    "Cang-agong",
    "Cang-alwang",
    "Cang-asa",
    "Cang-atuyom",
    "Cang-inte",
    "Cang-isad",
    "Canghunoghunog",
    "Cangmatnog",
    "Cangmohao",
    "Cantabon",
    "Caticugan",
    "Dumanhog",
    "Ibabao",
    "Lambojon",
    "Luyang",
    "Luzong",
    "Olo",
    "Pangi",
    "Panlautan",
    "Pasihagon",
    "Pili",
    "Poblacion",
    "Polangyuta",
    "Ponong",
    "Sabang",
    "San Antonio",
    "Songculan",
    "Tacdog",
    "Tacloban",
    "Tambisan",
    "Tebjong",
    "Tinago",
    "Tongo",
  ],
  "0730600000": [
    "Adlaon",
    "Agsungot",
    "Apas",
    "Babag",
    "Bacayan",
    "Banilad",
    "Basak Pardo",
    "Basak San Nicolas",
    "Binaliw",
    "Bonbon",
    "Budla-an (Pob.)",
    "Buhisan",
    "Bulacao",
    "Buot-Taup Pardo",
    "Busay (Pob.)",
    "Calamba",
    "Cambinocot",
    "Camputhaw (Pob.)",
    "Capitol Site (Pob.)",
    "Carreta",
    "Central (Pob.)",
    "Cogon Pardo",
    "Cogon Ramos (Pob.)",
    "Day-as",
    "Duljo (Pob.)",
    "Ermita (Pob.)",
    "Guadalupe",
    "Guba",
    "Hippodromo",
    "Inayawan",
    "Kalubihan (Pob.)",
    "Kalunasan",
    "Kamagayan (Pob.)",
    "Kasambagan",
    "Kinasang-an Pardo",
    "Labangon",
    "Lahug (Pob.)",
    "Lorega",
    "Lusaran",
    "Luz",
    "Mabini",
    "Mabolo",
    "Malubog",
    "Mambaling",
    "Pahina Central (Pob.)",
    "Pahina San Nicolas",
    "Pamutan",
    "Pardo (Pob.)",
    "Pari-an",
    "Paril",
    "Pasil",
    "Pit-os",
    "Pulangbato",
    "Pung-ol-Sibugay",
    "Punta Princesa",
    "Quiot Pardo",
    "Sambag I (Pob.)",
    "Sambag II (Pob.)",
    "San Antonio (Pob.)",
    "San Jose",
    "San Nicolas Central",
    "San Roque",
    "Santa Cruz (Pob.)",
    "Sapangdaku",
    "Sawang Calero (Pob.)",
    "Sinsin",
    "Sirao",
    "Suba Pob.",
    "Sudlon I",
    "Sudlon II",
    "T. Padilla",
    "Tabunan",
    "Tagbao",
    "Talamban",
    "Taptap",
    "Tejero",
    "Tinago",
    "Tisa",
    "To-ong Pardo",
    "Zapatera",
  ],
  "0731100000": [
    "Agus",
    "Babag",
    "Bankal",
    "Baring",
    "Basak",
    "Buaya",
    "Calawisan",
    "Canjulao",
    "Caubian",
    "Caw-oy",
    "Cawhagan",
    "Gun-ob",
    "Ibo",
    "Looc",
    "Mactan",
    "Maribago",
    "Marigondon",
    "Pajac",
    "Pajo",
    "Pangan-an",
    "Poblacion",
    "Punta Engaño",
    "Pusok",
    "Sabang",
    "San Vicente",
    "Santa Rosa",
    "Subabasbas",
    "Talima",
    "Tingo",
    "Tungasan",
  ],
  "0731300000": [
    "Alang-alang",
    "Bakilid",
    "Banilad",
    "Basak",
    "Cabancalan",
    "Cambaro",
    "Canduman",
    "Casili",
    "Casuntingan",
    "Centro (Pob.)",
    "Cubacub",
    "Guizo",
    "Ibabao-Estancia",
    "Jagobiao",
    "Labogon",
    "Looc",
    "Maguikay",
    "Mantuyong",
    "Opao",
    "Pagsabungan",
    "Pakna-an",
    "Subangdaku",
    "Tabok",
    "Tawason",
    "Tingub",
    "Tipolo",
    "Umapad",
  ],
};
