/** GENERATED — Region VIII: 4390 barangays across 143 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "0802601000": [
    "Aguinaldo",
    "Balud (Pob.)",
    "Bato",
    "Beri",
    "Bigo",
    "Buenavista",
    "Cagsalay",
    "Campacion",
    "Carapdapan",
    "Casidman",
    "Catumsan",
    "Central (Pob.)",
    "Concepcion",
    "Garden (Pob.)",
    "Inayawan",
    "Macarthur",
    "Rawis (Pob.)",
    "Tangbo",
    "Tawagan",
    "Tebalawon",
  ],
  "0802602000": [
    "Bacjao",
    "Barangay Poblacion I",
    "Barangay Poblacion II",
    "Barangay Poblacion III",
    "Barangay Poblacion IV",
    "Barangay Poblacion V",
    "Barangay Poblacion VI",
    "Cag-olango",
    "Cansumangcay",
    "Guinmaayohan",
    "Maybunga",
    "San Miguel",
    "Santa Rosa",
  ],
  "0802603000": [
    "Balogo",
    "Bangon",
    "Cabay",
    "Caisawan",
    "Cantubi",
    "General Malvar",
    "Guinpoliran",
    "Julag",
    "Magsaysay",
    "Maramag",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Poblacion V",
  ],
  "0802604000": [
    "Alang-alang",
    "Amantacop",
    "Ando",
    "Balacdas",
    "Balud",
    "Banuyo",
    "Baras",
    "Bato",
    "Bayobay",
    "Benowangan",
    "Bugas",
    "Cabalagnan",
    "Cabong",
    "Cagbonga",
    "Calico-an",
    "Calingatngan",
    "Camada",
    "Campesao",
    "Can-abong",
    "Can-aga",
    "Canjaway",
    "Canlaray",
    "Canyopay",
    "Divinubo",
    "Hebacong",
    "Hindang",
    "Lalawigan",
    "Libuton",
    "Locso-on",
    "Maybacong",
    "Maypangdan",
    "Pepelitan",
    "Pinanag-an",
    "Punta Maria",
    "Purok A (Pob.)",
    "Purok B (Pob.)",
    "Purok C (Pob.)",
    "Purok D1 (Pob.)",
    "Purok D2 (Pob.)",
    "Purok E (Pob.)",
    "Purok F (Pob.)",
    "Purok G (Pob.)",
    "Purok H (Pob.)",
    "Sabang North",
    "Sabang South",
    "San Andres",
    "San Gabriel",
    "San Gregorio",
    "San Jose",
    "San Mateo",
    "San Pablo",
    "San Saturnino",
    "Santa Fe",
    "Siha",
    "Sohutan",
    "Songco",
    "Suribao",
    "Surok",
    "Taboc",
    "Tabunan",
    "Tamoso",
  ],
  "0802605000": [
    "Balagon",
    "Barangay 1 Poblacion",
    "Barangay 10 Poblacion",
    "Barangay 2 Poblacion",
    "Barangay 3 Poblacion",
    "Barangay 4 Poblacion",
    "Barangay 5 Poblacion",
    "Barangay 6 Poblacion",
    "Barangay 7 Poblacion",
    "Barangay 8 Poblacion",
    "Barangay 9 Poblacion",
    "Baruk",
    "Boco",
    "Caghalong",
    "Camantang",
    "Can-ilay",
    "Cansangaya",
    "Canteros",
    "Carolina",
    "Guibuangan",
    "Jepaco",
    "Mabuhay",
    "Malogo",
    "Obong",
    "Pandol",
    "Rawis",
    "Salvacion",
    "Solong",
  ],
  "0802606000": [
    "Aroganga",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 12 (Pob.)",
    "Barangay 13 (Pob.)",
    "Barangay 14 (Pob.)",
    "Barangay 15 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Bonghon",
    "Buenavista",
    "Cabago-an",
    "Caglao-an",
    "Cagtabon",
    "Dampigan",
    "Dapdap",
    "Del Pilar",
    "Denigpian",
    "Gap-ang",
    "Hilabaan",
    "Hinolaso",
    "Japitan",
    "Jicontol",
    "Libertad",
    "Magongbong",
    "Magsaysay",
    "Malaintos",
    "Malobago",
    "Osmeña",
    "Rizal",
    "San Isidro",
    "San Pascual",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Santo Niño",
    "Tanauan",
    "Tikling",
    "Villahermosa",
  ],
  "0802607000": [
    "Aguinaldo",
    "Alang-alang",
    "Binalay",
    "Calutan",
    "Camcuevas",
    "Domrog",
    "Laurel",
    "Limbujan",
    "Macapagal",
    "Magsaysay",
    "Osmeña",
    "Pingan",
    "Poblacion Barangay 1",
    "Poblacion Barangay 2",
    "Poblacion Barangay 3",
    "Poblacion Barangay 4",
    "Poblacion Barangay 5",
    "Poblacion Barangay 6",
    "Poblacion Barangay 7",
    "Poblacion Barangay 8",
    "Quezon",
    "Quirino",
    "Roxas",
    "San Isidro",
    "San Roque",
    "Santa Cruz",
    "Santa Fe",
    "Tandang Sora",
    "Tugop",
    "Vigan",
  ],
  "0802608000": [
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Biga",
    "Coticot",
    "Gigoso",
    "Huknan",
    "Parina",
    "Paya",
    "President Roxas",
    "San Isidro",
    "San Miguel",
    "Santa Cruz",
  ],
  "0802609000": [
    "Alingarog",
    "Bagua",
    "Banaag",
    "Banahao",
    "Baras",
    "Barbo",
    "Bitaugan",
    "Bucao",
    "Buenavista",
    "Bungtod",
    "Cagdara-o",
    "Cagusu-an",
    "Camparang",
    "Campoyong",
    "Canawayon",
    "Cantahay",
    "Casuguran",
    "Cogon",
    "Culasi",
    "Dalaragan",
    "Gahoy",
    "Habag",
    "Hagna",
    "Hamorawon",
    "Hollywood",
    "Inapulangan",
    "Lupok (Pob.)",
    "Mayana",
    "Ngolos",
    "Pagbabangnan",
    "Pagnamitan",
    "Poblacion Ward 1",
    "Poblacion Ward 10",
    "Poblacion Ward 11",
    "Poblacion Ward 12",
    "Poblacion Ward 2",
    "Poblacion Ward 3",
    "Poblacion Ward 4",
    "Poblacion Ward 4-A",
    "Poblacion Ward 5",
    "Poblacion Ward 6",
    "Poblacion Ward 7",
    "Poblacion Ward 8",
    "Poblacion Ward 9",
    "Poblacion Ward 9-A",
    "Salug",
    "San Antonio",
    "San Jose",
    "San Juan",
    "San Pedro",
    "Santo Niño",
    "Sapao",
    "Sulangan",
    "Suluan",
    "Surok",
    "Tagporo",
    "Taytay",
    "Timala",
    "Trinidad",
    "Victory Island",
  ],
  "0802610000": [
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Batang",
    "Cacatmonan",
    "Canciledes",
    "Carmen",
    "Garawon",
    "Nagaja",
    "Padang",
    "San Isidro",
    "San Miguel",
  ],
  "0802611000": [
    "Agsaman",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Cagmanaba",
    "Dorillo",
    "Jewaran",
    "Mabuhay",
    "Magsaysay",
    "Recare",
    "Roxas",
    "San Roque",
  ],
  "0802612000": [
    "Barangay Poblacion 1",
    "Barangay Poblacion 10",
    "Barangay Poblacion 2",
    "Barangay Poblacion 3",
    "Barangay Poblacion 4",
    "Barangay Poblacion 5",
    "Barangay Poblacion 6",
    "Barangay Poblacion 7",
    "Barangay Poblacion 8",
    "Barangay Poblacion 9",
    "Betaog",
    "Bolusao",
    "Guinob-an",
    "Maslog",
    "San Isidro",
    "Taguite",
  ],
  "0802613000": [
    "Antipolo",
    "Babanikhon",
    "Bacayawan",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 12 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Barobo",
    "Burak",
    "Can-ato",
    "Candoros",
    "Canliwag",
    "Cantomco",
    "Hugpa",
    "Maca-anga",
    "Magtino",
    "Mina-anod",
    "Naubay",
    "Piliw",
    "San Jose",
    "San Miguel",
    "San Roque",
    "So-ong",
    "Tabok",
    "Waso",
  ],
  "0802614000": [
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Bulawan",
    "Carayacay",
    "Libertad",
    "Malobago",
    "Maputi",
    "San Miguel",
    "San Roque",
    "Tangbo",
    "Taytay",
    "Tugas",
  ],
  "0802615000": [
    "Barangay Poblacion 1",
    "Barangay Poblacion 2",
    "Barangay Poblacion 3",
    "Barangay Poblacion 4",
    "Barangay Poblacion 5",
    "Barangay Poblacion 6",
    "Barangay Poblacion 7",
    "Camada",
    "Campakerit",
    "Canloterio",
    "Del Pilar",
    "Guindalitan",
    "Lapgap",
    "Malobago",
    "Maybocog",
    "Maytigbao",
    "Omawas",
    "Patag",
    "San Gabriel",
    "Tagaslian",
  ],
  "0802616000": [
    "Anuron",
    "Banuyo",
    "Barangay 1 Poblacion",
    "Barangay 2 Poblacion",
    "Barangay 3 Poblacion",
    "Barangay 4 Poblacion",
    "Bobon",
    "Busay",
    "Buyayawon",
    "Cabunga-an",
    "Cambante",
    "Palamrag",
    "Port Kennedy",
    "San Jose",
    "San Roque",
    "Sung-an",
  ],
  "0802617000": [
    "Agsam",
    "Alang-alang",
    "Bagacay",
    "Balingasag",
    "Balocawe (Pob.)",
    "Bantayan",
    "Batang",
    "Bato",
    "Binalayan",
    "Buntay",
    "Burak",
    "Butnga (Pob.)",
    "Cadian",
    "Cagdine",
    "Cagpile",
    "Cagtoog",
    "Camanga (Pob.)",
    "Dalid",
    "Dao",
    "Factoria",
    "Gamot",
    "Iwayan",
    "Japay",
    "Kalaw",
    "Mabuhay",
    "Malingon",
    "Minap-os",
    "Nadacpan",
    "Naga",
    "Pangudtan",
    "Paypayon (Pob.)",
    "Riverside (Pob.)",
    "Rizal",
    "Sabang",
    "San Eduardo",
    "San Roque (Pob.)",
    "Santa Monica",
    "Saugan",
    "Saurong",
    "Tawagan (Pob.)",
    "Tiguib (Pob.)",
    "Trinidad",
  ],
  "0802618000": [
    "Alang-alang",
    "Anislag",
    "Bagte",
    "Barangay No. 1 (Pob.)",
    "Barangay No. 2 (Pob.)",
    "Barangay No. 3 (Pob.)",
    "Barangay No. 4 (Pob.)",
    "Barangay No. 5 (Pob.)",
    "Barangay No. 6 (Pob.)",
    "Barangay No. 7 (Pob.)",
    "Buenavista",
    "Caculangan",
    "Cagdaja",
    "Cambilla",
    "Cantenio",
    "Naga",
    "Paco",
    "Palactad",
    "Rizal",
    "San Isidro",
    "San Pedro",
    "San Vicente",
    "Santa Cruz",
    "Santa Margarita",
    "Santo Niño",
  ],
  "0802619000": [
    "Abejao",
    "Alog",
    "Asgad",
    "Bagtong",
    "Balud",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 12 (Pob.)",
    "Barangay 13 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Buabua",
    "Burak",
    "Butig",
    "Cagaut",
    "Camanga",
    "Cantomoja",
    "Carapdapan",
    "Caridad",
    "Casili-on",
    "Iberan",
    "Jagnaya",
    "Lusod",
    "Malbog",
    "Maliwaliw",
    "Matarinao",
    "Naparaan",
    "Palanas",
    "San Roque",
    "Santa Cruz",
    "Seguinon",
    "Tacla-on",
    "Tagbacan",
    "Talangdawan",
  ],
  "0802620000": [
    "Barangay No. 1 Poblacion",
    "Barangay No. 2 Poblacion",
    "Barangay No. 3 Poblacion",
    "Barangay No. 4 Poblacion",
    "Barangay No. 5 Poblacion",
    "Barangay No. 6 Poblacion",
    "Bunacan",
    "Campidhan",
    "Casoroy",
    "Libas",
    "Lunang",
    "Nena",
    "Pagbabangnan",
    "Putong",
    "San Isidro",
    "San Miguel",
  ],
  "0802621000": [
    "Alugan",
    "Bahay",
    "Bangon",
    "Barangay No. 1 (Pob.)",
    "Barangay No. 2 (Pob.)",
    "Barangay No. 3 (Pob.)",
    "Barangay No. 4 (Pob.)",
    "Barangay No. 5 (Pob.)",
    "Baras",
    "Binogawan",
    "Cajagwayan",
    "Japunan",
    "Natividad",
    "Pangpang",
    "Santa Cruz",
    "Tabo",
    "Tan-awan",
  ],
  "0802622000": [
    "A-et",
    "Abucay (Pob.)",
    "Baybay (Pob.)",
    "Del Remedio",
    "Kandalakit",
    "Loyola Heights (Pob.)",
    "Mabini",
    "Maglipay (Pob.)",
    "Maramara (Pob.)",
    "Riverside (Pob.)",
    "San Francisco",
    "San Isidro",
    "San Juan",
    "San Mateo",
    "San Vicente",
    "Santo Niño",
    "Santo Tomas",
    "Tabi (Pob.)",
  ],
  "0802623000": [
    "Batiawan",
    "Beto",
    "Binaloan",
    "Bongdo",
    "Dacul",
    "Danao",
    "Del Remedios",
    "Gayam",
    "Lomatud",
    "Mabuhay",
    "Malinao",
    "Mantang",
    "Nato",
    "Pangabutan",
    "Poblacion Barangay 1",
    "Poblacion Barangay 2",
    "Poblacion Barangay 3",
    "Poblacion Barangay 4",
    "Poblacion Barangay 5",
    "Poblacion Barangay 6",
    "Polangi",
    "San Luis",
    "San Pablo",
    "San Rafael",
  ],
  "0803701000": [
    "Alangilan",
    "Anibongan",
    "Bagacay",
    "Bahay",
    "Balinsasayao",
    "Balocawe",
    "Balocawehay",
    "Barayong",
    "Bayabas",
    "Bito (Pob.)",
    "Buaya",
    "Buenavista",
    "Bulak",
    "Bunga",
    "Buntay (Pob.)",
    "Burubud-an",
    "Cadac-an",
    "Cagbolo",
    "Can-aporong",
    "Can-uguib (Pob.)",
    "Canmarating",
    "Capilian",
    "Combis",
    "Dingle",
    "Guintagbucan (Pob.)",
    "Hampipila",
    "Katipunan",
    "Kikilo",
    "Laray",
    "Lawa-an",
    "Libertad",
    "Loyonsawang (Pob.)",
    "Mag-atubang",
    "Mahagna",
    "Mahayahay",
    "Maitum",
    "Malaguicay",
    "Matagnao",
    "Nalibunan (Pob.)",
    "Nebga",
    "New Taligue",
    "Odiongan",
    "Old Taligue",
    "Pagsang-an",
    "Paguite",
    "Parasanon",
    "Picas Sur",
    "Pilar",
    "Pinamanagan",
    "Salvacion",
    "San Francisco",
    "San Isidro",
    "San Roque",
    "Santa Fe (Pob.)",
    "Santa Lucia (Pob.)",
    "Santo Niño (Pob.)",
    "Tabigue",
    "Tadoc",
    "Tib-o",
    "Tinalian",
    "Tinocolan",
    "Tuy-a",
    "Victory (Pob.)",
  ],
  "0803702000": [
    "Aslum",
    "Astorga",
    "Bato",
    "Binongto-an",
    "Binotong",
    "Blumentritt (Pob.)",
    "Bobonon",
    "Borseth",
    "Buenavista",
    "Bugho",
    "Buri",
    "Cabadsan",
    "Calaasan",
    "Cambahanon",
    "Cambolao",
    "Canvertudes",
    "Capiz",
    "Cavite",
    "Cogon",
    "Dapdap",
    "Divisoria",
    "Ekiran",
    "Hinapolan",
    "Holy Child I (Pob.)",
    "Holy Child II (Pob.)",
    "Hubang",
    "Hupit",
    "Langit",
    "Lingayon",
    "Lourdes",
    "Lukay",
    "Magsaysay",
    "Milagrosa (Pob.)",
    "Mudboron",
    "P. Barrantes",
    "Peñalosa",
    "Pepita",
    "Salvacion",
    "Salvacion Poblacion",
    "San Antonio",
    "San Antonio Pob.",
    "San Diego",
    "San Francisco East",
    "San Francisco West",
    "San Isidro",
    "San Pedro",
    "San Roque (Pob.)",
    "San Vicente",
    "Santiago",
    "Santo Niño (Pob.)",
    "Santol",
    "Tabangohay",
    "Tombo",
    "Veteranos",
  ],
  "0803703000": [
    "Antipolo",
    "Balugo",
    "Benolho",
    "Cambalading",
    "Damula-an",
    "Doña Maria",
    "Mahayag",
    "Mahayahay",
    "Poblacion",
    "Salvacion",
    "San Pedro",
    "Seguinon",
    "Sherwood",
    "Tabgas",
    "Talisayan",
    "Tinag-an",
  ],
  "0803705000": [
    "Bacong",
    "Bagong Silang",
    "Biasong",
    "Gov. E. Jaro",
    "Guintigui-an",
    "Lukay",
    "Magcasuang",
    "Malibago",
    "Naga-asan",
    "Pagsulhugon",
    "Planza",
    "Poblacion District I",
    "Poblacion District II",
    "Poblacion District III",
    "Poblacion District IV",
    "Rizal I",
    "Rizal II",
    "San Agustin",
    "San Isidro",
    "San Ricardo",
    "Sangputan",
    "Taguite",
    "Uban",
    "Victory",
    "Villa Magsaysay",
  ],
  "0803706000": [
    "Abango",
    "Amahit",
    "Balire",
    "Balud",
    "Bukid",
    "Bulod",
    "Busay",
    "Cabarasan",
    "Cabolo-an",
    "Calingcaguing",
    "Can-isak",
    "Canomantag",
    "Cuta",
    "Domogdog",
    "Duka",
    "Guindaohan",
    "Hiagsam",
    "Hilaba",
    "Hinugayan",
    "Ibag",
    "Minuhang",
    "Minuswang",
    "Pikas",
    "Pitogo",
    "Poblacion Dist. I",
    "Poblacion Dist. II",
    "Poblacion Dist. III",
    "Poblacion Dist. IV",
    "Poblacion Dist. V",
    "Poblacion Dist. VI",
    "Pongso",
    "Roosevelt",
    "San Isidro",
    "San Roque",
    "Santa Rosa",
    "Santarin",
    "Tutug-an",
  ],
  "0803707000": [
    "Alegria",
    "Alejos",
    "Amagos",
    "Anahawan",
    "Bago",
    "Bagong Bayan District (Pob.)",
    "Buli",
    "Cebuana",
    "Daan Lungsod",
    "Dawahon",
    "Dolho",
    "Domagocdoc",
    "Guerrero District (Pob.)",
    "Himamaa",
    "Imelda",
    "Iniguihan District (Pob.)",
    "Kalanggaman District (Pob.)",
    "Katipunan",
    "Liberty",
    "Mabini",
    "Marcelo",
    "Naga",
    "Osmeña",
    "Plaridel",
    "Ponong",
    "Rivilla",
    "San Agustin",
    "Santo Niño",
    "Tabunok",
    "Tagaytay",
    "Tinago District (Pob.)",
    "Tugas",
  ],
  "0803708000": [
    "Altavista",
    "Ambacan",
    "Amguhan",
    "Ampihanon",
    "Balao",
    "Banahao",
    "Biasong",
    "Bidlinan",
    "Bitanhuan",
    "Bubon",
    "Buenavista",
    "Bunga",
    "Butigan",
    "Candadam",
    "Caridad",
    "Ciabo",
    "Cogon",
    "Ga-as",
    "Gabas",
    "Gakat",
    "Guadalupe",
    "Gubang",
    "Hibunawan",
    "Higuloan",
    "Hilapnitan",
    "Hipusngo",
    "Igang",
    "Imelda",
    "Jaena",
    "Kabalasan",
    "Kabatuan",
    "Kabungaan",
    "Kagumay",
    "Kambonggan",
    "Kan-ipa",
    "Kansungka",
    "Kantagnos",
    "Kilim",
    "Lintaon",
    "Maganhan",
    "Mahayahay",
    "Mailhi",
    "Maitum",
    "Makinhas",
    "Mapgap",
    "Marcos",
    "Maslug",
    "Matam-is",
    "Maybog",
    "Maypatag",
    "Monte Verde",
    "Monterico",
    "Palhi",
    "Pangasungan",
    "Pansagan",
    "Patag",
    "Plaridel",
    "Poblacion Zone 1",
    "Poblacion Zone 10",
    "Poblacion Zone 11",
    "Poblacion Zone 12",
    "Poblacion Zone 13",
    "Poblacion Zone 14",
    "Poblacion Zone 15",
    "Poblacion Zone 16",
    "Poblacion Zone 17",
    "Poblacion Zone 18",
    "Poblacion Zone 19",
    "Poblacion Zone 2",
    "Poblacion Zone 20",
    "Poblacion Zone 21",
    "Poblacion Zone 22",
    "Poblacion Zone 23",
    "Poblacion Zone 3",
    "Poblacion Zone 4",
    "Poblacion Zone 5",
    "Poblacion Zone 6",
    "Poblacion Zone 7",
    "Poblacion Zone 8",
    "Poblacion Zone 9",
    "Pomponan",
    "Punta",
    "Sabang",
    "San Agustin",
    "San Isidro",
    "San Juan",
    "Santa Cruz",
    "Santo Rosario",
    "Sapa",
    "Villa Mag-aso",
    "Villa Solidaridad",
    "Zacarito",
  ],
  "0803710000": [
    "Abuyogon",
    "Anonang",
    "Arado",
    "Balao",
    "Balatson",
    "Balorinay",
    "Bobon",
    "Buenavista",
    "Buri",
    "Caanislagan",
    "Cadahunan",
    "Cagangon",
    "Cali",
    "Calsadahay",
    "Candag-on",
    "Cansiboy",
    "Catagbacan",
    "Damulo-an",
    "Dina-ayan",
    "Dumalag",
    "Esperanza",
    "Gamay",
    "Gitablan",
    "Hapunan",
    "Hibonawan",
    "Hugpa East",
    "Hugpa West",
    "Ilihan",
    "Kagbana",
    "Kalao",
    "Kalipayan",
    "Kaparasanan",
    "Laguiwan",
    "Libas",
    "Limburan",
    "Logsongan",
    "Maabab",
    "Maghubas",
    "Mahagnao",
    "Malabca",
    "Malaguinabot",
    "Malaihao",
    "Matin-ao",
    "Moguing",
    "Paghudlan",
    "Paitan",
    "Pangdan",
    "Patag",
    "Patong",
    "Pawa",
    "Poblacion District I",
    "Poblacion District II",
    "Poblacion District III",
    "Poblacion District IV",
    "Poblacion District IX",
    "Poblacion District V",
    "Poblacion District VI",
    "Poblacion District VII",
    "Poblacion District VIII",
    "Roxas",
    "Sambel",
    "San Esteban",
    "San Fernando",
    "San Jose East",
    "San Jose West",
    "San Pablo",
    "Tabuanon",
    "Tagadtaran",
    "Taghuyan",
    "Takin",
    "Tambis",
    "Tambuko",
    "Toloyao",
    "Villa Aurora",
    "Villa Corazon",
    "Villa Patria",
    "Villa Rosas",
  ],
  "0803713000": [
    "Abanilla",
    "Agas",
    "Anislagan",
    "Bunacan",
    "Cabalhin",
    "Cabalquinto",
    "Cabradilla",
    "Caneja",
    "Cantonghao",
    "Caroyocan",
    "Casiongan",
    "Cristina",
    "Dalumpines",
    "Don Luis",
    "Dulao",
    "Efe",
    "Enage",
    "Espinosa",
    "Ferdinand E. Marcos",
    "Garganera",
    "Garrido",
    "Guadalupe",
    "Gutosan",
    "Igang",
    "Inalad",
    "Jubay",
    "Juson",
    "Kawayan Bogtong",
    "Kawayanan",
    "Kokoy Romualdez",
    "Labtic",
    "Laray",
    "M. Veloso",
    "Mahait",
    "Malobago",
    "Matagok",
    "Nipa",
    "Obispo",
    "Padoga",
    "Pagatpat",
    "Pangpang",
    "Patag",
    "Pates",
    "Paula",
    "Petrolio",
    "Poblacion",
    "Railes",
    "Tabla",
    "Tagharigue",
    "Tuburan",
    "Villahermosa",
    "Villalon",
    "Villanueva",
  ],
  "0803714000": [
    "Balucanad",
    "Balud",
    "Balugo",
    "Cabul-an",
    "Culasian",
    "Gayad",
    "Guinadiongan",
    "Lemon",
    "Libertad",
    "Manloy",
    "Nauguisan",
    "Pinamopoan",
    "Poblacion Zone I",
    "Poblacion Zone II",
    "Potot",
    "San Joaquin",
    "Santo Niño",
    "Talairan",
    "Talisay",
    "Tolibao",
    "Visares",
  ],
  "0803715000": [
    "Bagong Lipunan",
    "Balilit",
    "Barayong",
    "Barugohay Central",
    "Barugohay Norte",
    "Barugohay Sur",
    "Baybay (Pob.)",
    "Binibihan",
    "Bislig",
    "Caghalo",
    "Camansi",
    "Canal",
    "Candigahub",
    "Canfabi",
    "Canlampay",
    "Cogon",
    "Cutay",
    "East Visoria",
    "Guindapunan East",
    "Guindapunan West",
    "Hiluctogan",
    "Jugaban (Pob.)",
    "Libo",
    "Lower Hiraan",
    "Lower Sogod",
    "Macalpi",
    "Manloy",
    "Nauguisan",
    "Paglaum",
    "Pangna",
    "Parag-um",
    "Parina",
    "Piloro",
    "Ponong (Pob.)",
    "Rizal",
    "Sagkahan",
    "San Isidro",
    "San Juan",
    "San Mateo (Pob.)",
    "Santa Fe",
    "Sawang (Pob.)",
    "Tagak",
    "Tangnan",
    "Tigbao",
    "Tinaguban",
    "Upper Hiraan",
    "Upper Sogod",
    "Uyawan",
    "West Visoria",
  ],
  "0803717000": [
    "Abaca",
    "Abre",
    "Balilit",
    "Balugo",
    "Banayon",
    "Bayabas",
    "Bolirao",
    "Buenavista",
    "Buntay",
    "Caanislagan",
    "Cabariwan",
    "Cabuloran",
    "Cabunga-an",
    "Calipayan",
    "Calsadahay",
    "Caluctogan",
    "Calutan",
    "Camono-an",
    "Candagara",
    "Canlingga",
    "Cansamada East",
    "Cansamada West",
    "Capulhan",
    "Digahongan",
    "Guinarona",
    "Hiabangan",
    "Hilabago",
    "Hinabuyan",
    "Hinologan",
    "Hitumnog",
    "Katipunan",
    "Lapu-lapu Pob.",
    "Lobe-lobe",
    "Lobe-lobe East",
    "Los Martires",
    "Lusad Pob.",
    "Macaalang",
    "Maliwaliw",
    "Maragondong",
    "Ormocay",
    "Palacio",
    "Panda",
    "Paraiso",
    "Patoc",
    "Plaridel",
    "Poponton",
    "Rizal",
    "Salvacion",
    "Sampaguita",
    "Sampao East Pob.",
    "Sampao West Pob.",
    "San Antonio Pob.",
    "San Benito",
    "San Jose Pob.",
    "San Roque Pob.",
    "Santo Domingo",
    "Sawahon",
    "Sirab",
    "Sta. Mesa Pob.",
    "Tagkip",
    "Talinhugon",
    "Tin-ao",
    "Tunga Pob.",
    "Tuya",
    "Victoria",
  ],
  "0803718000": [
    "Alegre",
    "Arado",
    "Barbo (Pob.)",
    "Batug",
    "Bolongtohan",
    "Bulod",
    "Buntay (Pob.)",
    "Cabacungan",
    "Cabarasan",
    "Cabato-an",
    "Calipayan",
    "Calubian",
    "Cambula District (Pob.)",
    "Camitoc",
    "Camote",
    "Candao (Pob.)",
    "Catmonan (Pob.)",
    "Combis (Pob.)",
    "Dacay",
    "Del Carmen",
    "Del Pilar",
    "Fatima",
    "General Roxas",
    "Highway (Pob.)",
    "Luan",
    "Magsaysay",
    "Maricum",
    "Market Site (Pob.)",
    "Rawis",
    "Rizal",
    "Romualdez",
    "Sabang Daguitan",
    "Salvacion",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Miguel (Pob.)",
    "San Rafael",
    "San Vicente",
    "Serrano (Pob.)",
    "Sungi (Pob.)",
    "Tabu",
    "Tigbao",
    "Victory",
  ],
  "0803719000": [
    "Agutayan",
    "Atabay",
    "Baas",
    "Bagong Lipunan",
    "Bagumbayan",
    "Baliw",
    "Bantigue",
    "Bon-ot",
    "Bung-aw",
    "Cacao",
    "Campina",
    "Catandog 1",
    "Catandog 2",
    "Central Barangay (Pob.)",
    "Concepcion",
    "Eastern Barangay (Pob.)",
    "Hampangan",
    "Himo-aw",
    "Hitudpan",
    "Imelda Marcos",
    "Kang-iras",
    "Kangha-as",
    "Lamak",
    "Libertad",
    "Liberty",
    "Lunang",
    "Magnangoy",
    "Manaul",
    "Marangog",
    "Matapay",
    "Naval",
    "Owak",
    "Pa-a",
    "Pontod",
    "Proteccion",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Juan",
    "San Roque",
    "Santa Cruz",
    "Santa Margarita",
    "Santo Niño",
    "Tabunok",
    "Tagnate",
    "Talisay",
    "Tambis",
    "Tejero",
    "Tuguipa",
    "Utanan",
    "Western Barangay (Pob.)",
  ],
  "0803720000": [
    "Anahaw",
    "Anolon",
    "Baldoza",
    "Bontoc",
    "Bulacan",
    "Canha-ayon",
    "Capudlosan",
    "Doos Del Norte",
    "Doos Del Sur",
    "Himacugo",
    "Himokilan Island",
    "Katipunan",
    "Maasin",
    "Mabagon",
    "Mahilum",
    "Poblacion 1",
    "Poblacion 2",
    "San Vicente",
    "Tabok",
    "Tagbibi",
  ],
  "0803721000": [
    "Apid",
    "Cabulisan",
    "Caminto",
    "Can-angay",
    "Caulisihan",
    "Conalum",
    "De los Santos",
    "Esperanza",
    "Guadalupe",
    "Guinsanga-an",
    "Hinabay",
    "Jubasan",
    "Linao",
    "Macagoco",
    "Maljo",
    "Marao",
    "Poblacion",
    "Tahud",
    "Taotaon",
    "Tinago",
  ],
  "0803722000": [
    "Anislag",
    "Antipolo",
    "Apale",
    "Bantigue",
    "Benog",
    "Bilwang",
    "Can-andan",
    "Cangag",
    "Consolacion",
    "Honan",
    "Libertad",
    "Mahayag",
    "Marvel (Pob.)",
    "Matlang",
    "Monte Alegre",
    "Puting Bato",
    "San Francisco",
    "San Roque",
    "Santa Cruz",
    "Santo Niño (Pob.)",
    "Santo Rosario",
    "Tabunok",
    "Tolingon",
    "Tubod",
  ],
  "0803723000": [
    "Alahag",
    "Anibongan",
    "Atipolo",
    "Badiang",
    "Batug",
    "Bias Zabala",
    "Buenavista",
    "Bukid",
    "Burabod",
    "Buri",
    "Canapuan",
    "Canhandugan",
    "Crossing Rubas",
    "Daro",
    "District I (Pob.)",
    "District II (Pob.)",
    "District III (Pob.)",
    "District IV (Pob.)",
    "Hiagsam",
    "Hibucawan",
    "Hibunawon",
    "Kaglawaan",
    "Kalinawan",
    "La Paz",
    "Likod",
    "Macanip",
    "Macopa",
    "Mag-aso",
    "Malobago",
    "Olotan",
    "Palanog",
    "Pange",
    "Parasan",
    "Pitogo",
    "Sagkahan",
    "San Agustin",
    "San Pedro",
    "San Roque",
    "Santa Cruz",
    "Santo Niño",
    "Sari-sari",
    "Tinambacan",
    "Tuba",
    "Uguiao",
    "Villa Paz",
    "Villagonzoilo",
  ],
  "0803724000": [
    "Abuyogay",
    "Andres Bonifacio",
    "Batug",
    "Binulho",
    "Calzada",
    "Cancayang",
    "Caranhug",
    "Caraye",
    "Casalungan",
    "Comatin",
    "Guindapunan",
    "Inayupan",
    "Laray",
    "Magsaysay",
    "Malitbogay",
    "Manarug",
    "Manlilisid",
    "Naliwatan",
    "Odiong",
    "Picas Norte",
    "Pinocawan",
    "Poblacion Zone 1",
    "Poblacion Zone 2",
    "Rizal",
    "San Sotero",
    "Santa Cruz",
    "Talisayan",
    "Ulhay",
  ],
  "0803725000": [
    "Alegria",
    "Anibong",
    "Aslum",
    "Balante",
    "Bongdo",
    "Bonifacio",
    "Bugho",
    "Calbasag",
    "Caridad",
    "Cuya-e",
    "Dita",
    "Gitabla",
    "Hindang",
    "Inawangan",
    "Jurao",
    "Poblacion District I",
    "Poblacion District II",
    "Poblacion District III",
    "Poblacion District IV",
    "San Andres",
    "San Pablo",
    "Santa Cruz",
    "Santo Niño",
    "Tagkip",
    "Tolosahay",
    "Villa Hermosa",
  ],
  "0803726000": [
    "Aguiting",
    "Cacao",
    "Hiluctogan",
    "Kawayan",
    "Libertad",
    "Libongao",
    "Lim-ao",
    "Lonoy",
    "Mahawan",
    "Masarayao",
    "Monte Alegre",
    "Monte Bello",
    "Naghalin",
    "Natubgan",
    "Poblacion",
    "Rizal",
    "San Ignacio",
    "San Isidro",
    "Santo Domingo",
    "Santo Niño",
    "Tagaytay",
    "Tongonan",
    "Tugbong",
  ],
  "0803728000": [
    "Bagacay East",
    "Bagacay West",
    "Bocawon",
    "Bongtod",
    "Buracan",
    "Caabangan",
    "Cacao",
    "Cagngaran",
    "Calabnian",
    "Calaghusan",
    "Caltayan",
    "Canbañez",
    "Cogon",
    "Duyog",
    "Gimenarat East",
    "Gimenarat West",
    "Limba",
    "Lubi-lubi",
    "Luneta",
    "Mag-aso",
    "Moroboro",
    "Pansud",
    "Pawa",
    "Piliway",
    "Poblacion District 1",
    "Poblacion District 2",
    "Poblacion District 3",
    "Poblacion District 4",
    "Quiong",
    "Rizal",
    "San Victoray",
    "Santa Ana",
    "Santa Elena",
    "Tabang",
    "Tarugan",
  ],
  "0803729000": [
    "Bachao",
    "Baco",
    "Bagaba-o",
    "Basud",
    "Belen",
    "Burabod",
    "Calaguise",
    "Consuegra",
    "Culasi",
    "Danus",
    "Elizabeth",
    "Kawayan",
    "Libas",
    "Maanda",
    "Macupa",
    "Mataloto",
    "Palarao",
    "Palid I",
    "Palid II",
    "Parasan",
    "Poblacion",
    "Salog",
    "Sambulawan",
    "Tag-abaca",
    "Tapol",
    "Tigbawan",
    "Tinocdugan",
    "Toctoc",
    "Ugbon",
    "Wague",
  ],
  "0803730000": [
    "Batug",
    "Burabod",
    "Capudlosan",
    "Casuntingan",
    "Causwagan",
    "Danao",
    "Doña Josefa",
    "General Luna",
    "Kiling",
    "Lanawan",
    "Liwayway",
    "Maya",
    "Oguisan",
    "Osmeña",
    "Palale 1",
    "Palale 2",
    "Poblacion District 1",
    "Poblacion District 2",
    "Poblacion District 3",
    "Pongon",
    "Quezon",
    "Romualdez",
    "Salvacion",
    "San Antonio",
    "San Isidro",
    "San Pedro",
    "San Vicente",
    "Santa Isabel",
    "Tinawan",
    "Tuyo",
    "Villa Imelda",
  ],
  "0803731000": [
    "Campin",
    "Cuatro De Agosto",
    "Hiluctogan",
    "Hilusig",
    "Himamara",
    "Hinaguimitan",
    "Liberacion",
    "Mabuhay",
    "Mabunga",
    "Magsuganao",
    "Mahayag",
    "Mahayahay",
    "Maligaya",
    "Malinao",
    "Malipoon",
    "Palañogan",
    "Paril",
    "Pinamonoan",
    "Poblacion",
    "Polahongon",
    "San Isidro",
    "San Juan",
    "Santa Cruz",
    "Santo Niño",
    "Tagaytay",
    "Uguis",
    "Union",
    "Upper Mahaplag",
  ],
  "0803733000": [
    "Balagtas",
    "Bonoy (Pob.)",
    "Bulak",
    "Cambadbad",
    "Candelaria",
    "Cansoso",
    "Imelda",
    "Malazarte",
    "Mansahaon",
    "Mansalip (Pob.)",
    "Masaba",
    "Naulayan",
    "Riverside (Pob.)",
    "San Dionisio",
    "San Guillermo",
    "San Marcelino",
    "San Sebastian",
    "San Vicente",
    "Santa Rosa",
    "Santo Rosario",
    "Talisay (Pob.)",
  ],
  "0803734000": [
    "Agbanga",
    "Altavista",
    "Bagong Lipunan",
    "Cahagnaan",
    "Calumpang",
    "Caningag",
    "Caridad Norte",
    "Caridad Sur",
    "Elevado",
    "Esperanza",
    "Hitoog",
    "Itum",
    "Lowan",
    "Monte Alegre",
    "President Garcia",
    "Punong",
    "San Isidro (Pob.)",
    "San Juan",
    "San Pedro (Pob.)",
    "San Salvador",
    "San Vicente",
    "Santa Fe",
    "Santa Paz",
    "Santo Niño (Pob.)",
    "Tag-os",
    "Taglibas Imelda",
    "Templanza",
    "Tigbao",
    "Waterloo",
    "Zaragoza",
  ],
  "0803735000": [
    "A. Bonifacio",
    "Burgos",
    "Calipayan",
    "Camansi",
    "General Antonio Luna",
    "Liberty",
    "Mabini",
    "Ormocay",
    "Poblacion Zone 1",
    "Poblacion Zone 2",
    "Poblacion Zone 3",
    "San Roque",
    "Santa Cruz",
    "Talisay",
    "Union",
    "Wilson",
  ],
  "0803736000": [
    "Binabaye",
    "Cabaliwan",
    "Calunangan",
    "Calunasan",
    "Cambalong",
    "Can-unzo",
    "Canbantug",
    "Casilda",
    "Lamanoc",
    "Libas",
    "Libjo",
    "Lundag",
    "Macario",
    "Mahalit",
    "Mahayag",
    "Masumbang",
    "Mat-e",
    "Poblacion",
    "Puerto Bello",
    "San Isidro",
    "San Jose",
    "Tubod",
  ],
  "0803738000": [
    "Airport",
    "Alegria",
    "Alta Vista",
    "Bagong",
    "Bagong Buhay",
    "Bantigue",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 12 (Pob.)",
    "Barangay 13 (Pob.)",
    "Barangay 14 (Pob.)",
    "Barangay 15 (Pob.)",
    "Barangay 16 (Pob.)",
    "Barangay 17 (Pob.)",
    "Barangay 18 (Pob.)",
    "Barangay 19 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 20 (Pob.)",
    "Barangay 21 (Pob.)",
    "Barangay 22 (Pob.)",
    "Barangay 23 (Pob.)",
    "Barangay 24 (Pob.)",
    "Barangay 25 (Pob.)",
    "Barangay 26 (Pob.)",
    "Barangay 27 (Pob.)",
    "Barangay 28 (Pob.)",
    "Barangay 29 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Batuan",
    "Bayog",
    "Biliboy",
    "Borok",
    "Cabaon-an",
    "Cabintan",
    "Cabulihan",
    "Cagbuhangin",
    "Camp Downes",
    "Can-adieng",
    "Can-untog",
    "Catmon",
    "Cogon Combado",
    "Concepcion",
    "Curva",
    "Danao",
    "Danhug",
    "Dayhagan",
    "Dolores",
    "Domonar",
    "Don Felipe Larrazabal",
    "Don Potenciano Larrazabal",
    "Doña Feliza Z. Mejia",
    "Donghol",
    "Esperanza",
    "Gaas",
    "Green Valley",
    "Guintigui-an",
    "Hibunawon",
    "Hugpa",
    "Ipil",
    "Juaton",
    "Kadaohan",
    "Labrador",
    "Lao",
    "Leondoni",
    "Libertad",
    "Liberty",
    "Licuma",
    "Liloan",
    "Linao",
    "Luna",
    "Mabato",
    "Mabini",
    "Macabug",
    "Magaswi",
    "Mahayag",
    "Mahayahay",
    "Manlilinao",
    "Margen",
    "Mas-in",
    "Matica-a",
    "Milagro",
    "Monterico",
    "Nasunogan",
    "Naungan",
    "Nueva Sociedad",
    "Nueva Vista",
    "Patag",
    "Punta",
    "Quezon, Jr.",
    "Rufina M. Tan",
    "Sabang Bao",
    "Salvacion",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Pablo",
    "San Vicente",
    "Santo Niño",
    "Sumangga",
    "Tambulilid",
    "Tongonan",
    "Valencia",
  ],
  "0803739000": [
    "Anahaway",
    "Arado",
    "Baras",
    "Barayong",
    "Buri (Pob.)",
    "Cabarasan Daku",
    "Cabarasan Guti",
    "Campetik",
    "Candahug",
    "Cangumbang",
    "Canhidoc",
    "Capirawan",
    "Castilla",
    "Cavite East (Pob.)",
    "Cavite West (Pob.)",
    "Cogon",
    "Gacao",
    "Guindapunan",
    "Libertad",
    "Luntad (Pob.)",
    "Naga-naga",
    "Pawing",
    "Salvacion",
    "San Agustin",
    "San Antonio",
    "San Fernando",
    "San Isidro",
    "San Joaquin",
    "San Jose",
    "San Miguel (Pob.)",
    "Santa Cruz (Pob.)",
    "Tacuranga",
    "Teraza",
  ],
  "0803740000": [
    "Baguinbin",
    "Belen",
    "Bitaog Pob.",
    "Buenavista",
    "Caduhaan",
    "Cambakbak",
    "Cambinoy",
    "Cangcosme",
    "Cangmuya",
    "Canipaan",
    "Cantandoy",
    "Cantuhaon",
    "Catigahan",
    "Central 1 (Pob.)",
    "Central 2 (Pob.)",
    "Cruz",
    "Duljugan",
    "Guiwan 1 (Pob.)",
    "Guiwan 2 (Pob.)",
    "Himarco",
    "Hinablayan Pob.",
    "Hinagbuan",
    "Lat-osan",
    "Liberty",
    "Lomonon",
    "Mabini",
    "Magsaysay",
    "Masaba",
    "Mazawalo Pob.",
    "Parilla",
    "Pinagdait Pob.",
    "Pinaghi-usa Pob.",
    "Plaridel",
    "Rizal",
    "Sabang",
    "San Guillermo",
    "San Isidro",
    "San Joaquin",
    "San Juan",
    "San Miguel",
    "San Pablo",
    "San Pedro",
    "San Roque",
    "Santiago",
    "Taberna",
    "Tabunok",
    "Tambis",
    "Tinabilan",
    "Tinago",
    "Tinubdan",
  ],
  "0803741000": [
    "Arabunog",
    "Aringit",
    "Bahay",
    "Cabaohan",
    "Calsadahay",
    "Cancaraja",
    "Caninoan",
    "Capilla",
    "Colawen",
    "District 1 (Pob.)",
    "District 2 (Pob.)",
    "District 3 (Pob.)",
    "District 4 (Pob.)",
    "Dumarag",
    "Guindapunan",
    "Halaba",
    "Jones",
    "Lanawan",
    "Lima",
    "Lourdes",
    "Macalpiay",
    "Malitbogay",
    "Manaybanay",
    "Maricum",
    "Patong",
    "Sapsap",
    "Socsocon",
    "Tingib",
    "Yapad",
  ],
  "0803742000": [
    "Banat-e",
    "Basud",
    "Bawod (Pob.)",
    "Biasong",
    "Bunacan",
    "Busay",
    "Cabungaan",
    "Capiñahan (Pob.)",
    "Crossing (Pob.)",
    "Daja-daku",
    "Daja-diot",
    "Hacienda Maria",
    "Linao",
    "Matungao",
    "Paril",
    "San Jose",
    "San Miguel",
    "Taglawigan",
    "Tinago",
  ],
  "0803743000": [
    "Bagacay",
    "Bahay",
    "Bairan",
    "Cabatianuhan",
    "Canap",
    "Capilihan",
    "Caraycaray",
    "Cayare",
    "Guinciaman",
    "Impo",
    "Kinalumsan",
    "Libtong",
    "Lukay",
    "Malaguinabot",
    "Malpag",
    "Mawodpawod",
    "Patong",
    "Pinarigusan",
    "San Andres",
    "Santa Cruz",
    "Santol",
  ],
  "0803744000": [
    "Baculanad",
    "Badiangay",
    "Bulod",
    "Catoogan",
    "Cutay",
    "Gapas",
    "Katipunan",
    "Milagrosa",
    "Pilit",
    "Pitogo",
    "San Isidro",
    "San Juan",
    "San Miguelay",
    "San Roque",
    "Tibak",
    "Victoria",
    "Zone 1 (Pob.)",
    "Zone 2 (Pob.)",
    "Zone 3 (Pob.)",
    "Zone 4 Pob.",
  ],
  "0803745000": [
    "Butason I",
    "Butason II",
    "Campokpok",
    "Catmon",
    "Gibacungan",
    "Gimarco",
    "Inangatan",
    "Manlawaan",
    "Omaganhan",
    "Poblacion",
    "Santa Rosa",
    "Tabing",
    "Tugas",
  ],
  "0803746000": [
    "Amandangay",
    "Aslum",
    "Balingasag",
    "Belisong",
    "Cambucao",
    "Capahuan",
    "District I Pob.",
    "District II Pob.",
    "District III Pob.",
    "District IV Pob.",
    "Guingawan",
    "Jabong",
    "Mercadohay",
    "Mering",
    "Mohon",
    "San Pablo",
  ],
  "0803748000": [
    "Ada",
    "Amanluran",
    "Arado",
    "Atipolo",
    "Balud",
    "Bangon",
    "Bantagan",
    "Baras",
    "Binolo",
    "Binongto-an",
    "Bislig",
    "Buntay (Pob.)",
    "Cabalagnan",
    "Cabarasan Guti",
    "Cabonga-an",
    "Cabuynan",
    "Cahumayhumayan",
    "Calogcog",
    "Calsadahay",
    "Camire",
    "Canbalisara",
    "Canramos (Pob.)",
    "Catigbian",
    "Catmon",
    "Cogon",
    "Guindag-an",
    "Guingawan",
    "Hilagpad",
    "Kiling",
    "Lapay",
    "Licod (Pob.)",
    "Limbuhan Daku",
    "Limbuhan Guti",
    "Linao",
    "Magay",
    "Maghulod",
    "Malaguicay",
    "Maribi",
    "Mohon",
    "Pago",
    "Pasil",
    "Pikas",
    "Sacme",
    "Salvador",
    "San Isidro",
    "San Miguel (Pob.)",
    "San Roque (Pob.)",
    "San Victor",
    "Santa Cruz",
    "Santa Elena",
    "Santo Niño Pob.",
    "Solano",
    "Talolora",
    "Tugop",
  ],
  "0803749000": [
    "Burak",
    "Canmogsay",
    "Cantariwis",
    "Capangihan",
    "Doña Brigida",
    "Imelda",
    "Malbog",
    "Olot",
    "Opong",
    "Poblacion",
    "Quilao",
    "San Roque",
    "San Vicente",
    "Tanghas",
    "Telegrafo",
  ],
  "0803750000": [
    "Astorga",
    "Balire",
    "Banawang",
    "San Antonio (Pob.)",
    "San Pedro",
    "San Roque",
    "San Vicente (Pob.)",
    "Santo Niño (Pob.)",
  ],
  "0803751000": [
    "Abijao",
    "Balite",
    "Bangcal",
    "Bugabuga",
    "Cabunga-an",
    "Cabungahan",
    "Cagnocot",
    "Cahigan",
    "Calbugos",
    "Camporog",
    "Canquiason",
    "Capinyahan",
    "Casili-on",
    "Catagbacan",
    "Fatima (Pob.)",
    "Hibulangan",
    "Hinabuyan",
    "Iligay",
    "Jalas",
    "Jordan",
    "Libagong",
    "New Balanac",
    "Payao",
    "Poblacion Norte",
    "Poblacion Sur",
    "Sambulawan",
    "San Francisco",
    "San Vicente",
    "Santa Cruz",
    "Silad",
    "Suba",
    "Sulpa",
    "Tabunok",
    "Tagbubunga",
    "Tinghub",
  ],
  "0804801000": [
    "Alejandro Village",
    "Bonifacio",
    "Cabacungan",
    "Calarayan",
    "Frederic",
    "Guin-arawayan",
    "Imelda",
    "Jubasan",
    "Kinabranan Zone I (Pob.)",
    "Kinabranan Zone II (Pob.)",
    "Kinaguitman",
    "Lagundi",
    "Lipata",
    "Lo-oc",
    "Londres",
    "Sabang Zone I (Pob.)",
    "Sabang Zone II (Pob.)",
    "Santa Rita",
    "Tasvilla",
    "Victoria",
  ],
  "0804802000": [
    "Kauswagan",
    "MacArthur",
    "Pio Del Pilar",
    "Poblacion",
    "Progresso",
    "San Antonio",
    "San Pedro",
    "Santo Niño",
  ],
  "0804803000": [
    "Acerida",
    "Arellano",
    "Balat-balud",
    "Calantiao",
    "Dancalan",
    "E. Duran",
    "Gen. Lucban (Pob.)",
    "Jose Abad Santos",
    "Jose P. Laurel",
    "Magsaysay",
    "Quezon",
    "Salvacion",
    "San Isidro",
    "San Juan (Pob.)",
    "Santa Clara (Pob.)",
    "Santander",
    "Somoroy",
    "Trojello",
  ],
  "0804804000": [
    "Aguin",
    "Jubang",
    "Landusan",
    "Oson",
    "Poblacion Barangay 1",
    "Poblacion Barangay 2",
    "Poblacion Barangay 3",
    "Poblacion Barangay 4",
    "Poblacion Barangay 5",
    "Sagaosawan",
    "San Luis",
    "Sawang",
  ],
  "0804805000": [
    "Acacia (Pob.)",
    "Aguinaldo",
    "Airport Village",
    "Bangkerohan",
    "Baybay",
    "Bocsol",
    "Cabayhan",
    "Cag-abaca",
    "Cal-igang",
    "Calachuchi (Pob.)",
    "Cawayan",
    "Cervantes",
    "Cularima",
    "Daganas",
    "Dalakit (Pob.)",
    "Doña Pulqueria",
    "Galutan",
    "Gebalagnan",
    "Gebulwangan",
    "General Malvar",
    "Guba",
    "Hinatad",
    "Imelda",
    "Ipil-ipil (Pob.)",
    "Jose Abad Santos (Pob.)",
    "Jose P. Rizal (Pob.)",
    "Kasoy (Pob.)",
    "Lapu-lapu (Pob.)",
    "Liberty",
    "Libjo",
    "Mabini",
    "Mabolo (Pob.)",
    "Macagtas",
    "Mckinley",
    "Molave (Pob.)",
    "Narra (Pob.)",
    "New Rizal",
    "Old Rizal",
    "Paticua",
    "Polangi",
    "Quezon",
    "Salvacion",
    "Sampaguita (Pob.)",
    "San Julian",
    "San Pascual",
    "Santol (Pob.)",
    "Somoge",
    "Talisay (Pob.)",
    "Tinowaran",
    "Trangue",
    "UEP I",
    "UEP II",
    "UEP III",
    "Washington",
    "Yakal (Pob.)",
  ],
  "0804806000": [
    "Anongo",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Bonifacio",
    "Boring",
    "Cagbugna",
    "Cagmanaba",
    "Cagogobngan",
    "Calingnan",
    "Canuctan",
    "Claro M. Recto",
    "D. Mercader",
    "Guibwangan",
    "Hinagonoyan",
    "Hiparayan",
    "Hitapi-an",
    "Inoburan",
    "Irawahan",
    "Lenoyahan",
    "Libon",
    "Magongon",
    "Magtuad",
    "Manering",
    "Nabulo",
    "Nagoocan",
    "Nahulid",
    "Opong",
    "Osang",
    "Osmeña",
    "P. Rebadulla",
    "Roxas",
    "Sagudsuron",
    "San Antonio",
    "San Francisco",
    "San Jose",
    "San Vicente",
    "Santa Fe",
    "Sulitan",
    "Tangbo",
    "Tungodnon",
    "Vienna Maria",
  ],
  "0804807000": [
    "Anito",
    "Bangon",
    "Bato",
    "Baybay District (Pob.)",
    "Bonifacio",
    "Burabod (Pob.)",
    "Cabarasan",
    "Cadac-an",
    "Cade-an",
    "Cagamutan del Norte",
    "Cagamutan del Sur",
    "Dao",
    "G. M. Osias",
    "Gamay Central (Pob.)",
    "Gamay Occidental I (Pob.)",
    "Gamay Oriental I (Pob.)",
    "Guibuangan",
    "Henogawe",
    "Libertad (Pob.)",
    "Lonoy",
    "Luneta",
    "Malidong",
    "Occidental II (Pob.)",
    "Oriental II (Pob.)",
    "Rizal",
    "San Antonio",
  ],
  "0804808000": [
    "Abaton",
    "Aguadahan",
    "Aroganga",
    "Atipolo",
    "Bawang",
    "Baybay (Pob.)",
    "Binatiklan",
    "Bobolosan",
    "Bongliw",
    "Burabud",
    "Cabadiangan",
    "Cabagngan",
    "Cabago-an",
    "Cabulaloan",
    "Cagaasan",
    "Cagdara-o",
    "Cahayagan",
    "Calintaan Pob.",
    "Calomotan",
    "Candawid",
    "Cangcahipos",
    "Canyomanao",
    "Catigbian",
    "E. J. Dulay",
    "G. B. Tan",
    "Gibatangan",
    "Guilaoangi (Pob.)",
    "Inamlan",
    "La Perla",
    "Langob",
    "Lawaan",
    "Little Venice (Pob.)",
    "Magsaysay",
    "Marubay",
    "Mualbual",
    "Napotiocan",
    "Oleras",
    "Onay",
    "Palmera",
    "Pangdan",
    "Rawis",
    "Rombang",
    "San Antonio",
    "San Miguel Heights (Pob.)",
    "Sangcol",
    "Sibunot",
    "Simora",
    "Suba",
    "Talisay",
    "Tan-awan",
    "Tarusan",
    "Tinoblan",
    "Tumaguingting (Pob.)",
    "Vigo",
    "Yabyaban",
    "Yapas",
  ],
  "0804809000": [
    "Alang-alang",
    "Bagacay",
    "Cahagwayan",
    "Can Maria",
    "Can Omanio",
    "Imelda",
    "Lapinig Del Norte (Pob.)",
    "Lapinig Del Sur (Pob.)",
    "Lo-ok",
    "Mabini",
    "May-igot",
    "Palanas",
    "Pio Del Pilar",
    "Potong",
    "Potong Del Sur",
  ],
  "0804810000": [
    "Balugo",
    "Bugay",
    "Bugtosan",
    "Bukid",
    "Bulao",
    "Caputoan",
    "Catoto-ogan",
    "Cuenco",
    "Dapdap",
    "Del Pilar",
    "Dolores",
    "Epaw",
    "Geguinta",
    "Geracdo",
    "Guyo",
    "H. Jolejole",
    "H. Jolejole District (Pob.)",
    "Hangi",
    "Imelda",
    "L. Empon",
    "Lakandula",
    "Lourdes",
    "Lumala-og",
    "Mabini",
    "Macarthur",
    "Magsaysay",
    "Matelarag",
    "Osmeña",
    "Paco",
    "Palanas",
    "Perez",
    "Poponton",
    "Quezon",
    "Quirino",
    "Quirino District (Pob.)",
    "Rebong",
    "Rizal",
    "Roxas",
    "Rufino",
    "Sag-od",
    "San Andres",
    "San Antonio",
    "San Fernando",
    "San Francisco",
    "San Isidro",
    "San Jorge",
    "San Jose",
    "San Miguel",
    "Santo Tomas",
    "Tagab-iran",
    "Tagan-ayan",
    "Taylor",
    "Victory",
  ],
  "0804811000": [
    "Balicuatro",
    "Bani",
    "Barobaybay",
    "Caburihan (Pob.)",
    "Caragas (Pob.)",
    "Cataogan (Pob.)",
    "Chansvilla",
    "Datag",
    "Enriqueta",
    "Libas",
    "Libertad",
    "Macarthur",
    "Magsaysay",
    "Maravilla",
    "Ocad (Pob.)",
    "Sabong-Tabok",
    "Salvacion",
    "San Agustin",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Miguel",
    "To-og",
    "Urdaneta",
    "Villa",
    "Villahermosa",
  ],
  "0804812000": [
    "Burgos",
    "Del Norte (Pob.)",
    "Del Sur (Pob.)",
    "E. Laodenio",
    "Jubasan",
    "Magsaysay",
    "Magtaon",
    "Manaybanay",
    "Naparasan",
    "Quezon",
    "San Jose",
    "Santa Potenciana (Pob.)",
    "Siljagon",
  ],
  "0804813000": [
    "Bagasbas",
    "Bugko",
    "Cablangan",
    "Cagmanaba",
    "Cahicsan",
    "Chitongco (Pob.)",
    "De Maria",
    "Doña Lucia",
    "Eco (Pob.)",
    "Flormina",
    "Hinabangan",
    "Imelda",
    "La Trinidad",
    "Makiwalo",
    "Mirador",
    "Nenita",
    "Roxas",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Juan",
    "Santa Catalina",
    "Talolora",
  ],
  "0804814000": [
    "Asum (Pob.)",
    "Bagacay",
    "Bangon",
    "Benigno S. Aquino, Jr.",
    "Binay",
    "Cabariwan",
    "Cabatuan",
    "Campedico",
    "Capacujan",
    "Jangtud",
    "Laniwan (Pob.)",
    "Mabaras",
    "Magsaysay",
    "Manajao",
    "Mapno",
    "Maragano",
    "Matambag",
    "Monbon",
    "Nagbobtac",
    "Napo",
    "Natawo",
    "Nipa",
    "Osmeña",
    "Pangpang",
    "Paysud",
    "Sangay",
    "Simora",
    "Sinalaran",
    "Sumoroy",
    "Talolora",
    "Tambangan (Pob.)",
    "Tinampo (Pob.)",
  ],
  "0804815000": [
    "Cababto-an",
    "Cabari-an",
    "Cagbigajo",
    "Camparanga",
    "Canjumadal",
    "Doña Anecita",
    "Ge-adgawan",
    "Geparayan",
    "Ginulgan",
    "Igot",
    "Inanahawan",
    "Manahao",
    "Paninirongan",
    "Poblacion District 1",
    "Poblacion District 2",
    "Poblacion District 3",
    "Poblacion District 4",
    "Poblacion District 5",
    "Poblacion District 6",
    "Poblacion District 7",
    "Poblacion District 8",
    "San Ramon",
    "Senonogan",
    "Sixto T. Balanguit, Sr.",
    "Tula",
    "Ynaguingayan",
  ],
  "0804816000": [
    "Aguada",
    "Bantolinao",
    "Buenavista",
    "Commonwealth",
    "Guindaulan",
    "Jamoog",
    "Kailingan",
    "Ligaya",
    "Poblacion",
    "Salhag",
    "San Lorenzo",
  ],
  "0804817000": [
    "Burabod",
    "Dalupirit",
    "Manraya",
    "Pilar",
    "Rizal",
    "San Nicolas",
    "Vinisitahan",
    "Ward I (Pob.)",
    "Ward II (Pob.)",
    "Ward III (Pob.)",
  ],
  "0804818000": [
    "Alegria",
    "Balite",
    "Buenavista",
    "Caglanipao",
    "Happy Valley",
    "Mabuhay",
    "Palanit",
    "Poblacion Norte",
    "Poblacion Sur",
    "Salvacion",
    "San Juan",
    "San Roque",
    "Seven Hills",
    "Veriato",
  ],
  "0804819000": [
    "Aguadahan",
    "Bagong Sabang",
    "Balite",
    "Barangay East (Pob.)",
    "Barangay North (Pob.)",
    "Barangay South (Pob.)",
    "Barangay West (Pob.)",
    "Bonglas",
    "Da-o",
    "Gengarog",
    "Geratag",
    "Layuhan",
    "Mandugang",
    "P. Tingzon",
    "San Lorenzo",
    "Tubigdanao",
  ],
  "0804820000": [
    "Balnasan",
    "Balud",
    "Bantayan",
    "Coroconog",
    "Dale",
    "Ginagdanan",
    "Lao-angan",
    "Lawaan",
    "Malobago",
    "Pagsang-an",
    "Zone 1 (Pob.)",
    "Zone 2 (Pob.)",
    "Zone 3 (Pob.)",
    "Zone 4 (Pob.)",
    "Zone 5 (Pob.)",
    "Zone 6 (Pob.)",
  ],
  "0804821000": [
    "Destacado Pob.",
    "Maragat",
    "Mongol Bongol Pob.",
    "Punta Pob.",
    "Sangputan",
    "Sila",
    "Tarnate",
  ],
  "0804822000": [
    "Balud",
    "Cababayogan",
    "Cabunga-an",
    "Cagda-o",
    "Caghilot",
    "Camanggaran",
    "Camaya-an",
    "Deit De Suba",
    "Deit De Turag",
    "Gebolwangan",
    "Gebonawan",
    "Gecbo-an",
    "Genagasan",
    "Geparayan De Turag",
    "Giguimitan",
    "Gusaran",
    "Imelda",
    "Montalban",
    "Poblacion I",
    "Poblacion II",
    "San Antonio",
    "San Isidro",
    "Senonogan de Tubang",
    "Suba (Pob.)",
    "Tobgon",
    "Victory",
  ],
  "0804823000": [
    "Acedillo",
    "Buenasuerte",
    "Buenos Aires",
    "Colab-og",
    "Erenas",
    "Libertad",
    "Luisita",
    "Lungib",
    "Maxvilla",
    "Pasabuena",
    "San Lazaro",
    "San Miguel",
    "San Roman",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
  ],
  "0804824000": [
    "Bayho",
    "Bonifacio",
    "Cag-aguingay",
    "Cagamesarag",
    "Curry",
    "Gebonawan",
    "Gen. Luna",
    "Getigo",
    "Henaronagan",
    "Lope De Vega (Pob.)",
    "Lower Caynaga",
    "Maghipid",
    "Magsaysay",
    "Osmeña",
    "Paguite",
    "Roxas",
    "Sampaguita",
    "San Francisco",
    "San Jose",
    "San Miguel",
    "Somoroy",
    "Upper Caynaga",
  ],
  "0806001000": [
    "Bacjao",
    "Biasong I",
    "Biasong II",
    "Costa Rica",
    "Costa Rica II",
    "Guin-ansan",
    "Imelda",
    "Kerikite",
    "Lunang I",
    "Lunang II",
    "Mabuhay",
    "Magsaysay",
    "Malobago",
    "Marasbaras",
    "Panjobjoban I",
    "Panjobjoban II",
    "Poblacion",
    "Roño",
    "San Isidro",
    "San Jose",
    "Talahid",
    "Tonga-tonga",
    "Veloso",
  ],
  "0806002000": [
    "Amandayehan",
    "Anglit",
    "Bacubac",
    "Balante",
    "Baloog",
    "Basiao",
    "Baybay (Pob.)",
    "Binongtu-an",
    "Buenavista",
    "Bulao",
    "Burgos",
    "Buscada (Pob.)",
    "Cambayan",
    "Can-abay",
    "Cancaiyas",
    "Canmanila",
    "Catadman",
    "Cogon",
    "Del Pilar",
    "Dolongan",
    "Guintigui-an",
    "Guirang",
    "Iba",
    "Inuntan",
    "Lawa-an (Pob.)",
    "Loog",
    "Loyo (Pob.)",
    "Mabini",
    "Magallanes",
    "Manlilinab",
    "May-it",
    "Mercado (Pob.)",
    "Mongabong",
    "New San Agustin",
    "Nouvelas Occidental",
    "Old San Agustin",
    "Palaypay (Pob.)",
    "Panugmonon",
    "Pelit",
    "Roxas",
    "Salvacion",
    "San Antonio",
    "San Fernando",
    "Sawa",
    "Serum",
    "Sugca",
    "Sugponon",
    "Sulod (Pob.)",
    "Tinaogan",
    "Tingib",
    "Villa Aurora",
  ],
  "0806003000": [
    "Acedillo",
    "Aguit-itan (Pob.)",
    "Alibaba",
    "Amampacang",
    "Anislag",
    "Awang East (Pob.)",
    "Awang West (Pob.)",
    "Ba-ay",
    "Bagacay",
    "Bagong Lipunan",
    "Baja",
    "Balud (Pob.)",
    "Bante",
    "Bantian",
    "Basud",
    "Bayo",
    "Begaho",
    "Binaliw",
    "Bontay",
    "Buenavista",
    "Bugtong",
    "Cabacungan",
    "Cabatuan",
    "Cabicahan",
    "Cabugawan",
    "Cacaransan",
    "Cag-anahaw",
    "Cag-anibong",
    "Cag-olango",
    "Cagbanayacao",
    "Cagbayang",
    "Cagbilwang",
    "Cagboborac",
    "Caglanipao Sur",
    "Cagmanipis Norte",
    "Cagmanipis Sur",
    "Cagnipa",
    "Cagsalaosao",
    "Cahumpan",
    "Calocnayan",
    "Cangomaod",
    "Canhumadac",
    "Capacuhan",
    "Capoocan",
    "Carayman",
    "Carmen",
    "Catabunan",
    "Caybago",
    "Central (Pob.)",
    "Cogon",
    "Dagum",
    "Danao I",
    "Danao II",
    "Dawo",
    "De Victoria",
    "Dinabongan",
    "Dinagan",
    "Dinawacan",
    "Esperanza",
    "Gabay",
    "Gadgaran",
    "Gasdo",
    "Geragaan",
    "Guin-on",
    "Guinbaoyan Norte",
    "Guinbaoyan Sur",
    "Hamorawon",
    "Helino",
    "Hibabngan",
    "Hibatang",
    "Higasaan",
    "Himalandrog",
    "Hugon Rosales",
    "Jacinto",
    "Jimautan",
    "Jose A. Roño",
    "Kalilihan",
    "Kilikili",
    "La Paz",
    "Langoyon",
    "Lapaan",
    "Libertad",
    "Limarayon",
    "Longsob",
    "Lonoy",
    "Looc",
    "Mabini I",
    "Mabini II",
    "Macatingog",
    "Mag-ubay",
    "Malaga",
    "Malajog",
    "Malayog",
    "Malopalo",
    "Mancol",
    "Manguino-o",
    "Mantaong",
    "Manuel Barral, Sr.",
    "Marcatubig",
    "Matobato",
    "Mawacat",
    "Maybog",
    "Maysalong",
    "Migara",
    "Nabang",
    "Nag-uma",
    "Naga",
    "Navarro",
    "Nijaga",
    "Oboob",
    "Obrero",
    "Olera",
    "Oquendo (Pob.)",
    "Osmeña",
    "Pagbalican",
    "Palanas",
    "Palanogan",
    "Panlayahan",
    "Panonongon",
    "Panoypoy",
    "Patong",
    "Payahan",
    "Peña",
    "Pilar",
    "Pinamorotan",
    "Quezon",
    "Rawis",
    "Rizal I",
    "Rizal II",
    "Roxas I",
    "Roxas II",
    "Saljag",
    "Salvacion",
    "San Antonio",
    "San Isidro",
    "San Joaquin",
    "San Jose",
    "San Policarpo",
    "San Rufino",
    "Saputan",
    "Sigo",
    "Sinantan",
    "Sinidman Occidental",
    "Sinidman Oriental",
    "Tabawan",
    "Talahiban",
    "Tanval",
    "Tapae",
    "Tarabucan",
    "Tigbe",
    "Tinambacan Norte",
    "Tinambacan Sur",
    "Tinaplacan",
    "Tomaliguez",
    "Trinidad",
    "Victory",
    "Villahermosa",
  ],
  "0806004000": [
    "Antol",
    "Bacyaran",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barobaybay",
    "Beri",
    "Binanggaran",
    "Borong",
    "Bulao",
    "Buluan",
    "Caamlongan",
    "Calayaan",
    "Calingonan",
    "Canbagtic",
    "Canticum",
    "Daligan",
    "Guinbanga",
    "Hindang",
    "Hubasan",
    "Literon",
    "Lubang",
    "Macaalan",
    "Mahangcao",
    "Malabal",
    "Minata",
    "Otoc",
    "Panayuran",
    "Pasigay",
    "Patong",
    "Polangi",
    "Rawis",
    "San Ignacio",
    "San Mauricio",
    "Sinalangtan",
    "Timbangan",
    "Tinago",
  ],
  "0806005000": [
    "Albalate",
    "Bagongon",
    "Bangon",
    "Basiao",
    "Buluan",
    "Bunuanan",
    "Cabugawan",
    "Cagudalo",
    "Cagusipan",
    "Cagutian",
    "Cagutsan",
    "Canhawan Gote",
    "Canlapwas (Pob.)",
    "Cawayan",
    "Cinco",
    "Darahuway Daco",
    "Darahuway Gote",
    "Estaka",
    "Guindaponan",
    "Guinsorongan",
    "Ibol",
    "Iguid",
    "Lagundi",
    "Libas",
    "Lobo",
    "Manguehay",
    "Maulong",
    "Mercedes",
    "Mombon",
    "Muñoz",
    "New Mahayag",
    "Old Mahayag",
    "Palanyogon",
    "Pangdan",
    "Payao",
    "Poblacion 1",
    "Poblacion 10",
    "Poblacion 11",
    "Poblacion 12",
    "Poblacion 13",
    "Poblacion 2",
    "Poblacion 3",
    "Poblacion 4",
    "Poblacion 5",
    "Poblacion 6",
    "Poblacion 7",
    "Poblacion 8",
    "Poblacion 9",
    "Pupua",
    "Rama",
    "San Andres",
    "San Pablo",
    "San Roque",
    "San Vicente",
    "Silanga",
    "Socorro",
    "Totoringon",
  ],
  "0806006000": [
    "Arawane",
    "Astorga",
    "Bachao",
    "Baclayan",
    "Bagacay",
    "Bayog",
    "Betaug",
    "Birawan",
    "Bono-anon",
    "Buenavista",
    "Burgos",
    "Cabac",
    "Cabil-isan",
    "Cabiton-an",
    "Cabugao",
    "Cagboboto",
    "Calawan-an",
    "Cambuhay",
    "Campelipa",
    "Candugue",
    "Canloloy",
    "Cansaganay",
    "Casab-ahan",
    "Guindapunan",
    "Guintampilan",
    "Iquiran",
    "Jacopon",
    "Losa",
    "Lucob-lucob",
    "Mabini",
    "Macalpe",
    "Mandoyucan",
    "Marupangdan",
    "Mayabay",
    "Mongolbongol",
    "Nipa",
    "Parasan",
    "Poblacion 1",
    "Poblacion 2",
    "Poblacion 3",
    "Pondang",
    "Poso",
    "Real",
    "Rizal",
    "San Antonio",
    "San Jose",
    "San Miguel",
    "San Roque",
    "San Vicente",
    "Saugan",
    "So-ong",
    "Sua",
    "Sugod",
    "Talisay",
    "Tugas",
    "Ubo",
    "Valles-Bello",
    "Yangta",
  ],
  "0806007000": [
    "Adela Heights (Pob.)",
    "Arong",
    "Balocawe",
    "Bangahon",
    "Beslig",
    "Buao",
    "Bunyagan",
    "Burabod I (Pob.)",
    "Burabod II (Pob.)",
    "Calirocan",
    "Canhumawid",
    "Caparangasan",
    "Caranas",
    "Carmona",
    "Casab-ahan",
    "Casandig",
    "Catorse De Agosto",
    "Caugbusan",
    "Concepcion",
    "Diaz",
    "Dumalo-ong (Pob.)",
    "Elcano",
    "Gerali",
    "Gereganan",
    "Giaboc",
    "Hampton",
    "Hetebac",
    "Himamaloto",
    "Hinayagan",
    "Hinugacan",
    "Hiparayan",
    "Jasminez",
    "Lungib",
    "Mabuhay",
    "Macugo",
    "Malayog",
    "Marcos",
    "Minda (Pob.)",
    "Nacube",
    "Nalihugan",
    "Napalisan",
    "Natimonan",
    "Ngoso",
    "Palambrag",
    "Palanas",
    "Piñaplata",
    "Pizarro",
    "Pologon",
    "Purog",
    "Rawis",
    "Rizal",
    "Samoyao",
    "San Agustin",
    "San Antonio",
    "San Enrique",
    "San Francisco",
    "San Isidro",
    "San Jose",
    "San Miguel",
    "San Pelayo",
    "San Ramon",
    "Santa Elena",
    "Santo Niño",
    "Senibaran",
    "Sidmon",
    "Tagnao",
    "Tambongan",
    "Tawiran",
    "Tigbawon",
  ],
  "0806008000": [
    "Bagacay",
    "Binobucalan",
    "Bucalan",
    "Cabalagnan",
    "Cabang",
    "Canano",
    "Concord",
    "Consolabao",
    "Dalosdoson",
    "Fatima",
    "Lim-ao",
    "Malihao",
    "Mugdo",
    "Osmeña",
    "Poblacion 1",
    "Poblacion 2",
    "Rawis",
    "San Jose",
    "San Rafael",
    "Tabay",
    "Yabon",
  ],
  "0806009000": [
    "Barangay No. 1 (Pob.)",
    "Barangay No. 2 (Pob.)",
    "Barangay No. 3 (Pob.)",
    "Barangay No. 4 (Pob.)",
    "Barangay No. 5 (Pob.)",
    "Barangay No. 6 (Pob.)",
    "Barangay No. 7 (Pob.)",
    "Barangay No. 8 (Pob.)",
    "Bawang",
    "Bugho",
    "Camarobo-an",
    "Candayao",
    "Cantongtong",
    "Casapa",
    "Catalina",
    "Cristina",
    "Dogongan",
    "Garcia",
    "Hinaga",
    "Jia-an",
    "Jidanao",
    "Lulugayan",
    "Macabetas",
    "Malino",
    "Malobago",
    "Mercedes",
    "Nagbac",
    "Parina",
    "Salvacion",
    "San Andres",
    "San Fernando",
    "San Miguel",
    "Tagbayaon",
    "Victory",
  ],
  "0806010000": [
    "Amambucale",
    "Amantillo",
    "Binukyahan",
    "Caluwayan",
    "Canyoyo",
    "Catato Pob.",
    "Ferreras",
    "Legaspi",
    "Lipata",
    "Logero",
    "Mabuhay",
    "Malobago",
    "Odoc",
    "Osmeña",
    "Panan-awan",
    "Pinalanga",
    "Pinamitinan (Pob.)",
    "Roño",
    "San Roque",
    "Santa Rita",
    "Santo Niño Pob.",
    "Tagalag",
    "Tinabanan",
    "Veloso",
  ],
  "0806011000": [
    "Angyap",
    "Bag-otan",
    "Barruz",
    "Camonoan",
    "Carolina",
    "Deit",
    "Del Rosario",
    "Inubod",
    "Libertad",
    "Ligaya",
    "Mabuligon Pob.",
    "Maduroto Pob.",
    "Mahanud",
    "Mahayag",
    "Nagpapacao",
    "Rizal",
    "Salvacion",
    "San Isidro",
    "San Roque",
    "Santa Cruz",
  ],
  "0806012000": [
    "Angyap",
    "Barayong",
    "Bayog",
    "Beri",
    "Bonga",
    "Calantawan",
    "Calapi",
    "Caluyahan",
    "Canatuan",
    "Candomacol",
    "Canvais",
    "Capaysagan",
    "Caranas",
    "Caulayanan",
    "Hinica-an",
    "Inalad",
    "Linonoban",
    "Malobago",
    "Malonoy",
    "Mararangsi",
    "Maypange",
    "New Minarog",
    "Oyandic",
    "Pamamasan",
    "Poblacion I",
    "Poblacion I-A",
    "Pusongan",
    "San Andres",
    "Santo Niño",
    "Sarao",
  ],
  "0806013000": [
    "Bangon",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Botoc",
    "Bugho",
    "Calampong",
    "Canlobo",
    "Catigawan",
    "Dolores",
    "Lale",
    "Lawaan",
    "Laygayon",
    "Layo",
    "Loctob",
    "Madalunot",
    "Magdawat",
    "Mambog",
    "Manaing",
    "Nabong",
    "Obayan",
    "Pahug",
    "Parasanon",
    "Pelaon",
    "San Isidro",
  ],
  "0806014000": [
    "Aguingayan",
    "Babaclayon",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Can-aponte",
    "Cataydongan",
    "Gusa",
    "Hagbay",
    "Hibaca-an",
    "Hiduroma",
    "Hilumot",
    "San Nicolas",
  ],
  "0806015000": [
    "Balogo",
    "Bontod",
    "Cabaywa",
    "Camanhagay",
    "Campiyak",
    "Canduyucan",
    "Dolores",
    "Hita-asan I",
    "Hita-asan II",
    "Inobongan",
    "Poblacion Barangay 1",
    "Poblacion Barangay 2",
    "Poblacion Barangay 3",
    "Poblacion Barangay 4",
  ],
  "0806016000": [
    "Agrupacion",
    "Arapison",
    "Avelino",
    "Bahay",
    "Balud",
    "Bana-ao",
    "Burabod",
    "Cagsumji",
    "Campeig",
    "Camperito",
    "Can-ipulan",
    "Canmoros",
    "Cautod (Pob.)",
    "Cinco",
    "Curry",
    "Gajo",
    "Hindang",
    "Ilo",
    "Imelda",
    "Inoraguiao",
    "Jolacao",
    "Lambao",
    "Mabuhay",
    "Mahayag",
    "Matayonas",
    "Monbon (Pob.)",
    "Nabulo",
    "Napuro",
    "Napuro II",
    "Palale",
    "Panabatan",
    "Panaruan",
    "Roxas",
    "Salvacion",
    "Solsogon",
    "Sundara",
  ],
  "0806017000": [
    "Alegria",
    "Anibongan",
    "Aslum",
    "Bagolibas",
    "Binanalan",
    "Bokinggan Pob.",
    "Bougainvilla Pob.",
    "Cabacungan",
    "Cabunga-an",
    "Camayse",
    "Cansadong",
    "Caticugan",
    "Dampigan",
    "Guinbalot-an",
    "Gumamela Pob.",
    "Hinangudtan",
    "Igang-igang",
    "La Paz",
    "Lupig",
    "Magsaysay",
    "Maligaya",
    "New Manunca",
    "Old Manunca",
    "Pagsulhogon",
    "Rosal Pob. ",
    "Salvacion",
    "San Eduardo",
    "San Isidro",
    "San Juan",
    "San Pascual",
    "San Pedro",
    "San Roque",
    "Santa Elena",
    "Santan Pob.",
    "Tagacay",
    "Tominamos",
    "Tulay",
    "Union",
  ],
  "0806018000": [
    "Balatguti",
    "Baras",
    "Basud (Pob.)",
    "Buenavista",
    "Cabunga-an",
    "Corocawayan",
    "Ilijan",
    "Ilo (Pob.)",
    "Lobelobe",
    "Pinanangnan",
    "Sevilla",
    "Takut",
    "Villahermosa",
  ],
  "0806019000": [
    "Bo. Independencia",
    "Malaguining",
    "Mallorga",
    "Navatas Daku",
    "Navatas Guti",
    "Placer",
    "Poblacion Barangay 1",
    "Poblacion Barangay 2",
    "San Juan",
    "Tatabunan",
    "Victory",
  ],
  "0806020000": [
    "Alcazar",
    "Awang",
    "Bahay",
    "Balonga-as",
    "Balugo",
    "Bangon Gote",
    "Baras",
    "Binalayan",
    "Bisitahan",
    "Bonga",
    "Cabunga-an",
    "Cagtutulo",
    "Cambatutay Nuevo",
    "Cambatutay Viejo",
    "Canunghan",
    "Catan-agan",
    "Dapdap",
    "Gallego",
    "Imelda Pob.",
    "Lahong",
    "Libucan Dacu",
    "Libucan Gote",
    "Lucerdoni",
    "Majacob",
    "Mancares",
    "Marabut",
    "Oeste - A",
    "Oeste - B",
    "Pajo",
    "Palencia",
    "Poblacion A",
    "Poblacion B",
    "Poblacion C",
    "Poblacion D",
    "Poblacion E",
    "San Vicente",
    "Santa Cruz",
    "Sugod",
    "Talinga",
    "Tigdaranao",
    "Tizon",
  ],
  "0806021000": [
    "Banquil",
    "Bino-ongan",
    "Burabod",
    "Cambaguio",
    "Canmucat",
    "Central (Pob.)",
    "Conant",
    "Guintarcan",
    "Himyangan",
    "Igot",
    "Inarumbacan",
    "Inasudlan",
    "Lam-awan",
    "Lamingao",
    "Lawa-an",
    "Macopa",
    "Mahayag",
    "Malonoy",
    "Mercado (Pob.)",
    "Miramar (Pob.)",
    "Nagcaduha",
    "Pacao",
    "Pacoyoy",
    "Pangpang",
    "Patag",
    "Plaridel",
    "Polangi",
    "San Andres",
    "San Fernando",
    "San Rafael",
    "San Roque",
    "Santa Rosa",
    "Santo Niño",
    "Soledad (Pob.)",
    "Tayud (Pob.)",
    "Tomabe",
    "Ulayan",
    "Villarosa Pob.",
  ],
  "0806022000": [
    "Anagasi",
    "Apolonia",
    "Bagsa",
    "Balbagan",
    "Bato",
    "Buray",
    "Cantaguic",
    "Cantao-an",
    "Cantato",
    "Casandig I",
    "Casandig II",
    "Cawayan",
    "Concepcion",
    "Jose Roño",
    "Lawaan I",
    "Lawaan II",
    "Lipata",
    "Lokilokon",
    "Mangcal",
    "Maylobe",
    "Minarog",
    "Nawi",
    "Pabanog",
    "Paco",
    "Pagsa-ogan",
    "Pagsanjan",
    "Patag",
    "Pequit",
    "Poblacion 1",
    "Poblacion 2",
    "Poblacion 3",
    "Poblacion 4",
    "Poblacion 5",
    "Poblacion 6",
    "Salay",
    "San Isidro",
    "Santo Niño",
    "Sulopan",
    "Tabucan",
    "Tapul",
    "Tenani",
    "Tigbawon",
    "Tula",
    "Tutubigan",
  ],
  "0806023000": [
    "Alegria",
    "Arteche",
    "Bioso",
    "Boblaran",
    "Botaera",
    "Buntay",
    "Camayse",
    "Canwarak",
    "Ibarra",
    "Lumalantang",
    "Macalunod",
    "Maga-an",
    "Maputi",
    "Marapilit",
    "Monbon",
    "Mualbual",
    "Pangdan",
    "Poblacion 1",
    "Poblacion 2",
    "Poro",
    "San Isidro",
    "Sugod",
    "Talib",
    "Tinaugan",
    "Tubigan",
  ],
  "0806024000": [
    "Baguiw",
    "Balocawe",
    "Guinbarucan",
    "Labangbaybay",
    "Luna",
    "Mataluto",
    "Nipa",
    "Pantalan",
    "Pulangbato",
    "San Jose (Pob.)",
    "San Vicente",
    "Suarez",
    "Sugod (Pob.)",
    "Trinidad",
  ],
  "0806025000": [
    "Anquiana",
    "Aurora",
    "Bay-ang",
    "Blanca Aurora",
    "Buenavista I",
    "Buenavista II",
    "Bulao",
    "Bungliw",
    "Cabugao",
    "Cag-olo-olo",
    "Calundan",
    "Cantaguic",
    "Canyaki",
    "Cogtoto-og",
    "Erenas",
    "Gayondato",
    "Guadalupe",
    "Guindapunan",
    "Hernandez",
    "Himay",
    "Janipon",
    "La Paz",
    "Libertad",
    "Lincoro",
    "Mabuhay",
    "Mancol (Pob.)",
    "Matalud",
    "Mobo-ob",
    "Mombon",
    "Puhagan",
    "Quezon",
    "Ranera",
    "Rawis",
    "Rosalim",
    "San Isidro",
    "San Jorge I (Pob.)",
    "San Jorge II (Pob.)",
    "San Juan",
    "Sapinit",
    "Sinit-an",
    "Tomogbong",
  ],
  "0806026000": [
    "Bangon",
    "Buenos Aires",
    "Calanyugan",
    "Caloloma",
    "Cambaye",
    "Canlapwas (Pob.)",
    "Libertad",
    "Pañge",
    "San Luis",
    "Santo Niño",
    "Viejo",
    "Villahermosa Occidental",
    "Villahermosa Oriental",
  ],
  "0806401000": [
    "Amagusan",
    "Calintaan",
    "Canlabian",
    "Capacuhan",
    "Cogon",
    "Kagingkingan",
    "Lewing",
    "Lo-ok",
    "Mahalo",
    "Mainit",
    "Manigawong",
    "Poblacion",
    "San Vicente",
    "Tagup-on",
  ],
  "0806402000": [
    "Anahao",
    "Banahao",
    "Baugo",
    "Beniton",
    "Buenavista",
    "Bunga",
    "Casao",
    "Catmon",
    "Catoogan",
    "Cawayanan",
    "Dao",
    "Divisoria",
    "Esperanza",
    "Guinsangaan",
    "Hibagwan",
    "Hilaan",
    "Himakilo",
    "Hitawos",
    "Lanao",
    "Lawgawan",
    "Mahayahay",
    "Malbago",
    "Mauylab",
    "Olisihan",
    "Paku",
    "Pamahawan",
    "Pamigsian",
    "Pangi",
    "Poblacion",
    "Pong-on",
    "Sampongon",
    "San Ramon",
    "San Vicente",
    "Santa Cruz",
    "Santo Niño",
    "Taa",
    "Talisay",
    "Taytagan",
    "Tuburan",
    "Union",
  ],
  "0806403000": [
    "Ambacon",
    "Badiangon",
    "Bangcas A",
    "Bangcas B",
    "Biasong",
    "Bugho",
    "Calag-itan",
    "Calayugan",
    "Calinao",
    "Canipaan",
    "Catublian",
    "Ilaya",
    "Ingan",
    "Labrador",
    "Libas",
    "Lumbog",
    "Manalog",
    "Manlico",
    "Matin-ao",
    "Nava",
    "Nueva Esperanza",
    "Otama",
    "Palongpong",
    "Panalaron",
    "Patong",
    "Poblacion",
    "Pondol",
    "Salog",
    "Salvacion",
    "San Pablo Island",
    "San Pedro Island",
    "Santo Niño I",
    "Santo Niño II",
    "Tahusan",
    "Talisay",
    "Tawog",
    "Toptop",
    "Tuburan",
    "Union",
    "Upper Bantawon",
  ],
  "0806404000": [
    "Amaga",
    "Ambao",
    "An-an",
    "Baculod",
    "Biasong",
    "Bugho",
    "Cabulisan",
    "Cat-iwing",
    "District I (Pob.)",
    "District II (Pob.)",
    "District III (Pob.)",
    "Hubasan",
    "Lungsodaan",
    "Navalita",
    "Plaridel",
    "Sabang",
    "Sagbok",
  ],
  "0806405000": [
    "Biasong",
    "Bogasong",
    "Cawayan",
    "Gakat",
    "Jubas (Pob.)",
    "Magkasag",
    "Mayuga",
    "Nahaong",
    "Nahulid",
    "Otikon",
    "Pangi",
    "Punta",
    "Talisay (Pob.)",
    "Tigbao",
  ],
  "0806406000": [
    "Amaga",
    "Anilao",
    "Bahay",
    "Cagbungalon",
    "Calian",
    "Caligangan",
    "Candayuman",
    "Catig",
    "Estela",
    "Fatima",
    "Gud-an",
    "Guintoylan",
    "Himayangan",
    "Ilag",
    "Magaupas",
    "Malangsa",
    "Molopolo",
    "Pandan",
    "Poblacion",
    "Pres. Quezon",
    "President Roxas",
    "San Isidro",
    "San Roque",
    "Tabugon",
  ],
  "0806407000": [
    "Abgao (Pob.)",
    "Acasia",
    "Asuncion",
    "Bactul I",
    "Bactul II",
    "Badiang",
    "Bagtican",
    "Basak",
    "Bato I",
    "Bato II",
    "Batuan",
    "Baugo",
    "Bilibol",
    "Bogo",
    "Cabadiangan",
    "Cabulihan",
    "Cagnituan",
    "Cambooc",
    "Cansirong",
    "Canturing",
    "Canyuom",
    "Combado",
    "Dongon",
    "Gawisan",
    "Guadalupe",
    "Hanginan",
    "Hantag",
    "Hinapu Daku",
    "Hinapu Gamay",
    "Ibarra",
    "Isagani",
    "Laboon",
    "Lanao",
    "Lib-og",
    "Libertad",
    "Libhu",
    "Lonoy",
    "Lunas",
    "Mahayahay",
    "Malapoc Norte",
    "Malapoc Sur",
    "Mambajao (Pob.)",
    "Manhilo",
    "Mantahan (Pob.)",
    "Maria Clara",
    "Matin-ao",
    "Nasaug",
    "Nati",
    "Nonok Norte",
    "Nonok Sur",
    "Panan-awan",
    "Pansaan",
    "Pasay",
    "Pinascohan",
    "Rizal",
    "San Agustin",
    "San Isidro",
    "San Jose",
    "San Rafael",
    "Santa Cruz",
    "Santa Rosa",
    "Santo Niño",
    "Santo Rosario",
    "Soro-soro",
    "Tagnipa (Pob.)",
    "Tam-is",
    "Tawid",
    "Tigbawan",
    "Tomoy-tomoy",
    "Tunga-tunga (Pob.)",
  ],
  "0806408000": [
    "Aguinaldo",
    "Amparo",
    "Asuncion",
    "Bagong Silang",
    "Buscayan",
    "Cambaro",
    "Canlusay",
    "Danao",
    "Flordeliz",
    "Guadalupe",
    "Ichon",
    "Ilihan",
    "Laray",
    "Lower Villa Jacinta",
    "Mabini",
    "Mohon",
    "Molopolo",
    "Rizal",
    "Salvador",
    "San Isidro",
    "San Joaquin",
    "San Roque",
    "San Vicente",
    "San Vicente Poblacion",
    "Santa Cruz (Pob.)",
    "Santo Niño",
    "Santo Rosario (Pob.)",
    "Sindangan",
    "Upper Ichon",
    "Upper Villa Jacinta",
  ],
  "0806409000": [
    "Abgao",
    "Asuncion",
    "Aurora",
    "Benit",
    "Caaga",
    "Cabul-anonan (Pob.)",
    "Cadaruhan",
    "Cadaruhan Sur",
    "Candatag",
    "Cantamuac",
    "Caraatan",
    "Concepcion",
    "Fatima",
    "Guinabonan",
    "Iba",
    "Juangon",
    "Kauswagan",
    "Lambonao",
    "Mahayahay",
    "Maningning",
    "Maujo",
    "New Katipunan",
    "Pancil",
    "Pasil (Pob.)",
    "Sabang",
    "San Antonio (Pob.)",
    "San Isidro",
    "San Jose",
    "San Roque",
    "San Vicente",
    "Sangahon",
    "Santa Cruz",
    "Santo Niño",
    "Taliwa (Pob.)",
    "Tigbawan I",
    "Tigbawan II",
    "Timba",
  ],
  "0806410000": [
    "Buenavista",
    "Bunga",
    "Cantutang",
    "Dinahugan",
    "Laca",
    "Lungsodaan",
    "Poblacion",
    "San Juan",
    "Santa Sofia",
    "Santo Rosario",
    "Tangkaan",
  ],
  "0806411000": [
    "Badiang",
    "Balongbalong",
    "Buenavista",
    "Bulawan",
    "Canlawis",
    "Catbawan",
    "Caubang",
    "Cogon",
    "Dan-an",
    "Lobo",
    "Mainit",
    "Manglit",
    "Nueva Estrella Norte",
    "Nueva Estrella Sur",
    "Poblacion Ibabao",
    "Poblacion Ubos",
    "Pociano D. Equipilag",
    "Ponod",
    "San Roque",
    "Santa Cruz",
    "Son-ok I",
    "Son-ok II",
    "Tautag",
  ],
  "0806412000": [
    "Atuyan",
    "Ayahag",
    "Bantawon",
    "Bolodbolod",
    "Cabagawan",
    "Carnaga",
    "Catmon",
    "Guinsaugon",
    "Himatagon (Pob.)",
    "Himbangan",
    "Himos-onan",
    "Hinabian",
    "Hindag-an",
    "Kauswagan",
    "Libas",
    "Lipanto",
    "Magatas",
    "Magbagacay",
    "Mahayag",
    "Mahayahay",
    "Malibago",
    "Malinao",
    "Nueva Esperanza",
    "Panian",
    "San Isidro",
    "Santa Cruz",
    "Sug-angon",
    "Tabontabon",
    "Tambis I",
    "Tambis II",
  ],
  "0806413000": [
    "Anislagon",
    "Bongawisan",
    "Bongbong",
    "Cahayag",
    "Causi",
    "Central (Pob.)",
    "Dakit (Pob.)",
    "Gabi",
    "Habay",
    "Malico",
    "Marayag",
    "Napantao",
    "Pasanon",
    "Pinamudlan",
    "Punta",
    "Santa Cruz",
    "Santa Paz Norte",
    "Santa Paz Sur",
    "Sudmon",
    "Tinaan",
    "Tuno",
    "Ubos (Pob.)",
  ],
  "0806414000": [
    "Agay-ay",
    "Basak",
    "Bobon A",
    "Bobon B",
    "Dayanog",
    "Garrido",
    "Minoyho",
    "Osao",
    "Pong-oy",
    "San Jose (Pob.)",
    "San Roque",
    "San Vicente",
    "Santa Cruz (Pob.)",
    "Santa Filomena",
    "Santo Niño (Pob.)",
    "Somoje",
    "Sua",
    "Timba",
  ],
  "0806415000": [
    "Benit",
    "Bitoon",
    "Cabutan",
    "Camang",
    "Esperanza",
    "Esperanza Dos",
    "Inolinan",
    "Kinachawa",
    "Looc",
    "Pinut-an",
    "Poblacion",
    "San Antonio",
    "San Ramon",
    "Saub",
    "Timba",
  ],
  "0806416000": [
    "Balagawan",
    "Catmon",
    "Hingatungan",
    "Imelda",
    "Katipunan",
    "Laguma",
    "Mercedes",
    "Pob. District I",
    "Pob. District II",
    "Puntana",
    "Salvacion",
    "Sap-ang",
    "Sudmon",
    "Tuba-on",
    "Tubod",
  ],
  "0806417000": [
    "Benit",
    "Buac Daku",
    "Buac Gamay",
    "Cabadbaran",
    "Concepcion",
    "Consolacion",
    "Dagsa",
    "Hibod-hibod",
    "Hindangan",
    "Hipantag",
    "Javier",
    "Kahupian",
    "Kanangkaan",
    "Kauswagan",
    "La Purisima Concepcion",
    "Libas",
    "Lum-an",
    "Mabicay",
    "Mac",
    "Magatas",
    "Mahayahay",
    "Malinao",
    "Maria Plana",
    "Milagroso",
    "Olisihan",
    "Pancho Villa",
    "Pandan",
    "Rizal",
    "Salvacion",
    "San Francisco Mabuhay",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Miguel",
    "San Pedro",
    "San Roque",
    "San Vicente",
    "Santa Maria",
    "Suba",
    "Tampoong",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)",
    "Zone V (Pob.)",
  ],
  "0806418000": [
    "Anahawan",
    "Banday (Pob.)",
    "Biasong",
    "Bogo (Pob.)",
    "Cabascan",
    "Camansi",
    "Cambite (Pob.)",
    "Canlupao",
    "Carnaga",
    "Cawayan",
    "Higosoan",
    "Hinagtikan",
    "Hinapo",
    "Hugpa",
    "Iniguihan Pob.",
    "Looc",
    "Luan",
    "Maanyag",
    "Mag-ata",
    "Mapgap",
    "Maslog",
    "Ponong",
    "Rizal",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Miguel",
    "San Roque",
    "Tinago",
  ],
  "0806419000": [
    "Cabulihan",
    "Lugsongan",
    "Magallanes",
    "San Agustin",
    "San Bernardo",
    "Triana",
  ],
  "0807801000": [
    "Caucab",
    "Iyosan",
    "Jamorawon",
    "Lo-ok",
    "Matanga",
    "Pili",
    "Poblacion",
    "Pulang Bato",
    "Salangi",
    "Sampao",
    "Tabunan",
    "Talahid",
    "Tamarindo",
  ],
  "0807802000": [
    "Bato",
    "Burabod",
    "Busali",
    "Canila",
    "Hugpa",
    "Julita",
    "Pinangumhan",
    "San Isidro (Pob.)",
    "San Roque (Pob.)",
    "Sanggalang",
    "Villa Enage",
  ],
  "0807803000": [
    "Balaquid",
    "Baso",
    "Bunga",
    "Caanibongan",
    "Casiawan",
    "Esperanza (Pob.)",
    "Langgao",
    "Libertad",
    "Looc",
    "Magbangon (Pob.)",
    "Pawikan",
    "Salawad",
    "Talibong",
  ],
  "0807804000": [
    "Alegria",
    "Asug",
    "Bari-is",
    "Binohangan",
    "Cabibihan",
    "Caulangohan",
    "Kawayanon",
    "Looc",
    "Manlabang",
    "Maurang",
    "Palanay (Pob.)",
    "Palengke (Pob.)",
    "Tomalistis",
    "Union",
    "Uson",
    "Victory (Pob.)",
    "Villa Vicenta",
  ],
  "0807805000": [
    "Acaban",
    "Bacolod",
    "Binongtoan",
    "Bool Central (Pob.)",
    "Bool East (Pob.)",
    "Bool West (Pob.)",
    "Calipayan",
    "Culaba Central (Pob.)",
    "Guindapunan",
    "Habuhab",
    "Looc",
    "Marvel (Pob.)",
    "Patag",
    "Pinamihagan",
    "Salvacion",
    "San Roque",
    "Virginia (Pob.)",
  ],
  "0807806000": [
    "Baganito",
    "Balacson",
    "Balite",
    "Bilwang",
    "Bulalacao",
    "Burabod",
    "Buyo",
    "Inasuyan",
    "Kansanok",
    "Mada-o",
    "Mapuyo",
    "Masagaosao",
    "Masagongsong",
    "Poblacion",
    "San Lorenzo",
    "Tabunan North",
    "Tubig Guinoo",
    "Tucdao",
    "Ungale",
    "Villa Cornejo",
  ],
  "0807807000": [
    "Agutay",
    "Banlas",
    "Bato",
    "Binalayan East",
    "Binalayan West",
    "Binongto-an",
    "Burabod",
    "Calbani",
    "Canduhao",
    "Casibang",
    "Danao",
    "Ermita",
    "Ol-og",
    "Trabugan",
    "Viga",
  ],
  "0807808000": [
    "Agpangi",
    "Anislagan",
    "Atipolo",
    "Borac",
    "Cabungaan",
    "Calumpang",
    "Capiñahan",
    "Caraycaray",
    "Catmon",
    "Haguikhikan",
    "Imelda",
    "Larrazabal",
    "Libertad",
    "Libtong",
    "Lico",
    "Lucsoon",
    "Mabini",
    "Padre Inocentes Garcia (Pob.)",
    "Padre Sergio Eamiguel",
    "Sabang",
    "San Pablo",
    "Santissimo Rosario Pob.",
    "Santo Niño",
    "Talustusan",
    "Villa Caneja",
    "Villa Consuelo",
  ],
  "0831600000": [
    "Barangay 100",
    "Barangay 101",
    "Barangay 102",
    "Barangay 103",
    "Barangay 103-A",
    "Barangay 104",
    "Barangay 105",
    "Barangay 106",
    "Barangay 107",
    "Barangay 108",
    "Barangay 109",
    "Barangay 109-A",
    "Barangay 110",
    "Barangay 12",
    "Barangay 13",
    "Barangay 14",
    "Barangay 15",
    "Barangay 16",
    "Barangay 17",
    "Barangay 18",
    "Barangay 19",
    "Barangay 2",
    "Barangay 20",
    "Barangay 21",
    "Barangay 21-A",
    "Barangay 22",
    "Barangay 23",
    "Barangay 23-A",
    "Barangay 24",
    "Barangay 25",
    "Barangay 26",
    "Barangay 27",
    "Barangay 28",
    "Barangay 29",
    "Barangay 30",
    "Barangay 31",
    "Barangay 32",
    "Barangay 33",
    "Barangay 34",
    "Barangay 35",
    "Barangay 35-A",
    "Barangay 36",
    "Barangay 36-A",
    "Barangay 37",
    "Barangay 37-A",
    "Barangay 38",
    "Barangay 39",
    "Barangay 40",
    "Barangay 41",
    "Barangay 42",
    "Barangay 42-A",
    "Barangay 43",
    "Barangay 43-A",
    "Barangay 43-B",
    "Barangay 44",
    "Barangay 44-A",
    "Barangay 45",
    "Barangay 46",
    "Barangay 47",
    "Barangay 48",
    "Barangay 48-A",
    "Barangay 48-B",
    "Barangay 49",
    "Barangay 5",
    "Barangay 5-A",
    "Barangay 50",
    "Barangay 50-A",
    "Barangay 50-B",
    "Barangay 51",
    "Barangay 51-A",
    "Barangay 52",
    "Barangay 53",
    "Barangay 54",
    "Barangay 54-A",
    "Barangay 56",
    "Barangay 56-A",
    "Barangay 57",
    "Barangay 58",
    "Barangay 59",
    "Barangay 59-A",
    "Barangay 59-B",
    "Barangay 6",
    "Barangay 6-A",
    "Barangay 60",
    "Barangay 60-A",
    "Barangay 61",
    "Barangay 62",
    "Barangay 62-A",
    "Barangay 62-B",
    "Barangay 63",
    "Barangay 64",
    "Barangay 65",
    "Barangay 66",
    "Barangay 66-A",
    "Barangay 67",
    "Barangay 68",
    "Barangay 69",
    "Barangay 7",
    "Barangay 70",
    "Barangay 71",
    "Barangay 72",
    "Barangay 73",
    "Barangay 74",
    "Barangay 75",
    "Barangay 76",
    "Barangay 77",
    "Barangay 78",
    "Barangay 79",
    "Barangay 8",
    "Barangay 8-A",
    "Barangay 80",
    "Barangay 81",
    "Barangay 82",
    "Barangay 83",
    "Barangay 83-A",
    "Barangay 83-B",
    "Barangay 83-C",
    "Barangay 84",
    "Barangay 85",
    "Barangay 86",
    "Barangay 87",
    "Barangay 88",
    "Barangay 89",
    "Barangay 90",
    "Barangay 91",
    "Barangay 92",
    "Barangay 93",
    "Barangay 94",
    "Barangay 94-A",
    "Barangay 95",
    "Barangay 95-A",
    "Barangay 96",
    "Barangay 97",
    "Barangay 98",
    "Barangay 99",
    "El Reposo",
    "Libertad",
    "Nula-tula",
  ],
};
