/** GENERATED — Region IX: 1904 barangays across 72 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "0907201000": [
    "Aliguay",
    "Antipolo",
    "Aseniero",
    "Ba-ao",
    "Bagting (Pob.)",
    "Banbanan",
    "Banonong (Pob.)",
    "Barcelona",
    "Baylimango",
    "Burgos",
    "Canlucani",
    "Carang",
    "Cawa-cawa (Pob.)",
    "Dampalan",
    "Daro",
    "Dawo (Pob.)",
    "Diwa-an",
    "Guimputlan",
    "Hilltop",
    "Ilaya",
    "Kauswagan",
    "Larayan",
    "Linabo (Pob.)",
    "Liyang",
    "Maria Cristina",
    "Maria Uray",
    "Masidlakon",
    "Matagobtob Pob.",
    "Napo",
    "Opao",
    "Oro",
    "Owaon",
    "Oyan",
    "Polo",
    "Potol (Pob.)",
    "Potungan",
    "San Francisco",
    "San Nicolas",
    "San Pedro",
    "San Vicente",
    "Santa Cruz (Pob.)",
    "Santo Niño",
    "Selinog",
    "Sicayab-Bucana",
    "Sigayan",
    "Sinonoc",
    "Sulangon",
    "Tag-ulo",
    "Taguilon",
    "Tamion",
  ],
  "0907202000": [
    "Barra (Pob.)",
    "Biasong (Pob.)",
    "Central (Pob.)",
    "Cogon",
    "Dicayas",
    "Diwan",
    "Estaca (Pob.)",
    "Galas",
    "Gulayon",
    "Lugdungan",
    "Minaog",
    "Miputak (Pob.)",
    "Olingan",
    "Punta",
    "San Jose",
    "Sangkol",
    "Santa Filomena",
    "Santa Isabel",
    "Sicayab",
    "Sinaman",
    "Turno",
  ],
  "0907203000": [
    "Balok",
    "Barangay Dos (Pob.)",
    "Barangay Uno (Pob.)",
    "Basagan",
    "Biniray",
    "Bulawan",
    "Carupay",
    "Daanglungsod",
    "Dabiak",
    "Dr. Jose Rizal",
    "Fimagas",
    "Loyuran",
    "Malasay",
    "Malugas",
    "Matam",
    "Mias",
    "Miatan",
    "Nanginan",
    "New Tambo",
    "Patik",
    "San Antonio",
    "San Vicente",
    "Sanao",
    "Santo Niño",
    "Seres",
    "Seroan",
    "Singatong",
    "Sinuyak",
    "Sitog",
    "Tuburan",
  ],
  "0907204000": [
    "El Paraiso",
    "La Union",
    "La Victoria",
    "Mauswagon",
    "Mercedes",
    "New Argao",
    "New Bataan",
    "New Carcar",
    "Poblacion",
    "San Jose",
    "Santa Catalina",
    "Santa Cruz",
    "Singaran",
  ],
  "0907205000": [
    "Antonino (Pob.)",
    "Balas",
    "Bobongan",
    "Dansalan",
    "Gabu",
    "Gil Sanchez",
    "Imelda",
    "Immaculada",
    "Kipit",
    "La Union",
    "Lapatan",
    "Lawagan",
    "Lawigan",
    "Lopoc (Pob.)",
    "Malintuboan",
    "New Salvacion",
    "Osukan",
    "Patawag",
    "San Isidro",
    "Ubay",
  ],
  "0907206000": [
    "Banigan",
    "Baybay (Pob.)",
    "Cabangcalan",
    "Canaan",
    "Candelaria",
    "Causwagan",
    "Communal",
    "Compra",
    "Dela Paz",
    "El Paraiso",
    "Fatima",
    "Ganase",
    "Goaw",
    "Goin",
    "Kayok",
    "La Libertad",
    "Lamao",
    "Mabuhay",
    "Maigang",
    "Malila",
    "Mauswagon",
    "New Bethlehem",
    "Overview",
    "Panabang",
    "Patawag",
    "Punta",
    "San Francisco",
    "San Isidro",
    "San Miguel",
    "San Roque",
    "Santa Cruz",
    "Santo Niño",
    "Silucap",
    "Tapican",
    "Timan",
    "Villa Calixto Sudiacal",
    "Villa M. Tejero",
  ],
  "0907207000": [
    "Dipane",
    "Disakan",
    "Don Jose Aguirre",
    "East Poblacion",
    "Gupot",
    "Libuton",
    "Linay",
    "Lingatongan",
    "Lupasang",
    "Mate",
    "Meses",
    "Palaranan",
    "Pangandao",
    "Patagan",
    "Poblacion",
    "Punta Blanca",
    "Saluyong",
    "San Antonio",
    "Serongan",
    "Suisayan",
    "Upper Disakan",
    "Villaramos",
  ],
  "0907208000": [
    "Alvenda",
    "Buenasuerte",
    "Diland",
    "Diolen",
    "Head Tipan",
    "New Casul",
    "New Siquijor",
    "Newland",
    "Paso Rio",
    "Poblacion",
    "San Miguel",
    "Santo Tomas",
    "Tinglan",
    "Totongon",
    "Tubac",
    "Unidos",
  ],
  "0907209000": [
    "Adante",
    "Bacuyong",
    "Bagong Silang",
    "Calican",
    "Del Pilar",
    "Desin",
    "Dilawa",
    "Dionum",
    "Lapu-lapu",
    "Lower Gumay",
    "Luzvilla",
    "Poblacion North",
    "Poblacion South",
    "Santa Fe",
    "Segabe",
    "Sikitan",
    "Silano",
    "Teresita",
    "Tinaytayan",
    "Ubay",
    "Upper Gumay",
    "Villarico",
  ],
  "0907210000": [
    "Anastacio",
    "Bandera",
    "Bethlehem",
    "Dangi",
    "Dansullan",
    "De Venta Perla",
    "Guinles",
    "Isis",
    "Labrador",
    "Lapayanbaja",
    "Letapan",
    "Linabo",
    "Lingasad",
    "Macleodes",
    "Magangon",
    "Maligaya",
    "Milad",
    "New Lebangon",
    "New Sicayab",
    "Obay",
    "Pian",
    "Poblacion North",
    "Poblacion South",
    "San Antonio",
    "San Miguel",
    "San Pedro",
    "Santo Niño",
    "Sianib",
    "Silawe",
    "Villahermosa",
  ],
  "0907211000": [
    "Balubo",
    "Banbanan",
    "Canibongan",
    "Capase",
    "Cape",
    "Denoman",
    "Dohinob",
    "Galokso",
    "Gubat",
    "Irasan",
    "Labakid",
    "Langatian",
    "Lipakan",
    "Marupay",
    "Moliton",
    "Nabilid",
    "Panampalay",
    "Pangologon",
    "Piao",
    "Piñalan",
    "Piñamar",
    "Pongolan",
    "Salisig",
    "Sebod",
    "Sibatog",
    "Situbo",
    "Tanayan",
    "Tantingon",
    "Upper Irasan",
    "Upper Minang",
    "Villahermoso",
  ],
  "0907212000": [
    "Balubohan",
    "Birayan",
    "Damasing",
    "East Poblacion",
    "La Esperanza",
    "Mabuhay",
    "Mabunao",
    "Mitimos",
    "Nangca",
    "Nangcaan",
    "Napilan",
    "Nasipang",
    "New Dapitan",
    "Nilabo",
    "North Mapang",
    "Rizalina",
    "San Roque",
    "Sebaca",
    "Sipaon",
    "South Mapang",
    "Tolon",
    "West Poblacion",
  ],
  "0907213000": [
    "Bacong",
    "Balakan",
    "Binoni",
    "Calucap",
    "Canawan",
    "Caracol",
    "Danao",
    "Dinoan",
    "Dipolod",
    "Fatima",
    "Ipilan",
    "Lanawan",
    "Liguac",
    "Lipakan",
    "Mucas",
    "Pacuhan",
    "Poblacion",
    "Poblacion East",
    "Pukay",
    "Ramon Magsaysay",
    "Santo Niño",
    "Tambalang",
    "Tapalan",
  ],
  "0907214000": [
    "Antonino",
    "Bagong Baguio",
    "Bagumbayan",
    "Biayon",
    "Buenavista",
    "Dampalan",
    "Danao",
    "Don Eleno",
    "Kauswagan",
    "Labiray",
    "Liwanag",
    "Mabuhay",
    "Macalibre",
    "Mahayahay",
    "Marapong",
    "Nazareth",
    "Nebo",
    "New Rizal",
    "New Tangub",
    "Nuevavista",
    "Pedagan",
    "Penacio",
    "Poblacion Alto",
    "Poblacion Bajo",
    "Princesa Freshia",
    "Princesa Lamaya",
    "San Antonio",
    "San Francisco",
    "San Isidro",
    "San Jose",
    "San Juan",
    "Sinaad",
    "Sinai",
    "Situbo",
    "Tinago",
    "Tinindugan",
    "Tuburan",
    "Venus",
    "Wilben",
  ],
  "0907215000": [
    "Balok",
    "Balunokan",
    "Datagan",
    "Denoyan",
    "Diongan",
    "Domogok",
    "Dumpilas",
    "Gonayen",
    "Guibo",
    "Gunyan",
    "Litolet",
    "Macasing",
    "Mangilay",
    "Moyo",
    "Muñoz",
    "Pange",
    "Paranglumba (Pob.)",
    "Polayo",
    "Sayaw",
    "Seriac",
    "Siayan Proper (Pob.)",
    "Suguilon",
  ],
  "0907216000": [
    "Anongan",
    "Basak",
    "Bongalao",
    "Cabbunan",
    "Cawit-cawit",
    "Culaguan",
    "Cusipan",
    "Dinulan",
    "Jatian",
    "Kamarangan",
    "Lakiki",
    "Lambagoan",
    "Limpapa",
    "Lingayon",
    "Lintangan",
    "Litawan",
    "Lunday",
    "Malayal",
    "Mantivo",
    "Nala (Pob.)",
    "Panganuran",
    "Pangian",
    "Paniran",
    "Pasilnahut",
    "Poblacion",
    "Puliran",
    "Santo Niño",
    "Tangarak",
  ],
  "0907217000": [
    "Bagacay",
    "Calilic",
    "Calube",
    "Delapa",
    "Kanim",
    "Libay",
    "Magsaysay",
    "Marapong",
    "Minlasag",
    "Oyan",
    "Panganuran",
    "Poblacion",
    "Sawang",
    "Sibuloc",
    "Sinipay",
    "Sipaloc",
  ],
  "0907218000": [
    "Bago",
    "Balok",
    "Bantayan",
    "Bato",
    "Benigno Aquino Jr.",
    "Binuangan",
    "Bitoon",
    "Bucana",
    "Calatunan",
    "Caluan",
    "Calubian",
    "Dagohoy",
    "Dapaon",
    "Datagan",
    "Datu Tangkilan",
    "Dicoyong",
    "Disud",
    "Don Ricardo Macias",
    "Doña Josefa",
    "Dumalogdog",
    "Fatima",
    "Gampis",
    "Goleo",
    "Imelda",
    "Inuman",
    "Joaquin Macias",
    "La Concepcion",
    "La Roche San Miguel",
    "Labakid",
    "Lagag",
    "Lapero",
    "Lawis",
    "Magsaysay",
    "Mandih",
    "Maras",
    "Mawal",
    "Misok",
    "Motibot",
    "Nato",
    "Nipaan",
    "Pangalalan",
    "Piao",
    "Poblacion",
    "Santo Niño",
    "Santo Rosario",
    "Siare",
    "Talinga",
    "Tigbao",
    "Tinaplan",
    "Titik",
    "Upper Inuman",
    "Upper Nipaan",
  ],
  "0907219000": [
    "Andres Micubo Jr.",
    "Balagunan",
    "Bucana",
    "Bulacan",
    "Candiz",
    "Datu Sailila",
    "Dionisio Riconalla",
    "Jose P. Brillantes, Sr.",
    "Latabon",
    "Makiang",
    "Malambuhangin",
    "Malipot",
    "Manaol",
    "Mateo Francisco",
    "Matiag",
    "New Lituban",
    "Pangian",
    "Pisawak",
    "Poblacion",
    "S. Cabral",
    "Santa Maria",
    "Siay",
    "Suhaile Arabi",
    "Tabayo",
    "Tagaytay",
    "Tibangao",
  ],
  "0907220000": [
    "Balatakan",
    "Balonkan",
    "Balubuan",
    "Bitugan",
    "Bongon",
    "Catuyan",
    "Culasian",
    "Danganon",
    "Doña Cecilia",
    "Guban",
    "Lagundi",
    "Libucon",
    "Lubok",
    "Macuyon",
    "Minanga",
    "Motong",
    "Napulan",
    "Panabutan",
    "Piacan",
    "Piña",
    "Pisa Itom",
    "Pisa Puti",
    "Pugos",
    "Pula Bato",
    "Pulang Lupa",
    "Saint Mary (Pob.)",
    "San Nicolas (Pob.)",
    "San Roque (Pob.)",
    "San Vicente (Pob.)",
    "Sipakit",
    "Sipawa",
    "Sirawai Proper (Pob.)",
    "Talabiga",
    "Tapanayan",
  ],
  "0907221000": [
    "Balacbaan",
    "Banbanan",
    "Barili",
    "Cabong",
    "Camul",
    "Farmington",
    "Galingon",
    "Lawaan",
    "Lumbayao",
    "Malila-t",
    "Molos",
    "New Dapitan",
    "Poblacion",
    "Sandayong",
    "Santo Niño",
    "Situbo",
    "Tilubog",
    "Tininggaan",
    "Tubod",
    "Znac",
  ],
  "0907222000": [
    "Balatakan",
    "Bitoon",
    "Dinasan",
    "Ilihan",
    "Labakid",
    "Lipay",
    "Litalip",
    "Lopero",
    "Lumanping",
    "Madalag",
    "Manawan",
    "Marupay",
    "Poblacion",
    "Sigamok",
    "Siparok",
    "Tabon",
    "Tamarok",
    "Tamil",
  ],
  "0907223000": [
    "Bacong",
    "Bagong Silang",
    "Banganon",
    "Bayanihan",
    "Buenavista",
    "Canupong",
    "Cocob",
    "Datagan",
    "Imelda",
    "Immaculada Concepcion",
    "La Libertad",
    "Loay",
    "Lower Lux",
    "Lux",
    "Malian",
    "Mamawan",
    "Map",
    "Matunoy",
    "New Dapitan",
    "Panganuran",
    "Pitawe",
    "Pitogo",
    "Poblacion",
    "Salvador",
    "San Isidro",
    "San Juan",
    "San Roque",
    "San Vicente",
    "Santo Niño",
    "Sas",
    "Sibalic",
    "Tipan",
    "Upper Gutalac",
  ],
  "0907224000": [
    "Alegria",
    "Diangas",
    "Diculom",
    "Guimotan",
    "Kauswagan",
    "Kilalaban",
    "Linay",
    "Lumay",
    "Malinao",
    "Mamad",
    "Mamawan",
    "Milidan",
    "Nonoyan",
    "Poblacion",
    "San Jose",
    "Tamao",
    "Tan-awan",
  ],
  "0907225000": [
    "Baluno",
    "Banuangan",
    "Bunawan",
    "Dilucot",
    "Dipopor",
    "Guisapong",
    "Limbonga",
    "Lomogom",
    "Mauswagon",
    "Miampic",
    "Poblacion",
    "Raba",
    "Rambon",
    "San Pedro",
    "Sarawagan",
    "Sianan",
    "Sioran",
  ],
  "0907226000": [
    "Bacungan (Pob.)",
    "Bogabongan",
    "Delusom",
    "Mangop",
    "Manil",
    "Mawal",
    "Midatag",
    "Morob",
    "Nasibac",
    "Rizon",
    "Santa Maria",
    "Sipacong",
    "Talinga",
    "Tinaplan",
    "Tiniguiban",
    "Tinuyop",
    "Tiogan",
    "Titik",
  ],
  "0907227000": [
    "Batayan",
    "Botong",
    "Concepcion",
    "Daniel Maing",
    "Fatima",
    "Gatas",
    "Kalawit (Pob.)",
    "Marcelo",
    "New Calamba",
    "Palalian",
    "Paraiso",
    "Pianon",
    "San Jose",
    "Tugop*",
  ],
  "0907302000": [
    "Acad",
    "Alang-alang",
    "Alegria",
    "Anonang",
    "Bagong Mandaue",
    "Bagong Maslog",
    "Bagong Oslob",
    "Bagong Pitogo",
    "Baki",
    "Balas",
    "Balide",
    "Balintawak",
    "Bayabas",
    "Bemposa",
    "Cabilinan",
    "Campo Uno",
    "Ceboneg",
    "Commonwealth",
    "Gubaan",
    "Inasagan",
    "Inroad",
    "Kahayagan East",
    "Kahayagan West",
    "Kauswagan",
    "La Paz",
    "La Victoria",
    "Lantungan",
    "Libertad",
    "Lintugop",
    "Lubid",
    "Maguikay",
    "Mahayahay",
    "Monte Alegre",
    "Montela",
    "Napo",
    "Panaghiusa",
    "Poblacion",
    "Resthouse",
    "Romarate",
    "San Jose",
    "San Juan",
    "Sapa Loboc",
    "Tagulalo",
    "Waterfall",
  ],
  "0907303000": [
    "Baking",
    "Balukbahan",
    "Balumbunan",
    "Bantal",
    "Bobuan",
    "Camp Blessing",
    "Canoayan",
    "Conacon",
    "Dagum",
    "Damit",
    "Datagan",
    "Depase",
    "Depili",
    "Depore",
    "Deporehan",
    "Dimalinao",
    "Kahayagan",
    "Kanipaan",
    "Lamare",
    "Liba",
    "Matin-ao",
    "Matun-og",
    "Poblacion",
    "Pulang Bato",
    "Salawagan",
    "San Isidro",
    "Sigacad",
    "Supon",
  ],
  "0907305000": [
    "Bacayawan",
    "Baha",
    "Balanagan",
    "Baluno",
    "Binuay",
    "Buburay",
    "Grap",
    "Josefina",
    "Kagawasan",
    "Lalab",
    "Libertad",
    "Magahis",
    "Mahayag",
    "Mercedes",
    "Poblacion",
    "Saloagan",
    "San Roque",
    "Sugbay Uno",
    "Sumbato",
    "Sumpot",
    "Tinggabulong",
    "Tiniguangan",
    "Tipangi",
    "Upper Ludiong",
  ],
  "0907306000": [
    "Bacawan",
    "Benuatan",
    "Beray",
    "Don Jose",
    "Dongos",
    "East Migpulao",
    "Guinicolalay",
    "Ignacio Garrata",
    "Kinacap",
    "Legarda 1",
    "Legarda 2",
    "Legarda 3",
    "Lower Dimaya",
    "Lucoban",
    "Ludiong",
    "Nangka",
    "Nian",
    "Old Mirapao",
    "Pisa-an",
    "Poblacion",
    "Proper Dimaya",
    "Sagacad",
    "Sambulawan",
    "San Isidro",
    "Songayan",
    "Sumpotan",
    "Tarakan",
    "Upper Dimaya",
    "Upper Sibul",
    "West Migpulao",
  ],
  "0907307000": [
    "Anonang",
    "Bag-ong Misamis",
    "Bag-ong Silao",
    "Baga",
    "Baloboan",
    "Banta-ao",
    "Bibilik",
    "Calingayan",
    "Camalig",
    "Camanga",
    "Cuatro-cuatro",
    "Locuban",
    "Malasik",
    "Mama",
    "Matab-ang",
    "Mecolong",
    "Metokong",
    "Motosawa",
    "Pag-asa (Pob.)",
    "Paglaum (Pob.)",
    "Pantad",
    "Piniglibano",
    "Rebokon",
    "San Agustin",
    "Sibucao",
    "Sumadat",
    "Tikwas",
    "Tina",
    "Tubo-Pait",
    "Upper Dumalinao",
  ],
  "0907308000": [
    "Bag-ong Valencia",
    "Bagong Kauswagan",
    "Bagong Silang",
    "Bucayan",
    "Calumanggi",
    "Canibongan",
    "Caridad",
    "Danlugan",
    "Dapiwak",
    "Datu Totocan",
    "Dilud",
    "Ditulan",
    "Dulian",
    "Dulop",
    "Guintananan",
    "Guitran",
    "Gumpingan",
    "La Fortuna",
    "Labangon",
    "Libertad",
    "Licabang",
    "Lipawan",
    "Lower Landing",
    "Lower Timonan",
    "Macasing",
    "Mahayahay",
    "Malagalad",
    "Manlabay",
    "Maralag",
    "Marangan",
    "New Basak",
    "Saad",
    "Salvador",
    "San Juan",
    "San Pablo (Pob.)",
    "San Pedro (Pob.)",
    "San Vicente",
    "Senote",
    "Sinonok",
    "Sunop",
    "Tagun",
    "Tamurayan",
    "Upper Landing",
    "Upper Timonan",
  ],
  "0907311000": [
    "Bogayo",
    "Bolisong",
    "Boyugan East",
    "Boyugan West",
    "Bualan",
    "Diplo",
    "Gawil",
    "Gusom",
    "Kitaan Dagat",
    "Lantawan",
    "Limamawan",
    "Mahayahay",
    "Pangi",
    "Picanan",
    "Poblacion",
    "Salagmanok",
    "Secade",
    "Suminalum",
  ],
  "0907312000": [
    "Bagalupa",
    "Balimbingan",
    "Binayan",
    "Bokong",
    "Bulanit",
    "Cogonan",
    "Combo",
    "Dalapang",
    "Dimasangca",
    "Dipaya",
    "Langapod",
    "Lantian",
    "Lower Campo Islam (Pob.)",
    "Lower Pulacan",
    "Lower Sang-an",
    "New Labangan",
    "Noboran",
    "Old Labangan",
    "San Isidro",
    "Santa Cruz",
    "Tapodoc",
    "Tawagan Norte",
    "Upper Campo Islam (Pob.)",
    "Upper Pulacan",
    "Upper Sang-an",
  ],
  "0907313000": [
    "Bulawan",
    "Carpoc",
    "Danganan",
    "Dansal",
    "Dumara",
    "Linokmadalum",
    "Luanan",
    "Lubusan",
    "Mahalingeb",
    "Mandeg",
    "Maralag",
    "Maruing",
    "Molum",
    "Pampang",
    "Pantad",
    "Pingalay",
    "Poblacion",
    "Salambuyan",
    "San Jose",
    "Sayog",
    "Tabon",
    "Talabob",
    "Tiguha",
    "Tininghalang",
    "Tipasan",
    "Tugaya",
  ],
  "0907315000": [
    "Bag-ong Balamban",
    "Bag-ong Dalaguete",
    "Boniao",
    "Delusom",
    "Diwan",
    "Guripan",
    "Kaangayan",
    "Kabuhi",
    "Lourmah",
    "Lower Salug Daku",
    "Lower Santo Niño",
    "Malubo",
    "Manguiles",
    "Marabanan",
    "Panagaan",
    "Paraiso",
    "Pedagan",
    "Poblacion",
    "Pugwan",
    "San Isidro",
    "San Jose",
    "San Vicente",
    "Santa Cruz",
    "Sicpao",
    "Tuboran",
    "Tulan",
    "Tumapic",
    "Upper Salug Daku",
    "Upper Santo Niño",
  ],
  "0907317000": [
    "Balintawak",
    "Bularong",
    "Digon",
    "Guinimanan",
    "Igat Island",
    "Josefina",
    "Kalian",
    "Kolot",
    "Limamawan",
    "Limbatong",
    "Lumbog",
    "Magahis",
    "Poblacion",
    "Sagua",
    "Talanusa",
    "Tiguian",
    "Tulapok",
  ],
  "0907318000": [
    "Bacahan",
    "Balonai",
    "Bibilop",
    "Buloron",
    "Cabaloran",
    "Canipay Norte",
    "Canipay Sur",
    "Cumaron",
    "Dakayakan",
    "Duelic",
    "Dumalinao",
    "Ecuan",
    "Golictop",
    "Guinabot",
    "Guitalos",
    "Guma",
    "Kahayagan",
    "Licuro-an",
    "Lumpunid",
    "Matalang",
    "New Katipunan",
    "New Unidos",
    "Palili",
    "Pawan",
    "Pili",
    "Pisompongan",
    "Piwan",
    "Poblacion A",
    "Poblacion B",
    "Sigapod",
    "Timbaboy",
    "Tulbong",
    "Tuluan",
  ],
  "0907319000": [
    "Alicia",
    "Ariosa",
    "Bagong Argao",
    "Bagong Gutlang",
    "Blancia",
    "Bogo Capalaran",
    "Culo",
    "Dalaon",
    "Dipolo",
    "Dontulan",
    "Gonosan",
    "Lower Dimalinao",
    "Lower Dimorok",
    "Mabuhay",
    "Madasigon (Pob.)",
    "Makuguihon (Pob.)",
    "Maloloy-on (Pob.)",
    "Miligan",
    "Parasan",
    "Rizal",
    "Santo Rosario",
    "Silangit",
    "Simata",
    "Sudlon",
    "Upper Dimorok",
  ],
  "0907322000": [
    "Alegria",
    "Balangasan (Pob.)",
    "Balintawak",
    "Baloyboan",
    "Banale",
    "Bogo",
    "Bomba",
    "Buenavista",
    "Bulatok",
    "Bulawan",
    "Dampalan",
    "Danlugan",
    "Dao",
    "Datagan",
    "Deborok",
    "Ditoray",
    "Dumagoc",
    "Gatas (Pob.)",
    "Gubac",
    "Gubang",
    "Kagawasan",
    "Kahayagan",
    "Kalasan",
    "Kawit",
    "La Suerte",
    "Lala",
    "Lapidian",
    "Lenienza",
    "Lizon Valley",
    "Lourdes",
    "Lower Sibatang",
    "Lumad",
    "Lumbia",
    "Macasing",
    "Manga",
    "Muricay",
    "Napolan",
    "Palpalan",
    "Pedulonan",
    "Poloyagan",
    "San Francisco (Pob.)",
    "San Jose (Pob.)",
    "San Pedro (Pob.)",
    "Santa Lucia (Pob.)",
    "Santa Maria",
    "Santiago (Pob.)",
    "Santo Niño",
    "Tawagan Sur",
    "Tiguma",
    "Tuburan (Pob.)",
    "Tulangan",
    "Tulawas",
    "Upper Sibatang",
    "White Beach",
  ],
  "0907323000": [
    "Bagong Opon",
    "Bambong Daku",
    "Bambong Diut",
    "Bobongan",
    "Campo IV",
    "Campo V",
    "Caniangan",
    "Dipalusan",
    "Eastern Bobongan",
    "Esperanza",
    "Gapasan",
    "Katipunan",
    "Kauswagan",
    "Lower Sambulawan",
    "Mabini",
    "Magsaysay",
    "Malating",
    "Paradise",
    "Pasingkalan",
    "Poblacion",
    "San Fernando",
    "Santo Rosario",
    "Sapa Anding",
    "Sinaguing",
    "Switch",
    "Upper Laperian",
    "Wakat",
  ],
  "0907324000": [
    "Betinan",
    "Bulawan",
    "Calube",
    "Concepcion",
    "Dao-an",
    "Dumalian",
    "Fatima",
    "Langilan",
    "Lantawan",
    "Laperian",
    "Libuganan",
    "Limonan",
    "Mati",
    "Ocapan",
    "Poblacion",
    "San Isidro",
    "Sayog",
    "Tapian",
  ],
  "0907325000": [
    "Bag-ong Misamis",
    "Bubual",
    "Buton",
    "Culasian",
    "Daplayan",
    "Kalilangan",
    "Kapamanok",
    "Kondum",
    "Lumbayao",
    "Mabuhay",
    "Marcos Village",
    "Miasin",
    "Molansong",
    "Pantad",
    "Pao",
    "Payag",
    "Poblacion",
    "Pongapong",
    "Sacbulan",
    "Sagasan",
    "San Juan",
    "Senior",
    "Songgoy",
    "Tandubuay",
    "Taniapan",
    "Ticala Island",
    "Tubo-pait",
    "Villakapa",
  ],
  "0907327000": [
    "Abong-abong",
    "Baganian",
    "Baya-baya",
    "Capisan",
    "Concepcion",
    "Culabay",
    "Doña Josefina",
    "Lumbia",
    "Mabuhay",
    "Malim",
    "Manikaan",
    "New Oroquieta",
    "Poblacion",
    "San Francisco",
    "Tultolan",
  ],
  "0907328000": [
    "Alang-alang",
    "Angeles",
    "Bag-ong Kauswagan",
    "Bag-ong Tabogon",
    "Balugo",
    "Cabgan",
    "Calolot",
    "Dimalinao",
    "Fabian",
    "Gabunon",
    "Happy Valley (Pob.)",
    "Kapalaran",
    "Libato",
    "Limamawan",
    "Lower Liasan",
    "Lower Lodiong (Pob.)",
    "Lower Tiparak",
    "Lower Usogan",
    "Maya-maya",
    "New Village (Pob.)",
    "Pelocoban",
    "Riverside (Pob.)",
    "Sagrada Familia",
    "San Jose",
    "San Vicente",
    "Sumalig",
    "Tuluan",
    "Tungawan",
    "Upper Liason",
    "Upper Lodiong",
    "Upper Tiparak",
  ],
  "0907330000": [
    "Alindahaw",
    "Baclay",
    "Balimbingan",
    "Buenasuerte",
    "Camanga",
    "Curvada",
    "Laperian",
    "Libertad",
    "Lower Bayao",
    "Luy-a",
    "Manilan",
    "Manlayag",
    "Militar",
    "Navalan",
    "Panduma Senior",
    "Sambulawan",
    "San Antonio",
    "San Carlos (Pob.)",
    "Santo Niño (Pob.)",
    "Santo Rosario",
    "Sugod",
    "Tabuan",
    "Tagulo",
    "Tinotungan",
    "Upper Bayao",
  ],
  "0907333000": [
    "Bagong Kahayag",
    "Baking",
    "Biswangan",
    "Bululawan",
    "Dagum",
    "Gasa",
    "Gatub",
    "Lukuan",
    "Matalang",
    "Poblacion",
    "Sapang Pinoles",
    "Sebuguey",
    "Tiwales",
    "Tubod",
  ],
  "0907337000": [
    "Bogo Calabat",
    "Dawa",
    "Ebarle",
    "Gumahan (Pob.)",
    "Leonardo",
    "Litapan",
    "Lower Bagong Tudela",
    "Mansanas",
    "Moradji",
    "Nemeño",
    "Nopulan",
    "Sebukang",
    "Tagaytay Hill",
    "Upper Bagong Tudela (Pob.)",
  ],
  "0907338000": [
    "Balabawan",
    "Balong-balong",
    "Colojo",
    "Liasan",
    "Liguac",
    "Limbayan",
    "Lower Paniki-an",
    "Matin-ao",
    "Panubigan",
    "Poblacion",
    "Punta Flecha",
    "San Isidro",
    "Sugbay Dos",
    "Tongao",
    "Upper Paniki-an",
  ],
  "0907340000": [
    "Bag-ong Baroy",
    "Bag-ong Oroquieta",
    "Barubuhan",
    "Bulanay",
    "Datagan",
    "Eastern Poblacion",
    "Lantawan",
    "Libertad",
    "Lumangoy",
    "New Carmen",
    "Picturan",
    "Poblacion",
    "Rizal",
    "San Miguel",
    "Santo Niño",
    "Sawa",
    "Tungawan",
    "Upper Sicpao",
  ],
  "0907341000": [
    "Ambulon",
    "Bui-os",
    "Cogon",
    "Danan",
    "Kabatan",
    "Kapatagan",
    "Limason",
    "Linoguayan",
    "Lumbal",
    "Lunib",
    "Maculay",
    "Maraya",
    "Sagucan",
    "Waling-waling",
  ],
  "0907343000": [
    "Bagong Oroquieta",
    "Baguitan",
    "Balongating",
    "Canunan",
    "Dacsol",
    "Dagohoy",
    "Dalapang",
    "Datagan",
    "Guling",
    "Katipunan",
    "Lintum",
    "Litan",
    "Magting",
    "Poblacion",
    "Regla",
    "Sikatuna",
    "Singclot",
  ],
  "0907344000": [
    "Begong",
    "Busol",
    "Caluma",
    "Diana Countryside",
    "Guinlin",
    "Lacarayan",
    "Lacupayan",
    "Libayoy",
    "Limas",
    "Longmot",
    "Maragang",
    "Mate",
    "Nangan-nangan",
    "New Tuburan",
    "Nilo",
    "Tigbao",
    "Timolan",
    "Upper Nilo",
  ],
  "0908301000": [
    "Alegria",
    "Bagong Buhay",
    "Bella",
    "Calades",
    "Concepcion",
    "Dawa-dawa",
    "Gulayon",
    "Ilisan",
    "Kapatagan",
    "Kauswagan",
    "Kawayan",
    "La Paz",
    "Lambuyogan",
    "Lapirawan",
    "Litayon",
    "Lutiman",
    "Milagrosa",
    "Naga-naga",
    "Pandan-pandan",
    "Payongan",
    "Poblacion",
    "Santa Maria",
    "Santo Niño",
    "Talaptap",
    "Tampalan",
    "Tandiong Muslim",
    "Timbang-timbang",
  ],
  "0908302000": [
    "Agutayan",
    "Bagong Borbon",
    "Basalem",
    "Bawang",
    "Bliss",
    "Bulaan",
    "Compostela",
    "Danlugan",
    "Datu Panas",
    "Del Monte",
    "Guintuloan",
    "Guitom",
    "Guminta",
    "Labrador",
    "Lantawan",
    "Mabuhay",
    "Maganay",
    "Manlin",
    "Muyo",
    "Pamintayan",
    "Pling",
    "Poblacion",
    "Pulog",
    "San Jose",
    "Talairan",
    "Talamimi",
    "Villacastor",
  ],
  "0908303000": [
    "Balangao",
    "Butong",
    "Ditay",
    "Gaulan",
    "Goling",
    "Guinoman",
    "Kauswagan",
    "Lindang",
    "Lobing",
    "Luop",
    "Manangon",
    "Mejo",
    "Natan",
    "Paradise",
    "Pilar",
    "Poblacion",
    "Sampoli A",
    "Sampoli B",
    "Santa Cruz",
    "Songcuya",
    "Tinongtongan",
    "Tuno",
  ],
  "0908304000": [
    "Balugo",
    "Balungisan",
    "Baluyan",
    "Cana-an",
    "Dumpoc",
    "Gandiangan",
    "Israel",
    "La Victoria",
    "Little Baguio",
    "Lower Baluran",
    "Lumbog",
    "Lumpanac",
    "Mali Little Baguio",
    "Poblacion",
    "Pulawan",
    "San Jose",
    "Santa Barbara",
    "Upper Baluran",
  ],
  "0908305000": [
    "Bacalan",
    "Bangkerohan",
    "Bulu-an",
    "Caparan",
    "Domandan",
    "Don Andres",
    "Doña Josefa",
    "Guituan",
    "Ipil Heights",
    "Labi",
    "Logan",
    "Lower Ipil Heights",
    "Lower Taway",
    "Lumbia",
    "Maasin",
    "Magdaup",
    "Makilas",
    "Pangi",
    "Poblacion",
    "Sanito",
    "Suclema",
    "Taway",
    "Tenan",
    "Tiayon",
    "Timalang",
    "Tomitom",
    "Upper Pangi",
    "Veteran's Village",
  ],
  "0908306000": [
    "Banker",
    "Bolo Batallion",
    "Buayan",
    "Cainglet",
    "Calapan",
    "Calubihan",
    "Concepcion",
    "Diampak",
    "Dipala",
    "Gacbusan",
    "Goodyear",
    "Lacnapan",
    "Little Baguio",
    "Lumbayao",
    "Nazareth",
    "Palinta",
    "Peñaranda",
    "Poblacion",
    "Riverside",
    "Sanghanan",
    "Santa Cruz",
    "Sayao",
    "Shiolan",
    "Simbol",
    "Sininan",
    "Tamin",
    "Tampilisan",
    "Tigbangagan",
    "Timuay Danda",
  ],
  "0908307000": [
    "Abunda",
    "Bagong Silang",
    "Bangkaw-bangkaw",
    "Caliran",
    "Catipan",
    "Kauswagan",
    "Ligaya",
    "Looc-Barlak",
    "Malinao",
    "Pamansaan",
    "Pinalim",
    "Poblacion",
    "Punawan",
    "Santo Niño",
    "Sawa",
    "Sioton",
    "Taguisian",
    "Tandu-Comot",
  ],
  "0908308000": [
    "Bacao",
    "Basak-bawang",
    "Bontong",
    "Camanga",
    "Candiis",
    "Catituan",
    "Dansulao",
    "Del Pilar",
    "Guilawa",
    "Kigay",
    "La Dicha",
    "Lipacan",
    "Logpond",
    "Mabini",
    "Malungon",
    "Mulom",
    "Overland",
    "Palalian",
    "Payag",
    "Poblacion",
    "Rebocon",
    "San Vicente",
    "Sinusayan",
    "Tackling",
    "Tigabon",
  ],
  "0908309000": [
    "Aguinaldo",
    "Baga",
    "Baluno",
    "Bangkaw-bangkaw",
    "Cabong",
    "Crossing Sta. Clara",
    "Gubawang",
    "Guintoloan",
    "Kaliantana",
    "La Paz",
    "Lower Sulitan",
    "Mamagon",
    "Marsolo",
    "Poblacion",
    "San Isidro",
    "Sandayong",
    "Santa Clara",
    "Sulo",
    "Tambanan",
    "Taytay Manubo",
    "Tilubog",
    "Tipan",
    "Upper Sulitan",
  ],
  "0908310000": [
    "Bateria",
    "Calais",
    "Esperanza",
    "Fama",
    "Galas",
    "Gandaan",
    "Kahayagan",
    "Looc Sapi",
    "Matim",
    "Noque",
    "Pulo Laum",
    "Pulo Mabao",
    "San Isidro",
    "San Jose",
    "Santa Maria",
    "Solar (Pob.)",
    "Tambanan",
    "Villacorte",
    "Villagonzalo",
  ],
  "0908311000": [
    "Balian",
    "Balogo",
    "Balungisan",
    "Binangonan",
    "Bulacan",
    "Bulawan",
    "Calape",
    "Dalama",
    "Fatima",
    "Guintolan",
    "Guiwan",
    "Katipunan",
    "Kima",
    "Kulasian",
    "Kulisap",
    "La Fortuna",
    "Labatan",
    "Mayabo",
    "Minundas",
    "Mountain View",
    "Nanan",
    "Poblacion",
    "San Isidro",
    "San Roque",
    "San Vicente",
    "Silal",
    "Sumilong",
    "Talaptap",
    "Upper Sumilong",
  ],
  "0908312000": [
    "Ali Alsree",
    "Balansag",
    "Calula",
    "Casacon",
    "Don Perfecto",
    "Gango",
    "Katipunan",
    "Kulambugan",
    "Mabini",
    "Magsaysay",
    "Malubal",
    "New Antique",
    "New Sagay",
    "Palmera",
    "Pres. Roxas",
    "Remedios",
    "San Antonio",
    "San Fernandino",
    "San Jose",
    "Santo Rosario",
    "Siawang",
    "Silingan",
    "Surabay",
    "Taruc",
    "Tilasan",
    "Tupilac",
  ],
  "0908313000": [
    "Bagong Silang",
    "Balagon",
    "Balingasan",
    "Balucanan",
    "Bataan",
    "Batu",
    "Buyogan",
    "Camanga",
    "Coloran",
    "Kimos",
    "Labasan",
    "Lagting",
    "Laih",
    "Logpond",
    "Magsaysay",
    "Mahayahay",
    "Maligaya",
    "Maniha",
    "Minsulao",
    "Mirangan",
    "Monching",
    "Paruk",
    "Poblacion",
    "Princesa Sumama",
    "Salinding",
    "San Isidro",
    "Sibuguey",
    "Siloh",
    "Villagracia",
  ],
  "0908314000": [
    "Aurora",
    "Baganipay",
    "Bolingan",
    "Bualan",
    "Cawilan",
    "Florida",
    "Kasigpitan",
    "Laparay",
    "Mahayahay",
    "Moalboal",
    "Poblacion",
    "Sagay",
    "Samonte",
    "Tuburan",
  ],
  "0908315000": [
    "Achasol",
    "Azusano",
    "Bangco",
    "Camanga",
    "Culasian",
    "Dalangin",
    "Dalangin Muslim",
    "Dalisay",
    "Gomotoc",
    "Imelda",
    "Kipit",
    "Kitabog",
    "La Libertad",
    "Longilog",
    "Mabini",
    "Malagandis",
    "Mate",
    "Moalboal",
    "Namnama",
    "New Canaan",
    "Palomoc",
    "Poblacion",
    "Poblacion Muslim",
    "Pulidan",
    "San Antonio",
    "San Isidro",
    "Santa Fe",
    "Supit",
    "Tugop",
    "Tugop Muslim",
  ],
  "0908316000": [
    "Baluran",
    "Batungan",
    "Cayamcam",
    "Datu Tumanggong",
    "Gaycon",
    "Langon",
    "Libertad (Pob.)",
    "Linguisan",
    "Little Margos",
    "Loboc",
    "Looc-labuan",
    "Lower Tungawan",
    "Malungon",
    "Masao",
    "San Isidro",
    "San Pedro",
    "San Vicente",
    "Santo Niño",
    "Sisay",
    "Taglibas",
    "Tigbanuang",
    "Tigbucay",
    "Tigpalay",
    "Timbabauan",
    "Upper Tungawan",
  ],
  "0931700000": [
    "Arena Blanco",
    "Ayala",
    "Baliwasan",
    "Baluno",
    "Barangay Zone I (Pob.)",
    "Barangay Zone II (Pob.)",
    "Barangay Zone III (Pob.)",
    "Barangay Zone IV (Pob.)",
    "Boalan",
    "Bolong",
    "Buenavista",
    "Bunguiao",
    "Busay",
    "Cabaluay",
    "Cabatangan",
    "Cacao",
    "Calabasa",
    "Calarian",
    "Camino Nuevo",
    "Campo Islam",
    "Canelar",
    "Capisan",
    "Cawit",
    "Culianan",
    "Curuan",
    "Dita",
    "Divisoria",
    "Dulian",
    "Dulian",
    "Guisao",
    "Guiwan",
    "Kasanyangan",
    "La Paz",
    "Labuan",
    "Lamisahan",
    "Landang Gua",
    "Landang Laum",
    "Lanzones",
    "Lapakan",
    "Latuan",
    "Licomo",
    "Limaong",
    "Limpapa",
    "Lubigan",
    "Lumayang",
    "Lumbangan",
    "Lunzuran",
    "Maasin",
    "Malagutay",
    "Mampang",
    "Manalipa",
    "Mangusu",
    "Manicahan",
    "Mariki",
    "Mercedes",
    "Muti",
    "Pamucutan",
    "Pangapuyan",
    "Panubigan",
    "Pasilmanta",
    "Pasobolong",
    "Pasonanca",
    "Patalon",
    "Putik",
    "Quiniput",
    "Recodo",
    "Rio Hondo",
    "Salaan",
    "San Jose Cawa-cawa",
    "San Jose Gusu",
    "San Roque",
    "Sangali",
    "Santa Barbara",
    "Santa Catalina",
    "Santa Maria",
    "Santo Niño",
    "Sibulao",
    "Sinubung",
    "Sinunoc",
    "Tagasilay",
    "Taguiti",
    "Talabaan",
    "Talisayan",
    "Talon-talon",
    "Taluksangay",
    "Tetuan",
    "Tictapul",
    "Tigbalabag",
    "Tigtabon",
    "Tolosa",
    "Tugbungan",
    "Tulungatung",
    "Tumaga",
    "Tumalutab",
    "Tumitus",
    "Victoria",
    "Vitali",
    "Zambowood",
  ],
  "0990101000": [
    "Aguada",
    "Balatanay",
    "Baluno",
    "Begang",
    "Binuangan",
    "Busay",
    "Cabunbata",
    "Calvario",
    "Carbon",
    "Diki",
    "Dona Ramona T. Alano",
    "Isabela Eastside (Pob.)",
    "Isabela Proper (Pob.)",
    "Kapatagan Grande",
    "Kapayawan",
    "Kaumpurnah Zone I",
    "Kaumpurnah Zone II",
    "Kaumpurnah Zone III",
    "Kumalarang",
    "La Piedad (Pob.)",
    "Lampinigan",
    "Lanote",
    "Lukbuton",
    "Lumbang",
    "Makiri",
    "Maligue",
    "Marang-marang",
    "Marketsite (Pob.)",
    "Masula",
    "Menzi",
    "Panigayan",
    "Panunsulan",
    "Port Area (Pob.)",
    "Riverside",
    "San Rafael",
    "Santa Barbara",
    "Santa Cruz (Pob.)",
    "Seaside (Pob.)",
    "Small Kapatagan",
    "Sumagdang",
    "Sunrise Village (Pob.)",
    "Tabiawan",
    "Tabuk (Pob.)",
    "Tampalan",
    "Timpul",
  ],
};
