/** GENERATED — Region X: 2022 barangays across 93 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "1001301000": [
    "Balintad",
    "Buenavista",
    "Danatag",
    "Imbatug (Pob.)",
    "Kalilangan",
    "Lacolac",
    "Langaon",
    "Liboran",
    "Lingating",
    "Mabuhay",
    "Mabunga",
    "Nicdao",
    "Pualas",
    "Salimbalan",
    "San Miguel",
    "San Vicente",
  ],
  "1001302000": [
    "Aludas",
    "Angga-an",
    "Kinapat",
    "Kiraon",
    "Kitingting",
    "Lagandang",
    "Macapari",
    "Maican",
    "Migcawayan",
    "New Compostela",
    "Old Damulog",
    "Omonay",
    "Poblacion",
    "Pocopoco",
    "Sampagar",
    "San Isidro",
    "Tangkulan",
  ],
  "1001303000": [
    "Barongcot",
    "Bugwak",
    "Dolorosa",
    "Kapalaran",
    "Kianggat",
    "Lourdes",
    "Macarthur",
    "Miaray",
    "Migcuya",
    "New Visayas",
    "Osmeña",
    "Poblacion",
    "Sagbayan",
    "San Vicente",
  ],
  "1001304000": [
    "Bismartz",
    "Bocboc",
    "Buyot",
    "Cabadiangan",
    "Calaocalao",
    "Don Carlos Norte",
    "Don Carlos Sur (Pob.)",
    "Embayao",
    "Kalubihon",
    "Kasigkot",
    "Kawilihan",
    "Kiara",
    "Kibatang",
    "Mahayahay",
    "Manlamonay",
    "Maraymaray",
    "Mauswagon",
    "Minsalagan",
    "New Nongnongan",
    "New Visayas",
    "Old Nongnongan",
    "Pinamaloy",
    "Pualas",
    "San Antonio East",
    "San Antonio West",
    "San Francisco",
    "San Nicolas",
    "San Roque",
    "Sinangguyan",
  ],
  "1001305000": [
    "Bontongon",
    "Bulonay",
    "Capitan Bayong",
    "Cawayan",
    "Dumalaguing",
    "Guihean",
    "Hagpa",
    "Impalutao",
    "Kalabugao",
    "Kibenton",
    "La Fortuna",
    "Poblacion",
    "Sayawan",
  ],
  "1001306000": [
    "Bagongbayan",
    "Bagor",
    "Balaoro",
    "Baroy",
    "Cabadiangan",
    "Husayan",
    "Kibalagon",
    "Kibogtok",
    "Mabuhay",
    "Malinao",
    "Matampay",
    "Pay-as",
    "Pinamanguhan",
    "Poblacion",
    "Salvacion",
    "San Andres",
    "Sibonga",
  ],
  "1001307000": [
    "Baborawon",
    "Bangbang",
    "Canituan",
    "Kibaning",
    "Kinura",
    "Lampanusan",
    "Maca-opao",
    "Malinao",
    "Ninoy Aquino",
    "Pamotolon",
    "Poblacion",
    "Public",
    "San Vicente Ferrer",
    "West Poblacion",
  ],
  "1001308000": [
    "Balintawak",
    "Bukang Liwayway",
    "Cagawasan",
    "East Kibawe (Pob.)",
    "Gutapol",
    "Kiorao",
    "Kisawa",
    "Labuagon",
    "Magsaysay",
    "Marapangi",
    "Mascariñas",
    "Natulongan",
    "New Kidapawan",
    "Old Kibawe",
    "Palma",
    "Pinamula",
    "Romagooc",
    "Sampaguita",
    "Sanipon",
    "Spring",
    "Talahiron",
    "Tumaras",
    "West Kibawe (Pob.)",
  ],
  "1001309000": [
    "Balangigay",
    "Balukbukan",
    "Bershiba",
    "Binoongan",
    "Bobong",
    "Bolocaon",
    "Cabalantian",
    "Calapaton",
    "Digongan",
    "East Dalurong",
    "Kahusayan",
    "Kalumihan",
    "Kauyonan",
    "Kimolong",
    "Kipilas",
    "Kitaihon",
    "Kitobo",
    "Kiulom",
    "Magsaysay",
    "Malobalo",
    "Metebagao",
    "Napalico",
    "Pagan",
    "Panganan",
    "Poblacion",
    "Sagundanon",
    "San Isidro",
    "San Lorenzo",
    "Santo Rosario",
    "Sinaysayan",
    "Sinuda",
    "Tandong",
    "Tawas",
    "West Dalurong",
    "White Kulaman",
  ],
  "1001310000": [
    "Alanib",
    "Baclayon",
    "Balila",
    "Bantuanon",
    "Basak",
    "Bugcaon",
    "Capitan Juan",
    "Cawayan",
    "Ka-atoan",
    "Kibangay",
    "Kulasihan",
    "Poblacion",
    "Songco",
    "Victory",
  ],
  "1001311000": [
    "Capihan",
    "Crossing",
    "Gango",
    "Kiliog",
    "Kinawe",
    "Laturan",
    "Maambong",
    "Nangka",
    "Palabucan",
    "Poblacion",
    "Pongol",
    "San Jose",
    "Santa Fe",
    "Sil-ipon",
  ],
  "1001312000": [
    "Aglayan",
    "Apo Macote",
    "Bangcud",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Busdi",
    "Cabangahan",
    "Caburacanan",
    "Canayan",
    "Capitan Angel",
    "Casisang",
    "Dalwangan",
    "Imbayao",
    "Indalaza",
    "Kabalabag",
    "Kalasungay",
    "Kulaman",
    "Laguitas",
    "Linabo",
    "Magsaysay",
    "Maligaya",
    "Managok",
    "Manalog",
    "Mapayag",
    "Mapulo",
    "Miglamin",
    "Patpat",
    "Saint Peter",
    "San Jose",
    "San Martin",
    "Santo Niño",
    "Silae",
    "Simaya",
    "Sinanglanan",
    "Sumpong",
    "Violeta",
    "Zamboanguita",
  ],
  "1001313000": [
    "Kalingking",
    "Kiabo",
    "Mindagat",
    "Omagling",
    "Patpat",
    "Poblacion",
    "Sampiano",
    "San Luis",
    "Santa Ines",
    "Silo-o",
    "Sumalsag",
  ],
  "1001314000": [
    "Agusan Canyon",
    "Alae",
    "Dahilayan",
    "Dalirig",
    "Damilag",
    "Diclum",
    "Guilang-guilang",
    "Kalugmanan",
    "Lindaban",
    "Lingion",
    "Lunocan",
    "Maluko",
    "Mambatangan",
    "Mampayag",
    "Mantibugao",
    "Minsuro",
    "San Miguel",
    "Sankanan",
    "Santiago",
    "Santo Niño",
    "Tankulan (Pob.)",
    "Ticala",
  ],
  "1001315000": [
    "Anahawon",
    "Bagongsilang",
    "Base Camp",
    "Bayabason",
    "Camp I",
    "Colambugan",
    "Dagumba-an",
    "Danggawan",
    "Dologon",
    "Kiharong",
    "Kisanday",
    "Kuya",
    "La Roxas",
    "North Poblacion",
    "Panadtalan",
    "Panalsalan",
    "San Miguel",
    "San Roque",
    "South Poblacion",
    "Tubigon",
  ],
  "1001316000": [
    "Adtuyon",
    "Bacusanon",
    "Bangahan",
    "Barandias",
    "Concepcion",
    "Gandingan",
    "Kimanait",
    "Kipadukan",
    "Langcataon",
    "Lantay",
    "Madaya",
    "Malipayon",
    "Mendis",
    "Nabaliwa",
    "New Eden",
    "Payad",
    "Pigtauranan",
    "Poblacion",
    "Portulin",
  ],
  "1001317000": [
    "Butong",
    "C-Handumanan",
    "Cawayan",
    "Cebole",
    "Delapa",
    "Dumalama",
    "Kiburiao",
    "Kipaypayon",
    "Libertad",
    "Linabo",
    "Lipa",
    "Lumintao",
    "Magsaysay",
    "Mahayag",
    "Manuto",
    "Merangerang",
    "Mibantang",
    "Minongan",
    "Minsalirak",
    "Minsamongan",
    "Paitan",
    "Palacapao",
    "Pinilayan",
    "Poblacion",
    "Puntian",
    "Salawagan",
    "San Isidro",
    "San Jose",
    "San Roque",
    "Santa Cruz",
    "Santa Filomena",
  ],
  "1001318000": [
    "Bonacao",
    "Bulalang",
    "Cabuling",
    "Candelaria",
    "Cayaga",
    "Dao",
    "Durian",
    "Halapitan (Pob.)",
    "Iglugsad",
    "Kalagangan",
    "Kawayan",
    "Kibongcog",
    "Little Baguio",
    "Mabuhay",
    "Magkalungay",
    "Malayanan",
    "Matupe",
    "Nacabuklad",
    "Namnam",
    "Palacpacan",
    "Sacramento Valley",
    "San Jose",
    "Santo Domingo",
    "Tugop",
  ],
  "1001319000": [
    "Culasi",
    "Kisolon",
    "Licoan",
    "Lupiagan",
    "Ocasion",
    "Poblacion",
    "Puntian",
    "San Roque",
    "San Vicente",
    "Vista Villa",
  ],
  "1001320000": [
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Basak",
    "Baylanan",
    "Cacaon",
    "Colawingon",
    "Cosina",
    "Dagumbaan",
    "Dagundalahon",
    "Dominorog",
    "Indulang",
    "Lantud",
    "Lapok",
    "Liguron",
    "Lingi-on",
    "Lirongan",
    "Miarayon",
    "Sagaran",
    "Salucot",
    "San Antonio",
    "San Isidro",
    "San Miguel",
    "San Rafael",
    "Santo Niño",
    "Tagbak",
    "Tikalaan",
  ],
  "1001321000": [
    "Bagontaas",
    "Banlag",
    "Barobo",
    "Batangan",
    "Catumbalon",
    "Colonia",
    "Concepcion",
    "Dagat-Kidavao",
    "Guinoyuran",
    "Kahapunan",
    "Laligan",
    "Lilingayon",
    "Lourdes",
    "Lumbayao",
    "Lumbo",
    "Lurogan",
    "Maapag",
    "Mabuhay",
    "Mailag",
    "Mt. Nebo",
    "Nabago",
    "Pinatilan",
    "Poblacion",
    "San Carlos",
    "San Isidro",
    "Sinabuagan",
    "Sinayawan",
    "Sugod",
    "Tongantongan",
    "Tugaya",
    "Vintar",
  ],
  "1001322000": [
    "Anlogan",
    "Cabulohan",
    "Canangaan",
    "Capinonan",
    "Dalacutan",
    "Freedom",
    "Iba",
    "Imbatug",
    "Jasaan",
    "Lambangan",
    "Mandahikan",
    "Mandaing",
    "Mauswagon",
    "Paradise",
    "Poblacion",
  ],
  "1001801000": [
    "Alga",
    "Bonbon",
    "Bura",
    "Catibac",
    "Compol",
    "Lawigan",
    "Liloan",
    "Looc",
    "Mainit",
    "Manduao",
    "Panghiawan",
    "Poblacion",
    "Santo Niño",
    "Tangaro",
  ],
  "1001802000": [
    "Butay",
    "Cabuan",
    "Cantaan",
    "Liong",
    "Maac",
    "North Poblacion",
    "South Poblacion",
  ],
  "1001803000": [
    "Benoni",
    "Binatubo",
    "Catohugan",
    "Hubangon",
    "Owakan",
    "Poblacion",
    "Puntod",
    "San Isidro",
    "San Jose",
    "San Miguel",
    "San Roque",
    "Tubod",
    "Tupsan Pequeño",
  ],
  "1001804000": [
    "Agoho",
    "Anito",
    "Balbagon",
    "Baylao",
    "Benhaan",
    "Bug-ong",
    "Kuguita",
    "Magting",
    "Naasag",
    "Pandan",
    "Poblacion",
    "Soro-soro",
    "Tagdo",
    "Tupsan",
    "Yumbing",
  ],
  "1001805000": [
    "Alangilan",
    "Bacnit",
    "Balite",
    "Bonbon",
    "Bugang",
    "Cuna",
    "Manuyog",
    "Mayana",
    "Poblacion",
  ],
  "1003501000": [
    "Alegria",
    "Babalaya",
    "Babalayan Townsite",
    "Binuni",
    "Delabayan West",
    "Demologan",
    "Dimarao",
    "Esperanza",
    "Kahayag",
    "Liangan East",
    "Mati",
    "Minaulon",
    "Pagayawan",
    "Poblacion Bacolod",
    "Punod",
    "Rupagan",
  ],
  "1003502000": [
    "Abaga",
    "Adapun-Ali",
    "Angandog",
    "Angayen",
    "Bangko",
    "Batolacongan",
    "Buenavista",
    "Cadayonan",
    "Landa",
    "Lumbac",
    "Mamaanun",
    "Maria-Cristina",
    "Matampay",
    "Nangka",
    "Pacalundo",
    "Poblacion East",
    "Poblacion West",
    "Sandor",
    "Sangcad",
    "Sarip-Alawi",
    "Sigayan",
  ],
  "1003503000": [
    "Andil",
    "Bagong Dawis",
    "Baroy Daku",
    "Bato",
    "Cabasagan",
    "Dalama",
    "Libertad",
    "Limwag",
    "Lindongan",
    "Maliwanag",
    "Manan-ao",
    "Pange",
    "Pindolonan",
    "Poblacion",
    "Princesa",
    "Rawan Point",
    "Riverside",
    "Sagadan",
    "Sagadan Upper",
    "Salong",
    "San Juan",
    "Tinubdan",
    "Village",
  ],
  "1003505000": [
    "Bagong Badian",
    "Bagong Silang",
    "Balili",
    "Bansarvil",
    "Belis",
    "Buenavista",
    "Butadon",
    "Cathedral Falls",
    "Concepcion",
    "Curvada",
    "De Asis",
    "Donggoan",
    "Durano",
    "Kahayagan",
    "Kidalos",
    "La Libertad",
    "Lapinig",
    "Mahayahay",
    "Malinas",
    "Maranding",
    "Margos",
    "Poblacion",
    "Pulang Yuta",
    "San Isidro",
    "San Vicente",
    "Santa Cruz",
    "Santo Tomas",
    "Suso",
    "Taguitic",
    "Tiacongan",
    "Tipolo",
    "Tulatulahan",
    "Waterfalls",
  ],
  "1003506000": [
    "Bangaan",
    "Bangco",
    "Bansarvil II",
    "Bauyan",
    "Cabongbongan",
    "Calibao",
    "Calipapa",
    "Calube",
    "Campo Islam",
    "Capocao",
    "Dabliston",
    "Dalama",
    "Dangulaan",
    "Ditago",
    "Ilian",
    "Kauswagan",
    "Kirapan",
    "Koreo",
    "Lantawan",
    "Mabuhay",
    "Maguindanao",
    "Mahayahay",
    "Mamagum",
    "Mina",
    "Pandanan",
    "Payong",
    "Pikalawag",
    "Pikinit",
    "Piraka",
    "Poblacion",
    "Ramain",
    "Rebucon",
    "Sigayan",
    "Sugod",
    "Tagulo",
    "Tantaon",
    "Topocon",
  ],
  "1003507000": [
    "Bagumbayan (Pob.)",
    "Bara-ason",
    "Cayontor",
    "Delabayan",
    "Inudaran",
    "Kawit Occidental",
    "Kawit Oriental",
    "Libertad",
    "Paiton",
    "Poblacion",
    "Tacub",
    "Tingintingin",
    "Tugar",
  ],
  "1003508000": [
    "Austin Heights",
    "Baybay",
    "Bubong",
    "Caromatan",
    "Inudaran",
    "Kulasihan",
    "Libertad",
    "Lumbac",
    "Manga",
    "Matampay",
    "Mukas",
    "Muntay",
    "Pagalungan",
    "Palao",
    "Pantaon",
    "Pantar",
    "Poblacion",
    "Rebucon",
    "Riverside",
    "San Roque",
    "Santo Niño",
    "Simbuco",
    "Small Banisilan",
    "Sucodan",
    "Tabigue",
    "Titunod",
  ],
  "1003509000": [
    "Abaga",
    "Andil",
    "Cabasagan",
    "Camalan",
    "Darumawang Bucana",
    "Darumawang Ilaya",
    "El Salvador",
    "Gumagamot",
    "Lala Proper (Pob.)",
    "Lanipao",
    "Magpatao",
    "Maranding",
    "Matampay Bucana",
    "Matampay Ilaya",
    "Pacita",
    "Pendolonan",
    "Pinoyak",
    "Raw-an",
    "Rebe",
    "San Isidro Lower",
    "San Isidro Upper",
    "San Manuel",
    "Santa Cruz Lower",
    "Santa Cruz Upper",
    "Simpak",
    "Tenazas",
    "Tuna-an",
  ],
  "1003510000": [
    "Busque",
    "Larapan",
    "Magoong",
    "Napo",
    "Poblacion",
    "Purakan",
    "Robocon",
    "Samburon",
  ],
  "1003511000": [
    "Babasalon",
    "Baguiguicon",
    "Daan Campo",
    "Durianon",
    "Ilihan",
    "Lamigadato",
    "Lemoncret",
    "Lower Caningag",
    "Lubo",
    "Lumbac",
    "Malabaogan",
    "Mapantao",
    "Olango",
    "Pangao",
    "Pelingkingan",
    "Poblacion",
    "Rarab",
    "Somiorang",
    "Talambo",
    "Tambacon",
    "Tawinian",
    "Tipaan",
    "Tombador",
    "Upper Caningag",
  ],
  "1003512000": [
    "Balagatasa",
    "Camp 1",
    "Claro M. Recto",
    "Inoma",
    "Kulasihan",
    "Labuay",
    "Liangan West",
    "Mahayahay",
    "Maliwanag",
    "Mentring",
    "Poblacion",
    "Santa Cruz",
    "Segapod",
  ],
  "1003513000": [
    "Bangco",
    "Batal",
    "Batangan",
    "Bubong Radapan",
    "Cadayonan",
    "Matampay",
    "Pangi",
    "Pasayanon",
    "Poblacion",
    "Puntod",
    "Santa Cruz",
    "Somiorang",
  ],
  "1003514000": [
    "Bacayawan",
    "Balabacun",
    "Balintad",
    "Dalama",
    "Kadayonan",
    "Lindongan",
    "Lingco-an",
    "Lininding",
    "Lumba-Bayabao",
    "Madaya",
    "Maganding",
    "Matampay",
    "North Cadulawan",
    "Old Poblacion",
    "Panggao",
    "Pantao",
    "Pantao-A-Munai",
    "Pantaon",
    "Pindolonan",
    "Punong",
    "Ramain",
    "Sandigamunai",
    "Tagoranao",
    "Tambo",
    "Tamparan",
    "Taporog",
  ],
  "1003515000": [
    "Abaga",
    "Bangco",
    "Cabasaran",
    "Canibongan",
    "Dimayon",
    "Inayawan",
    "Kaludan",
    "Karcum",
    "Katubuan",
    "Liangan",
    "Lupitan",
    "Malaig",
    "Mangan",
    "Masibay",
    "Notongan",
    "Panganapan",
    "Pantar",
    "Paridi",
    "Petadun",
    "Poblacion",
    "Rarab",
    "Raraban",
    "Rebucon",
    "Songgod",
    "Taraka",
  ],
  "1003516000": [
    "Aloon",
    "Banday",
    "Bobonga Pantao Ragat",
    "Bobonga Radapan",
    "Cabasagan",
    "Calawe",
    "Culubun",
    "Dilimbayan",
    "Dimayon",
    "Lomidong",
    "Madaya",
    "Maliwanag",
    "Matampay",
    "Natangcopan",
    "Pansor",
    "Pantao Marug",
    "Poblacion East",
    "Poblacion West",
    "Tangcal",
    "Tongcopan",
  ],
  "1003517000": [
    "Alowin",
    "Bubong-Dinaig",
    "Cabasaran",
    "Cadayonan",
    "Caromatan",
    "Daramba",
    "Dinaig",
    "Kablangan",
    "Linindingan",
    "Lumbatan",
    "Lupitan",
    "Madamba",
    "Madaya",
    "Maliwanag",
    "Nunang",
    "Nunungan",
    "Pantao Raya",
    "Pantaon",
    "Pendolonan",
    "Pened",
    "Piangamangaan",
    "Poblacion",
    "Sulo",
    "Tagoranao",
    "Tangclao",
    "Timbangalan",
  ],
  "1003518000": [
    "Barandia",
    "Bulacon",
    "Buntong",
    "Calimodan",
    "Camp III",
    "Curva-Miagao",
    "Daligdigan",
    "Inasagan",
    "Kilala",
    "Mabatao",
    "Madaya",
    "Mamaanon",
    "Mapantao",
    "Mindalano",
    "Padianan",
    "Pagalongan",
    "Pagayawan",
    "Panaliwad-on",
    "Pangantapan",
    "Pansor",
    "Patidon",
    "Pawak",
    "Poblacion",
    "Saumay",
    "Sudlon",
  ],
  "1003519000": [
    "Baning",
    "Buriasan (Pob.)",
    "Dansalan",
    "Gamal",
    "Inudaran I",
    "Inudaran II",
    "Karkum",
    "Katipunan",
    "Mabugnao",
    "Maito Salug",
    "Mala Salug",
    "Mama-anon",
    "Mapurog",
    "Pancilan",
    "Panoloon",
    "Pili",
    "Sapad",
  ],
  "1003520000": [
    "Dalamas",
    "Darimbang",
    "Dimayon",
    "Inagongan",
    "Kiazar (Pob.)",
    "Malimbato",
    "Panalawan",
  ],
  "1003521000": [
    "Bayabao",
    "Berwar",
    "Big Banisilon",
    "Big Meladoc",
    "Bubong",
    "Lamaosa",
    "Linao",
    "Lindongan",
    "Lingco-an",
    "Papan",
    "Pelingkingan",
    "Poblacion",
    "Poona Kapatagan",
    "Punod",
    "Small Banisilon",
    "Small Meladoc",
    "Somiorang",
    "Tangcal Proper",
  ],
  "1003522000": [
    "Barakanas",
    "Baris",
    "Bualan",
    "Bulod",
    "Camp V",
    "Candis",
    "Caniogan",
    "Dalama",
    "Kakai Renabor",
    "Kalilangan",
    "Licapao",
    "Malingao",
    "Palao",
    "Patudan",
    "Pigcarangan",
    "Pinpin",
    "Poblacion",
    "Pualas",
    "San Antonio",
    "Santo Niño",
    "Taden",
    "Taguranao",
    "Tangueguiron",
    "Tubaran",
  ],
  "1003523000": [
    "Bangcal",
    "Bowi",
    "Bubong Madaya",
    "Cabasaran",
    "Cadayonan",
    "Campong",
    "Dibarosan",
    "Kalanganan East",
    "Kalanganan Lower",
    "Kalilangan",
    "Lumba-Punod",
    "Pantao-Marug",
    "Pantao-Ranao",
    "Pantar East",
    "Pitubo",
    "Poblacion",
    "Poona-Punod",
    "Punod",
    "Sundiga-Punod",
    "Tawanan",
    "West Pantar",
  ],
  "1004201000": [
    "Balintonga",
    "Banisilon",
    "Burgos",
    "Calube",
    "Caputol",
    "Casusan",
    "Conat",
    "Culpan",
    "Dalisay",
    "Dullan",
    "Ibabao",
    "Labo",
    "Lawa-an",
    "Lobogon",
    "Lumbayao",
    "Macubon",
    "Makawa",
    "Manamong",
    "Matipaz",
    "Maular",
    "Mitazan",
    "Mohon",
    "Monterico",
    "Nabuna",
    "Ospital (Pob.)",
    "Palayan",
    "Pelong",
    "Roxas",
    "San Pedro",
    "Santa Ana",
    "Sinampongan",
    "Taguanao",
    "Tawi-tawi",
    "Toril",
    "Tubod",
    "Tuburan",
    "Tugaya",
    "Zamora",
  ],
  "1004202000": [
    "Del Pilar",
    "Landing",
    "Lumipac",
    "Lusot",
    "Mabini",
    "Magsaysay",
    "Misom",
    "Mitacas",
    "Naburos",
    "Northern Poblacion",
    "Punta Miray",
    "Punta Sulong",
    "Sinian",
    "Southern Poblacion",
    "Tugas",
  ],
  "1004203000": [
    "Bag-ong Anonang",
    "Bagumbang",
    "Baybay",
    "Bolinsong",
    "Buenavista",
    "Buracan",
    "Calolot",
    "Demetrio Fernan",
    "Digson",
    "Dimalco",
    "Dullan",
    "Kanaokanao",
    "Liloan",
    "Linconan",
    "Lodiong",
    "Lower Usugan",
    "Mapurog",
    "Migpange",
    "Montol",
    "Pisa-an",
    "Poblacion",
    "Remedios",
    "Rufino Lumapas",
    "Sibuyon",
    "Tangab",
    "Tiaman",
    "Tusik",
    "Upper Usogan",
  ],
  "1004204000": [
    "Bonifacio",
    "Bunawan",
    "Calaran",
    "Dapacan Alto",
    "Dapacan Bajo",
    "Don Bernardo Nery Pob.",
    "Langub",
    "Libertad",
    "Magcamiguing",
    "Mamalad",
    "Mauswagon",
    "Northern Poblacion",
    "Salvador",
    "San Isidro",
    "Siloy",
    "Singalat",
    "Solinog",
    "Southwestern Poblacion",
    "Sulipat",
  ],
  "1004205000": [
    "Bernad",
    "Bito-on",
    "Cabunga-an",
    "Canibungan Daku",
    "Canibungan Putol",
    "Canipacan",
    "Dalingap",
    "Dela Paz",
    "Dolores",
    "Gata Daku",
    "Gata Diot",
    "Guba",
    "Kinangay Norte",
    "Kinangay Sur",
    "Lapasan",
    "Lupagan",
    "Malibangcao",
    "Masabud",
    "Mialen",
    "Pan-ay",
    "Penacio",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Sebasi",
    "Segatic Daku",
    "Segatic Diot",
    "Tinacla-an",
  ],
  "1004206000": [
    "Bagong Nayon",
    "Capule",
    "Guiban",
    "Laya-an",
    "Lingatongan",
    "Maligubaan",
    "Mantukoy",
    "Marugang",
    "New Casul",
    "Poblacion",
    "Pogan",
    "Small Potongan",
    "Soso-on",
    "Upper Dapitan",
    "Upper Dioyo",
    "Upper Potongan",
    "Upper Salimpono",
    "Virayan",
  ],
  "1004207000": [
    "Adorable",
    "Butuay",
    "Carmen",
    "Corrales",
    "Dicoloc",
    "Gata",
    "Guintomoyan",
    "Macabayao",
    "Malibacsan",
    "Matugas Alto",
    "Matugas Bajo",
    "Mialem",
    "Nacional (Pob.)",
    "Naga (Pob.)",
    "Palilan",
    "Rizal (Pob.)",
    "San Isidro",
    "Santa Cruz (Pob.)",
    "Seti",
    "Sibaroc",
    "Sinara Alto",
    "Sinara Bajo",
    "Tabo-o",
    "Taraka (Pob.)",
  ],
  "1004208000": [
    "Alegria",
    "Bagong Silang",
    "Biasong",
    "Bonifacio",
    "Burgos",
    "Dalacon",
    "Dampalan",
    "Don Andres Soriano",
    "Eastern Poblacion",
    "Estante",
    "Jasa-an",
    "Katipa",
    "Luzaran",
    "Mabas",
    "Macalibre Alto",
    "Macalibre Bajo",
    "Mahayahay",
    "Manguehan",
    "Mansabay Alto",
    "Mansabay Bajo",
    "Molatuhan Alto",
    "Molatuhan Bajo",
    "Peniel",
    "Puntod",
    "Rizal",
    "Sibugon",
    "Sibula",
    "Western Poblacion",
  ],
  "1004209000": [
    "Apil",
    "Binuangan",
    "Bolibol",
    "Buenavista",
    "Bunga",
    "Buntawan",
    "Burgos",
    "Canubay",
    "Ciriaco C. Pastrano",
    "Clarin Settlement",
    "Dolipos Alto",
    "Dolipos Bajo",
    "Dulapo",
    "Dullan Norte",
    "Dullan Sur",
    "Lamac Lower",
    "Lamac Upper",
    "Langcangan Lower",
    "Langcangan Proper",
    "Langcangan Upper",
    "Layawan",
    "Loboc Lower",
    "Loboc Upper",
    "Malindang",
    "Mialen",
    "Mobod",
    "Paypayan",
    "Pines",
    "Poblacion I",
    "Poblacion II",
    "Rizal Lower",
    "Rizal Upper",
    "San Vicente Alto",
    "San Vicente Bajo",
    "Sebucal",
    "Senote",
    "Taboc Norte",
    "Taboc Sur",
    "Talairon",
    "Talic",
    "Tipan",
    "Toliyok",
    "Tuyabang Alto",
    "Tuyabang Bajo",
    "Tuyabang Proper",
    "Victoria",
    "Villaflor",
  ],
  "1004210000": [
    "50th District (Pob.)",
    "Aguada (Pob.)",
    "Bacolod",
    "Bagakay",
    "Balintawak",
    "Banadero (Pob.)",
    "Baybay San Roque",
    "Baybay Santa Cruz",
    "Baybay Triunfo",
    "Bongbong",
    "Calabayan",
    "Capucao C.",
    "Capucao P.",
    "Carangan",
    "Carmen",
    "Catadman-Manabay",
    "Cavinte",
    "Cogon",
    "Dalapang",
    "Diguan",
    "Dimaluna",
    "Doña Consuelo",
    "Embargo",
    "Gala",
    "Gango",
    "Gotokan Daku",
    "Gotokan Diot",
    "Guimad",
    "Guingona",
    "Kinuman Norte",
    "Kinuman Sur",
    "Labinay",
    "Labo",
    "Lam-an",
    "Liposong",
    "Litapan",
    "Malaubang",
    "Manaka",
    "Maningcol",
    "Mentering",
    "Molicay",
    "Pantaon",
    "Pulot",
    "San Antonio",
    "Sangay Daku",
    "Sangay Diot",
    "Sinuza",
    "Stimson Abordo",
    "Tabid",
    "Tinago",
    "Trigos",
  ],
  "1004211000": [
    "Baga",
    "Bangko",
    "Camanucan",
    "Dela Paz",
    "Lutao",
    "Magsaysay",
    "Map-an",
    "Mohon",
    "Poblacion",
    "Punta",
    "Salimpuno",
    "San Andres",
    "San Juan",
    "San Roque",
    "Sumasap",
    "Villalin",
  ],
  "1004212000": [
    "Agunod",
    "Bato",
    "Buena Voluntad",
    "Calaca-an",
    "Cartagena Proper",
    "Catarman",
    "Cebulin",
    "Clarin",
    "Danao",
    "Deboloc",
    "Divisoria",
    "Eastern Looc",
    "Ilisan",
    "Katipunan",
    "Kauswagan",
    "Lao Proper",
    "Lao Santa Cruz",
    "Looc Proper",
    "Mamanga Daku",
    "Mamanga Gamay",
    "Mangidkid",
    "New Cartagena",
    "New Look",
    "Northern Poblacion",
    "Panalsalan",
    "Puntod",
    "Quirino",
    "Santa Cruz",
    "Southern Looc",
    "Southern Poblacion",
    "Tipolo",
    "Unidos",
    "Usocan",
  ],
  "1004213000": [
    "Agapito Yap, Sr.",
    "Bautista",
    "Bitibut",
    "Boundary",
    "Caluya",
    "Capundag",
    "Casul",
    "Dalumpinas",
    "Dasa",
    "Dioyo",
    "Disoy",
    "El Paraiso",
    "Guinabot",
    "Libertad",
    "Locus",
    "Macabibo",
    "Manla",
    "Masubong",
    "Medallo",
    "Poblacion",
    "Salimpuno",
    "San Agustin",
    "Sapang Ama",
    "Sinaad",
    "Sipac",
    "Sixto Velez, Sr.",
    "Upper Bautista",
    "Ventura",
  ],
  "1004214000": [
    "Cagay-anon",
    "Camanse",
    "Colupan Alto",
    "Colupan Bajo",
    "Dinas",
    "Estrella",
    "Katipunan",
    "Libertad Alto",
    "Libertad Bajo",
    "Poblacion",
    "San Isidro Alto",
    "San Isidro Bajo",
    "San Lorenzo Ruiz",
    "San Vicente",
    "Señor",
    "Sinonoc",
    "Tipan",
  ],
  "1004215000": [
    "Aquino",
    "Balatacan",
    "Baluk",
    "Banglay",
    "Barangay I - City Hall (Pob.)",
    "Barangay II - Marilou Annex (Pob.)",
    "Barangay III- Market Kalubian (Pob.)",
    "Barangay IV - St. Michael (Pob.)",
    "Barangay V - Malubog (Pob.)",
    "Barangay VI - Lower Polao (Pob.)",
    "Barangay VII - Upper Polao (Pob.)",
    "Bintana",
    "Bocator",
    "Bongabong",
    "Caniangan",
    "Capalaran",
    "Catagan",
    "Garang",
    "Guinabot",
    "Guinalaban",
    "Huyohoy",
    "Isidro D. Tan",
    "Kauswagan",
    "Kimat",
    "Labuyo",
    "Lorenzo Tan",
    "Lumban",
    "Maloro",
    "Manga",
    "Mantic",
    "Maquilao",
    "Matugnaw",
    "Migcanaway",
    "Minsubong",
    "Owayan",
    "Paiton",
    "Panalsalan",
    "Pangabuan",
    "Prenza",
    "Salimpuno",
    "San Antonio",
    "San Apolinario",
    "San Vicente",
    "Santa Cruz",
    "Santa Maria",
    "Santo Niño",
    "Sicot",
    "Silanga",
    "Silangit",
    "Simasay",
    "Sumirap",
    "Taguite",
    "Tituron",
    "Tugas",
    "Villaba",
  ],
  "1004216000": [
    "Balon",
    "Barra",
    "Basirang",
    "Bongabong",
    "Buenavista",
    "Cabol-anonan",
    "Cahayag",
    "Calambutan Bajo",
    "Calambutan Settlement",
    "Camating",
    "Canibungan Proper",
    "Casilak San Agustin",
    "Centro Hulpa (Pob.)",
    "Centro Napu (Pob.)",
    "Centro Upper (Pob.)",
    "Duanguican",
    "Gala",
    "Gumbil",
    "Locso-on",
    "Maikay",
    "Maribojoc",
    "Mitugas",
    "Nailon",
    "Namut",
    "Napurog",
    "Pan-ay Diot",
    "San Nicolas",
    "Sebac",
    "Silongon",
    "Sinuza",
    "Taguima",
    "Tigdok",
    "Yahong",
  ],
  "1004217000": [
    "Bagong Clarin",
    "Gandawan",
    "Lake Duminagat",
    "Lalud",
    "Lampasan",
    "Liboron",
    "Maramara",
    "Napangan",
    "Nueva Vista",
    "Petianan",
    "Tuno",
  ],
  "1004301000": [
    "Baybay",
    "Benigwayan",
    "Calatcat",
    "Lagtang",
    "Lanao",
    "Loguilo",
    "Lourdes",
    "Lumbo",
    "Molocboloc",
    "Poblacion",
    "Sampatulog",
    "Sungay",
    "Talaba",
    "Taparak",
    "Tugasnon",
    "Tula",
  ],
  "1004302000": [
    "Balagnan",
    "Baliwagan",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Binitinan",
    "Blanco",
    "Calawag",
    "Camuayan",
    "Cogon",
    "Dansuli",
    "Dumarait",
    "Hermano",
    "Kibanban",
    "Linabu",
    "Linggangao",
    "Mambayaan",
    "Mandangoa",
    "Napaliran",
    "Quezon",
    "Rosario",
    "Samay",
    "San Francisco",
    "San Isidro",
    "San Juan",
    "Talusan",
    "Waterfall",
  ],
  "1004303000": [
    "Baukbauk Pob.",
    "Dahilig",
    "Kabangasan",
    "Kabulakan",
    "Kauswagan",
    "Lapinig (Pob.)",
    "Mantangale",
    "Mapua",
    "San Alonzo",
  ],
  "1004304000": [
    "Dampias",
    "Kitamban",
    "Kitambis",
    "Mabini",
    "Mosangot",
    "Nabataan",
    "Poblacion",
    "Valdeconcha",
  ],
  "1004306000": [
    "Ani-e",
    "Aposkahoy",
    "Bulahan",
    "Cabacungan",
    "Gumaod",
    "Hinaplanan",
    "Kalawitan",
    "Lanise",
    "Luna",
    "Madaguing",
    "Malagana",
    "Mat-i",
    "Minalwang",
    "Pambugas",
    "Panampawan",
    "Patrocenio",
    "Pelaez",
    "Plaridel",
    "Poblacion",
    "Punong",
    "Rizal",
    "Santa Cruz",
    "Tamboboan",
    "Tipolohon",
  ],
  "1004307000": [
    "Amoros",
    "Bolisong",
    "Bolobolo",
    "Calongonan",
    "Cogon",
    "Himaya",
    "Hinigdaan",
    "Kalabaylabay",
    "Kibonbon",
    "Molugan",
    "Poblacion",
    "Sambulawan",
    "Sinaloc",
    "Taytay",
    "Ulaliman",
  ],
  "1004308000": [
    "Agay-ayan",
    "Alagatan",
    "Anakan",
    "Bagubad",
    "Bakidbakid",
    "Bal-ason",
    "Bantaawan",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 12 (Pob.)",
    "Barangay 13 (Pob.)",
    "Barangay 14 (Pob.)",
    "Barangay 15 (Pob.)",
    "Barangay 16 (Pob.)",
    "Barangay 17 (Pob.)",
    "Barangay 18 (Pob.)",
    "Barangay 18-A (Pob.)",
    "Barangay 19 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 20 (Pob.)",
    "Barangay 21 (Pob.)",
    "Barangay 22 (Pob.)",
    "Barangay 22-A (Pob.)",
    "Barangay 23 (Pob.)",
    "Barangay 24 (Pob.)",
    "Barangay 24-A (Pob.)",
    "Barangay 25 (Pob.)",
    "Barangay 26 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Binakalan",
    "Capitulangan",
    "Daan-Lungsod",
    "Dinawehan",
    "Eureka",
    "Hindangon",
    "Kalagonoy",
    "Kalipay",
    "Kamanikan",
    "Kianlagan",
    "Kibuging",
    "Kipuntos",
    "Lawaan",
    "Lawit",
    "Libertad",
    "Libon",
    "Lunao",
    "Lunotan",
    "Malibud",
    "Malinao",
    "Maribucao",
    "Mimbalagon",
    "Mimbunga",
    "Mimbuntong",
    "Minsapinit",
    "Murallon",
    "Odiongan",
    "Pangasihan",
    "Pigsaluhan",
    "Punong",
    "Ricoro",
    "Samay",
    "San Jose",
    "San Juan",
    "San Luis",
    "San Miguel",
    "Sangalan",
    "Santiago",
    "Tagpako",
    "Talisay",
    "Talon",
    "Tinabalan",
    "Tinulongan",
  ],
  "1004309000": [
    "Burnay",
    "Carlos P. Garcia",
    "Cogon",
    "Gregorio Pelaez",
    "Kilangit",
    "Matangad",
    "Pangayawan",
    "Poblacion",
    "Quezon",
    "Tala-o",
    "Ulab",
  ],
  "1004310000": [
    "Aluna",
    "Andales",
    "Apas",
    "Calacapan",
    "Gimangpang",
    "Jampason",
    "Kamelon",
    "Kanitoan",
    "Oguis",
    "Pagahan",
    "Poblacion",
    "Pontacon",
    "San Pedro",
    "Sinalac",
    "Tawantawan",
    "Tubigan",
  ],
  "1004311000": [
    "Aplaya",
    "Bobontugan",
    "Corrales",
    "Danao",
    "I. S. Cruz",
    "Jampason",
    "Kimaya",
    "Lower Jasaan (Pob.)",
    "Luz Banzon",
    "Natubo",
    "San Antonio",
    "San Isidro",
    "San Nicolas",
    "Solana",
    "Upper Jasaan (Pob.)",
  ],
  "1004312000": [
    "Beray",
    "Bolisong",
    "Buko",
    "Calubo",
    "Campo",
    "Esperanza",
    "Kagumahan",
    "Kalitian",
    "Kitotok",
    "Panabol",
    "Poblacion",
    "Salicapawan",
    "Salubsob",
    "Suarez",
    "Sumalag",
  ],
  "1004313000": [
    "Banglay",
    "Dampil",
    "Gaston",
    "Kabulawan",
    "Kauswagan",
    "Lumbo",
    "Manaol",
    "Poblacion",
    "Tabok",
    "Umagos",
  ],
  "1004314000": [
    "Aromahon",
    "Gasi",
    "Kibaghot",
    "Lapad",
    "Liberty",
    "Mauswagon",
    "Moog",
    "Poblacion",
    "Sambulawan",
    "Sinai",
    "Tubajon",
  ],
  "1004315000": [
    "Dulong",
    "Gimaylan",
    "Kimalok",
    "Lubluban",
    "Poblacion",
    "Retablo",
    "Santo Niño",
    "Tangcub",
    "Taytayan",
  ],
  "1004316000": [
    "Aya-aya",
    "Betahon",
    "Biga",
    "Calangahan",
    "Kaluknayan",
    "Lower Talacogon",
    "Poblacion",
    "Upper Talacogon",
  ],
  "1004317000": [
    "Abunda",
    "Artadi",
    "Bonifacio Aquino",
    "Cabalawan",
    "Cabantian",
    "Cabubuhan",
    "Candiis",
    "Consuelo",
    "Damayuhan",
    "Gumabon",
    "Katipunan",
    "Kauswagan",
    "Kibungsod",
    "Mahayahay",
    "Mindulao",
    "Pag-asa",
    "Poblacion",
    "San Isidro",
    "San Vicente",
    "Santa Cruz",
    "Tama",
    "Tibon-tibon",
    "Tinaan",
    "Tulang",
    "Villa Felipa",
  ],
  "1004318000": [
    "Argayoso",
    "Balintad",
    "Cabalantian",
    "Camanga",
    "Digkilaan",
    "Mahayahay",
    "Pagawan",
    "Paniangan",
    "Patag",
    "Poblacion",
    "Punta Silum",
    "Tuod",
    "Upper Malubog",
  ],
  "1004319000": [
    "Bangbang",
    "Bulwa",
    "Cabug",
    "Dig-aguyan",
    "Duka",
    "Gasa",
    "Maanas",
    "Mananum Bag-o",
    "Mananum Daan",
    "North Poblacion",
    "Pahindong",
    "Portulin",
    "San Isidro",
    "San Jose",
    "San Roque",
    "San Vicente",
    "South Poblacion",
    "Tambagan",
    "Tup-on",
  ],
  "1004320000": [
    "Don Pedro",
    "Linangkayan",
    "Lubilan",
    "Mapulog",
    "Maputi",
    "Mat-i",
    "Patag",
    "Poblacion",
    "Tagbalogo",
    "Tuboran",
  ],
  "1004321000": [
    "Awang",
    "Bagocboc",
    "Barra",
    "Bonbon",
    "Cauyonan",
    "Igpit",
    "Limonda",
    "Luyongbonbon",
    "Malanang",
    "Nangcaon",
    "Patag",
    "Poblacion",
    "Taboc",
    "Tingalan",
  ],
  "1004322000": [
    "Alipuaton",
    "Ampenican",
    "Bunal",
    "Casulog",
    "Dinagsaan",
    "Guinalaban",
    "Ili-ilihon",
    "Inobulan",
    "Looc",
    "Matampa",
    "Membuli",
    "Poblacion",
    "Salagsag",
    "Salay River I",
    "Salay River II",
    "Saray",
    "Tinagaan",
    "Yungod",
  ],
  "1004323000": [
    "Alicomohan",
    "Ampianga",
    "Kaulayanan",
    "Kidampas",
    "Kiraging",
    "Mangga",
    "Mimbuahan",
    "Poblacion",
    "Santa Cruz",
    "Silad",
  ],
  "1004324000": [
    "Baluarte",
    "Casinglot",
    "Gracia",
    "Mohon",
    "Natumolan",
    "Poblacion",
    "Rosario",
    "Santa Ana",
    "Santa Cruz",
    "Sugbongcogon",
  ],
  "1004325000": [
    "Bugdang",
    "Calamcam",
    "Casibole",
    "Macopa",
    "Magkarila",
    "Mahayag",
    "Mandahilag",
    "Mintabon",
    "Pangpangon",
    "Poblacion",
    "Pook",
    "Punta Santiago",
    "Puting Balas",
    "San Jose",
    "Santa Ines",
    "Sibantang",
    "Sindangan",
    "Tagbocboc",
  ],
  "1004326000": [
    "Balacanas",
    "Dayawan",
    "Imelda",
    "Katipunan",
    "Kimaya",
    "Looc",
    "Poblacion 1",
    "Poblacion 2",
    "Poblacion 3",
    "San Martin",
    "Tambobong",
  ],
  "1030500000": [
    "Agusan",
    "Baikingon",
    "Balubal",
    "Balulang",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 12 (Pob.)",
    "Barangay 13 (Pob.)",
    "Barangay 14 (Pob.)",
    "Barangay 15 (Pob.)",
    "Barangay 16 (Pob.)",
    "Barangay 17 (Pob.)",
    "Barangay 18 (Pob.)",
    "Barangay 19 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 20 (Pob.)",
    "Barangay 21 (Pob.)",
    "Barangay 22 (Pob.)",
    "Barangay 23 (Pob.)",
    "Barangay 24 (Pob.)",
    "Barangay 25 (Pob.)",
    "Barangay 26 (Pob.)",
    "Barangay 27 (Pob.)",
    "Barangay 28 (Pob.)",
    "Barangay 29 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 30 (Pob.)",
    "Barangay 31 (Pob.)",
    "Barangay 32 (Pob.)",
    "Barangay 33 (Pob.)",
    "Barangay 34 (Pob.)",
    "Barangay 35 (Pob.)",
    "Barangay 36 (Pob.)",
    "Barangay 37 (Pob.)",
    "Barangay 38 (Pob.)",
    "Barangay 39 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 40 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Bayabas",
    "Bayanga",
    "Besigan",
    "Bonbon",
    "Bugo",
    "Bulua",
    "Camaman-an",
    "Canito-an",
    "Carmen",
    "Consolacion",
    "Cugman",
    "Dansolihon",
    "F. S. Catanico",
    "Gusa",
    "Indahag",
    "Iponan",
    "Kauswagan",
    "Lapasan",
    "Lumbia",
    "Macabalan",
    "Macasandig",
    "Mambuaya",
    "Nazareth",
    "Pagalungan",
    "Pagatpat",
    "Patag",
    "Pigsag-an",
    "Puerto",
    "Puntod",
    "San Simon",
    "Tablon",
    "Taglimao",
    "Tagpangi",
    "Tignapoloan",
    "Tuburan",
    "Tumpagon",
  ],
  "1030900000": [
    "Abuno",
    "Acmac",
    "Bagong Silang",
    "Bonbonon",
    "Bunawan",
    "Buru-un",
    "Dalipuga",
    "Del Carmen",
    "Digkilaan",
    "Ditucalan",
    "Dulag",
    "Hinaplanon",
    "Hindang",
    "Kabacsanan",
    "Kalilangan",
    "Kiwalan",
    "Lanipao",
    "Luinab",
    "Mahayahay",
    "Mainit",
    "Mandulog",
    "Maria Cristina",
    "Palao",
    "Panoroganan",
    "Poblacion",
    "Puga-an",
    "Rogongon",
    "San Miguel",
    "San Roque",
    "Santa Elena",
    "Santa Filomena",
    "Santiago",
    "Santo Rosario",
    "Saray",
    "Suarez",
    "Tambacan",
    "Tibanga",
    "Tipanoy",
    "Tomas L. Cabili",
    "Tubod",
    "Ubaldo Laya",
    "Upper Hinaplanon",
    "Upper Tominobo",
    "Villa Verde",
  ],
};
