/** GENERATED — Region XI: 1162 barangays across 49 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "1102301000": [
    "Binancian",
    "Buan",
    "Buclad",
    "Cabaywa",
    "Camansa",
    "Cambanogoy (Pob.)",
    "Camoning",
    "Canatan",
    "Concepcion",
    "Doña Andrea",
    "Magatos",
    "Napungas",
    "New Bantayan",
    "New Loon",
    "New Santiago",
    "Pamacaun",
    "Sagayen",
    "San Vicente",
    "Santa Filomena",
    "Sonlon",
  ],
  "1102303000": [
    "Alejal",
    "Anibongan",
    "Asuncion",
    "Cebulano",
    "Guadalupe",
    "Ising (Pob.)",
    "La Paz",
    "Mabaus",
    "Mabuhay",
    "Magsaysay",
    "Mangalcal",
    "Minda",
    "New Camiling",
    "Salvacion",
    "San Isidro",
    "Santo Niño",
    "Taba",
    "Tibulao",
    "Tubod",
    "Tuganay",
  ],
  "1102305000": [
    "Capungagan",
    "Florida",
    "Gabuyan",
    "Gupitan",
    "Katipunan",
    "Luna",
    "Mabantao",
    "Mamacao",
    "Maniki",
    "Pag-asa",
    "Sampao",
    "Semong",
    "Sua-on",
    "Tiburcia",
  ],
  "1102314000": [
    "Cabidianan",
    "Carcor",
    "Del Monte",
    "Del Pilar",
    "El Salvador",
    "Limba-an",
    "Macgum",
    "Mambing",
    "Mesaoy",
    "New Bohol",
    "New Cortez",
    "New Sambog",
    "Patrocenio",
    "Poblacion",
    "San Jose",
    "San Roque",
    "Santa Cruz",
    "Santa Fe",
    "Santo Niño",
    "Suawon",
  ],
  "1102315000": [
    "A. O. Floirendo",
    "Buenavista",
    "Cacao",
    "Cagangohan",
    "Consolacion",
    "Dapco",
    "Datu Abdul Dadia",
    "Gredu (Pob.)",
    "J.P. Laurel",
    "Kasilak",
    "Katipunan",
    "Katualan",
    "Kauswagan",
    "Kiotoy",
    "Little Panay",
    "Lower Panaga",
    "Mabunao",
    "Maduao",
    "Malativas",
    "Manay",
    "Nanyo",
    "New Malaga",
    "New Malitbog",
    "New Pandan (Pob.)",
    "New Visayas",
    "Quezon",
    "Salvacion",
    "San Francisco (Pob.)",
    "San Nicolas",
    "San Pedro",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Santo Niño (Pob.)",
    "Sindaton",
    "Southern Davao",
    "Tagpore",
    "Tibungol",
    "Upper Licanan",
    "Waterfall",
  ],
  "1102317000": [
    "Adecor",
    "Anonang",
    "Aumbay",
    "Aundanao",
    "Balet",
    "Bandera",
    "Caliclic",
    "Camudmud",
    "Catagman",
    "Cawag",
    "Cogon",
    "Cogon",
    "Dadatan",
    "Del Monte",
    "Guilon",
    "Kanaan",
    "Kinawitnon",
    "Libertad",
    "Libuak",
    "Licup",
    "Limao",
    "Linosutan",
    "Mambago-A",
    "Mambago-B",
    "Miranda (Pob.)",
    "Moncado (Pob.)",
    "Pangubatan",
    "Peñaplata (Pob.)",
    "Poblacion",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Isidro",
    "San Jose",
    "San Miguel",
    "San Remigio",
    "Santa Cruz",
    "Santo Niño",
    "Sion",
    "Tagbaobo",
    "Tagbay",
    "Tagbitan-ag",
    "Tagdaliao",
    "Tagpopongan",
    "Tambo",
    "Toril",
  ],
  "1102318000": [
    "Balagunan",
    "Bobongon",
    "Casig-Ang",
    "Esperanza",
    "Kimamon",
    "Kinamayan",
    "La Libertad",
    "Lungaog",
    "Magwawa",
    "New Katipunan",
    "New Visayas",
    "Pantaron",
    "Salvacion",
    "San Jose",
    "San Miguel",
    "San Vicente",
    "Talomo",
    "Tibal-og (Pob.)",
    "Tulalian",
  ],
  "1102319000": [
    "Apokon",
    "Bincungan",
    "Busaon",
    "Canocotan",
    "Cuambogan",
    "La Filipina",
    "Liboganon",
    "Madaum",
    "Magdum",
    "Magugpo East",
    "Magugpo North",
    "Magugpo Poblacion",
    "Magugpo South",
    "Magugpo West",
    "Mankilam",
    "New Balamban",
    "Nueva Fuerza",
    "Pagsabangan",
    "Pandapan",
    "San Agustin",
    "San Isidro",
    "San Miguel",
    "Visayan Village",
  ],
  "1102322000": ["Dagohoy", "Palma Gil", "Santo Niño"],
  "1102323000": ["Cabayangan", "Dujali", "Magupising", "New Casay", "Tanglaw"],
  "1102324000": [
    "Dacudao",
    "Datu Balong",
    "Igangon",
    "Kipalili",
    "Libuton",
    "Linao",
    "Mamangan",
    "Monte Dujali",
    "Pinamuno",
    "Sabangan",
    "San Miguel",
    "Santo Niño",
    "Sawata",
  ],
  "1102401000": [
    "Alegre",
    "Alta Vista",
    "Anonang",
    "Bitaug",
    "Bonifacio",
    "Buenavista",
    "Darapuay",
    "Dolo",
    "Eman",
    "Kinuskusan",
    "Libertad",
    "Linawan",
    "Mabuhay",
    "Mabunga",
    "Managa",
    "Marber",
    "New Clarin",
    "Poblacion",
    "Poblacion Dos",
    "Rizal",
    "Santo Niño",
    "Sibayan",
    "Tinongtongan",
    "Tubod",
    "Union",
  ],
  "1102403000": [
    "Aplaya",
    "Balabag",
    "Binaton",
    "Cogon",
    "Colorado",
    "Dawis",
    "Dulangan",
    "Goma",
    "Igpit",
    "Kapatagan",
    "Kiagot",
    "Lungag",
    "Mahayahay",
    "Matti",
    "Ruparan",
    "San Agustin",
    "San Jose",
    "San Miguel",
    "San Roque",
    "Sinawilan",
    "Soong",
    "Tiguman",
    "Tres De Mayo",
    "Zone 1 (Pob.)",
    "Zone 2 (Pob.)",
    "Zone 3 (Pob.)",
  ],
  "1102404000": [
    "Balutakay",
    "Clib",
    "Guihing",
    "Guihing Aplaya",
    "Hagonoy Crossing",
    "Kibuaya",
    "La Union",
    "Lanuro",
    "Lapulabao",
    "Leling",
    "Mahayahay",
    "Malabang Damsite",
    "Maliit Digos",
    "New Quezon",
    "Paligue",
    "Poblacion",
    "Sacub",
    "San Guillermo",
    "San Isidro",
    "Sinayawan",
    "Tologan",
  ],
  "1102406000": [
    "Abnate",
    "Bagong Negros",
    "Bagong Silang",
    "Bagumbayan",
    "Balasiao",
    "Bonifacio",
    "Bulol-Salo",
    "Bunot",
    "Cogon-Bacaca",
    "Dapok",
    "Ihan",
    "Kibongbong",
    "Kimlawis",
    "Kisulan",
    "Lati-an",
    "Manual",
    "Maraga-a",
    "Molopolo",
    "New Sibonga",
    "Panaglib",
    "Pasig",
    "Poblacion",
    "Pocaleel",
    "San Isidro",
    "San Jose",
    "San Pedro",
    "Santo Niño",
    "Tacub",
    "Tacul",
    "Waterfall",
  ],
  "1102407000": [
    "Bacungan",
    "Balnate",
    "Barayong",
    "Blocon",
    "Dalawinon",
    "Dalumay",
    "Glamang",
    "Kanapulo",
    "Kasuga",
    "Lower Bala",
    "Mabini",
    "Maibo",
    "Malawanit",
    "Malongon",
    "New Ilocos",
    "New Opon",
    "Poblacion",
    "San Isidro",
    "San Miguel",
    "Tacul",
    "Tagaytay",
    "Upper Bala",
  ],
  "1102408000": [
    "Bagumbayan",
    "Baybay",
    "Bolton",
    "Bulacan",
    "Caputian",
    "Ibo",
    "Kiblagon",
    "Lapu-Lapu",
    "Mabini",
    "New Baclayon",
    "Pitu",
    "Poblacion",
    "Rizal",
    "San Isidro",
    "Tagansule",
  ],
  "1102410000": [
    "Asbang",
    "Asinan",
    "Bagumbayan",
    "Bangkal",
    "Buas",
    "Buri",
    "Cabligan",
    "Camanchiles",
    "Ceboza",
    "Colonsabak",
    "Dongan-Pekong",
    "Kabasagan",
    "Kapok",
    "Kauswagan",
    "Kibao",
    "La Suerte",
    "Langa-an",
    "Lower Marber",
    "Manga",
    "New Katipunan",
    "New Murcia",
    "New Visayas",
    "Poblacion",
    "Saboy",
    "San Jose",
    "San Miguel",
    "San Vicente",
    "Saub",
    "Sinaragan",
    "Sinawilan",
    "Tamlangon",
    "Tibongbong",
    "Towak",
  ],
  "1102411000": [
    "Almendras (Pob.)",
    "Don Sergio Osmeña, Sr.",
    "Harada Butai",
    "Lower Katipunan",
    "Lower Limonzo",
    "Lower Malinao",
    "N C Ordaneza District (Pob.)",
    "Northern Paligue",
    "Palili",
    "Piape",
    "Punta Piape",
    "Quirino District (Pob.)",
    "San Isidro",
    "Southern Paligue",
    "Tulogan",
    "Upper Limonzo",
    "Upper Malinao",
  ],
  "1102412000": [
    "Astorga",
    "Bato",
    "Coronon",
    "Darong",
    "Inawayan",
    "Jose Rizal",
    "Matutungan",
    "Melilia",
    "Saliducon",
    "Sibulan",
    "Sinoron",
    "Tagabuli",
    "Tibolo",
    "Tuban",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)",
  ],
  "1102414000": [
    "Balasinon",
    "Buguis",
    "Carre",
    "Clib",
    "Harada Butai",
    "Katipunan",
    "Kiblagon",
    "Labon",
    "Laperas",
    "Lapla",
    "Litos",
    "Luparan",
    "Mckinley",
    "New Cebu",
    "Osmeña",
    "Palili",
    "Parame",
    "Poblacion",
    "Roxas",
    "Solongvale",
    "Tagolilong",
    "Tala-o",
    "Talas",
    "Tanwalang",
    "Waterfall",
  ],
  "1102501000": [
    "Baculin",
    "Banao",
    "Batawan",
    "Batiano",
    "Binondo",
    "Bobonao",
    "Campawan",
    "Central (Pob.)",
    "Dapnan",
    "Kinablangan",
    "Lambajon",
    "Lucod",
    "Mahanub",
    "Mikit",
    "Salingcomot",
    "San Isidro",
    "San Victor",
    "Saoquegue",
  ],
  "1102502000": [
    "Cabangcalan",
    "Caganganan",
    "Calubihan",
    "Causwagan",
    "Mahayag",
    "Maputi",
    "Mogbongcogon",
    "Panikian",
    "Pintatagan",
    "Piso Proper",
    "Poblacion",
    "Punta Linao",
    "Rang-ay",
    "San Vicente",
  ],
  "1102503000": [
    "Caatihan",
    "Cabasagan",
    "Carmen",
    "Cawayanan",
    "Poblacion",
    "San Jose",
    "Sibajay",
    "Simulao",
  ],
  "1102504000": [
    "Alvar",
    "Caningag",
    "Don Leon Balante",
    "Lamiawan",
    "Manorigao",
    "Mercedes",
    "Palma Gil",
    "Pichon",
    "Poblacion",
    "San Antonio",
    "San Jose",
    "San Luis",
    "San Miguel",
    "San Pedro",
    "Santa Fe",
    "Santiago",
    "Sobrecarey",
  ],
  "1102505000": [
    "Abijod",
    "Alegria",
    "Aliwagwag",
    "Aragon",
    "Baybay",
    "Maglahus",
    "Mainit",
    "Malibago",
    "Poblacion",
    "San Alfonso",
    "San Antonio",
    "San Miguel",
    "San Rafael",
    "San Vicente",
    "Santa Filomena",
    "Taytayan",
  ],
  "1102506000": [
    "Anitap",
    "Crispin Dela Cruz",
    "Don Aurelio Chicote",
    "Lavigan",
    "Luzon",
    "Magdug",
    "Manuel Roxas",
    "Monserrat",
    "Nangan",
    "Oregon",
    "Poblacion",
    "Pundaguitan",
    "Sergio Osmeña",
    "Surop",
    "Tagabebe",
    "Tamban",
    "Tandang Sora",
    "Tibanban",
    "Tiblawan",
    "Upper Tibanban",
  ],
  "1102507000": [
    "Bagumbayan",
    "Cabadiangan",
    "Calapagan",
    "Cocornon",
    "Corporacion",
    "Don Mariano Marcos",
    "Ilangay",
    "Langka",
    "Lantawan",
    "Limbahan",
    "Macangao",
    "Magsaysay",
    "Mahayahay",
    "Maragatas",
    "Marayag",
    "New Visayas",
    "Poblacion",
    "San Isidro",
    "San Jose",
    "Tagboa",
    "Tagugpo",
  ],
  "1102508000": [
    "Capasnan",
    "Cayawan",
    "Central (Pob.)",
    "Concepcion",
    "Del Pilar",
    "Guza",
    "Holy Cross",
    "Lambog",
    "Mabini",
    "Manreza",
    "New Taokanga",
    "Old Macopa",
    "Rizal",
    "San Fermin",
    "San Ignacio",
    "San Isidro",
    "Zaragosa",
  ],
  "1102509000": [
    "Badas",
    "Bobon",
    "Buso",
    "Cabuaya",
    "Central (Pob.)",
    "Culian",
    "Dahican",
    "Danao",
    "Dawan",
    "Don Enrique Lopez",
    "Don Martin Marundan",
    "Don Salvador Lopez, Sr.",
    "Langka",
    "Lawigan",
    "Libudon",
    "Luban",
    "Macambol",
    "Mamali",
    "Matiao",
    "Mayo",
    "Sainz",
    "Sanghay",
    "Tagabakid",
    "Tagbinonga",
    "Taguibo",
    "Tamisan",
  ],
  "1102510000": [
    "Baon",
    "Batobato (Pob.)",
    "Bitaogan",
    "Cambaleon",
    "Dugmanon",
    "Iba",
    "La Union",
    "Lapu-lapu",
    "Maag",
    "Manikling",
    "Maputi",
    "San Miguel",
    "San Roque",
    "Santo Rosario",
    "Sudlon",
    "Talisay",
  ],
  "1102511000": [
    "Cabagayan",
    "Central (Pob.)",
    "Dadong",
    "Jovellar",
    "Limot",
    "Lucatan",
    "Maganda",
    "Ompao",
    "Tomoaong",
    "Tubaon",
  ],
  "1108201000": [
    "Aurora",
    "Bagongon",
    "Gabi",
    "Lagab",
    "Mangayon",
    "Mapaca",
    "Maparat",
    "New Alegria",
    "Ngan",
    "Osmeña",
    "Panansalan",
    "Poblacion",
    "San Jose",
    "San Miguel",
    "Siocon",
    "Tamia",
  ],
  "1108202000": [
    "Aguinaldo",
    "Amor Cruz",
    "Ampawid",
    "Andap",
    "Anitap",
    "Bagong Silang",
    "Banbanon",
    "Belmonte",
    "Binasbas",
    "Bullucan",
    "Cebulida",
    "Concepcion",
    "Datu Ampunan",
    "Datu Davao",
    "Doña Josefa",
    "El Katipunan",
    "Il Papa",
    "Imelda",
    "Inacayan",
    "Kaligutan",
    "Kapatagan",
    "Kidawa",
    "Kilagding",
    "Kiokmay",
    "Laac (Pob.)",
    "Langtud",
    "Longanapan",
    "Mabuhay",
    "Macopa",
    "Malinao",
    "Mangloy",
    "Melale",
    "Naga",
    "New Bethlehem",
    "Panamoren",
    "Sabud",
    "San Antonio",
    "Santa Emilia",
    "Santo Niño",
    "Sisimon",
  ],
  "1108203000": [
    "Anitapan",
    "Cabuyuan",
    "Cadunan",
    "Cuambog (Pob.)",
    "Del Pilar",
    "Golden Valley",
    "Libodon",
    "Pangibiran",
    "Pindasan",
    "San Antonio",
    "Tagnanan",
  ],
  "1108204000": [
    "Anibongan",
    "Anislagan",
    "Binuangan",
    "Bucana",
    "Calabcab",
    "Concepcion",
    "Dumlan",
    "Elizalde",
    "Gubatan",
    "Hijo",
    "Kinuban",
    "Langgam",
    "Lapu-lapu",
    "Libay-libay",
    "Limbo",
    "Lumatab",
    "Magangit",
    "Mainit",
    "Malamodao",
    "Manipongol",
    "Mapaang",
    "Masara",
    "New Asturias",
    "New Barili",
    "New Leyte",
    "New Visayas",
    "Panangan",
    "Pangi",
    "Panibasan",
    "Panoraon",
    "Poblacion",
    "San Juan",
    "San Roque",
    "Sangab",
    "Tagbaros",
    "Taglawig",
    "Teresa",
  ],
  "1108205000": [
    "Bagong Silang",
    "Bahi",
    "Cambagang",
    "Coronobe",
    "Katipunan",
    "Lahi",
    "Langgawisan",
    "Mabugnao",
    "Magcagong",
    "Mahayahay",
    "Mapawa",
    "Maragusan (Pob.)",
    "Mauswagon",
    "New Albay",
    "New Katipunan",
    "New Manay",
    "New Panay",
    "Paloc",
    "Pamintaran",
    "Parasanon",
    "Talian",
    "Tandik",
    "Tigbao",
    "Tupas",
  ],
  "1108206000": [
    "Andili",
    "Bawani",
    "Concepcion",
    "Malinawon",
    "Nueva Visayas",
    "Nuevo Iloco",
    "Poblacion",
    "Salvacion",
    "Saosao",
    "Sawangan",
    "Tuboran",
  ],
  "1108207000": [
    "Awao",
    "Babag",
    "Banlag",
    "Baylo",
    "Casoon",
    "Haguimitan",
    "Inambatan",
    "Macopa",
    "Mamunga",
    "Mount Diwata",
    "Naboc",
    "Olaycon",
    "Pasian",
    "Poblacion",
    "Rizal",
    "Salvacion",
    "San Isidro",
    "San Jose",
    "Tubo-tubo",
    "Union",
    "Upper Ulip",
  ],
  "1108208000": [
    "Banagbanag",
    "Banglasan",
    "Bankerohan Norte",
    "Bankerohan Sur",
    "Camansi",
    "Camantangan",
    "Canidkid",
    "Concepcion",
    "Dauman",
    "Lebanon",
    "Linoan",
    "Mayaon",
    "New Calape",
    "New Cebulan",
    "New Dalaguete",
    "New Visayas",
    "Prosperidad",
    "San Jose (Pob.)",
    "San Vicente",
    "Tapia",
  ],
  "1108209000": [
    "Anislagan",
    "Antequera",
    "Basak",
    "Bayabas",
    "Bukal",
    "Cabacungan",
    "Cabidianan",
    "Katipunan",
    "Libasan",
    "Linda",
    "Magading",
    "Magsaysay",
    "Mainit",
    "Manat",
    "Matilo",
    "Mipangi",
    "New Dauis",
    "New Sibonga",
    "Ogao",
    "Pangutosan",
    "Poblacion",
    "San Isidro",
    "San Roque",
    "San Vicente",
    "Santa Maria",
    "Santo Niño",
    "Sasa",
    "Tagnocon",
  ],
  "1108210000": [
    "Andap",
    "Bantacan",
    "Batinao",
    "Cabinuangan (Pob.)",
    "Camanlangan",
    "Cogonon",
    "Fatima",
    "Kahayag",
    "Katipunan",
    "Magangit",
    "Magsaysay",
    "Manurigao",
    "Pagsabangan",
    "Panag",
    "San Roque",
    "Tandawan",
  ],
  "1108211000": [
    "Araibo",
    "Bongabong",
    "Bongbong",
    "Kingking (Pob.)",
    "Las Arenas",
    "Magnaga",
    "Matiao",
    "Napnapan",
    "P. Fuentes",
    "Tag-Ugpo",
    "Tagdangua",
    "Tambongon",
    "Tibagon",
  ],
  "1108601000": [
    "Baluntaya",
    "Calian",
    "Dalupan",
    "Kinanga",
    "Kiobog",
    "Lanao",
    "Lapuan",
    "Lawa (Pob.)",
    "Linadasan",
    "Mabuhay",
    "North Lamidan",
    "Nueva Villa",
    "South Lamidan",
    "Talagutong (Pob.)",
    "West Lamidan",
  ],
  "1108602000": [
    "Balangonan",
    "Buguis",
    "Bukid",
    "Butuan",
    "Butulan",
    "Caburan Big",
    "Caburan Small (Pob.)",
    "Camalian",
    "Carahayan",
    "Cayaponga",
    "Culaman",
    "Kalbay",
    "Kitayo",
    "Magulibas",
    "Malalan",
    "Mangile",
    "Marabutuan",
    "Meybio",
    "Molmol",
    "Nuing",
    "Patulang",
    "Quiapo",
    "San Isidro",
    "Sugal",
    "Tabayon",
    "Tanuman",
  ],
  "1108603000": [
    "Bito",
    "Bolila",
    "Buhangin",
    "Culaman",
    "Datu Danwata",
    "Demoloc",
    "Felis",
    "Fishing Village",
    "Kibalatong",
    "Kidalapong",
    "Kilalag",
    "Kinangan",
    "Lacaron",
    "Lagumit",
    "Lais",
    "Little Baguio",
    "Macol",
    "Mana",
    "Manuel Peralta",
    "New Argao",
    "Pangaleon",
    "Pangian",
    "Pinalpalan",
    "Poblacion",
    "Sangay",
    "Talogoy",
    "Tical",
    "Ticulon",
    "Tingolo",
    "Tubalan",
  ],
  "1108604000": [
    "Basiawan",
    "Buca",
    "Cadaatan",
    "Datu Daligasao",
    "Datu Intan",
    "Kidadan",
    "Kinilidan",
    "Kisulad",
    "Malalag Tubig",
    "Mamacao",
    "Ogpao",
    "Poblacion",
    "Pongpong",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Juan",
    "San Pedro",
    "San Roque",
    "Santo Niño",
    "Santo Rosario",
    "Tanglad",
  ],
  "1108605000": [
    "Batuganding",
    "Camahual",
    "Camalig",
    "Gomtago",
    "Konel",
    "Laker",
    "Lipol",
    "Mabila (Pob.)",
    "Patuco",
    "Tagen",
    "Tinina",
    "Tucal",
  ],
  "1130700000": [
    "Acacia",
    "Agdao",
    "Alambre",
    "Alejandra Navarro",
    "Alfonso Angliongto Sr.",
    "Angalan",
    "Atan-Awe",
    "Baganihan",
    "Bago Aplaya",
    "Bago Gallera",
    "Bago Oshiro",
    "Baguio (Pob.)",
    "Balengaeng",
    "Baliok",
    "Bangkas Heights",
    "Bantol",
    "Baracatan",
    "Barangay 1-A (Pob.)",
    "Barangay 10-A (Pob.)",
    "Barangay 11-B (Pob.)",
    "Barangay 12-B (Pob.)",
    "Barangay 13-B (Pob.)",
    "Barangay 14-B (Pob.)",
    "Barangay 15-B (Pob.)",
    "Barangay 16-B (Pob.)",
    "Barangay 17-B (Pob.)",
    "Barangay 18-B (Pob.)",
    "Barangay 19-B (Pob.)",
    "Barangay 2-A (Pob.)",
    "Barangay 20-B (Pob.)",
    "Barangay 21-C (Pob.)",
    "Barangay 22-C (Pob.)",
    "Barangay 23-C (Pob.)",
    "Barangay 24-C (Pob.)",
    "Barangay 25-C (Pob.)",
    "Barangay 26-C (Pob.)",
    "Barangay 27-C (Pob.)",
    "Barangay 28-C (Pob.)",
    "Barangay 29-C (Pob.)",
    "Barangay 3-A (Pob.)",
    "Barangay 30-C (Pob.)",
    "Barangay 31-D (Pob.)",
    "Barangay 32-D (Pob.)",
    "Barangay 33-D (Pob.)",
    "Barangay 34-D (Pob.)",
    "Barangay 35-D (Pob.)",
    "Barangay 36-D (Pob.)",
    "Barangay 37-D (Pob.)",
    "Barangay 38-D (Pob.)",
    "Barangay 39-D (Pob.)",
    "Barangay 4-A (Pob.)",
    "Barangay 40-D (Pob.)",
    "Barangay 5-A (Pob.)",
    "Barangay 6-A (Pob.)",
    "Barangay 7-A (Pob.)",
    "Barangay 8-A (Pob.)",
    "Barangay 9-A (Pob.)",
    "Bato",
    "Bayabas",
    "Biao Escuela",
    "Biao Guianga",
    "Biao Joaquin",
    "Binugao",
    "Bucana",
    "Buda",
    "Buhangin (Pob.)",
    "Bunawan (Pob.)",
    "Cabantian",
    "Cadalian",
    "Calinan (Pob.)",
    "Callawa",
    "Camansi",
    "Carmen",
    "Catalunan Grande",
    "Catalunan Pequeño",
    "Catigan",
    "Cawayan",
    "Centro",
    "Colosas",
    "Communal",
    "Crossing Bayabas",
    "Dacudao",
    "Dalag",
    "Dalagdag",
    "Daliao",
    "Daliaon Plantation",
    "Datu Salumay",
    "Dominga",
    "Dumoy",
    "Eden",
    "Fatima",
    "Gatungan",
    "Gov. Paciano Bangoy",
    "Gov. Vicente Duterte",
    "Gumalang",
    "Gumitan",
    "Ilang",
    "Inayangan",
    "Indangan",
    "Kap. Tomas Monteverde, Sr.",
    "Kilate",
    "Lacson",
    "Lamanan",
    "Lampianao",
    "Langub",
    "Lapu-lapu",
    "Leon Garcia, Sr.",
    "Lizada",
    "Los Amigos",
    "Lubogan",
    "Lumiad",
    "Ma-a",
    "Mabuhay",
    "Magsaysay",
    "Magtuod",
    "Mahayag",
    "Malabog",
    "Malagos",
    "Malamba",
    "Manambulan",
    "Mandug",
    "Manuel Guianga",
    "Mapula",
    "Marapangi",
    "Marilog",
    "Matina Aplaya",
    "Matina Biao",
    "Matina Crossing",
    "Matina Pangi",
    "Megkawayan",
    "Mintal",
    "Mudiang",
    "Mulig",
    "New Carmen",
    "New Valencia",
    "Pampanga",
    "Panacan",
    "Panalum",
    "Pandaitan",
    "Pangyan",
    "Paquibato (Pob.)",
    "Paradise Embak",
    "Rafael Castillo",
    "Riverside",
    "Salapawan",
    "Salaysay",
    "Saloy",
    "San Antonio",
    "San Isidro",
    "Santo Niño",
    "Sasa",
    "Sibulan",
    "Sirawan",
    "Sirib",
    "Suawan",
    "Subasta",
    "Sumimao",
    "Tacunan",
    "Tagakpan",
    "Tagluno",
    "Tagurano",
    "Talandang",
    "Talomo (Pob.)",
    "Talomo River",
    "Tamayong",
    "Tambobong",
    "Tamugan",
    "Tapak",
    "Tawan-tawan",
    "Tibuloy",
    "Tibungco",
    "Tigatto",
    "Toril (Pob.)",
    "Tugbok (Pob.)",
    "Tungakalan",
    "Ubalde",
    "Ula",
    "Vicente Hizon Sr.",
    "Waan",
    "Wangan",
    "Wilfredo Aquino",
    "Wines",
  ],
};
