/** GENERATED — Region XII: 1095 barangays across 49 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "1204701000": [
    "Bao",
    "Barangiran",
    "Camansi",
    "Dado",
    "Guiling",
    "Kitacubong (Pob.)",
    "Lower Dado",
    "Macabasa",
    "Malitubog",
    "Mapurok",
    "Mirasol",
    "Pacao",
    "Paruayan",
    "Pigcawaran",
    "Polayagan",
    "Rangayen",
    "Raradangan",
  ],
  "1204702000": [
    "Aroman",
    "Bentangan",
    "Cadiis",
    "General Luna",
    "Katanayanan",
    "Kibenes",
    "Kibugtongan",
    "Kilala",
    "Kimadzil",
    "Lanoon",
    "Liliongan",
    "Macabenban",
    "Malapag",
    "Manili",
    "Palanggalan",
    "Poblacion",
    "Ranzo",
    "Tacupan",
    "Tambad",
    "Tonganon",
    "Ugalingan",
  ],
  "1204703000": [
    "Aringay",
    "Bangilan",
    "Bannawag",
    "Cuyapon",
    "Dagupan",
    "Katidtuan",
    "Kayaga",
    "Kilagasan",
    "Magatos",
    "Malamote",
    "Malanduague",
    "Osias",
    "Paatan Lower",
    "Paatan Upper",
    "Pisan",
    "Poblacion",
    "Salapungan",
  ],
  "1204704000": [
    "Amas",
    "Amazion",
    "Balabag",
    "Balindog",
    "Benoligan",
    "Berada",
    "Gayola",
    "Ginatilan",
    "Ilomavis",
    "Indangan",
    "Junction",
    "Kalaisan",
    "Kalasuyan",
    "Katipunan",
    "Lanao",
    "Linangcob",
    "Luvimin",
    "Macabolig",
    "Magsaysay",
    "Malinan",
    "Manongol",
    "Marbel",
    "Mateo",
    "Meochao",
    "Mua-an",
    "New Bohol",
    "Nuangan",
    "Onica",
    "Paco",
    "Patadon",
    "Perez",
    "Poblacion",
    "San Isidro",
    "San Roque",
    "Santo Niño",
    "Sibawan",
    "Sikitan",
    "Singao",
    "Sudapin",
    "Sumbao",
  ],
  "1204705000": [
    "Abaga",
    "Baguer",
    "Barongis",
    "Batiocan",
    "Cabaruyan",
    "Cabpangi",
    "Demapaco",
    "Grebona",
    "Gumaga",
    "Kapayawi",
    "Kiloyao",
    "Kitubod",
    "Malengen",
    "Montay",
    "Nica-an",
    "Palao",
    "Poblacion",
    "Sinapangan",
    "Sinawingan",
    "Ulamian",
  ],
  "1204706000": [
    "Alibayon",
    "Amabel",
    "Bagumbayan",
    "Balete",
    "Bangkal",
    "Bantac",
    "Basak",
    "Binay",
    "Bongolanon",
    "Datu Celo",
    "Del Pilar",
    "Doles",
    "Don Panaca",
    "Gubatan",
    "Ilian",
    "Imamaling",
    "Inac",
    "Kamada",
    "Kauswagan",
    "Kinarum",
    "Kisandal",
    "Magcaalam",
    "Mahongcog",
    "Manobisa",
    "Manobo",
    "Noa",
    "Owas",
    "Pangao-an",
    "Poblacion",
    "Sallab",
    "Tagbac",
    "Temporan",
  ],
  "1204707000": [
    "Batasan",
    "Bato",
    "Biangan",
    "Buena Vida",
    "Buhay",
    "Bulakanon",
    "Cabilao",
    "Concepcion",
    "Dagupan",
    "Garsika",
    "Guangan",
    "Indangan",
    "Jose Rizal",
    "Katipunan II",
    "Kawayanon",
    "Kisante",
    "Leboce",
    "Libertad",
    "Luayon",
    "Luna Norte",
    "Luna Sur",
    "Malabuan",
    "Malasila",
    "Malungon",
    "New Baguio",
    "New Bulatukan",
    "New Cebu",
    "New Israel",
    "Old Bulatukan",
    "Poblacion",
    "Rodero",
    "Saguing",
    "San Vicente",
    "Santa Felomina",
    "Santo Niño",
    "Sinkatulan",
    "Taluntalunan",
    "Villaflores",
  ],
  "1204708000": [
    "Arakan",
    "Bangbang",
    "Bato",
    "Central Malamote",
    "Dalapitan",
    "Estado",
    "Ilian",
    "Kabulacan",
    "Kibia",
    "Kibudoc",
    "Kidama",
    "Kilada",
    "Lampayan",
    "Latagan",
    "Linao",
    "Lower Malamote",
    "Manubuan",
    "Manupal",
    "Marbel",
    "Minamaing",
    "Natutungan",
    "New Abra",
    "New Alimodian",
    "New Bugasong",
    "New Pandan",
    "Patadon West",
    "Pinamaton",
    "Poblacion",
    "Salvacion",
    "Santa Maria",
    "Sarayan",
    "Taculen",
    "Taguranao",
    "Tamped",
  ],
  "1204709000": [
    "Agriculture",
    "Anonang",
    "Arizona",
    "Bagumba",
    "Baliki",
    "Barangay Poblacion 1",
    "Barangay Poblacion 2",
    "Barangay Poblacion 3",
    "Barangay Poblacion 4",
    "Barangay Poblacion 5",
    "Barangay Poblacion 6",
    "Barangay Poblacion 7",
    "Barangay Poblacion 8",
    "Bitoka",
    "Bual Norte",
    "Bual Sur",
    "Bulanan Upper",
    "Central Bulanan",
    "Central Glad",
    "Central Katingawan",
    "Ilbocean",
    "Kimagango",
    "Kiwanan",
    "Lagumbingan",
    "Lomopog",
    "Lower Glad",
    "Lower Katingawan",
    "Macasendeg",
    "Malamote",
    "Milaya",
    "Nalin",
    "Nes",
    "Palongoguen",
    "Patindeguen",
    "Rangaban",
    "Sadaan",
    "Salunayan",
    "San Isidro",
    "San Pedro",
    "Santa Cruz",
    "Upper Glad I",
    "Upper Glad II",
    "Upper Labas",
    "Villarica",
  ],
  "1204710000": [
    "Bagontapay",
    "Bialong",
    "Buayan",
    "Calunasan",
    "Dagong",
    "Dalipe",
    "Dungo-an",
    "Gaunan",
    "Inas",
    "Katipunan",
    "La Fortuna",
    "La Suerte",
    "Langkong",
    "Lepaga",
    "Liboo",
    "Lika",
    "Luz Village",
    "Magallon",
    "Malayan",
    "New Antique",
    "New Barbaza",
    "New Consolacion",
    "New Esperanza",
    "New Janiuay",
    "New Kalibo",
    "New Lawa-an",
    "New Rizal",
    "Nueva Vida",
    "Pag-asa",
    "Palma-Perez",
    "Poblacion",
    "Poblacion B",
    "Pulang-lupa",
    "Sangat",
    "Tawantawan",
    "Tibao",
    "Ugpay",
  ],
  "1204711000": [
    "Anick",
    "Balogo",
    "Banucagon",
    "Buluan",
    "Bulucaon",
    "Cabpangi",
    "Capayuran",
    "Central Panatan",
    "Kimarayang",
    "Malagakit",
    "Maluao",
    "Midpapan I",
    "Midpapan II",
    "Mulok",
    "New Culasi",
    "New Igbaras",
    "New Panay",
    "North Manuangan",
    "Payong-payong",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Presbitero",
    "Renibon",
    "South Manuangan",
    "Tigbawan",
    "Tubon",
    "Upper Baguer",
  ],
  "1204712000": [
    "Balabak",
    "Balatican",
    "Bulod",
    "Calawag",
    "Dalingaoen",
    "Damalasak",
    "Ginatilan",
    "Inug-ug",
    "Kalacacan",
    "Katilacan",
    "Kolambog",
    "Ladtingan",
    "Langayen",
    "Paidu Pulangi",
    "Poblacion",
    "Punol",
    "Silik",
    "Takipan",
    "Talitay",
    "Tinutulan",
  ],
  "1204713000": [
    "Alegria",
    "Bato-bato",
    "Cabangbangan",
    "Camasi",
    "Datu Indang",
    "Datu Sandongan",
    "Del Carmen",
    "F. Cajelo",
    "Greenhill",
    "Idaoman",
    "Ilustre",
    "Kamarahan",
    "Kimaruhing",
    "Kisupaan",
    "La Esperanza",
    "Labu-o",
    "Lamalama",
    "Lomonay",
    "Mabuhay",
    "New Cebu",
    "Poblacion",
    "Sagcungan",
    "Salat",
    "Sarayan",
    "Tuael",
  ],
  "1204714000": [
    "Bacong",
    "Bagumbayan",
    "Banayal",
    "Batang",
    "Bituan",
    "Bual",
    "Bunawan",
    "Daig",
    "Damawato",
    "Dungos",
    "F. Cajelo",
    "Galidan",
    "Genoveva Baynosa",
    "Kanibong",
    "La Esperanza",
    "Lampagang",
    "Magbok",
    "Maybula",
    "Minapan",
    "Nabundasan",
    "New Caridad",
    "New Culasi",
    "New Panay",
    "Paraiso",
    "Poblacion",
    "Popoyon",
    "Sibsib",
    "Tambac",
    "Tuburan",
  ],
  "1204715000": [
    "B. Cadungon",
    "Camutan",
    "Canaan",
    "Datu Agod",
    "Dolores",
    "Kiyaab",
    "Luhong",
    "Magsaysay",
    "Malangag",
    "Malatad",
    "Malire",
    "New Pontevedra",
    "Poblacion",
  ],
  "1204716000": [
    "Banisilan Poblacion",
    "Busaon",
    "Capayangan",
    "Carugmanan",
    "Gastay",
    "Kalawaig",
    "Kiaring",
    "Malagap",
    "Malinao",
    "Miguel Macasarte",
    "Pantar",
    "Paradise",
    "Pinamulaan",
    "Poblacion II",
    "Puting-bato",
    "Solama",
    "Thailand",
    "Tinimbacan",
    "Tumbao-Camalig",
    "Wadya",
  ],
  "1204717000": [
    "Bagolibas",
    "Cawilihan",
    "Dualing",
    "Katalicanan",
    "Lawili",
    "Lower Mingading",
    "Luanan",
    "Malapang",
    "New Leon",
    "New Panay",
    "Pagangan",
    "Palacat",
    "Pentil",
    "San Mateo",
    "Santa Cruz",
    "Tomado",
    "Upper Mingading",
  ],
  "1204718000": [
    "Allab",
    "Anapolon",
    "Badiangon",
    "Binoongan",
    "Dallag",
    "Datu Ladayon",
    "Datu Matangkil",
    "Doroluman",
    "Gambodes",
    "Ganatan",
    "Greenfield",
    "Kabalantian",
    "Katipunan",
    "Kinawayan",
    "Kulaman Valley",
    "Lanao Kuran",
    "Libertad",
    "Makalangot",
    "Malibatuan",
    "Maria Caridad",
    "Meocan",
    "Naje",
    "Napalico",
    "Salasang",
    "San Miguel",
    "Santo Niño",
    "Sumalili",
    "Tumanding",
  ],
  "1206302000": [
    "Benitez (Pob.)",
    "Cabudian",
    "Cabuling",
    "Cinco",
    "Derilon",
    "El Nonok",
    "Improgo Village (Pob.)",
    "Kusan",
    "Lam-Apos",
    "Lamba",
    "Lambingi",
    "Lampari",
    "Liwanay",
    "Malaya",
    "Punong Grande",
    "Rang-ay",
    "Reyes (Pob.)",
    "Rizal",
    "Rizal Poblacion",
    "San Jose",
    "San Vicente",
    "Yangco Poblacion",
  ],
  "1206306000": [
    "Assumption",
    "Avanceña",
    "Cacub",
    "Caloocan",
    "Carpenter Hill",
    "Concepcion",
    "Esperanza",
    "General Paulino Santos",
    "Mabini",
    "Magsaysay",
    "Mambucal",
    "Morales",
    "Namnama",
    "New Pangasinan",
    "Paraiso",
    "Rotonda",
    "San Isidro",
    "San Jose",
    "San Roque",
    "Santa Cruz",
    "Santo Niño",
    "Sarabia",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)",
    "Zulueta",
  ],
  "1206311000": [
    "Benigno Aquino, Jr.",
    "Dumaguil",
    "Esperanza",
    "Kibid",
    "Lapuz",
    "Liberty",
    "Lopez Jaena",
    "Matapol",
    "Poblacion",
    "Puti",
    "San Jose",
    "San Miguel",
    "Simsiman",
    "Tinago",
  ],
  "1206312000": [
    "Bentung",
    "Cannery Site",
    "Crossing Palkan",
    "Glamang",
    "Kinilis",
    "Klinan 6",
    "Koronadal Proper",
    "Lam-Caliaf",
    "Landan",
    "Lapu",
    "Lumakil",
    "Magsaysay",
    "Maligo",
    "Pagalungan",
    "Palkan",
    "Poblacion",
    "Polo",
    "Rubber",
    "Silway 7",
    "Silway 8",
    "Sulit",
    "Sumbakil",
    "Upper Klinan",
  ],
  "1206313000": [
    "Buenavista",
    "Canahay",
    "Centrala",
    "Colongulo",
    "Dajay",
    "Duengas",
    "Lambontong",
    "Lamian",
    "Lamsugod",
    "Libertad (Pob.)",
    "Little Baguio",
    "Moloy",
    "Naci",
    "Talahik",
    "Tubiala",
    "Upper Sepaka",
    "Veterans",
  ],
  "1206314000": [
    "Albagan",
    "Buto",
    "Danlag",
    "Kipalbig",
    "Lambayong",
    "Lampitak",
    "Liberty",
    "Maltana",
    "Palo",
    "Poblacion",
    "Pula-bato",
    "San Isidro",
    "Santa Cruz",
    "Tablu",
  ],
  "1206315000": [
    "Bukay Pait",
    "Cabuling",
    "Dumadalig",
    "Libas",
    "Magon",
    "Maibo",
    "Mangilala",
    "New Cuyapo",
    "New Iloilo",
    "New Lambunao",
    "Poblacion",
    "San Felipe",
    "Tinongcop",
  ],
  "1206316000": [
    "Aflek",
    "Afus",
    "Basag",
    "Datal Bob",
    "Desawo",
    "Dlanag",
    "Edwards (Pob.)",
    "Kematu",
    "Laconon",
    "Lambangan",
    "Lambuling",
    "Lamhako",
    "Lamsalome",
    "Lemsnolon",
    "Maan",
    "Malugong",
    "Mongocayo",
    "New Dumangas",
    "Poblacion",
    "Salacafe",
    "Sinolon",
    "T'bolok",
    "Talcon",
    "Talufo",
    "Tudok",
  ],
  "1206317000": [
    "Acmonan",
    "Bololmala",
    "Bunao",
    "Cebuano",
    "Crossing Rubber",
    "Kablon",
    "Kalkam",
    "Linan",
    "Lunen",
    "Miasong",
    "Palian",
    "Poblacion",
    "Polonuling",
    "Simbo",
    "Tubeng",
  ],
  "1206318000": [
    "Ambalgan",
    "Guinsang-an",
    "Katipunan",
    "Manuel Roxas",
    "Panay",
    "Poblacion",
    "Sajaneba",
    "San Isidro",
    "San Vicente",
    "Teresita",
  ],
  "1206319000": [
    "Bacdulong",
    "Denlag",
    "Halilan",
    "Hanoon",
    "Klubi",
    "Lake Lahit",
    "Lamcade",
    "Lamdalag",
    "Lamfugon",
    "Lamlahak",
    "Lower Maculan",
    "Luhib",
    "Ned",
    "Poblacion",
    "Siluton",
    "Takunel",
    "Talisay",
    "Tasiman",
    "Upper Maculan",
  ],
  "1206501000": [
    "Bai Sarifinang",
    "Biwang",
    "Busok",
    "Chua",
    "Daguma",
    "Daluga",
    "Kabulanan",
    "Kanulay",
    "Kapaya",
    "Kinayao",
    "Masiag",
    "Monteverde",
    "Poblacion",
    "Santo Niño",
    "Sison",
    "South Sepaka",
    "Sumilil",
    "Titulok",
    "Tuka",
  ],
  "1206502000": [
    "Bantangan",
    "Datablao",
    "Eday",
    "Elbebe",
    "Lasak",
    "Libertad",
    "Lomoyon",
    "Makat",
    "Maligaya",
    "Mayo",
    "Natividad",
    "Poblacion",
    "Polomolok",
    "Sinapulan",
    "Sucob",
    "Telafas",
  ],
  "1206503000": [
    "Ala",
    "Daladap",
    "Dukay",
    "Guiamalia",
    "Ilian",
    "Kangkong",
    "Laguinding",
    "Magsaysay",
    "Margues",
    "New Panay",
    "Numo",
    "Paitan",
    "Pamantingan",
    "Poblacion",
    "Sagasa",
    "Salabaca",
    "Saliao",
    "Salumping",
    "Villamor",
  ],
  "1206504000": [
    "Bambad",
    "Bual",
    "D'Lotilla",
    "Dansuli",
    "Impao",
    "Kalawag I (Pob.)",
    "Kalawag II (Pob.)",
    "Kalawag III (Pob.)",
    "Kenram",
    "Kolambog",
    "Kudanding",
    "Lagandang",
    "Laguilayan",
    "Mapantig",
    "New Pangasinan",
    "Sampao",
    "Tayugo",
  ],
  "1206505000": [
    "Bantogon",
    "Cadiz",
    "Datu Ito Andong",
    "Datu Wasay",
    "Dumangas Nuevo",
    "Hinalaan",
    "Limulan",
    "Nalilidan",
    "Obial",
    "Pag-asa",
    "Paril",
    "Poblacion",
    "Sabanal",
    "Sangay",
    "Santa Maria",
  ],
  "1206506000": [
    "Aurelio F. Freires",
    "Barurao",
    "Barurao II",
    "Basak",
    "Bolebok",
    "Bululawan",
    "Capilan",
    "Christiannuevo",
    "Datu Karon",
    "Kalamongog",
    "Keytodac",
    "Kinodalan",
    "New Calinog",
    "Nuling",
    "Pansud",
    "Pasandalan",
    "Poblacion",
    "Poblacion III",
    "Poloy-poloy",
    "Purikay",
    "Ragandang",
    "Salaman",
    "Salangsang",
    "Taguisa",
    "Tibpuan",
    "Tran",
    "Villamonte",
  ],
  "1206507000": [
    "Antong",
    "Bayasong",
    "Blingkong",
    "Lutayan Proper",
    "Maindang",
    "Mamali",
    "Manili",
    "Palavilla",
    "Sampao",
    "Sisiman",
    "Tamnag (Pob.)",
  ],
  "1206508000": [
    "Caridad",
    "Didtaras",
    "Gansing",
    "Kabulakan",
    "Kapingkong",
    "Katitisan",
    "Lagao",
    "Lilit",
    "Madanding",
    "Maligaya",
    "Mamali",
    "Matiompong",
    "Midtapok",
    "New Cebu",
    "Palumbi",
    "Pidtiguian",
    "Pimbalayan",
    "Pinguiaman",
    "Poblacion",
    "Sadsalan",
    "Seneben",
    "Sigayan",
    "Tambak",
    "Tinumigues",
    "Tumiao",
    "Udtong",
  ],
  "1206509000": [
    "Akol",
    "Badiangon",
    "Baliango",
    "Balwan",
    "Bambanen",
    "Baranayan",
    "Barongis",
    "Batang-baglas",
    "Butril",
    "Colobe",
    "Datu Maguiales",
    "Domolol",
    "Kabuling",
    "Kalibuhan",
    "Kanipaan",
    "Kidayan",
    "Kiponget",
    "Kisek",
    "Kraan",
    "Kulong-kulong",
    "Langali",
    "Libua",
    "Ligao",
    "Lopoken",
    "Lumitan",
    "Maganao",
    "Maguid",
    "Malatuneng",
    "Malisbong",
    "Medol",
    "Milbuk",
    "Mina",
    "Molon",
    "Namat Masla",
    "Napnapon",
    "Poblacion",
    "San Roque",
    "Tibuhol",
    "Wal",
    "Wasag",
  ],
  "1206510000": [
    "Bagumbayan",
    "Bannawag",
    "Bayawa",
    "C. Mangilala",
    "Estrella",
    "Kalanawe I",
    "Kalanawe II",
    "Katico",
    "Malingon",
    "Mangalen",
    "Pedtubo",
    "Poblacion",
    "Romualdez",
    "San Jose",
    "San Pedro",
    "Sinakulay",
    "Suben",
    "Tinaungan",
    "Tual",
  ],
  "1206511000": [
    "Baras",
    "Buenaflor",
    "Calean",
    "Carmen",
    "D'Ledesma",
    "Enrique J.C. Montilla",
    "Kalandagan",
    "Lancheta",
    "New Isabela",
    "New Lagao",
    "New Passi",
    "Poblacion",
    "Rajah Nuda",
    "San Antonio",
    "San Emmanuel",
    "San Pablo",
    "San Rafael",
    "Tina",
    "Upper Katungal",
    "Virginia Griño",
  ],
  "1206512000": [
    "Banali",
    "Basag",
    "Buenaflores",
    "Bugso",
    "Buklod",
    "Gapok",
    "Kadi",
    "Kapatagan",
    "Kiadsam",
    "Kuden",
    "Kulaman",
    "Lagubang",
    "Langgal",
    "Limuhay",
    "Malegdeg",
    "Midtungok",
    "Nati",
    "Sewod",
    "Tacupis",
    "Tinalon",
  ],
  "1208001000": [
    "Alegria",
    "Bagacay",
    "Baluntay",
    "Datal Anggas",
    "Domolok",
    "Kawas",
    "Ladol",
    "Maribulan",
    "Pag-Asa",
    "Paraiso",
    "Poblacion",
    "Spring",
    "Tokawal",
  ],
  "1208002000": [
    "Baliton",
    "Batotuling",
    "Batulaki",
    "Big Margus",
    "Burias",
    "Cablalan",
    "Calabanit",
    "Calpidong",
    "Congan",
    "Cross",
    "Datalbukay",
    "E. Alegado",
    "Glan Padidu",
    "Gumasa",
    "Ilaya",
    "Kaltuad",
    "Kapatan",
    "Lago",
    "Laguimit",
    "Mudan",
    "New Aklan",
    "Pangyan",
    "Poblacion",
    "Rio Del Pilar",
    "San Jose",
    "San Vicente",
    "Small Margus",
    "Sufatubo",
    "Taluya",
    "Tango",
    "Tapon",
  ],
  "1208003000": [
    "Badtasan",
    "Datu Dani",
    "Gasi",
    "Kapate",
    "Katubao",
    "Kayupo",
    "Kling",
    "Lagundi",
    "Lebe",
    "Lomuyon",
    "Luma",
    "Maligang",
    "Nalus",
    "Poblacion",
    "Salakit",
    "Suli",
    "Tablao",
    "Tamadang",
    "Tambilil",
  ],
  "1208004000": [
    "Amsipit",
    "Bales",
    "Colon",
    "Daliao",
    "Kabatiol",
    "Kablacan",
    "Kamanga",
    "Kanalo",
    "Lumasal",
    "Lumatil",
    "Malbang",
    "Nomoh",
    "Pananag",
    "Poblacion",
    "Seven Hills",
    "Tinoto",
  ],
  "1208005000": [
    "Bati-an",
    "Kalaneg",
    "Kalaong",
    "Kiambing",
    "Kiayap",
    "Mabay",
    "Maguling",
    "Malalag (Pob.)",
    "Mindupok",
    "New La Union",
    "Old Poblacion",
    "Pangi",
    "Pinol",
    "Sison",
    "Ticulab",
    "Tuanadatu",
    "Upo",
    "Wali",
    "Zion",
  ],
  "1208006000": [
    "Daan Suyan",
    "Kihan",
    "Kinam",
    "Libi",
    "Lun Masla",
    "Lun Padidu",
    "Patag",
    "Poblacion",
    "Sapu Masla",
    "Sapu Padidu",
    "Tuyan",
    "Upper Suyan",
  ],
  "1208007000": [
    "Alkikan",
    "Ampon",
    "Atlae",
    "B'Laan",
    "Banahaw",
    "Banate",
    "Datal Batong",
    "Datal Bila",
    "Datal Tampal",
    "J.P. Laurel",
    "Kawayan",
    "Kibala",
    "Kiblat",
    "Kinabalan",
    "Lower Mainit",
    "Lutay",
    "Malabod",
    "Malalag Cogon",
    "Malandag",
    "Malungon Gamay",
    "Nagpan",
    "Panamin",
    "Poblacion",
    "San Juan",
    "San Miguel",
    "San Roque",
    "Talus",
    "Tamban",
    "Upper Biangan",
    "Upper Lumabat",
    "Upper Mainit",
  ],
  "1230800000": [
    "Apopong",
    "Baluan",
    "Batomelong",
    "Buayan",
    "Bula",
    "Calumpang",
    "City Heights",
    "Conel",
    "Dadiangas East (Pob.)",
    "Dadiangas North",
    "Dadiangas South",
    "Dadiangas West",
    "Fatima",
    "Katangawan",
    "Labangal",
    "Lagao",
    "Ligaya",
    "Mabuhay",
    "Olympog",
    "San Isidro",
    "San Jose",
    "Siguel",
    "Sinawal",
    "Tambler",
    "Tinagacan",
    "Upper Labay",
  ],
};
