/** GENERATED — CAR: 1178 barangays across 77 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "1400101000": [
    "Agtangao",
    "Angad",
    "Bañacao",
    "Bangbangar",
    "Cabuloan",
    "Calaba",
    "Cosili East",
    "Cosili West",
    "Dangdangla",
    "Lingtan",
    "Lipcan",
    "Lubong",
    "Macarcarmay",
    "Macray",
    "Malita",
    "Maoay",
    "Palao",
    "Patucannay",
    "Sagap",
    "San Antonio",
    "Santa Rosa",
    "Sao-atan",
    "Sappaac",
    "Tablac",
    "Zone 1 Pob.",
    "Zone 2 Pob.",
    "Zone 3 Pob.",
    "Zone 4 Pob.",
    "Zone 5 Pob.",
    "Zone 6 Pob. ",
    "Zone 7 Pob.",
  ],
  "1400102000": [
    "Amti",
    "Bao-yan",
    "Danac East",
    "Danac West",
    "Dao-angan",
    "Dumagas",
    "Kilong-Olao",
    "Poblacion",
  ],
  "1400103000": [
    "Abang",
    "Bangbangcag",
    "Bangcagan",
    "Banglolao",
    "Bugbog",
    "Calao",
    "Dugong",
    "Labon",
    "Layugan",
    "Madalipay",
    "North Poblacion",
    "Pagala",
    "Pakiling",
    "Palaquio",
    "Patoc",
    "Quimloong",
    "Salnec",
    "San Miguel",
    "Siblong",
    "South Poblacion",
    "Tabiog",
  ],
  "1400104000": ["Ducligan", "Labaan", "Lamao (Pob.)", "Lingey"],
  "1400105000": ["Ableg", "Cabaruyan", "Pikek", "Tui (Pob.)"],
  "1400106000": [
    "Abaquid",
    "Cabaruan",
    "Caupasan (Pob.)",
    "Danglas",
    "Nagaparan",
    "Padangitan",
    "Pangal",
  ],
  "1400107000": [
    "Bayaan",
    "Cabaroan",
    "Calumbaya",
    "Cardona",
    "Isit",
    "Kimmalaba",
    "Libtec",
    "Lub-lubba",
    "Mudiit",
    "Namit-ingan",
    "Pacac",
    "Poblacion",
    "Salucag",
    "Talogtog",
    "Taping",
  ],
  "1400108000": [
    "Benben",
    "Bulbulala",
    "Buli",
    "Canan",
    "Liguis",
    "Malabbaga",
    "Mudeng",
    "Pidipid",
    "Poblacion",
    "San Gregorio",
    "Toon",
    "Udangan",
  ],
  "1400109000": [
    "Bacag",
    "Buneg",
    "Guinguinabang",
    "Lan-ag",
    "Pacoc",
    "Poblacion",
  ],
  "1400110000": [
    "Aguet",
    "Bacooc",
    "Balais",
    "Cayapa",
    "Dalaguisen",
    "Laang",
    "Lagben",
    "Laguiben",
    "Nagtipulan",
    "Nagtupacan",
    "Paganao",
    "Pawa",
    "Poblacion",
    "Presentar",
    "San Isidro",
    "Tagodtod",
    "Taping",
  ],
  "1400111000": ["Ba-i", "Collago", "Pang-ot", "Poblacion", "Pulot"],
  "1400112000": [
    "Baac",
    "Dalayap",
    "Mabungtot",
    "Malapaao",
    "Poblacion",
    "Quillat",
  ],
  "1400113000": [
    "Bonglo",
    "Bulbulala",
    "Cawayan",
    "Domenglay",
    "Lenneng",
    "Mapisla",
    "Mogao",
    "Nalbuan",
    "Poblacion",
    "Subagan",
    "Tumalip",
  ],
  "1400114000": [
    "Ampalioc",
    "Barit",
    "Gayaman",
    "Lul-luno",
    "Luzong",
    "Nagbukel-Tuquipa",
    "Poblacion",
    "Sabnangan",
  ],
  "1400115000": [
    "Bayabas",
    "Binasaran",
    "Buanao",
    "Dulao",
    "Duldulao",
    "Gacab",
    "Lat-ey",
    "Malibcong (Pob.)",
    "Mataragan",
    "Pacgued",
    "Taripan",
    "Umnap",
  ],
  "1400116000": [
    "Ayyeng (Pob.)",
    "Catacdegan Nuevo",
    "Catacdegan Viejo",
    "Luzong",
    "San Jose Norte",
    "San Jose Sur",
    "San Juan Norte",
    "San Juan Sur",
    "San Ramon East",
    "San Ramon West",
    "Santo Tomas",
  ],
  "1400117000": [
    "Dumayco",
    "Lusuac",
    "Malamsit",
    "Namarabar",
    "Patiao",
    "Poblacion",
    "Riang",
    "Santa Rosa",
    "Tattawa",
  ],
  "1400118000": [
    "Alinaya",
    "Arab",
    "Garreta",
    "Immuli",
    "Laskig",
    "Monggoc",
    "Naguirayan",
    "Pamutic",
    "Pangtud",
    "Poblacion East",
    "Poblacion West",
    "San Diego",
    "Sulbec",
    "Suyo",
    "Yuyeng",
  ],
  "1400119000": [
    "Bolbolo",
    "Brookside",
    "Dalit",
    "Dintan",
    "Gapang",
    "Kinabiti",
    "Maliplipit",
    "Nagcanasan",
    "Nanangduan",
    "Narnara",
    "Ocup",
    "Pang-ot",
    "Patad",
    "Poblacion",
    "San Juan East",
    "San Juan West",
    "South Balioag",
    "Tikitik",
    "Villavieja",
  ],
  "1400120000": [
    "Bazar",
    "Bilabila",
    "Gangal (Pob.)",
    "Maguyepyep",
    "Naguilian",
    "Saccaang",
    "Sallapadan",
    "Subusob",
    "Ud-udiao",
  ],
  "1400121000": [
    "Cabayogan",
    "Dalimag",
    "Langbaban",
    "Manayday",
    "Pantoc",
    "Poblacion",
    "Sabtan-olo",
    "San Marcial",
    "Tangbao",
  ],
  "1400122000": [
    "Abualan",
    "Ba-ug",
    "Badas",
    "Cabcaborao",
    "Colabaoan",
    "Culiong",
    "Daoidao",
    "Guimba",
    "Lam-ag",
    "Lumobang",
    "Nangobongan",
    "Pattaoig",
    "Poblacion North",
    "Poblacion South",
    "Quidaoen",
    "Sabangan",
    "Silet",
    "Supi-il",
    "Tagaytay",
  ],
  "1400123000": [
    "Labaan",
    "Palang",
    "Pantoc",
    "Poblacion",
    "Tangadan",
    "Villa Mercedes",
  ],
  "1400124000": [
    "Bagalay",
    "Basbasa",
    "Budac",
    "Bumagcat",
    "Cabaroan",
    "Deet",
    "Gaddani",
    "Patucannay",
    "Pias",
    "Poblacion",
    "Velasco",
  ],
  "1400125000": [
    "Alaoa",
    "Anayan",
    "Apao",
    "Belaat",
    "Caganayan",
    "Cogon",
    "Lanec",
    "Lapat-Balantay",
    "Naglibacan",
    "Poblacion",
  ],
  "1400126000": [
    "Alangtin",
    "Amtuagan",
    "Dilong",
    "Kili",
    "Poblacion",
    "Supo",
    "Tabacda",
    "Tiempo",
    "Tubtuba",
    "Wayangan",
  ],
  "1400127000": [
    "Ap-apaya",
    "Bol-lilising",
    "Cal-lao",
    "Lap-lapog",
    "Lumaba",
    "Poblacion",
    "Tamac",
    "Tuquib",
  ],
  "1401101000": [
    "Abiang",
    "Caliking",
    "Cattubo",
    "Naguey",
    "Paoay",
    "Pasdong",
    "Poblacion",
    "Topdac",
  ],
  "1401103000": [
    "Ampusongan",
    "Bagu",
    "Dalipey",
    "Gambang",
    "Kayapa",
    "Poblacion",
    "Sinacbat",
  ],
  "1401104000": [
    "Ambuclao",
    "Bila",
    "Bobok-Bisal",
    "Daclan",
    "Ekip",
    "Karao",
    "Nawal",
    "Pito",
    "Poblacion",
    "Tikey",
  ],
  "1401105000": [
    "Abatan",
    "Amgaleyguey",
    "Amlimay",
    "Baculongan Norte",
    "Baculongan Sur",
    "Bangao",
    "Buyacaoan",
    "Calamagan",
    "Catlubong",
    "Lengaoan",
    "Loo",
    "Natubleng",
    "Poblacion",
    "Sebang",
  ],
  "1401106000": [
    "Ampucao",
    "Dalupirip",
    "Gumatdang",
    "Loacan",
    "Poblacion",
    "Tinongdan",
    "Tuding",
    "Ucab",
    "Virac",
  ],
  "1401107000": [
    "Adaoay",
    "Anchukey",
    "Ballay",
    "Bashoy",
    "Batan",
    "Duacan",
    "Eddet",
    "Gusaran",
    "Kabayan Barrio",
    "Lusod",
    "Pacso",
    "Poblacion",
    "Tawangan",
  ],
  "1401108000": [
    "Balakbak",
    "Beleng-Belis",
    "Boklaoan",
    "Cayapes",
    "Cuba",
    "Datakan",
    "Gadang",
    "Gasweling",
    "Labueg",
    "Paykek",
    "Poblacion Central",
    "Pongayan",
    "Pudong",
    "Sagubo",
    "Taba-ao",
  ],
  "1401109000": [
    "Badeo",
    "Lubo",
    "Madaymen",
    "Palina",
    "Poblacion",
    "Sagpat",
    "Tacadang",
  ],
  "1401110000": [
    "Alapang",
    "Alno",
    "Ambiong",
    "Bahong",
    "Balili",
    "Beckel",
    "Betag",
    "Bineng",
    "Cruz",
    "Lubas",
    "Pico",
    "Poblacion",
    "Puguis",
    "Shilan",
    "Tawang",
    "Wangal",
  ],
  "1401111000": [
    "Balili",
    "Bedbed",
    "Bulalacao",
    "Cabiten",
    "Colalo",
    "Guinaoang",
    "Paco",
    "Palasaan",
    "Poblacion",
    "Sapid",
    "Tabio",
    "Taneg",
  ],
  "1401112000": [
    "Bagong",
    "Balluay",
    "Banangan",
    "Banengbeng",
    "Bayabas",
    "Kamog",
    "Pappa",
    "Poblacion",
  ],
  "1401113000": [
    "Ansagan",
    "Camp 3",
    "Camp 4",
    "Camp One",
    "Nangalisan",
    "Poblacion",
    "San Pascual",
    "Tabaan Norte",
    "Tabaan Sur",
    "Tadiangan",
    "Taloy Norte",
    "Taloy Sur",
    "Twin Peaks",
  ],
  "1401114000": [
    "Ambassador",
    "Ambongdolan",
    "Ba-ayan",
    "Basil",
    "Caponga (Pob.)",
    "Daclan",
    "Tublay Central",
    "Tuel",
  ],
  "1402701000": [
    "Amganad",
    "Anaba",
    "Balawis",
    "Banao",
    "Bangaan",
    "Batad",
    "Bocos",
    "Cambulo",
    "Ducligan",
    "Gohang",
    "Kinakin",
    "Ohaj",
    "Poblacion",
    "Poitan",
    "Pula",
    "San Fernando",
    "Tam-an",
    "View Point",
  ],
  "1402702000": [
    "Abatan",
    "Ba-ang",
    "Bangbang",
    "Bokiawan",
    "Hapao",
    "Lubo-ong",
    "Maggok",
    "Nungulunan",
    "Poblacion",
  ],
  "1402703000": [
    "Ambabag",
    "Baguinge",
    "Bokiawan",
    "Bolog",
    "Dalligan",
    "Duit",
    "Hucab",
    "Julongan",
    "Lingay",
    "Mungayang",
    "Nagacadan",
    "Pindongan",
    "Poblacion",
    "Tuplac",
  ],
  "1402704000": [
    "Abinuan",
    "Banga",
    "Boliwong",
    "Burnay",
    "Buyabuyan",
    "Caba",
    "Cudog",
    "Dulao",
    "Jucbong",
    "Luta",
    "Montabiong",
    "Olilicon",
    "Poblacion East",
    "Poblacion North",
    "Poblacion South",
    "Poblacion West",
    "Ponghal",
    "Pullaan",
    "Tungngod",
    "Tupaya",
  ],
  "1402705000": [
    "Ambasa",
    "Bimpal",
    "Hapid",
    "Holowon",
    "Lawig",
    "Lucban",
    "Mabatobato",
    "Magulon",
    "Nayon",
    "Panopdopan",
    "Payawan",
    "Pieza",
    "Poblacion East",
    "Poblacion West",
    "Pugol",
    "Salamague",
    "Sanafe",
    "Umilag",
  ],
  "1402706000": [
    "Aduyongan",
    "Alimit",
    "Ayangan",
    "Balangbang",
    "Banao",
    "Banhal",
    "Bato-Alatbang",
    "Bongan",
    "Buninan",
    "Chaya",
    "Chumang",
    "Epeng",
    "Guinihon",
    "Inwaloy",
    "Langayan",
    "Liwo",
    "Maga",
    "Magulon",
    "Mapawoy",
    "Mayoyao Proper",
    "Mongol",
    "Nalbu",
    "Nattum",
    "Palaad",
    "Poblacion",
    "Talboc",
    "Tulaed",
  ],
  "1402707000": [
    "Bangar",
    "Busilac",
    "Calimag",
    "Calupaan",
    "Caragasan",
    "Dolowog",
    "Kiling",
    "Laya",
    "Little Tadian",
    "Namillangan",
    "Namnama",
    "Ngileb",
    "Pinto",
    "Poblacion",
    "San Jose",
    "San Juan",
    "San Marcos",
    "San Quintin",
    "Santa Maria",
    "Santo Domingo",
  ],
  "1402708000": [
    "Awayan",
    "Bunhian",
    "Butac",
    "Buwag",
    "Chalalo",
    "Damag",
    "Galonogon",
    "Halag",
    "Itab",
    "Jacmal",
    "Majlong",
    "Mongayang",
    "Posnaan",
    "Ta-ang",
    "Talite",
    "Ubao",
  ],
  "1402709000": [
    "Anao",
    "Bangtinon",
    "Bitu",
    "Cababuyan",
    "Mompolia",
    "Namulditan",
    "Northern Cababuyan",
    "O-ong",
    "Piwong",
    "Poblacion",
    "Ubuag",
    "Umalbong",
  ],
  "1402710000": [
    "Ahin",
    "Ap-apid",
    "Binablayan",
    "Danggo",
    "Eheb",
    "Gumhang",
    "Impugong",
    "Luhong",
    "Tinoc",
    "Tukucan",
    "Tulludan",
    "Wangwang",
  ],
  "1402711000": [
    "Amduntog",
    "Antipolo",
    "Camandag",
    "Cawayan",
    "Hallap",
    "Liwon",
    "Namal",
    "Nungawa",
    "Panubtuban",
    "Pula",
  ],
  "1403201000": [
    "Ababa-an",
    "Balantoy",
    "Balbalan Proper",
    "Balbalasang",
    "Buaya",
    "Dao-angan",
    "Gawa-an",
    "Mabaca",
    "Maling",
    "Pantikian",
    "Poblacion",
    "Poswoy",
    "Talalang",
    "Tawang",
  ],
  "1403206000": [
    "Antonio Canao",
    "Dangoy",
    "Lower Uma",
    "Mabilong",
    "Mabongtot",
    "Poblacion",
    "Tanglag",
    "Uma del Norte",
    "Upper Uma",
  ],
  "1403208000": [
    "Ableg",
    "Bagtayan",
    "Balatoc",
    "Balenciagao Sur",
    "Balinciagao Norte",
    "Cagaluan",
    "Colayo",
    "Dalupa",
    "Dangtalan",
    "Galdang",
    "Guina-ang (Pob.)",
    "Magsilay",
    "Malucsad",
    "Pugong",
  ],
  "1403209000": [
    "Aciga",
    "Allaguia",
    "Ammacian",
    "Apatan",
    "Asibanglan",
    "Ba-ay",
    "Ballayangon",
    "Bayao",
    "Camalog",
    "Cawagayan",
    "Dugpa",
    "Katabbogan",
    "Limos",
    "Magaogao",
    "Malagnat",
    "Mapaco",
    "Pakawit",
    "Pinococ",
    "Pinukpuk Junction",
    "Socbot",
    "Taga (Pob.)",
    "Taggay",
    "Wagud",
  ],
  "1403211000": [
    "Babalag East (Pob.)",
    "Babalag West (Pob.)",
    "Bulbol",
    "Calaocan",
    "Kinama",
    "Liwan East",
    "Liwan West",
    "Macutay",
    "Romualdez",
    "San Francisco",
    "San Pascual",
    "San Pedro",
    "San Quintin",
    "Santor",
  ],
  "1403213000": [
    "Agbannawag",
    "Amlao",
    "Appas",
    "Bado Dangwa",
    "Bagumbayan",
    "Balawag",
    "Balong",
    "Bantay",
    "Bulanao",
    "Bulanao Norte",
    "Bulo",
    "Cabaritan",
    "Cabaruan",
    "Calaccad",
    "Calanan",
    "Casigayan",
    "Cudal",
    "Dagupan Centro (Pob.)",
    "Dagupan Weste",
    "Dilag",
    "Dupag",
    "Gobgob",
    "Guilayon",
    "Ipil",
    "Lacnog",
    "Lacnog West",
    "Lanna",
    "Laya East",
    "Laya West",
    "Lucog",
    "Magnao",
    "Magsaysay",
    "Malalao",
    "Malin-awa",
    "Masablang",
    "Nambaran",
    "Nambucayan",
    "Naneng",
    "New Tanglag",
    "San Juan",
    "San Julian",
    "Suyang",
    "Tuga",
  ],
  "1403214000": [
    "Anggacan",
    "Anggacan Sur",
    "Babbanoy",
    "Dacalan",
    "Dupligan",
    "Gaang",
    "Lay-asan",
    "Lower Lubo",
    "Lower Mangali",
    "Lower Taloctoc",
    "Mabaca",
    "Mangali Centro",
    "Pangol",
    "Poblacion",
    "Upper Lubo",
    "Upper Taloctoc",
  ],
  "1403215000": [
    "Ambato Legleg",
    "Bangad Centro",
    "Basao",
    "Belong Manubal",
    "Bugnay",
    "Buscalan",
    "Butbut",
    "Dananao",
    "Loccong",
    "Lower Bangad",
    "Luplupa",
    "Mallango",
    "Ngibat",
    "Old Tinglayan",
    "Poblacion",
    "Sumadel 1",
    "Sumadel 2",
    "Tulgao East",
    "Tulgao West",
    "Upper Bangad",
  ],
  "1404401000": [
    "Chupac",
    "Fiangtin",
    "Gawana (Pob.)",
    "Kaleo",
    "Latang",
    "Lias Kanluran",
    "Lias Silangan",
    "Lingoy",
    "Lunas",
    "Macalana",
    "Ogo-og",
  ],
  "1404402000": [
    "Abatan",
    "Bagnen Oriente",
    "Bagnen Proper",
    "Balintaugan",
    "Banao",
    "Bila",
    "Guinzadan Central",
    "Guinzadan Norte",
    "Guinzadan Sur",
    "Lagawa",
    "Leseb",
    "Mabaay",
    "Mayag",
    "Monamon Norte",
    "Monamon Sur",
    "Mount Data",
    "Otucan Norte",
    "Otucan Sur",
    "Poblacion",
    "Sadsadan",
    "Sinto",
    "Tapapan",
  ],
  "1404403000": [
    "Agawa",
    "Ambaguio",
    "Banguitan",
    "Besao East",
    "Besao West",
    "Catengan",
    "Gueday",
    "Kin-iway (Pob.)",
    "Lacmaan",
    "Laylaya",
    "Padangan",
    "Payeo",
    "Suquib",
    "Tamboan",
  ],
  "1404404000": [
    "Alab Oriente",
    "Alab Proper",
    "Balili",
    "Bayyo",
    "Bontoc Ili",
    "Caluttit",
    "Caneo",
    "Dalican",
    "Gonogon",
    "Guinaang",
    "Mainit",
    "Maligcong",
    "Poblacion",
    "Samoki",
    "Talubin",
    "Tocucan",
  ],
  "1404405000": [
    "Alunogan",
    "Balangao",
    "Banao",
    "Banawal",
    "Butac",
    "Maducayan",
    "Poblacion",
    "Pudo",
    "Saliok",
    "Sta. Isabel",
    "Tonglayan",
  ],
  "1404406000": [
    "Anonat",
    "Bacarri",
    "Bananao",
    "Bantay",
    "Bunot",
    "Buringal",
    "Butigue",
    "Palitud",
    "Poblacion",
  ],
  "1404407000": [
    "Bao-angan",
    "Bun-ayan",
    "Busa",
    "Camatagan",
    "Capinitan",
    "Data",
    "Gayang",
    "Lagan",
    "Losad",
    "Namatec",
    "Napua",
    "Pingad",
    "Poblacion",
    "Supang",
    "Tambingan",
  ],
  "1404408000": [
    "Anabel",
    "Bekigan",
    "Belwang",
    "Betwagan",
    "Demang",
    "Poblacion",
    "Sacasacan",
    "Saclit",
  ],
  "1404409000": [
    "Aguid",
    "Ambasing",
    "Angkeling",
    "Antadao",
    "Balugan",
    "Bangaan",
    "Dagdag (Pob.)",
    "Demang (Pob.)",
    "Fidelisan",
    "Kilong",
    "Madongo",
    "Nacagang",
    "Pide",
    "Poblacion",
    "Suyo",
    "Taccong",
    "Tanulong",
    "Tetepan Norte",
    "Tetepan Sur",
  ],
  "1404410000": [
    "Balaoa",
    "Banaao",
    "Bantey",
    "Batayan",
    "Bunga",
    "Cadad-anan",
    "Cagubatan",
    "Dacudac",
    "Duagan",
    "Kayan East",
    "Kayan West",
    "Lenga",
    "Lubon",
    "Mabalite",
    "Masla",
    "Pandayan",
    "Poblacion",
    "Sumadel",
    "Tue",
  ],
  "1408101000": [
    "Butao",
    "Cadaclan",
    "Don Roque Ablan Sr.",
    "Eleazar",
    "Eva Puzon",
    "Kabugawan",
    "Langnao",
    "Lubong",
    "Macalino",
    "Naguilian",
    "Namaltugan",
    "Poblacion",
    "Sabangan",
    "Santa Elena",
    "Santa Filomena",
    "Tanglagan",
    "Tubang",
    "Tubongan",
  ],
  "1408102000": [
    "Allangigan",
    "Banban",
    "Buluan",
    "Caglayan",
    "Calafug",
    "Cupis",
    "Daga",
    "Guinaang",
    "Guinamgaman",
    "Ili",
    "Karikitan",
    "Katablangan",
    "Malama",
    "Manag",
    "Mawigue",
    "Nabuangan",
    "Paddaoan",
    "Puguin",
    "Ripang",
    "Sacpil",
    "Talifugo",
  ],
  "1408103000": [
    "Allig",
    "Anninipan",
    "Atok",
    "Bagutong",
    "Balasi",
    "Balluyan",
    "Malayugan",
    "Mallig",
    "Malubibit Norte",
    "Malubibit Sur",
    "Poblacion East",
    "Poblacion West",
    "San Jose",
    "Santa Maria",
    "Tamalunog",
    "Upper Atok",
  ],
  "1408104000": [
    "Badduat",
    "Baliwanan",
    "Bulu",
    "Cabetayan",
    "Dagara",
    "Dibagat",
    "Karagawan",
    "Kumao",
    "Laco",
    "Lenneng",
    "Lucab",
    "Luttuacan",
    "Madatag",
    "Madduang",
    "Magabta",
    "Maragat",
    "Musimut",
    "Nagbabalayan",
    "Poblacion",
    "Tuyangan",
    "Waga",
  ],
  "1408105000": [
    "Bacsay",
    "Cagandungan",
    "Calabigan",
    "Cangisitan",
    "Capagaypayan",
    "Dagupan",
    "Lappa",
    "Luyon",
    "Marag",
    "Poblacion",
    "Quirino",
    "Salvacion",
    "San Francisco",
    "San Gregorio",
    "San Isidro Norte",
    "San Isidro Sur",
    "San Sebastian",
    "Santa Lina",
    "Shalom",
    "Tumog",
    "Turod",
    "Zumigui",
  ],
  "1408106000": [
    "Aga",
    "Alem",
    "Amado",
    "Aurora",
    "Cabatacan",
    "Cacalaggan",
    "Capannikian",
    "Doña Loreta",
    "Emilia",
    "Imelda",
    "Lower Maton",
    "Lt. Balag",
    "Lydia",
    "Malibang",
    "Mataguisi",
    "Poblacion",
    "San Antonio",
    "San Jose",
    "San Luis",
    "San Mariano",
    "Swan",
    "Upper Maton",
  ],
  "1408107000": [
    "Barocboc",
    "Consuelo",
    "Emiliana",
    "Imelda",
    "Malekkeg",
    "Marcela (Pob.)",
    "Nueva",
    "Panay",
    "San Antonio",
    "San Carlos",
    "San Juan",
    "San Mariano",
    "Sipa Proper",
  ],
  "1430300000": [
    "A. Bonifacio-Caguioa-Rimando",
    "Abanao-Zandueta-Kayong-Chugum-Otek",
    "Alfonso Tabora",
    "Ambiong",
    "Andres Bonifacio",
    "Apugan-Loakan",
    "Asin Road",
    "Atok Trail",
    "Aurora Hill Proper",
    "Aurora Hill, North Central",
    "Aurora Hill, South Central",
    "Bagong Lipunan",
    "Bakakeng Central",
    "Bakakeng North",
    "Bal-Marcoville",
    "Balsigan",
    "Bayan Park East",
    "Bayan Park Village",
    "Bayan Park West",
    "BGH Compound",
    "Brookside",
    "Brookspoint",
    "Cabinet Hill-Teacher's Camp",
    "Camdas Subdivision",
    "Camp 7",
    "Camp 8",
    "Camp Allen",
    "Campo Filipino",
    "City Camp Central",
    "City Camp Proper",
    "Country Club Village",
    "Cresencia Village",
    "Dagsian, Lower",
    "Dagsian, Upper",
    "Dizon Subdivision",
    "Dominican Hill-Mirador",
    "Dontogan",
    "DPS Area",
    "Engineers' Hill",
    "Fairview Village",
    "Ferdinand",
    "Fort del Pilar",
    "Gabriela Silang",
    "General Emilio F. Aguinaldo",
    "General Luna, Lower",
    "General Luna, Upper",
    "Gibraltar",
    "Greenwater Village",
    "Guisad Central",
    "Guisad Sorong",
    "Happy Hollow",
    "Happy Homes",
    "Harrison-Claudio Carantes",
    "Hillside",
    "Holy Ghost Extension",
    "Holy Ghost Proper",
    "Honeymoon",
    "Imelda R. Marcos",
    "Imelda Village",
    "Irisan",
    "Kabayanihan",
    "Kagitingan",
    "Kayang Extension",
    "Kayang-Hilltop",
    "Kias",
    "Legarda-Burnham-Kisad",
    "Liwanag-Loakan",
    "Loakan Proper",
    "Lopez Jaena",
    "Lourdes Subdivision Extension",
    "Lourdes Subdivision, Lower",
    "Lourdes Subdivision, Proper",
    "Lualhati",
    "Lucnab",
    "Magsaysay Private Road",
    "Magsaysay, Lower",
    "Magsaysay, Upper",
    "Malcolm Square-Perfecto",
    "Manuel A. Roxas",
    "Market Subdivision, Upper",
    "Middle Quezon Hill Subdivision",
    "Military Cut-off",
    "Mines View Park",
    "Modern Site, East",
    "Modern Site, West",
    "MRR-Queen Of Peace",
    "New Lucban",
    "Outlook Drive",
    "Pacdal",
    "Padre Burgos",
    "Padre Zamora",
    "Palma-Urbano",
    "Phil-Am",
    "Pinget",
    "Pinsao Pilot Project",
    "Pinsao Proper",
    "Poliwes",
    "Pucsusan",
    "Quezon Hill Proper",
    "Quezon Hill, Upper",
    "Quirino Hill, East",
    "Quirino Hill, Lower",
    "Quirino Hill, Middle",
    "Quirino Hill, West",
    "Quirino-Magsaysay, Upper",
    "Rizal Monument Area",
    "Rock Quarry, Lower",
    "Rock Quarry, Middle",
    "Rock Quarry, Upper",
    "Saint Joseph Village",
    "Salud Mitra",
    "San Antonio Village",
    "San Luis Village",
    "San Roque Village",
    "San Vicente",
    "Sanitary Camp, North",
    "Sanitary Camp, South",
    "Santa Escolastica",
    "Santo Rosario",
    "Santo Tomas Proper",
    "Santo Tomas School Area",
    "Scout Barrio",
    "Session Road Area",
    "Slaughter House Area",
    "SLU-SVP Housing Village",
    "South Drive",
    "Teodora Alonzo",
    "Trancoville",
    "Victoria Village",
  ],
};
