/** GENERATED — Region XIII: 1311 barangays across 73 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "1600201000": [
    "Abilan",
    "Agong-ong",
    "Alubijid",
    "Guinabsan",
    "Lower Olave",
    "Macalang",
    "Malapong",
    "Malpoc",
    "Manapa",
    "Matabao",
    "Poblacion 1",
    "Poblacion 10",
    "Poblacion 2",
    "Poblacion 3",
    "Poblacion 4",
    "Poblacion 5",
    "Poblacion 6",
    "Poblacion 7",
    "Poblacion 8",
    "Poblacion 9",
    "Rizal",
    "Sacol",
    "Sangay",
    "Simbalan",
    "Talo-ao",
  ],
  "1600203000": [
    "Antonio Luna",
    "Bay-ang",
    "Bayabas",
    "Caasinan",
    "Cabinet",
    "Calamba",
    "Calibunan",
    "Comagascas",
    "Concepcion",
    "Del Pilar",
    "Katugasan",
    "Kauswagan",
    "La Union",
    "Mabini",
    "Mahaba",
    "Poblacion 1",
    "Poblacion 10",
    "Poblacion 11",
    "Poblacion 12",
    "Poblacion 2",
    "Poblacion 3",
    "Poblacion 4",
    "Poblacion 5",
    "Poblacion 6",
    "Poblacion 7",
    "Poblacion 8",
    "Poblacion 9",
    "Puting Bato",
    "Sanghan",
    "Soriano",
    "Tolosa",
  ],
  "1600204000": [
    "Cahayagan",
    "Gosoon",
    "Manoligao",
    "Poblacion",
    "Rojales",
    "San Agustin",
    "Tagcatong",
    "Vinapor",
  ],
  "1600205000": [
    "A. Beltran",
    "Baleguian",
    "Bangonay",
    "Bunga",
    "Colorado",
    "Cuyago",
    "Libas",
    "Magdagooc",
    "Magsaysay",
    "Maraiging",
    "Poblacion",
    "San Jose",
    "San Pablo",
    "San Vicente",
    "Santo Niño",
  ],
  "1600206000": [
    "Bangayan",
    "Canaway",
    "Crossing",
    "Hinimbangan",
    "Jaliobong",
    "Mahayahay",
    "Poblacion",
    "San Isidro",
    "San Roque",
    "Sangay",
    "Songkoy",
  ],
  "1600207000": [
    "Ambacon",
    "Balungagan",
    "Bonifacio",
    "Casiklan",
    "Consorcia",
    "Durian",
    "Eduardo G. Montilla",
    "Ibuan",
    "Katipunan",
    "Lingayao",
    "Malicato",
    "Maningalao",
    "Marcos Calo",
    "Mat-i",
    "Pinana-an",
    "Poblacion",
    "Rosario",
    "San Isidro",
    "San Roque",
    "Tinucoran",
  ],
  "1600208000": [
    "Buhang",
    "Caloc-an",
    "Guiasan",
    "Marcos",
    "Poblacion",
    "Santo Niño",
    "Santo Rosario",
    "Taod-oy",
  ],
  "1600209000": [
    "Aclan",
    "Amontay",
    "Ata-atahon",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Camagong",
    "Cubi-cubi",
    "Culit",
    "Jaguimitan",
    "Kinabjangan",
    "Punta",
    "Santa Ana",
    "Talisay",
    "Triangulo",
  ],
  "1600210000": [
    "Curva",
    "Estanislao Morgado",
    "Jagupit",
    "La Paz",
    "Pangaylan-IP",
    "Poblacion I",
    "Poblacion II",
    "San Isidro",
    "Tagbuyacan",
  ],
  "1600211000": [
    "Binuangan",
    "Cabayawa",
    "Doña Rosario",
    "Doña Telesfora",
    "La Fraternidad",
    "Lawigan",
    "Poblacion 1",
    "Poblacion 2",
    "Santa Ana",
    "Tagmamarkay",
    "Tagpangahoy",
    "Tinigbasan",
    "Victory",
  ],
  "1600212000": [
    "Balangbalang",
    "Basilisa",
    "Humilog",
    "Panaytayon",
    "Poblacion I",
    "Poblacion II",
    "San Antonio",
    "Tagbongabong",
  ],
  "1600301000": [
    "Berseba",
    "Bucac",
    "Cagbas",
    "Calaitan",
    "Canayugan",
    "Charito",
    "Claro Cortez",
    "Fili",
    "Gamao",
    "Getsemane",
    "Grace Estate",
    "Hamogaway",
    "Katipunan",
    "Mabuhay",
    "Magkiangkang",
    "Mahayag",
    "Marcelina",
    "Maygatasan",
    "Montivesta",
    "Mt. Ararat",
    "Mt. Carmel",
    "Mt. Olive",
    "New Salem",
    "Noli",
    "Osmeña",
    "Panaytay",
    "Pinagalaan",
    "Poblacion",
    "Sagmone",
    "Saguma",
    "Salvacion",
    "San Agustin",
    "San Isidro",
    "San Juan",
    "Santa Irene",
    "Santa Teresita",
    "Santo Niño",
    "Taglatawan",
    "Taglibas",
    "Tagubay",
    "Verdu",
    "Villa Undayon",
    "Wawa",
  ],
  "1600302000": [
    "Bunawan Brook",
    "Consuelo",
    "Imelda",
    "Libertad",
    "Mambalili",
    "Nueva Era",
    "Poblacion",
    "San Andres",
    "San Marcos",
    "San Teodoro",
  ],
  "1600303000": [
    "Agsabu",
    "Aguinaldo",
    "Anolingan",
    "Bakingking",
    "Balubo",
    "Bentahon",
    "Bunaguit",
    "Catmonon",
    "Cebulan",
    "Concordia",
    "Crossing Luna",
    "Cubo",
    "Dakutan",
    "Duangan",
    "Guadalupe",
    "Guibonon",
    "Hawilian",
    "Kalabuan",
    "Kinamaybay",
    "Labao",
    "Langag",
    "Maasin",
    "Mac-Arthur",
    "Mahagcot",
    "Maliwanag",
    "Milagros",
    "Nato",
    "New Gingoog",
    "Odiong",
    "Oro",
    "Piglawigan",
    "Poblacion",
    "Remedios",
    "Salug",
    "San Isidro",
    "San Jose",
    "San Toribio",
    "San Vicente",
    "Santa Fe",
    "Segunda",
    "Sinakungan",
    "Tagabase",
    "Taganahaw",
    "Tagbalili",
    "Tahina",
    "Tandang Sora",
    "Valentina",
  ],
  "1600304000": [
    "Angeles",
    "Bataan",
    "Comota",
    "Halapitan",
    "Kasapa II",
    "Langasian",
    "Lydia",
    "Osmeña, Sr.",
    "Panagangan",
    "Poblacion",
    "Sabang Adgawan",
    "Sagunto",
    "San Patricio",
    "Valentina",
    "Villa Paz",
  ],
  "1600305000": [
    "Binucayan",
    "Johnson",
    "Kasapa",
    "Katipunan",
    "Kauswagan",
    "Magaud",
    "Nueva Gracia",
    "Poblacion",
    "Sabud",
    "San Isidro",
    "San Mariano",
    "San Vicente",
    "Santa Teresa",
    "Santo Niño",
    "Santo Tomas",
    "Violanta",
    "Waloe",
  ],
  "1600306000": [
    "Aurora",
    "Awa",
    "Azpetia",
    "La Caridad",
    "La Perian",
    "La Purisima",
    "La Suerte",
    "La Union",
    "Las Navas",
    "Libertad",
    "Los Arcos",
    "Lucena",
    "Mabuhay",
    "Magsaysay",
    "Mapaga",
    "Napo",
    "New Maug",
    "Patin-ay",
    "Poblacion",
    "Salimbogaon",
    "Salvacion",
    "San Joaquin",
    "San Jose",
    "San Lorenzo",
    "San Martin",
    "San Pedro",
    "San Rafael",
    "San Roque",
    "San Salvador",
    "San Vicente",
    "Santa Irene",
    "Santa Maria",
  ],
  "1600307000": [
    "Bayugan 3",
    "Cabantao",
    "Cabawan",
    "Libuac",
    "Maligaya",
    "Marfil",
    "Novele",
    "Poblacion",
    "Santa Cruz",
    "Tagbayagan",
    "Wasi-an",
  ],
  "1600308000": [
    "Alegria",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Bayugan 2",
    "Bitan-agan",
    "Borbon",
    "Buenasuerte",
    "Caimpugan",
    "Das-agan",
    "Ebro",
    "Hubang",
    "Karaus",
    "Ladgadan",
    "Lapinigan",
    "Lucac",
    "Mate",
    "New Visayas",
    "Ormaca",
    "Pasta",
    "Pisa-an",
    "Rizal",
    "San Isidro",
    "Santa Ana",
    "Tagapua",
  ],
  "1600309000": [
    "Anislagan",
    "Balit",
    "Baylo",
    "Binicalan",
    "Cecilia",
    "Coalicion",
    "Culi",
    "Dimasalang",
    "Don Alejandro",
    "Don Pedro",
    "Doña Flavia",
    "Doña Maxima",
    "Mahagsay",
    "Mahapag",
    "Mahayahay",
    "Muritula",
    "Nuevo Trabajo",
    "Poblacion",
    "Policarpo",
    "San Isidro",
    "San Pedro",
    "Santa Ines",
    "Santa Rita",
    "Santiago",
    "Wegguam",
  ],
  "1600310000": [
    "Angas",
    "Aurora",
    "Awao",
    "Concepcion",
    "Pag-asa",
    "Patrocinio",
    "Poblacion",
    "San Jose",
    "Santa Isabel",
    "Sayon",
    "Tapaz",
  ],
  "1600311000": [
    "Batucan",
    "BuenaGracia",
    "Causwagan",
    "Culi",
    "Del Monte",
    "Desamparados",
    "La Flora",
    "Labnig",
    "Maharlika",
    "Marbon",
    "Sabang Gibung",
    "San Agustin (Pob.)",
    "San Isidro (Pob.)",
    "San Nicolas (Pob.)",
    "Zamora",
    "Zillovia",
  ],
  "1600312000": [
    "Basa",
    "Cebolin",
    "Cuevas",
    "Kapatungan",
    "Langkila-an",
    "Manat",
    "New Visayas",
    "Pangyan",
    "Poblacion",
    "Pulang-lupa",
    "Salvacion",
    "San Ignacio",
    "San Isidro",
    "San Roque",
    "Santa Maria",
    "Tudela",
  ],
  "1600313000": [
    "Anitap",
    "Bacay II",
    "Binongan",
    "Caigangan",
    "Candiis",
    "Del Monte",
    "Don Mateo",
    "Katipunan",
    "La Fortuna",
    "Limot",
    "Magsaysay",
    "Masayan",
    "Poblacion",
    "Sampaguita",
    "San Gabriel",
    "Santa Cruz",
    "Santa Emelia",
    "Sawagan",
    "Sinobong",
    "Sisimon",
  ],
  "1600314000": [
    "Afga",
    "Anahawan",
    "Banagbanag",
    "Del Rosario",
    "El Rio",
    "Ilihan",
    "Kauswagan",
    "Kioya",
    "Kolambugan",
    "Magkalape",
    "Magsaysay",
    "Mahayahay",
    "New Tubigon",
    "Padiay",
    "Perez",
    "Poblacion",
    "San Isidro",
    "San Vicente",
    "Santa Cruz",
    "Santa Maria",
    "Sinai",
    "Tabon-tabon",
    "Tag-uyango",
    "Villangit",
  ],
  "1606701000": [
    "Alipao",
    "Anahaw",
    "Budlingin",
    "Camp Eduard",
    "Ferlda",
    "Gamuton",
    "Julio Ouano (Pob.)",
    "Ombong",
    "Poblacion",
    "Pongtud",
    "San Juan",
    "San Pedro",
  ],
  "1606702000": [
    "Cabugao",
    "Cambuayon",
    "Campo",
    "Dugsangon",
    "Pautao",
    "Payapag",
    "Poblacion",
    "Pungtod",
    "Santo Rosario",
  ],
  "1606704000": [
    "Baybay",
    "Bitaug",
    "Matin-ao",
    "Poblacion 1",
    "Poblacion 2",
    "San Mateo",
  ],
  "1606706000": [
    "Bagakay",
    "Cabugo",
    "Cagdianao",
    "Daywan",
    "Hayanggabon",
    "Ladgaron (Pob.)",
    "Lapinigan",
    "Magallanes",
    "Panatao",
    "Sapa",
    "Taganito",
    "Tayaga",
    "Urbiztondo",
    "Wangke",
  ],
  "1606707000": [
    "Bagakay",
    "Barangay 1 (Pob.)",
    "Barangay 10 (Pob.)",
    "Barangay 11 (Pob.)",
    "Barangay 12 (Pob.)",
    "Barangay 13 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Barangay 9 (Pob.)",
    "Buenavista",
    "Cabawa",
    "Cambas-ac",
    "Consolacion",
    "Corregidor",
    "Dagohoy",
    "Don Paulino",
    "Jubang",
    "Montserrat",
    "Osmeña",
    "San Carlos",
    "San Miguel",
    "Santa Fe",
    "Santa Felomina",
    "Union",
  ],
  "1606708000": [
    "Antipolo",
    "Bagakay",
    "Bitoon",
    "Cabugao",
    "Cancohoy",
    "Caub",
    "Del Carmen (Pob.)",
    "Domoyog",
    "Esperanza",
    "Halian",
    "Jamoyaon",
    "Katipunan",
    "Lobogon",
    "Mabuhay",
    "Mahayahay",
    "Quezon",
    "San Fernando",
    "San Jose (Pob.)",
    "Sayak",
    "Tuboran",
  ],
  "1606710000": [
    "Anajawan",
    "Cabitoonan",
    "Catangnan",
    "Consuelo",
    "Corazon",
    "Daku",
    "La Januza",
    "Libertad",
    "Magsaysay",
    "Malinao",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Poblacion V",
    "Santa Cruz",
    "Santa Fe",
    "Suyangan",
    "Tawin-tawin",
  ],
  "1606711000": [
    "Alambique (Pob.)",
    "Anibongan",
    "Cam-boayon",
    "Camam-onan",
    "Ipil (Pob.)",
    "Lahi",
    "Mahanub",
    "Poniente",
    "San Antonio",
    "San Isidro",
    "Sico-sico",
    "Villaflor",
    "Villafranca",
  ],
  "1606714000": [
    "Binga",
    "Bobona-on",
    "Cantugas",
    "Dayano",
    "Mabini",
    "Magpayang",
    "Magsaysay (Pob.)",
    "Mansayao",
    "Marayag",
    "Matin-ao",
    "Paco",
    "Quezon (Pob.)",
    "Roxas",
    "San Francisco",
    "San Isidro",
    "San Jose",
    "Siana",
    "Silop",
    "Tagbuyawan",
    "Tapi-an",
    "Tolingon",
  ],
  "1606715000": [
    "Bunyasan",
    "Cagtinae",
    "Can-aga",
    "Cansayong",
    "Cantapoy",
    "Cayawan",
    "Doro",
    "Hanagdong",
    "Karihatag",
    "Masgad",
    "Pili",
    "San Isidro (Pob.)",
    "Tinago",
    "Villariza",
  ],
  "1606716000": [
    "Asinan (Pob.)",
    "Caridad",
    "Centro (Pob.)",
    "Consolacion",
    "Datu",
    "Dayaohay",
    "Jaboy",
    "Katipunan",
    "Maasin",
    "Mabini",
    "Mabuhay",
    "Pilaring (Pob.)",
    "Punta (Pob.)",
    "Salvacion",
    "San Roque",
  ],
  "1606717000": [
    "Amoslog",
    "Anislagan",
    "Bad-as",
    "Boyongan",
    "Bugas-bugas",
    "Central (Pob.)",
    "Ellaperal",
    "Ipil (Pob.)",
    "Lakandula",
    "Mabini",
    "Macalaya",
    "Magsaysay (Pob.)",
    "Magupange",
    "Pananay-an",
    "Panhutongan",
    "San Isidro",
    "Sani-sani",
    "Santa Cruz",
    "Suyoc",
    "Tagbongabong",
  ],
  "1606718000": [
    "Bongdo",
    "Maribojoc",
    "Nuevo Campo",
    "San Juan",
    "Santa Cruz (Pob.)",
    "Talisay (Pob.)",
  ],
  "1606719000": [
    "Amontay",
    "Balite",
    "Banbanon",
    "Diaz",
    "Honrado",
    "Jubgan",
    "Linongganan",
    "Macopa",
    "Magtangale",
    "Oslao",
    "Poblacion",
  ],
  "1606720000": [
    "Buhing Calipay",
    "Del Carmen (Pob.)",
    "Del Pilar",
    "Macapagal",
    "Pacifico",
    "Pelaez",
    "Roxas",
    "San Miguel",
    "Santa Paz",
    "Santo Niño",
    "Tambacan",
    "Tigasao",
  ],
  "1606721000": [
    "Abad Santos",
    "Alegria",
    "Bailan",
    "Garcia",
    "Libertad",
    "Mabini",
    "Mabuhay (Pob.)",
    "Magsaysay",
    "Rizal",
    "T. Arlan (Pob.)",
    "Tangbo",
  ],
  "1606722000": [
    "Biyabid",
    "Gacepan",
    "Ima",
    "Lower Patag",
    "Mabuhay",
    "Mayag",
    "Poblacion",
    "San Isidro",
    "San Pablo",
    "Tagbayani",
    "Tinogpahan",
    "Upper Patag",
  ],
  "1606723000": [
    "Albino Taruc",
    "Del Pilar",
    "Helene",
    "Honrado",
    "Navarro (Pob.)",
    "Nueva Estrella",
    "Pamosaingan",
    "Rizal (Pob.)",
    "Salog",
    "San Roque",
    "Santa Cruz",
    "Sering",
    "Songkoy",
    "Sudlon",
  ],
  "1606724000": [
    "Alang-alang",
    "Alegria",
    "Anomar",
    "Aurora",
    "Balibayon",
    "Baybay",
    "Bilabid",
    "Bitaugan",
    "Bonifacio",
    "Buenavista",
    "Cabongbongan",
    "Cagniog",
    "Cagutsan",
    "Canlanipa",
    "Cantiasay",
    "Capalayan",
    "Catadman",
    "Danao",
    "Danawan",
    "Day-asan",
    "Ipil",
    "Libuac",
    "Lipata",
    "Lisondra",
    "Luna",
    "Mabini",
    "Mabua",
    "Manyagao",
    "Mapawa",
    "Mat-i",
    "Nabago",
    "Nonoc",
    "Orok",
    "Poctoy",
    "Punta Bilar",
    "Quezon",
    "Rizal",
    "Sabang",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Pedro",
    "San Roque",
    "Serna",
    "Sidlakan",
    "Silop",
    "Sugbay",
    "Sukailang",
    "Taft (Pob.)",
    "Talisay",
    "Togbongon",
    "Trinidad",
    "Washington (Pob.)",
    "Zaragoza",
  ],
  "1606725000": [
    "Aurora (Pob.)",
    "Azucena (Pob.)",
    "Banban",
    "Cawilan",
    "Fabio",
    "Himamaug",
    "Laurel",
    "Lower Libas",
    "Opong",
    "Patino",
    "Sampaguita (Pob.)",
    "Talavera",
    "Union",
    "Upper Libas",
  ],
  "1606727000": [
    "Capayahan",
    "Cawilan",
    "Del Rosario",
    "Marga",
    "Motorpool",
    "Poblacion",
    "San Isidro",
    "San Pablo",
    "Timamana",
  ],
  "1606801000": [
    "Amaga",
    "Bahi",
    "Cabacungan",
    "Cambagang",
    "Causwagan",
    "Dapdap",
    "Dughan",
    "Gamut",
    "Javier",
    "Kinayan",
    "Mamis",
    "Poblacion",
    "Rizal",
    "San Jose",
    "San Roque",
    "San Vicente",
    "Sua",
    "Sudlon",
    "Tambis",
    "Unidad",
    "Wakat",
  ],
  "1606802000": [
    "Amag",
    "Balete (Pob.)",
    "Cabugo",
    "Cagbaoto",
    "La Paz",
    "Magobawok",
    "Panaosawon",
  ],
  "1606803000": [
    "Bucto",
    "Burboanan",
    "Caguyao",
    "Coleto",
    "Comawas",
    "Kahayag",
    "Labisma",
    "Lawigan",
    "Maharlika",
    "Mangagoy",
    "Mone",
    "Pamanlinan",
    "Pamaypayan",
    "Poblacion",
    "San Antonio",
    "San Fernando",
    "San Isidro",
    "San Jose",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Sibaroy",
    "Tabon",
    "Tumanan",
  ],
  "1606804000": [
    "Aras-Asan",
    "Bacolod",
    "Bitaugan East",
    "Bitaugan West",
    "La Purisima",
    "Lactudan",
    "Mat-e",
    "Poblacion",
    "Tawagan",
    "Tubo-tubo",
    "Unidad",
  ],
  "1606805000": [
    "Bugsukan",
    "Buntalid",
    "Cabangahan",
    "Cabas-an",
    "Calagdaan",
    "Consuelo",
    "General Island",
    "Lininti-an (Pob.)",
    "Lobo",
    "Magasang",
    "Magosilom (Pob.)",
    "Pag-Antayan",
    "Palasao",
    "Parang",
    "San Pedro",
    "Tapi",
    "Tigabong",
  ],
  "1606806000": [
    "Antao",
    "Cancavan",
    "Carmen (Pob.)",
    "Esperanza",
    "Hinapoyan",
    "Puyat",
    "San Vicente",
    "Santa Cruz",
  ],
  "1606807000": [
    "Adlay",
    "Babuyan",
    "Bacolod",
    "Baybay (Pob.)",
    "Bon-ot",
    "Caglayag",
    "Dahican",
    "Doyos (Pob.)",
    "Embarcadero (Pob.)",
    "Gamuton",
    "Panikian",
    "Pantukan",
    "Saca (Pob.)",
    "Tag-Anito",
  ],
  "1606808000": [
    "Balibadon",
    "Burgos",
    "Capandan",
    "Mabahin",
    "Madrelino",
    "Manlico",
    "Matho",
    "Poblacion",
    "Tag-Anongan",
    "Tigao",
    "Tuboran",
    "Uba",
  ],
  "1606809000": [
    "Baculin",
    "Benigno Aquino",
    "Bigaan",
    "Cambatong",
    "Campa",
    "Dugmanon",
    "Harip",
    "La Casa (Pob.)",
    "Loyola",
    "Maligaya",
    "Pagtigni-an",
    "Pocto",
    "Port Lamon",
    "Roxas",
    "San Juan",
    "Sasa",
    "Tagasaka",
    "Tagbobonga",
    "Talisay",
    "Tarusan",
    "Tidman",
    "Tiwi",
    "Zone II (Pob.)",
    "Zone III Maharlika (Pob.)",
  ],
  "1606810000": [
    "Agsam",
    "Bocawe",
    "Bunga",
    "Gamuton",
    "Habag",
    "Mampi",
    "Nurcia",
    "Pakwan",
    "Sibahay",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)",
  ],
  "1606811000": [
    "Anibongan",
    "Ban-as",
    "Banahao",
    "Baucawe",
    "Diatagon",
    "Ganayon",
    "Liatimco",
    "Manyayay",
    "Payasan",
    "Poblacion",
    "Saint Christine",
    "San Isidro",
    "San Pedro",
  ],
  "1606812000": [
    "Anibongan",
    "Barcelona",
    "Bogak",
    "Bongan",
    "Handamayan",
    "Mahayahay",
    "Mandus",
    "Mansa-ilao",
    "Pagtila-an",
    "Palo Alto",
    "Poblacion",
    "Rajah Cabungso-an",
    "Sabang",
    "Salvacion",
    "San Roque",
    "Tagpoporan",
    "Union",
    "Valencia",
  ],
  "1606813000": [
    "Bagsac",
    "Bayogo",
    "Linibonan",
    "Magsaysay",
    "Manga",
    "Panayogon",
    "Patong Patong",
    "Quirino (Pob.)",
    "San Antonio",
    "San Juan",
    "San Roque",
    "San Vicente",
    "Songkit",
    "Union",
  ],
  "1606814000": [
    "Alegria",
    "Amontay",
    "Antipolo",
    "Arorogan",
    "Bayan",
    "Mahaba",
    "Mararag",
    "Poblacion",
    "San Antonio",
    "San Isidro",
    "San Pedro",
    "Santa Cruz",
  ],
  "1606815000": [
    "Bretania",
    "Buatong",
    "Buhisan",
    "Gata",
    "Hornasan",
    "Janipaan",
    "Kauswagan",
    "Oteiza",
    "Poblacion",
    "Pong-on",
    "Pongtod",
    "Salvacion",
    "Santo Niño",
  ],
  "1606816000": [
    "Bagyang",
    "Baras",
    "Bitaugan",
    "Bolhoon",
    "Calatngan",
    "Carromata",
    "Castillo",
    "Libas Gua",
    "Libas Sud",
    "Magroyong",
    "Mahayag",
    "Patong",
    "Poblacion",
    "Sagbayan",
    "San Roque",
    "Siagao",
    "Tina",
    "Umalag",
  ],
  "1606817000": [
    "Batunan",
    "Carpenito",
    "Doña Carmen",
    "Hinagdanan",
    "Kahayagan",
    "Lago",
    "Maglambing",
    "Maglatab",
    "Magsaysay",
    "Malixi",
    "Manambia",
    "Osmeña",
    "Poblacion",
    "Quezon",
    "San Vicente",
    "Santa Cruz",
    "Santa Fe",
    "Santa Juana",
    "Santa Maria",
    "Sayon",
    "Soriano",
    "Tagongon",
    "Trinidad",
    "Ugoban",
    "Villaverde",
  ],
  "1606818000": [
    "Alba",
    "Anahao Bag-o",
    "Anahao Daan",
    "Badong",
    "Bajao",
    "Bangsud",
    "Cabangahan",
    "Cagdapao",
    "Camagong",
    "Caras-an",
    "Cayale",
    "Dayo-an",
    "Gamut",
    "Jubang",
    "Kinabigtasan",
    "Layog",
    "Lindoy",
    "Mercedes",
    "Purisima (Pob.)",
    "Sumo-sumo",
    "Umbay",
    "Unaban",
    "Unidos",
    "Victoria",
  ],
  "1606819000": [
    "Awasian",
    "Bagong Lungsod (Pob.)",
    "Bioto",
    "Bongtod Pob.",
    "Buenavista",
    "Dagocdoc (Pob.)",
    "Mabua",
    "Mabuhay",
    "Maitum",
    "Maticdum",
    "Pandanon",
    "Pangi",
    "Quezon",
    "Rosario",
    "Salvacion",
    "San Agustin Norte",
    "San Agustin Sur",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "Telaje",
  ],
  "1608501000": [
    "Benglen",
    "Catadman",
    "Columbus",
    "Coring",
    "Cortes",
    "Diegas",
    "Doña Helene",
    "Edera",
    "Ferdinand",
    "Geotina",
    "Imee",
    "Melgar",
    "Montag",
    "Navarro",
    "New Nazareth",
    "Poblacion",
    "Puerto Princesa",
    "Rita Glenda",
    "Roma",
    "Roxas",
    "Santa Monica",
    "Santo Niño",
    "Sering",
    "Sombrado",
    "Tag-abaca",
    "Villa Ecleo",
    "Villa Pantinople",
  ],
  "1608502000": [
    "Boa",
    "Cabunga-an",
    "Del Pilar",
    "Laguna",
    "Legaspi",
    "Ma-atas",
    "Mabini",
    "Nueva Estrella",
    "Poblacion",
    "R. Ecleo, Sr.",
    "San Jose",
    "Santa Rita",
    "Tigbao",
    "Valencia",
  ],
  "1608503000": [
    "Bagumbayan",
    "Cab-ilan",
    "Cabayawan",
    "Cayetano",
    "Escolta (Pob.)",
    "Gomez",
    "Justiniana Edera",
    "Magsaysay",
    "Mauswagon (Pob.)",
    "New Mabuhay",
    "Wadas",
    "White Beach (Pob.)",
  ],
  "1608504000": [
    "Albor (Pob.)",
    "Arellano",
    "Bayanihan",
    "Doña Helen",
    "Garcia",
    "General Aguinaldo",
    "Kanihaan",
    "Llamera",
    "Magsaysay",
    "Osmeña",
    "Plaridel",
    "Quezon",
    "Rosita",
    "San Antonio (Pob.)",
    "San Jose",
    "Santo Niño",
  ],
  "1608505000": [
    "Carmen (Pob.)",
    "Esperanza",
    "Ferdinand",
    "Helene",
    "Liberty",
    "Magsaysay",
    "Panamaon",
    "San Juan (Pob.)",
    "Santa Cruz (Pob.)",
    "Santiago (Pob.)",
  ],
  "1608506000": [
    "Aurelio",
    "Cuarinta",
    "Don Ruben Ecleo",
    "Jacquez",
    "Justiniana Edera",
    "Luna",
    "Mahayahay",
    "Matingbe",
    "San Jose (Pob.)",
    "San Juan",
    "Santa Cruz",
    "Wilson",
  ],
  "1608507000": [
    "Diaz",
    "Imelda",
    "Mabini",
    "Malinao",
    "Navarro",
    "Roxas",
    "San Roque (Pob.)",
    "San Vicente (Pob.)",
    "Santa Cruz (Pob.)",
  ],
  "1630400000": [
    "Agao Pob.",
    "Agusan Pequeño",
    "Ambago",
    "Amparo",
    "Ampayon",
    "Anticala",
    "Antongalon",
    "Aupagan",
    "Baan KM 3",
    "Baan Riverside Pob.",
    "Babag",
    "Bading Pob.",
    "Bancasi",
    "Banza",
    "Baobaoan",
    "Basag",
    "Bayanihan Pob.",
    "Bilay",
    "Bit-os",
    "Bitan-agan",
    "Bobon",
    "Bonbon",
    "Bugabus",
    "Bugsukan",
    "Buhangin Pob.",
    "Cabcabon",
    "Camayahan",
    "Dagohoy Pob.",
    "Dankias",
    "De Oro",
    "Diego Silang Pob.",
    "Don Francisco",
    "Doongan",
    "Dulag",
    "Dumalagan",
    "Florida",
    "Golden Ribbon Pob.",
    "Holy Redeemer Pob.",
    "Humabon Pob.",
    "Imadejas Pob.",
    "Jose Rizal Pob.",
    "Kinamlutan",
    "Lapu-lapu Pob.",
    "Lemon",
    "Leon Kilat Pob.",
    "Libertad",
    "Limaha Pob.",
    "Los Angeles",
    "Lumbocan",
    "Maguinda",
    "Mahay",
    "Mahogany Pob.",
    "Maibu",
    "Mandamo",
    "Manila de Bugabus",
    "Maon Pob.",
    "Masao",
    "Maug",
    "New Society Village Pob.",
    "Nong-nong",
    "Obrero Pob.",
    "Ong Yiu Pob.",
    "Pagatpatan",
    "Pangabugan",
    "Pianing",
    "Pigdaulan",
    "Pinamanculan",
    "Port Poyohon Pob.",
    "Rajah Soliman Pob.",
    "Salvacion",
    "San Ignacio Pob.",
    "San Mateo",
    "San Vicente",
    "Santo Niño",
    "Sikatuna Pob.",
    "Silongan Pob.",
    "Sumile",
    "Sumilihon",
    "Tagabaca",
    "Taguibo",
    "Taligaman",
    "Tandang Sora Pob.",
    "Tiniwisan",
    "Tungao",
    "Urduja Pob.",
    "Villa Kananga",
  ],
};
