/** GENERATED — Region IV-B: 1460 barangays across 73 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "1704001000": [
    "Agot",
    "Agumaymayan",
    "Amoingon",
    "Apitong",
    "Balagasan",
    "Balaring",
    "Balimbing",
    "Balogo",
    "Bamban",
    "Bangbangalon",
    "Bantad",
    "Bantay",
    "Bayuti",
    "Binunga",
    "Boi",
    "Boton",
    "Buliasnin",
    "Bunganay",
    "Caganhao",
    "Canat",
    "Catubugan",
    "Cawit",
    "Daig",
    "Daypay",
    "Duyay",
    "Hinapulan",
    "Ihatub",
    "Isok I (Pob.)",
    "Isok II Pob.",
    "Laylay",
    "Lupac",
    "Mahinhin",
    "Mainit",
    "Malbog",
    "Maligaya",
    "Malusak (Pob.)",
    "Mansiwat",
    "Mataas Na Bayan (Pob.)",
    "Maybo",
    "Mercado (Pob.)",
    "Murallon (Pob.)",
    "Ogbac",
    "Pawa",
    "Pili",
    "Poctoy",
    "Poras",
    "Puting Buhangin",
    "Puyog",
    "Sabong",
    "San Miguel (Pob.)",
    "Santol",
    "Sawi",
    "Tabi",
    "Tabigue",
    "Tagwak",
    "Tambunan",
    "Tampus (Pob.)",
    "Tanza",
    "Tugos",
    "Tumagabok",
    "Tumapon",
  ],
  "1704002000": [
    "Bagacay",
    "Bagtingon",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Bicas-bicas",
    "Caigangan",
    "Daykitin",
    "Libas",
    "Malbog",
    "Sihi",
    "Timbo",
    "Tungib-Lipata",
    "Yook",
  ],
  "1704003000": [
    "Antipolo",
    "Bachao Ibaba",
    "Bachao Ilaya",
    "Bacongbacong",
    "Bahi",
    "Bangbang",
    "Banot",
    "Banuyo",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Bognuyan",
    "Cabugao",
    "Dawis",
    "Dili",
    "Libtangin",
    "Mahunig",
    "Mangiliol",
    "Masiga",
    "Matandang Gasan",
    "Pangi",
    "Pinggan",
    "Tabionan",
    "Tapuyan",
    "Tiguion",
  ],
  "1704004000": [
    "Anapog-Sibucao",
    "Argao",
    "Balanacan",
    "Banto",
    "Bintakay",
    "Bocboc",
    "Butansapa",
    "Candahon",
    "Capayang",
    "Danao",
    "Dulong Bayan (Pob.)",
    "Gitnang Bayan (Pob.)",
    "Guisian",
    "Hinadharan",
    "Hinanggayon",
    "Ino",
    "Janagdong",
    "Lamesa",
    "Laon",
    "Magapua",
    "Malayak",
    "Malusak",
    "Mampaitan",
    "Mangyan-Mababad",
    "Market Site (Pob.)",
    "Mataas Na Bayan",
    "Mendez",
    "Nangka I",
    "Nangka II",
    "Paye",
    "Pili",
    "Puting Buhangin",
    "Sayao",
    "Silangan",
    "Sumangga",
    "Tarug",
    "Villa Mendez (Pob.)",
  ],
  "1704005000": [
    "Alobo",
    "Angas",
    "Aturan",
    "Bagong Silang Pob.",
    "Baguidbirin",
    "Baliis",
    "Balogo",
    "Banahaw Pob.",
    "Bangcuangan",
    "Banogbog",
    "Biga",
    "Botilao",
    "Buyabod",
    "Dating Bayan",
    "Devilla",
    "Dolores",
    "Haguimit",
    "Hupi",
    "Ipil",
    "Jolo",
    "Kaganhao",
    "Kalangkang",
    "Kamandugan",
    "Kasily",
    "Kilo-kilo",
    "Kinyaman",
    "Labo",
    "Lamesa",
    "Landy",
    "Lapu-lapu Pob.",
    "Libjo",
    "Lipa",
    "Lusok",
    "Maharlika Pob.",
    "Makulapnit",
    "Maniwaya",
    "Manlibunan",
    "Masaguisi",
    "Masalukot",
    "Matalaba",
    "Mongpong",
    "Morales",
    "Napo",
    "Pag-Asa Pob.",
    "Pantayin",
    "Polo",
    "Pulong-Parang",
    "Punong",
    "San Antonio",
    "San Isidro",
    "Tagum",
    "Tamayo",
    "Tambangan",
    "Tawiran",
    "Taytay",
  ],
  "1704006000": [
    "Bangwayin",
    "Bayakbakin",
    "Bolo",
    "Bonliw",
    "Buangan",
    "Cabuyo",
    "Cagpo",
    "Dampulan",
    "Kay Duke",
    "Mabuhay",
    "Makawayan",
    "Malibago",
    "Malinao",
    "Maranlig",
    "Marlangga",
    "Matuyatuya",
    "Nangka",
    "Pakaskasan",
    "Payanas",
    "Poblacion",
    "Poctoy",
    "Sibuyao",
    "Suha",
    "Talawan",
    "Tigwi",
  ],
  "1705101000": [
    "Armado",
    "Balao",
    "Cabacao",
    "Lumangbayan",
    "Poblacion",
    "San Vicente",
    "Santa Maria",
    "Tibag",
    "Udalo",
    "Wawa",
  ],
  "1705102000": [
    "Concepcion",
    "Iriron",
    "Malpalon",
    "New Dagupan",
    "Poblacion",
    "Poypoy",
    "Tanyag",
  ],
  "1705103000": [
    "Agkawayan",
    "Ambil",
    "Balikyas",
    "Bonbon (Pob.)",
    "Bulacan",
    "Burol",
    "Guitna (Pob.)",
    "Kanluran (Pob.)",
    "Talaotao",
  ],
  "1705104000": [
    "Araw At Bituin (Pob.)",
    "Bagong Sikat (Pob.)",
    "Banaag ng Pag-asa (Pob.)",
    "Binakas",
    "Cabra",
    "Likas Ng Silangan (Pob.)",
    "Maginhawa (Pob.)",
    "Maligaya",
    "Maliig",
    "Ninikat Ng Pag-Asa (Pob.)",
    "Paraiso (Pob.)",
    "Sorville (Pob.)",
    "Tagbac",
    "Tangal",
    "Tilik",
    "Vigo",
  ],
  "1705105000": [
    "Alibog",
    "Caguray",
    "Calawag",
    "Gapasan",
    "Laste",
    "Lourdes",
    "Nicolas",
    "Paclolo",
    "Poblacion",
    "Purnaga",
    "Santa Teresa",
    "Sibalat",
  ],
  "1705106000": [
    "Balansay",
    "Fatima",
    "Payompon",
    "Poblacion 1",
    "Poblacion 2",
    "Poblacion 3",
    "Poblacion 4",
    "Poblacion 5",
    "Poblacion 6",
    "Poblacion 7",
    "Poblacion 8",
    "San Luis",
    "Talabaan",
    "Tangkalan",
    "Tayamaan",
  ],
  "1705107000": [
    "Alipaoy",
    "Bagong Silang Pob.",
    "Handang Tumulong Pob.",
    "Harrison",
    "Lumangbayan",
    "Mananao",
    "Mapalad Pob.",
    "Marikit",
    "Pag-Asa Ng Bayan Pob.",
    "San Jose Pob.",
    "Silahis Ng Pag-Asa Pob.",
    "Tubili",
  ],
  "1705108000": [
    "Adela",
    "Aguas",
    "Magsikap",
    "Malawaan",
    "Manoot",
    "Pitogo",
    "Rizal",
    "Rumbang",
    "Salvacion",
    "San Pedro",
    "Santo Niño",
  ],
  "1705109000": [
    "Batong Buhay",
    "Buenavista",
    "Burgos",
    "Claudio Salgado",
    "General Emilio Aguinaldo",
    "Ibud",
    "Ilvita",
    "Lagnas",
    "Ligaya",
    "Malisbong",
    "Paetan",
    "Pag-Asa",
    "Poblacion",
    "San Agustin",
    "San Francisco",
    "San Nicolas",
    "San Vicente",
    "Santa Lucia",
    "Santo Niño",
    "Tagumpay",
    "Tuban",
    "Victoria",
  ],
  "1705110000": [
    "Ambulong",
    "Ansiray",
    "Bagong Sikat",
    "Bangkal",
    "Barangay 1 (Pob.)",
    "Barangay 2 (Pob.)",
    "Barangay 3 (Pob.)",
    "Barangay 4 (Pob.)",
    "Barangay 5 (Pob.)",
    "Barangay 6 (Pob.)",
    "Barangay 7 (Pob.)",
    "Barangay 8 (Pob.)",
    "Batasan",
    "Bayotbot",
    "Bubog",
    "Buri",
    "Camburay",
    "Caminawit",
    "Catayungan",
    "Central",
    "Iling Proper",
    "Inasakan",
    "Ipil",
    "La Curva",
    "Labangan Iling",
    "Labangan Poblacion",
    "Mabini",
    "Magbay",
    "Mangarin",
    "Mapaya",
    "Monte Claro",
    "Murtha",
    "Naibuan",
    "Natandol",
    "Pag-Asa",
    "Pawican",
    "San Agustin",
    "San Isidro",
    "San Roque",
  ],
  "1705111000": [
    "Alacaak",
    "Barahan",
    "Casague",
    "Dayap",
    "Kurtinganan",
    "Lumangbayan",
    "Mulawin",
    "Pinagturilan",
    "Poblacion I",
    "Poblacion II",
    "San Vicente",
  ],
  "1705201000": [
    "Alag",
    "Bangkatan",
    "Baras",
    "Bayanan",
    "Burbuli",
    "Catwiran I",
    "Catwiran II",
    "Dulangan I",
    "Dulangan II",
    "Lantuyang",
    "Lumang Bayan",
    "Malapad",
    "Mangangan I",
    "Mangangan II",
    "Mayabig",
    "Pambisan",
    "Poblacion",
    "Pulang-Tubig",
    "Putican-Cabulo",
    "San Andres",
    "San Ignacio",
    "Santa Cruz",
    "Santa Rosa I",
    "Santa Rosa II",
    "Tabon-tabon",
    "Tagumpay",
    "Water",
  ],
  "1705202000": [
    "Alcadesma",
    "Bato",
    "Conrazon",
    "Malo",
    "Manihala",
    "Pag-Asa",
    "Poblacion",
    "Proper Bansud",
    "Proper Tiguisan",
    "Rosacara",
    "Salcedo",
    "Sumagui",
    "Villa Pag-Asa",
  ],
  "1705203000": [
    "Anilao",
    "Aplaya",
    "Bagumbayan I",
    "Bagumbayan II",
    "Batangan",
    "Bukal",
    "Camantigue",
    "Carmundo",
    "Cawayan",
    "Dayhagan",
    "Formon",
    "Hagan",
    "Hagupit",
    "Ipil",
    "Kaligtasan",
    "Labasan",
    "Labonan",
    "Libertad",
    "Lisap",
    "Luna",
    "Malitbog",
    "Mapang",
    "Masaguisi",
    "Mina de Oro",
    "Morente",
    "Ogbot",
    "Orconuma",
    "Poblacion",
    "Polusahi",
    "Sagana",
    "San Isidro",
    "San Jose",
    "San Juan",
    "Santa Cruz",
    "Sigange",
    "Tawas",
  ],
  "1705204000": [
    "Bagong Sikat",
    "Balatasan",
    "Benli",
    "Cabugao",
    "Cambunang (Pob.)",
    "Campaasan (Pob.)",
    "Maasin",
    "Maujao",
    "Milagrosa",
    "Nasukob (Pob.)",
    "Poblacion",
    "San Francisco",
    "San Isidro",
    "San Juan",
    "San Roque ",
  ],
  "1705205000": [
    "Balingayan",
    "Balite",
    "Baruyan",
    "Batino",
    "Bayanan I",
    "Bayanan II",
    "Biga",
    "Bondoc",
    "Bucayao",
    "Buhuan",
    "Bulusan",
    "Calero (Pob.)",
    "Camansihan",
    "Camilmil",
    "Canubing I",
    "Canubing II",
    "Comunal",
    "Guinobatan",
    "Gulod",
    "Gutad",
    "Ibaba East (Pob.)",
    "Ibaba West (Pob.)",
    "Ilaya (Pob.)",
    "Lalud",
    "Lazareto",
    "Libis (Pob.)",
    "Lumangbayan",
    "Mahal Na Pangalan",
    "Maidlang",
    "Malad",
    "Malamig",
    "Managpi",
    "Masipit",
    "Nag-Iba I",
    "Nag-Iba II",
    "Navotas",
    "Pachoca",
    "Palhi",
    "Panggalaan",
    "Parang",
    "Patas",
    "Personas",
    "Puting Tubig",
    "Salong",
    "San Antonio",
    "San Vicente Central (Pob.)",
    "San Vicente East (Pob.)",
    "San Vicente North (Pob.)",
    "San Vicente South (Pob.)",
    "San Vicente West (Pob.)",
    "Sapul",
    "Silonay",
    "Sta. Cruz",
    "Sta. Isabel",
    "Sta. Maria Village",
    "Sta. Rita",
    "Sto. Niño",
    "Suqui",
    "Tawagan",
    "Tawiran",
    "Tibag",
    "Wawa",
  ],
  "1705206000": [
    "Agos",
    "Agsalin",
    "Alma Villa",
    "Andres Bonifacio",
    "Balete",
    "Banus",
    "Banutan",
    "Bulaklakan",
    "Buong Lupa",
    "Gaudencio Antonino",
    "Guimbonan",
    "Kawit",
    "Lucio Laurel",
    "Macario Adriatico",
    "Malamig",
    "Malayong",
    "Maligaya (Pob.)",
    "Malubay",
    "Manguyang",
    "Maragooc",
    "Mirayan",
    "Narra",
    "Papandungin",
    "San Antonio",
    "Santa Maria",
    "Santa Theresa",
    "Tambong",
  ],
  "1705207000": [
    "B. Del Mundo",
    "Balugo",
    "Bonbon",
    "Budburan",
    "Cabalwa",
    "Don Pedro",
    "Maliwanag",
    "Manaul",
    "Panaytayan",
    "Poblacion",
    "Roma",
    "Santa Brigida",
    "Santa Maria",
    "Santa Teresita",
    "Villa Celestial",
    "Wasig",
    "Waygan",
  ],
  "1705208000": [
    "Adrialuna",
    "Andres Ilagan",
    "Antipolo",
    "Apitong",
    "Arangin",
    "Aurora",
    "Bacungan",
    "Bagong Buhay",
    "Balite",
    "Bancuro",
    "Banuton",
    "Barcenaga",
    "Bayani",
    "Buhangin",
    "Caburo",
    "Concepcion",
    "Dao",
    "Del Pilar",
    "Estrella",
    "Evangelista",
    "Gamao",
    "General Esco",
    "Herrera",
    "Inarawan",
    "Kalinisan",
    "Laguna",
    "Mabini",
    "Magtibay",
    "Mahabang Parang",
    "Malaya",
    "Malinao",
    "Malvar",
    "Masagana",
    "Masaguing",
    "Melgar A",
    "Melgar B",
    "Metolza",
    "Montelago",
    "Montemayor",
    "Motoderazo",
    "Mulawin",
    "Nag-Iba I",
    "Nag-Iba II",
    "Pagkakaisa",
    "Paitan",
    "Paniquian",
    "Pinagsabangan I",
    "Pinagsabangan II",
    "Piñahan",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Sampaguita",
    "San Agustin I",
    "San Agustin II",
    "San Andres",
    "San Antonio",
    "San Carlos",
    "San Isidro",
    "San Jose",
    "San Luis",
    "San Nicolas",
    "San Pedro",
    "Santa Cruz",
    "Santa Isabel",
    "Santa Maria",
    "Santiago",
    "Santo Niño",
    "Tagumpay",
    "Tigkan",
  ],
  "1705209000": [
    "Anoling",
    "Bacungan",
    "Bangbang",
    "Banilad",
    "Buli",
    "Cacawan",
    "Calingag",
    "Delrazon",
    "Guinhawa",
    "Inclanay",
    "Lumambayan",
    "Malaya",
    "Maliangcog",
    "Maningcol",
    "Marayos",
    "Marfrancisco",
    "Nabuslot",
    "Pagalagala",
    "Palayan",
    "Pambisan Malaki",
    "Pambisan Munti",
    "Panggulayan",
    "Papandayan",
    "Pili",
    "Quinabigan",
    "Ranzo",
    "Rosario",
    "Sabang",
    "Sta. Isabel",
    "Sta. Maria",
    "Sta. Rita",
    "Sto. Niño",
    "Wawa",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)",
  ],
  "1705210000": [
    "Bacawan",
    "Bacungan",
    "Batuhan",
    "Bayanan",
    "Biga",
    "Buhay Na Tubig",
    "Calima",
    "Calubasanhon",
    "Campamento",
    "Casiligan",
    "Malibago",
    "Maluanluan",
    "Matulatula",
    "Misong",
    "Pahilahan",
    "Panikihan",
    "Pula",
    "Puting Cacao",
    "Tagbakin",
    "Tagumpay",
    "Tiguihan",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
  ],
  "1705211000": [
    "Aninuan",
    "Baclayan",
    "Balatero",
    "Dulangan",
    "Palangan",
    "Poblacion",
    "Sabang",
    "San Antonio",
    "San Isidro",
    "Santo Niño",
    "Sinandigan",
    "Tabinay",
    "Villaflor",
  ],
  "1705212000": [
    "Bagumbayan (Pob.)",
    "Cantil",
    "Dangay",
    "Happy Valley",
    "Libertad",
    "Libtong",
    "Little Tanauan",
    "Mabuhay",
    "Maraska",
    "Odiong",
    "Paclasan (Pob.)",
    "San Aquilino",
    "San Isidro",
    "San Jose",
    "San Mariano",
    "San Miguel",
    "San Rafael",
    "San Vicente",
    "Uyao",
    "Victoria",
  ],
  "1705213000": [
    "Bigaan",
    "Caagutayan",
    "Calangatan",
    "Calsapa",
    "Ilag",
    "Lumangbayan",
    "Poblacion",
    "Tacligan",
  ],
  "1705214000": [
    "Bagsok",
    "Batong Dalig",
    "Bayuin",
    "Bugtong Na Tuog",
    "Calocmoy",
    "Calubayan",
    "Catiningan",
    "Fortuna",
    "Happy Valley",
    "Leuteboro I",
    "Leuteboro II",
    "Ma. Concepcion",
    "Mabuhay I",
    "Mabuhay II",
    "Malugay",
    "Matungao",
    "Monteverde",
    "Pasi I",
    "Pasi II",
    "Santo Domingo",
    "Subaan",
    "Villareal",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)",
  ],
  "1705215000": [
    "Alcate",
    "Antonino",
    "Babangonan",
    "Bagong Buhay",
    "Bagong Silang",
    "Bambanin",
    "Bethel",
    "Canaan",
    "Concepcion",
    "Duongan",
    "Jose Leido Jr.",
    "Loyal",
    "Mabini",
    "Macatoc",
    "Malabo",
    "Merit",
    "Ordovilla",
    "Pakyas",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Sampaguita",
    "San Antonio",
    "San Cristobal",
    "San Gabriel",
    "San Gelacio",
    "San Isidro",
    "San Juan",
    "San Narciso",
    "Urdaneta",
    "Villa Cerveza",
  ],
  "1705301000": [
    "Apo-Aporawan",
    "Apoc-apoc",
    "Aporawan",
    "Barake",
    "Cabigaan",
    "Culandanum",
    "Gogognan",
    "Iraan",
    "Isaub",
    "Jose Rizal",
    "Mabini",
    "Magbabadil",
    "Plaridel",
    "Poblacion",
    "Ramon Magsaysay",
    "Sagpangan",
    "San Juan",
    "Tagpait",
    "Tigman",
  ],
  "1705302000": [
    "Abagat (Pob.)",
    "Algeciras",
    "Bangcal (Pob.)",
    "Cambian (Pob.)",
    "Concepcion",
    "Diit",
    "Maracanao",
    "Matarawis",
    "Villafria",
    "Villasol",
  ],
  "1705303000": [
    "Balogo",
    "Dagman",
    "Dalayawon",
    "Lumacad",
    "Madoldolon",
    "Mauringuen",
    "Osmeña",
    "Poblacion",
    "San Jose De Oro",
    "Santo Niño",
    "Taloto",
    "Tinintinan",
    "Tudela",
  ],
  "1705304000": [
    "Agutayan",
    "Bancalaan",
    "Bugsuk",
    "Catagupan",
    "Indalawan",
    "Malaking Ilog",
    "Mangsee",
    "Melville",
    "Pandanan",
    "Pasig",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Poblacion V",
    "Poblacion VI",
    "Rabor",
    "Ramos",
    "Salang",
    "Sebaring",
  ],
  "1705305000": [
    "Bono-bono",
    "Bulalacao",
    "Buliluyan",
    "Culandanum",
    "Igang-igang",
    "Inogbong",
    "Iwahig",
    "Malihud",
    "Malitub",
    "Marangas (Pob.)",
    "Ocayan",
    "Puring",
    "Rio Tuba",
    "Sandoval",
    "Sapa",
    "Sarong",
    "Sumbiling",
    "Tabud",
    "Tagnato",
    "Tagolango",
    "Taratak",
    "Tarusan",
  ],
  "1705306000": [
    "Amas",
    "Aribungos",
    "Barong-barong",
    "Calasaguen",
    "Imulnod",
    "Ipilan",
    "Maasin",
    "Mainit",
    "Malis",
    "Mambalot",
    "Oring-oring",
    "Pangobilian",
    "Poblacion I",
    "Poblacion II",
    "Salogon",
    "Samareñana",
    "Saraza",
    "Tubtub",
  ],
  "1705307000": [
    "Bogtong",
    "Buluang",
    "Cheey",
    "Concepcion",
    "Maglalambay",
    "New Busuanga (Pob.)",
    "Old Busuanga",
    "Panlaitan",
    "Quezon",
    "Sagrada",
    "Salvacion",
    "San Isidro",
    "San Rafael",
    "Santo Niño",
  ],
  "1705308000": [
    "Bantayan (Pob.)",
    "Calsada (Pob.)",
    "Convento (Pob.)",
    "Lipot North (Pob.)",
    "Lipot South (Pob.)",
    "Magsaysay",
    "Mampio",
    "Nusa",
    "Santa Cruz",
    "Tacas (Pob.)",
    "Talaga",
    "Wahig (Pob.)",
  ],
  "1705309000": [
    "Banuang Daan",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V (Pob.)",
    "Barangay VI (Pob.)",
    "Bintuan",
    "Borac",
    "Buenavista",
    "Bulalacao",
    "Cabugao",
    "Decabobo",
    "Decalachao",
    "Guadalupe",
    "Lajala",
    "Malawig",
    "Marcilla",
    "San Jose",
    "San Nicolas",
    "Tagumpay",
    "Tara",
    "Turda",
  ],
  "1705310000": [
    "Balading",
    "Bangcal (Pob.)",
    "Cabigsing (Pob.)",
    "Caburian",
    "Caponayan",
    "Catadman (Pob.)",
    "Funda",
    "Lagaoriao (Pob.)",
    "Lubid",
    "Lungsod (Pob.)",
    "Manamoc",
    "Maringian",
    "Pawa",
    "San Carlos",
    "Suba",
    "Tenga-tenga (Pob.)",
    "Tocadan (Pob.)",
  ],
  "1705311000": [
    "Bacao",
    "Bohol",
    "Calasag",
    "Capayas",
    "Catep",
    "Culasian",
    "Danleg",
    "Dumaran (Pob.)",
    "Ilian",
    "Itangil",
    "Magsaysay",
    "San Juan",
    "Santa Maria",
    "Santa Teresita",
    "Santo Tomas",
    "Tanatanaon",
  ],
  "1705312000": [
    "Aberawan",
    "Bagong Bayan",
    "Barotuan",
    "Bebeladan",
    "Bucana",
    "Buena Suerte Pob.",
    "Corong-corong Pob.",
    "Mabini",
    "Maligaya Pob.",
    "Manlag",
    "Masagana Pob.",
    "New Ibajay",
    "Pasadeña",
    "San Fernando",
    "Sibaltan",
    "Teneguiban",
    "Villa Libertad",
    "Villa Paz",
  ],
  "1705313000": [
    "Barangonan",
    "Cabunlawan",
    "Calibangbangan",
    "Decabaitot",
    "Maroyogroyog",
    "Nangalao",
    "New Culaylayan",
    "Pical",
    "San Miguel (Pob.)",
    "San Nicolas",
  ],
  "1705314000": [
    "Alcoba",
    "Balaguen",
    "Canipo",
    "Cocoro",
    "Danawan (Pob.)",
    "Emilod",
    "Igabas",
    "Lacaren",
    "Los Angeles",
    "Lucbuan",
    "Rizal",
  ],
  "1705315000": [
    "Antipuluan",
    "Aramaywan",
    "Bagong Sikat",
    "Batang-batang",
    "Bato-bato",
    "Burirao",
    "Caguisan",
    "Calategas",
    "Dumagueña",
    "Elvita",
    "Estrella Village",
    "Ipilan",
    "Malatgao",
    "Malinao",
    "Narra (Pob.)",
    "Panacan",
    "Panacan 2",
    "Princess Urduja",
    "Sandoval",
    "Tacras",
    "Taritien",
    "Teresa",
    "Tinagong Dagat",
  ],
  "1705317000": [
    "Alfonso XIII (Pob.)",
    "Aramaywan",
    "Berong",
    "Calatagbak",
    "Calumpang",
    "Isugod",
    "Maasin",
    "Malatgao",
    "Panitian",
    "Pinaglabanan",
    "Quinlogan",
    "Sowangan",
    "Tabon",
    "Tagusao",
  ],
  "1705318000": [
    "Abaroan",
    "Antonino",
    "Bagong Bayan",
    "Barangay 1 (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Barangay V Pob.",
    "Barangay VI Pob.",
    "Caramay",
    "Dumarao",
    "Iraan",
    "Jolo",
    "Magara",
    "Malcampo",
    "Mendoza",
    "Narra",
    "New Barbacan",
    "New Cuyo",
    "Nicanor Zabala",
    "Rizal",
    "Salvacion",
    "San Isidro",
    "San Jose",
    "San Miguel",
    "San Nicolas",
    "Sandoval",
    "Tagumpay",
    "Taradungan",
    "Tinitian",
    "Tumarbong",
  ],
  "1705319000": [
    "Alimanguan",
    "Binga",
    "Caruray",
    "Kemdeng",
    "New Agutaya",
    "New Canipo",
    "Poblacion",
    "Port Barton",
    "San Isidro",
    "Santo Niño",
  ],
  "1705320000": [
    "Abongan",
    "Alacalian",
    "Banbanan",
    "Bantulan",
    "Baras",
    "Batas",
    "Bato",
    "Beton",
    "Busy Bees",
    "Calawag",
    "Casian",
    "Cataban",
    "Debangan",
    "Depla",
    "Libertad",
    "Liminangcong",
    "Meytegued",
    "Minapla",
    "New Guinlo",
    "Old Guinlo",
    "Paglaum",
    "Paly",
    "Pamantolon",
    "Pancol",
    "Poblacion",
    "Pularaquen",
    "San Jose",
    "Sandoval",
    "Silanga",
    "Talog",
    "Tumbod",
  ],
  "1705321000": ["Pag-Asa (Pob.)"],
  "1705322000": [
    "Balala",
    "Baldat",
    "Binudac",
    "Burabod",
    "Culango",
    "De Carabao",
    "Galoc",
    "Halsey",
    "Jardin",
    "Libis",
    "Luac",
    "Malaking Patag",
    "Osmeña",
    "Tiza",
  ],
  "1705323000": [
    "Bunog",
    "Campong Ulay",
    "Candawaga",
    "Canipaan",
    "Culasian",
    "Iraan",
    "Latud",
    "Panalingaan",
    "Punta Baja",
    "Ransang",
    "Taburi",
  ],
  "1705324000": [
    "Abo-abo",
    "Iraray",
    "Isumbo",
    "Labog",
    "Panitian",
    "Pulot Center",
    "Pulot Interior",
    "Pulot Shore",
    "Punang",
  ],
  "1705901000": [
    "Bagsik",
    "Bonlao",
    "Calagonsao",
    "Camili",
    "Comod-om",
    "Gui-ob",
    "Lawan",
    "Madalag",
    "Poblacion",
    "San Isidro",
    "San Roque",
    "Tugdan",
  ],
  "1705902000": [
    "Balogo",
    "Banice",
    "Hambi-an",
    "Lagang",
    "Libtong",
    "Mainit",
    "Nabalay",
    "Nasunogan",
    "Poblacion",
    "Sibay",
    "Tan-Ag",
    "Toctoc",
    "Togbongan",
    "Togong",
    "Tumalum",
    "Tungonan",
    "Yabawon",
  ],
  "1705903000": [
    "Alibagon",
    "Cambajao",
    "Cambalo",
    "Cambijang",
    "Cantagda",
    "Danao",
    "Gutivan",
    "Lico",
    "Lumbang Este",
    "Lumbang Weste",
    "Marigondon",
    "Poblacion",
    "Sugod",
    "Taguilos",
  ],
  "1705904000": [
    "Balogo",
    "Linao",
    "Pagsangahan",
    "Pangulo",
    "Poblacion",
    "San Roque",
    "Talisay",
  ],
  "1705905000": [
    "Bachawan",
    "Calabasahan",
    "Dalajican",
    "Masadya",
    "Masudsud",
    "Poblacion",
    "Sampong",
    "San Pedro",
    "San Vicente",
  ],
  "1705906000": [
    "Alegria",
    "Ambulong",
    "Colongcolong",
    "Gobon",
    "Guintiguiban",
    "Ilijan",
    "Labnig",
    "Mabini",
    "Mahaba",
    "Mangansag",
    "Poblacion",
    "San Agustin",
    "San Roque",
    "San Vicente",
    "Tacasan",
  ],
  "1705907000": [
    "Agojo",
    "Balatucan",
    "Buenavista",
    "Camandag",
    "Guinhayaan",
    "Limon Norte",
    "Limon Sur",
    "Manhac",
    "Pili",
    "Poblacion",
    "Punta",
    "Tuguis",
  ],
  "1705908000": [
    "Agsao",
    "Agutay",
    "Ambulong",
    "Dulangan",
    "Ipil",
    "Jao-asan",
    "Poblacion",
    "Silum",
    "Tampayan",
  ],
  "1705909000": [
    "Amatong",
    "Anahao",
    "Bangon",
    "Batiano",
    "Budiong",
    "Canduyong",
    "Dapawan",
    "Gabawan",
    "Libertad",
    "Ligaya (Pob.)",
    "Liwanag (Pob.)",
    "Liwayway (Pob.)",
    "Malilico",
    "Mayha",
    "Panique",
    "Pato-o",
    "Poctoy",
    "Progreso Este",
    "Progreso Weste",
    "Rizal",
    "Tabing Dagat (Pob.)",
    "Tabobo-an",
    "Tuburan",
    "Tulay",
    "Tumingad",
  ],
  "1705910000": [
    "Agbaluto",
    "Agbudia",
    "Agnaga",
    "Agnay",
    "Agnipa",
    "Agpanabat",
    "Agtongo",
    "Alad",
    "Bagacay",
    "Barangay I (Pob.)",
    "Barangay II (Pob.)",
    "Barangay III (Pob.)",
    "Barangay IV (Pob.)",
    "Cajimos",
    "Calabogo",
    "Capaclan",
    "Cobrador",
    "Ginablan",
    "Guimpingan",
    "Ilauran",
    "Lamao",
    "Li-o",
    "Logbon",
    "Lonos",
    "Lunas",
    "Macalas",
    "Mapula",
    "Palje",
    "Sablayan",
    "Sawang",
    "Tambac",
  ],
  "1705911000": [
    "Bachawan",
    "Binonga-an",
    "Buli",
    "Cabolutan",
    "Cagbo-aya",
    "Camantaya",
    "Carmen",
    "Cawayan",
    "Doña Juana",
    "Dubduban",
    "Hinugusan",
    "Lusong",
    "Mahabang Baybay",
    "Poblacion",
    "Sugod",
  ],
  "1705912000": [
    "Agpudlos",
    "Calunacon",
    "Doña Trinidad",
    "Juncarlo",
    "Linawan",
    "Mabini",
    "Marigondon Norte",
    "Marigondon Sur",
    "Matutuna",
    "Pag-Alad",
    "Poblacion",
    "Tan-Agan",
    "Victoria",
  ],
  "1705913000": [
    "Agtiwa",
    "Azarga",
    "Campalingo",
    "Canjalon",
    "España",
    "Mabini",
    "Mabulo",
    "Otod",
    "Panangcalan",
    "Pili",
    "Poblacion",
    "Taclobo",
  ],
  "1705914000": ["Busay", "Combot", "Lanas", "Pinamihagan", "Poblacion"],
  "1705915000": [
    "Agmanic",
    "Canyayo",
    "Danao Norte",
    "Danao Sur",
    "Guinbirayan",
    "Guintigbasan",
    "Magsaysay",
    "Mat-i",
    "Pandan",
    "Poblacion",
    "Tabugon",
  ],
  "1705916000": [
    "Agnonoc",
    "Bunsoran",
    "Claro M. Recto",
    "Hinaguman",
    "Poblacion",
    "Tubigon",
  ],
  "1705917000": [
    "Bonga",
    "Concepcion Norte (Pob.)",
    "Concepcion Sur",
    "Paroyhog",
    "San Isidro",
    "Santo Niño",
  ],
  "1731500000": [
    "Babuyan",
    "Bacungan",
    "Bagong Bayan",
    "Bagong Pag-Asa (Pob.)",
    "Bagong Sikat (Pob.)",
    "Bagong Silang (Pob.)",
    "Bahile",
    "Bancao-bancao",
    "Barangay ng mga Mangingisda",
    "Binduyan",
    "Buenavista",
    "Cabayugan",
    "Concepcion",
    "Inagawan",
    "Inagawan Sub-Colony",
    "Irawan",
    "Iwahig (Pob.)",
    "Kalipay (Pob.)",
    "Kamuning",
    "Langogan",
    "Liwanag (Pob.)",
    "Lucbuan",
    "Luzviminda",
    "Mabuhay (Pob.)",
    "Macarascas",
    "Magkakaibigan (Pob.)",
    "Maligaya (Pob.)",
    "Manalo",
    "Mandaragat",
    "Manggahan (Pob.)",
    "Maningning (Pob.)",
    "Maoyon",
    "Marufinas",
    "Maruyogon",
    "Masigla (Pob.)",
    "Masikap (Pob.)",
    "Masipag (Pob.)",
    "Matahimik (Pob.)",
    "Matiyaga (Pob.)",
    "Maunlad (Pob.)",
    "Milagrosa (Pob.)",
    "Model (Pob.)",
    "Montible (Pob.)",
    "Napsan",
    "New Panggangan",
    "Pagkakaisa (Pob.)",
    "Princesa (Pob.)",
    "Salvacion",
    "San Jose",
    "San Manuel",
    "San Miguel",
    "San Pedro",
    "San Rafael",
    "Santa Cruz",
    "Santa Lourdes",
    "Santa Lucia (Pob.)",
    "Santa Monica",
    "Seaside (Pob.)",
    "Sicsican",
    "Simpocan",
    "Tagabinit",
    "Tagburos",
    "Tagumpay (Pob.)",
    "Tanabag",
    "Tanglaw (Pob.)",
    "Tiniguiban",
  ],
};
