/** GENERATED — BARMM: 2590 barangays across 127 cities. */
export const BARANGAYS: Record<string, string[]> = {
  "1900702000": [
    "Arco",
    "Ba-as",
    "Baimbing",
    "Balagtasan",
    "Balas",
    "Balobo",
    "Bato",
    "Baungos",
    "Bohebessey",
    "Boheibu",
    "Bohenange",
    "Bohesapa",
    "Boheyakan",
    "Boheyawas",
    "Buahan",
    "Bulanting",
    "Bulingan",
    "Cabobo",
    "Calugusan",
    "Campo Uno",
    "Colonia",
    "Danit-Puntocan",
    "Kulay Bato",
    "Lebbuh",
    "Limo-ok",
    "Lo-ok",
    "Luksumbang",
    "Lumuton",
    "Maganda",
    "Malakas",
    "Maligaya",
    "Malinis (Pob.)",
    "Malo-ong Canal",
    "Malo-ong San Jose",
    "Matatag",
    "Matibay",
    "Parangbasak",
    "Sabong",
    "Santa Clara",
    "Sengal",
    "Simbangon",
    "Tandong Ahas",
    "Tumakid",
    "Ubit",
    "Ulame",
  ],
  "1900703000": [
    "Atong-atong",
    "Bagbagon",
    "Baungis",
    "Bulan-bulan",
    "Bulanza",
    "Calayan",
    "Calugusan",
    "Canibungan",
    "Landugan",
    "Lantawan Proper (Pob.)",
    "Lawi-lawi",
    "Lawila",
    "Lower Bañas",
    "Lower Manggas",
    "Luuk-Maluha",
    "Matarling",
    "Matikang",
    "Pamucalin",
    "Paniongan",
    "Parian-Baunoh",
    "Suba-an",
    "Switch Yakal",
    "Tairan",
    "Upper Bañas",
    "Upper Manggas",
  ],
  "1900704000": [
    "Abong-Abong",
    "Batungal",
    "Calang Canas",
    "Fuente Maluso",
    "Guanan North",
    "Guanan South",
    "Limbubong",
    "Mahayahay Lower",
    "Mahayahay Upper",
    "Muslim Area",
    "Port Holland Zone I Pob.",
    "Port Holland Zone II Pob.",
    "Port Holland Zone III Pob.",
    "Port Holland Zone IV",
    "Port Holland Zone V",
    "Taberlongan",
    "Tamuk",
    "Townsite (Pob.)",
    "Tubigan",
    "Upper Garlayan",
  ],
  "1900705000": [
    "Bacung",
    "Baiwas",
    "Basak",
    "Benembengan Lower",
    "Benembengan Upper",
    "Bohe-languyan",
    "Buli-buli",
    "Cabcaban",
    "Cabengbeng Lower",
    "Cabengbeng Upper",
    "Ettub-ettub",
    "Guiong",
    "Kaum-Air",
    "Kaumpamatsakem",
    "Libug",
    "Limbocandis",
    "Lukketon",
    "Luuk-Bait",
    "Mahatalang",
    "Manaul",
    "Mangal (Pob.)",
    "Marang",
    "Mebak",
    "Sahaya Bohe Bato",
    "Sapah Bulak",
    "Sumisip Central",
    "Tikus",
    "Tongsengal",
    "Tumahubong",
  ],
  "1900706000": [
    "Badja",
    "Baguindan",
    "Banah",
    "Bangcuang",
    "Bohe-Tambak",
    "Bohebaca",
    "Bohelebung",
    "Lagayas",
    "Limbo-Upas",
    "Silangkum",
    "Tipo-tipo Proper (Pob.)",
  ],
  "1900707000": [
    "Bohetambis",
    "Calut",
    "Duga-a",
    "Katipunan",
    "Lahi-lahi",
    "Lower Sinangkapan",
    "Lower Tablas",
    "Mahawid",
    "Sinulatan",
    "Tablas Usew",
  ],
  "1900708000": [
    "Caddayan",
    "Linongan",
    "Lower Bato-bato",
    "Mangalut",
    "Manguso",
    "Paguengan",
    "Semut",
    "Upper Bato-bato",
    "Upper Sinangkapan",
  ],
  "1900709000": [
    "Apil-apil",
    "Bato-bato",
    "Bohe-Piang",
    "Bucalao",
    "Cambug",
    "Danapah",
    "Guinanta",
    "Kailih",
    "Kinukutan",
    "Kuhon",
    "Kuhon Lennuh",
    "Linuan",
    "Lookbisaya",
    "Macalang",
    "Magcawa",
    "Sangkahan",
  ],
  "1900710000": [
    "Basakan",
    "Buton",
    "Candiis",
    "Langil",
    "Langong",
    "Languyan",
    "Pintasan",
    "Seronggon",
    "Sibago",
    "Sulutan Matangal",
    "Tuburan Proper (Pob.)",
  ],
  "1900711000": [
    "Amaloy",
    "Bohe-Pahuh",
    "Bohe-Suyak",
    "Cabangalan",
    "Danit",
    "Kamamburingan",
    "Matata",
    "Materling",
    "Pipil",
    "Sungkayut",
    "Tongbato",
    "Ulitan",
  ],
  "1900712000": [
    "Baluk-baluk",
    "Dasalan",
    "Lubukan",
    "Luukbongsod",
    "Mananggal",
    "Palahangan",
    "Panducan",
    "Sangbay Big",
    "Sangbay Small",
    "Tausan",
  ],
  "1900713000": [
    "Babag",
    "Balanting",
    "Boloh-boloh",
    "Bukut-Umus",
    "Kaumpurnah",
    "Lanawan",
    "Pisak-pisak",
    "Saluping",
    "Suligan",
    "Sulloh",
    "Tambulig Buton",
    "Tong-Umus",
  ],
  "1903601000": [
    "Ampao",
    "Bagoaingud",
    "Balut",
    "Barua",
    "Buadiawani",
    "Bubong",
    "Daramoyod",
    "Dilabayan",
    "Dipatuan",
    "Gandamato",
    "Gurain",
    "Ilian",
    "Lama",
    "Liawao",
    "Lumbaca-Ingud",
    "Madanding",
    "Orong",
    "Pindolonan",
    "Poblacion I",
    "Poblacion II",
    "Raya",
    "Rorowan",
    "Sugod",
    "Tambo",
    "Tuka I",
    "Tuka II",
  ],
  "1903602000": [
    "Bagoaingud",
    "Banago",
    "Barorao",
    "Batuan",
    "Budas",
    "Buenavista",
    "Buisan",
    "Calilangan",
    "Igabay",
    "Ilian",
    "Lalabuan",
    "Lorenzo",
    "Lower Itil",
    "Lumbac",
    "Macao",
    "Magulalung Occidental",
    "Magulalung Oriental",
    "Matampay",
    "Matanog",
    "Molimoc",
    "Narra",
    "Pindolonan",
    "Plasan",
    "Poblacion",
    "Purakan",
    "Tataya",
    "Upper Itil",
  ],
  "1903603000": [
    "Abaga",
    "Bantoga Wato",
    "Barit",
    "Bolinsong",
    "Borakis",
    "Bualan",
    "Bubong",
    "Bubong Cadapaan",
    "Cadapaan",
    "Cadayonan",
    "Dadayag",
    "Dado",
    "Dibarusan",
    "Dilausan",
    "Dimarao",
    "Ingud",
    "Kaluntay",
    "Lalabuan",
    "Lati",
    "Lilod",
    "Limbo",
    "Lumbac Lalan",
    "Lumbac Wato",
    "Lumbayao",
    "Magarang",
    "Malaig",
    "Nusa Lumba Ranao",
    "Padila",
    "Pagayawan",
    "Paigoay",
    "Pantaragoo",
    "Poblacion",
    "Raya",
    "Salipongan",
    "Talub",
    "Tantua Raya",
    "Tomarompong",
    "Tuka Bubong",
  ],
  "1903604000": [
    "Bagoaingud",
    "Bairan (Pob.)",
    "Bandingun",
    "Biabi",
    "Bialaan",
    "Bubong Lilod",
    "Bubong Raya",
    "Cadayonan",
    "Cadingilan Occidental",
    "Cadingilan Oriental",
    "Condaraan Pob.",
    "Cormatan",
    "Gandamato",
    "Ilian",
    "Lalapung Central",
    "Lalapung Proper (Pob.)",
    "Lalapung Upper",
    "Linao",
    "Linuk (Pob.)",
    "Liong",
    "Lumbac",
    "Lumbac Cadayonan",
    "Maliwanag",
    "Mapantao",
    "Mimbalawag",
    "Palao",
    "Pama-an",
    "Pamacotan",
    "Pantar",
    "Parao",
    "Patong",
    "Poblacion",
    "Porotan",
    "Rantian",
    "Raya Cadayonan",
    "Rinabor (Pob.)",
    "Samporna (Pob.)",
    "Sapa",
    "Silid",
    "Sugod",
    "Sultan Pandapatan",
    "Sumbag (Pob.)",
    "Tagoranao",
    "Tangcal",
    "Tangcal Proper (Pob.)",
    "Tomarompong",
    "Tomongcal Ligi",
    "Torogan",
    "Tuca (Pob.)",
  ],
  "1903605000": [
    "Badak",
    "Baguiangun",
    "Balut Maito",
    "Basak",
    "Bubong",
    "Bubonga-Ranao",
    "Dansalan Dacsula",
    "Ingud",
    "Kialilidan",
    "Lumbac",
    "Macaguiling",
    "Madaya",
    "Magonaya",
    "Maindig",
    "Masolun",
    "Olama",
    "Pagalamatan (Pob.)",
    "Pantar",
    "Picalilangan",
    "Picotaan",
    "Pindolonan",
    "Poblacion",
    "Soldaroro",
    "Tambac",
    "Timbangan",
    "Tuca",
  ],
  "1903606000": [
    "Bacolod",
    "Bagoaingud",
    "Bansayan",
    "Basingan",
    "Batangan",
    "Bualan",
    "Bubonga Didagun",
    "Carigongan",
    "Dalaon",
    "Dibarosan",
    "Dilabayan",
    "Dimapatoy",
    "Dimayon",
    "Dimayon Proper",
    "Diolangan",
    "Guiguikun",
    "Madanding",
    "Malungun",
    "Masorot",
    "Matampay Dimarao",
    "Miabalawag",
    "Montiaan",
    "Pagayawan",
    "Palao",
    "Panalawan",
    "Pantar",
    "Pendogoan",
    "Pindolonan",
    "Poblacion",
    "Polayagan",
    "Punud",
    "Ramain Bubong",
    "Rogero",
    "Salipongan",
    "Sunggod",
    "Taboro",
  ],
  "1903607000": [
    "Bayabao Poblacion",
    "Butig Proper",
    "Cabasaran",
    "Coloyan Tambo",
    "Dilimbayan",
    "Dolangan",
    "Malungun",
    "Pindolonan",
    "Poktan",
    "Ragayan",
    "Raya",
    "Samer",
    "Sandab Madaya",
    "Sundig",
    "Timbab",
    "Tiowi",
  ],
  "1903609000": [
    "Bagoaingud",
    "Balintad",
    "Balintad A",
    "Barit",
    "Barorao",
    "Bato Batoray",
    "Baya",
    "Campong a Raya",
    "Campong Sabela",
    "Dapaan",
    "Gadongan",
    "Gui",
    "Linuk",
    "Lumbac",
    "Lumbacaingud",
    "Macabao",
    "Macaguiling",
    "Masolun",
    "Pagalongan",
    "Pamalian",
    "Pangadapun",
    "Panggawalupa",
    "Pantaon",
    "Pantaon A",
    "Para-aba",
    "Pindolonan",
    "Poblacion",
    "Sekun Matampay",
    "Sogod Madaya",
    "Tabuan",
    "Taganonok",
    "Taliogon",
  ],
  "1903610000": [
    "Babayog",
    "Cormatan",
    "Dilabayan",
    "Dilimbayan",
    "Dimagaling",
    "Dimunda",
    "Doronan",
    "Gadongan",
    "Kasayanan",
    "Kasayanan West",
    "Kibolos",
    "Kining",
    "Lidasan",
    "Macadar",
    "Malna Proper",
    "Pagalongan",
    "Pantaon",
    "Parao",
    "Pindolonan",
    "Poblacion",
  ],
  "1903611000": [
    "Bacolod I",
    "Bacolod II",
    "Bantayao",
    "Barit",
    "Baugan",
    "Buad Lumbac",
    "Cabasaran",
    "Calilangan",
    "Carandangan-Mipaga",
    "Cormatan Langban",
    "Dialongana",
    "Dilindongan-Cadayonan",
    "Gadongan",
    "Galawan",
    "Gambai",
    "Kasola",
    "Lalangitun",
    "Lama",
    "Lindongan Dialongana",
    "Lobo Basara",
    "Lumbac Bacayawan",
    "Macaguiling",
    "Mapantao",
    "Mapoling",
    "Maribo (Pob.)",
    "Minaring Diladigan",
    "Pagayawan",
    "Posudaragat",
    "Rumayas",
    "Sabala Bantayao",
    "Salaman",
    "Salolodun Berwar",
    "Sarigidan Madiar",
    "Sunggod",
    "Taluan",
    "Tamlang",
    "Tongcopan",
    "Turogan",
  ],
  "1903612000": [
    "Alog",
    "Basayungun",
    "Buad",
    "Bubong Macadar",
    "Budi",
    "Dago-ok",
    "Dalama",
    "Dalipuga",
    "Lalapung",
    "Ligue",
    "Lumbac",
    "Lumbac Bacayawan",
    "Lunay",
    "Macadar",
    "Madaya",
    "Minanga",
    "Pantar",
    "Penaring",
    "Picotaan",
    "Poblacion",
    "Tambac",
  ],
  "1903613000": [
    "Abaga",
    "Bacayawan",
    "Bagoaingud",
    "Basak",
    "Bato",
    "Bubong",
    "Cabasaran",
    "Cadayonan",
    "Dandamun",
    "Delausan",
    "Diampaca",
    "Dibarosan",
    "Gadongan",
    "Gurain",
    "Kormatan",
    "Liangan",
    "Liangan I",
    "Lilitun",
    "Linao",
    "Linuk",
    "Lumbac",
    "Madaya",
    "Padian Torogan I",
    "Pagayawan",
    "Paridi-Kalimodan",
    "Poblacion",
    "Punud",
    "Racotan",
    "Raya",
    "Riray",
    "Sabanding",
    "Salongabanding",
    "Sogod Kaloy",
    "Sugod",
    "Tamporong",
    "Tongantongan",
    "Udangun",
  ],
  "1903614000": [
    "Balagunun",
    "Balintad",
    "Bawang",
    "Biabe",
    "Bubong Uyaan",
    "Cabasaran",
    "Dibarusan",
    "Ilian",
    "Lakitan",
    "Liangan",
    "Linuk",
    "Lumbaca Ingud",
    "Madamba",
    "Pagayonan",
    "Palao",
    "Pangadapan",
    "Pantaon",
    "Pantar",
    "Punud",
    "Tambo",
    "Tubaran",
    "Tuca",
    "Tulay",
    "Uyaan Proper (Pob.)",
  ],
  "1903615000": [
    "Bacayawan",
    "Badak Lumao",
    "Bagoaingud",
    "Banday",
    "Betayan",
    "Boniga",
    "BPS Village",
    "Bunk House",
    "Cabasaran",
    "Calibagat",
    "Calumbog",
    "Campo Muslim",
    "China Town (Pob.)",
    "Corahab",
    "Diamaro",
    "Inandayan",
    "Jose Abad Santos",
    "Lamin",
    "Mable",
    "Macuranding",
    "Madaya",
    "Mananayo",
    "Manggahan",
    "Masao",
    "Matalin",
    "Matampay",
    "Matling",
    "Montay",
    "Pasir",
    "Pialot",
    "Rebocun",
    "Sarang",
    "Sumbagarogong",
    "Tacub",
    "Tambara",
    "Tiongcop",
    "Tuboc",
  ],
  "1903616000": [
    "Bacayawan",
    "Bacong",
    "Banga-Pantar",
    "Batal-Punud",
    "Bubong Madanding",
    "Camalig (Pob.)",
    "Camalig Bandara Ingud",
    "Camalig Bubong",
    "Cawayan",
    "Cawayan Bacolod",
    "Cawayan Kalaw",
    "Cawayan Linuk",
    "Daanaingud",
    "Ilian",
    "Inudaran Campong",
    "Inudaran Loway",
    "Inudaran Lumbac",
    "Kialdan",
    "Lubo",
    "Lumbac Kialdan",
    "Mantapoli",
    "Matampay",
    "Maul",
    "Maul Ilian",
    "Maul Lumbaca Ingud",
    "Nataron",
    "Pagalongan Bacayawan",
    "Palao",
    "Pataimas",
    "Poblacion",
    "Poona Marantao",
    "Punud Proper",
    "Tacub",
    "Tuca Kialdan",
  ],
  "1903617000": [
    "Ambolong",
    "Amito Marantao",
    "Bacolod Chico Proper",
    "Banga",
    "Bangco",
    "Banggolo Poblacion",
    "Bangon",
    "Basak Malutlut",
    "Beyaba-Damag",
    "Bito Buadi Itowa",
    "Bito Buadi Parba",
    "Boganga",
    "Boto Ambolong",
    "Buadi Sacayo",
    "Bubong Lumbac",
    "Bubonga Cadayonan",
    "Bubonga Lilod Madaya",
    "Bubonga Marawi",
    "Bubonga Pagalamatan",
    "Bubonga Punod",
    "Cabasaran",
    "Cabingan",
    "Cadayonan",
    "Cadayonan I",
    "Calocan East",
    "Calocan West",
    "Daguduban",
    "Dansalan",
    "Datu Naga",
    "Datu Sa Dansalan",
    "Dayawan",
    "Dimaluna",
    "Dulay",
    "Dulay West",
    "East Basak",
    "Emie Punud",
    "Fort",
    "Gadongan",
    "Gadongan Mapantao",
    "Guimba",
    "Kapantaran",
    "Kilala",
    "Kormatan Matampay",
    "Lilod Madaya (Pob.)",
    "Lilod Saduc",
    "Lomidong",
    "Lumbac Marinaut",
    "Lumbaca Madaya (Pob.)",
    "Lumbaca Toros",
    "Malimono",
    "Marawi Poblacion",
    "Marinaut East",
    "Marinaut West",
    "Matampay",
    "Mipaga Proper",
    "Moncado Colony",
    "Moncado Kadingilan",
    "Moriatao Loksadato",
    "Navarro",
    "Norhaya Village",
    "Olawa Ambolong",
    "Pagalamatan Gambai",
    "Pagayawan",
    "Panggao Saduc",
    "Pantaon",
    "Papandayan",
    "Papandayan Caniogan",
    "Paridi",
    "Patani",
    "Pindolonan",
    "Poona Marantao",
    "Pugaan",
    "Rapasun MSU",
    "Raya Madaya I",
    "Raya Madaya II",
    "Raya Saduc",
    "Rorogagus East",
    "Rorogagus Proper",
    "Sabala Manao",
    "Sabala Manao Proper",
    "Saduc Proper",
    "Sagonsongan",
    "Sangcay Dansalan",
    "Somiorang",
    "South Madaya Proper",
    "Sugod Proper",
    "Tampilong",
    "Timbangalan",
    "Tolali",
    "Tongantongan-Tuca Timbangalan",
    "Toros",
    "Tuca",
    "Tuca Ambolong",
    "Tuca Marinaut",
    "Wawalayan Calocan",
    "Wawalayan Marinaut",
  ],
  "1903618000": [
    "Abdullah Buisan",
    "Alip Lalabuan",
    "Alumpang Paino Mimbalay",
    "Buadi Amloy",
    "Caramian Alim Raya",
    "Dalog Balut",
    "Gindolongan Alabat",
    "Gondarangin Asa Adigao",
    "Kalilangan",
    "Laila Lumbac Bacon",
    "Lakadun",
    "Lanco Dimapatoy",
    "Lomigis Sucod",
    "Lumbaca Ingud",
    "Macabangan Imbala",
    "Macadaag Talaguian",
    "Macalupang Lumbac Caramian",
    "Macompara Apa Mimbalay",
    "Magayo Bagoaingud",
    "Mai Ditimbang Balindong",
    "Mai Sindaoloan Dansalan",
    "Manalocon Talub",
    "Maranat Bontalis",
    "Matao Araza",
    "Mocamad Tangul",
    "Moriatao-Bai Labay",
    "Pantao",
    "Putad Marandang Buisan",
    "Sambowang Atawa",
    "Sawir",
    "Talub Langi",
    "Tamboro Cormatan",
    "Tomambiling Lumbaca Ingud",
    "Towanao Arangga",
    "Unda Dayawan",
  ],
  "1903619000": [
    "Bagoaingud",
    "Bangon",
    "Buadi-Abala",
    "Buadi-Bayawa",
    "Buadi-Insuba",
    "Bubong",
    "Bubonga Guilopa",
    "Cabasaran",
    "Cairatan",
    "Cormatan",
    "Dalama",
    "Dansalan",
    "Dimarao",
    "Guilopa",
    "Ilian",
    "Kitambugun",
    "Lama",
    "Lilod",
    "Lilod Raybalai",
    "Lumbac",
    "Lumbaca Ingud",
    "Madaya",
    "Pindolonan",
    "Poblacion",
    "Salipongan",
    "Sugan",
  ],
  "1903620000": [
    "Ayong",
    "Bandara Ingud",
    "Bangon (Pob.)",
    "Biala-an",
    "Diampaca",
    "Guiarong",
    "Ilian",
    "Kalaludan",
    "Linindingan",
    "Madang",
    "Mapantao",
    "Ngingir",
    "Padas",
    "Paigoay",
    "Pinalangca",
    "Poblacion",
    "Rangiran",
    "Rubokun",
  ],
  "1903621000": [
    "Aposong",
    "Bagoaingud",
    "Bangco (Pob.)",
    "Bansayan",
    "Basak",
    "Bobo",
    "Bualan",
    "Bubong Ilian",
    "Bubong Tawa-an",
    "Bubonga Mamaanun",
    "Gacap",
    "Ilian",
    "Ilian Poblacion",
    "Kalanganan",
    "Katumbacan",
    "Lininding",
    "Lumbaca Mamaan",
    "Mamaanun",
    "Mentring",
    "Olango",
    "Palacat",
    "Palao",
    "Paling",
    "Pantaon",
    "Pantar",
    "Paridi",
    "Pindolonan",
    "Radapan",
    "Radapan Poblacion",
    "Rantian",
    "Sapingit",
    "Talao",
    "Tambo",
    "Tapocan",
    "Taporug",
    "Tawaan",
    "Udalo",
  ],
  "1903622000": [
    "Ataragadong",
    "Bangon",
    "Bansayan",
    "Bualan",
    "Bubong-Dimunda",
    "Bugaran",
    "Cadayonan",
    "Calilangan Dicala",
    "Calupaan",
    "Dilausan",
    "Dimayon",
    "Dongcoan",
    "Gadongan",
    "Liangan",
    "Lumbac",
    "Lumbaca Ingud",
    "Madanding",
    "Pantao",
    "Poblacion",
    "Punud",
    "Ragayan",
    "Rogan Cairan",
    "Rogan Tandiong Dimayon",
    "Talaguian",
    "Taporog",
  ],
  "1903623000": [
    "Badak",
    "Bantayan",
    "Basagad",
    "Bolinsong",
    "Boring",
    "Bualan",
    "Danugan",
    "Dapao",
    "Diamla",
    "Gadongan",
    "Ingud",
    "Linuk",
    "Lumbac",
    "Maligo",
    "Masao",
    "Notong",
    "Porug",
    "Romagondong",
    "Tambo (Pob.)",
    "Tamlang",
    "Tomarompong",
    "Tuka",
    "Yaran",
  ],
  "1903624000": [
    "Baclayan Lilod",
    "Baclayan Raya",
    "Bagoaingud",
    "Barimbingan",
    "Bayabao",
    "Buadi Alao",
    "Buadi Babai",
    "Buadi Oloc",
    "Buayaan Lilod",
    "Buayaan Madanding",
    "Buayaan Raya",
    "Bubong Dangiprampiai",
    "Dado",
    "Dangimprampiai",
    "Darimbang",
    "Dilausan",
    "Ditsaan",
    "Gadongan",
    "Linamon",
    "Lumbatan Ramain",
    "Maindig Ditsaan",
    "Mandara",
    "Maranao Timber",
    "Pagalongan Buadiadingan",
    "Pagalongan Ginaopan",
    "Pagalongan Masioon",
    "Pagalongan Proper",
    "Polo",
    "Ramain Poblacion",
    "Ramain Proper",
    "Rantian",
    "Sultan Pangadapun",
    "Sundiga Bayabao",
    "Talub",
    "Upper Pugaan",
  ],
  "1903625000": [
    "Alinun",
    "Bagoaingud",
    "Basak Maito",
    "Batangan",
    "Bubong",
    "Cadayon",
    "Cadingilan",
    "Comonal",
    "Dilausan",
    "Dilimbayan",
    "Gadongan",
    "Limogao",
    "Linao",
    "Lumbac Toros",
    "Lumbayanague",
    "Maliwanag",
    "Mapantao",
    "Mipaga",
    "Natangcopan",
    "Pagalamatan",
    "Pamacotan",
    "Panggao",
    "Pantao Raya",
    "Pantaon",
    "Patpangkat",
    "Pawak",
    "Pindolonan",
    "Poblacion",
    "Salocad",
    "Sungcod",
  ],
  "1903626000": [
    "Balutmadiar",
    "Bangon",
    "Beruar",
    "Bocalan",
    "Cabasaran",
    "Dasomalong",
    "Dilausan",
    "Ginaopan",
    "Lalabuan",
    "Lilod Tamparan",
    "Lilod Tubok",
    "Lindongan",
    "Linuk",
    "Linuk Oriental",
    "Lumbac",
    "Lumbaca Ingud",
    "Lumbaca Lilod",
    "Lumbacaingud South",
    "Maidan Linuk",
    "Mala-abangon",
    "Maliwanag",
    "Mariatao Datu",
    "Minanga",
    "Miondas",
    "New Lumbacaingud",
    "Occidental Linuk",
    "Pagalamatan Linuk",
    "Pagayawan",
    "Picarabawan",
    "Pimbago-Pagalongan",
    "Pindolonan Mariatao Sarip",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Raya Buadi Barao",
    "Raya Niondas",
    "Raya Tamparan",
    "Salongabanding",
    "Saminunggay",
    "Talub",
    "Tatayawan North",
    "Tatayawan South",
    "Tubok",
  ],
  "1903627000": [
    "Bandera Buisan",
    "Boriongan",
    "Borowa",
    "Buadi Amao",
    "Buadi Amunta",
    "Buadi Amunud",
    "Buadi Arorao",
    "Buadi Atopa",
    "Buadi Dayomangga",
    "Buadi Dingun",
    "Buadi Ongcalo",
    "Bucalan",
    "Cadayonan Bagumbayan",
    "Caramat",
    "Carandangan Calopaan",
    "Datu Ma-as",
    "Dilabayan",
    "Dimayon",
    "Gapao Balindong",
    "Ilian",
    "Lumasa",
    "Lumasa Proper",
    "Lumbac Bagoaingud",
    "Lumbac Bubong Maindang",
    "Lumbac Pitakus",
    "Malungun",
    "Mangayao",
    "Maruhom",
    "Masolun",
    "Moriatao Loksa Datu",
    "Pagalamatan",
    "Pindolonan",
    "Pitakus",
    "Ririk",
    "Salipongan",
    "Sambolawan",
    "Samporna Salamatollah",
    "Sigayan Proper",
    "Somiorang Bandingun",
    "Sunding",
    "Sunggod",
    "Supangan",
    "Tupa-an Buadiatupa",
  ],
  "1903628000": [
    "Alog",
    "Bagiangun",
    "Beta",
    "Campo",
    "Datumanong",
    "Dinaigan",
    "Gadongan",
    "Gaput",
    "Guiarong",
    "Madaya",
    "Malaganding",
    "Metadicop",
    "Mindamudag",
    "Pagalamatan",
    "Paigoay-Pimbataan",
    "Poblacion",
    "Polo",
    "Riantaran",
    "Tangcal",
    "Tubaran Proper",
    "Wago",
  ],
  "1903629000": [
    "Bagoaingud",
    "Buadi Alawang",
    "Buadi Dico",
    "Bubong",
    "Campong Talao",
    "Cayagan",
    "Dandanun",
    "Dilimbayan",
    "Gurain",
    "Lumbac",
    "Maidan",
    "Mapantao",
    "Pagalamatan",
    "Pandiaranao",
    "Pindolonan I",
    "Pindolonan II",
    "Poblacion",
    "Putad",
    "Raya",
    "Sugod I",
    "Sugod Mawatan",
    "Sumbaga Rogong",
    "Tangcal",
  ],
  "1903630000": [
    "Amoyong",
    "Balatin",
    "Banga",
    "Bo-ot",
    "Buntongun",
    "Cebuano Group",
    "Christian Village",
    "Eastern Wao",
    "Extension Poblacion",
    "Gata",
    "Kabatangan",
    "Kadingilan",
    "Katutungan (Pob.)",
    "Kilikili East",
    "Kilikili West",
    "Malaigang",
    "Manila Group",
    "Milaya",
    "Mimbuaya",
    "Muslim Village",
    "Pagalongan",
    "Panang",
    "Park Area (Pob.)",
    "Pilintangan",
    "Serran Village",
    "Western Wao (Pob.)",
  ],
  "1903631000": [
    "Bagumbayan",
    "Balut",
    "Bitayan",
    "Bolawan",
    "Bonga",
    "Cabasaran",
    "Cadayonan",
    "Cahera",
    "Cairantang",
    "Calumbog",
    "Canibongan",
    "Diragun",
    "Mantailoco",
    "Mapantao",
    "Marogong East",
    "Marogong Proper (Pob.)",
    "Mayaman",
    "Pabrica",
    "Paigoay Coda",
    "Pasayanan",
    "Piangologan",
    "Puracan",
    "Romagondong",
    "Sarang",
  ],
  "1903632000": [
    "Bubonga Ranao",
    "Calalaoan (Pob.)",
    "Gas",
    "Inoma",
    "Inudaran",
    "Luguna",
    "Mimbalawag",
    "Ngingir",
    "Pagalongan",
    "Panggawalupa",
    "Pantaon",
    "Piksan",
    "Pindolonan",
    "Punud",
    "Tagoranao",
    "Taliboboka",
    "Tambac",
  ],
  "1903633000": [
    "Bacolod",
    "Bangon",
    "Bangon Proper",
    "Boto Ragondingan",
    "Buadiposo Lilod",
    "Buadiposo Proper",
    "Buadiposo Raya",
    "Bubong",
    "Buntong Proper",
    "Cadayonan",
    "Dansalan",
    "Datu Tambara",
    "Dirisan",
    "Gata",
    "Kalakala",
    "Katogonan",
    "Lumbac",
    "Lumbatan Manacab",
    "Lumbatan Pataingud",
    "Lunduban",
    "Manacab (Pob.)",
    "Minanga",
    "Paling",
    "Pindolonan",
    "Pualas",
    "Ragondingan East",
    "Ragondingan Proper",
    "Ragondingan West",
    "Raya Buntong",
    "Sapot",
    "Tangcal",
    "Tarik",
    "Tuka",
  ],
  "1903634000": [
    "Agagan",
    "Balagunun",
    "Balawag",
    "Balintao",
    "Bato-bato",
    "Bolao",
    "Borocot",
    "Borrowa",
    "Botud",
    "Buadiangkay",
    "Bubong",
    "Bubong Bayabao",
    "Camalig",
    "Cambong",
    "Dilausan (Pob.)",
    "Dilimbayan",
    "Ilalag",
    "Kianodan",
    "Lilod Borocot",
    "Lilod Maguing",
    "Lumbac",
    "Lumbac-Dimarao",
    "Madanding",
    "Madaya",
    "Maguing Proper",
    "Malungun",
    "Malungun Borocot",
    "Malungun Pagalongan",
    "Pagalongan",
    "Panayangan",
    "Pilimoknan",
    "Pindolonan",
    "Ragayan",
    "Sabala Dilausan",
  ],
  "1903635000": [
    "Anas",
    "Bara-as",
    "Biasong",
    "Bulangos",
    "Durian",
    "Ilian",
    "Liangan (Pob.)",
    "Maganding",
    "Maladi",
    "Mapantao",
    "Micalubo",
    "Mimbalawag",
    "Pindolonan",
    "Punong",
    "Ramitan",
    "Torogan",
    "Tual",
    "Tuca",
    "Ubanoban",
  ],
  "1903636000": [
    "Bagoaingud",
    "Balaigay",
    "Bualan",
    "Cabuntungan",
    "Cadayonan",
    "Cadingilan",
    "Cadingilan A",
    "Casalayan",
    "Dala",
    "Dilimbayan",
    "Diromoyod",
    "Kabasaran (Pob.)",
    "Lamin",
    "Mapantao-Balangas",
    "Miniros",
    "Nanagun",
    "Pantaon",
    "Pindolonan",
    "Pitatanglan",
    "Poctan",
    "Singcara",
    "Wago",
  ],
  "1903637000": [
    "Bagumbayan",
    "Bandara-Ingud",
    "Comara",
    "Frankfort",
    "Lambanogan",
    "Lico",
    "Mansilano",
    "Natangcopan",
    "Pagalamatan",
    "Pagonayan",
    "Piagma",
    "Poblacion",
    "Punud",
    "Ranao-Baning",
    "Sagua-an",
    "Salam",
    "Sumugot",
  ],
  "1903638000": [
    "Bagoaingud",
    "Bantalan",
    "Bayog",
    "Cadayonan",
    "Dagonalan",
    "Dimalama",
    "Gayakay",
    "Inodaran",
    "Kalilangan",
    "Kianibong",
    "Kingan",
    "Kitaon",
    "Maimbaguiang",
    "Malinao",
    "Malingon",
    "Mama-an Pagalongan",
    "Marawi",
    "Sigayan",
    "Tagoloan Poblacion",
  ],
  "1903639000": [
    "Bakikis",
    "Barao",
    "Bongabong",
    "Daguan",
    "Inudaran",
    "Kabaniakawan",
    "Kapatagan",
    "Lusain",
    "Matimos",
    "Minimao",
    "Pinantao",
    "Salaman",
    "Sigayan",
    "Tabuan",
    "Upper Igabay",
  ],
  "1903640000": [
    "Bacayawan",
    "Buta",
    "Dinganun Guilopa",
    "Lumbac",
    "Malalis",
    "Pagalongan",
    "Tagoranao",
  ],
  "1903641000": [
    "Bangon",
    "Beta",
    "Calalon",
    "Calipapa",
    "Dilausan",
    "Dimapaok",
    "Lumbac Dilausan",
    "Oriental Beta",
    "Tringun",
  ],
  "1903801000": [
    "Dicalongan (Pob.)",
    "Kakal",
    "Kamasi",
    "Kapinpilan",
    "Kauran",
    "Malatimon",
    "Matagabong",
    "Salman",
    "Saniag",
    "Tomicor",
    "Tubak",
  ],
  "1903802000": [
    "Ampuan",
    "Aratuc",
    "Cabayuan",
    "Calaan (Pob.)",
    "Dinganen",
    "Edcor",
    "Karim",
    "Kulimpang",
    "Mataya",
    "Minabay",
    "Nuyo",
    "Oring",
    "Pantawan",
    "Piers",
    "Rumidas",
  ],
  "1903803000": [
    "Digal",
    "Lower Siling",
    "Maslabeng",
    "Poblacion",
    "Popol",
    "Talitay",
    "Upper Siling",
  ],
  "1903804000": [
    "Bagua",
    "Bagua I",
    "Bagua II",
    "Bagua III",
    "Kalanganan",
    "Kalanganan I",
    "Kalanganan II",
    "Poblacion",
    "Poblacion I",
    "Poblacion II",
    "Poblacion III",
    "Poblacion IV",
    "Poblacion IX",
    "Poblacion V",
    "Poblacion VI",
    "Poblacion VII",
    "Poblacion VIII",
    "Rosary Heights",
    "Rosary Heights I",
    "Rosary Heights II",
    "Rosary Heights III",
    "Rosary Heights IV",
    "Rosary Heights IX",
    "Rosary Heights V",
    "Rosary Heights VI",
    "Rosary Heights VII",
    "Rosary Heights VIII",
    "Rosary Heights X",
    "Rosary Heights XI",
    "Rosary Heights XII",
    "Rosary Heights XIII",
    "Tamontaka",
    "Tamontaka I",
    "Tamontaka II",
    "Tamontaka III",
    "Tamontaka IV",
    "Tamontaka V",
  ],
  "1903805000": [
    "Alip (Pob.)",
    "Bonawan",
    "Bulod",
    "Damalusay",
    "Damawato",
    "Datang",
    "Elbebe",
    "Kalumenga",
    "Katil",
    "Lipao",
    "Lomoyon",
    "Madidis",
    "Makat",
    "Malala",
    "Mangadeg",
    "Manindolo",
    "Mao",
    "Napok",
    "Palao sa Buto",
    "Poblacion",
    "Puya",
    "Salendab",
    "Sepaka",
  ],
  "1903806000": [
    "Alonganan",
    "Ambadao",
    "Balanakan",
    "Balong",
    "Buayan",
    "Dado",
    "Damabalas",
    "Duaminanga",
    "Kalipapa",
    "Kanguan",
    "Liong",
    "Magaslong",
    "Masigay",
    "Montay",
    "Poblacion",
    "Reina Regente",
  ],
  "1903807000": [
    "Ambolodto",
    "Awang",
    "Badak",
    "Bagoenged",
    "Baka",
    "Benolen",
    "Bitu",
    "Bongued",
    "Bugawas",
    "Capiton",
    "Dados",
    "Dalican Poblacion",
    "Dinaig Proper",
    "Dulangan",
    "Kakar",
    "Kenebeka",
    "Kurintem",
    "Kusiong",
    "Labungan",
    "Linek",
    "Makir",
    "Margues",
    "Mompong",
    "Nekitan",
    "Sapalan",
    "Semba",
    "Sibuto",
    "Sifaren",
    "Tambak",
    "Tamontaka",
    "Tanuel",
    "Tapian",
    "Taviran",
    "Tenonggos",
  ],
  "1903808000": [
    "Bagong",
    "Bialong",
    "Kuloy",
    "Labu-labu",
    "Lapok",
    "Malingao",
    "Poblacion",
    "Poblacion I",
    "Poblacion II",
    "Satan",
    "Tapikan",
    "Timbangan",
    "Tina",
  ],
  "1903809000": [
    "Bayanga Norte",
    "Bayanga Sur",
    "Bugasan Norte",
    "Bugasan Sur (Pob.)",
    "Kidama",
    "Langco",
    "Langkong",
    "Sapad",
  ],
  "1903810000": [
    "Bagoenged",
    "Buliok",
    "Dalgan",
    "Damalasak",
    "Galakit",
    "Inug-ug",
    "Kalbugan",
    "Kilangan",
    "Kudal",
    "Layog",
    "Linandangan",
    "Poblacion",
  ],
  "1903811000": [
    "Bongo Island",
    "Campo Islam",
    "Cotongan",
    "Datu Macarimbang Biruar",
    "Gadungan",
    "Gadunganpedpandaran",
    "Guiday T. Biruar",
    "Gumagadong Calawag",
    "Kabuan",
    "Landasan",
    "Limbayan",
    "Macasandag",
    "Magsaysay",
    "Making",
    "Manion",
    "Moro Point",
    "Nituan",
    "Orandang",
    "Pinantao",
    "Poblacion",
    "Poblacion II",
    "Polloc",
    "Samberen",
    "Tagudtongan",
    "Tuca-Maror",
  ],
  "1903812000": [
    "Alamada",
    "Banatin",
    "Banubo",
    "Bulalo",
    "Bulibod",
    "Calsada",
    "Crossing Simuay",
    "Dalumangcob (Pob.)",
    "Damaniog",
    "Darapanan",
    "Gang",
    "Inawan",
    "Kabuntalan",
    "Kakar",
    "Kapimpilan",
    "Katamlangan",
    "Katidtuan",
    "Katuli",
    "Ladia",
    "Limbo",
    "Maidapa",
    "Makaguiling",
    "Matengen",
    "Mulaug",
    "Nalinan",
    "Nara",
    "Nekitan",
    "Olas",
    "Panatan",
    "Pigcalagan",
    "Pigkelegan",
    "Pinaring",
    "Pingping",
    "Raguisi",
    "Rebuken",
    "Salimbao",
    "Sambolawan",
    "Senditan",
    "Ungap",
  ],
  "1903813000": [
    "Angkayamat",
    "Barurao",
    "Bulod",
    "Darampua",
    "Gadungan",
    "Kulambog",
    "Langgapanan",
    "Masulot",
    "Paldong",
    "Papakan",
    "Tugal",
    "Tukanakuden",
  ],
  "1903814000": [
    "Bagumbayan",
    "Buterin",
    "Dadtumog",
    "Gambar",
    "Ganta",
    "Katidtuan",
    "Langeban",
    "Liong",
    "Lower Taviran",
    "Maitong",
    "Matilak",
    "Pagalungan",
    "Payan",
    "Pedtad",
    "Pened",
    "Poblacion",
    "Upper Taviran",
  ],
  "1903815000": [
    "Bantek",
    "Bayabas",
    "Blensong",
    "Borongotan",
    "Bugabungan",
    "Bungcog",
    "Darugao",
    "Ganasi",
    "Kabakaba",
    "Kibleg",
    "Kibucay",
    "Kiga",
    "Kinitan",
    "Mirab",
    "Nangi",
    "Nuro Poblacion",
    "Ranao Pilayan",
    "Rempes",
    "Renede",
    "Renti",
    "Rifao",
    "Sefegefen",
    "Tinungkaan",
  ],
  "1903816000": [
    "Binangga North",
    "Binangga South",
    "Boboguiron",
    "Damablac",
    "Fugotan",
    "Fukol",
    "Katibpuan",
    "Kedati",
    "Lanting",
    "Linamunan",
    "Marader",
    "Talayan",
    "Tamar",
    "Tambunan I",
    "Timbaluan",
  ],
  "1903817000": [
    "Biarong",
    "Bongo",
    "Itaw",
    "Kigan",
    "Kuya",
    "Lamud",
    "Looy",
    "Pandan",
    "Pilar",
    "Romangaob (Pob.)",
    "San Jose",
  ],
  "1903818000": [
    "Barira (Pob.)",
    "Bualan",
    "Gadung",
    "Korosoyan",
    "Lamin",
    "Liong",
    "Lipa",
    "Lipawan",
    "Marang",
    "Minabay",
    "Nabalawag",
    "Panggao",
    "Rominimbang",
    "Togaig",
  ],
  "1903819000": [
    "Badak",
    "Bulod",
    "Kaladturan",
    "Kulasi",
    "Lao-lao",
    "Lasangan",
    "Lower Idtig",
    "Lumabao",
    "Makainis",
    "Midconding",
    "Midpandacan",
    "Panosolen",
    "Pidtiguian",
    "Quipolot",
    "Ramcor",
    "Sadangen",
    "Sumakubay",
    "Tonggol",
    "Upper Lasangan",
  ],
  "1903820000": [
    "Bagumbong",
    "Dabenayan",
    "Daladap",
    "Dasikil",
    "Liab",
    "Libutan",
    "Lusay",
    "Mamasapano",
    "Manongkaling",
    "Pidsandawan",
    "Pimbalakan",
    "Sapakan",
    "Tuka",
    "Tukanalipao",
  ],
  "1903821000": [
    "Bintan",
    "Gadungan",
    "Kiladap",
    "Kilalan",
    "Kuden",
    "Makadayon",
    "Manggay",
    "Pageda",
    "Talitay",
  ],
  "1903822000": [
    "Balatungkayo",
    "Bulit",
    "Bulod",
    "Dungguan",
    "Limbalud",
    "Maridagao",
    "Nabundas",
    "Pagagawan",
    "Talapas",
    "Talitay",
    "Tunggol",
  ],
  "1903823000": [
    "Campo",
    "Damakling",
    "Damalusay",
    "Kakal",
    "Paglat",
    "Salam",
    "Tual",
    "Upper Idtig",
  ],
  "1903824000": [
    "Balut",
    "Boliok",
    "Bungabong",
    "Dagurongan",
    "Kirkir",
    "Macabico",
    "Namuken",
    "Simuay/Seashore",
    "Solon",
    "Tambo",
    "Tapayan",
    "Tariken",
    "Tuka",
  ],
  "1903825000": [
    "Ahan",
    "Bagan",
    "Datalpandan",
    "Kalumamis",
    "Kateman",
    "Lambayao",
    "Macasampen",
    "Muslim",
    "Muti",
    "Sampao",
    "Tambunan II",
  ],
  "1903826000": [
    "Dapiawan",
    "Elian",
    "Gawang",
    "Kabengi",
    "Kitango",
    "Kitapok",
    "Madia",
    "Salbu",
  ],
  "1903827000": [
    "Bulayan",
    "Iganagampong",
    "Macalag",
    "Maitumaig",
    "Malangog",
    "Meta",
    "Panangeti",
    "Tuntungan",
  ],
  "1903828000": [
    "Banaba",
    "Dimampao",
    "Guinibon",
    "Kaya-kaya",
    "Maganoy",
    "Mao",
    "Maranding",
    "Sugadol",
    "Talisawa",
    "Tukanolocong",
  ],
  "1903829000": [
    "Baital",
    "Bakat",
    "Dapantis",
    "Gaunan",
    "Malibpolok",
    "Mileb",
    "Panadtaban",
    "Pidsandawan",
    "Sampao",
    "Sapakan (Pob.)",
    "Tabungao",
  ],
  "1903830000": [
    "Kinimi",
    "Laguitan",
    "Lapaken",
    "Matuber",
    "Meti",
    "Nalkan",
    "Penansaran",
    "Pura",
    "Resa",
    "Sedem",
    "Sinipak",
    "Tambak",
    "Tubuan",
  ],
  "1903831000": [
    "Adaon",
    "Brar",
    "Mapayag",
    "Midtimbang (Pob.)",
    "Nunangan",
    "Tugal",
    "Tulunan",
  ],
  "1903832000": [
    "Daladagan",
    "Kalian",
    "Luayan",
    "Paitan",
    "Panapan",
    "Tenok",
    "Tinambulan",
    "Tumbao",
  ],
  "1903833000": [
    "Kabuling",
    "Kayaga",
    "Kayupo",
    "Lepak",
    "Lower Dilag",
    "Malangit",
    "Pandag",
    "Upper Dilag",
  ],
  "1903834000": [
    "Balong",
    "Damatog",
    "Gayonga",
    "Guiawa",
    "Indatuan",
    "Kapimpilan",
    "Libungan",
    "Montay",
    "Paulino Labio",
    "Sabaken",
    "Tumaguinting",
  ],
  "1903835000": [
    "Kubentong",
    "Labu-labu I",
    "Labu-labu II",
    "Limpongo",
    "Macalag",
    "Sayap",
    "Taib",
    "Talibadok",
    "Tuayan",
    "Tuayan I",
    "Tuntungan",
  ],
  "1903836000": [
    "Alonganan",
    "Andavit",
    "Balanakan",
    "Buayan",
    "Butilen",
    "Dado",
    "Damabalas",
    "Duaminanga",
    "Kalipapa",
    "Liong",
    "Magaslong",
    "Masigay",
    "Pagatin",
    "Pandi",
    "Penditen",
    "Sambulawan",
    "Tee",
  ],
  "1903837000": [
    "Bakat",
    "Dale-Bong",
    "Dasawao",
    "Datu Bakal",
    "Datu Kilay",
    "Duguengen",
    "Ganta",
    "Inaladan",
    "Libutan",
    "Linantangan",
    "Nabundas",
    "Pagatin",
    "Pagatin",
    "Pamalian",
    "Pikeg",
    "Pusao",
  ],
  "1906601000": [
    "Adjid",
    "Bangalan",
    "Bato-bato",
    "Buanza",
    "Bud-Taran",
    "Bunut",
    "Jati-Tunggal",
    "Kabbon Maas",
    "Kagay",
    "Kajatian",
    "Kan Islam",
    "Kandang Tukay",
    "Karawan",
    "Katian",
    "Kuppong",
    "Lambayong",
    "Langpas",
    "Licup",
    "Malimbaya",
    "Manggis",
    "Manilop",
    "Paligue",
    "Panabuan",
    "Panglima Misuari",
    "Pasil",
    "Poblacion",
    "Sapah Malaum",
    "Sawaki",
    "Sionogan",
    "Tagbak",
    "Timbangan",
    "Tubig Dakulah",
    "Tubig Parang",
    "Tumantangis",
  ],
  "1906602000": [
    "Alat",
    "Asturias",
    "Bus-bus",
    "Chinese Pier",
    "San Raymundo",
    "Takut-takut",
    "Tulay",
    "Walled City (Pob.)",
  ],
  "1906603000": [
    "Kambing",
    "Kanlagay",
    "Karungdong (Pob.)",
    "Masjid Bayle",
    "Masjid Punjungan",
    "Pang",
    "Pangdan Pangdan",
    "Pitogo",
    "Tunggol",
  ],
  "1906604000": [
    "Bual",
    "Guimbaun",
    "Kan-Bulak",
    "Kan-Mindus",
    "Lambago",
    "Lianutan",
    "Lingah",
    "Mananti",
    "Niog-niog",
    "Tandu-Bato",
    "Tubig-Puti (Pob.)",
    "Tulayan Island",
  ],
  "1906605000": [
    "Anak Jati",
    "Bato Ugis",
    "Bualo Lahi",
    "Bualo Lipid",
    "Bulabog",
    "Duhol Kabbon",
    "Gulangan",
    "Ipil",
    "Kandang",
    "Kapok-Punggol",
    "Kulasi",
    "Labah",
    "Lagasan Asibih",
    "Lantong",
    "Lapa",
    "Laud Kulasi",
    "Laum Maimbung",
    "Lower Tambaking",
    "Lunggang",
    "Matatal",
    "Patao",
    "Poblacion",
    "Ratag Limbon",
    "Tabu-Bato",
    "Tandu Patong",
    "Tubig-Samin",
    "Upper Tambaking",
  ],
  "1906606000": [
    "Bangas (Pob.)",
    "Bubuan",
    "Kabuukan",
    "Pag-asinan",
    "Teomabal",
  ],
  "1906607000": [
    "Asin",
    "Bakud",
    "Bangday",
    "Baunoh",
    "Bitanag",
    "Bud Seit",
    "Bulangsi",
    "Datag",
    "Kamalig",
    "Kan Asaali",
    "Kan Ukol",
    "Kan-Dayok",
    "Kan-Sipat",
    "Kawasan",
    "Kulay-kulay",
    "Lakit",
    "Lower Patibulan",
    "Lunggang",
    "Parang",
    "Pugad Manaul",
    "Puhagan",
    "Seit Higad",
    "Seit Lake (Pob.)",
    "Su-uh",
    "Tabu Manuk",
    "Tandu-tandu",
    "Tayungan",
    "Tinah",
    "Tubig Gantang",
    "Tubig Jati",
    "Upper Patibulan",
  ],
  "1906608000": [
    "Alu Bunah",
    "Bangkilay",
    "Kawitan",
    "Kehi Niog",
    "Lantong Babag",
    "Lumah Dapdap",
    "Pandan Niog",
    "Panducan",
    "Panitikan",
    "Patutol",
    "Se-ipang",
    "Simbahan (Pob.)",
    "Suang Bunah",
    "Tonggasang",
    "Tubig Nonok",
    "Tubig Sallang",
  ],
  "1906609000": [
    "Alu Layag-Layag",
    "Alu Pangkoh",
    "Bagsak",
    "Bawisan",
    "Biid",
    "Bukid",
    "Buli Bawang",
    "Buton",
    "Buton Mahablo",
    "Danapa",
    "Duyan Kabao",
    "Gimba Lagasan",
    "Kaha",
    "Kahoy Sinah",
    "Kanaway",
    "Kutah Sairap",
    "Lagasan Higad",
    "Lanao Dakula",
    "Laum Buwahan",
    "Laum Suwah",
    "Liang",
    "Linuho",
    "Lipunos",
    "Lower Sampunay",
    "Lumbaan Mahaba",
    "Lungan Gitong",
    "Lupa Abu",
    "Nonokan",
    "Paugan",
    "Payuhan",
    "Piyahan",
    "Poblacion",
    "Saldang",
    "Sampunay",
    "Silangkan",
    "Taingting",
    "Tikong",
    "Tukay",
    "Tumangas",
    "Wanni Piyanjihan",
  ],
  "1906610000": [
    "Andalan",
    "Daungdong",
    "Kamawi",
    "Kanjarang",
    "Kayawan (Pob.)",
    "Kiput",
    "Likud",
    "Luuk-tulay",
    "Niog-niog",
    "Patian",
    "Pisak-pisak",
    "Saimbangon",
    "Sangkap",
    "Timuddas",
  ],
  "1906611000": [
    "Anuling",
    "Bakong",
    "Bangkal",
    "Bonbon",
    "Buhanginan",
    "Bungkaung",
    "Danag",
    "Gandasuli",
    "Igasan",
    "Kabbon Takas",
    "Kadday Mampallam",
    "Kan Ague",
    "Kaunayan",
    "Langhub",
    "Latih",
    "Liang",
    "Maligay",
    "Mauboh",
    "Pangdanon",
    "Panglayahan",
    "Pansul",
    "Patikul Higad",
    "Sandah",
    "Taglibi (Pob.)",
    "Tandu-Bagua",
    "Tanum",
    "Taung",
    "Timpok",
    "Tugas",
    "Umangay",
  ],
  "1906612000": [
    "Bakud",
    "Buan",
    "Bulansing Tara",
    "Bulihkullul",
    "Campo Islam",
    "Duggo",
    "Duhol Tara",
    "East Kungtad",
    "East Sisangat",
    "Ipil",
    "Jambangan",
    "Kabubu",
    "Kong-Kong Laminusa",
    "Kud-kud",
    "Kungtad West",
    "Latung",
    "Luuk Laminusa",
    "Luuk Tara",
    "Manta",
    "Minapan",
    "Nipa-nipa",
    "North Laud",
    "North Manta",
    "North Musu Laud",
    "North Silumpak",
    "Pislong",
    "Poblacion",
    "Punungan",
    "Puukan Laminusa",
    "Ratag",
    "Sablay",
    "Sarukot",
    "Siburi",
    "Singko",
    "Siolakan",
    "Siowing",
    "Sipanding",
    "Sisangat",
    "Siundoh",
    "South Musu Laud",
    "South Silumpak",
    "Southwestern Bulikullul",
    "Subah Buaya",
    "Tampakan Laminusa",
    "Tengah Laminusa",
    "Tong Laminusa",
    "Tong-tong",
    "Tonglabah",
    "Tubig Kutah",
    "Tulling",
  ],
  "1906613000": [
    "Andalan",
    "Bagsak",
    "Bandang",
    "Bilaan (Pob.)",
    "Bud Bunga",
    "Buntod",
    "Buroh",
    "Dalih",
    "Gata",
    "Kabatuhan Bilaan",
    "Kabatuhan Tiis",
    "Kabungkol",
    "Kagay",
    "Kahawa",
    "Kandaga",
    "Kanlibot",
    "Kiutaan",
    "Kuhaw",
    "Kulamboh",
    "Kuttong",
    "Lagtoh",
    "Lambanah",
    "Liban",
    "Liu-Bud Pantao",
    "Lower Binuang",
    "Lower Kamuntayan",
    "Lower Laus",
    "Lower Sinumaan",
    "Lower Talipao",
    "Lumbayao",
    "Lumping Pigih Daho",
    "Lungkiaban",
    "Mabahay",
    "Mahala",
    "Mampallam",
    "Marsada",
    "Mauboh",
    "Mungit-mungit",
    "Niog-Sangahan",
    "Pantao",
    "Samak",
    "Talipao Proper",
    "Tampakan",
    "Tiis",
    "Tinggah",
    "Tubod",
    "Tuyang",
    "Upper Binuang",
    "Upper Kamuntayan",
    "Upper Laus",
    "Upper Sinumaan",
    "Upper Talipao",
  ],
  "1906614000": [
    "Alu-Kabingaan",
    "Banting",
    "Hawan",
    "Kalang (Pob.)",
    "Kamaunggi",
    "Kanaway",
    "Kanmangon",
    "Kaumpang",
    "Pagatpat",
    "Pangdan",
    "Puok",
    "Sayli",
    "Sumambat",
    "Tangkapaan",
    "Tulakan",
  ],
  "1906615000": [
    "Bakkaan",
    "Bangalaw",
    "Danao",
    "Dungon",
    "Kahikukuk",
    "Luuk (Pob.)",
    "North Paarol",
    "Sigumbal",
    "South Paarol",
    "Tabialan",
    "Tainga-Bakkao",
    "Tambun-bun",
    "Tattalan",
    "Tinutungan",
  ],
  "1906616000": [
    "Gagguil",
    "Gata-gata",
    "Jinggan",
    "Kamih-Pungud",
    "Lihbug Kabaw",
    "Likbah",
    "Lubuk-lubuk",
    "Marsada",
    "Paiksa",
    "Pandakan",
    "Punay (Pob.)",
    "Tiptipon",
  ],
  "1906617000": [
    "Alu Bus-Bus",
    "Alu-Duyong",
    "Bas Lugus",
    "Gapas Rugasan",
    "Gapas Tubig Tuwak",
    "Huwit-huwit Bas Nonok",
    "Huwit-huwit Proper",
    "Kutah Parang",
    "Laha",
    "Larap",
    "Lugus Proper",
    "Mangkallay",
    "Mantan",
    "Pait",
    "Parian Kayawan",
    "Sibul",
    "Tingkangan",
  ],
  "1906618000": [
    "Baligtang",
    "Bud Sibaud",
    "Hambilan",
    "Kabbon",
    "Lahi",
    "Lapak",
    "Laud Sibaud",
    "Malanta",
    "Mamanok",
    "North Manubul",
    "Parian Dakula",
    "Sibaud Proper",
    "Siganggang",
    "South Manubul",
    "Suba-suba",
    "Tenga Manubul",
  ],
  "1906619000": [
    "Andalan",
    "Angilan",
    "Capual Island",
    "Huwit-huwit",
    "Lahing-Lahing",
    "Niangkaan",
    "Sucuban",
    "Tangkuan",
  ],
  "1907001000": [
    "Balimbing Proper",
    "Batu-batu (Pob.)",
    "Bauno Garing",
    "Belatan Halu",
    "Buan",
    "Dungon",
    "Karaha",
    "Kulape",
    "Liyaburan",
    "Luuk Buntal",
    "Magsaggaw",
    "Malacca",
    "Parangan",
    "Sumangday",
    "Tabunan",
    "Tundon",
    "Tungbangkaw",
  ],
  "1907002000": [
    "Bongao Poblacion",
    "Ipil",
    "Kamagong",
    "Karungdong",
    "Lagasan",
    "Lakit Lakit",
    "Lamion",
    "Lapid Lapid",
    "Lato Lato",
    "Luuk Pandan",
    "Luuk Tulay",
    "Malassa",
    "Mandulan",
    "Masantong",
    "Montay Montay",
    "Nalil",
    "Pababag",
    "Pag-asa",
    "Pagasinan",
    "Pagatpat",
    "Pahut",
    "Pakias",
    "Paniongan",
    "Pasiagan",
    "Sanga-sanga",
    "Silubog",
    "Simandagit",
    "Sumangat",
    "Tarawakan",
    "Tongsinah",
    "Tubig Basag",
    "Tubig Tanah",
    "Tubig-Boh",
    "Tubig-Mampallam",
    "Ungus-ungus",
  ],
  "1907003000": [
    "Boki",
    "Duhul Batu",
    "Erok-erok",
    "Guppah",
    "Kompang",
    "Liyubud",
    "Lubbak Parang",
    "Lupa Pula (Pob.)",
    "Mahalo",
    "Pawan",
    "Sapa",
    "Sikub",
    "Tabulian",
    "Tanduan",
    "Umus Mataha",
  ],
  "1907004000": [
    "Bagid*",
    "Bakong",
    "Doh-Tong",
    "Luuk Datan",
    "Manuk Mangkaw",
    "Maruwa",
    "Mongkay",
    "Pagasinan",
    "Panglima Mastul",
    "Sukah-Bulan",
    "Tampakan (Pob.)",
    "Timundon",
    "Tonggosong",
    "Tubig Indangan",
    "Ubol",
  ],
  "1907005000": [
    "Datu Baguinda Putih",
    "Imam Sapie",
    "North Larap",
    "Panglima Alari",
    "Sipangkot",
    "Sitangkai Poblacion",
    "South Larap",
    "Tongmageng",
    "Tongusong",
  ],
  "1907006000": [
    "Babagan",
    "Bengkol",
    "Bintawlan",
    "Bohe",
    "Bubuan",
    "Bunay Bunay Center",
    "Bunay Bunay Lookan",
    "Bunay Bunay Tong",
    "East Talisay",
    "Lahad Dampong",
    "Laitan",
    "Lambi-lambian",
    "Laud",
    "Likud Dampong",
    "Likud Tabawan",
    "Nunuk",
    "Nusa",
    "Nusa-nusa",
    "Pampang",
    "Putat",
    "Sollogan",
    "Talisay",
    "Tampakan Dampong",
    "Tangngah",
    "Tinda-tindahan",
    "Tong Tampakan",
    "Tubig Dayang",
    "Tubig Dayang Center",
    "Tubig Dayang Riverside",
    "Tukkai",
    "Unas-unas",
  ],
  "1907007000": [
    "Baliungan",
    "Ballak",
    "Butun",
    "Himbah",
    "Kakoong",
    "Kalang-kalang",
    "Kepeng",
    "Lahay-lahay",
    "Naungan",
    "Salamat",
    "Sallangan",
    "Sapa",
    "Sibakloon",
    "Silantup",
    "Tandubato",
    "Tangngah",
    "Tapian",
    "Tapian Sukah",
    "Taruk",
    "Tongbangkaw",
  ],
  "1907008000": ["Likud Bakkao", "Taganak Poblacion"],
  "1907009000": [
    "Adnin",
    "Bakaw-bakaw",
    "Bakong",
    "Bas-bas Proper",
    "BasLikud",
    "Basnunuk",
    "Darussalam",
    "Jakarta",
    "Kalupag",
    "Kiniktal",
    "Languyan Proper (Pob.)",
    "Marang-marang",
    "Maraning",
    "Parang Pantay",
    "Sikullis",
    "Simalak",
    "Tubig Dakula",
    "Tuhog-tuhog",
    "Tumahubong",
    "Tumbagaan",
  ],
  "1907010000": [
    "Baldatal Islam",
    "Butun",
    "Dalo-dalo",
    "Kohec",
    "Lakit-lakit",
    "Latuan",
    "Look Natuh",
    "Lookan Banaran",
    "Lookan Latuan",
    "Malanta",
    "Mantabuan Tabunan",
    "Nunuk Likud Sikubong",
    "Palate Gadjaminah",
    "Pamasan",
    "Sapa-sapa (Pob.)",
    "Sapaat",
    "Sukah-sukah",
    "Tabunan Likud Sikubong",
    "Tangngah",
    "Tapian Bohe North",
    "Tapian Bohe South",
    "Tonggusong Banaran",
    "Tup-tup Banaran",
  ],
  "1907011000": [
    "Ambulong Sapal",
    "Datu Amilhamja Jaafar",
    "Hadji Imam Bidin",
    "Hadji Mohtar Sulayman",
    "Hadji Taha",
    "Imam Hadji Mohammad",
    "Ligayan",
    "Nunukan",
    "Sheik Makdum",
    "Sibutu (Pob.)",
    "Talisay",
    "Tandu Banak",
    "Taungoh",
    "Tongehat",
    "Tongsibalo",
    "Ungus-ungus",
  ],
  "1999901000": [
    "Kib-Ayao",
    "Kitulaan",
    "Langogan",
    "Manarapan",
    "Nasapian",
    "Pebpoloan",
    "Tupig",
  ],
  "1999902000": [
    "Buluan",
    "Nanga-an",
    "Pedtad",
    "Sanggadong",
    "Simbuhay",
    "Simone",
    "Tamped",
  ],
  "1999903000": [
    "Central Labas",
    "Kapinpilan",
    "Malingao",
    "Mudseng",
    "Sambulawan",
    "Tugal",
    "Tumbras",
  ],
  "1999904000": [
    "Damatulan",
    "Kadigasan",
    "Kadingilan",
    "Kudarangan",
    "Nabalawag",
    "Olandang",
  ],
  "1999905000": [
    "Balacayon",
    "Buricain",
    "Datu Binasing",
    "Datu Mantil",
    "Kadingilan",
    "Libungan Torreta",
    "Lower Baguer",
    "Lower Pangangkalan",
    "Matilac",
    "Patot",
    "Simsiman",
    "Upper Pangangkalan",
  ],
  "1999906000": [
    "Balungis",
    "Batulawan",
    "Fort Pikit",
    "Gokoton",
    "Nabundas",
    "Nalapaan",
    "Nunguan",
    "Panicupan",
  ],
  "1999907000": [
    "Bagoaingud",
    "Barungis",
    "Buliok",
    "Bulol",
    "Gligli",
    "Kabasalan",
    "Macabual",
    "Rajah Muda",
  ],
  "1999908000": [
    "Balong",
    "Bualan",
    "Dunguan",
    "Lagunde",
    "Macasendeg",
    "Manaulanan",
    "Pamalian",
    "Tapodoc",
  ],
};
