/**
 * Per-product KYC declarations — admin-configured questions a borrower
 * answers as part of an application (source of funds, purpose, PEP
 * status, …). Distinct from the credit-scoring survey, which feeds the
 * score; declarations are compliance answers, and they gate approval
 * the same way document verification does.
 *
 * The question set lives on LoanProduct.kycQuestions as JSON; answers
 * are snapshotted onto LoanApplication.kycDeclarations WITH the
 * question text as it stood — the admin can rewrite the questionnaire
 * tomorrow, and what a borrower actually attested to must not rewrite
 * itself along with it.
 */

export type KycQuestionType = "TEXT" | "YES_NO" | "NUMBER" | "SELECT";

export interface KycQuestion {
  /** Stable id — answers key on it. Slug generated by the builder UI. */
  id: string;
  label: string;
  type: KycQuestionType;
  /** SELECT only. */
  options?: string[];
  /** Required answers block approval; optional ones are just recorded. */
  required: boolean;
  /** Helper copy under the field. */
  hint?: string;
  /**
   * Free-text grouping shown as a heading ("Property", "Compliance").
   * Free text rather than an enum: what a lender groups by is their
   * policy, and every product would need different enum members.
   * Blank groups under "General".
   */
  category?: string;
}

/** One snapshotted question + its answer as attested. */
export interface KycDeclarationItem {
  id: string;
  label: string;
  type: KycQuestionType;
  /**
   * Kept in the snapshot so a later edit (the KYC-stage flow) can still
   * validate a SELECT answer against the options as offered at apply
   * time — not against whatever the admin has since changed them to.
   */
  options?: string[];
  required: boolean;
  /** Snapshotted so the review panel groups as it did at apply time. */
  category?: string;
  /** Null = not answered (yet). YES_NO stores booleans. */
  answer: string | number | boolean | null;
}

/** What LoanApplication.kycDeclarations holds. */
export interface KycDeclarations {
  items: KycDeclarationItem[];
  answeredAt: string | null;
  answeredById: string | null;
}

/** Raw answers as they arrive on the wire: question id → value. */
export type KycAnswers = Record<string, string | number | boolean | null>;

export interface DeclarationValidation {
  /** Every REQUIRED question has a well-formed answer. */
  complete: boolean;
  /** Required question ids with no answer. */
  missing: string[];
  /** Answers that don't fit their question's type/options. */
  invalid: Array<{ id: string; reason: string }>;
}

/**
 * Check `answers` against the product's questions.
 *
 * Missing OPTIONAL answers are fine. Missing REQUIRED answers are
 * reported but don't make the input invalid — submit accepts partial
 * declarations (they can be completed at the KYC stage) and only
 * approval insists on completeness. Malformed answers are always
 * invalid: a NUMBER answering "abc" is a bug or tampering, not a
 * borrower who hasn't finished.
 */
export function validateDeclarations(
  questions: KycQuestion[],
  answers: KycAnswers,
): DeclarationValidation {
  const missing: string[] = [];
  const invalid: DeclarationValidation["invalid"] = [];

  for (const q of questions) {
    const value = answers[q.id];
    if (value === undefined || value === null || value === "") {
      if (q.required) missing.push(q.id);
      continue;
    }
    switch (q.type) {
      case "TEXT":
        if (typeof value !== "string") {
          invalid.push({ id: q.id, reason: "Expected text" });
        } else if (value.length > 1000) {
          invalid.push({ id: q.id, reason: "Answer too long (1000 max)" });
        }
        break;
      case "YES_NO":
        if (typeof value !== "boolean") {
          invalid.push({ id: q.id, reason: "Expected yes/no" });
        }
        break;
      case "NUMBER":
        if (typeof value !== "number" || !Number.isFinite(value)) {
          invalid.push({ id: q.id, reason: "Expected a number" });
        }
        break;
      case "SELECT":
        if (typeof value !== "string" || !(q.options ?? []).includes(value)) {
          invalid.push({ id: q.id, reason: "Not one of the offered options" });
        }
        break;
    }
  }

  // Answers for questions that no longer exist are ignored rather than
  // rejected: the admin may have removed a question between the form
  // render and the submit, and punishing the borrower for that race
  // helps nobody. The snapshot only ever contains current questions.
  return { complete: missing.length === 0, missing, invalid };
}

/**
 * Freeze the current questions + answers into the application-side
 * snapshot. Unanswered questions are included with `answer: null` so
 * the record shows what was ASKED, not only what was answered — an
 * unanswered required declaration is a fact worth keeping.
 */
export function snapshotDeclarations(
  questions: KycQuestion[],
  answers: KycAnswers,
  actor: { id: string } | null,
): KycDeclarations {
  const anyAnswered = questions.some(
    (q) => answers[q.id] !== undefined && answers[q.id] !== null,
  );
  return {
    items: questions.map((q) => ({
      id: q.id,
      label: q.label,
      type: q.type,
      ...(q.options ? { options: q.options } : {}),
      ...(q.category ? { category: q.category } : {}),
      required: q.required,
      answer: answers[q.id] ?? null,
    })),
    answeredAt: anyAnswered ? new Date().toISOString() : null,
    answeredById: anyAnswered ? (actor?.id ?? null) : null,
  };
}

/**
 * Merge new answers into an existing snapshot — the KYC-stage edit.
 *
 * Answers validate against the SNAPSHOT's questions (types and options
 * as offered at apply time), provided ids overwrite, everything else is
 * kept, and attribution refreshes to whoever answered last. Unknown ids
 * are ignored for the same race-with-the-admin reason as
 * validateDeclarations.
 */
export function answerDeclarations(
  current: KycDeclarations,
  answers: KycAnswers,
  actor: { id: string } | null,
):
  | { ok: true; next: KycDeclarations }
  | { ok: false; invalid: DeclarationValidation["invalid"] } {
  const questions: KycQuestion[] = current.items.map((i) => ({
    id: i.id,
    label: i.label,
    type: i.type,
    options: i.options,
    category: i.category,
    required: i.required,
  }));
  const { invalid } = validateDeclarations(questions, answers);
  if (invalid.length > 0) return { ok: false, invalid };

  return {
    ok: true,
    next: {
      items: current.items.map((i) =>
        answers[i.id] !== undefined ? { ...i, answer: answers[i.id]! } : i,
      ),
      answeredAt: new Date().toISOString(),
      answeredById: actor?.id ?? null,
    },
  };
}

/**
 * Completeness of an already-stored snapshot — the approval gate reads
 * this, not the live product questions. Deliberate: the contract is
 * "answer what you were asked when you applied"; an admin adding a new
 * required question tomorrow must not retroactively block a decision
 * on yesterday's application.
 */
export function declarationsComplete(
  declarations: KycDeclarations | null | undefined,
): { complete: boolean; missing: KycDeclarationItem[] } {
  const items = declarations?.items ?? [];
  const missing = items.filter(
    (i) => i.required && (i.answer === null || i.answer === ""),
  );
  return { complete: missing.length === 0, missing };
}

/**
 * Group questions (or snapshot items) under their category heading,
 * preserving the author's ordering: categories appear in the order
 * their first question does, and questions keep their order within.
 *
 * Shared so the builder, the capture forms and the review panel all
 * group identically — three hand-rolled groupings would drift, and a
 * borrower seeing a different arrangement from the officer reviewing
 * them is exactly the confusion categories exist to remove.
 *
 * Uncategorised questions collect under "General" rather than floating
 * loose, so the rendering is a list of groups in every case.
 */
export const DEFAULT_CATEGORY = "General";

export function groupByCategory<T extends { category?: string }>(
  items: T[],
): Array<{ category: string; items: T[] }> {
  const order: string[] = [];
  const groups = new Map<string, T[]>();
  for (const item of items) {
    const key = item.category?.trim() || DEFAULT_CATEGORY;
    const bucket = groups.get(key);
    if (bucket) {
      bucket.push(item);
    } else {
      groups.set(key, [item]);
      order.push(key);
    }
  }
  return order.map((category) => ({ category, items: groups.get(category)! }));
}
