import { describe, expect, it } from "vitest";

import { type InstallmentDue, allocatePayment } from "./posting";

/**
 * GOLDEN TESTS — `allocatePayment` (posting.ts).
 *
 * Written against the CURRENT implementation and committed passing BEFORE
 * it is touched, per §81. The §26 work adds fee and penalty tiers and makes
 * the order configurable; these exist so that "a loan on the existing order
 * pays exactly what it paid yesterday" is a claim with evidence behind it
 * rather than an intention.
 *
 * READ THIS BEFORE CHANGING A NUMBER IN THIS FILE. A figure here moving is
 * a borrower's money moving. If a deliberate change makes one of these
 * wrong, the number may be updated — but only with a written reason in the
 * commit, and only after confirming the change was meant to reach loans on
 * the legacy order at all.
 *
 * ── What the current implementation computes, exactly ───────────────────
 *
 * `round2(n)` is `Math.round(n * 100) / 100` throughout.
 *
 *   remaining ← round2(amount)
 *   interest ← 0; principal ← 0; perInstallment ← []
 *   for index in 0 .. installments.length-1:
 *     if remaining <= 0: BREAK          ← stops the whole loop, not `continue`
 *     interestOpen  ← max(0, round2(interestDue  - (interestPaid  ?? 0)))
 *     principalOpen ← max(0, round2(principalDue - (principalPaid ?? 0)))
 *     interestPart  ← min(remaining, interestOpen)
 *     remaining     ← round2(remaining - interestPart)
 *     principalPart ← min(remaining, principalOpen)
 *     remaining     ← round2(remaining - principalPart)
 *     if interestPart <= 0 and principalPart <= 0: CONTINUE   ← no slice row
 *     interest  ← round2(interest + interestPart)
 *     principal ← round2(principal + principalPart)
 *     push { index, interest: interestPart, principal: principalPart }
 *   return { interest, principal, overpayment: round2(remaining), perInstallment }
 *
 * The order is INTEREST then PRINCIPAL **within each instalment**, walking
 * instalments in the order the caller passed them (`recordPayment` passes
 * open rows ordered by `installmentNo` ascending). It is emphatically NOT
 * "all interest across the whole schedule, then all principal" — a payment
 * spanning two instalments pays #1's principal before it touches #2's
 * interest. There is no fee tier and no penalty tier: those two words do
 * not appear in the function.
 *
 * Rounding lands in four places and nowhere else: the incoming amount, each
 * open balance, `remaining` after each subtraction, and the two running
 * totals. The per-slice figures pushed onto `perInstallment` are NOT
 * separately rounded — they are `Math.min` of values that are already
 * 2-decimal, so they are exact whenever the inputs are.
 *
 * Two behaviours that read like accidents and are not:
 *
 *   - `max(0, …)` on both open balances. An over-credited row — a repair
 *     script, a manual edit — must not hand back negative headroom and
 *     silently inflate the next instalment's slice.
 *   - `continue` (not `break`) on a wholly-settled instalment, so a row
 *     with nothing left open is stepped over and later rows still get
 *     paid. Contrast the `break` at the top, which fires only when the
 *     MONEY is exhausted.
 *
 * Underpayment is not a distinct code path: the money runs out, `remaining`
 * hits 0, the loop breaks, and the instalments it never reached are simply
 * untouched. Overpayment is everything left after the last instalment is
 * full, and comes back in its own bucket — `recordPayment` books it to
 * Customer Advances, never as extra principal.
 *
 * ── The schedule these figures come from ────────────────────────────────
 *
 * A real declining-balance amortisation: ₱50,000.00 over 6 monthly
 * instalments at 18% p.a., generated by `@loan/loans` `computeAmortizationFor`
 * — the same function that writes `LoanSchedule` rows in production.
 *
 *   #   principalDue   interestDue   totalDue
 *   1      8,026.26        750.00     8,776.26
 *   2      8,146.65        629.61     8,776.26
 *   3      8,268.85        507.41     8,776.26
 *   4      8,392.89        383.37     8,776.26
 *   5      8,518.78        257.48     8,776.26
 *   6      8,646.57        129.70     8,776.27   ← absorbs the rounding drift
 *   ───────────────────────────────────────────
 *      50,000.00      2,657.57    52,657.57
 *
 * Every peso figure asserted below was derived by hand from the algorithm
 * above and the table here, independently of running the code. A failure
 * therefore means the code and the derivation disagree — which is the
 * whole point.
 */

/** The six rows above, fresh (nothing paid). */
const SCHEDULE: InstallmentDue[] = [
  { interestDue: 750.0, principalDue: 8026.26 },
  { interestDue: 629.61, principalDue: 8146.65 },
  { interestDue: 507.41, principalDue: 8268.85 },
  { interestDue: 383.37, principalDue: 8392.89 },
  { interestDue: 257.48, principalDue: 8518.78 },
  { interestDue: 129.7, principalDue: 8646.57 },
];

const TOTAL_INTEREST = 2657.57;
const TOTAL_PRINCIPAL = 50000.0;
const TOTAL_DUE = 52657.57;

/** Fresh copy — `allocatePayment` does not mutate, but the tests shouldn't rely on that. */
const fresh = (): InstallmentDue[] => SCHEDULE.map((r) => ({ ...r }));

describe("allocatePayment — exact payment of one instalment", () => {
  /*
   * ₱8,776.26 against a fresh schedule.
   *   #1 interest  750.00 → remaining 8,026.26
   *   #1 principal 8,026.26 → remaining 0.00
   *   #2 is never reached: the loop breaks on `remaining <= 0`.
   */
  it("clears instalment 1 to the centavo and touches nothing else", () => {
    const r = allocatePayment(8776.26, fresh());

    expect(r.interest).toBe(750.0);
    expect(r.principal).toBe(8026.26);
    expect(r.overpayment).toBe(0);
    expect(r.perInstallment).toEqual([
      { index: 0, interest: 750.0, principal: 8026.26 },
    ]);
  });

  it("conserves the payment exactly — no centavo created or lost", () => {
    const r = allocatePayment(8776.26, fresh());
    expect(r.interest + r.principal + r.overpayment).toBe(8776.26);
  });
});

describe("allocatePayment — partial payment", () => {
  /*
   * ₱5,000.00 against a fresh schedule.
   *   #1 interest  750.00   → remaining 4,250.00
   *   #1 principal 4,250.00 (min of 4,250.00 and 8,026.26) → remaining 0.00
   * Instalment 1 is left short by 8,026.26 - 4,250.00 = 3,776.26 of principal.
   */
  it("takes all of the interest first, then whatever principal it reaches", () => {
    const r = allocatePayment(5000, fresh());

    expect(r.interest).toBe(750.0);
    expect(r.principal).toBe(4250.0);
    expect(r.overpayment).toBe(0);
    expect(r.perInstallment).toEqual([
      { index: 0, interest: 750.0, principal: 4250.0 },
    ]);
  });

  it("leaves instalments 2..6 entirely untouched", () => {
    const r = allocatePayment(5000, fresh());
    // Only index 0 appears. This is the guarantee `recordPayment` relies on
    // when it decides which schedule rows to write back.
    expect(r.perInstallment.map((p) => p.index)).toEqual([0]);
  });

  /*
   * A second partial against the progress the first one left. This is the
   * `interestPaid`/`principalPaid` path — without it the 750.00 of interest
   * would be recognised as income a second time.
   */
  it("does not re-charge interest on a follow-up partial", () => {
    const r = allocatePayment(3000, [
      {
        interestDue: 750.0,
        principalDue: 8026.26,
        interestPaid: 750.0,
        principalPaid: 4250.0,
      },
      ...fresh().slice(1),
    ]);

    // interestOpen is 0, so the whole 3,000.00 is principal.
    expect(r.interest).toBe(0);
    expect(r.principal).toBe(3000.0);
    expect(r.overpayment).toBe(0);
    expect(r.perInstallment).toEqual([
      { index: 0, interest: 0, principal: 3000.0 },
    ]);
  });
});

describe("allocatePayment — a payment spanning instalments", () => {
  /*
   * ₱20,000.00 against a fresh schedule.
   *   #1 interest    750.00 → 19,250.00
   *   #1 principal 8,026.26 → 11,223.74
   *   #2 interest    629.61 → 10,594.13
   *   #2 principal 8,146.65 →  2,447.48
   *   #3 interest    507.41 →  1,940.07
   *   #3 principal 1,940.07 (min of 1,940.07 and 8,268.85) → 0.00
   *   #4 breaks.
   *
   *   interest  =   750.00 + 629.61 + 507.41   = 1,887.02
   *   principal = 8,026.26 + 8,146.65 + 1,940.07 = 18,112.98
   *   1,887.02 + 18,112.98 = 20,000.00
   */
  it("pays #1's principal before it touches #2's interest", () => {
    const r = allocatePayment(20_000, fresh());

    expect(r.interest).toBe(1887.02);
    expect(r.principal).toBe(18_112.98);
    expect(r.overpayment).toBe(0);
    expect(r.perInstallment).toEqual([
      { index: 0, interest: 750.0, principal: 8026.26 },
      { index: 1, interest: 629.61, principal: 8146.65 },
      { index: 2, interest: 507.41, principal: 1940.07 },
    ]);
  });

  it("conserves the payment across the three instalments it reached", () => {
    const r = allocatePayment(20_000, fresh());
    expect(r.interest + r.principal + r.overpayment).toBe(20_000);
  });
});

describe("allocatePayment — overpayment spanning instalments", () => {
  /*
   * ₱53,000.00 against a fresh 52,657.57 book. Every instalment settles and
   * 53,000.00 - 52,657.57 = 342.43 is left over.
   */
  it("fills all six instalments and returns the excess in its own bucket", () => {
    const r = allocatePayment(53_000, fresh());

    expect(r.interest).toBe(TOTAL_INTEREST);
    expect(r.principal).toBe(TOTAL_PRINCIPAL);
    expect(r.overpayment).toBe(342.43);
    expect(r.perInstallment).toHaveLength(6);
  });

  it("never folds the excess into principal", () => {
    // Crediting Loans Receivable past zero misstates the asset — the reason
    // overpayment is a separate bucket at all.
    const r = allocatePayment(53_000, fresh());
    expect(r.principal).toBe(TOTAL_PRINCIPAL);
    expect(r.principal).toBeLessThanOrEqual(TOTAL_PRINCIPAL);
  });

  it("gives every instalment exactly its own due", () => {
    const r = allocatePayment(53_000, fresh());
    expect(r.perInstallment).toEqual([
      { index: 0, interest: 750.0, principal: 8026.26 },
      { index: 1, interest: 629.61, principal: 8146.65 },
      { index: 2, interest: 507.41, principal: 8268.85 },
      { index: 3, interest: 383.37, principal: 8392.89 },
      { index: 4, interest: 257.48, principal: 8518.78 },
      { index: 5, interest: 129.7, principal: 8646.57 },
    ]);
  });

  it("conserves a payment that exceeds the whole book", () => {
    const r = allocatePayment(53_000, fresh());
    expect(r.interest + r.principal + r.overpayment).toBe(53_000);
  });

  /* A payment on a book with nothing open is pure overpayment. */
  it("returns the whole amount as overpayment when every row is settled", () => {
    const settled = SCHEDULE.map((row) => ({
      ...row,
      interestPaid: row.interestDue,
      principalPaid: row.principalDue,
    }));
    const r = allocatePayment(1_500, settled);

    expect(r.interest).toBe(0);
    expect(r.principal).toBe(0);
    expect(r.overpayment).toBe(1_500);
    // `continue`, not `break` — every row is stepped over and none produces
    // a slice, so the caller writes nothing back to the schedule.
    expect(r.perInstallment).toEqual([]);
  });
});

describe("allocatePayment — settling an instalment precisely", () => {
  /*
   * ₱3,000.00 then ₱5,776.26 settles instalment 1 to the exact centavo.
   *   first : interest 750.00, principal 2,250.00
   *   second: interestOpen 0.00, principalOpen round2(8,026.26 - 2,250.00)
   *           = 5,776.26 → the whole payment is principal.
   */
  it("lands the second payment exactly on the remaining principal", () => {
    const r = allocatePayment(5776.26, [
      {
        interestDue: 750.0,
        principalDue: 8026.26,
        interestPaid: 750.0,
        principalPaid: 2250.0,
      },
      ...fresh().slice(1),
    ]);

    expect(r.interest).toBe(0);
    expect(r.principal).toBe(5776.26);
    expect(r.overpayment).toBe(0);
    // A zero-interest slice is still a slice: `continue` only fires when
    // BOTH parts are zero, and the principal part is 5,776.26.
    expect(r.perInstallment).toEqual([
      { index: 0, interest: 0, principal: 5776.26 },
    ]);
  });

  it("settles the final instalment on its odd 8,776.27 total", () => {
    // The last row carries the drift, so its total is a centavo above the
    // other five. Paying that exact figure must clear it and leave nothing.
    const r = allocatePayment(8776.27, [
      { interestDue: 129.7, principalDue: 8646.57 },
    ]);
    expect(r.interest).toBe(129.7);
    expect(r.principal).toBe(8646.57);
    expect(r.overpayment).toBe(0);
  });
});

describe("allocatePayment — a centavo short", () => {
  /*
   * ₱8,776.25 — one centavo under instalment 1's total.
   *   #1 interest  750.00   → remaining 8,026.25
   *   #1 principal 8,026.25 (min of 8,026.25 and 8,026.26) → remaining 0.00
   * The instalment is left owing exactly ₱0.01 of principal.
   */
  it("allocates every centavo it was given and leaves 0.01 owing", () => {
    const r = allocatePayment(8776.25, fresh());

    expect(r.interest).toBe(750.0);
    expect(r.principal).toBe(8026.25);
    expect(r.overpayment).toBe(0);
    expect(r.perInstallment).toEqual([
      { index: 0, interest: 750.0, principal: 8026.25 },
    ]);

    // The shortfall, stated as a figure rather than implied.
    expect(Math.round((8026.26 - r.principal) * 100) / 100).toBe(0.01);
  });

  it("is a centavo short of the whole book too", () => {
    // 52,657.56 against 52,657.57. The last instalment ends one centavo shy
    // on principal; nothing spills into overpayment.
    const r = allocatePayment(TOTAL_DUE - 0.01, fresh());

    expect(r.interest).toBe(TOTAL_INTEREST);
    expect(r.principal).toBe(49_999.99);
    expect(r.overpayment).toBe(0);
    expect(r.perInstallment[5]).toEqual({
      index: 5,
      interest: 129.7,
      principal: 8646.56,
    });
  });
});

describe("allocatePayment — edges the §26 rewrite must not disturb", () => {
  it("a zero payment produces no slices at all", () => {
    // `remaining <= 0` breaks before the first instalment is examined.
    const r = allocatePayment(0, fresh());
    expect(r).toEqual({
      interest: 0,
      principal: 0,
      overpayment: 0,
      perInstallment: [],
    });
  });

  it("an empty schedule turns the whole payment into overpayment", () => {
    // The written-off-loan and never-scheduled cases both arrive here.
    const r = allocatePayment(2_500, []);
    expect(r).toEqual({
      interest: 0,
      principal: 0,
      overpayment: 2_500,
      perInstallment: [],
    });
  });

  it("steps over a fully-settled row and pays the one behind it", () => {
    // `continue`, not `break`. If this ever became `break`, a borrower with
    // one settled row early in the schedule would stop being able to pay.
    const r = allocatePayment(1_000, [
      {
        interestDue: 750.0,
        principalDue: 8026.26,
        interestPaid: 750.0,
        principalPaid: 8026.26,
      },
      { interestDue: 629.61, principalDue: 8146.65 },
    ]);

    expect(r.interest).toBe(629.61);
    expect(r.principal).toBe(370.39);
    expect(r.perInstallment).toEqual([
      { index: 1, interest: 629.61, principal: 370.39 },
    ]);
  });

  it("clamps an over-credited row to zero rather than inflating the next slice", () => {
    // A repair script or manual edit can leave paid > due. Without the
    // `max(0, …)` the negative headroom would be handed to instalment 2.
    const r = allocatePayment(1_000, [
      {
        interestDue: 750.0,
        principalDue: 8026.26,
        interestPaid: 900.0,
        principalPaid: 8500.0,
      },
      { interestDue: 629.61, principalDue: 8146.65 },
    ]);

    expect(r.interest).toBe(629.61);
    expect(r.principal).toBe(370.39);
    expect(r.interest + r.principal).toBe(1_000);
  });
});
