#!/usr/bin/env node
/**
 * PSGC dataset ingestion — generates psgc-cities.generated.ts and
 * psgc-barangays.generated.ts from the official PSA publication.
 *
 * The bundled libs/shared-utils/src/lib/psgc.ts currently ships a
 * curated subset (60 cities, ~75 barangays). To switch to the full
 * dataset:
 *
 *   1. Download the latest PSA PSGC publication (CSV):
 *      https://psa.gov.ph/classification/psgc
 *      Save as ./data/psgc.csv (gitignored).
 *
 *      The CSV must have these columns (PSA publication format,
 *      Q4 2024 schema):
 *
 *        10-digit PSGC Code, Name, Correspondence Code, Geographic Level,
 *        Old names, City Class, Income Classification, Urban / Rural,
 *        2020 Population, Status
 *
 *      "Geographic Level" is one of Reg / Prov / Mun / City / SubMun / Bgy.
 *
 *   2. From the repo root:
 *        node scripts/ingest-psgc.mjs ./data/psgc.csv
 *
 *   3. The script writes two files alongside the curated dataset:
 *        libs/shared-utils/src/lib/psgc-cities.generated.ts
 *        libs/shared-utils/src/lib/psgc-barangays.generated.ts
 *
 *   4. Update libs/shared-utils/src/lib/psgc.ts to re-export the
 *      generated arrays instead of (or in addition to) the curated
 *      starter set. Suggested pattern:
 *
 *        export { PSGC_CITIES } from './psgc-cities.generated.js';
 *        export { PSGC_BARANGAYS } from './psgc-barangays.generated.js';
 *
 *      The cascade helpers (citiesForProvince, barangaysForCity, etc.)
 *      keep working untouched because they operate by code/name.
 *
 *   5. Commit the generated files. Bundle size impact: ~150 KB gzipped.
 *      If that's too heavy for the customer modal, switch to a lazy
 *      dynamic import in CustomerProfileForm so the data only loads
 *      when the modal opens.
 *
 * This script is intentionally I/O light — pure parse + emit, no
 * Prisma writes, no network. The PSA CSV is small enough (~3 MB
 * uncompressed) that streaming isn't necessary; we read it into
 * memory in one pass.
 */

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUT_DIR = join(REPO_ROOT, "libs/shared-utils/src/lib");

const HEADER = `// AUTO-GENERATED by scripts/ingest-psgc.mjs. Do not hand-edit.
// Source: PSA PSGC publication, ingested via \`node scripts/ingest-psgc.mjs\`.
// To refresh: re-run the script with the latest PSGC CSV.

`;

const usage = `Usage: node scripts/ingest-psgc.mjs <path-to-psgc.csv>
       node scripts/ingest-psgc.mjs ./data/psgc.csv`;

async function main() {
  const csvPath = process.argv[2];
  if (!csvPath) {
    console.error(usage);
    process.exit(1);
  }

  const raw = await readFile(resolve(REPO_ROOT, csvPath), "utf8");
  const lines = raw.split(/\r?\n/).filter((l) => l.trim().length > 0);
  if (lines.length < 2) {
    console.error("CSV looks empty.");
    process.exit(1);
  }

  // First line is the PSA header row; we don't actually rely on the
  // column names since they vary by publication year. We rely on
  // positional fields: code (0), name (1), level (3).
  const data = lines.slice(1);

  /** @type {Array<{code: string, name: string, level: string}>} */
  const rows = data
    .map((line) => parseCsvLine(line))
    .filter((cols) => cols.length >= 4)
    .map((cols) => ({
      code: cols[0].trim(),
      name: cols[1].trim().replace(/"/g, ""),
      level: cols[3].trim(),
    }));

  // PSGC codes are hierarchical:
  //   Region:    1300000000   (first 2 digits)
  //   Province:  0102800000   (next 2)
  //   City/Mun:  0102801000   (next 3)
  //   Barangay:  010280100001 (last 3 / 5 depending on length)
  // We derive parent codes by zeroing out the right segments.

  const cities = [];
  const barangays = [];

  for (const r of rows) {
    if (r.level === "City" || r.level === "Mun" || r.level === "SubMun") {
      const regionCode = r.code.slice(0, 2) + "00000000";
      const provinceCode = r.code.slice(0, 4) + "000000";
      cities.push({
        code: r.code,
        name: r.name,
        provinceCode,
        regionCode,
        // PSA flags capital status separately; not all CSVs include it.
        // Defaulting to false; can be improved with a separate capitals
        // list if the publication exposes one.
        isCapital: false,
      });
    } else if (r.level === "Bgy") {
      // Barangay codes are typically 9–12 digits; the city portion is
      // the first 10. Truncate to derive the parent.
      const cityCode = r.code.slice(0, 10).padEnd(10, "0");
      barangays.push({
        code: r.code,
        name: r.name,
        cityCode,
      });
    }
  }

  console.log(`Parsed ${cities.length} cities, ${barangays.length} barangays.`);

  const citiesOut =
    HEADER +
    `import type { PsgcCity } from './psgc.js';\n\n` +
    `export const PSGC_CITIES_FULL: ReadonlyArray<PsgcCity> = ${stringify(cities)};\n`;

  const brgyOut =
    HEADER +
    `import type { PsgcBarangay } from './psgc.js';\n\n` +
    `export const PSGC_BARANGAYS_FULL: ReadonlyArray<PsgcBarangay> = ${stringify(barangays)};\n`;

  await writeFile(join(OUT_DIR, "psgc-cities.generated.ts"), citiesOut, "utf8");
  await writeFile(
    join(OUT_DIR, "psgc-barangays.generated.ts"),
    brgyOut,
    "utf8",
  );

  console.log(`\nWrote:`);
  console.log(`  ${join(OUT_DIR, "psgc-cities.generated.ts")}`);
  console.log(`  ${join(OUT_DIR, "psgc-barangays.generated.ts")}`);
  console.log(`\nNext step: update libs/shared-utils/src/lib/psgc.ts to`);
  console.log(`re-export PSGC_CITIES_FULL / PSGC_BARANGAYS_FULL — see the`);
  console.log(`header comment in scripts/ingest-psgc.mjs for the pattern.`);
}

/**
 * Lightweight CSV line splitter. Handles quoted cells with embedded
 * commas; doesn't try to be RFC 4180 perfect — PSA CSVs are well-formed.
 */
function parseCsvLine(line) {
  const out = [];
  let cur = "";
  let inQuote = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuote) {
      if (ch === '"' && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else if (ch === '"') {
        inQuote = false;
      } else {
        cur += ch;
      }
    } else if (ch === '"') {
      inQuote = true;
    } else if (ch === ",") {
      out.push(cur);
      cur = "";
    } else {
      cur += ch;
    }
  }
  out.push(cur);
  return out;
}

/** Stable, deterministic JSON-style emit so generated files diff cleanly. */
function stringify(arr) {
  if (arr.length === 0) return "[]";
  const sorted = [...arr].sort((a, b) => a.code.localeCompare(b.code));
  const lines = sorted.map((row) => {
    const entries = Object.entries(row)
      .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
      .join(", ");
    return `  { ${entries} }`;
  });
  return `[\n${lines.join(",\n")},\n]`;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
