import { describe, expect, it } from "vitest";

import {
  computeAmortizationFor,
  installmentCount,
  monthlyPayment,
} from "./index";

/**
 * Golden financial corpus — Phase 2.2 of docs/modernization/roadmap.md.
 *
 * READ THIS BEFORE CHANGING A NUMBER IN THIS FILE.
 *
 * The brief (§81/§82) forbids changing a financial calculation without a
 * corpus to reconcile against, and it is right: the arithmetic in this
 * repository may be accountingly and contractually significant, and "it
 * reads better" is not a reason to risk a borrower's schedule.
 *
 * The file has two halves, and they carry very different authority:
 *
 * 1. VERIFIED — values derived from closed-form finance, independently
 *    of this implementation. First-period interest is principal ×
 *    period rate. Flat interest is principal × annual rate × years. The
 *    declining payment is the standard annuity formula. If the code
 *    disagrees with these, the CODE is wrong.
 *
 * 2. CHARACTERIZATION — schedule fingerprints captured from the current
 *    implementation on 11 Aug 2026. These do NOT prove correctness.
 *    They prove that behaviour has not CHANGED, which is exactly what a
 *    refactor needs and exactly what a bug report does not care about.
 *    If one of these fails after a deliberate change, the number may be
 *    updated — but only with a written reason in the commit, and only
 *    after checking the VERIFIED half still passes.
 *
 * A note on where these came from: they were generated by running this
 * implementation, not supplied by the business. Anything the closed-form
 * checks below do not cover is therefore "what the system does today",
 * not "what the cooperative's loan agreements promise". Replacing the
 * characterization values with worked examples from real signed loan
 * documents would be a strict upgrade, and is the one thing that would
 * make this corpus authoritative rather than merely protective.
 */

const r2 = (n: number) => Math.round(n * 100) / 100;

interface Scenario {
  id: string;
  label: string;
  principal: number;
  annual: number;
  termMonths: number;
  method: "DECLINING" | "FLAT";
  frequency: "MONTHLY" | "BIWEEKLY" | "WEEKLY";
}

/** Shapes drawn from the products the system actually offers. */
const SCENARIOS: Scenario[] = [
  {
    id: "salary-declining-monthly",
    label: "Salary loan, ₱50k over 2y at 18% declining",
    principal: 50_000,
    annual: 0.18,
    termMonths: 24,
    method: "DECLINING",
    frequency: "MONTHLY",
  },
  {
    id: "salary-flat-monthly",
    label: "Salary loan, ₱50k over 1y at 12% flat",
    principal: 50_000,
    annual: 0.12,
    termMonths: 12,
    method: "FLAT",
    frequency: "MONTHLY",
  },
  {
    id: "auto-declining-monthly",
    label: "Auto loan, ₱800k over 5y at 9.5% declining",
    principal: 800_000,
    annual: 0.095,
    termMonths: 60,
    method: "DECLINING",
    frequency: "MONTHLY",
  },
  {
    id: "motorcycle-flat-monthly",
    label: "Motorcycle, ₱120k over 3y at 24% flat",
    principal: 120_000,
    annual: 0.24,
    termMonths: 36,
    method: "FLAT",
    frequency: "MONTHLY",
  },
  {
    id: "housing-declining-monthly",
    label: "Housing, ₱2.5M over 20y at 7% declining",
    principal: 2_500_000,
    annual: 0.07,
    termMonths: 240,
    method: "DECLINING",
    frequency: "MONTHLY",
  },
  {
    id: "micro-declining-weekly",
    label: "Micro, ₱20k over 6m at 30% declining, weekly",
    principal: 20_000,
    annual: 0.3,
    termMonths: 6,
    method: "DECLINING",
    frequency: "WEEKLY",
  },
  {
    id: "salary-declining-biweekly",
    label: "Salary, ₱35k over 1y at 15% declining, bi-weekly",
    principal: 35_000,
    annual: 0.15,
    termMonths: 12,
    method: "DECLINING",
    frequency: "BIWEEKLY",
  },
  {
    id: "zero-rate-declining",
    label: "Zero-interest, ₱12k over 1y",
    principal: 12_000,
    annual: 0,
    termMonths: 12,
    method: "DECLINING",
    frequency: "MONTHLY",
  },
];

const periodsPerYearFor = (f: Scenario["frequency"]) =>
  f === "MONTHLY" ? 12 : f === "BIWEEKLY" ? 26 : 52;

const build = (s: Scenario) =>
  computeAmortizationFor(s.principal, s.annual, s.termMonths, {
    method: s.method,
    frequency: s.frequency,
  });

// ─────────────────────────────────────────────────────────────────────
// 1. VERIFIED — closed-form, independent of this implementation
// ─────────────────────────────────────────────────────────────────────

describe("golden: values derivable without the implementation", () => {
  it.each(SCENARIOS)(
    "$label — first period charges interest on the full principal",
    (s) => {
      // The one interest figure that needs no amortization at all: at
      // installment 1 nothing has been repaid, so interest is simply
      // principal × the period rate.
      const periodRate = s.annual / periodsPerYearFor(s.frequency);
      const rows = build(s);
      if (s.method === "DECLINING") {
        expect(rows[0]!.interest).toBe(r2(s.principal * periodRate));
      }
    },
  );

  it.each(SCENARIOS.filter((s) => s.method === "FLAT"))(
    "$label — flat interest is principal × rate × years",
    (s) => {
      // Add-on interest, the PH standard for motorcycle and small salary
      // lending: computed once on the original principal and split
      // evenly, never recomputed on the declining balance.
      const years = s.termMonths / 12;
      const expected = r2(s.principal * s.annual * years);
      const actual = r2(build(s).reduce((a, x) => a + x.interest, 0));
      expect(actual).toBe(expected);
    },
  );

  it.each(SCENARIOS.filter((s) => s.method === "DECLINING" && s.annual > 0))(
    "$label — instalment matches the annuity formula",
    (s) => {
      // P·r·(1+r)^n / ((1+r)^n − 1), computed here rather than read from
      // the implementation, so the two must independently agree.
      const n = installmentCount(s.termMonths, s.frequency);
      const r = s.annual / periodsPerYearFor(s.frequency);
      const expected = r2(
        (s.principal * r * Math.pow(1 + r, n)) / (Math.pow(1 + r, n) - 1),
      );
      const first = build(s)[0]!;
      // The first instalment is the un-trued-up one, so it equals the
      // formula exactly; the last absorbs the rounding drift.
      expect(Math.abs(first.payment - expected)).toBeLessThanOrEqual(0.01);
      expect(r2(monthlyPayment(s.principal, r, n))).toBe(expected);
    },
  );

  it.each(SCENARIOS)(
    "$label — principal repays exactly, no more, no less",
    (s) => {
      /*
       * The invariant with real money behind it. The loan is booked to
       * Loans Receivable at full principal on disbursement, so if the
       * ROUNDED rows do not sum to the principal, a borrower who pays
       * every instalment in full still leaves a residual on the
       * receivable — a debt that can never be settled.
       */
      const total = r2(build(s).reduce((a, x) => a + x.principal, 0));
      expect(total).toBe(s.principal);
    },
  );

  it.each(SCENARIOS)("$label — every row's payment is its parts", (s) => {
    for (const row of build(s)) {
      expect(row.payment).toBe(r2(row.principal + row.interest));
      expect(row.principal).toBeGreaterThanOrEqual(0);
      expect(row.interest).toBeGreaterThanOrEqual(0);
    }
  });

  it.each(SCENARIOS)("$label — instalment count follows the frequency", (s) => {
    // Weekly is term × 52/12, bi-weekly × 26/12, rounded. A borrower on
    // a 6-month weekly loan pays 26 times, not 24.
    expect(build(s)).toHaveLength(installmentCount(s.termMonths, s.frequency));
  });

  it("declining interest falls every period; flat does not", () => {
    const declining = build(SCENARIOS[0]!);
    for (let i = 1; i < declining.length; i++) {
      expect(declining[i]!.interest).toBeLessThanOrEqual(
        declining[i - 1]!.interest,
      );
    }
    const flat = build(SCENARIOS[1]!);
    for (const row of flat) {
      expect(row.interest).toBe(flat[0]!.interest);
    }
  });
});

// ─────────────────────────────────────────────────────────────────────
// 2. CHARACTERIZATION — captured 11 Aug 2026. Behaviour, not truth.
// ─────────────────────────────────────────────────────────────────────

interface Fingerprint {
  installments: number;
  totalPrincipal: number;
  totalInterest: number;
  totalPayment: number;
  first: { principal: number; interest: number; payment: number };
  last: { principal: number; interest: number; payment: number };
}

const GOLDEN: Record<string, Fingerprint> = {
  "salary-declining-monthly": {
    installments: 24,
    totalPrincipal: 50_000,
    totalInterest: 9_908.93,
    totalPayment: 59_908.93,
    first: { principal: 1_746.21, interest: 750, payment: 2_496.21 },
    last: { principal: 2_459.31, interest: 36.89, payment: 2_496.2 },
  },
  "salary-flat-monthly": {
    installments: 12,
    totalPrincipal: 50_000,
    totalInterest: 6_000,
    totalPayment: 56_000,
    first: { principal: 4_166.67, interest: 500, payment: 4_666.67 },
    last: { principal: 4_166.63, interest: 500, payment: 4_666.63 },
  },
  "auto-declining-monthly": {
    installments: 60,
    totalPrincipal: 800_000,
    totalInterest: 208_089.34,
    totalPayment: 1_008_089.34,
    first: { principal: 10_468.16, interest: 6_333.33, payment: 16_801.49 },
    last: { principal: 16_669.54, interest: 131.97, payment: 16_801.51 },
  },
  "motorcycle-flat-monthly": {
    installments: 36,
    totalPrincipal: 120_000,
    totalInterest: 86_400,
    totalPayment: 206_400,
    first: { principal: 3_333.33, interest: 2_400, payment: 5_733.33 },
    last: { principal: 3_333.45, interest: 2_400, payment: 5_733.45 },
  },
  "housing-declining-monthly": {
    installments: 240,
    totalPrincipal: 2_500_000,
    totalInterest: 2_151_793.58,
    totalPayment: 4_651_793.58,
    first: { principal: 4_799.14, interest: 14_583.33, payment: 19_382.47 },
    last: { principal: 19_270.09, interest: 112.41, payment: 19_382.5 },
  },
  "micro-declining-weekly": {
    installments: 26,
    totalPrincipal: 20_000,
    totalInterest: 1_595.01,
    totalPayment: 21_595.01,
    first: { principal: 715.19, interest: 115.38, payment: 830.57 },
    last: { principal: 825.79, interest: 4.76, payment: 830.55 },
  },
  "salary-declining-biweekly": {
    installments: 26,
    totalPrincipal: 35_000,
    totalInterest: 2_791.27,
    totalPayment: 37_791.27,
    first: { principal: 1_251.59, interest: 201.92, payment: 1_453.51 },
    last: { principal: 1_445.18, interest: 8.34, payment: 1_453.52 },
  },
  "zero-rate-declining": {
    installments: 12,
    totalPrincipal: 12_000,
    totalInterest: 0,
    totalPayment: 12_000,
    first: { principal: 1_000, interest: 0, payment: 1_000 },
    last: { principal: 1_000, interest: 0, payment: 1_000 },
  },
};

describe("golden: schedules have not changed", () => {
  it.each(SCENARIOS)("$label", (s) => {
    const expected = GOLDEN[s.id]!;
    const rows = build(s);
    const first = rows[0]!;
    const lastRow = rows[rows.length - 1]!;

    expect({
      installments: rows.length,
      totalPrincipal: r2(rows.reduce((a, x) => a + x.principal, 0)),
      totalInterest: r2(rows.reduce((a, x) => a + x.interest, 0)),
      totalPayment: r2(rows.reduce((a, x) => a + x.payment, 0)),
      first: {
        principal: first.principal,
        interest: first.interest,
        payment: first.payment,
      },
      last: {
        principal: lastRow.principal,
        interest: lastRow.interest,
        payment: lastRow.payment,
      },
    }).toEqual(expected);
  });

  it("every scenario is covered — no silent gaps in the corpus", () => {
    // A corpus that quietly stops covering a product is worse than no
    // corpus: it still reads as protection.
    expect(Object.keys(GOLDEN).sort()).toEqual(
      SCENARIOS.map((s) => s.id).sort(),
    );
  });
});
